DROP PROCEDURE TYJINFWLIB.SMS_TSHORTURLF_ADD;

CREATE PROCEDURE TYJINFWLIB.SMS_TSHORTURLF_ADD 
(
	    IN P_WSEQ       VARCHAR(10) , 
		IN P_WLONGURL   VARCHAR(200) , 
		IN P_WSHORTURL  VARCHAR(50)  
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_TSHORTURLF_ADD
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	

		INSERT INTO TYSCMLIB.TSHORTURLF(
             WSEQ,
             WLONGURL,
             WSHORTURL)
        VALUES(
             P_WSEQ,
             P_WLONGURL,
             P_WSHORTURL
			 );

END P1