DROP PROCEDURE TYJINFWLIB.SMS_TB_USER_RUN;

CREATE PROCEDURE TYJINFWLIB.SMS_TB_USER_RUN
( 
    IN P_COMPANYCODE  VARCHAR(4),
	IN P_LOGINID      VARCHAR(9),
    IN P_PASSWORD     VARCHAR(100)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (
            SELECT  COMPANYCODE, EMPID 
            FROM GWSCMLIB.TB_USER
            WHERE  COMPANYCODE = P_COMPANYCODE
               AND LOGINID = P_LOGINID
            )
            SELECT  A.EMPID, A.PASSWORD
            FROM GWSCMLIB.TB_PASSWORD A
            WHERE A.EMPID =  ( SELECT EMPID FROM TABLE1 )
                 AND A.PASSWORD = P_PASSWORD;
		
	OPEN REFCURSOR;

END