DROP PROCEDURE TYJINFWLIB.SMS_ADMASTA_LIST;

CREATE PROCEDURE TYJINFWLIB.SMS_ADMASTA_LIST
( 
	
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (		
				
				SELECT DISTINCT
					1 AS LVL,
					CAST(0 AS VARCHAR(4)) AS UP_MENU_NO,
					CAST(ADMGROUP AS VARCHAR(13)) AS MENU_NO,
					ADMGRNAME AS MENU_NAME
					FROM TYSCMLIB.PSM_SMSManager_ADMASTA
					WHERE ADMGROUP NOT IN('0')
			 )
			 SELECT *
			 FROM TABLE1
  			 ORDER BY LVL, UP_MENU_NO;
		
	OPEN REFCURSOR;

END