DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_LOGDETAIL_ADD;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_LOGDETAIL_ADD 
(
	 IN P_LODDATE    VARCHAR (10) , 
	 IN	P_LODSEQ     VARCHAR (3) , 
	 IN	P_LODRECTEL  VARCHAR (13) , 
	 IN	P_LODRECSAB  VARCHAR (9) , 
	 IN	P_LODRECDAT  VARCHAR (10) , 
	 IN	P_LODRECTIM  VARCHAR (8) , 
	 IN	P_LODTIME    VARCHAR (8) ,  
	 IN	P_LODSMSCODE VARCHAR (6) ,  
	 IN	P_LODSMSMESSAGE VARCHAR (200),
	 IN P_LODHISAB   VARCHAR (9)   
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_LOGDETAIL_ADD
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	INSERT INTO TYSCMLIB.PSM_SMSManager_LOGDETAIL(
	  LODDATE, LODSEQ, LODRECTEL, LODRECSAB, LODRECDAT, LODRECTIM,  LODTIME, LODSMSCODE, LODSMSMESSAGE, LODHIGB, LODHIDAT, LODHITIM, LODHISAB
	 )
    VALUES
		(
		P_LODDATE, 
		P_LODSEQ, 
		P_LODRECTEL, 
		P_LODRECSAB, 
		P_LODRECDAT,
		P_LODRECTIM,
		P_LODTIME, 
		P_LODSMSCODE, 
		P_LODSMSMESSAGE,
		'A',
		CURRENT DATE,
		CURRENT TIME,
		P_LODHISAB
		);

END P1