--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SMS_SMSManagerLogDetail_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SMS_SMSManagerLogDetail_LIST ( 
	IN P_LODDATE   VARCHAR(10),
	IN P_LODSEQ    VARCHAR(8)
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SMS_SMSManagerLogDetail_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 

  
  
MAIN : BEGIN  -- 실행부 

    

	    
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS (
				   SELECT
						ROWNUMBER() OVER(ORDER BY KBHANGL) AS ROWNO,
						LODDATE,
						LODSEQ,
						LODRECTEL,
						LODRECSAB,
						KBHANGL,
						LODTIME,
						LODSMSCODE,
						LODSMSMESSAGE,
						LODHIGB,
						CASE WHEN LODHIGB = 'C' THEN 'Y' ELSE '' END AS LODCHECK,
						LODRECDAT,
						CASE WHEN LODRECTIM <> '' THEN  SUBSTR(LODRECTIM ,1,2) || ':' || SUBSTR(LODRECTIM ,4,2) || ':' || SUBSTR(LODRECTIM ,7,2) ELSE '' END AS LODRECTIM,
						LODHIDAT,
						LODHITIM,
						LODHISAB,
                                                (SELECT COUNT(*) FROM TYSCMLIB.PSM_SMSManager_LOGDETAIL B
								WHERE B.LODDATE = A.LODDATE
								AND B.LODSEQ = A.LODSEQ
								AND B.LODRECDAT != ''  ) AS CHKCNT,
						(SELECT COUNT(*) FROM TYSCMLIB.PSM_SMSManager_LOGDETAIL B
								WHERE B.LODDATE = A.LODDATE
								AND B.LODSEQ = A.LODSEQ
								AND B.LODRECDAT = ''  ) AS UNCHKCNT,
						(SELECT COUNT(*) FROM TYSCMLIB.PSM_SMSManager_LOGDETAIL B
								WHERE B.LODDATE = A.LODDATE
								AND B.LODSEQ = A.LODSEQ
									) AS TOTALCNT
						FROM TYSCMLIB.PSM_SMSManager_LOGDETAIL A
						LEFT OUTER JOIN TYSCMLIB.INKIBNMF
						ON KBSABUN = LODRECSAB
						WHERE LODDATE = P_LODDATE
						AND LODSEQ = P_LODSEQ
						ORDER BY LODDATE, LODSEQ, KBHANGL			
				)
				SELECT
					    ROWNO,
						LODDATE,
						LODSEQ,
						LODRECTEL,
						LODRECSAB,
						KBHANGL,
						LODTIME,
						LODSMSCODE,
						LODSMSMESSAGE,
						LODHIGB,
						LODCHECK,
						LODRECDAT,
						LODRECTIM,
						LODHIDAT,
						LODHITIM,
						LODHISAB,
						CHKCNT,
						UNCHKCNT,
						TOTALCNT
				FROM ORIGINAL_DATA
				ORDER BY ROWNO ASC;

			OPEN REFCURSOR ;

				


END MAIN ; 
END  ;
