--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SMS_SMSMANAGER_FORMCODE_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SMS_SMSMANAGER_FORMCODE_LIST (    
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SMS_SMSMANAGER_FORMCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = TYSCMLIB , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 

  
MAIN : BEGIN  -- 실행부 

      LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			
		   SELECT
                  FORMCODE AS GUBNCODE,
                  FORMNAME AS GUBNNAME
           FROM TYSCMLIB.PSM_SMSMANAGER_FORMCODE
           ORDER BY FORMCODE;
			
		OPEN REFCURSOR ;

	END LIST ; 

END MAIN ; 
END  ;




