--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_FORM_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_FORM_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
    IN P_SMSGUBN  VARCHAR(3),
	IN P_SMSSEQ   VARCHAR(3)
) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SMS_SMSManager_FORM_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 

	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 

    

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS (
				   SELECT
						                ROWNUMBER() OVER(ORDER BY SMSSEQ) AS ROWNO,
										'선 택' as CHK,
										SMSGUBN,
										FORMNAME AS SMSGUBNNM,
										SMSSEQ,
										SMSCONTENT,
										SMSETC,
										SMSHIGB,
										SMSHIDAT,
										SMSHITIM,
										SMSHISAB
										FROM TYSCMLIB.PSM_SMSManager_FORM
										LEFT OUTER JOIN TYSCMLIB.PSM_SMSMANAGER_FORMCODE
										ON SMSGUBN = FORMCODE
										WHERE SMSGUBN LIKE P_SMSGUBN||'%'
										AND    SMSSEQ LIKE P_SMSSEQ||'%'	
				)
				SELECT
					    ROWNO,
						CHK,
						SMSGUBN,
						SMSGUBNNM,
						SMSSEQ,
						SMSCONTENT,
						SMSETC,
						SMSHIGB,
						SMSHIDAT,
						SMSHITIM,
						SMSHISAB
				FROM ORIGINAL_DATA
				WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
				ORDER BY ROWNO ASC;

			OPEN REFCURSOR ;

		END LIST ; 
	  
		PAGING : BEGIN  -- 페이징 					

				DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
				
				WITH ORIGINAL_DATA AS (
				    SELECT
						ROWNUMBER() OVER(ORDER BY SMSSEQ) AS ROWNO,						               
										SMSGUBN,
										FORMNAME AS SMSGUBNNM,
										SMSSEQ,
										SMSCONTENT,
										SMSETC,
										SMSHIGB,
										SMSHIDAT,
										SMSHITIM,
										SMSHISAB
										FROM TYSCMLIB.PSM_SMSManager_FORM
										LEFT OUTER JOIN TYSCMLIB.PSM_SMSMANAGER_FORMCODE
										ON SMSGUBN = FORMCODE
										WHERE SMSGUBN LIKE P_SMSGUBN||'%'
										AND    SMSSEQ LIKE P_SMSSEQ||'%'				
				)				
				SELECT
					COUNT(*) AS TOTALCOUNT
				FROM ORIGINAL_DATA;

				OPEN REFCURSOR2 ;

		END PAGING ; 


END MAIN ; 
END  ;
