DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_ADDETAIL_DEL;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_ADDETAIL_DEL
(
	IN P_ADDGROUP       VARCHAR (2) ,
	IN P_ADDSABUN       VARCHAR (9) 
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_ADDETAIL_DEL
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
		DELETE FROM TYSCMLIB.PSM_SMSManager_ADDETAIL 
		WHERE ADDSABUN = P_ADDSABUN
		 AND  ADDGROUP = P_ADDGROUP ; 				

END P1