DROP PROCEDURE TYJINFWLIB.SMS_TB_PASSWORD_RUN;

CREATE PROCEDURE TYJINFWLIB.SMS_TB_PASSWORD_RUN
( 
    IN P_COMPANYCODE  VARCHAR(4),
	IN P_EMPID        VARCHAR(9),
    IN P_PASSWORD     VARCHAR(100)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT  EMPID, KBSABUN, KBMAILID, PASSWORD
        FROM GWSCMLIB.TB_PASSWORD
        LEFT OUTER JOIN TYSCMLIB.INKIBNMF
              ON KBSABUN = EMPID
        WHERE    COMPANYCODE = P_COMPANYCODE
          AND    EMPID = P_EMPID
          AND    (CASE WHEN P_PASSWORD = '' THEN '' ELSE PASSWORD END)
          =
                    (CASE WHEN P_PASSWORD = '' THEN '' ELSE P_PASSWORD END);
		
	OPEN REFCURSOR;

END;