--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SMS_SMSManagerLog_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SMS_SMSManagerLog_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE    VARCHAR(8),
	IN P_EDATE    VARCHAR(8),
	IN P_TEAM     VARCHAR(1),
	IN P_SABUN    VARCHAR(6),
    IN P_SMSGUBN  VARCHAR(1)	
	) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SMS_SMSManagerLog_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 

	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 

    

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS (
				   SELECT
				    ROW_NUMBER() OVER(ORDER BY LOMDATE DESC, LOMTIME DESC) AS ROWNO,
					LOMDATE,
					LOMSEQ,
					LOMSMSGUBN,
					CASE WHEN LOMSMSGUBN ='1' THEN '일반' ELSE '비상'
								END LOMSMSGUBNNM,
					LOMLOCAT,
					CASE WHEN LOMLOCAT ='1' THEN 'PSM 관리' 
						WHEN LOMLOCAT = '2' THEN '모바일' 
						WHEN LOMLOCAT = '3' THEN 'S정문' 
						WHEN LOMLOCAT = '4' THEN 'T상단지' 
						WHEN LOMLOCAT = '5' THEN 'T하단지' ELSE 'T해안단지'
								END LOMLOCATNM,
					LOMTEAM,
					TYSCMLIB.SF_GB_ORGNAME( LOMTEAM,SUBSTR(LOMDATE,1,4)||SUBSTR(LOMDATE,6,2)||SUBSTR(LOMDATE,9,2)) AS LOMTEAMNM,
					LOMSENDTEL,
					LOMSABUN,
					KBHANGL,
					LOMTIME,
					LOMCONTENT,
					(  SELECT  COUNT(*) AS CNT  FROM TYSCMLIB.PSM_SMSMANAGER_LOGDETAIL
                       WHERE LODDATE = LOMDATE
                         AND LODSEQ = LOMSEQ ) AS SMSCNT
					FROM TYSCMLIB.PSM_SMSManager_LOGMASTA
					LEFT OUTER JOIN TYSCMLIB.INKIBNMF
					ON KBSABUN = LOMSABUN
					WHERE REPLACE(LOMDATE,'-','') BETWEEN P_SDATE AND P_EDATE
					AND SUBSTR(LOMTEAM,1,1) LIKE P_TEAM||'%'
					AND LOMSABUN LIKE P_SABUN||'%'
					AND LOMSMSGUBN LIKE P_SMSGUBN||'%'
					ORDER BY LOMDATE DESC, LOMTIME DESC 				
				)
				SELECT
					ROWNO,
					LOMDATE,
					LOMSEQ,
					LOMSMSGUBN,
					LOMSMSGUBNNM,
					LOMLOCAT,
					LOMLOCATNM,
					LOMTEAM,
					LOMTEAMNM,
					LOMSENDTEL,
					LOMSABUN,
					KBHANGL,
					LOMTIME,
					LOMCONTENT,
				    ( SELECT VALUE(SUM(SMSCNT),0) FROM ORIGINAL_DATA WHERE LOMSMSGUBN = '1' ) AS STCNT,
                    ( SELECT VALUE(SUM(SMSCNT),0) FROM ORIGINAL_DATA WHERE LOMSMSGUBN = '2' ) AS EMCNT,
                    ( SELECT VALUE(SUM(SMSCNT),0)  FROM ORIGINAL_DATA  ) AS TOTALCNT
				FROM ORIGINAL_DATA
				WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
				ORDER BY ROWNO ASC;

			OPEN REFCURSOR ;

		END LIST ; 
	  
		PAGING : BEGIN  -- 페이징 					

				DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
				
				WITH ORIGINAL_DATA AS (
				   SELECT
				    ROW_NUMBER() OVER(ORDER BY LOMDATE DESC, LOMTIME DESC) AS ROWNO,
					LOMDATE,
					LOMSEQ,
					LOMSMSGUBN,
					CASE WHEN LOMSMSGUBN ='1' THEN '일반' ELSE '비상'
								END LOMSMSGUBNNM,
					LOMLOCAT,
					CASE WHEN LOMLOCAT ='1' THEN 'PSM 관리' 
						WHEN LOMLOCAT = '2' THEN '모바일' 
						WHEN LOMLOCAT = '3' THEN 'S정문' 
						WHEN LOMLOCAT = '4' THEN 'T상단지' 
						WHEN LOMLOCAT = '5' THEN 'T하단지' ELSE 'T해안단지'
								END LOMLOCATNM,
					LOMTEAM,
					TYSCMLIB.SF_GB_ORGNAME( LOMTEAM,SUBSTR(LOMDATE,1,4)||SUBSTR(LOMDATE,6,2)||SUBSTR(LOMDATE,9,2)) AS LOMTEAMNM,
					LOMSENDTEL,
					LOMSABUN,
					KBHANGL,
					LOMTIME,
					LOMCONTENT
					FROM TYSCMLIB.PSM_SMSManager_LOGMASTA
					LEFT OUTER JOIN TYSCMLIB.INKIBNMF
					ON KBSABUN = LOMSABUN
					WHERE REPLACE(LOMDATE,'-','') BETWEEN P_SDATE AND P_EDATE
					AND SUBSTR(LOMTEAM,1,1) LIKE P_TEAM||'%'
					AND LOMSABUN LIKE P_SABUN||'%'
					AND LOMSMSGUBN LIKE P_SMSGUBN||'%'
					ORDER BY LOMDATE DESC, LOMTIME DESC 				
				)				
				SELECT
					COUNT(*) AS TOTALCOUNT
				FROM ORIGINAL_DATA;

				OPEN REFCURSOR2 ;

		END PAGING ; 


END MAIN ; 
END  ;
