DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_FORM_ADD;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_FORM_ADD 
(
	 IN P_SMSGUBN     VARCHAR (2) ,
	 IN P_SMSSEQ      VARCHAR (3) ,
	 IN P_SMSCONTENT  VARCHAR (200) ,
	 IN P_SMSETC      VARCHAR (100) ,
	 IN P_SMSHISAB    VARCHAR (9) 	 
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_FORM_ADD
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	IF NOT EXISTS(	SELECT SMSGUBN FROM TYSCMLIB.PSM_SMSManager_FORM WHERE SMSGUBN = P_SMSGUBN AND SMSSEQ = P_SMSSEQ ) THEN

		INSERT INTO  TYSCMLIB.PSM_SMSManager_FORM
		(
			SMSGUBN, SMSSEQ, SMSCONTENT ,SMSETC, SMSHIGB, SMSHIDAT, SMSHITIM, SMSHISAB
		)
		VALUES
		(
		    P_SMSGUBN,
			(SELECT VALUE(MAX(SMSSEQ),0) + 1 
			 FROM TYSCMLIB.PSM_SMSManager_FORM
			 WHERE SMSGUBN = P_SMSGUBN
			 )  , 
			P_SMSCONTENT, 
			P_SMSETC,
			'A', 
			CURRENT_DATE, 
			CURRENT_TIME, 
			P_SMSHISAB
		);

	ELSE

		UPDATE TYSCMLIB.PSM_SMSManager_FORM 
		SET
			SMSCONTENT = P_SMSCONTENT, 
			SMSETC = P_SMSETC,
			SMSHIGB  = 'C' ,
			SMSHIDAT = CURRENT_DATE, 
			SMSHITIM = CURRENT_TIME, 
			SMSHISAB = P_SMSHISAB
		WHERE SMSGUBN = P_SMSGUBN
		  AND SMSSEQ  = P_SMSSEQ;

	END IF;	

END P1