DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_FORM_DEL;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_FORM_DEL 
(
	 IN P_SMSGUBN       VARCHAR (2) ,
	 IN P_SMSSEQ        VARCHAR (3) 
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_FORM_DEL
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	

		DELETE FROM TYSCMLIB.PSM_SMSManager_FORM 		
		WHERE SMSGUBN = P_SMSGUBN
		  AND SMSSEQ  = P_SMSSEQ;

	

END P1