DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_LOGMASTA_ADD;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_LOGMASTA_ADD 
(
	    IN P_LOMDATE     VARCHAR(10) , 
		IN P_LOMSEQ      VARCHAR(3) , 
		IN P_LOMLOCAT    VARCHAR(1) , 
		IN P_LOMTEAM     VARCHAR(6) ,  
		IN P_LOMSENDTEL  VARCHAR(13) ,  
		IN P_LOMSABUN    VARCHAR(9) ,  
		IN P_LOMTIME     VARCHAR(8) ,  
		IN P_LOMCONTENT  VARCHAR(200) ,  
		IN P_LOMSMSGUBN  VARCHAR(1) , 
	    IN P_LOMHISAB    VARCHAR (9) 	 
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_LOGMASTA_ADD
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	

		INSERT INTO  TYSCMLIB.PSM_SMSManager_LOGMASTA
		(
			LOMDATE, LOMSEQ, LOMLOCAT, LOMTEAM, LOMSENDTEL, LOMSABUN, LOMTIME, LOMCONTENT, LOMSMSGUBN, LOMHIGB, LOMHIDAT, LOMHITIM, LOMHISAB
		)
		VALUES
		(
			P_LOMDATE, 
			P_LOMSEQ, 
			P_LOMLOCAT, 
			P_LOMTEAM, 
			P_LOMSENDTEL, 
			P_LOMSABUN, 
			P_LOMTIME, 
			P_LOMCONTENT, 
			P_LOMSMSGUBN,
			'A', 
			CURRENT_DATE, 
			CURRENT_TIME, 
			P_LOMHISAB
		);	

END P1