DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_ADDETAIL_ADD;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_ADDETAIL_ADD 
(
	 IN P_ADDGROUP       VARCHAR (2) ,
	 IN P_ADDSABUN       VARCHAR (9) ,
	 IN P_ADDTEL         VARCHAR (13) ,
	 IN P_ADMHISAB       VARCHAR (9) 	 
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_ADDETAIL_ADD
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	IF NOT EXISTS(	SELECT ADDGROUP FROM TYSCMLIB.PSM_SMSManager_ADDETAIL WHERE ADDGROUP = P_ADDGROUP AND  ADDSABUN = P_ADDSABUN ) THEN

		INSERT INTO  TYSCMLIB.PSM_SMSManager_ADDETAIL 
		(
			ADDSABUN, ADDGROUP, ADDTEAM, ADDNAME, ADDTEL, ADDEMAIL, ADDBIGO, ADDHIGB, ADDHIDAT, ADDHITIM, ADDHISAB
		)
		VALUES
		(
			P_ADDSABUN  , 
			P_ADDGROUP  , 
			(SELECT KBBSTEAM FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = P_ADDSABUN ),
			(SELECT KBHANGL FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = P_ADDSABUN ),
			P_ADDTEL,
			'',
			'',
			'A', 
			CURRENT_DATE, 
			CURRENT_TIME, 
			P_ADMHISAB
		);

	ELSE

		UPDATE TYSCMLIB.PSM_SMSManager_ADDETAIL 
		SET ADDTEAM = (SELECT KBBUSEO FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = P_ADDSABUN ),
			ADDTEL = P_ADDTEL, 
			ADDHIGB  = 'C' ,
			ADDHIDAT = CURRENT_DATE, 
			ADDHITIM = CURRENT_TIME, 
			ADDHISAB = P_ADMHISAB
		WHERE ADDSABUN = P_ADDSABUN
		 AND  ADDGROUP = P_ADDGROUP ; 			

	END IF;	

END P1