DROP PROCEDURE TYJINFWLIB.SMS_SMSManager_ADMASTA_ADD;

CREATE PROCEDURE TYJINFWLIB.SMS_SMSManager_ADMASTA_ADD 
(
	 IN P_ADMGROUP       VARCHAR (20) ,
	 IN P_ADMGRNAME      VARCHAR (30) ,
	 IN P_ADMHISAB       VARCHAR (9) 	 
)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.SMS_SMSManager_ADMASTA_ADD
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
P1: BEGIN
	
	IF NOT EXISTS(	SELECT ADMGROUP FROM TYSCMLIB.PSM_SMSManager_ADMASTA WHERE ADMGROUP = P_ADMGROUP ) THEN

		INSERT INTO  TYSCMLIB.PSM_SMSManager_ADMASTA 
		(
			ADMGROUP, ADMGRNAME, ADMHIGB, ADMHIDAT, ADMHITIM, ADMHISAB
		)
		VALUES
		(
			(SELECT VALUE(MAX(ADMGROUP),0) + 1 FROM TYSCMLIB.PSM_SMSManager_ADMASTA)  , 
			P_ADMGRNAME, 
			'A', 
			CURRENT_DATE, 
			CURRENT_TIME, 
			P_ADMHISAB
		);

	ELSE

		UPDATE TYSCMLIB.PSM_SMSManager_ADMASTA 
		SET
			ADMGRNAME = P_ADMGRNAME, 
			ADMHIGB  = 'C' ,
			ADMHIDAT = CURRENT_DATE, 
			ADMHITIM = CURRENT_TIME, 
			ADMHISAB = P_ADMHISAB
		WHERE ADMGROUP= P_ADMGROUP; 			

	END IF;	

END P1