--DROP PROCEDURE PSSCMLIB.PSM_REFERENCE_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_REFERENCE_LIST ( 
	IN P_REDOCID VARCHAR(2), 
	IN P_REDOCNUM VARCHAR(50)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_REFERENCE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT
				RESABUN,
				RENAME
			FROM PSSCMLIB.PSM_Reference
			WHERE REDOCID  = P_REDOCID
			AND   REDOCNUM = P_REDOCNUM;
  
		OPEN REFCURSOR ; 
END MAIN ; 
END;