




DROP PROCEDURE PSSCMLIB.PSM_Plants_GetUnitData;

CREATE PROCEDURE PSSCMLIB.PSM_Plants_GetUnitData
( 
	P_C2SAUP     VARCHAR(1)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- ½ÃÀÛ
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR	
						
			WITH  TABLE1 AS (
			SELECT FXC2SAUP AS C2SAUP,
					  FXC2BCODE||DIGITS(FXC2MCODE)||'000' AS C2KEYCODE,
					  FXC2DESC AS  C2NAME ,
					  FXC2XPOINT AS  C2XPOINT,
					  FXC2YPOINT AS  C2YPOINT,
					  FXC2DSGUBN AS   C2DSGUBN,
					  FXC2SCGUBN AS C2SCGUBN         
			FROM TYSCMLIB.ACFIXCLASS2
			WHERE FXC2BCODE IN ('20','30','40')
			UNION ALL
			SELECT  FXC3SAUP AS C2SAUP,
						FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) AS C2KEYCODE, 
						FXC3DESC  AS C2NAME,
						FXC3XPOINT  AS C2XPOINT,
						FXC3YPOINT AS C2YPOINT,
						FXC3DSGUBN AS C2DSGUBN,
						FXC3SCGUBN AS C2SCGUBN
			FROM  TYSCMLIB.ACFIXCLASS3
			WHERE FXC3BCODE IN ('20','30','40')
			   AND FXC3XPOINT > 0 
			UNION ALL
			SELECT L3SAUP  AS C2SAUP,
					  L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) AS C2KEYCODE, 
					 L3NAME  AS C2NAME,  
					 L3XPOINT  AS C2XPOINT,
					 L3YPOINT AS C2YPOINT, 
				 L3DSGUBN AS C2DSGUBN, 
				 L3SCGUBN 
			AS C2SCGUBN
			FROM PSSCMLIB.PSM_LOCATION_CLASS3

			), TABLE3 AS (
			   SELECT  SMSYSTEMCODE,  MIN(DSPCOLOR) AS DSPCOLOR
				FROM  (
					SELECT  SMSYSTEMCODE1 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO
					UNION ALL
					SELECT  SMSYSTEMCODE2 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO
					UNION ALL
					SELECT  SMSYSTEMCODE3 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO
					UNION ALL
					SELECT  SMSYSTEMCODE4 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO
					UNION ALL
					SELECT  SMSYSTEMCODE5 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMAREACODE1 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMAREACODE2 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMAREACODE3 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMAREACODE4 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMAREACODE5 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE11 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE12 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE21 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE22 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE31 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE32 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE41 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE42 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE51 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
					UNION ALL
					SELECT  SMCONNCODE52 AS SMSYSTEMCODE,  DSPCOLOR
					FROM PSSCMLIB.CV_PSM_WORKLIST_SILO 
				  )
				WHERE  SMSYSTEMCODE != ''
                               GROUP BY SMSYSTEMCODE
			), TABLE2 AS (
			SELECT  C2SAUP,
						C2SAUP||C2KEYCODE AS C2KEYCODE,
						C2NAME ,
						C2XPOINT,
						C2YPOINT,
						C2DSGUBN,
						C2SCGUBN,
                        SMSYSTEMCODE ,
						CASE WHEN  DSPCOLOR = '1' THEN '02'
							 WHEN  DSPCOLOR = '2' THEN '03'
							 WHEN  DSPCOLOR = '3' THEN '04'
						ELSE '01' END AS UNITSTATUS
			FROM TABLE1 
			LEFT OUTER JOIN TABLE3
			    ON CASE WHEN INT(SUBSTR(C2KEYCODE,1,1)) > 7 THEN 
				               SMSYSTEMCODE
                        WHEN C2DSGUBN = 'PUMP' THEN
						      SMSYSTEMCODE    
				    ELSE SUBSTR(SMSYSTEMCODE,1,7) END  =
			       CASE WHEN INT(SUBSTR(C2KEYCODE,1,1)) > 7 THEN 
				           (C2SAUP||C2KEYCODE)
						WHEN C2DSGUBN = 'PUMP' THEN 
						   (C2SAUP||C2KEYCODE)
				   ELSE SUBSTR(C2SAUP||C2KEYCODE,1,7) END 
			WHERE C2SAUP = P_C2SAUP
			UNION ALL
			SELECT   'S' AS C2SAUP,
			        'T0001' ,
				'CHAIN CONVEYOR',
				523,
				273,
                                'SUBPOINT',
				'Main',
				'',
                                '01'
			FROM SYSIBM.SYSDUMMY1
                        UNION ALL
			SELECT   'S' AS C2SAUP,
			        'T0002' ,
				'CHAIN CONVEYOR',
				732,
				513,
                                'SUBPOINT',
				'Main',
				'',
                                '01'
			FROM SYSIBM.SYSDUMMY1
			)
			SELECT *
			FROM TABLE2
			WHERE C2SAUP = P_C2SAUP
			ORDER BY C2KEYCODE;
		
	OPEN REFCURSOR;

END