DROP PROCEDURE PSSCMLIB.PSM_GET_MAILID_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_GET_MAILID_LIST ( 
	IN P_KBSABUN VARCHAR(3000)) 

	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_GET_MAILID_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   

P1 : BEGIN

	MAIN : BEGIN  -- ½ÇÇàºÎ
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			
			SELECT
				DISTINCT
				KBSABUN,
				KBMAILID,
				KBHANGL
			FROM TYSCMLIB.INKIBNMF
			WHERE KBCOMPANY = '2'
			AND   KBSABUN   IN(SELECT * FROM TABLE(PSSCMLIB.SF_GB_RevColRow(P_KBSABUN, ',')) AS InTable )
			AND   KBIGUBN NOT IN ('560','900')
			AND   KBMAILID <> '';
  
		OPEN REFCURSOR;
	END MAIN;

END P1;