--DROP PROCEDURE PSSCMLIB.PSM_SAFE_MAG_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_SAFE_MAG_LIST ( 
	IN P_GRPID VARCHAR(30),
    IN P_USRID VARCHAR(6)) 

DYNAMIC RESULT SETS 1 

LANGUAGE SQL 
	
P1 : BEGIN 
	 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		
		SELECT
			ROW_NUMBER() OVER(ORDER BY USRID) AS ROWNO,
			USRID AS KBSABUN,
			KBHANGL
		FROM TYJINFWLIB.ORG_GROUPUSR AS GROUP
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
		ON     GROUP.USRID = KIBN.KBSABUN
		WHERE 1=1
		AND   GRPID     = P_GRPID
		AND   KBCOMPANY = '2'
		AND   USRID = P_USRID
		AND   KBBALCD NOT IN ('900', '560');

	OPEN REFCURSOR;

END P1;

CALL PSSCMLIB.PSM_SAFE_MAG_LIST('SAFE_MAG','0374-M');