--DROP PROCEDURE PSSCMLIB.PSM_ATTACHFILE_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_ATTACHFILE_DEL (
	IN P_ATTACH_TYPE  VARCHAR(2), 
	IN P_ATTACH_NO VARCHAR(50)
	) 

LANGUAGE SQL

P1 : BEGIN

	DELETE FROM PSSCMLIB.PSM_CMN_ATTACH
	WHERE ATTACH_TYPE = P_ATTACH_TYPE
	AND   ATTACH_NO   = P_ATTACH_NO;

END P1;