DROP PROCEDURE PSSCMLIB.PSM_TANKNO_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_TANKNO_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SEARCHCONDITION VARCHAR(1000) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	P1 : BEGIN 
  
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	 
	S1 : BEGIN  -- °ª ¼³Á¤ 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END S1 ; 
	 
	MAIN : BEGIN 
		 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
			WITH ORIGINAL_DATA AS 
			( 
  
				SELECT 
					ROW_NUMBER ( ) OVER ( ORDER BY TNTANKNO ) AS ROWNO , 
					TRIM ( TNTANKNO ) AS TNTANKNO , 
					TNBIJUNG 
				FROM TYSCMLIB . UTITANKF 
				WHERE TRIM ( TNTANKNO ) LIKE '%' || P_SEARCHCONDITION || '%' 
				ORDER BY TRIM ( TNTANKNO ) 
			) 
  
			SELECT 
				A . * 
			FROM ORIGINAL_DATA AS A 
			WHERE ( ROWNO BETWEEN P_STNUM AND P_FNNUM ) 
			ORDER BY A . ROWNO ASC ; 
  
		OPEN REFCURSOR ; 
  
	END MAIN ; 
	 
	TOTAL : BEGIN 
  
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
  
			SELECT 
				COUNT ( * ) AS TOTALCOUNT 
			FROM TYSCMLIB . UTITANKF 
			WHERE TRIM ( TNTANKNO ) LIKE '%' || P_SEARCHCONDITION || '%' ; 
		 
		OPEN REFCURSOR2 ; 
	END TOTAL ; 
  
END P1  ; 