--DROP PROCEDURE PSSCMLIB.PSM_REFERENCE_UPDATE;

CREATE PROCEDURE PSSCMLIB.PSM_REFERENCE_UPDATE (
	IN P_GUBUN    VARCHAR(1),
	IN P_REDOCID  VARCHAR(2),
	IN P_REDOCNUM VARCHAR(50),
	IN P_RESABUN  VARCHAR(1000),
	IN P_RENAME   VARCHAR(2000),
	IN P_REHISAB  VARCHAR(6)) 

LANGUAGE SQL

P1 : BEGIN

	DECLARE V_CNT     NUMERIC(3,0);
	 
	IF P_GUBUN = 'A' THEN

		SELECT
		COUNT(*) INTO V_CNT
		FROM PSSCMLIB.PSM_Reference
		WHERE REDOCID  = P_REDOCID
		AND   REDOCNUM = P_REDOCNUM;

		IF (V_CNT = 0) THEN

			INSERT INTO PSSCMLIB.PSM_Reference
			(
				REDOCID,
				REDOCNUM,
				RESABUN,
				RENAME,
				REHIGB,
				REHIDAT,
				REHITIM,
				REHISAB
			)
			VALUES
			(
				P_REDOCID,
				P_REDOCNUM,
				P_RESABUN,
				P_RENAME,
				P_GUBUN,
				CURRENT_DATE,
				CURRENT_TIME,
				P_REHISAB
			);
		ELSE

			UPDATE PSSCMLIB.PSM_Reference SET
				RESABUN = P_RESABUN,
				RENAME  = P_RENAME, 
				REHIGB  = P_GUBUN,
				REHIDAT = CURRENT_DATE,
				REHITIM = CURRENT_TIME,
				REHISAB = P_REHISAB
			WHERE REDOCID  = P_REDOCID
			AND   REDOCNUM = P_REDOCNUM;

		END IF;

	ELSE

		DELETE FROM PSSCMLIB.PSM_Reference
		WHERE REDOCID  = P_REDOCID
		AND   REDOCNUM = P_REDOCNUM;

	END IF;

END P1;