--DROP PROCEDURE PSSCMLIB.PSM_BUSEO_GETDATA;

CREATE PROCEDURE PSSCMLIB.PSM_BUSEO_GETDATA ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_DATE VARCHAR(8) , 
	IN P_SEARCHCONDITION VARCHAR(4000) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_BUSEO_GETDATA 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
  
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
	 
	S1 : BEGIN  -- 蔼 汲沥 
	SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END S1 ; 
	 
	MAIN : BEGIN 
		 
		DECLARE REFCURSOR INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR1 ;  -- 目辑积己 
		SET P_TABLE_QUERY = '	WITH TABLE1 AS 
					( 
						SELECT 
							ORG_CD AS BUSEO , 
							ORG_NM AS BUSEONM 
						FROM TYSCMLIB . INTORG101 
						WHERE ENTER_CD = ''TY''
						AND REPLACE ( CHAR ( CAST ( ' || P_DATE || ' AS VARCHAR ( 8 ) ) ) , ''-'' , '''' ) BETWEEN SDATE AND CASE WHEN EDATE = '''' THEN ''99991231'' ELSE COALESCE ( EDATE , ''99991231'' ) END 
						' || P_SEARCHCONDITION || '
						ORDER BY ORG_CD 
					) , 
					ORIGINAL_DATA AS 
					( 
						SELECT ROW_NUMBER ( ) OVER ( ORDER BY BUSEO ) AS ROWNO , 
						BUSEO , 
						BUSEONM 
						FROM TABLE1 
					) 
					SELECT A . * 
					FROM ORIGINAL_DATA AS A 
					WHERE A.ROWNO BETWEEN ' || CAST ( P_STNUM AS VARCHAR ( 100 ) ) || ' AND ' || CAST ( P_FNNUM AS VARCHAR ( 100 ) ) || '
					ORDER BY A . ROWNO ASC
					' ; 
  
		PREPARE CUR1 FROM P_TABLE_QUERY ; 
  
		OPEN REFCURSOR ; 
  
	END MAIN ; 
  
	TOTAL : BEGIN 
		 
		DECLARE REFCURSOR2 INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR2 ;  -- 目辑积己 
		SET P_COUNT_QUERY = '	WITH TABLE1 AS 
					( 
						SELECT 
							ORG_CD AS BUSEO , 
							ORG_NM AS BUSEONM 
						FROM TYSCMLIB . INTORG101 
						WHERE ENTER_CD = ''TY''
						AND REPLACE ( CHAR ( CAST ( ' || P_DATE || ' AS VARCHAR ( 8 ) ) ) , ''-'' , '''' ) BETWEEN SDATE AND CASE WHEN EDATE = '''' THEN ''99991231'' ELSE COALESCE ( EDATE , ''99991231'' ) END 
						' || P_SEARCHCONDITION || '
						ORDER BY ORG_CD 
					) 
			  
					SELECT COUNT ( * ) AS TOTALCOUNT 
					FROM TABLE1' ;   
		PREPARE CUR2 FROM P_COUNT_QUERY ; 
		OPEN REFCURSOR2 ; 
	END TOTAL ; 
END P1  ; 
