--DROP PROCEDURE PSSCMLIB.PSM_WORKORDER_DOC;

CREATE PROCEDURE PSSCMLIB.PSM_WORKORDER_DOC
(
    P_CURRENTPAGEINDEX      INTEGER,
	P_PAGESIZE              INTEGER,
	P_SDATE  	VARCHAR(8),
    P_EDATE  	VARCHAR(8),
	P_SABUN     VARCHAR(6)
)
	RESULT SETS 2
	LANGUAGE SQL

P1: BEGIN

	DECLARE P_STNUM			INTEGER;
    DECLARE P_FNNUM			INTEGER;

	PREV : BEGIN -- 값 설정
        SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ;
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ;
    END PREV;
	

	LIST : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH TABLE1 AS (
		SELECT  WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APP_NUM,
				WOORTEAM ,  
				WOORDATE ,  
				DIGITS(WOSEQ) AS WOSEQ,  
				WOORSABUN,  
				K1.KBHANGL AS  WOORSABUNNM,
				WOWORKTITLE,
			WOCHANGEWKDIV,
			CASE WHEN WOCHANGEWKDIV = '1' THEN '단순변경' ELSE '변경관리' END WOCHANGEWKDIVNM,
				PAR.SABUN
		FROM PSSCMLIB.PSM_WORKORDER
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF K1
			 ON K1.KBSABUN =  WOORSABUN
		 LEFT OUTER JOIN (SELECT CAST(P_SDATE AS VARCHAR(8))  AS SDATE, 
								 CAST(P_EDATE AS VARCHAR(8))  AS EDATE,
					 CAST(P_SABUN AS VARCHAR(8))  AS SABUN 
					 FROM SYSIBM.SYSDUMMY1) AS PAR
				 ON 1 = 1
		WHERE  WOORDATE BETWEEN SDATE AND EDATE
		), TABLE2 AS (
		SELECT  
				ROWNUMBER() OVER() AS ROWNO,
				B.APP_NUM AS PO_NO,
				B.WOORSABUN AS PO_SABUN,  
				B.WOORSABUNNM AS PO_SABUNNM,
				B.WOWORKTITLE AS PO_TITLE,
			B.WOCHANGEWKDIV AS WORKGUBN,
			B.WOCHANGEWKDIVNM AS WORKGUBNNM,
			  --CASE WHEN PSSCMLIB.SF_PSM_MAINWOAPPNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ ) = B.SABUN THEN 'Y' ELSE '' END AS APPWKORDER,

			  ( SELECT   CASE WHEN WODOCSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MAINWOAPPNEXT
                            WHERE WOORTEAM  = B.WOORTEAM
                              AND WOORDATE  = B.WOORDATE
                              AND WOSEQ     = B.WOSEQ ) AS APPWKORDER,	

			   (SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE '' END
				  FROM PSSCMLIB.PSM_CHECKLIST_MASTER 
				 WHERE CKMWKTEAM = B.WOORTEAM
				   AND CKMWKDATE = B.WOORDATE
				   AND CKMWKSEQ  = B.WOSEQ
				   AND CKMAPPSABUN = B.SABUN 
			   AND CKMAPPDATE = '' ) AS APPCHECKLIST,
			   --CASE WHEN PSSCMLIB.SF_PSM_MaincChangeASKDocNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ ) = B.SABUN THEN 'Y' ELSE '' END AS APPCHANGASK,     
			   --CASE WHEN PSSCMLIB.SF_PSM_MaincChangeRevDocNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ ) = B.SABUN THEN 'Y' ELSE '' END AS APPCHANGREV,   
               ( SELECT   CASE WHEN CAASKSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MaincChangeASKDocNEXT
                  WHERE CAASKTEAM  = B.WOORTEAM
                   AND CAASKDATE  = B.WOORDATE
                   AND CAASKSEQ     = B.WOSEQ ) AS APPCHANGASK,     

               ( SELECT   CASE WHEN CRREVSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MaincChangeRevDocNEXT
                  WHERE CRREVTEAM  = B.WOORTEAM
                    AND CRREVDATE  = B.WOORDATE
                    AND CRREVSEQ     = B.WOSEQ ) AS APPCHANGREV,     			   

			  --CASE WHEN  PSSCMLIB.SF_PSM_MaincSafeDocNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ, B.SABUN ) = B.SABUN THEN 'Y' ELSE '' END AS APPSAFE,

			    ( SELECT   CASE WHEN SMSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MaincSafeDocNEXT
                  WHERE SMWKTEAM  = B.WOORTEAM
                    AND SMWKDATE  = B.WOORDATE
                    AND SMWKSEQ   = B.WOSEQ ) AS APPSAFE,  

			  ( SELECT  CASE WHEN  MAX(SMWKORAPPDATE||DIGITS(SMWKORSEQ)) IS NULL THEN '' ELSE 
									   MAX(SMWKORAPPDATE||DIGITS(SMWKORSEQ)) END
				 FROM PSSCMLIB.PSM_SafeOrder_MASTER
				 WHERE SMWKTEAM = B.WOORTEAM
				   AND SMWKDATE = B.WOORDATE
				   AND SMWKSEQ  = B.WOSEQ
				   AND ( (SMORSABUN = B.SABUN AND SMORAPPDATE = '') OR (SMGRSABUN = B.SABUN AND SMGRAPPDATE = '') OR (SMCOSABUN = B.SABUN  AND SMCOAPPDATE = '')
										 OR (SMSMSABUN = B.SABUN AND SMSMAPPDATE ='')  )
				 ) AS OR_NO
		FROM TABLE1 B ), TABLE3 AS (
			SELECT  ROWNUMBER() OVER() AS ROWNO,
					PO_NO,
					PO_SABUN,  
					PO_SABUNNM,
					PO_TITLE,
					WORKGUBN,
					WORKGUBNNM,
					CASE WHEN APPWKORDER = 'Y' THEN
						'<img src="/Resources/Images/Ext/doc.gif" style="cursor:pointer" onclick="GridDocRowClick(''' || PO_NO || ''');" />'
					ELSE
						''
					END as APPWKORDER_IMG,
					APPWKORDER,
					CASE WHEN APPCHECKLIST = 'Y' THEN
						'<img src="/Resources/Images/Ext/doc.gif" style="cursor:pointer" onclick="GridDocRowClick(''' || PO_NO || ''');" />'
					ELSE
						''
					END as APPCHECKLIST_IMG,
					APPCHECKLIST,
					CASE WHEN APPCHANGASK = 'Y' THEN
						'<img src="/Resources/Images/Ext/doc.gif" style="cursor:pointer" onclick="GridDocRowClick(''' || PO_NO || ''');" />'
					ELSE
						''
					END as APPCHANGASK_IMG,
					APPCHANGASK,
					CASE WHEN APPCHANGREV = 'Y' THEN
						'<img src="/Resources/Images/Ext/doc.gif" style="cursor:pointer" onclick="GridDocRowClick(''' || PO_NO || ''');" />'
					ELSE
						''
					END as APPCHANGREV_IMG,
					APPCHANGREV,
					CASE WHEN APPSAFE = 'Y' THEN
						'<img src="/Resources/Images/Ext/doc.gif" style="cursor:pointer" onclick="GridDocRowClick(''' || PO_NO || ''');" />'
					ELSE
						''
					END as APPSAFE_IMG,
					APPSAFE,
					OR_NO
			FROM TABLE2
			WHERE APPWKORDER = 'Y' OR APPCHECKLIST = 'Y' OR APPCHANGASK ='Y' OR APPCHANGREV ='Y' OR APPSAFE ='Y'
			ORDER BY SUBSTR(PO_NO,8,12)  DESC, PO_NO 
		)
		SELECT *
		FROM TABLE3
		WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM;
				
		OPEN REFCURSOR;
	END LIST;

	 PAGING : BEGIN -- 페이징
		  DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
		
		  WITH TABLE1 AS (
				SELECT  WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APP_NUM,
						WOORTEAM ,  
						WOORDATE ,  
						DIGITS(WOSEQ) AS WOSEQ,  
						WOORSABUN,  
						K1.KBHANGL AS  WOORSABUNNM,
						WOWORKTITLE,
					WOCHANGEWKDIV,
					CASE WHEN WOCHANGEWKDIV = '1' THEN '단순변경' ELSE '변경관리' END WOCHANGEWKDIVNM,
						PAR.SABUN
				FROM PSSCMLIB.PSM_WORKORDER
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF K1
					 ON K1.KBSABUN =  WOORSABUN
				 LEFT OUTER JOIN (SELECT CAST(P_SDATE AS VARCHAR(8))  AS SDATE, 
										 CAST(P_EDATE AS VARCHAR(8))  AS EDATE,
							 CAST(P_SABUN AS VARCHAR(8))  AS SABUN 
							 FROM SYSIBM.SYSDUMMY1) AS PAR
						 ON 1 = 1
				WHERE  WOORDATE BETWEEN SDATE AND EDATE
				), TABLE2 AS (
				SELECT  
						ROWNUMBER() OVER() AS ROWNO,
						B.APP_NUM AS PO_NO,
						B.WOORSABUN AS PO_SABUN,  
						B.WOORSABUNNM AS PO_SABUNNM,
						B.WOWORKTITLE AS PO_TITLE,
					B.WOCHANGEWKDIV AS WORKGUBN,
					B.WOCHANGEWKDIVNM AS WORKGUBNNM,
					--CASE WHEN PSSCMLIB.SF_PSM_MAINWOAPPNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ ) = B.SABUN THEN 'Y' ELSE '' END AS APPWKORDER,
                     ( SELECT   CASE WHEN WODOCSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MAINWOAPPNEXT
                            WHERE WOORTEAM  = B.WOORTEAM
                              AND WOORDATE  = B.WOORDATE
                              AND WOSEQ     = B.WOSEQ ) AS APPWKORDER,	
					   (SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE '' END
						  FROM PSSCMLIB.PSM_CHECKLIST_MASTER 
						 WHERE CKMWKTEAM = B.WOORTEAM
						   AND CKMWKDATE = B.WOORDATE
						   AND CKMWKSEQ  = B.WOSEQ
						   AND CKMAPPSABUN = B.SABUN 
					   AND CKMAPPDATE = '' ) AS APPCHECKLIST,
					   --CASE WHEN PSSCMLIB.SF_PSM_MaincChangeASKDocNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ ) = B.SABUN THEN 'Y' ELSE '' END AS APPCHANGASK,     
					   --CASE WHEN PSSCMLIB.SF_PSM_MaincChangeRevDocNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ ) = B.SABUN THEN 'Y' ELSE '' END AS APPCHANGREV,     
                 ( SELECT   CASE WHEN CAASKSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MaincChangeASKDocNEXT
                  WHERE CAASKTEAM  = B.WOORTEAM
                   AND CAASKDATE  = B.WOORDATE
                   AND CAASKSEQ     = B.WOSEQ ) AS APPCHANGASK,     

               ( SELECT   CASE WHEN CRREVSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MaincChangeRevDocNEXT
                  WHERE CRREVTEAM  = B.WOORTEAM
                    AND CRREVDATE  = B.WOORDATE
                    AND CRREVSEQ     = B.WOSEQ ) AS APPCHANGREV,     	

					  --CASE WHEN  PSSCMLIB.SF_PSM_MaincSafeDocNEXT(B.WOORTEAM, B.WOORDATE, B.WOSEQ, B.SABUN ) = B.SABUN THEN 'Y' ELSE '' END AS APPSAFE,

                ( SELECT   CASE WHEN SMSABUN = B.SABUN THEN 'Y'  ELSE '' END  FROM PSSCMLIB.CV_PSM_MaincSafeDocNEXT
                  WHERE SMWKTEAM  = B.WOORTEAM
                    AND SMWKDATE  = B.WOORDATE
                    AND SMWKSEQ   = B.WOSEQ ) AS APPSAFE,  

					  ( SELECT  CASE WHEN  MAX(SMWKORAPPDATE||DIGITS(SMWKORSEQ)) IS NULL THEN '' ELSE 
											   MAX(SMWKORAPPDATE||DIGITS(SMWKORSEQ)) END
						 FROM PSSCMLIB.PSM_SafeOrder_MASTER
						 WHERE SMWKTEAM = B.WOORTEAM
						   AND SMWKDATE = B.WOORDATE
						   AND SMWKSEQ  = B.WOSEQ
						   AND ( (SMORSABUN = B.SABUN AND SMORAPPDATE = '') OR (SMGRSABUN = B.SABUN AND SMGRAPPDATE = '') OR (SMCOSABUN = B.SABUN  AND SMCOAPPDATE = '')
												 OR (SMSMSABUN = B.SABUN AND SMSMAPPDATE ='')  )
						 ) AS OR_NO
				FROM TABLE1 B )
					SELECT COUNT(*) AS TOTALCOUNT
					FROM TABLE2
					WHERE APPWKORDER = 'Y' OR APPCHECKLIST = 'Y' OR APPCHANGASK ='Y' OR APPCHANGREV ='Y' OR APPSAFE ='Y';		
	
		OPEN REFCURSOR2;
    END PAGING;
	
END