--DROP PROCEDURE PSSCMLIB.PSM_MAILRETRACT_INSERT;

CREATE PROCEDURE PSSCMLIB.PSM_MAILRETRACT_INSERT (
	IN P_RTDOCID   VARCHAR(2),
	IN P_RTDOCNUM  VARCHAR(50),
	IN P_RTCOMMENT VARCHAR(1000),
	IN P_RTHISAB   VARCHAR(6)
) 

LANGUAGE SQL

P1 : BEGIN

	DECLARE V_CNT     NUMERIC(3,0);
	 
	INSERT INTO PSSCMLIB.PSM_MailRetract
	(
		RTDOCID,
		RTDOCNUM,
		RTSEQ,
		RTCOMMENT,
		RTHIGB,
		RTHIDAT,
		RTHITIM,
		RTHISAB
	)
	VALUES
	(
		P_RTDOCID,
		P_RTDOCNUM,
		(
			SELECT
				VALUE(MAX(RTSEQ) + 1, 1) AS RTSEQ
			FROM PSSCMLIB.PSM_MailRetract
			WHERE RTDOCID  = P_RTDOCID 
			AND   RTDOCNUM = P_RTDOCNUM
		),
		P_RTCOMMENT,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_RTHISAB
	);

END P1;