--DROP PROCEDURE PSSCMLIB.PSM_OPERA_KBSABUN_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_OPERA_KBSABUN_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_KBBUSEO VARCHAR(30) , 
	IN P_SEARCHCONDITION VARCHAR(4000) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_OPERA_KBSABUN_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
	LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR1 ;  -- 커서생성 
			SET P_TABLE_QUERY = '
				
				WITH ORIGINAL_DATA AS (  
					SELECT
						ROW_NUMBER() OVER(ORDER BY KBBUSEO, KBJKCD, KBSABUN) AS ROWNO,
						KBSABUN ,   
						KBHANGL ,   
						KBBUSEO ,   
						KBJUSO , 
						KBSEXGB  , 
						KBHOBN, 
						KBJKCD, 
						KBGUNMU,
						CDDESC1,
						KBMOBILE,
						KBMAILID
					 FROM TYSCMLIB.INKIBNMF
					 LEFT OUTER JOIN TYSCMLIB.INCODEMF
					 ON      ''JK'' = CDINDEX
					 AND     KBJKCD = CDCODE
					 WHERE KBCOMPANY  = ''2''  
					   AND KBBALCD NOT IN (''900'', ''560'')
					   AND SUBSTR(KBBUSEO,1,2) IN ( SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(''' || P_KBBUSEO || ''' AS VARCHAR(100)), '','')) AS InTable )
					   AND KBJJCD IN (''090'', ''110'', ''130'', ''150'', ''180'')
					   AND KBSABUN NOT IN(''0040-M'')
					   ' || P_SEARCHCONDITION || '
				)               
				SELECT *
				FROM ORIGINAL_DATA
				WHERE ROWNO BETWEEN ' || CAST ( P_STNUM AS VARCHAR ( 100 ) ) || ' AND ' || CAST ( P_FNNUM AS VARCHAR ( 100 ) ) || '
				ORDER BY ROWNO
				' ; 
  
				PREPARE CUR1 FROM P_TABLE_QUERY ; 
				OPEN REFCURSOR ; 
			END LIST ; 
  
			PAGING : BEGIN  -- 페이징 
				DECLARE REFCURSOR2 INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR2 ;  -- 커서생성 
					SET P_COUNT_QUERY = '
									SELECT 
										COUNT(*) AS TOTALCOUNT  
									FROM TYSCMLIB.INKIBNMF
									LEFT OUTER JOIN TYSCMLIB.INCODEMF
									ON      ''JK'' = CDINDEX
									AND     KBJKCD = CDCODE
									WHERE KBCOMPANY  = ''2''  
									AND   KBBALCD NOT IN (''900'', ''560'')
									AND   SUBSTR(KBBUSEO,1,2) IN ( SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(''' || P_KBBUSEO || ''' AS VARCHAR(100)), '','')) AS InTable )
									AND   KBJJCD IN (''090'', ''110'', ''130'', ''150'', ''180'')
									AND   KBSABUN NOT IN(''0040-M'')
									' || P_SEARCHCONDITION || '
								' ; 
  
					PREPARE CUR2 FROM P_COUNT_QUERY ; 
				 
				OPEN REFCURSOR2 ; 
			END PAGING ; 
END MAIN ; 
END;

CALL PSSCMLIB.PSM_OPERA_KBSABUN_LIST(1,10,'S1,T1','');

