-- DROP PROCEDURE PSSCMLIB.PSM_SAFE_KBSABUN_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_SAFE_KBSABUN_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER,
	IN P_PAGESIZE         INTEGER,
	IN P_GRPID            VARCHAR(30),
	IN P_SEARCHCONDITION  VARCHAR(4000))

DYNAMIC RESULT SETS 2 
LANGUAGE SQL 


P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
	LIST : BEGIN  -- 리스트 
		
		DECLARE REFCURSOR INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR1 ;  -- 커서생성 
		
			SET P_TABLE_QUERY = '

				WITH ORIGINAL_DATA AS (  
					SELECT
						ROW_NUMBER() OVER(ORDER BY USRID) AS ROWNO,
						USRID AS KBSABUN,
						KBHANGL
					FROM TYJINFWLIB.ORG_GROUPUSR AS GROUP
					LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
					ON     GROUP.USRID = KIBN.KBSABUN
					WHERE 1=1
					AND   GRPID     = ''' || P_GRPID || '''
					AND   KBCOMPANY = ''2''  
					AND   KBBALCD NOT IN ( ''900'', ''560'')
					' || P_SEARCHCONDITION || '
				)               
				SELECT *
				FROM ORIGINAL_DATA
				WHERE ROWNO BETWEEN ' || CAST ( P_STNUM AS VARCHAR ( 100 ) ) || ' AND ' || CAST ( P_FNNUM AS VARCHAR ( 100 ) ) || '
				ORDER BY ROWNO ASC 
				' ; 

				PREPARE CUR1 FROM P_TABLE_QUERY ; 
				OPEN REFCURSOR ; 
			END LIST ; 
  
			PAGING : BEGIN  -- 페이징 
				
				DECLARE REFCURSOR2 INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR2 ;  -- 커서생성 
					SET P_COUNT_QUERY = '
									SELECT 
										COUNT(*) AS TOTALCOUNT  
									FROM TYJINFWLIB.ORG_GROUPUSR AS GROUP
									LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
									ON     GROUP.USRID = KIBN.KBSABUN
									WHERE 1=1
									AND   GRPID     = ''' || P_GRPID || '''
									AND   KBCOMPANY = ''2''  
									AND   KBBALCD NOT IN ( ''900'', ''560'')
									' || P_SEARCHCONDITION || '
								';

					PREPARE CUR2 FROM P_COUNT_QUERY ; 
				
				OPEN REFCURSOR2 ; 
			END PAGING ; 
END MAIN ; 
END;

CALL PSSCMLIB.PSM_SAFE_KBSABUN_LIST(1,10,'SAFE_MAG','');