--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-07-14 14:00:25 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","IKHPDM" ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_CODE_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SEARCHCONDITION VARCHAR(1000) , 
	IN P_INDEX VARCHAR(2) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_CODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
DECLARE P_STNUM INTEGER ; 
DECLARE P_FNNUM INTEGER ; 
  
S1 : BEGIN  -- °ª ¼³Á¤ 
SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
END S1 ; 
  
MAIN : BEGIN 
DECLARE REFCURSOR CURSOR WITH RETURN FOR 
WITH ORIGINAL_DATA AS ( 
		 
			SELECT ROW_NUMBER ( ) OVER ( ORDER BY CDCODE ) AS ROWNO , 
			CDCODE , 
CDDESC1 
FROM PSSCMLIB.PSM_CODEMF 
WHERE CDINDEX = P_INDEX 
AND CDDESC1 LIKE '%' || P_SEARCHCONDITION || '%' 
ORDER BY CDCODE 
) 
SELECT A . * 
FROM ORIGINAL_DATA AS A 
WHERE ( ROWNO BETWEEN P_STNUM AND P_FNNUM ) 
ORDER BY A . ROWNO ASC ; 
  
OPEN REFCURSOR ; 
END MAIN ; 
  
TOTAL : BEGIN 
DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
SELECT COUNT ( * ) AS TOTALCOUNT 
FROM PSSCMLIB.PSM_CODEMF 
WHERE CDINDEX = P_INDEX 
AND CDDESC1 LIKE '%' || P_SEARCHCONDITION || '%' ; 
  
OPEN REFCURSOR2 ; 
END TOTAL ; 
END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE PSSCMLIB.PSM_CODE_LIST 
TO IKHPDM WITH GRANT OPTION ;
