--DROP PROCEDURE PSSCMLIB.PSM_BUSEO_EMPOYEE_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_BUSEO_EMPOYEE_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_BUSEO VARCHAR(30) , 
	IN P_SEARCHCONDITION VARCHAR(4000) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_BUSEO_EMPOYEE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
	LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR1 ;  -- 커서생성 
			SET P_TABLE_QUERY = '

				WITH ORIGINAL_DATA AS (  
					SELECT
						DISTINCT
						ROW_NUMBER() OVER(ORDER BY KBSABUN) AS ROWNO,
						KBSABUN,
						KBHANGL
					FROM
					(
						SELECT
							DISTINCT
							KBSABUN,
							KBHANGL
						FROM
						(
							SELECT
								DISTINCT
								TEMP.KBSABUN,
								TEMP.KBHANGL
							FROM
							(
								SELECT
									DISTINCT
									KBSABUN, 
									KBHANGL,
									KBJKCD,
									CASE WHEN EIS . EMORG_CD IS NULL THEN KBBUSEO 
									     ELSE CASE WHEN KBSABUN = ''0312-F'' AND EMYYMM <= ''201412'' THEN ''A90000'' 
										       WHEN KBSABUN = ''0346-F'' AND EMYYMM <= ''201412'' THEN ''C10000''
										       ELSE EIS . EMORG_CD END 
									     END ORG_CD 
								FROM TYSCMLIB.INKIBNMF 
								LEFT OUTER JOIN (SELECT EMSABUN , EMORG_CD , EMYYMM FROM TYSCMLIB.EIORGMEMBERF 
										 WHERE EMENTER_CD = ''TY'' 
										 AND EMYYMM = SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTR(CHAR(CURRENT_DATE),6,2)) EIS 
								ON EIS . EMSABUN = KBSABUN 
								WHERE KBCOMPANY  = ''2''  
								AND   KBBALCD NOT IN(''90'',''91'',''900'',''560'')
							) AS TEMP
							LEFT OUTER JOIN (SELECT ORG_CD , ORG_NM 
									 FROM TYSCMLIB.INTORG101 B 
									 WHERE B.ENTER_CD = ''TY'' 
									 AND SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)||SUBSTRING(CHAR(CURRENT_DATE),9,2) BETWEEN B.SDATE AND CASE WHEN EDATE = '''' THEN ''99991231'' ELSE VALUE(EDATE , ''99991231'' ) END ) ORG 
							ON ORG.ORG_CD = TEMP.ORG_CD
							WHERE SUBSTR(TEMP.ORG_CD,1,2) = ''' || SUBSTR ( P_BUSEO , 1 , 2 ) || '''
							AND   TEMP.KBJKCD IN(''1A'',''1B'',''2A'',''2B'', ''3A'', ''3B'', ''3C'')
							' || P_SEARCHCONDITION || '

							UNION ALL

							SELECT
								DISTINCT
								TEMP.KBSABUN,
								TEMP.KBHANGL
							FROM
							(
								SELECT
									DISTINCT
									KBSABUN, 
									KBHANGL,
									KBJKCD,
									CASE WHEN EIS . EMORG_CD IS NULL THEN KBBUSEO 
									     ELSE CASE WHEN KBSABUN = ''0312-F'' AND EMYYMM <= ''201412'' THEN ''A90000'' 
										       WHEN KBSABUN = ''0346-F'' AND EMYYMM <= ''201412'' THEN ''C10000'' 
										       ELSE EIS . EMORG_CD END 
									     END ORG_CD 
								FROM TYSCMLIB.INKIBNMF 
								LEFT OUTER JOIN (SELECT EMSABUN , EMORG_CD , EMYYMM FROM TYSCMLIB.EIORGMEMBERF 
										 WHERE EMENTER_CD = ''TY'' 
										 AND EMYYMM = SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)) EIS 
								ON EIS . EMSABUN = KBSABUN 
								WHERE KBCOMPANY  = ''2''  
								AND   KBBALCD NOT IN(''90'',''91'',''900'',''560'')
							) AS TEMP
							LEFT OUTER JOIN (SELECT ORG_CD , ORG_NM 
									 FROM TYSCMLIB.INTORG101 B 
									 WHERE B.ENTER_CD = ''TY''
									 AND SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)||SUBSTRING(CHAR(CURRENT_DATE),9,2) BETWEEN B.SDATE AND CASE WHEN EDATE = '''' THEN ''99991231'' ELSE VALUE(EDATE , ''99991231'' ) END ) ORG 
							ON ORG.ORG_CD = TEMP.ORG_CD
							WHERE SUBSTR(TEMP.ORG_CD,1,2) = ''' || SUBSTR ( P_BUSEO , 1 , 2 ) || '''
							AND   TEMP.KBJKCD IN(''1A'',''1B'',''2A'',''2B'', ''3A'', ''3B'', ''3C'')
							' || P_SEARCHCONDITION || '
						) AS TEMP30
						
					) AS TEMP3
				)               
				SELECT *
				FROM ORIGINAL_DATA
				WHERE ROWNO BETWEEN ' || CAST ( P_STNUM AS VARCHAR ( 100 ) ) || ' AND ' || CAST ( P_FNNUM AS VARCHAR ( 100 ) ) || '
				ORDER BY ROWNO ASC 
				' ; 
  
				PREPARE CUR1 FROM P_TABLE_QUERY ; 
				OPEN REFCURSOR ; 
			END LIST ; 
  
			PAGING : BEGIN  -- 페이징 
				DECLARE REFCURSOR2 INSENSITIVE SCROLL CURSOR WITH RETURN FOR CUR2 ;  -- 커서생성 
					SET P_COUNT_QUERY = '
							SELECT 
								COUNT(*) AS TOTALCOUNT
							FROM
							(
								SELECT
									DISTINCT
									KBSABUN,
									KBHANGL
								FROM
								(
									SELECT
										DISTINCT
										TEMP.KBSABUN,
										TEMP.KBHANGL
									FROM
									(
										SELECT
											KBSABUN, 
											KBHANGL,
											KBJKCD,
											CASE WHEN EIS . EMORG_CD IS NULL THEN KBBUSEO 
											     ELSE CASE WHEN KBSABUN = ''0312-F'' AND EMYYMM <= ''201412'' THEN ''A90000'' 
												       WHEN KBSABUN = ''0346-F'' AND EMYYMM <= ''201412'' THEN ''C10000''
												       ELSE EIS . EMORG_CD END 
											     END ORG_CD 
										FROM TYSCMLIB.INKIBNMF 
										LEFT OUTER JOIN (SELECT EMSABUN , EMORG_CD , EMYYMM FROM TYSCMLIB.EIORGMEMBERF 
												 WHERE EMENTER_CD = ''TY'' 
												 AND EMYYMM = SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)) EIS 
										ON EIS . EMSABUN = KBSABUN 
										WHERE KBCOMPANY  = ''2''  
										AND   KBBALCD NOT IN(''90'',''91'',''900'',''560'')
									) AS TEMP
									LEFT OUTER JOIN (SELECT ORG_CD , ORG_NM 
											 FROM TYSCMLIB.INTORG101 B 
											 WHERE B.ENTER_CD = ''TY'' 
											 AND SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)||SUBSTRING(CHAR(CURRENT_DATE),9,2) BETWEEN B.SDATE AND CASE WHEN EDATE = '''' THEN ''99991231'' ELSE VALUE(EDATE , ''99991231'' ) END ) ORG 
									ON ORG.ORG_CD = TEMP.ORG_CD
									WHERE SUBSTR(TEMP.ORG_CD,1,2) = ''' || SUBSTR ( P_BUSEO , 1 , 2 ) || '''
									AND   TEMP.KBJKCD IN(''1A'',''1B'',''2A'',''2B'', ''3A'', ''3B'', ''3C'')
									' || P_SEARCHCONDITION || '

									UNION ALL

									SELECT
										DISTINCT
										TEMP.KBSABUN,
										TEMP.KBHANGL
									FROM
									(
										SELECT
											DISTINCT
											KBSABUN, 
											KBHANGL,
											KBJKCD,
											CASE WHEN EIS . EMORG_CD IS NULL THEN KBBUSEO 
											     ELSE CASE WHEN KBSABUN = ''0312-F'' AND EMYYMM <= ''201412'' THEN ''A90000'' 
												       WHEN KBSABUN = ''0346-F'' AND EMYYMM <= ''201412'' THEN ''C10000'' 
												       ELSE EIS . EMORG_CD END 
											     END ORG_CD 
										FROM TYSCMLIB.INKIBNMF 
										LEFT OUTER JOIN (SELECT EMSABUN , EMORG_CD , EMYYMM FROM TYSCMLIB.EIORGMEMBERF 
												 WHERE EMENTER_CD = ''TY'' 
												 AND EMYYMM = SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)) EIS 
										ON EIS . EMSABUN = KBSABUN 
										WHERE KBCOMPANY  = ''2''  
										AND   KBBALCD NOT IN(''90'',''91'',''900'',''560'')
									) AS TEMP
									LEFT OUTER JOIN (SELECT ORG_CD , ORG_NM 
											 FROM TYSCMLIB.INTORG101 B 
											 WHERE B.ENTER_CD = ''TY'' 
											 AND SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTRING(CHAR(CURRENT_DATE),6,2)||SUBSTRING(CHAR(CURRENT_DATE),9,2) BETWEEN B.SDATE AND CASE WHEN EDATE = '''' THEN ''99991231'' ELSE VALUE(EDATE , ''99991231'' ) END ) ORG 
									ON ORG.ORG_CD = TEMP.ORG_CD
									WHERE SUBSTR(TEMP.ORG_CD,1,2) = ''' || SUBSTR ( P_BUSEO , 1 , 2 ) || '''
									AND   TEMP.KBJKCD IN(''1A'',''1B'',''2A'',''2B'', ''3A'', ''3B'', ''3C'')
									' || P_SEARCHCONDITION || '
									
								) AS TEMP3
							) AS TEMP5

						' ; 
  
					PREPARE CUR2 FROM P_COUNT_QUERY ; 
				 
				OPEN REFCURSOR2 ; 
			END PAGING ; 
END MAIN ; 
END;