--DROP PROCEDURE PSSCMLIB.PSM_SABUN_GET_BUSEO;
  
CREATE PROCEDURE PSSCMLIB.PSM_SABUN_GET_BUSEO ( 
	IN P_DATE    VARCHAR(8),
	IN P_KBSABUN VARCHAR(6)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_SABUN_GET_BUSEO 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 

		SELECT
		KBHANGL,
		TYSCMLIB.SF_GB_NEWORGID(KBSABUN, 'CODE', PAR.KIJUNDATE) AS KBBUSEO, /* 부서코드 */
		TYSCMLIB.SF_GB_NEWORGID(KBSABUN, 'NAME', PAR.KIJUNDATE) AS KBBUSEONM, /* 부서명 */
		KBJKCD,
		JKCODE.CDDESC1
		FROM TYSCMLIB.INKIBNMF
		LEFT OUTER JOIN (SELECT CAST(P_DATE AS VARCHAR(8)) AS KIJUNDATE
				 FROM SYSIBM.SYSDUMMY1) AS PAR 
			  ON 1 = 1
		LEFT OUTER JOIN TYSCMLIB.INCODEMF AS JKCODE
		 ON        'JK' = CDINDEX
		 AND     KBJKCD = CDCODE
		WHERE KBSABUN = P_KBSABUN
		AND   KBCOMPANY = '2'
		AND   KBBALCD NOT IN ( '900', '560');
  
	OPEN REFCURSOR ; 
  
END P1;

CALL PSSCMLIB.PSM_SABUN_GET_BUSEO('20230710','0311-M');