--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1083_JSA_CLASS1_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1083_JSA_CLASS1_DEL ( 
	IN P_J1CODE VARCHAR(2)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1083_JSA_CLASS1_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
	DELETE FROM PSSCMLIB.PSM_JSA_CLASS1 
	WHERE J1CODE = P_J1CODE ;
  
END P1  ; 
  