--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","LSHPDM" ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1081_JSA_CLASS3_RUN ( 
	IN P_J3BCODE VARCHAR(2) , 
	IN P_J3MCODE VARCHAR(2) , 
	IN P_J3SCODE VARCHAR(3) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1081_JSA_CLASS3_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
			J3BCODE,
			J1NAME AS J3BCODENM,
			J3MCODE AS J3MCODE,
			J2NAME AS J3MCODENM,
			J3SCODE AS J3SCODE,
			J3NAME,
			J3BIGO ,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_JSA_MASTER WHERE JSMBLASS = J3BCODE AND JSMMLASS = J3MCODE AND JSMSLASS = J3SCODE) > 0 THEN 'Y' ELSE 'N' END AS JSMGUBUN,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_JSACHANGE_MASTER WHERE JSMBLASS = J3BCODE AND JSMMLASS = J3MCODE AND JSMSLASS = J3SCODE) > 0 THEN 'Y' ELSE 'N' END AS JSCGUBUN
		FROM PSSCMLIB.PSM_JSA_CLASS3 
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1 
		ON   J1CODE = J3BCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2 
		ON   J2BCODE = J3BCODE
		AND  J2MCODE = J3MCODE 
		WHERE J3BCODE = P_J3BCODE
		AND   J3MCODE = P_J3MCODE
		AND   J3SCODE = P_J3SCODE
  
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
