DROP PROCEDURE PSSCMLIB.PSM_PSM1081_JSA_CLASS3_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1081_JSA_CLASS3_ADD ( 
	IN P_J3BCODE VARCHAR(2) , 
	IN P_J3MCODE VARCHAR(2) , 
	IN P_J3SCODE VARCHAR(3) , 
	IN P_J3NAME VARCHAR(100) , 
	IN P_J3BIGO VARCHAR(200) ,
	IN P_J3HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1081_JSA_CLASS3_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_JSA_CLASS3(
		J3BCODE,
		J3MCODE,
		J3SCODE,
		J3NAME,
		J3BIGO,
		J3HIGB,
		J3HIDAT,
		J3HITIM,
		J3HISAB
		)
		VALUES
		(
		P_J3BCODE,
		P_J3MCODE,
		P_J3SCODE,
		P_J3NAME,
		P_J3BIGO,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_J3HISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_JSA_CLASS3 SET
			J3NAME  = P_J3NAME, 
			J3BIGO  = P_J3BIGO, 
			J3HIGB  = 'C', 
			J3HIDAT = CURRENT_DATE, 
			J3HITIM = CURRENT_TIME,
			J3HISAB = P_J3HISAB
		WHERE J3BCODE = P_J3BCODE
		AND   J3MCODE = P_J3MCODE
		AND   J3SCODE = P_J3SCODE ;
  
	END IF ; 
  
END P1  ; 
  