

DROP PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS1_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS1_DEL ( 
	IN P_PBC1NTCODE VARCHAR(2),
	IN P_PBC1LCODE   VARCHAR(3)
	) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_BOARD_CLASS1_DEL
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	
  
		DELETE FROM PSSCMLIB.PSM_BOARD_CLASS1
		WHERE PBC1LCODE = P_PBC1LCODE
		AND   PBC1NTCODE = P_PBC1NTCODE;
  
	
  
END P1  ; 
  