--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1030_SCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1030_SCODE_LIST ( 
	IN P_SAUP VARCHAR(1),
	IN P_BCODE VARCHAR(2),
	IN P_MCODE VARCHAR(4)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1030_SCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		''AS C3SAUP ,   
		''AS C3BCODE,   
		''AS C3BCODENM,
		''AS C3MCODE,   
		''AS C3MCODENM,
		''AS C3SCODE,
		''AS C3NAME,
		'전체'AS  C3CODENAME,   
		'' AS C3BIGO 
		FROM SYSIBM.SYSDUMMY1

		UNION ALL

		SELECT
		FXC3SAUP          AS C3SAUP ,   
		FXC3BCODE         AS C3BCODE,   
		FXC1DESC          AS C3BCODENM,
		DIGITS(FXC3MCODE) AS C3MCODE,   
		FXC2DESC          AS C3MCODENM,
		DIGITS(FXC3SCODE) AS C3SCODE,
		FXC3DESC          AS C3NAME ,   
		DIGITS(FXC3SCODE)||'-'||FXC3DESC AS C3CODENAME,
		FXC3BIGO AS C3BIGO 
		FROM TYSCMLIB.ACFIXCLASS3
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS1 
		ON      FXC1SAUP = FXC3SAUP
		AND    FXC1CODE = FXC3BCODE
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS2
		ON      FXC2SAUP    = FXC3SAUP
		AND    FXC2BCODE  = FXC3BCODE
		AND    FXC2MCODE = FXC3MCODE 
		WHERE FXC3BCODE IN('20', '30', '40', '90')
		AND    FXC3SAUP    = P_SAUP
		AND    FXC3BCODE  = P_BCODE
		AND   (CASE WHEN P_MCODE = '' THEN 1 ELSE FXC3MCODE END) = (CASE WHEN P_MCODE = '' THEN 2 ELSE P_MCODE END)
		ORDER BY C3SAUP, C3BCODE, C3MCODE, C3SCODE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 