

DROP PROCEDURE PSSCMLIB.PSM_PSM1021_LOCATIONCODE_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1021_LOCATIONCODE_ADD ( 
	IN P_L3SAUP VARCHAR(1) , 
	IN P_L3BCODE VARCHAR(1) , 
	IN P_L3MCODE VARCHAR(4) , 
	IN P_L3SCODE VARCHAR(3) , 
	IN P_L3NAME VARCHAR(100) , 
	IN P_L3BIGO VARCHAR(200) ,
	IN P_L3HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1021_LOCATIONCODE_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO  PSSCMLIB.PSM_LOCATION_CLASS3 ( 
			 L3SAUP     , 
			 L3BCODE    , 
			 L3MCODE    , 
			 L3SCODE    , 
			 L3NAME     , 
			 L3BIGO    , 
			 L3HIGB    , 
			 L3HIDAT   , 
			 L3HITIM   , 
			 L3HISAB   
		) VALUES (
			 P_L3SAUP     , 
			 P_L3BCODE    , 
			 P_L3MCODE    , 
			 P_L3SCODE    , 
			 P_L3NAME     , 
			 P_L3BIGO    , 
			 'A'    , 
			 CURRENT_DATE   , 
			 CURRENT_TIME   , 
			 P_L3HISAB   
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_LOCATION_CLASS3 
		SET      L3NAME      = P_L3NAME, 
			 L3BIGO    = P_L3BIGO, 
			 L3HIGB    = 'C', 
			 L3HIDAT   = CURRENT_DATE, 
			 L3HITIM   = CURRENT_TIME,
			 L3HISAB   = P_L3HISAB
		WHERE L3SAUP  = P_L3SAUP
		  AND L3BCODE = P_L3BCODE
		  AND L3MCODE = P_L3MCODE
		  AND L3SCODE = P_L3SCODE ;
  
	END IF ; 
  
END P1  ; 
  