

DROP PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS2_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS2_ADD ( 
	IN P_PBC2NTCODE  VARCHAR(2),
	IN P_PBC2LCODE   VARCHAR(3),
	IN P_PBC2MCODE   VARCHAR(3),
	IN P_PBC2NAME    VARCHAR(100),
	IN P_PBC2BIGO    VARCHAR(200),
	IN P_PBC2HISAB   VARCHAR(6)	
	) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_BOARD_CLASS2_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF NOT EXISTS(	SELECT PBC2LCODE FROM PSSCMLIB.PSM_BOARD_CLASS2 WHERE PBC2NTCODE = P_PBC2NTCODE AND PBC2LCODE = P_PBC2LCODE AND  PBC2MCODE = P_PBC2MCODE ) THEN
  
		INSERT INTO PSSCMLIB.PSM_BOARD_CLASS2 ( 
				PBC2NTCODE ,
				PBC2LCODE  ,
				PBC2MCODE  ,
				PBC2NAME   ,
				PBC2BIGO   ,
				PBC2HIGB   ,
				PBC2HIDAT  ,
				PBC2HITIM  ,
				PBC2HISAB  
			) VALUES (
				P_PBC2NTCODE ,
				P_PBC2LCODE  ,
				P_PBC2MCODE  ,
				P_PBC2NAME   ,
				P_PBC2BIGO   ,
					  'A'  ,
				CURRENT_DATE ,
				CURRENT_TIME ,
				P_PBC2HISAB
			);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_BOARD_CLASS2
		 SET    PBC2NAME   = P_PBC2NAME,
			PBC2BIGO   = P_PBC2BIGO,
			PBC2HIGB   =  'C',
			PBC2HIDAT  = CURRENT_DATE,
			PBC2HITIM  = CURRENT_TIME,
			PBC2HISAB  = P_PBC2HISAB 
		WHERE PBC2NTCODE = P_PBC2NTCODE
		  AND PBC2LCODE = P_PBC2LCODE
		  AND PBC2MCODE = P_PBC2MCODE;
  
	END IF ; 
  
END P1  ; 
  