DROP PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MENU_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MENU_LIST
( 
	
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (
		SELECT   DISTINCT
			1 as LVL, 
			'AAA' AS UP_MENU_NO,
			JSMBLASS AS MENU_NO,                        
			'' AS MENU_NAME,
			'' AS INDEX
			FROM PSSCMLIB.PSM_JSA_MASTER
		 ), TABLE2 AS (
		SELECT  ROWNUMBER() OVER(order by LVL, int(MENU_NO)) AS rownum,  LVL, UP_MENU_NO, MENU_NO,   MENU_NAME, J1NAME AS CODE_NAME
		FROM TABLE1
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
		ON   J1CODE = MENU_NO
		)

		SELECT
		DISTINCT
		LVL,
		UP_MENU_NO,
		MENU_NO,
		MENU_NAME,
		CODE_NAME
		FROM
		(
		SELECT LVL, UP_MENU_NO, MENU_NO,   MENU_NAME,  CODE_NAME
		FROM TABLE2
		UNION  ALL
		SELECT   2 AS LVL,
			 A.JSMBLASS AS UP_MENU_NO,
			 A.JSMBLASS||'_'||A.JSMMLASS AS MENU_NO,
			 A.JSMMLASS AS MENU_NAME,
			 A.JSMMLASS || '_' || (SELECT J2NAME FROM PSSCMLIB.PSM_JSA_CLASS2 WHERE J2BCODE = A.JSMBLASS AND J2MCODE = A.JSMMLASS)  AS CODE_NAME
		FROM    PSSCMLIB.PSM_JSA_MASTER A

		UNION  ALL

		SELECT   3 AS LVL,
			 B.JSMBLASS||'_'||B.JSMMLASS AS UP_MENU_NO,
			 B.JSMBLASS||'_'||B.JSMMLASS||'_'||B.JSMSLASS AS MENU_NO,
			 B.JSMSLASS AS MENU_NAME,
			 B.JSMSLASS || '_' || (SELECT J3NAME FROM PSSCMLIB.PSM_JSA_CLASS3 WHERE J3BCODE = B.JSMBLASS AND J3MCODE = B.JSMMLASS AND J3SCODE = B.JSMSLASS)  AS CODE_NAME
		FROM    PSSCMLIB.PSM_JSA_MASTER B

		UNION  ALL

		SELECT   4 AS LVL,
			 C.JSMBLASS||'_'||C.JSMMLASS||'_'||C.JSMSLASS AS UP_MENU_NO,
			 C.JSMBLASS||'_'||C.JSMMLASS||'_'||C.JSMSLASS||'_'||DIGITS(C.JSMSEQ) AS MENU_NO,
			 C.JSMWKNAME AS MENU_NAME,
			 C.JSMWKNAME AS CODE_NAME
		FROM PSSCMLIB.PSM_JSA_MASTER AS C
		) AS TEMP
		ORDER BY LVL, UP_MENU_NO, MENU_NO;

		
	OPEN REFCURSOR;

END