--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_RUN ( 
	IN P_L2SAUP VARCHAR(1) , 
	IN P_L2BCODE VARCHAR(1) , 
	IN P_L2MCODE VARCHAR(4) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT  L2SAUP   , 
			L2BCODE  , 
			L1NAME AS L2BCODENM,
			DIGITS(L2MCODE) AS L2MCODE  , 
			L2NAME   , 
			L2BIGO    ,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_LOCATION_CLASS3 WHERE L3SAUP = L2SAUP AND L3BCODE = L2BCODE AND L3MCODE = L2MCODE) >0 THEN 'Y' ELSE 'N' END L3GUBUN
		FROM PSSCMLIB.PSM_LOCATION_CLASS2
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS1 
		ON L1SAUP = L2SAUP 
		AND L1CODE = L2BCODE 
		WHERE L2SAUP  = P_L2SAUP
		  AND L2BCODE = P_L2BCODE
		  AND L2MCODE = P_L2MCODE
  
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_RUN 
TO LSHPDM WITH GRANT OPTION ;
