

DROP PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_ADD ( 
	IN P_C2SAUP VARCHAR(1) , 
	IN P_C2BCODE VARCHAR(2) , 
	IN P_C2MCODE VARCHAR(4) , 
	IN P_C2NAME VARCHAR(100) , 
	IN P_C2BIGO VARCHAR(100) ,
	IN P_C2HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO TYSCMLIB.ACFIXCLASS2 (
		FXC2SAUP  ,  
		FXC2BCODE ,  
		FXC2MCODE ,  
		FXC2DESC  ,  
		FXC2BIGO  ,  
		FXC2HIGB  ,  
		FXC2HIDAT ,  
		FXC2HITIM ,  
		FXC2HISAB)
		VALUES(
		P_C2SAUP  ,  
		P_C2BCODE ,  
		P_C2MCODE ,  
		P_C2NAME  ,  
		P_C2BIGO  ,  
		'A'  ,  
		CURRENT_DATE ,  
		CURRENT_TIME ,  
		P_C2HISAB
		);
  
	ELSE 
  
		UPDATE TYSCMLIB.ACFIXCLASS2 SET
		FXC2DESC  = P_C2NAME,
		FXC2BIGO  = P_C2BIGO,
		FXC2HIGB  = 'C',
		FXC2HIDAT = CURRENT_DATE,
		FXC2HITIM = CURRENT_TIME,
		FXC2HISAB = P_C2HISAB
		WHERE FXC2SAUP  = P_C2SAUP
		AND   FXC2BCODE = P_C2BCODE
		AND   FXC2MCODE = P_C2MCODE ;
  
	END IF ; 
  
END P1  ; 
  