--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1050_RISKCODE_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1050_RISKCODE_DEL ( 
	IN P_RSYEAR VARCHAR(4), 
	IN P_RSSEQ VARCHAR(3)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1050_RISKCODE_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE
		FROM PSSCMLIB.PSM_RISKCODE_VER
		WHERE RSYEAR = P_RSYEAR
		AND RSSEQ = P_RSSEQ ;

		DELETE FROM PSSCMLIB.PSM_RISKCODE_MASTER
		WHERE RMYEAR = P_RSYEAR
		AND RMSEQ = P_RSSEQ ;

		DELETE FROM PSSCMLIB.PSM_RISKCODE_LIST
		WHERE RLYEAR = P_RSYEAR
		AND RLSEQ = P_RSSEQ ;
  
END P1  ; 
  