

DROP PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_ADD ( 
	IN P_C3SAUP VARCHAR(1) , 
	IN P_C3BCODE VARCHAR(2) , 
	IN P_C3MCODE VARCHAR(4) , 
	IN P_C3SCODE VARCHAR(3) , 
	IN P_C3NAME VARCHAR(100) ,
	IN P_C3LINKCODE1 VARCHAR(10) , 
	IN P_C3LINKCODE2 VARCHAR(10) , 
	IN P_C3BIGO VARCHAR(100) ,
	IN P_C3HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO  TYSCMLIB.ACFIXCLASS3
		( 
		FXC3SAUP     , 
		FXC3BCODE    , 
		FXC3MCODE    , 
		FXC3SCODE    , 
		FXC3DESC     , 
		FXC3LINKCODE1, 
		FXC3LINKCODE2, 
		FXC3BIGO    , 
		FXC3HIGB    , 
		FXC3HIDAT   , 
		FXC3HITIM   , 
		FXC3HISAB   
		)
		VALUES
		(
		P_C3SAUP     , 
		P_C3BCODE    , 
		P_C3MCODE    , 
		P_C3SCODE    , 
		P_C3NAME     , 
		P_C3LINKCODE1, 
		P_C3LINKCODE2, 
		P_C3BIGO    , 
		'A'    , 
		CURRENT_DATE   , 
		CURRENT_TIME   , 
		P_C3HISAB   
		);
  
	ELSE 
  
		UPDATE TYSCMLIB.ACFIXCLASS3 SET
		FXC3DESC      = P_C3NAME, 
		FXC3LINKCODE1 = P_C3LINKCODE1,
		FXC3LINKCODE2 = P_C3LINKCODE2, 
		FXC3BIGO      = P_C3BIGO, 
		FXC3HIGB      = 'C', 
		FXC3HIDAT     = CURRENT_DATE, 
		FXC3HITIM     = CURRENT_TIME,
		FXC3HISAB     = P_C3HISAB
		WHERE FXC3SAUP  = P_C3SAUP
		AND   FXC3BCODE = P_C3BCODE
		AND   FXC3MCODE = P_C3MCODE
		AND   FXC3SCODE = P_C3SCODE ;
  
	END IF ; 
  
END P1  ; 
  