--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1081_JSA_CLASS3_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1081_JSA_CLASS3_DEL ( 
	IN P_J3BCODE VARCHAR(2),
	IN P_J3MCODE VARCHAR(2),
	IN P_J3SCODE VARCHAR(3)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1081_JSA_CLASS3_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM  PSSCMLIB.PSM_JSA_CLASS3 
		WHERE J3BCODE = P_J3BCODE
		AND   J3MCODE = P_J3MCODE
		AND   J3SCODE = P_J3SCODE ;
  
END P1  ; 
  