DROP PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_STRESULT_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_STRESULT_ADD ( 
	IN P_CSTSBCODE VARCHAR(1) , 
	IN P_CSTGRCODE VARCHAR(2) , 
	IN P_CSTGRSEQ VARCHAR(4) , 
	IN P_CSTITEMNUM VARCHAR(2) ,
	IN P_CSTSEQ VARCHAR(2) ,
	IN P_CSTACTDESC VARCHAR(400) ,
	IN P_CSTADVDESC VARCHAR(400) ,
	IN P_CSTWRSABUN VARCHAR(6),
	IN P_CSTWRDATE VARCHAR(8),
	IN P_CSTHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1072_CHECKLIST_STRESULT_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_CHECKLIST_STRESULT
		(
		CSTSBCODE,
		CSTGRCODE,
		CSTGRSEQ,
		CSTITEMNUM,
		CSTSEQ,
		CSTACTDESC,
		CSTADVDESC,
		CSTWRSABUN,
		CSTWRDATE,
		CSTHIGB,
		CSTHIDAT,
		CSTHITIM,
		CSTHISAB
		)
		VALUES
		(
		P_CSTSBCODE,
		P_CSTGRCODE,
		P_CSTGRSEQ,
		P_CSTITEMNUM,
		P_CSTSEQ,
		P_CSTACTDESC,
		P_CSTADVDESC,
		P_CSTWRSABUN,
		P_CSTWRDATE,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_CSTHISAB
		)
		;
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_CHECKLIST_STRESULT SET
		CSTACTDESC = P_CSTACTDESC ,
		CSTADVDESC = P_CSTADVDESC ,
		CSTWRSABUN = P_CSTWRSABUN ,
		CSTWRDATE = P_CSTWRDATE ,
		CSTHIGB = 'C',
		CSTHIDAT = CURRENT_DATE,
		CSTHITIM = CURRENT_TIME,
		CSTHISAB = P_CSTHISAB 
		WHERE CSTSBCODE  = P_CSTSBCODE
		AND   CSTGRCODE  = P_CSTGRCODE 
		AND   CSTGRSEQ   = P_CSTGRSEQ 
		AND   CSTITEMNUM = P_CSTITEMNUM 
		AND   CSTSEQ     = P_CSTSEQ  ;
  
	END IF ; 
  
END P1  ; 
  