

DROP PROCEDURE PSSCMLIB.PSM_PSM1071_CHECKLIST_MCODE_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1071_CHECKLIST_MCODE_ADD ( 
	IN P_CMSBCODE VARCHAR(1) , 
	IN P_CMGRCODE VARCHAR(2) , 
	IN P_CMGRSEQ VARCHAR(4) , 
	IN P_CMMCNUM VARCHAR(30) ,
	IN P_CMDESC VARCHAR(200) ,
	IN P_CMWRSABUN VARCHAR(6) ,
	IN P_CMWRDATE VARCHAR(8) ,
	IN P_CMHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1071_CHECKLIST_MCODE_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_CHECKLIST_MCODE
		(
		CMSBCODE,
		CMGRCODE,
		CMGRSEQ,
		CMMCNUM,
		CMDESC,
		CMWRSABUN,
		CMWRDATE,
		CMHIGB,
		CMHIDAT,
		CMHITIM,
		CMHISAB
		)
		VALUES
		(
		P_CMSBCODE,
		P_CMGRCODE,
		P_CMGRSEQ,
		P_CMMCNUM,
		P_CMDESC,
		P_CMWRSABUN,
		P_CMWRDATE,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_CMHISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_CHECKLIST_MCODE SET
		CMMCNUM = P_CMMCNUM,
		CMDESC = P_CMDESC,
		CMWRSABUN = P_CMWRSABUN,
		CMWRDATE = P_CMWRDATE,
		CMHIGB = 'C',
		CMHIDAT = CURRENT_DATE,
		CMHITIM = CURRENT_TIME,
		CMHISAB = P_CMHISAB
		WHERE CMSBCODE = P_CMSBCODE
		AND   CMGRCODE = P_CMGRCODE 
		AND   CMGRSEQ  = P_CMGRSEQ  ;
  
	END IF ; 
  
END P1  ; 
  