DROP PROCEDURE PSSCMLIB.PSM_PSM1050_RISKCODE_VER_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM1050_RISKCODE_VER_LIST
( 
	
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS(
			SELECT DISTINCT
			1 AS LVL,
			'0' AS UP_MENU_NO,
			'1111' AS MENU_NO,
			'UTT' AS MENU_NAME
			FROM PSSCMLIB.PSM_RISKCODE_VER
			WHERE RSUSDPMK = 'T'
		UNION ALL
			SELECT DISTINCT
			1 AS LVL,
			'0' AS UP_MENU_NO,
			'2222' AS MENU_NO,
			'SILO' AS MENU_NAME
			FROM PSSCMLIB.PSM_RISKCODE_VER
			WHERE RSUSDPMK = 'S'
		)
		 SELECT
		LVL, UP_MENU_NO, MENU_NO, MENU_NAME
		FROM TABLE1
		UNION ALL
			SELECT 2 AS LVL,
			CASE WHEN A.RSUSDPMK = 'T' THEN '1111' ELSE '2222' END AS UP_MENU_NO,
			CAST(A.RSSEQ AS VARCHAR(4)) AS MENU_NO ,
			CAST((A.RSYEAR ||'_'|| DIGITS(A.RSSEQ)) AS VARCHAR(8)) AS MENU_NAME
		FROM PSSCMLIB.PSM_RISKCODE_VER
		 A



		ORDER BY LVL, UP_MENU_NO, MENU_NAME;

		
	OPEN REFCURSOR;

END