

DROP PROCEDURE PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_ADD ( 
	IN P_C1SAUP VARCHAR(1) , 
	IN P_C1CODE VARCHAR(2) , 
	IN P_C1NAME VARCHAR(100) , 
	IN P_C1BIGO VARCHAR(100) ,
	IN P_C1HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO TYSCMLIB.ACFIXCLASS1 ( 
		FXC1SAUP ,
		FXC1CODE , 
		FXC1DESC , 
		FXC1BIGO , 
		FXC1HIGB , 
		FXC1HIDAT, 
		FXC1HITIM, 
		FXC1HISAB
		) VALUES (
		P_C1SAUP  ,
		P_C1CODE , 
		P_C1NAME , 
		P_C1BIGO , 
		'A' , 
		CURRENT_DATE, 
		CURRENT_TIME, 
		P_C1HISAB
		);
  
	ELSE 
  
		UPDATE TYSCMLIB.ACFIXCLASS1 SET
		FXC1DESC  = P_C1NAME, 
		FXC1BIGO  = P_C1BIGO, 
		FXC1HIGB  = 'C', 
		FXC1HIDAT = CURRENT_DATE, 
		FXC1HITIM = CURRENT_TIME, 
		FXC1HISAB = P_C1HISAB
		WHERE FXC1SAUP = P_C1SAUP
		AND   FXC1CODE = P_C1CODE ;
  
	END IF ; 
  
END P1  ; 
  