--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_DEL ( 
	IN P_L1SAUP VARCHAR(1), 
	IN P_L1CODE VARCHAR(1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_LOCATION_CLASS1 
		WHERE L1SAUP = P_L1SAUP
		  AND L1CODE = P_L1CODE
		 ;
  
END P1  ; 
  