DROP PROCEDURE TYJINFWLIB.PSM_IMGSIGN_DEL;

CREATE PROCEDURE TYJINFWLIB.PSM_IMGSIGN_DEL 
(
	  P_IMGSABUN       VARCHAR (10) 
)
	LANGUAGE SQL
P1: BEGIN

        DELETE FROM TYSCMLIB.PSM_IMGSIGN
		WHERE	IMGSABUN = P_IMGSABUN;

END P1