--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1110_MCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_MCODE_LIST ( 
	IN P_PBC2LCODE VARCHAR(3)
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_MCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			'' AS PBC2MCODE,
			'' AS PBC2MCODENM,
			'전체' AS PBC2MCODENAME
			FROM SYSIBM.SYSDUMMY1			

			UNION ALL
			
			SELECT  
		 		    PBC2MCODE  , 
				    PBC2NAME AS PBC2MCODENM,
				    PBC2MCODE||'-'||PBC2NAME   AS PBC2MCODENAME 				    
			FROM PSSCMLIB.PSM_BOARD_CLASS2
			WHERE  PBC2LCODE =  P_PBC2LCODE			   
			ORDER BY PBC2MCODE ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 