--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSP1091_SACODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSP1091_SACODE_LIST ( 
	IN P_CDINDEX VARCHAR(2), 
	IN P_CDCODE VARCHAR(100)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSP1091_SACODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			CDCODE AS CODE,
			CDDESC1 AS NAME,
			'Y' AS CHK
			FROM PSSCMLIB.PSM_CODEMF
			WHERE CDINDEX = P_CDINDEX
			AND   CDCODE IN( SELECT * FROM TABLE(PSSCMLIB.SF_GB_RevColRow(CAST(P_CDCODE AS VARCHAR(100)), ',')) AS InTable )

			UNION ALL

			SELECT
			CDCODE AS CODE,
			CDDESC1 AS NAME,
			'N' AS CHK
			FROM PSSCMLIB.PSM_CODEMF
			WHERE CDINDEX = P_CDINDEX
			AND   CDCODE NOT IN( SELECT * FROM TABLE(PSSCMLIB.SF_GB_RevColRow(CAST(P_CDCODE AS VARCHAR(100)), ',')) AS InTable )

			ORDER BY CODE ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 