--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_DEL ( 
	IN P_J2BCODE VARCHAR(2),
	IN P_J2MCODE VARCHAR(2)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1082_JSA_CLASS2_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_JSA_CLASS2
		WHERE J2BCODE = P_J2BCODE
		AND   J2MCODE = P_J2MCODE ;
  
END P1  ; 
  