--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1083_JSA_CLASS1_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1083_JSA_CLASS1_RUN ( 
	IN P_J1CODE VARCHAR(2)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1083_JSA_CLASS1_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		J1CODE,
		J1NAME ,
		J1CODE||'-'||J1NAME AS J1CODENAME,
		J1BIGO,
		CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_JSA_CLASS2 WHERE J2BCODE = J1CODE) > 0 THEN 'Y' ELSE 'N' END AS J2GUBUN
		FROM PSSCMLIB.PSM_JSA_CLASS1
		WHERE J1CODE = P_J1CODE 
		ORDER BY J1CODE
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 