--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1030_BCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1030_BCODE_LIST ( 
	IN P_SAUP VARCHAR(1) ,
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1030_BCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			'' AS C1SAUP,
			'' AS C1CODE,
			'' AS C1NAME,
			'전체' AS C1CODENAME
			FROM SYSIBM.SYSDUMMY1
			WHERE CASE WHEN P_GUBUN = '' THEN '1' ELSE '' END = CASE WHEN P_GUBUN = '' THEN '2' ELSE '' END

			UNION ALL
			 
			SELECT
			FXC1SAUP AS C1SAUP,
			FXC1CODE AS  C1CODE,
			FXC1DESC AS   C1NAME,  
			FXC1CODE||'-'||FXC1DESC AS C1CODENAME
			FROM  TYSCMLIB.ACFIXCLASS1
			WHERE FXC1CODE IN('20', '30', '40', '90')
			AND   FXC1SAUP = P_SAUP
			ORDER BY C1SAUP,C1CODE ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 