--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_RUN ( 
	IN P_C1SAUP VARCHAR(1) , 
	IN P_C1CODE VARCHAR(2)  ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		FXC1SAUP AS C1SAUP, 
		FXC1CODE AS C1CODE,
		FXC1DESC AS C1NAME,
		FXC1BIGO AS C1BIGO ,
		CASE WHEN (SELECT COUNT(*) FROM TYSCMLIB.ACFIXCLASS2 WHERE FXC2SAUP = FXC1SAUP AND FXC2BCODE = FXC1CODE) > 0 THEN 'Y' ELSE 'N' END C2GUBUN
		FROM TYSCMLIB.ACFIXCLASS1
		WHERE FXC1SAUP = P_C1SAUP
		AND   FXC1CODE = P_C1CODE
  
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
