--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","LSHPDM" ; 

DROP PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_DEL ( 
	IN P_C3SAUP VARCHAR(1), 
	IN P_C3BCODE VARCHAR(2),
	IN P_C3MCODE VARCHAR(4),
	IN P_C3SCODE VARCHAR(3)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM TYSCMLIB.ACFIXCLASS3
		WHERE FXC3SAUP  = P_C3SAUP
		AND   FXC3BCODE = P_C3BCODE
		AND   FXC3MCODE = P_C3MCODE
		AND   FXC3SCODE = P_C3SCODE ;
  
END P1  ; 