--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_SEQ ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_SEQ ( 
	IN P_C3SAUP VARCHAR(1),
	IN P_C3BCODE VARCHAR(2),
	IN P_C3MCODE VARCHAR(4)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_SEQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT   VALUE(MAX(FXC3SCODE), 0) + 1 AS C3SCODE
			FROM TYSCMLIB.ACFIXCLASS3 
			WHERE FXC3SAUP  = P_C3SAUP
			 AND  FXC3BCODE = P_C3BCODE
			 AND  FXC3MCODE = P_C3MCODE;
			
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 