

DROP PROCEDURE PSSCMLIB.PSM_PSM1040_TKCHANGE_FACTOR_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1040_TKCHANGE_FACTOR_ADD ( 
	IN P_TCNUM VARCHAR(2) , 
	IN P_TCCHFANAME VARCHAR(200) , 
	IN P_TCATTACH VARCHAR(1) , 
	IN P_TCTHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1040_TKCHANGE_FACTOR_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_TKCHANGE_FACTOR (
		TCNUM, 
		TCCHFANAME, 
		TCATTACH ,
		TCTHIGB, 
		TCTHIDAT, 
		TCTHITIM, 
		TCTHISAB)
		VALUES		
		(P_TCNUM,
		P_TCCHFANAME,
		P_TCATTACH,
		'A',
		CURRENT DATE,
		CURRENT TIME,
		P_TCTHISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_TKCHANGE_FACTOR
		SET	TCATTACH = P_TCATTACH,
		    TCCHFANAME = P_TCCHFANAME,
			TCTHIGB = 'C',
			TCTHIDAT = CURRENT DATE,
			TCTHITIM = CURRENT TIME,
			TCTHISAB = P_TCTHISAB
		WHERE	TCNUM = P_TCNUM ;
  
	END IF ; 
  
END P1  ; 
  