--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MASTER_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MASTER_DEL ( 
	IN P_JSMBLASS VARCHAR(2) , 
	IN P_JSMMLASS VARCHAR(2) , 
	IN P_JSMSLASS VARCHAR(3) , 
	IN P_JSMSEQ NUMERIC(3,0)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1090_JSA_MASTER_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
		-- 마스터 삭제
		DELETE FROM PSSCMLIB.PSM_JSA_MASTER
		WHERE JSMBLASS = P_JSMBLASS
		AND   JSMMLASS = P_JSMMLASS
		AND   JSMSLASS = P_JSMSLASS
		AND   JSMSEQ   = P_JSMSEQ ;

		-- 안전장비 삭제
		DELETE
		FROM PSSCMLIB.PSM_JSA_MSAFETOOL
		WHERE JSTBLASS = P_JSMBLASS
		AND   JSTMLASS = P_JSMMLASS
		AND   JSTSLASS = P_JSMSLASS
		AND   JSTSEQ   = P_JSMSEQ ;

		-- 디테일 삭제
		DELETE
		FROM PSSCMLIB.PSM_JSA_DETAIL
		WHERE JSDBLASS = P_JSMBLASS
		AND   JSDMLASS = P_JSMMLASS
		AND   JSDSLASS = P_JSMSLASS
		AND   JSDSEQ   = P_JSMSEQ ;

		-- 위험성 삭제
		DELETE
		FROM PSSCMLIB.PSM_JSA_RISK
		WHERE JSRBLASS = P_JSMBLASS
		AND   JSRMLASS = P_JSMMLASS
		AND   JSRSLASS = P_JSMSLASS
		AND   JSRSEQ   = P_JSMSEQ ;

		-- 개선대책 삭제
		DELETE
		FROM PSSCMLIB.PSM_JSA_REFORM
		WHERE JSEBLASS = P_JSMBLASS
		AND   JSEMLASS = P_JSMMLASS
		AND   JSESLASS = P_JSMSLASS
		AND   JSESEQ   = P_JSMSEQ ;

		-- 첨부파일 삭제
		DELETE FROM PSSCMLIB . PSM_CMN_ATTACH
		WHERE ATTACH_TYPE = 'JSA'
		AND    SUBSTR(ATTACH_NO,1,2) = P_JSMBLASS
		AND    SUBSTR(ATTACH_NO,3,2) = P_JSMSLASS
		AND    SUBSTR(ATTACH_NO,5,3) = P_JSMMLASS
		AND    CAST(SUBSTR(ATTACH_NO,8,3) AS NUMERIC(3, 0)) = P_JSMSEQ ;
  
END P1  ; 
  