--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1031_SAFEORDER_CHECK ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1031_SAFEORDER_CHECK ( 
	IN P_C3SAUP VARCHAR(1), 
	IN P_C3BCODE VARCHAR(2),
	IN P_C3MCODE VARCHAR(4),
	IN P_C3SCODE VARCHAR(3)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1031_SAFEORDER_CHECK 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			
			SELECT  COUNT(*) AS CNT
			FROM PSSCMLIB.PSM_SafeOrder_MASTER
			 LEFT OUTER JOIN (SELECT CAST(P_C3SAUP||P_C3BCODE||P_C3MCODE||P_C3SCODE AS VARCHAR(10))  AS AREACODE    FROM SYSIBM.SYSDUMMY1) AS PAR
				 ON 1 = 1
			WHERE (SMSYSTEMCODE1 = PAR.AREACODE OR SMSYSTEMCODE2 = PAR.AREACODE OR SMSYSTEMCODE3 = PAR.AREACODE OR SMSYSTEMCODE4 = PAR.AREACODE OR SMSYSTEMCODE5 = PAR.AREACODE) ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 