DROP PROCEDURE PSSCMLIB.PSM_TEMP_ATTACH_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_TEMP_ATTACH_DEL 
(
	  P_ATTACH_TYPE      VARCHAR (50) ,
	  P_ATTACH_UNID      VARCHAR (50) 
)
	LANGUAGE SQL
P1: BEGIN

        DELETE FROM PSSCMLIB.PSM_TEMP_ATTACH 
		WHERE	ATTACH_TYPE = P_ATTACH_TYPE
		  AND   ATTACH_UNID = P_ATTACH_UNID;

END P1