--DROP PROCEDURE TYJINFWLIB.PSM_IMGSIGN_ADD;

CREATE PROCEDURE TYJINFWLIB.PSM_IMGSIGN_ADD 
(
	  P_IMGSABUN       VARCHAR (10) 
	, P_IMGFILENAME    VARCHAR (50) 
	, P_IMGFILESIZE    NUMERIC(8,0)
	, P_IMGSIGN        BLOB
)
	LANGUAGE SQL
P1: BEGIN
	
	IF NOT EXISTS(	SELECT P_IMGSABUN FROM TYSCMLIB.PSM_ImgSign WHERE IMGSABUN = P_IMGSABUN	) THEN

		INSERT INTO  TYSCMLIB.PSM_ImgSign 
		(
			IMGSABUN, IMGFILENAME, IMGFILESIZE, IMGSIGN 
		)
		VALUES
		(
			P_IMGSABUN, P_IMGFILENAME, P_IMGFILESIZE, P_IMGSIGN 
		);

	ELSE

		UPDATE TYSCMLIB.PSM_ImgSign 
		SET
			IMGFILENAME = P_IMGFILENAME, 
			IMGFILESIZE = P_IMGFILESIZE, 
			IMGSIGN  = P_IMGSIGN
		WHERE IMGSABUN= P_IMGSABUN;		

	END IF;

END P1