--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1030_MCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1030_MCODE_LIST ( 
	IN P_SAUP VARCHAR(1),
	IN P_BCODE VARCHAR(2),
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1030_MCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			'' AS C2SAUP,
			'' AS C2BCODE,
			'' AS C2BCODENM,
			'' AS C2MCODE,
			'' AS C2NAME,
			'전체' AS C2CODENAME,
			'' AS C2BIGO
			FROM SYSIBM.SYSDUMMY1
			WHERE CASE WHEN P_GUBUN = '' THEN '1' ELSE '' END = CASE WHEN P_GUBUN = '' THEN '2' ELSE '' END

			UNION ALL
			 
			SELECT
			FXC2SAUP AS C2SAUP, 
			FXC2BCODE AS C2BCODE , 
			FXC1DESC AS C2BCODENM,
			DIGITS(FXC2MCODE) AS C2MCODE,
			FXC2DESC AS C2NAME, 
			DIGITS(FXC2MCODE)||'-'||FXC2DESC AS C2CODENAME,
			FXC2BIGO AS C2BIGO    
			FROM TYSCMLIB.ACFIXCLASS2
			LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS1
			      ON   FXC1SAUP   = FXC2SAUP
			    AND   FXC1CODE  = FXC2BCODE
			WHERE FXC2BCODE IN('20', '30', '40', '90')
			AND    FXC2SAUP =  P_SAUP
			AND    FXC2BCODE = P_BCODE
			ORDER BY C2SAUP, C2BCODE, C2MCODE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 