--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MASTER_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MASTER_RUN ( 
	IN P_JSMBLASS VARCHAR(2),
	IN P_JSMMLASS VARCHAR(2),
	IN P_JSMSLASS VARCHAR(3),
	IN P_JSMSEQ VARCHAR(3)) 
	DYNAMIC RESULT SETS 3 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1090_JSA_MASTER_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 矫累 
MAIN : BEGIN  -- 角青何 
	LIST : BEGIN  -- 府胶飘 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		JSMBLASS     ,
		J1NAME AS JBCODE,
		JSMMLASS     ,
		J2NAME AS JMCODE,
		JSMSLASS     ,
		J3NAME AS JSCODE,
		JSMSEQ       ,
		JSMWKNAME    ,
		JSMSYSTEM    ,
		JSMWKDATE    ,
		JSMADDATE    ,
		JSMADCHASU   ,
		JSMWKSABUN   ,
		KBHANGL AS JSMWKSABUNNM,
		JSMSECTIONNUM,
		H1CODE.CDDESC1 AS H1CODE,
		JSMMSDSCODE  ,
		JSMMSDSSEQ   ,
		JSMWKSUMMARY ,
		JSMNEEDDATA  ,
		JSMRISKCASE  ,
		JSMSELFNAME1 ,
		JSMSELFTEXT1 ,
		JSMSELFNAME2 ,
		JSMSELFTEXT2 ,
		JSMSELFNAME3 ,
		JSMSELFTEXT3 ,
		JSMSELFNAME4 ,
		JSMSELFTEXT4 ,
		JSMSELFNAME5 ,
		JSMSELFTEXT5 ,
		JSMSCOMNAME1 ,
		JSMSCOMTEXT1 ,
		JSMSCOMNAME2 ,
		JSMSCOMTEXT2 ,
		JSMSANAME,
		'' AS JSMPODATE
		FROM PSSCMLIB.PSM_JSA_MASTER
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1 AS JBCODE
		ON    JSMBLASS = J1CODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2 AS JMCODE
		ON    JSMBLASS = J2BCODE
		AND   JSMMLASS = J2MCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3 AS JSCODE
		ON    JSMBLASS = J3BCODE
		AND   JSMMLASS = J3MCODE
		AND   JSMSLASS = J3SCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF AS H1CODE
		ON        'H1' = H1CODE.CDINDEX
		AND   JSMSECTIONNUM = H1CODE.CDCODE
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF KB
		ON  KB.KBSABUN = JSMWKSABUN
		WHERE JSMBLASS = P_JSMBLASS
		AND   JSMMLASS = P_JSMMLASS
		AND   JSMSLASS = P_JSMSLASS
		AND   JSMSEQ   = P_JSMSEQ
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 

	SACODE : BEGIN  -- 其捞隆 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR  -- 目辑积己 
				SELECT
				JSTSAFECODE AS CODE,
				JSTSAFENAME AS NAME
				FROM PSSCMLIB.PSM_JSA_MSAFETOOL
				WHERE JSTBLASS = P_JSMBLASS
				AND    JSTMLASS = P_JSMMLASS
				AND    JSTSLASS = P_JSMSLASS
				AND    JSTSEQ = P_JSMSEQ
				AND    JSTCODEGUBN = '1' ;
			OPEN REFCURSOR2 ; 
	END SACODE ; 

	TOCODE : BEGIN  -- 其捞隆 
			DECLARE REFCURSOR3 CURSOR WITH RETURN FOR  -- 目辑积己 
				SELECT
				JSTSAFECODE AS CODE,
				JSTSAFENAME AS NAME
				FROM PSSCMLIB.PSM_JSA_MSAFETOOL
				WHERE JSTBLASS = P_JSMBLASS
				AND    JSTMLASS = P_JSMMLASS
				AND    JSTSLASS = P_JSMSLASS
				AND    JSTSEQ = P_JSMSEQ
				AND    JSTCODEGUBN = '2' ;
			OPEN REFCURSOR3 ; 
	END TOCODE ; 
  
END MAIN ; 
END  ; 
  
