

DROP PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS1_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS1_ADD ( 
	IN P_PBC1LCODE   VARCHAR(3),
	IN P_PBC1NTCODE   VARCHAR(2),
	IN P_PBC1NAME    VARCHAR(100),
	IN P_PBC1BIGO    VARCHAR(200),
	IN P_PBC1HISAB   VARCHAR(6)	
	) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_BOARD_CLASS1_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF NOT EXISTS(	SELECT PBC1LCODE FROM PSSCMLIB.PSM_BOARD_CLASS1 WHERE PBC1LCODE = P_PBC1LCODE AND   PBC1NTCODE = P_PBC1NTCODE) THEN
  
		INSERT INTO  PSSCMLIB.PSM_BOARD_CLASS1 ( 
				PBC1LCODE ,
				PBC1NTCODE ,
				PBC1NAME  ,
				PBC1BIGO  ,
				PBC1HIGB  ,
				PBC1HIDAT ,
				PBC1HITIM ,
				PBC1HISAB 
			) VALUES (

	   		        P_PBC1LCODE ,
			        P_PBC1NTCODE ,
				P_PBC1NAME  ,
				P_PBC1BIGO  ,
				'A'  ,
				CURRENT_DATE ,
				CURRENT_TIME ,
				P_PBC1HISAB 
			);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_BOARD_CLASS1
		 SET PBC1NAME   = P_PBC1NAME,
			 PBC1BIGO  = P_PBC1BIGO,
			 PBC1HIGB  =  'C',
			 PBC1HIDAT = CURRENT_DATE,
			 PBC1HITIM  = CURRENT_TIME,
			 PBC1HISAB = P_PBC1HISAB
		WHERE PBC1LCODE = P_PBC1LCODE
	    AND   PBC1NTCODE = P_PBC1NTCODE;
  
	END IF ; 
  
END P1  ; 
  