--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1040_TKCHANGE_FACTOR_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1040_TKCHANGE_FACTOR_DEL ( 
	IN P_TCNUM VARCHAR(2)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1040_TKCHANGE_FACTOR_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM  PSSCMLIB.PSM_TKCHANGE_FACTOR
		WHERE TCNUM = P_TCNUM
		 ;
  
END P1  ; 
  