

DROP PROCEDURE PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_ADD ( 
	IN P_RMYEAR VARCHAR(4) , 
	IN P_RMSEQ VARCHAR(3) , 
	IN P_RMCODE VARCHAR(1) , 
	IN P_RMNAME VARCHAR(100) , 
	IN P_RMHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_RISKCODE_MASTER
		(RMYEAR,
		 RMSEQ,
		 RMCODE,
		 RMNAME,
		 RMHIGB,
		 RMHIDAT,
		 RMHITIM,
		 RMHISAB)
		VALUES
		(P_RMYEAR,
		 P_RMSEQ,
		 P_RMCODE,
		 P_RMNAME,
		 'A',
		 CURRENT_DATE,
		 CURRENT_TIME,
		 P_RMHISAB);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_RISKCODE_MASTER SET
		RMNAME = P_RMNAME,
		RMHIGB = 'C',
		RMHIDAT = CURRENT_DATE,
		RMHITIM = CURRENT_TIME,
		RMHISAB = P_RMHISAB
		WHERE RMYEAR = P_RMYEAR
		AND RMSEQ = P_RMSEQ
		AND RMCODE = P_RMCODE ;

		UPDATE PSSCMLIB.PSM_RISKCODE_LIST SET 
		RLNAME = P_RMNAME,
		RLHIGB = 'C',
		RLHIDAT = CURRENT_DATE,
		RLHITIM = CURRENT_TIME,
		RLHISAB = P_RMHISAB
		WHERE RLYEAR = P_RMYEAR
		AND RLSEQ = P_RMSEQ
		AND RLCODE = P_RMCODE ;
  
	END IF ; 
  
END P1  ; 
  