DROP PROCEDURE PSSCMLIB.PSM_TEMP_ATTACH_ADD;

CREATE PROCEDURE PSSCMLIB.PSM_TEMP_ATTACH_ADD 
(
	  P_ATTACH_TYPE    VARCHAR (50) 
	, P_ATTACH_UNID    VARCHAR (50)
	, P_FILE_NAME      VARCHAR (500)	
	, P_FILE_SIZE      NUMERIC(8,0)
	, P_FILE_PATH      VARCHAR (4000)
	, P_ATTACH_BYTE    BLOB(2G)
)
	LANGUAGE SQL
P1: BEGIN
	
	

		INSERT INTO  PSSCMLIB.PSM_TEMP_ATTACH 
		(
			ATTACH_TYPE, ATTACH_UNID, FILE_NAME, FILE_SIZE,  FILE_PATH, ATTACH_BYTE
		)
		VALUES
		(
			P_ATTACH_TYPE, P_ATTACH_UNID, P_FILE_NAME, P_FILE_SIZE, P_FILE_PATH, P_ATTACH_BYTE
		);

	

END P1