--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1070_CHECKLIST_MENU_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1070_CHECKLIST_MENU_RUN ( 
	IN P_CMSBCODE VARCHAR(1), 
	IN P_CMGRCODE VARCHAR(2),
	IN P_CMGRSEQ VARCHAR(4)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1070_CHECKLIST_MENU_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		CMSBCODE,
		CASE WHEN CMSBCODE = 'T' THEN 'UTT' ELSE 'SILO' END AS CMSBCODENM,
		CMGRCODE,
		CMMCNUM,
		CDDESC1,
		CMGRSEQ,
		CMDESC,
		KBHANGL, 
		SUBSTR(CMWRDATE,1,4) || '-' || SUBSTR(CMWRDATE,5,2) || '-' || SUBSTR(CMWRDATE,7,2) AS CMWRDATE,
		SUBSTR(CMWRDATE,1,4) || '.' || SUBSTR(CMWRDATE,5,2) || '.' || SUBSTR(CMWRDATE,7,2) AS CMWRDATE2
		FROM PSSCMLIB.PSM_CHECKLIST_MCODE ST
		LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF CD
			ON CD.CDINDEX = 'CK'
			AND CD.CDCODE = ST.CMGRCODE
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF MF
			ON MF.KBSABUN = ST.CMWRSABUN
		WHERE CMSBCODE = P_CMSBCODE
		AND   CMGRCODE = P_CMGRCODE 
		AND   CMGRSEQ  = P_CMGRSEQ 
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
