--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1080_JSA_MCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1080_JSA_MCODE_LIST ( 
	IN P_BCODE VARCHAR(2),
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1080_JSA_MCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			'' AS J2BCODE,
			'' AS J2BCODENM,
			'' AS J2MCODE,
			'' AS J2NAME,
			'전체' AS J2CODENAME,
			'' AS J2BIGO
			FROM SYSIBM.SYSDUMMY1
			WHERE CASE WHEN P_GUBUN = '' THEN '1' ELSE '' END = CASE WHEN P_GUBUN = '' THEN '2' ELSE '' END

			UNION ALL
			 
			SELECT
			J2BCODE,
			J1NAME AS J2BCODENM,
			J2MCODE,
			J2NAME,
			J2MCODE||'-'||J2NAME AS J2CODENAME,
			J2BIGO
			FROM PSSCMLIB.PSM_JSA_CLASS2
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
			ON    J1CODE = J2BCODE
			WHERE J2BCODE = P_BCODE
			ORDER BY J2BCODE, J2MCODE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 