--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_REFORM_SEQ ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_REFORM_SEQ ( 
	IN P_JSEBLASS VARCHAR(2),
	IN P_JSEMLASS VARCHAR(2),
	IN P_JSESLASS VARCHAR(3),
	IN P_JSESEQ NUMERIC(3,0),
	IN P_JSEITEMSEQ NUMERIC(3,0)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1093_JSA_REFORM_SEQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT   VALUE(MAX(JSESUBSEQ), 0) + 1 AS JSESUBSEQ
			FROM PSSCMLIB.PSM_JSA_REFORM
			WHERE JSEBLASS = P_JSEBLASS
			AND    JSEMLASS = P_JSEMLASS
			AND    JSESLASS = P_JSESLASS
			AND    JSESEQ = P_JSESEQ
			AND    JSEITEMSEQ = P_JSEITEMSEQ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 

