--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1053_RISKCODE_LIST_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1053_RISKCODE_LIST_RUN ( 
	IN P_RLYEAR VARCHAR(4), 
	IN P_RLSEQ VARCHAR(3),
	IN P_RLCODE VARCHAR(1),
	IN P_RLITEMCODE VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1053_RISKCODE_LIST_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		RLYEAR,
		RLSEQ,
		RLCODE,
		RLITEMCODE,
		RLNAME,
		RLITEMNAME,
		RLRSINDEX0,
		RLRSINDEX1,
		RLRSINDEX2,
		RLRSINDEX3,
		RLHIGB,
		RLHIDAT,
		RLHITIM,
		RLHISAB,
		CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_RISK_MASTER WHERE RMRSSTYEAR = RLYEAR AND RMRSSTSEQ = RLSEQ) > 0 THEN 'Y' ELSE 'N' END RMGUBUN
		FROM PSSCMLIB.PSM_RISKCODE_LIST
		WHERE RLYEAR = P_RLYEAR
		AND RLSEQ = P_RLSEQ
		AND RLCODE = P_RLCODE
		AND RLITEMCODE = P_RLITEMCODE
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
