DROP PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MSAFETOOL_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MSAFETOOL_ADD ( 
	IN P_JSTBLASS VARCHAR(2) , 
	IN P_JSTMLASS VARCHAR(2) , 
	IN P_JSTSLASS VARCHAR(3) , 
	IN P_JSTSEQ NUMERIC(3,0) , 
	IN P_JSTINDX NUMERIC(3,0) , 
	IN P_JSTCODEGUBN VARCHAR(1) , 
	IN P_JSTSAFECODE VARCHAR(3) , 
	IN P_JSTSAFENAME VARCHAR(100) , 
	IN P_SWHISAB VARCHAR(6))
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1090_JSA_MSAFETOOL_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	INSERT INTO PSSCMLIB.PSM_JSA_MSAFETOOL
	(
	JSTBLASS,
	JSTMLASS,
	JSTSLASS,
	JSTSEQ,
	JSTINDX,
	JSTCODEGUBN,
	JSTSAFECODE,
	JSTSAFENAME,
	JSTHIGB,
	JSTHIDAT,
	JSTHITIM,
	JSTHISAB
	)
	VALUES(
	P_JSTBLASS,
	P_JSTMLASS,
	P_JSTSLASS,
	P_JSTSEQ,
	P_JSTINDX,
	P_JSTCODEGUBN,
	P_JSTSAFECODE,
	P_JSTSAFENAME,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_SWHISAB
	); 
  
END P1  ; 
  

