--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:14:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","IKHPDM" ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1010_CODEMF_ADD ( 
	IN P_CDINDEX VARCHAR(10) , 
	IN P_CDCODE VARCHAR(10) , 
	IN P_CDDESC1 VARCHAR(100) , 
	IN P_CDDESC2 VARCHAR(100) , 
	IN P_CDBIGO VARCHAR(100) , 
	IN P_CDHISAB VARCHAR(10) ) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1010_CODEMF_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF NOT EXISTS (	SELECT CDINDEX FROM PSSCMLIB . PSM_CODEMF WHERE CDINDEX = P_CDINDEX AND CDCODE = P_CDCODE	) THEN 
  
		INSERT INTO PSSCMLIB . PSM_CODEMF 
		( 
			CDINDEX , CDCODE , CDDESC1 , CDDESC2 , CDBIGO , CDHIGB , CDHIDAT , CDHITIM , CDHISAB 
		) 
		VALUES 
		( 
			P_CDINDEX , P_CDCODE , P_CDDESC1 , P_CDDESC2 , P_CDBIGO , 'A' , CURRENT_DATE , CURRENT_TIME , P_CDHISAB 
		) ; 
  
	ELSE 
  
		UPDATE PSSCMLIB . PSM_CODEMF 
		SET 
			CDDESC1 = P_CDDESC1 , 
			CDDESC2 = P_CDDESC2 , 
			CDBIGO = P_CDBIGO , 
			CDHIGB = 'C' , 
			CDHIDAT = CURRENT_DATE , 
			CDHITIM = CURRENT_TIME , 
			CDHISAB = P_CDHISAB 
		WHERE CDINDEX = P_CDINDEX 
			AND CDCODE = P_CDCODE ; 
  
	END IF ; 
  
END P1  ; 
  