--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_RUN ( 
	IN P_CISBCODE VARCHAR(1), 
	IN P_CIGRCODE VARCHAR(2),
	IN P_CIGRSEQ VARCHAR(4),
	IN P_CIITEMNUM VARCHAR(2)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		CISBCODE,
		CIGRCODE,
		CIGRSEQ,
		CIITEMNUM,
		CIEVAITEM,
		CIEVASTD,
		CIWRSABUN,
		CIWRDATE,
		CIHIGB,
		CIHIDAT,
		CIHITIM,
		CIHISAB,
		KBHANGL,
		CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_CHECKLIST_STRESULT WHERE CSTSBCODE = CISBCODE AND CSTGRCODE = CIGRCODE AND CSTGRSEQ = CIGRSEQ AND CSTITEMNUM = CIITEMNUM) > 0 THEN 'Y' ELSE 'N' END AS LTGUBUN
		FROM PSSCMLIB.PSM_CHECKLIST_DCODE ST
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF MF
			ON MF.KBSABUN = ST.CIWRSABUN
		WHERE CISBCODE = P_CISBCODE
		AND   CIGRCODE = P_CIGRCODE
		AND   CIGRSEQ  = P_CIGRSEQ
		AND   CIITEMNUM = P_CIITEMNUM
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
