DROP PROCEDURE PSSCMLIB.PSM_PSM1083_JSA_CLASS1_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1083_JSA_CLASS1_ADD ( 
	IN P_J1CODE VARCHAR(2) , 
	IN P_J1NAME VARCHAR(100) , 
	IN P_J1BIGO VARCHAR(200) ,
	IN P_J1HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1083_JSA_CLASS1_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_JSA_CLASS1 ( 
		J1CODE,
		J1NAME,
		J1BIGO,
		J1HIGB,
		J1HIDAT,
		J1HITIM,
		J1HISAB
		)
		VALUES
		(
		P_J1CODE,
		P_J1NAME,
		P_J1BIGO,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_J1HISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_JSA_CLASS1 SET
		J1NAME  = P_J1NAME, 
		J1BIGO  = P_J1BIGO, 
		J1HIGB  = 'C', 
		J1HIDAT = CURRENT_DATE, 
		J1HITIM = CURRENT_TIME, 
		J1HISAB = P_J1HISAB
		WHERE J1CODE = P_J1CODE ;
  
	END IF ; 
  
END P1  ; 
  