--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1112_MCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1112_MCODE_LIST (
	IN P_PBC2NTCODE VARCHAR(2),
	IN P_PBC2LCODE VARCHAR(3),
	IN P_PBC2MCODE VARCHAR(3)
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1112_MCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		
			
			SELECT  PBC2NTCODE,
					PBC1NTCODE || '-' || CDDESC1 AS PBC2NTCODENM,
					PBC2LCODE,
			        REPLACE(PBC1NAME, 'amp;','') AS PBC2LCODENM,
		 		    PBC2MCODE  , 
				    REPLACE(PBC2NAME, 'amp;','') AS PBC2MCODENM,
				    PBC2BIGO,
					CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_BOARD_CLASS3 WHERE PBC3NTCODE = PBC2NTCODE AND PBC3LCODE = PBC2LCODE AND PBC3MCODE = PBC2MCODE) > 0 THEN 'Y' ELSE 'N' END AS C3GUBUN
			FROM PSSCMLIB.PSM_BOARD_CLASS2
			LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS1
			   ON  PBC1NTCODE = PBC2NTCODE
			   AND PBC1LCODE = PBC2LCODE
		    LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF AS NTCD
			   ON  CDINDEX = 'NT'
			  AND  CDCODE = PBC2NTCODE
			WHERE  PBC2NTCODE LIKE P_PBC2NTCODE||'%'
			  AND  PBC2LCODE LIKE P_PBC2LCODE||'%'
			  AND  PBC2MCODE LIKE P_PBC2MCODE||'%'			   
			ORDER BY PBC2NTCODE,PBC2LCODE, PBC2MCODE ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 