--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE PSSCMLIB.PSM_PSM1070_CHECKLIST_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1070_CHECKLIST_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_CISBCODE VARCHAR(1),
	IN P_CIGRCODE VARCHAR(2),
	IN P_CIGRSEQ VARCHAR(4)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1070_CHECKLIST_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
      LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR  -- 커서생성 
			WITH TABLE1 AS(
			SELECT
			CISBCODE,
			DIGITS(CAST(CIGRCODE AS NUMERIC(2,0))) AS CIGRCODE,
			CIGRSEQ,
			CIITEMNUM,
			CIEVAITEM,
			CIEVASTD,
			CIWRSABUN,
			CIWRDATE,
			CIHIGB,
			CIHIDAT,
			CIHITIM,
			CIHISAB,
			CSTGRCODE,
			CSTGRSEQ,
			CSTITEMNUM,
			CSTSEQ,
			CSTACTDESC,
			CSTADVDESC,
			CSTWRSABUN,
			CSTWRDATE,
			CSTHIGB,
			CSTHIDAT,
			CSTHITIM,
			CSTHISAB
			FROM PSSCMLIB.PSM_CHECKLIST_DCODE ST
			LEFT OUTER JOIN PSSCMLIB.PSM_CHECKLIST_STRESULT LT
			ON   LT.CSTSBCODE = ST.CISBCODE
			AND LT.CSTGRCODE  =  ST.CIGRCODE
			AND LT.CSTGRSEQ = ST.CIGRSEQ 
			AND LT.CSTITEMNUM = ST.CIITEMNUM
			WHERE CISBCODE = P_CISBCODE
			AND    CIGRCODE = P_CIGRCODE
			AND    CIGRSEQ = P_CIGRSEQ
			),
			ORIGINAL_DATA AS
			(
			SELECT
			ROW_NUMBER() OVER(ORDER BY CISBCODE, CIGRCODE, CIGRSEQ,CIITEMNUM) AS ROWNO,
			CISBCODE,
			CIGRCODE,
			CIGRSEQ,
			CIITEMNUM,
			CIEVAITEM,
			CIEVASTD,
			CIWRSABUN,
			CIWRDATE,
			CIHIGB,
			CIHIDAT,
			CIHITIM,
			CIHISAB,
			CSTGRCODE,
			CSTGRSEQ,
			CSTITEMNUM,
			CSTSEQ,
			CSTACTDESC,
			CSTADVDESC,
			CSTWRSABUN,
			CSTWRDATE,
			CSTHIGB,
			CSTHIDAT,
			CSTHITIM,
			CSTHISAB,
			CASE WHEN CSTSEQ = 1 THEN CIEVAITEM ELSE (CASE WHEN CSTSEQ IS NULL THEN CIEVAITEM ELSE '' END) END AS CIEVAITEM2,
			CASE WHEN CSTSEQ = 1 THEN CIEVASTD ELSE (CASE WHEN CSTSEQ IS NULL THEN CIEVASTD ELSE '' END) END AS CIEVASTD2,
			CASE WHEN CSTSEQ = 1 THEN CAST(CIITEMNUM AS VARCHAR(2)) ELSE (CASE WHEN CSTSEQ IS NULL THEN CAST(CIITEMNUM AS VARCHAR(2)) ELSE '' END) END AS CIITEMNUM2,
			'' AS CKDAPPRESULT1,
			'' AS CKDAPPRESULT2,
			'' AS CKDRECOMMEND
			FROM TABLE1
			)
			SELECT
			*
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC ;

		OPEN REFCURSOR ;

	END LIST ;  

	PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR  -- 커서생성 
				SELECT
				COUNT(*) AS TOTALCOUNT
				FROM PSSCMLIB.PSM_CHECKLIST_DCODE ST
				LEFT OUTER JOIN PSSCMLIB.PSM_CHECKLIST_STRESULT LT
				ON   LT.CSTSBCODE = ST.CISBCODE
				AND LT.CSTGRCODE  =  ST.CIGRCODE
				AND LT.CSTGRSEQ = ST.CIGRSEQ 
				AND LT.CSTITEMNUM = ST.CIITEMNUM
				WHERE CISBCODE = P_CISBCODE
				AND    CIGRCODE = P_CIGRCODE
				AND    CIGRSEQ = P_CIGRSEQ ;
			OPEN REFCURSOR2 ; 
	END PAGING ; 
END MAIN ; 
END  ;
