--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_DEL ( 
	IN P_CISBCODE VARCHAR(1), 
	IN P_CIGRCODE VARCHAR(2),
	IN P_CIGRSEQ VARCHAR(4),
	IN P_CIITEMNUM VARCHAR(2)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_CHECKLIST_DCODE
		WHERE CISBCODE  = P_CISBCODE
		AND   CIGRCODE  = P_CIGRCODE 
		AND   CIGRSEQ   = P_CIGRSEQ 
		AND   CIITEMNUM = P_CIITEMNUM  ;
  
END P1  ; 