--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_DEL ( 
	IN P_RMYEAR VARCHAR(4), 
	IN P_RMSEQ VARCHAR(3),
	IN P_RMCODE VARCHAR(1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_RISKCODE_MASTER
		WHERE RMYEAR = P_RMYEAR
		AND RMSEQ = P_RMSEQ
		AND RMCODE = P_RMCODE ;

		DELETE FROM PSSCMLIB.PSM_RISKCODE_LIST
		WHERE RLYEAR = P_RMYEAR
		AND RLSEQ = P_RMSEQ
		AND RLCODE = P_RMCODE ;
  
END P1  ; 
  