

DROP PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_ADD ( 
	IN P_L2SAUP VARCHAR(1) , 
	IN P_L2BCODE VARCHAR(1) , 
	IN P_L2MCODE VARCHAR(4) , 
	IN P_L2NAME VARCHAR(100) , 
	IN P_L2BIGO VARCHAR(200) ,
	IN P_L2HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_LOCATION_CLASS2 (
		L2SAUP  ,  
		L2BCODE ,  
		L2MCODE ,  
		L2NAME  ,  
		L2BIGO  ,  
		L2HIGB  ,  
		L2HIDAT ,  
		L2HITIM ,  
		L2HISAB ) VALUES (
		P_L2SAUP  ,  
		P_L2BCODE ,  
		P_L2MCODE ,  
		P_L2NAME  ,  
		P_L2BIGO  ,  
		'A'  ,  
		CURRENT_DATE ,  
		CURRENT_TIME ,  
		P_L2HISAB
		);
  
	ELSE 
  
		UPDATE  PSSCMLIB.PSM_LOCATION_CLASS2
		SET    L2NAME = P_L2NAME,
		       L2BIGO =  P_L2BIGO,
		       L2HIGB = 'C',
		       L2HIDAT = CURRENT_DATE,
		       L2HITIM = CURRENT_TIME,
		       L2HISAB = P_L2HISAB
		WHERE L2SAUP  = P_L2SAUP
		  AND L2BCODE = P_L2BCODE
		  AND L2MCODE = P_L2MCODE ;
  
	END IF ; 
  
END P1  ; 
  