--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_RUN ( 
	IN P_J2BCODE VARCHAR(2),
	IN P_J2MCODE VARCHAR(2)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1082_JSA_CLASS2_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		J2BCODE,
		J2MCODE AS J2MCODE,
		J2NAME,
		J2BIGO,
		CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_JSA_CLASS3 WHERE J3BCODE = J2BCODE AND J3MCODE = J2MCODE) > 0 THEN 'Y' ELSE 'N' END AS J3GUBUN
		FROM PSSCMLIB.PSM_JSA_CLASS2
		WHERE J2BCODE = P_J2BCODE
		AND   J2MCODE = P_J2MCODE
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
