--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_C2SAUP VARCHAR(1),
	IN P_C2BCODE VARCHAR(2),
	IN P_C2NAME VARCHAR(100)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
      LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR  -- 커서생성 
			WITH ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER(ORDER BY FXC2SAUP, FXC2BCODE, FXC2MCODE) AS ROWNO,
				FXC2SAUP  AS C2SAUP, 
				FXC2BCODE AS C2BCODE, 
				FXC1DESC  AS C2BCODENM,
				DIGITS(FXC2MCODE) AS C2MCODE,
				FXC2DESC AS C2NAME,
				FXC2BIGO AS C2BIGO
			FROM TYSCMLIB.ACFIXCLASS2
			LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS1
			ON    FXC1SAUP = FXC2SAUP
			AND   FXC1CODE = FXC2BCODE
			WHERE FXC2BCODE IN('20','30','40','90')
			AND   FXC2SAUP  = P_C2SAUP
			AND   (CASE WHEN P_C2BCODE = '' THEN 1 ELSE FXC2BCODE END) = (CASE WHEN P_C2BCODE = '' THEN 1 ELSE P_C2BCODE END)
			AND   FXC2DESC   LIKE  '%' || P_C2NAME || '%'
			ORDER BY FXC2SAUP, FXC2BCODE, FXC2MCODE
			)
			SELECT
			*
			FROM ORIGINAL_DATA
			--WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC ;

		OPEN REFCURSOR ;

	END LIST ;  

	PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR  -- 커서생성 
				SELECT   COUNT(*) AS TOTALCOUNT
				FROM TYSCMLIB.ACFIXCLASS2
			LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS1
			ON    FXC1SAUP = FXC2SAUP
			AND   FXC1CODE = FXC2BCODE
			WHERE FXC2BCODE IN('20','30','40','90')
			AND   FXC2SAUP  = P_C2SAUP
			AND   (CASE WHEN P_C2BCODE = '' THEN 1 ELSE FXC2BCODE END) = (CASE WHEN P_C2BCODE = '' THEN 1 ELSE P_C2BCODE END)
			AND   FXC2DESC   LIKE  '%' || P_C2NAME || '%' ;
			OPEN REFCURSOR2 ; 
	END PAGING ; 
END MAIN ; 
END  ;
