--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1113_SCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1113_SCODE_LIST ( 
	IN P_PBC3NTCODE VARCHAR(2),
	IN P_PBC3LCODE VARCHAR(3),
	IN P_PBC3MCODE VARCHAR(3),
	IN P_PBC3SCODE VARCHAR(3)
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1113_SCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		
			
			SELECT  PBC3NTCODE,
					PBC3LCODE,
			        REPLACE(PBC1NAME, 'amp;','') AS PBC3LCODENM,
		 		    PBC3MCODE , 
				    REPLACE(PBC2NAME, 'amp;','') AS PBC3MCODENM,
					PBC3SCODE  , 
					REPLACE(PBC3NAME, 'amp;','') AS PBC3NAME , 
				    PBC3BIGO ,
					CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_BOARD_MAST WHERE PBMCNTCODE = PBC3NTCODE AND PBMLCODE = PBC3LCODE AND PBMMCODE = PBC3MCODE AND PBMSCODE = PBC3SCODE) > 0 THEN 'Y' ELSE 'N' END AS PBGUBUN
			FROM PSSCMLIB.PSM_BOARD_CLASS3
			LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS1
			   ON  PBC1NTCODE = PBC3NTCODE
			   AND  PBC1LCODE = PBC3LCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS2
			   ON  PBC2NTCODE = PBC3NTCODE
			  AND  PBC2LCODE = PBC3LCODE
              AND  PBC2MCODE = PBC3MCODE
			WHERE PBC3NTCODE LIKE P_PBC3NTCODE||'%'
			  AND PBC3LCODE LIKE P_PBC3LCODE||'%'
			  AND  PBC3MCODE LIKE P_PBC3MCODE||'%'			   
			  AND  PBC3SCODE LIKE P_PBC3SCODE||'%'			   
			ORDER BY PBC3LCODE, PBC3MCODE,PBC3SCODE; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 