--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1010_CODEMF_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1010_CODEMF_RUN ( 
	IN IN_CDINDEX VARCHAR(2),
	IN IN_CDCODE VARCHAR(10)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1010_CODEMF_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT
			CDINDEX,
			CDCODE,
			CDDESC1,
			CDDESC2,
			CDBIGO
			FROM PSSCMLIB.PSM_CODEMF
			WHERE CDINDEX = IN_CDINDEX
			AND    CDCODE = IN_CDCODE
			ORDER BY CDCODE ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 