DROP PROCEDURE PSSCMLIB.PSM_PSM1053_RISKCODE_LIST_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1053_RISKCODE_LIST_ADD ( 
	IN P_RLYEAR VARCHAR(4) , 
	IN P_RLSEQ VARCHAR(3) , 
	IN P_RLCODE VARCHAR(1) , 
	IN P_RLITEMCODE VARCHAR(1) , 
	IN P_RLNAME VARCHAR(100) , 
	IN P_RLITEMNAME VARCHAR(100) , 
	IN P_RLRSINDEX0 VARCHAR(100) , 
	IN P_RLRSINDEX1 VARCHAR(100) , 
	IN P_RLRSINDEX2 VARCHAR(100) , 
	IN P_RLRSINDEX3 VARCHAR(100) , 
	IN P_RLHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1053_RISKCODE_LIST_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_RISKCODE_LIST
		(RLYEAR,
		 RLSEQ,
		 RLCODE,
		 RLITEMCODE,
		 RLNAME,
		 RLITEMNAME,
		 RLRSINDEX0,
		 RLRSINDEX1,
		 RLRSINDEX2,
		 RLRSINDEX3,
		 RLHIGB,
		 RLHIDAT,
		 RLHITIM,
		 RLHISAB)
		VALUES
		(P_RLYEAR,
		 P_RLSEQ,
		 P_RLCODE,
		 P_RLITEMCODE,
		 P_RLNAME,
		 P_RLITEMNAME,
		 P_RLRSINDEX0,
		 P_RLRSINDEX1,
		 P_RLRSINDEX2,
		 P_RLRSINDEX3,
		 'C',
		 CURRENT_DATE,
		 CURRENT_TIME,
		 P_RLHISAB);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_RISKCODE_LIST SET
		RLNAME = P_RLNAME,
		RLITEMNAME = P_RLITEMNAME,
		RLRSINDEX0 = P_RLRSINDEX0,
		RLRSINDEX1 = P_RLRSINDEX1,
		RLRSINDEX2 = P_RLRSINDEX2,
		RLRSINDEX3 = P_RLRSINDEX3,
		RLHIGB = 'C',
		RLHIDAT = CURRENT_DATE,
		RLHITIM = CURRENT_TIME,
		RLHISAB = P_RLHISAB
		WHERE RLYEAR = P_RLYEAR
		AND RLSEQ = P_RLSEQ
		AND RLCODE = P_RLCODE
		AND RLITEMCODE = P_RLITEMCODE ;
  
	END IF ; 
  
END P1  ; 
  