--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","LSHPDM" ; 

DROP PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_DEL ( 
	IN P_C2SAUP VARCHAR(1), 
	IN P_C2BCODE VARCHAR(2),
	IN P_C2MCODE VARCHAR(4)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM TYSCMLIB.ACFIXCLASS2
		WHERE FXC2SAUP  = P_C2SAUP
		AND   FXC2BCODE = P_C2BCODE
		AND   FXC2MCODE = P_C2MCODE ;
  
END P1  ; 