--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_PRT_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_PRT_LIST ( 
	IN P_SESSION VARCHAR(24) , 
	IN P_BLASS VARCHAR(2) , 
	IN P_MLASS VARCHAR(2) , 
	IN P_SLASS VARCHAR(3) , 
	IN P_SEQ NUMERIC(3, 0) , 
	IN P_SABUN VARCHAR(6),
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1090_JSA_PRT_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 

	CALL PSSCMLIB.PSM_PSM1090_JSA_PRT_CREATE(P_SESSION, P_BLASS, P_MLASS, P_SLASS, P_SEQ, P_SABUN);

LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		WITH TABLE1 AS
		(
			SELECT
			rownumber() over(ORDER BY PRBLASS, PRMLASS, PRSLASS, PRSEQ, PRITEMSEQ, PRRSUBSEQ, PRESUBSEQ) as PRROWNUM,
			PRSESSIONID, 
			PRBLASS, 
			PRMLASS, 
			PRSLASS, 
			PRSEQ,
			PRITEMSEQ,
			PRITEMTEXT,
			PRTOOLTEXT,
			PRRSUBSEQ, 
			PRRISKTEXT,
			PRESUBSEQ, 
			PREREFORMTEXT,
			PRRISKCNT,
			PRRISKSOLID,
			PRRISKDEGREE,
			PREREFORMCNT,
			PREREFORMSOLID,
			PREREFORMDEGREE
			FROM
			(
				SELECT
				rownumber() over() as PRROWNUM,
				PRSESSIONID, 
				PRBLASS, 
				PRMLASS, 
				PRSLASS, 
				PRSEQ,
				PRITEMSEQ,
				PRITEMTEXT,
				PRTOOLTEXT,
				(CASE WHEN PRRSUBSEQ = 0 THEN 99999 ELSE PRRSUBSEQ END) AS PRRSUBSEQ,
				PRRISKTEXT,
				(CASE WHEN PRESUBSEQ = 0 THEN 99999 ELSE PRESUBSEQ END) AS PRESUBSEQ,
				PREREFORMTEXT,
				PRRISKCNT,
				PRRISKSOLID,
				PRRISKDEGREE,
				PREREFORMCNT,
				PREREFORMSOLID,
				PREREFORMDEGREE
				FROM PSSCMLIB.PSM_JSA_Print
				WHERE  PRSESSIONID = P_SESSION
				ORDER BY PRBLASS, PRMLASS, PRSLASS, PRSEQ, PRITEMSEQ
			) AS TEMP
		),
		TABLE2 AS
		(
		SELECT
		PRROWNUM,
		PRSESSIONID, 
		PRBLASS,
		PRMLASS,
		PRSLASS,
		PRSEQ,
		PRITEMSEQ,
		CASE WHEN (SELECT COUNT(*) FROM TABLE1 B
			   WHERE B.PRBLASS   = A.PRBLASS
			   AND   B.PRMLASS   = A.PRMLASS
			   AND   B.PRSLASS   = A.PRSLASS
			   AND   B.PRSEQ     = A.PRSEQ
			       AND   B.PRITEMSEQ = A.PRITEMSEQ
			   AND   B.PRROWNUM < A.PRROWNUM)  = 0 THEN
			   PRITEMTEXT ELSE '' END PRITEMTEXT,
		PRITEMTEXT AS HIDEPRITEMTEXT,
		CASE WHEN (SELECT COUNT(*) FROM TABLE1 B
			   WHERE B.PRBLASS   = A.PRBLASS
			   AND   B.PRMLASS   = A.PRMLASS
			   AND   B.PRSLASS   = A.PRSLASS
			   AND   B.PRSEQ     = A.PRSEQ
			       AND   B.PRITEMSEQ = A.PRITEMSEQ
			   AND   B.PRROWNUM < A.PRROWNUM)  = 0 THEN
			   PRTOOLTEXT ELSE '' END PRTOOLTEXT,
			   PRRSUBSEQ,
			   PRRISKTEXT,
			   PRESUBSEQ,
			   PREREFORMTEXT,
			   PRRISKCNT,
			   PRRISKSOLID,
			   PRRISKDEGREE,
			   PREREFORMCNT,
			   PREREFORMSOLID,
			   PREREFORMDEGREE
		FROM TABLE1 A
		ORDER BY PRBLASS, PRMLASS, PRSLASS, PRSEQ, PRITEMSEQ, PRROWNUM
		)
		SELECT
		PRROWNUM,
		PRSESSIONID, 
		PRBLASS,
		PRMLASS,
		PRSLASS,
		PRSEQ,
		PRITEMSEQ,
		CASE WHEN PRITEMTEXT = '' THEN PRITEMTEXT
		WHEN P_GUBUN <> 'S' THEN PRITEMTEXT
		ELSE '<img src="/Resources/Images/Icon/it_res.png" style="cursor:pointer" onclick="gridClick1(''' || PRITEMSEQ || ''');" /> ' || PRITEMTEXT
		END  AS PRITEMTEXT,
		CASE WHEN PRITEMTEXT = '' THEN PRTOOLTEXT
		WHEN P_GUBUN <> 'S' THEN PRTOOLTEXT
		ELSE '<img src="/Resources/Images/Icon/it_res.png" style="cursor:pointer" onclick="gridClick1(''' || PRITEMSEQ || ''');" /> ' || PRTOOLTEXT
		END  AS PRTOOLTEXT,
		PRITEMSEQ,
		 PRRSUBSEQ,
		CASE WHEN P_GUBUN <> 'S' THEN PRRISKTEXT
		ELSE '<img src="/Resources/Images/Icon/it_res.png" style="cursor:pointer" onclick="gridRiskClick1(''' || PRITEMSEQ || '^' || PRRSUBSEQ || ''');" /> ' || PRRISKTEXT
		END AS PRRISKTEXT,
		PRESUBSEQ,
		CASE WHEN P_GUBUN <> 'S' THEN PREREFORMTEXT
		ELSE '<img src="/Resources/Images/Icon/it_res.png" style="cursor:pointer" onclick="gridReformClick1(''' || PRITEMSEQ || '^' || PRRSUBSEQ || ''');" /> ' || PREREFORMTEXT 
		END AS PREREFORMTEXT,
		PRRISKCNT,
		PRRISKSOLID,
		PRRISKDEGREE,
		PREREFORMCNT,
		PREREFORMSOLID,
		PREREFORMDEGREE
		FROM TABLE2
		ORDER BY PRBLASS, PRMLASS, PRSLASS, PRSEQ, PRITEMSEQ, PRROWNUM
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 