

DROP PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS2_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS2_DEL ( 
    IN P_PBC2NTCODE   VARCHAR(2), 
	IN P_PBC2LCODE   VARCHAR(3),
	IN P_PBC2MCODE   VARCHAR(3)
	) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_BOARD_CLASS2_DEL
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	
  
		DELETE FROM PSSCMLIB.PSM_BOARD_CLASS2
		WHERE PBC2NTCODE = P_PBC2NTCODE
		  AND PBC2LCODE = P_PBC2LCODE
		  AND PBC2MCODE = P_PBC2MCODE;
  
	
  
END P1  ; 
  