--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","IKHPDM" ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1010_CODEMF_DEL ( 
	IN P_CDINDEX VARCHAR(10) , 
	IN P_CDCODE VARCHAR(10) ) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1010_CODEMF_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB . PSM_CODEMF	 
		WHERE CDINDEX = P_CDINDEX 
			AND CDCODE = P_CDCODE ; 
  
END P1  ; 
  