

DROP PROCEDURE PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_ADD ( 
	IN P_L1SAUP VARCHAR(1) , 
	IN P_L1CODE VARCHAR(1) , 
	IN P_L1NAME VARCHAR(100) , 
	IN P_L1BIGO VARCHAR(200) ,
	IN P_L1HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_LOCATION_CLASS1 ( 
		L1SAUP  ,
		L1CODE , 
		L1NAME , 
		L1BIGO , 
		L1HIGB , 
		L1HIDAT, 
		L1HITIM, 
		L1HISAB
		) VALUES (
		P_L1SAUP  ,
		P_L1CODE , 
		P_L1NAME , 
		P_L1BIGO , 
		'A' , 
		CURRENT_DATE, 
		CURRENT_TIME, 
		P_L1HISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_LOCATION_CLASS1 
		SET  L1NAME  = P_L1NAME, 
		     L1BIGO  = P_L1BIGO, 
		     L1HIGB  = 'C', 
		     L1HIDAT = CURRENT_DATE, 
		     L1HITIM = CURRENT_TIME, 
		     L1HISAB = P_L1HISAB
		WHERE L1SAUP = P_L1SAUP
		  AND L1CODE = P_L1CODE ;
  
	END IF ; 
  
END P1  ; 
  