

DROP PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS3_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS3_ADD ( 
	IN P_PBC3NTCODE  VARCHAR(2),
	IN P_PBC3LCODE   VARCHAR(3),
	IN P_PBC3MCODE   VARCHAR(3),
	IN P_PBC3SCODE   VARCHAR(3),
	IN P_PBC3NAME    VARCHAR(100),
	IN P_PBC3BIGO    VARCHAR(200),
	IN P_PBC3HISAB   VARCHAR(6)	
	) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_BOARD_CLASS3_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF NOT EXISTS(	SELECT PBC3LCODE FROM PSSCMLIB.PSM_BOARD_CLASS3 WHERE PBC3NTCODE = P_PBC3NTCODE AND PBC3LCODE = P_PBC3LCODE AND  PBC3MCODE = P_PBC3MCODE AND PBC3SCODE = P_PBC3SCODE ) THEN
  
		INSERT INTO PSSCMLIB.PSM_BOARD_CLASS3 ( 
				PBC3NTCODE ,
				PBC3LCODE ,
				PBC3MCODE ,
				PBC3SCODE ,
				PBC3NAME  ,
				PBC3BIGO  ,
				PBC3HIGB  ,
				PBC3HIDAT ,
				PBC3HITIM ,
				PBC3HISAB 
			) VALUES (
				P_PBC3NTCODE ,
				P_PBC3LCODE ,
				P_PBC3MCODE ,
				P_PBC3SCODE ,
				P_PBC3NAME  ,
				P_PBC3BIGO  ,
					  'A'  ,
				CURRENT_DATE ,
				CURRENT_TIME ,
				P_PBC3HISAB
			);
  
	ELSE 
  
		 UPDATE PSSCMLIB.PSM_BOARD_CLASS3
		  SET   
		    PBC3NAME   = P_PBC3NAME,
			PBC3BIGO   = P_PBC3BIGO,
			PBC3HIGB   =  'C',
			PBC3HIDAT  = CURRENT_DATE,
			PBC3HITIM  = CURRENT_TIME,
			PBC3HISAB  = P_PBC3HISAB 
		 WHERE PBC3NTCODE = P_PBC3NTCODE
		   AND PBC3LCODE = P_PBC3LCODE
		   AND PBC3MCODE = P_PBC3MCODE
		   AND PBC3SCODE = P_PBC3SCODE; 

	END IF ; 
  
END P1  ; 
  