DROP PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_REFORM_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_REFORM_ADD ( 
	IN P_JSEBLASS VARCHAR(2) , 
	IN P_JSEMLASS VARCHAR(2) , 
	IN P_JSESLASS VARCHAR(3) , 
	IN P_JSESEQ NUMERIC(3,0) , 
	IN P_JSEITEMSEQ NUMERIC(3,0) ,
	IN P_JSESUBSEQ NUMERIC(3,0),
	IN P_JSEREFORMTEXT VARCHAR(400),
	IN P_JSEREFORMCNT NUMERIC(1,0),
	IN P_JSEREFORMSOLID NUMERIC(1,0),
	IN P_JSEREFORMDEGREE NUMERIC(1,0),
	IN P_JSEHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1093_JSA_REFORM_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_JSA_REFORM
		(
		JSEBLASS,
		JSEMLASS,
		JSESLASS,
		JSESEQ,
		JSEITEMSEQ,
		JSESUBSEQ,
		JSEREFORMTEXT,
		JSEREFORMCNT,
		JSEREFORMSOLID,
		JSEREFORMDEGREE,
		JSEHIGB,
		JSEHIDAT,
		JSEHITIM,
		JSEHISAB
		)
		VALUES
		(
		P_JSEBLASS,
		P_JSEMLASS,
		P_JSESLASS,
		P_JSESEQ,
		P_JSEITEMSEQ,
		P_JSESUBSEQ,
		P_JSEREFORMTEXT,
		P_JSEREFORMCNT,
		P_JSEREFORMSOLID,
		P_JSEREFORMDEGREE,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_JSEHISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_JSA_REFORM SET
		JSEREFORMTEXT   = P_JSEREFORMTEXT,
		JSEREFORMCNT    = P_JSEREFORMCNT,
		JSEREFORMSOLID  = P_JSEREFORMSOLID,
		JSEREFORMDEGREE = P_JSEREFORMDEGREE,
		JSEHIGB         = 'C',
		JSEHIDAT        = CURRENT_DATE,
		JSEHITIM        = CURRENT_TIME,
		JSEHISAB        = P_JSEHISAB
		WHERE JSEBLASS   = P_JSEBLASS
		AND   JSEMLASS   = P_JSEMLASS
		AND   JSESLASS   = P_JSESLASS
		AND   JSESEQ     = P_JSESEQ
		AND   JSEITEMSEQ = P_JSEITEMSEQ
		AND   JSESUBSEQ  = P_JSESUBSEQ ;
  
	END IF ; 
  
END P1  ; 
  