

DROP PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS3_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1110_BOARD_CLASS3_DEL ( 
	IN P_PBC3NTCODE   VARCHAR(2),
	IN P_PBC3LCODE   VARCHAR(3),
	IN P_PBC3MCODE   VARCHAR(3),
	IN P_PBC3SCODE   VARCHAR(3)
	) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1110_BOARD_CLASS3_DEL
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	
  
		DELETE FROM PSSCMLIB.PSM_BOARD_CLASS3
		WHERE PBC3NTCODE = P_PBC3NTCODE
		  AND PBC3LCODE = P_PBC3LCODE
          AND PBC3MCODE = P_PBC3MCODE 
          AND PBC3SCODE = P_PBC3SCODE; 
  
	
  
END P1  ; 
  