--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1033_ACFIXCLASS1_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
      LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR  -- 커서생성 
			WITH ORIGINAL_DATA AS (
				SELECT
				ROW_NUMBER() OVER(ORDER BY FXC1SAUP,FXC1CODE) AS ROWNO,
				FXC1SAUP AS C1SAUP,
				FXC1CODE AS  C1CODE,
				FXC1DESC AS   C1NAME,  
				FXC1CODE||'-'||FXC1DESC AS C1CODENAME,
				FXC1BIGO AS C1BIGO
				FROM  TYSCMLIB.ACFIXCLASS1
				WHERE FXC1SAUP IN('S','T')
				AND   FXC1CODE IN('20', '30', '40', '90')
				ORDER BY FXC1SAUP,FXC1CODE
			)
			SELECT
			*
			FROM ORIGINAL_DATA
			--WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC ;

		OPEN REFCURSOR ;

	END LIST ;  

	PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR  -- 커서생성 
				SELECT   COUNT(*) AS TOTALCOUNT
				FROM  TYSCMLIB.ACFIXCLASS1
				WHERE FXC1SAUP IN('S','T')
				AND   FXC1CODE IN('20', '30', '40', '90');
			OPEN REFCURSOR2 ; 
	END PAGING ; 
END MAIN ; 
END  ;
