DROP PROCEDURE PSSCMLIB.PSM_PSM1091_JSA_COPY;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1091_JSA_COPY ( 
	IN P_JSMBLASS VARCHAR(2) , 
	IN P_JSMMLASS VARCHAR (2) ,
	IN P_JSMSLASS VARCHAR(3) , 
	IN P_JSMSEQ NUMERIC(3,0) , 
	IN P_BCODE VARCHAR(2) , 
	IN P_MCODE VARCHAR(2) , 
	IN P_SCODE VARCHAR(3) , 
	IN P_JSMWKNAME VARCHAR(400), 
	IN P_JSMHISAB VARCHAR(6)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1091_JSA_COPY 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 

	DECLARE V_JSMSEQ	NUMERIC ( 3, 0 ) ; 
	 
	SELECT VALUE(MAX(JSMSEQ),0) + 1 INTO V_JSMSEQ
	FROM PSSCMLIB.PSM_JSA_MASTER
	WHERE JSMBLASS = P_BCODE
	AND   JSMMLASS = P_MCODE
	AND   JSMSLASS = P_SCODE ;

	-- JSA 마스터 복사
	INSERT INTO PSSCMLIB.PSM_JSA_MASTER
	(
	JSMBLASS,
	JSMMLASS,
	JSMSLASS,
	JSMSEQ,
	JSMWKNAME,
	JSMSYSTEM,
	JSMWKDATE,
	JSMADDATE,
	JSMADCHASU,
	JSMWKSABUN,
	JSMSANAME,
	JSMSECTIONNUM,
	JSMMSDSCODE,
	JSMMSDSSEQ,
	JSMWKSUMMARY,
	JSMNEEDDATA,
	JSMRISKCASE,
	JSMSELFNAME1,
	JSMSELFTEXT1,
	JSMSELFNAME2,
	JSMSELFTEXT2,
	JSMSELFNAME3,
	JSMSELFTEXT3,
	JSMSELFNAME4,
	JSMSELFTEXT4,
	JSMSELFNAME5,
	JSMSELFTEXT5,
	JSMSCOMNAME1,
	JSMSCOMTEXT1,
	JSMSCOMNAME2,
	JSMSCOMTEXT2,
	JSMHIGB,
	JSMHIDAT,
	JSMHITIM,
	JSMHISAB
	)
	SELECT
	CAST(P_BCODE AS VARCHAR(2)) AS JSMBLASS,
	CAST(P_MCODE AS VARCHAR(2)) AS JSMMLASS,
	CAST(P_SCODE AS VARCHAR(3)) AS JSMSLASS,
	CAST(V_JSMSEQ AS NUMERIC(3,0)) AS JSMSEQ,
	CAST(P_JSMWKNAME AS VARCHAR(400)) AS JSMWKNAME,
	JSMSYSTEM,
	JSMWKDATE,
	JSMADDATE,
	JSMADCHASU,
	JSMWKSABUN,
	JSMSANAME,
	JSMSECTIONNUM,
	JSMMSDSCODE,
	JSMMSDSSEQ,
	JSMWKSUMMARY,
	JSMNEEDDATA,
	JSMRISKCASE,
	JSMSELFNAME1,
	JSMSELFTEXT1,
	JSMSELFNAME2,
	JSMSELFTEXT2,
	JSMSELFNAME3,
	JSMSELFTEXT3,
	JSMSELFNAME4,
	JSMSELFTEXT4,
	JSMSELFNAME5,
	JSMSELFTEXT5,
	JSMSCOMNAME1,
	JSMSCOMTEXT1,
	JSMSCOMNAME2,
	JSMSCOMTEXT2,
	'A' AS JSMHIGB,
	CURRENT_DATE,
	CURRENT_TIME,
	CAST(P_JSMHISAB AS VARCHAR(6)) AS JSMHISAB
	FROM PSSCMLIB.PSM_JSA_MASTER
	WHERE JSMBLASS = P_JSMBLASS
	AND   JSMMLASS = P_JSMMLASS
	AND   JSMSLASS = P_JSMSLASS
	AND   JSMSEQ   = P_JSMSEQ ;

	-- JSA 마스터 안전장비 복사
	INSERT INTO PSSCMLIB.PSM_JSA_MSAFETOOL
	( 
	JSTBLASS,
	JSTMLASS,
	JSTSLASS,
	JSTSEQ,
	JSTINDX,
	JSTCODEGUBN,
	JSTSAFECODE,
	JSTSAFENAME,
	JSTHIGB,
	JSTHIDAT,
	JSTHITIM,
	JSTHISAB
	)
	SELECT
	CAST(P_BCODE AS VARCHAR(2)) AS JSTBLASS,
	CAST(P_MCODE AS VARCHAR(2)) AS JSTMLASS,
	CAST(P_SCODE AS VARCHAR(3)) AS JSTSLASS,
	CAST(V_JSMSEQ AS NUMERIC(3,0)) AS JSTSEQ,
	JSTINDX,
	JSTCODEGUBN,
	JSTSAFECODE,
	JSTSAFENAME,
	'A' AS JSTHIGB,
	CURRENT_DATE,
	CURRENT_TIME,
	CAST(P_JSMHISAB AS VARCHAR(6)) AS JSTHISAB
	FROM PSSCMLIB.PSM_JSA_MSAFETOOL
	WHERE JSTBLASS = P_JSMBLASS
	AND   JSTMLASS = P_JSMMLASS
	AND   JSTSLASS = P_JSMSLASS
	AND   JSTSEQ   = P_JSMSEQ ;

	-- JSA 디테일 복사
	INSERT INTO PSSCMLIB.PSM_JSA_DETAIL
	(
	JSDBLASS,
	JSDMLASS,
	JSDSLASS,
	JSDSEQ,
	JSDITEMSEQ,
	JSDITEMTEXT,
	JSDTOOLTEXT,
	JSDHIGB,
	JSDHIDAT,
	JSDHITIM,
	JSDHISAB
	)
	SELECT
	CAST(P_BCODE AS VARCHAR(2)) JSDBLASS,
	CAST(P_MCODE AS VARCHAR(2)) JSDMLASS,
	CAST(P_SCODE AS VARCHAR(3)) JSDSLASS,
	CAST(V_JSMSEQ AS NUMERIC(3,0)) AS JSDSEQ,
	JSDITEMSEQ,
	JSDITEMTEXT,
	JSDTOOLTEXT,
	'A' AS JSDHIGB,
	CURRENT_DATE,
	CURRENT_TIME,
	CAST(P_JSMHISAB AS VARCHAR(6)) AS JSDHISAB
	FROM PSSCMLIB.PSM_JSA_DETAIL
	WHERE JSDBLASS = P_JSMBLASS
	AND   JSDMLASS = P_JSMMLASS
	AND   JSDSLASS = P_JSMSLASS
	AND   JSDSEQ   = P_JSMSEQ ;

	-- JSA 위험성 복사
	INSERT INTO PSSCMLIB.PSM_JSA_RISK
	( 
	JSRBLASS,
	JSRMLASS,
	JSRSLASS,
	JSRSEQ,
	JSRITEMSEQ,
	JSRSUBSEQ,
	JSRRISKTEXT,
	JSRRISKCNT,
	JSRRISKSOLID,
	JSRRISKDEGREE,
	JSRHIGB,
	JSRHIDAT,
	JSRHITIM,
	JSRHISAB
	)
	SELECT
	CAST(P_BCODE AS VARCHAR(2)) JSRBLASS,
	CAST(P_MCODE AS VARCHAR(2)) JSRMLASS,
	CAST(P_SCODE AS VARCHAR(3)) JSRSLASS,
	CAST(V_JSMSEQ AS NUMERIC(3,0)) AS JSRSEQ,
	JSRITEMSEQ,
	JSRSUBSEQ,
	JSRRISKTEXT,
	JSRRISKCNT,
	JSRRISKSOLID,
	JSRRISKDEGREE,
	'A' AS JSRHIGB,
	CURRENT_DATE,
	CURRENT_TIME,
	CAST(P_JSMHISAB AS VARCHAR(6)) AS JSRHISAB
	FROM PSSCMLIB.PSM_JSA_RISK
	WHERE JSRBLASS = P_JSMBLASS
	AND   JSRMLASS = P_JSMMLASS
	AND   JSRSLASS = P_JSMSLASS
	AND   JSRSEQ   = P_JSMSEQ ;

	-- JSA 개선대책 복사
	INSERT INTO PSSCMLIB.PSM_JSA_REFORM
	(
	JSEBLASS,
	JSEMLASS,
	JSESLASS,
	JSESEQ,
	JSEITEMSEQ,
	JSESUBSEQ,
	JSEREFORMTEXT,
	JSEREFORMCNT,
	JSEREFORMSOLID,
	JSEREFORMDEGREE,
	JSEHIGB,
	JSEHIDAT,
	JSEHITIM,
	JSEHISAB
	)
	SELECT
	CAST(P_BCODE AS VARCHAR(2)) JSEBLASS,
	CAST(P_MCODE AS VARCHAR(2)) JSEMLASS,
	CAST(P_SCODE AS VARCHAR(3)) JSESLASS,
	CAST(V_JSMSEQ AS NUMERIC(3,0)) AS JSESEQ,
	JSEITEMSEQ,
	JSESUBSEQ,
	JSEREFORMTEXT,
	JSEREFORMCNT,
	JSEREFORMSOLID,
	JSEREFORMDEGREE,
	'A' AS JSEHIGB,
	CURRENT_DATE,
	CURRENT_TIME,
	CAST(P_JSMHISAB AS VARCHAR(6)) AS JSEHISAB
	FROM PSSCMLIB.PSM_JSA_REFORM
	WHERE JSEBLASS = P_JSMBLASS
	AND   JSEMLASS = P_JSMMLASS
	AND   JSESLASS = P_JSMSLASS
	AND   JSESEQ   = P_JSMSEQ ;
  
END P1  ; 