--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_LIST ( 
	IN P_J2BCODE VARCHAR(2)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1082_JSA_CLASS2_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		J2BCODE,
		J1NAME AS J2BCODENM,
		J2MCODE,
		J2NAME,
		J2MCODE||'-'||J2NAME AS J2CODENAME,
		J2BIGO
		FROM PSSCMLIB.PSM_JSA_CLASS2
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
		ON    J1CODE = J2BCODE
		WHERE   (CASE WHEN P_J2BCODE = '' THEN '1' ELSE J2BCODE END) = (CASE WHEN P_J2BCODE = '' THEN '1' ELSE P_J2BCODE END)
		ORDER BY J2BCODE, J2MCODE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 