--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","LSHPDM" ; 

DROP PROCEDURE PSSCMLIB.PSM_PSM1071_CHECKLIST_MCODE_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1071_CHECKLIST_MCODE_DEL ( 
	IN P_CMSBCODE VARCHAR(1), 
	IN P_CMGRCODE VARCHAR(2),
	IN P_CMGRSEQ VARCHAR(4)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1071_CHECKLIST_MCODE_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_CHECKLIST_MCODE
		WHERE CMSBCODE = P_CMSBCODE
		AND   CMGRCODE = P_CMGRCODE 
		AND   CMGRSEQ  = P_CMGRSEQ  ;

		DELETE FROM PSSCMLIB.PSM_CHECKLIST_DCODE
		WHERE CISBCODE = P_CMSBCODE
		AND   CIGRCODE = P_CMGRCODE
		AND   CIGRSEQ  = P_CMGRSEQ ;

		DELETE FROM PSSCMLIB.PSM_CHECKLIST_STRESULT
		WHERE CSTSBCODE = P_CMSBCODE
		AND   CSTGRCODE = P_CMGRCODE
		AND   CSTGRSEQ  = P_CMGRSEQ ;
  
END P1  ; 