DROP PROCEDURE PSSCMLIB.PSM_PSM1070_CHECKLIST_MENU_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM1070_CHECKLIST_MENU_LIST
( 
	
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (
			
			SELECT DISTINCT
			1 AS LVL,
			'000' AS UP_MENU_NO,
			CMSBCODE AS MENU_NO,
				      '' AS MENU_CODE,
			(CASE WHEN CMSBCODE = 'T' THEN 'UTT' ELSE 'SILO' END) AS MENU_NAME
			FROM PSSCMLIB.PSM_CHECKLIST_MCODE ST

			UNION ALL
			SELECT DISTINCT
			2 AS LVL,
			CMSBCODE AS UP_MENU_NO,
			CMSBCODE||'_'||CMGRCODE AS MENU_NO,
				      DIGITS(MIN(CMGRSEQ)) AS MENU_CODE,
			CDDESC1 AS MENU_NAME
			FROM PSSCMLIB.PSM_CHECKLIST_MCODE ST
			LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF CD
			ON CD.CDINDEX = 'CK'
			AND CD.CDCODE = ST.CMGRCODE
			GROUP BY CMSBCODE, CMGRCODE, CDDESC1
		)
		SELECT
		LVL, UP_MENU_NO, MENU_NO, MENU_CODE, MENU_NAME
		FROM TABLE1

		UNION ALL
			SELECT 3 AS LVL,
				A.CMSBCODE||'_'||A.CMGRCODE AS UP_MENU_NO,
				A.CMSBCODE||'_'||A.CMGRCODE||'_'||DIGITS(A.CMGRSEQ) AS MENU_NO,
							    DIGITS(A.CMGRSEQ) AS MENU_CODE,
				A.CMDESC AS MENU_NAME
		FROM PSSCMLIB.PSM_CHECKLIST_MCODE
		 AS A
		ORDER BY LVL, UP_MENU_NO, MENU_NO, MENU_CODE;

		
	OPEN REFCURSOR;

END