--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1111_LCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1111_LCODE_LIST ( 
	   IN P_PBC1NTCODE VARCHAR(2),
       IN P_PBC1LCODE VARCHAR(3)
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1111_LCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			
			 
			SELECT PBC1LCODE,
				PBC1NTCODE ,
				PBC1NTCODE || '-' || CDDESC1 AS PBC1NTNAME,
			       REPLACE(PBC1NAME, 'amp;','') as PBC1LCODENM,			       
			       PBC1BIGO,
				   CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_BOARD_CLASS2 WHERE PBC2NTCODE = PBC1NTCODE AND PBC2LCODE = PBC1LCODE) > 0 THEN 'Y' ELSE 'N' END AS C2GUBUN
			FROM  PSSCMLIB.PSM_BOARD_CLASS1	
			LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF	
			ON  CDINDEX = 'NT'
			AND CDCODE = PBC1NTCODE	
			WHERE  PBC1NTCODE LIKE '%' || P_PBC1NTCODE || '%'
			AND    PBC1LCODE LIKE '%' || P_PBC1LCODE || '%'
			ORDER BY PBC1NTCODE, PBC1LCODE ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 