--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_RISK_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_RISK_DEL ( 
	IN P_JSRBLASS VARCHAR(2) , 
	IN P_JSRMLASS VARCHAR(2) , 
	IN P_JSRSLASS VARCHAR(3) , 
	IN P_JSRSEQ NUMERIC(3,0), 
	IN P_JSRITEMSEQ NUMERIC(3,0),
	IN P_JSRSUBSEQ NUMERIC(3,0)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1093_JSA_RISK_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_JSA_RISK
		WHERE JSRBLASS = P_JSRBLASS
		AND    JSRMLASS = P_JSRMLASS
		AND    JSRSLASS = P_JSRSLASS
		AND    JSRSEQ = P_JSRSEQ
		AND    JSRITEMSEQ = P_JSRITEMSEQ
		AND    JSRSUBSEQ = P_JSRSUBSEQ ;
  
END P1  ; 
  