--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","LSHPDM" ; 

DROP PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_RUN ( 
	IN P_C3SAUP VARCHAR(1) , 
	IN P_C3BCODE VARCHAR(2) , 
	IN P_C3MCODE VARCHAR(4) , 
	IN P_C3SCODE VARCHAR(3) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
			FXC3SAUP AS C3SAUP,
			FXC3BCODE AS C3BCODE,
			FXC1DESC AS C3BCODENM,
			DIGITS(FXC3MCODE) AS C3MCODE,
			FXC2DESC AS C3MCODENM,
			DIGITS(FXC3SCODE) AS C3SCODE,
			FXC3DESC AS C3NAME,
			FXC3LINKCODE1 AS C3LINKCODE1,
			VALUE((SELECT CNM1.FXC3DESC FROM TYSCMLIB.ACFIXCLASS3 AS CNM1 WHERE CNM1.FXC3SAUP || CNM1.FXC3BCODE || DIGITS(CNM1.FXC3MCODE) || DIGITS(CNM1.FXC3SCODE) = CL3.FXC3LINKCODE1),'') AS C3LINKCODE1NM,
			FXC3LINKCODE2 AS C3LINKCODE2,
			VALUE((SELECT CNM2.FXC3DESC FROM TYSCMLIB.ACFIXCLASS3 AS CNM2 WHERE CNM2.FXC3SAUP || CNM2.FXC3BCODE || DIGITS(CNM2.FXC3MCODE) || DIGITS(CNM2.FXC3SCODE) = CL3.FXC3LINKCODE2),'') AS C3LINKCODE2NM,
			FXC3BIGO AS C3BIGO,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_SAFEORDER_MASTER 
			WHERE (SMSYSTEMCODE1 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) OR SMSYSTEMCODE2 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) 
			OR SMSYSTEMCODE3 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) OR SMSYSTEMCODE4 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) 
			OR SMSYSTEMCODE5 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE))) > 0 THEN 'Y' ELSE 'N' END SOGUBUN,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_WORKORDER
			WHERE (WOLOCATIONCODE1 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) OR WOLOCATIONCODE2 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) 
			OR WOLOCATIONCODE3 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) OR WOLOCATIONCODE4 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) 
			OR WOLOCATIONCODE5 = FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE))) > 0 THEN 'Y' ELSE 'N' END WOGUBUN
		FROM TYSCMLIB.ACFIXCLASS3 AS CL3
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS1
		ON    FXC1SAUP  = FXC3SAUP
		AND   FXC1CODE  = FXC3BCODE
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS2
		ON    FXC2SAUP  = FXC3SAUP
		AND   FXC2BCODE = FXC3BCODE
		AND   FXC2MCODE = FXC3MCODE
		WHERE FXC3SAUP  = P_C3SAUP
		AND   FXC3BCODE = P_C3BCODE
		AND   FXC3MCODE = P_C3MCODE
		AND   FXC3SCODE = P_C3SCODE
  
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE PSSCMLIB.PSM_PSM1031_ACFIXCLASS3_RUN 
TO LSHPDM WITH GRANT OPTION ;
