--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MSAFETOOL_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1090_JSA_MSAFETOOL_DEL ( 
	IN P_JSTBLASS VARCHAR(2) , 
	IN P_JSTMLASS VARCHAR(2) , 
	IN P_JSTSLASS VARCHAR(3) , 
	IN P_JSTSEQ NUMERIC(3,0) ) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1090_JSA_MSAFETOOL_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_JSA_MSAFETOOL
		WHERE JSTBLASS = P_JSTBLASS
		AND   JSTMLASS = P_JSTMLASS
		AND   JSTSLASS = P_JSTSLASS
		AND   JSTSEQ   = P_JSTSEQ ;
  
END P1  ; 
  