--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1081_JSACHANGE_MASTER_CHECK ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1081_JSACHANGE_MASTER_CHECK ( 
	IN P_JSMBLASS VARCHAR(2), 
	IN P_JSMMLASS VARCHAR(2), 
	IN P_JSMSLASS VARCHAR(3)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1081_JSACHANGE_MASTER_CHECK 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			*
			FROM PSSCMLIB.PSM_JSACHANGE_MASTER
			WHERE JSMBLASS = P_JSMBLASS
			AND   JSMMLASS = P_JSMMLASS
			AND   JSMSLASS = P_JSMSLASS ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 