--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_RUN ( 
	IN P_L1SAUP VARCHAR(1) , 
	IN P_L1CODE VARCHAR(1)  ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1023_LOCATION_CLASS1_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT L1SAUP, 
			     L1CODE,
			     L1NAME,
			     L1BIGO ,
				 CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_LOCATION_CLASS2 WHERE L2SAUP = L1SAUP AND L2BCODE = L1CODE) > 0 THEN 'Y' ELSE 'N' END AS L2GUBUN
		FROM  PSSCMLIB.PSM_LOCATION_CLASS1
		WHERE  L1SAUP =  P_L1SAUP
		    AND   L1CODE = P_L1CODE
		ORDER BY L1SAUP,L1CODE
  
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
