--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_RISK_SEQ ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1093_JSA_RISK_SEQ ( 
	IN P_JSRBLASS VARCHAR(2),
	IN P_JSRMLASS VARCHAR(2),
	IN P_JSRSLASS VARCHAR(3),
	IN P_JSRSEQ NUMERIC(3,0),
	IN P_JSRITEMSEQ NUMERIC(3,0)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1093_JSA_RISK_SEQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT   VALUE(MAX(JSRSUBSEQ), 0) + 1 AS JSRSUBSEQ
			FROM PSSCMLIB.PSM_JSA_RISK
			WHERE JSRBLASS = P_JSRBLASS
			AND    JSRMLASS = P_JSRMLASS
			AND    JSRSLASS = P_JSRSLASS
			AND    JSRSEQ = P_JSRSEQ
			AND    JSRITEMSEQ = P_JSRITEMSEQ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 

