DROP PROCEDURE PSSCMLIB.PSM_PSM1111_NTCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1111_NTCODE_LIST (
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			'' AS CODE,
			'전체' AS CODENAME
			FROM SYSIBM.SYSDUMMY1
			WHERE CASE WHEN P_GUBUN = '' THEN '1' ELSE '' END = CASE WHEN P_GUBUN = '' THEN '2' ELSE '' END
			
			UNION ALL

			SELECT
			CDCODE AS CODE,
			CDCODE || '-' || CDDESC1 AS CODENAME
			FROM PSSCMLIB.PSM_CODEMF
			WHERE CDINDEX = 'NT'
			ORDER BY CODE ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 