--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","IKHPDM" ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1021_LOCATIONCODE_DEL ( 
	IN P_L3SAUP VARCHAR(1), 
	IN P_L3BCODE VARCHAR(1),
	IN P_L3MCODE VARCHAR(4),
	IN P_L3SCODE VARCHAR(3)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1021_LOCATIONCODE_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM  PSSCMLIB.PSM_LOCATION_CLASS3 
		WHERE L3SAUP  = P_L3SAUP
		  AND L3BCODE = P_L3BCODE
		  AND L3MCODE = P_L3MCODE
		  AND L3SCODE = P_L3SCODE ;
  
END P1  ; 
  