--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1092_JSA_DETAIL_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1092_JSA_DETAIL_DEL ( 
	IN P_JSDBLASS VARCHAR(2) , 
	IN P_JSDMLASS VARCHAR(2) , 
	IN P_JSDSLASS VARCHAR(3) , 
	IN P_JSDSEQ NUMERIC(3,0), 
	IN P_JSDITEMSEQ NUMERIC(3,0)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1092_JSA_DETAIL_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_JSA_DETAIL
		WHERE JSDBLASS   = P_JSDBLASS
		AND   JSDMLASS   = P_JSDMLASS
		AND   JSDSLASS   = P_JSDSLASS
		AND   JSDSEQ     = P_JSDSEQ
		AND   JSDITEMSEQ = P_JSDITEMSEQ ;

		-- 첨부파일 삭제
		DELETE FROM PSSCMLIB . PSM_CMN_ATTACH
		WHERE ATTACH_TYPE = 'JSA'
		AND    SUBSTR(ATTACH_NO,1,2) = P_JSDBLASS
		AND    SUBSTR(ATTACH_NO,3,2) = P_JSDMLASS
		AND    SUBSTR(ATTACH_NO,5,3) = P_JSDSLASS
		AND    CAST  (SUBSTR(ATTACH_NO,8,3) AS NUMERIC(3 , 0)) = P_JSDSEQ
		AND    CAST  (SUBSTR(ATTACH_NO,11,3) AS NUMERIC(3 , 0)) = P_JSDITEMSEQ
		;
  
END P1  ; 
  