--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_RUN ( 
	IN P_C2SAUP VARCHAR(1) , 
	IN P_C2BCODE VARCHAR(2) , 
	IN P_C2MCODE VARCHAR(4) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
			FXC2SAUP AS C2SAUP, 
			FXC2BCODE AS C2BCODE, 
			FXC1DESC AS C2BCODENM,
			DIGITS(FXC2MCODE) AS C2MCODE, 
			FXC2DESC AS C2NAME, 
			FXC2BIGO AS C2BIGO,
			FXC2XPOINT AS C2XPOINT,
			FXC2YPOINT AS C2YPOINT,
			CASE WHEN (SELECT COUNT(*) FROM TYSCMLIB.ACFIXCLASS3 WHERE FXC3SAUP = FXC2SAUP AND FXC3BCODE = FXC2BCODE AND FXC3MCODE = FXC2MCODE) > 0 THEN 'Y' ELSE 'N' END C3GUBUN
		FROM TYSCMLIB.ACFIXCLASS2
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS1
		ON   FXC1SAUP = FXC2SAUP
		AND FXC1CODE = FXC2BCODE
		WHERE FXC2SAUP  = P_C2SAUP
		AND   FXC2BCODE = P_C2BCODE
		AND   FXC2MCODE = P_C2MCODE	; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE PSSCMLIB.PSM_PSM1032_ACFIXCLASS2_RUN 
TO LSHPDM WITH GRANT OPTION ;
