--DROP PROCEDURE TYJINFWLIB.PSM_CODEMF_DEL;

CREATE PROCEDURE TYJINFWLIB.PSM_CODEMF_DEL 
(
	  P_CDINDEX       VARCHAR (10) 
	, P_CDCODE        VARCHAR (10) 
)
	LANGUAGE SQL
P1: BEGIN
	

		DELETE FROM TYSCMLIB.PSM_CODEMF 	
		WHERE CDINDEX= P_CDINDEX 
			AND CDCODE=P_CDCODE;

END P1