--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1080_JSA_SCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1080_JSA_SCODE_LIST ( 
	IN P_BCODE VARCHAR(2),
	IN P_MCODE VARCHAR(2),
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1080_JSA_SCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		''AS J3BCODE ,   
		''AS J3BCODENM,   
		''AS J3MCODE,
		''AS J3MCODENM,   
		''AS J3SCODE,
		''AS J3NAME,
		'전체'AS J3CODENAME,
		'' AS J3BIGO 
		FROM SYSIBM.SYSDUMMY1
		WHERE CASE WHEN P_GUBUN = '' THEN '1' ELSE '' END = CASE WHEN P_GUBUN = '' THEN '2' ELSE '' END

		UNION ALL

		SELECT
		J3BCODE,
		J1NAME AS J3BCODENM,
		J3MCODE,
		J2NAME AS J3MCODENM,
		J3SCODE AS J3SCODE,
		J3NAME,
		J3SCODE||'-'||J3NAME AS J3CODENAME,
		J3BIGO
		FROM PSSCMLIB.PSM_JSA_CLASS3 
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1 
		ON   J1CODE  = J3BCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2 
		ON   J2BCODE = J3BCODE
		AND  J2MCODE = J3MCODE 
		WHERE J3BCODE = P_BCODE
		AND   J3MCODE = P_MCODE
		ORDER BY J3BCODE, J3MCODE, J3SCODE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 