

DROP PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_ADD ( 
	IN P_CISBCODE VARCHAR(1) , 
	IN P_CIGRCODE VARCHAR(2) , 
	IN P_CIGRSEQ VARCHAR(4) , 
	IN P_CIITEMNUM VARCHAR(2) ,
	IN P_CIEVAITEM VARCHAR(400) ,
	IN P_CIEVASTD VARCHAR(400) ,
	IN P_CIWRSABUN VARCHAR(6) ,
	IN P_CIWRDATE VARCHAR(8),
	IN P_CIHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1072_CHECKLIST_DCODE_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_CHECKLIST_DCODE
		(
		CISBCODE,
		CIGRCODE,
		CIGRSEQ,
		CIITEMNUM,
		CIEVAITEM,
		CIEVASTD,
		CIWRSABUN,
		CIWRDATE,
		CIHIGB,
		CIHIDAT,
		CIHITIM,
		CIHISAB
		)
		VALUES
		(
		P_CISBCODE,
		P_CIGRCODE,
		P_CIGRSEQ,
		P_CIITEMNUM,
		P_CIEVAITEM,
		P_CIEVASTD,
		P_CIWRSABUN,
		P_CIWRDATE,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_CIHISAB
		)
		;
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_CHECKLIST_DCODE SET
		CIEVAITEM = P_CIEVAITEM ,
		CIEVASTD = P_CIEVASTD ,
		CIWRSABUN = P_CIWRSABUN ,
		CIWRDATE = P_CIWRDATE ,
		CIHIGB = 'C',
		CIHIDAT = CURRENT_DATE,
		CIHITIM = CURRENT_TIME,
		CIHISAB = P_CIHISAB 
		WHERE CISBCODE = P_CISBCODE
		AND   CIGRCODE= P_CIGRCODE
		AND   CIGRSEQ= P_CIGRSEQ
		AND   CIITEMNUM = P_CIITEMNUM ;
  
	END IF ; 
  
END P1  ; 
  