--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1020_SCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1020_SCODE_LIST ( 
	IN P_SAUP VARCHAR(1),
	IN P_LCODE VARCHAR(1),
	IN P_MCODE VARCHAR(4)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1020_SCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		''AS L3SAUP ,   
		''AS L3BCODE,   
		''AS L3BCODENM,
		''AS L3MCODE,   
		''AS L3MCODENM,
		''AS L3SCODE,
		''AS L3NAME,
		'전체'AS  L3CODENAME,   
		'' AS L3BIGO 
		FROM SYSIBM.SYSDUMMY1

		UNION ALL

		SELECT   L3SAUP ,   
			 L3BCODE,   
			 L1NAME AS L3BCODENM,
			 DIGITS(L3MCODE) AS L3MCODE,   
			 L2NAME AS L3MCODENM,
			 DIGITS(L3SCODE) AS L3SCODE,
				  L3NAME,
			 DIGITS(L3SCODE)||'-'||L3NAME AS L3CODENAME,   
			 L3BIGO 
		FROM PSSCMLIB.PSM_LOCATION_CLASS3 
		LEFT OUTER JOIN PSSCMLIB.PSM_LOCATION_CLASS1 
		    ON  L1SAUP = L3SAUP
		   AND  L1CODE = L3BCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_LOCATION_CLASS2 
		    ON  L2SAUP = L3SAUP
		   AND  L2BCODE = L3BCODE
		   AND  L2MCODE = L3MCODE 
		WHERE L3SAUP = P_SAUP
		   AND   L3BCODE =  P_LCODE
		   AND   (CASE WHEN P_MCODE = '' THEN 1 ELSE L3MCODE END) = (CASE WHEN P_MCODE = '' THEN 2 ELSE P_MCODE END)
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 