--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_STRESULT_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1072_CHECKLIST_STRESULT_RUN ( 
	IN P_CSTSBCODE VARCHAR(1), 
	IN P_CSTGRCODE VARCHAR(2),
	IN P_CSTGRSEQ VARCHAR(4),
	IN P_CSTITEMNUM VARCHAR(2),
	IN P_CSTSEQ VARCHAR(2)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1072_CHECKLIST_STRESULT_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		CSTSBCODE,
		CSTGRCODE,
		CSTGRSEQ,
		CSTITEMNUM,
		CSTSEQ,
		CSTACTDESC,
		CSTADVDESC,
		CSTWRSABUN,
		CSTWRDATE,
		CSTHIGB,
		CSTHIDAT,
		CSTHITIM,
		CSTHISAB,
		KBHANGL
		FROM PSSCMLIB.PSM_CHECKLIST_STRESULT LT
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF MF
			ON MF.KBSABUN = LT.CSTWRSABUN
		WHERE CSTSBCODE  = P_CSTSBCODE
		AND   CSTGRCODE  = P_CSTGRCODE 
		AND   CSTGRSEQ   = P_CSTGRSEQ 
		AND   CSTITEMNUM = P_CSTITEMNUM 
		AND   CSTSEQ     = P_CSTSEQ
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
