--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-28 17:07:17 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 

DROP PROCEDURE PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_RUN ( 
	IN P_RMYEAR VARCHAR(4), 
	IN P_RMSEQ VARCHAR(3),
	IN P_RMCODE VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1052_RISKCODE_MASTER_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		RMYEAR, 
		DIGITS(RMSEQ) AS RMSEQ, 
		RMCODE, 
		RMNAME, 
		RMHIGB, 
		RMHIDAT, 
		RMHITIM, 
		RMHISAB,
		CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_RISK_MASTER WHERE RMRSSTYEAR = RMYEAR AND RMRSSTSEQ = RMSEQ) > 0 THEN 'Y' ELSE 'N' END RMGUBUN
		FROM PSSCMLIB.PSM_RISKCODE_MASTER
		WHERE RMYEAR = P_RMYEAR 
		AND RMSEQ = P_RMSEQ 
		AND RMCODE = P_RMCODE
		ORDER BY RMCODE 
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
