DROP PROCEDURE PSSCMLIB.PSM_PSM1021_LOCATIONCODE_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1021_LOCATIONCODE_RUN ( 
	IN P_L3SAUP VARCHAR(1) , 
	IN P_L3BCODE VARCHAR(1) , 
	IN P_L3MCODE VARCHAR(4) , 
	IN P_L3SCODE VARCHAR(3) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1021_LOCATIONCODE_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT L3SAUP , 
			L3BCODE , 
			L1NAME AS L3BCODENM , 
			DIGITS ( L3MCODE ) AS L3MCODE , 
			L2NAME AS L3MCODENM , 
			DIGITS ( L3SCODE ) AS L3SCODE , 
			L3NAME , 
			L3BIGO ,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_SAFEORDER_MASTER 
			WHERE (SMAREACODE1 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) OR SMAREACODE2 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) 
			OR SMAREACODE3 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) OR SMAREACODE4 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) 
			OR SMAREACODE5 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE))) > 0 THEN 'Y' ELSE 'N' END SOGUBUN,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_WORKORDER
			WHERE (WOAREACODE1 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) OR WOAREACODE2 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) 
			OR WOAREACODE3 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) OR WOAREACODE4 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) 
			OR WOAREACODE5 = L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE))) > 0 THEN 'Y' ELSE 'N' END WOGUBUN
		FROM PSSCMLIB . PSM_LOCATION_CLASS3 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS1 
		ON L1SAUP = L3SAUP 
		AND L1CODE = L3BCODE 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS2 
		ON L2SAUP = L3SAUP 
		AND L2BCODE = L3BCODE 
		AND L2MCODE = L3MCODE 
		WHERE L3SAUP = P_L3SAUP 
		AND L3BCODE = P_L3BCODE 
		AND L3MCODE = P_L3MCODE 
		AND L3SCODE = P_L3SCODE 
  
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE PSSCMLIB.PSM_PSM1021_LOCATIONCODE_RUN 
TO LSHPDM WITH GRANT OPTION ;
