DROP PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1082_JSA_CLASS2_ADD ( 
	IN P_J2BCODE VARCHAR(2) , 
	IN P_J2MCODE VARCHAR(2) , 
	IN P_J2NAME VARCHAR(100) , 
	IN P_J2BIGO VARCHAR(200) ,
	IN P_J2HISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1082_JSA_CLASS2_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_JSA_CLASS2(
		J2BCODE,
		J2MCODE,
		J2NAME,
		J2BIGO,
		J2HIGB,
		J2HIDAT,
		J2HITIM,
		J2HISAB
		)
		VALUES
		(
		P_J2BCODE,
		P_J2MCODE,
		P_J2NAME,
		P_J2BIGO,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_J2HISAB
		);
  
	ELSE 
  
		UPDATE  PSSCMLIB.PSM_JSA_CLASS2 SET
			J2NAME  = P_J2NAME,
			J2BIGO  =  P_J2BIGO,
			J2HIGB  = 'C',
			J2HIDAT = CURRENT_DATE,
			J2HITIM = CURRENT_TIME,
			J2HISAB = P_J2HISAB
		WHERE J2BCODE = P_J2BCODE
		AND   J2MCODE = P_J2MCODE ;
  
	END IF ; 
  
END P1  ; 
  