--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_DEL ( 
	IN P_L2SAUP VARCHAR(1), 
	IN P_L2BCODE VARCHAR(1),
	IN P_L2MCODE VARCHAR(4)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM1022_LOCATION_CLASS2_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_LOCATION_CLASS2
		WHERE L2SAUP  = P_L2SAUP
		  AND L2BCODE = P_L2BCODE
		  AND L2MCODE = P_L2MCODE
		 ;
  
END P1  ; 
  