-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORM_USER_LIST_BYEMPID
-- 작성자     : 장경환
-- 작성일     : 2010-07-13
-- 설명       : 임직원를 검색하여 조회한다..
-- 예문       : CALL TYJINFWLIB.ORM_USER_LIST_BYEMPID('dev005','1000','ko')
-- DB2 변환   : 이전프로시져명 UP_ORGCHART_SELECT_USER_BYEMPID
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORM_USER_LIST_BYEMPID
CREATE PROCEDURE TYJINFWLIB.ORM_USER_LIST_BYEMPID
(
		P_EMPID			VARCHAR(20)
	,	P_COMPANYID		VARCHAR(10)
	,	P_LANGCODE		VARCHAR(10)
)
	LANGUAGE SQL
	RESULT SETS 1
	
P1 : BEGIN
	IF (COALESCE(P_COMPANYID, '') = '') THEN
		SET P_COMPANYID = (SELECT CompanyCode FROM TYJINFWLIB.ORG_USER WHERE EMPID = P_EMPID FETCH FIRST 1 ROWS ONLY);
	END IF;
	
	MAIN : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		SELECT
				U.EMPID					AS EMPID			--사번 = 'EMP77771' 
			,	U.LOGINID				AS LOGINID			--로그인ID = 'AUTOKYC' 
			,	U.EMAIL					AS EMAIL			--이메일 = 'AUTOKYC@FEMTECH.CO.KR' 
			,	U.MAINDEPTCODE			AS MAINDEPTCODE
			,	DP.DEPTNAME				AS MAINDEPTNAME	--부서코드 = 'ZZZZZ' 
			,	U.CREATEDDT				AS CREATEDDT		-- =생성일 '20100714' 
			,	U.DISPLAYNAME			AS DISPLAYNAME		--이름 = '김영춘' 
			,	UL.UserLName 
				|| (CASE WHEN P_LANGCODE NOT IN ('ko', 'cn', 'zh') THEN ' ' ELSE '' END)
				|| UL.UserFName	AS USERNAME
			,	DU.DUTYNAME				AS DUTYNAME		--직급 = '900' 
			,	''						AS JOBNAME
			--,	dbo.UF_USERINFO_JOBNAME2(U.CompanyCode, U.EmpID, P_LANGCODE)			AS JOBNAME			--직무 = '0502' 
			,	RA.RANKNAME				AS RANKNAME		--직책 = '111'
			,	U.CELLPHONE				AS CELLPHONE		--휴대전화번호 = '010-90EM-7771' 
			,	U.FAXNUMBER				AS FAXNUMBER		-- = NULL 
			,	U.EXTENSIONNUMBER		AS EXTENSIONNUMBER	--내선번호 = '2-7771'
			,	U.LOCATIONCODE 			AS LOCATIONCODE --지역
			,   COM.COMPANY 			AS COMPANYNAME
			,	U.DATEOFBIRTH			AS DATEOFBIRTH
			,	COALESCE(DU.TeamChiefYN, 'N')	AS TEAMCHIEFYN
			,	U.Phone1				AS PHONE1
			,	U.Phone2				AS PHONE2
			,	''						AS USERIMAGE
			--,	UI.FilePath				AS USERIMAGE
		FROM 
				TYJINFWLIB.ORG_USER AS U
				LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL
					ON	U.EMPID = UL.EMPID
					AND	UL.LANGCODE = P_LANGCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DP
					ON (U.MAINDEPTCODE = DP.DEPTCODE AND DP.COMPANYCODE = P_COMPANYID AND DP.LANGCODE = P_LANGCODE) -- 부서이름테이블JOIN
				LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS DU
					ON (U.DUTYCODE = DU.DUTYCODE AND DU.COMPANYCODE = P_COMPANYID AND DU.LANGCODE = P_LANGCODE AND DU.REGULARITYYN = '1') -- 직급테이블JOIN
				LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS RA
					ON (U.RANKCODE = RA.RANKCODE AND RA.COMPANYCODE = P_COMPANYID AND RA.LANGCODE = P_LANGCODE AND RA.PRGTYPE = '1')	-- 직책테이블JOIN
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS COM
					ON (U.COMPANYCODE = COM.COMPANYCODE AND COM.LANGUAGECODE = P_LANGCODE)
				--LEFT OUTER JOIN	DBO.tb_UserImage	AS UI
				--	ON	U.CompanyCode = UI.CompanyCode AND U.EMPID = UI.EMPID AND UI.UseYN = '1'
		WHERE 
				U.EMPID = P_EMPID AND U.COMPANYCODE = P_COMPANYID AND U.DISPLAYYN = 'Y'
		FETCH FIRST 1 ROWS ONLY;
		OPEN REFCURSOR;
	END MAIN;
END P1;