-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORM_USER_LIST_SEARCH
-- 작성자     : 장경환
-- 작성일     : 2010-07-13
-- 설명       : 부서를 검색하여 조회한다..
-- 예문       : CALL TYJINFWLIB.ORM_USER_LIST_SEARCH ('2100','','N', 'ko', '')
-- DB2 변환   : 이전프로시져명 up_OrgChart_Select_SearchUser
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORM_USER_LIST_SEARCH
CREATE PROCEDURE TYJINFWLIB.ORM_USER_LIST_SEARCH(
		P_COMPANYCODE	VARCHAR(50)
	,	P_KEYWORD		VARCHAR(20)
	,	P_ISRELATIVE	VARCHAR(1)
	,	P_LANGCODE		VARCHAR(10)
	,	P_ISDEACTIVE	VARCHAR(1)
)
	LANGUAGE SQL
	RESULT SETS 1
	
P1 : BEGIN
	MAIN : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		WITH CTE (EMPID, REMPID, EXTENSIONNUMBER, CELLPHONE, TEAMCHIEFYN, USERNAME, DISPLAYNAME ,EMAIL, DEPTCODE, DEPTNAME, COMPANYCODE, COMPANYNAME, RANKCODE, RANKNAME,
					JOBCODE, JOBNAME, DUTYCODE, DUTYNAME, FAXNUMBER, SIGNID, LOCATIONCODE, DATEOFBIRTH, ISMAINDEPT, KOSTL, ICON, DSORTNO, RSORTNO, SITECOMPANYCODE, SITECOMPANYNAME, CULTURE
		) AS (
			SELECT
					M.LOGINID						AS EMPID		-- 업체 로그인 아이디 대문자 P 때문에 LOWER(M.LOGINID)에서 LOWER 제거. 문제시 원복 2017-06-22 장윤호
				,	LOWER(M.EMPID)					AS REMPID
				,	COALESCE(M.EXTENSIONNUMBER,'')	AS EXTENSIONNUMBER
				,	COALESCE(M.CELLPHONE,'')		AS CELLPHONE
				,	COALESCE(D.TEAMCHIEFYN, 'N')	AS TEAMCHIEFYN
				,	COALESCE(UL.USERLNAME,'') 		AS USERNAME
				,	COALESCE(M.DISPLAYNAME,'')		AS DISPLAYNAME
				,	COALESCE(M.EMAIL,'')			AS EMAIL
				,	COALESCE(M.MAINDEPTCODE,'')		AS DEPTCODE
				,	COALESCE(DL.DEPTNAME,'')		AS DEPTNAME
				,	COALESCE(M.COMPANYCODE,'')		AS COMPANYCODE
				,	COALESCE(CL.COMPANY,'')			AS COMPANYNAME
				,	COALESCE(M.RANKCODE,'')			AS RANKCODE
				,	COALESCE(R.RANKNAME,'')			AS RANKNAME
				,	'' 								AS JOBCODE
					--COALESCE(M.JOBCODE,'')			AS JOBCODE,
				,	'' 								AS JOBNAME
					--DBO.UF_USERINFO_JOBNAME2(M.COMPANYCODE, M.EMPID, P_LANGCODE) AS JOBNAME,
				,	COALESCE(M.DUTYCODE,'')			AS DUTYCODE
				,	COALESCE(D.DUTYNAME,'')			AS DUTYNAME
				,	COALESCE(M.FAXNUMBER, '')		AS FAXNUMBER
				,	'' AS SIGNID
				--,	COALESCE(DBO.UF_USERINFO_SIGN(M.COMPANYCODE, M.EMPID), '') AS SIGNID
				,	COALESCE(M.LOCATIONCODE, '')	AS LOCATIONCODE
				,	COALESCE(M.DATEOFBIRTH, '')		AS DATEOFBIRTH
				,	'Y'								AS ISMAINDEPT
				,	COALESCE(DP.KOSTL, '')			AS KOSTL
				,	''								AS ICON
				,	COALESCE(D.SORTNO, 9999)		AS DSORTNO
				,	COALESCE(R.SORTNO, 9999)		AS RSORTNO
				,	COALESCE(M.SITECOMPANY, '')				AS SITECOMPANYCODE
				,	COALESCE(SCL.COMPANY,'')				AS SITECOMPANYNAME
				,	COALESCE(M.CULTURE, '')					AS CULTURE
			FROM 
					TYJINFWLIB.ORG_USER AS M
					LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL
						ON 	M.EMPID 		= UL.EMPID
						AND UL.LANGCODE 	= P_LANGCODE
						AND M.COMPANYCODE 	= UL.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL
						ON 	M.MAINDEPTCODE 	= DL.DEPTCODE
						AND DL.LANGCODE 	= P_LANGCODE
						AND M.COMPANYCODE 	= DL.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
						ON 	M.COMPANYCODE 	= CL.COMPANYCODE
						AND CL.LANGUAGECODE = P_LANGCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS SCL
						ON	M.SITECOMPANY 		= SCL.COMPANYCODE
						AND	SCL.LANGUAGECODE	= P_LANGCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS R
						ON 	M.RANKCODE 		= R.RANKCODE
						AND R.LANGCODE 		= P_LANGCODE
						--AND M.COMPANYCODE 	= R.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS D
						ON 	M.DUTYCODE 		= D.DUTYCODE
						AND D.LANGCODE 		= P_LANGCODE
						--AND M.COMPANYCODE 	= D.COMPANYCODE
					--LEFT OUTER JOIN DBO.TB_JOB J
					--	ON M.JOBCODE = J.JOBCODE AND J.LANGCODE = P_LANGCODE AND M.COMPANYCODE = J.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS DP
						ON 	M.MAINDEPTCODE 	= DP.DEPTCODE
						AND M.COMPANYCODE 	= DP.COMPANYCODE
			WHERE 
					M.DISPLAYYN					= 'Y'
			AND		M.COMPANYCODE				= CASE
													WHEN M.DPARTNER = '1'
													THEN P_COMPANYCODE
													ELSE M.COMPANYCODE
												END
			--AND		ISNULL(M.DEACTIVE, 'N')	<> 'Y'
			--AND		M.COMPANYCODE				= P_COMPANYCODE
			--AND		COALESCE(P_ISDEACTIVE, '') 	= 'Y'
		
			UNION
		
			SELECT
					M.LOGINID						AS EMPID		-- 업체 로그인 아이디 대문자 P 때문에 LOWER(M.LOGINID)에서 LOWER 제거. 문제시 원복 2017-06-22 장윤호
				,	LOWER(M.EMPID)					AS REMPID
				,	COALESCE(M.EXTENSIONNUMBER,'')	AS EXTENSIONNUMBER
				,	COALESCE(M.CELLPHONE,'')		AS CELLPHONE
				,	COALESCE(AJ.TEAMCHIEFYN, 'N')	AS TEAMCHIEFYN
				,	COALESCE(UL.USERLNAME,'')		AS USERNAME
				,	COALESCE(M.DISPLAYNAME,'')		AS DISPLAYNAME
				,	COALESCE(M.EMAIL,'')			AS EMAIL
				,	COALESCE(AJ.DEPTCODE,'')		AS DEPTCODE
				,	COALESCE(DL.DEPTNAME,'')		AS DEPTNAME
				,	COALESCE(AJ.ADDCOMPANYCODE,'')	AS COMPANYCODE
				,	COALESCE(CL.COMPANY,'')			AS COMPANYNAME
				,	COALESCE(AJ.RANKCODE,'')		AS RANKCODE
				,	COALESCE(R.RANKNAME,'')			AS RANKNAME
				,	'' 								AS JOBCODE
					--COALESCE(AJ.JOBCODE,'')			AS JOBCODE,
				,	'' 								AS JOBNAME
					--DBO.UF_USERINFO_JOBNAME2(M.COMPANYCODE, M.EMPID, P_LANGCODE) AS JOBNAME,
				,	COALESCE(AJ.DUTYCODE,'')		AS DUTYCODE
				,	COALESCE(D.DUTYNAME,'')			AS DUTYNAME
				,	COALESCE(M.FAXNUMBER, '')		AS FAXNUMBER
				,	'' 								AS SIGNID
				--,	COALESCE(DBO.UF_USERINFO_SIGN(M.COMPANYCODE, M.EMPID), '') AS SIGNID
				,	COALESCE(M.LOCATIONCODE, '')	AS LOCATIONCODE
				,	COALESCE(M.DATEOFBIRTH, '')		AS DATEOFBIRTH
				,	'N'								AS ISMAINDEPT
				,	COALESCE(DP.KOSTL, '')			AS KOSTL
				,	'ADDJ'							AS ICON
				,	COALESCE(D.SORTNO, 9999)		AS DSORTNO
				,	COALESCE(R.SORTNO, 9999)		AS RSORTNO
				,	COALESCE(M.SITECOMPANY, '')				AS SITECOMPANYCODE
				,	COALESCE(SCL.COMPANY,'')				AS SITECOMPANYNAME
				,	COALESCE(M.CULTURE, '')					AS CULTURE
			FROM 
					TYJINFWLIB.ORG_ADDITIONALJOB AS AJ
					INNER JOIN TYJINFWLIB.ORG_USER AS M
						ON	AJ.COMPANYCODE		= M.COMPANYCODE
						AND	AJ.EMPID			= M.EMPID
						AND	M.DISPLAYYN = 'Y'
					LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL
						ON	M.EMPID				= UL.EMPID
						AND	UL.LANGCODE			= P_LANGCODE 
						AND	M.COMPANYCODE		= UL.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL
						ON	AJ.DEPTCODE			= DL.DEPTCODE 
						AND	DL.LANGCODE			= P_LANGCODE 
						AND	AJ.ADDCOMPANYCODE	= DL.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
						ON	AJ.ADDCOMPANYCODE	= CL.COMPANYCODE
						AND	CL.LANGUAGECODE		= P_LANGCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS SCL
						ON	M.SITECOMPANY 		= SCL.COMPANYCODE
						AND	SCL.LANGUAGECODE	= P_LANGCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS R
						ON	AJ.RANKCODE			= R.RANKCODE 
						AND	R.LANGCODE			= P_LANGCODE 
						--AND	AJ.ADDCOMPANYCODE	= R.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS D 
						ON  AJ.DUTYCODE = D.DUTYCODE 
						AND D.LANGCODE = P_LANGCODE 
						--AND AJ.ADDCOMPANYCODE = D.COMPANYCODE 
					--LEFT OUTER JOIN DBO.TB_JOB J
					--	ON	AJ.JOBCODE			= J.JOBCODE 
					--	AND	J.LANGCODE			= P_LANGCODE 
					--	AND	AJ.ADDCOMPANYCODE	= J.COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS DP
						ON	AJ.DEPTCODE			= DP.DEPTCODE 
						AND AJ.ADDCOMPANYCODE	= DP.COMPANYCODE
			WHERE 
					M.COMPANYCODE				= CASE
													WHEN M.DPARTNER = '1'
													THEN P_COMPANYCODE
													ELSE M.COMPANYCODE
												END
			--		AJ.ADDCOMPANYCODE 			= P_COMPANYCODE
			--AND		COALESCE(P_ISDEACTIVE, '') 	= 'Y'
		)
		SELECT
				M.EMPID
			,	M.REMPID
			,	M.EXTENSIONNUMBER
			,	M.CELLPHONE
			,	M.TEAMCHIEFYN
			,	CASE WHEN M.USERNAME = '' THEN M.DISPLAYNAME ELSE M.USERNAME END AS USERNAME
			,	M.DISPLAYNAME
			,	M.EMAIL
			,	M.DEPTCODE
			,	CASE WHEN M.DEPTNAME = '' THEN DL.DEPTNAME ELSE M.DEPTNAME END DEPTNAME
			,	M.COMPANYCODE
			,	CASE WHEN M.COMPANYNAME = '' THEN CL.COMPANY ELSE M.COMPANYNAME END COMPANYNAME
			,	M.RANKCODE
			,	CASE WHEN M.RANKNAME = '' THEN R.RANKNAME ELSE M.RANKNAME END RANKNAME
			,	M.JOBCODE
			,	M.JOBNAME
			,	M.DUTYCODE
			,	CASE WHEN M.DUTYNAME = '' THEN D.DUTYNAME ELSE M.DUTYNAME END DUTYNAME
			,	M.FAXNUMBER
			,	M.SIGNID
			,	M.LOCATIONCODE
			,	M.DATEOFBIRTH
			,	M.ISMAINDEPT
			,	M.KOSTL
			,	M.ICON
			,	M.DSORTNO
			,	M.RSORTNO
			,	M.SITECOMPANYCODE
			,	M.SITECOMPANYNAME
			,	M.CULTURE
		FROM
				CTE AS M
				LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL
					ON 	M.COMPANYCODE	= DL.COMPANYCODE
					AND DL.LANGCODE 	= 'KO'
					AND M.DEPTCODE 		= DL.DEPTCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
					ON 	M.COMPANYCODE = CL.COMPANYCODE
					AND CL.LANGUAGECODE = 'KO'
				LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS R
					ON	R.LANGCODE 		= 'KO'
					AND M.RANKCODE 		= R.RANKCODE
					--AND M.COMPANYCODE 	= R.COMPANYCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS D
					ON	D.LANGCODE 		= 'KO'
					AND M.DUTYCODE 		= D.DUTYCODE
					--AND M.COMPANYCODE 	= D.COMPANYCODE
		WHERE
				--ISNULL(M.USERNAME, M.DISPLAYNAME)			LIKE '%' + P_KEYWORD + '%'
				M.REMPID IN (	SELECT
										LOWER(EMPID) AS EMPID
								FROM
										TYJINFWLIB.ORG_USERLANG
								WHERE
										USERLNAME LIKE '%' || P_KEYWORD || '%'
									--	(
									--		LANGCODE != 'EN' AND COALESCE(USERLNAME || USERFNAME, '') LIKE '%' || P_KEYWORD || '%'
									--	)
									--OR	(
									--		LANGCODE = 'EN' AND COALESCE(USERFNAME || USERLNAME, '') LIKE '%' || P_KEYWORD || '%'
									--	)
								)
		OR		M.JOBNAME			LIKE '%' || P_KEYWORD || '%'
		OR		M.REMPID			LIKE '%' || P_KEYWORD || '%'
		OR		M.EMAIL				LIKE '%' || P_KEYWORD || '%'
		OR		M.DEPTNAME			LIKE '%' || P_KEYWORD || '%'
		ORDER BY M.DSORTNO ASC, M.TEAMCHIEFYN DESC, M.RSORTNO ASC, M.USERNAME ASC, M.ISMAINDEPT DESC;
		OPEN REFCURSOR;
	END MAIN;
END P1;