-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORM_DEPTMEMBER_LIST
-- 작성자     : 장경환
-- 작성일     : 2010-07-13
-- 설명       : 부서의 임직원를 검색하여 조회한다..
-- 예문       : CALL TYJINFWLIB.ORM_DEPTMEMBER_LIST('321000','0100','N','ko', '')
-- DB2 변환   : 이전프로시져명 up_OrgChart_Select_DeptMember
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORM_DEPTMEMBER_LIST
CREATE PROCEDURE TYJINFWLIB.ORM_DEPTMEMBER_LIST
(
		P_DEPTCODE		CHAR(12)
	,	P_COMPANYCODE	CHAR(10)
	,	P_ISRELATIVE	CHAR(1)
	,	P_LANGCODE		CHAR(2)
	,	P_ISDEACTIVE	CHAR(1)
)
	LANGUAGE SQL
	RESULT SETS 2
	
P1 : BEGIN
	SET P_ISRELATIVE = 'N';

	IF COALESCE(P_COMPANYCODE,'') = '' THEN
		SET P_COMPANYCODE = '1000';
	END IF;
	
	-- 파라미터로 넘어온 language code의 데이터가 없을때 한국어로 셋팅
	IF NOT EXISTS(SELECT EmpID FROM TYJINFWLIB.ORG_USERLANG WHERE LangCode = P_LANGCODE and CompanyCode = P_COMPANYCODE) THEN
		SET P_LANGCODE = 'ko';
	END IF;
		
	MAIN1 : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		SELECT
				D.DEPTCODE
			,	(
					SELECT
							COALESCE(DL2.DEPTNAME, D2.DISPLAYNAME) AS DEPTNAME
					FROM
							TYJINFWLIB.ORG_DEPT AS D2
							LEFT OUTER JOIN	TYJINFWLIB.ORG_DEPTLANG AS DL2
								ON	D2.DEPTCODE		= DL2.DEPTCODE
								AND	D2.COMPANYCODE	= DL2.COMPANYCODE
								AND	DL2.LANGCODE	= P_LANGCODE
					WHERE
							(
								COALESCE(D.COMPANYCODE, '')		= ''
							OR	D2.COMPANYCODE					= D.COMPANYCODE
							)
					AND		D2.DEPTCODE = D.DEPTCODE
				) AS DEPTNAME
			,	D.COMPANYCODE AS COMPANYCODE
			,	COALESCE(CL.COMPANY,'') AS COMPANYNAME
			,	COALESCE(D.DEPTEMAIL, '') AS DEPTEMAIL
		FROM
				TYJINFWLIB.ORG_DEPT AS D 
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
					ON	D.COMPANYCODE 		= CL.COMPANYCODE
					AND	CL.LANGUAGECODE		= P_LANGCODE
		WHERE
				D.DEPTCODE 		= P_DEPTCODE
		AND		D.COMPANYCODE 	= P_COMPANYCODE
		FETCH FIRST 1 ROWS ONLY;
		
		OPEN REFCURSOR;
	END MAIN1;
	
	MAIN2 : BEGIN
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
		SELECT
				M.LOGINID								AS EMPID		-- 업체 로그인 아이디 대문자 P 때문에 LOWER(M.LOGINID)에서 LOWER 제거. 문제시 원복 2017-06-22 장윤호
			,	M.EMPID									AS REMPID		-- 그룹등록시 그룹멤버ID가 소문자로 들어감으로 LOWER(M.EMPID) LOWER 제거. 문제시 원복 2017-08-31 장윤호
			,	COALESCE(M.EXTENSIONNUMBER,'')			AS EXTENSIONNUMBER
			,	COALESCE(M.CELLPHONE,'')				AS CELLPHONE
			,	COALESCE(M.LOCATIONCODE,'')				AS LOCATIONCODE
			,	COALESCE(D.TEAMCHIEFYN, 'N')			AS TEAMCHIEFYN
			--,	COALESCE(UL.USERLNAME, UL_K.USERLNAME)	AS USERNAME
			,	TYJINFWLIB.UF_USERINFO_USERNAME2(M.EMPID, P_LANGCODE) AS USERNAME
			,	COALESCE(M.DISPLAYNAME,'')				AS DISPLAYNAME
			,	COALESCE(M.EMAIL,'')					AS EMAIL
			,	COALESCE(M.MAINDEPTCODE,'')				AS DEPTCODE
			,	COALESCE(DL.DEPTNAME,'')				AS DEPTNAME
			,	COALESCE(CL.COMPANYCODE,'')				AS COMPANYCODE
			,	COALESCE(CL.COMPANY,'')					AS COMPANYNAME
			,	COALESCE(M.RANKCODE,'')					AS RANKCODE
			--,	COALESCE(R.RANKNAME,'')					AS RANKNAME
			,	''										AS RANKNAME
			,	''										AS JOBCODE
			--,	COALESCE(J.JOBCODE,'')					AS JOBCODE
			,	''										AS JOBNAME
			--,	DBO.UF_USERINFO_JOBNAME2(M.COMPANYCODE, M.EMPID, P_LANGCODE) AS JOBNAME
			
			,	COALESCE(D.DUTYCODE,'')					AS DUTYCODE
			,	COALESCE(D.DUTYNAME,'')					AS DUTYNAME

			,	COALESCE(M.FAXNUMBER, '')				AS FAXNUMBER
			,	''										AS SIGNID
			--,	COALESCE(DBO.UF_USERINFO_SIGN(M.COMPANYCODE, M.EMPID), '') AS SIGNID
			,	COALESCE(M.DATEOFBIRTH, '')				AS DATEOFBIRTH
			,	COALESCE(DP.KOSTL, '')					AS KOSTL
			,	''										AS ICON
			--,	COALESCE(DD.USRTYPE, '')				AS ICON
			,	COALESCE(D.SORTNO, 9999)				AS DSORTNO
			,	COALESCE(R.SORTNO, 9999)				AS RSORTNO
			,	COALESCE(M.SITECOMPANY, '')				AS SITECOMPANYCODE
			,	COALESCE(SCL.COMPANY,'')				AS SITECOMPANYNAME
			,	COALESCE(M.CULTURE, '')					AS CULTURE
		FROM
				TYJINFWLIB.ORG_USER AS M
				LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL
					ON	M.EMPID 			= UL.EMPID
					AND	UL.LANGCODE 		= P_LANGCODE
					AND	M.COMPANYCODE 		= UL.COMPANYCODE
				--LEFT OUTER JOIN ORG_USERLANG AS UL_K
				--	ON	M.EMPID 		= UL_K.EMPID 
				--	AND	UL_K.LANGCODE 	= 'ko'
				--	AND	M.COMPANYCODE 	= UL_K.COMPANYCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL
					ON	M.MAINDEPTCODE 		= DL.DEPTCODE
					AND DL.LANGCODE 		= P_LANGCODE
					AND M.COMPANYCODE 		= DL.COMPANYCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
					ON	M.COMPANYCODE 		= CL.COMPANYCODE
					AND	CL.LANGUAGECODE		= P_LANGCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS SCL
					ON	M.SITECOMPANY 		= SCL.COMPANYCODE
					AND	SCL.LANGUAGECODE	= P_LANGCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS R
					ON	M.RANKCODE			= R.RANKCODE
					AND	R.LANGCODE 			= P_LANGCODE
					--AND	M.COMPANYCODE = R.COMPANYCODE 
				LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS D 
					ON	M.DUTYCODE 			= D.DUTYCODE 
					AND	D.LANGCODE 			= P_LANGCODE 
					--AND	M.COMPANYCODE = D.COMPANYCODE 
				--LEFT OUTER JOIN DBO.TB_JOB J 
				--	ON	M.JOBCODE = J.JOBCODE 
				--	AND	J.LANGCODE = P_LANGCODE
				--	AND	M.COMPANYCODE = J.COMPANYCODE 
				LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS DP
					ON	M.MAINDEPTCODE 		= DP.DEPTCODE
					AND M.COMPANYCODE		= DP.COMPANYCODE
				--LEFT OUTER JOIN	DBO.TB_DEPTDOCMGR	AS DD
				--	ON	M.MAINDEPTCODE	= DD.DEPTCODE
				--	AND M.COMPANYCODE	= DD.COMPANYCODE
				--	AND	M.EMPID			= DD.EMPID
				--	AND	DD.USEYN		= 'Y'
		WHERE
				MAINDEPTCODE	= P_DEPTCODE
		AND		M.DISPLAYYN		= 'Y'
		AND		M.COMPANYCODE	= P_COMPANYCODE
		--AND		(COALESCE(P_ISDEACTIVE, '') = 'Y')

		--UNION -- 겸직을 사용하지 않음으로 주석처리함
		--
		--/* 겸직정보 [파견과 부수직은 겸직처리에서 제외함 */
		--SELECT
		--		M.LOGINID								AS EMPID		-- 업체 로그인 아이디 대문자 P 때문에 LOWER(M.LOGINID)에서 LOWER 제거. 문제시 원복 2017-06-22 장윤호
		--	,	M.EMPID 								AS REMPID
		--	,	M.EXTENSIONNUMBER
		--	,	M.CELLPHONE
		--	,	COALESCE(M.LOCATIONCODE, '')			AS LOCATIONCODE
		--	,	COALESCE(AJ.TEAMCHIEFYN, 'N')			AS TEAMCHIEFYN
		--	--,	COALESCE(UL.USERLNAME, UL_K.USERLNAME)	AS USERNAME
		--	,	TYJINFWLIB.UF_USERINFO_USERNAME2(M.EMPID, P_LANGCODE)				AS USERNAME
		--	,	COALESCE(M.DISPLAYNAME,'')				AS DISPLAYNAME
		--	,	COALESCE(M.EMAIL,'')					AS EMAIL
		--	,	COALESCE(AJ.DEPTCODE,'')				AS DEPTCODE
		--	,	COALESCE(DL.DEPTNAME,'')				AS DEPTNAME
		--	,	COALESCE(CL.COMPANYCODE,'')				AS COMPANYCODE
		--	,	COALESCE(CL.COMPANY,'')					AS COMPANYNAME
		--	,	COALESCE(AJ.RANKCODE,'')				AS RANKCODE
		--	,	COALESCE(R.RANKNAME,'')					AS RANKNAME
		--	,	''										AS JOBCODE
		--	--,	COALESCE(AJ.JOBCODE,'')					AS JOBCODE
		--	,	''										AS JOBNAME
		--	--,	DBO.UF_USERINFO_JOBNAME2(M.COMPANYCODE, M.EMPID, P_LANGCODE)			AS JOBNAME
		--	,	COALESCE(AJ.DUTYCODE,'')				AS DUTYCODE
		--	,	COALESCE(D.DUTYNAME,'')					AS DUTYNAME
		--	,	COALESCE(M.FAXNUMBER, '')				AS FAXNUMBER
		--	,	''										AS SIGNID
		--	--,	COALESCE(DBO.UF_USERINFO_SIGN(M.COMPANYCODE, M.EMPID), '') AS SIGNID
		--	,	COALESCE(M.DATEOFBIRTH, '')				AS DATEOFBIRTH
		--	,	COALESCE(DP.KOSTL, '')					AS KOSTL
		--	,	'ADDJ'									AS ICON
		--	,	COALESCE(D.SORTNO, 9999)				AS DSORTNO
		--	,	COALESCE(R.SORTNO, 9999)				AS RSORTNO
		--	,	COALESCE(M.SITECOMPANY, '')				AS SITECOMPANYCODE
		--	,	COALESCE(SCL.COMPANY,'')				AS SITECOMPANYNAME
		--	,	COALESCE(M.CULTURE, '')					AS CULTURE
		--FROM 
		--		TYJINFWLIB.ORG_ADDITIONALJOB AS AJ 
		--		INNER JOIN TYJINFWLIB.ORG_USER AS M 
		--			ON	AJ.LOGINID 			= M.LOGINID 
		--			AND AJ.COMPANYCODE 		= M.COMPANYCODE
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL 
		--			ON	M.EMPID 			= UL.EMPID 
		--			AND UL.LANGCODE 		= P_LANGCODE 
		--			AND	M.COMPANYCODE 		= UL.COMPANYCODE
		--		--LEFT OUTER JOIN ORG_USERLANG AS UL_K
		--		--	ON	M.EMPID 		= UL_K.EMPID 
		--		--	AND	UL_K.LANGCODE 	= 'ko'
		--		--	AND	M.COMPANYCODE 	= UL_K.COMPANYCODE
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL 
		--			ON	AJ.DEPTCODE 		= DL.DEPTCODE 
		--			AND DL.LANGCODE 		= P_LANGCODE 
		--			AND AJ.ADDCOMPANYCODE 	= DL.COMPANYCODE
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL 
		--			ON	M.COMPANYCODE 		= CL.COMPANYCODE 
		--			AND CL.LANGUAGECODE		= P_LANGCODE
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS SCL
		--			ON	M.SITECOMPANY 		= SCL.COMPANYCODE
		--			AND	SCL.LANGUAGECODE	= P_LANGCODE
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS R 
		--			ON	AJ.RANKCODE 		= R.RANKCODE 
		--			AND R.LANGCODE 			= P_LANGCODE 
		--			--AND AJ.ADDCOMPANYCODE 	= R.COMPANYCODE 
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS D 
		--			ON  AJ.DUTYCODE 		= D.DUTYCODE 
		--			AND D.LANGCODE 			= P_LANGCODE 
		--			--AND AJ.ADDCOMPANYCODE 	= D.COMPANYCODE 
		--		--LEFT OUTER JOIN DBO.TB_JOB J 
		--		--	ON	AJ.JOBCODE = J.JOBCODE 
		--		--	AND J.LANGCODE = P_LANGCODE 
		--		--	AND AJ.ADDCOMPANYCODE = J.COMPANYCODE 
		--		LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS DP
		--			ON	AJ.DEPTCODE			= DP.DEPTCODE 
		--			AND AJ.ADDCOMPANYCODE	= DP.COMPANYCODE
		--WHERE
		--		AJ.DEPTCODE = P_DEPTCODE
		----AND		(AJ.TYPECODE IS NOT NULL AND AJ.TYPECODE <> '1' AND AJ.TYPECODE <> '2')
		--AND		M.DISPLAYYN = 'Y'
		--AND		AJ.COMPANYCODE = P_COMPANYCODE		-- AJ.ADDCOMPANYCODE 자릿수가 CHAR(4)이고 값이 NULL 이므로 AJ.ADDCOMPANYCODE 를 AJ.COMPANYCODE 로 수정		2017-05-08 장윤호

		ORDER BY DSORTNO ASC, TEAMCHIEFYN DESC, RSORTNO ASC, REMPID ASC, USERNAME ASC;
		
		OPEN REFCURSOR2;
		--UNION
		
		--SELECT
		--		LOWER(M.LOGINID)				AS EMPID
		--	,	LOWER(M.EMPID)					AS REMPID
		--	,	COALESCE(M.EXTENSIONNUMBER,'')	AS EXTENSIONNUMBER
		--	,	COALESCE(M.CELLPHONE,'')			AS CELLPHONE
		--	,	COALESCE(M.LOCATIONCODE,'')		AS LOCATIONCODE
		--	,	COALESCE(D.TEAMCHIEFYN, 'N')		AS TEAMCHIEFYN
		--	,	DBO.UF_USERINFO_USERNAME2(M.EMPID, P_LANGCODE) AS USERNAME
		--	,	COALESCE(M.DISPLAYNAME,'')		AS DISPLAYNAME
		--	,	COALESCE(M.EMAIL,'')				AS EMAIL
		--	,	COALESCE(DD.DEPTCODE,'')		AS DEPTCODE
		--	,	COALESCE(DL.DEPTNAME,'')			AS DEPTNAME
		--	,	COALESCE(CL.COMPANYCODE,'')		AS COMPANYCODE
		--	,	COALESCE(CL.COMPANY,'')			AS COMPANYNAME
		--	,	COALESCE(M.RANKCODE,'')			AS RANKCODE
		--	,	COALESCE(R.RANKNAME,'')			AS RANKNAME
		--	,	COALESCE(J.JOBCODE,'')			AS JOBCODE
		--	,	DBO.UF_USERINFO_JOBNAME2(M.COMPANYCODE, M.EMPID, P_LANGCODE)			AS JOBNAME
		--	,	COALESCE(D.DUTYCODE,'')			AS DUTYCODE
		--	,	COALESCE(D.DUTYNAME,'')			AS DUTYNAME
		--	,	COALESCE(M.FAXNUMBER, '')			AS FAXNUMBER
		--	,	COALESCE(DBO.UF_USERINFO_SIGN(M.COMPANYCODE, M.EMPID), '')	 AS SIGNID
		--	,	COALESCE(M.LOCATIONCODE, '')		AS LOCATIONCODE
		--	,	COALESCE(M.DATEOFBIRTH, '')		AS DATEOFBIRTH
		--	,	COALESCE(DP.KOSTL, '')			AS KOSTL
		--	,	COALESCE(DD.USRTYPE, '')			AS ICON
		--	,	COALESCE(D.SORTNO, 9999)			AS DSORTNO
		--	,	COALESCE(R.SORTNO, 9999)			AS RSORTNO
		--FROM
		--		DBO.TB_DEPTDOCMGR	AS DD
		--		INNER JOIN	DBO.TB_USER M 
		--			ON	DD.USERCOMPANYCODE		= M.COMPANYCODE
		--			AND	DD.EMPID				= M.EMPID
		--			AND	M.DISPLAYYN				= 'Y'
		--		LEFT OUTER JOIN ORG_USERLANG AS UL 
		--			ON	M.EMPID = UL.EMPID 
		--			AND	UL.LANGCODE = P_LANGCODE 
		--			AND	M.COMPANYCODE = UL.COMPANYCODE
		--		LEFT OUTER JOIN DBO.TB_DEPTLANG DL 
		--			ON	DD.DEPTCODE = DL.DEPTCODE 
		--			AND DL.LANGCODE = P_LANGCODE 
		--			AND DD.COMPANYCODE	= DL.COMPANYCODE
		--		LEFT OUTER JOIN DBO.TB_COMPANYGLOBAL CL 
		--			ON	M.COMPANYCODE = CL.COMPANYCODE 
		--			AND	CL.LANGUAGECODE = P_LANGCODE
		--		LEFT OUTER JOIN DBO.TB_RANK R 
		--			ON	M.RANKCODE = R.RANKCODE 
		--			AND	R.LANGCODE = P_LANGCODE 
		--			AND	M.COMPANYCODE = R.COMPANYCODE 
		--		LEFT OUTER JOIN DBO.TB_DUTY D 
		--			ON	M.DUTYCODE = D.DUTYCODE 
		--			AND	D.LANGCODE = P_LANGCODE 
		--			AND	M.COMPANYCODE = D.COMPANYCODE 
		--		LEFT OUTER JOIN DBO.TB_JOB J 
		--			ON	M.JOBCODE = J.JOBCODE 
		--			AND	J.LANGCODE = P_LANGCODE
		--			AND	M.COMPANYCODE = J.COMPANYCODE 
		--		LEFT OUTER JOIN DBO.TB_DEPT DP
		--			ON	M.MAINDEPTCODE = DP.DEPTCODE 
		--			AND M.COMPANYCODE = DP.COMPANYCODE
		--WHERE
		--		DD.DEPTCODE		= P_DEPTCODE
		--AND		DD.USEYN		= 'Y'
		--AND		DD.COMPANYCODE	= P_COMPANYCODE
		--AND		DD.USRTYPE		= '01'
		--AND		COALESCE(M.DEACTIVE, 'N')	<> 'Y'
		
		--ORDER BY DSORTNO ASC, TEAMCHIEFYN DESC, RSORTNO ASC, REMPID ASC, USERNAME ASC
	END MAIN2;
END P1;