-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORM_COMPANY_LIST
-- 작성자     : 장경환
-- 작성일     : 2010-07-13
-- 설명       : 회사를 조회한다.
-- 예문       : CALL TYJINFWLIB.ORM_COMPANY_LIST('KO')
-- DB2 변환   : 이전프로시져명 up_OrgChart_Select_Company
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORM_COMPANY_LIST
CREATE PROCEDURE TYJINFWLIB.ORM_COMPANY_LIST
(
		P_LANGCODE		VARCHAR(10)
)
	LANGUAGE SQL
    RESULT SETS 2
P1 : BEGIN
	
	
	IF NOT EXISTS (SELECT COMPANYCODE FROM TYJINFWLIB.ORG_COMPANYLANG WHERE LANGUAGECODE = P_LANGCODE) THEN
		SET P_LANGCODE = 'en';
	END IF;
	
	MAIN1 : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		SELECT
				COALESCE(CL.COMPANY, CL2.COMPANY) AS COMPANYNAME
			,	C.COMPANYCODE AS COMPANYCODE
		FROM
				TYJINFWLIB.ORG_COMPANY AS C 
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL 
					ON	C.COMPANYCODE		= CL.COMPANYCODE
					AND	CL.LANGUAGECODE		= P_LANGCODE
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL2
					ON	C.COMPANYCODE		= CL2.COMPANYCODE
					AND	CL2.LANGUAGECODE	= 'ko'
		ORDER BY C.DISPLAYORDER;
		OPEN REFCURSOR;
	END MAIN1;
	
	MAIN2 : BEGIN
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
		SELECT
				CG.COMPANY AS COMPANYNAME
			,	C.COMPANYCODE AS COMPANYCODE
		FROM
				TYJINFWLIB.ORG_COMPANY AS C 
				INNER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CG
					ON	C.COMPANYCODE = CG.COMPANYCODE 
					AND	CG.LANGUAGECODE	= P_LANGCODE
		ORDER BY C.DISPLAYORDER;
		OPEN REFCURSOR2;
	END MAIN2;
END P1