
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORM_GROUPMEMBER_LIST
-- 작성자     : 장경환
-- 작성일     : 2010-07-13
-- 설명       : 그룹 사용자를 조회한다..
-- 예문       : CALL TYJINFWLIB.ORM_GROUPMEMBER_LIST ('1000', 'GW100000', 'cn')
-- DB2 변환   : 이전프로시져명 up_OrgChart_Select_GroupMember
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORM_GROUPMEMBER_LIST
CREATE PROCEDURE TYJINFWLIB.ORM_GROUPMEMBER_LIST
(
		P_COMPANYCODE	VARCHAR(50)
	,	P_GROUPCODE		VARCHAR(50)
	,	P_LANGCODE		VARCHAR(10)
)
	LANGUAGE SQL
	RESULT SETS 2
	--SET OPTION OUTPUT=*PRINT
	
P1 : BEGIN
	MAIN1 : BEGIN
		--그룹
		DECLARE REFCURSOR1 CURSOR WITH RETURN FOR
		SELECT
					G . GRPID			AS GROUPCODE
				,	GL . GRPNAME		AS GROUPNAME
				,	''				AS GROUPMAIL
		FROM
				TYJINFWLIB . ORG_GROUP AS G
				LEFT JOIN TYJINFWLIB . ORG_GROUPLANG AS GL
					ON G . GRPID = GL . GRPID
		WHERE
				G . GRPID			= P_GROUPCODE
		AND		GL . LANGCODE		= P_LANGCODE
		AND		G . USEYN			= '1' ;
		OPEN REFCURSOR1 ;
	END MAIN1 ;
	
	MAIN2 : BEGIN
		DECLARE P_GRPEXT VARCHAR ( 100 ) ;
		SET P_GRPEXT = ( SELECT GRPEXT FROM TYJINFWLIB . ORG_GROUP WHERE GRPID = P_GROUPCODE ) ;
		
		DECLARE GLOBAL TEMPORARY TABLE SESSION . EXT (
				COMPANYCODE			VARCHAR ( 50 )
			,	EMPID				VARCHAR ( 32 )
			,	MAINDEPTCODE		VARCHAR ( 32 )
			,	ACLCOMPANYCODE		VARCHAR ( 50 )
		) WITH REPLACE ;
		
		IF ( P_GRPEXT = 'OFFICER' ) THEN
			INSERT INTO SESSION . EXT (
					COMPANYCODE
				,	EMPID
				,	MAINDEPTCODE
				,	ACLCOMPANYCODE
			)
			SELECT
						U . COMPANYCODE
					,	U . EMPID
					,	U . MAINDEPTCODE
					,	'1000'			AS ACLCOMPANYCODE
			FROM
					TYJINFWLIB . ORG_USER	AS U
					INNER JOIN	TYJINFWLIB . ORG_RANK AS R
						ON	U . COMPANYCODE	= R . COMPANYCODE
						AND	U . RANKCODE		= R . RANKCODE
						AND	R . LANGCODE		= 'KO'
			WHERE
					U . DISPLAYYN			= 'Y'
			--AND		U.RANKCODE			IN ('01','02','03','04','05','06','07','08','09','10','11','13','14','Z6', 'Z7')
			-- 직군코드가 임원인 경우로 수정(Z6:고문은 예외처리) : 2016-02-17
			--AND		(U.RANKCODE			IN (SELECT DISTINCT RANKCODE FROM TB_RANK WHERE COMPANYCODE = '1000' AND JOBGROUP = 'JG01') OR U.RANKCODE IN ('Z6'))
			AND		( U . RANKCODE IN ( 'Z6' )	OR R . JOBGROUP = 'JG01' )
			AND		U . COMPANYCODE		= '1000'
			AND		U . MAINDEPTCODE		NOT LIKE 'ECT%' ;
		ELSEIF ( P_GRPEXT = 'TEAMCHIEF' ) THEN
			INSERT INTO SESSION . EXT (
					COMPANYCODE
				,	EMPID
				,	MAINDEPTCODE
				,	ACLCOMPANYCODE
			)
			SELECT
						U . COMPANYCODE
					,	U . EMPID
					,	U . MAINDEPTCODE
					,	'1000'			AS ACLCOMPANYCODE
			FROM
					TYJINFWLIB . ORG_USER	AS U
			WHERE
					U . DISPLAYYN			= 'Y'
			AND		U . DUTYCODE			IN ( '010' , '011' )
			AND		U . COMPANYCODE		= '1000'
			AND		U . MAINDEPTCODE		NOT LIKE 'ECT%'
			
			UNION ALL
			
			SELECT
						U . COMPANYCODE
					,	U . EMPID
					,	U . DEPTCODE
					,	'1000'			AS ACLCOMPANYCODE
			FROM
					TYJINFWLIB . ORG_ADDITIONALJOB	AS U
			WHERE
					U . DUTYCODE			IN ( '010' , '011' )
			AND		U . ADDCOMPANYCODE	= '1000'
			AND		U . DEPTCODE			NOT LIKE 'ECT%' ;
		END IF ;
			
		DECLARE GLOBAL TEMPORARY TABLE SESSION . MST (
				COMPANYCODE			VARCHAR ( 50 )
			,	EMPID				VARCHAR ( 32 )
			,	MAINDEPTCODE		VARCHAR ( 32 )
			,	ACLCOMPANYCODE		VARCHAR ( 50 )
		) WITH REPLACE ;
		
		INSERT INTO SESSION . MST (
				COMPANYCODE
			,	EMPID
			,	MAINDEPTCODE
			,	ACLCOMPANYCODE
		)
		WITH CTE ( COMPANYCODE , EMPID ) AS (
			SELECT
						COMPANYCODE
					,	USRID AS EMPID
			FROM
					TYJINFWLIB . ORG_GROUPUSR
			WHERE
					GRPID			= P_GROUPCODE
			AND		USRTYPE			= '1'
	
			UNION ALL
	
			SELECT
						D . USERCOMPANYCODE	AS COMPANYCODE
					,	D . EMPID				AS EMPID
			FROM
					TYJINFWLIB . ORG_GROUPUSR AS G
					INNER JOIN TYJINFWLIB . ORG_DEPTUSR AS D
						ON	G . COMPANYCODE		= D . COMPANYCODE
						AND	G . USRID				= D . DEPTCODE
						AND	G . USRTYPE			= '2'
			WHERE
					G . GRPID			= P_GROUPCODE
		) , LIST ( COMPANYCODE , EMPID , MAINDEPTCODE , ACLCOMPANYCODE ) AS (
			SELECT
						C . COMPANYCODE
					,	C . EMPID
					,	U . MAINDEPTCODE
					,	C . COMPANYCODE AS ACLCOMPANYCODE
			FROM
					CTE	AS C
					INNER JOIN TYJINFWLIB . ORG_USER AS U
						ON	C . COMPANYCODE		= U . COMPANYCODE
						AND	C . EMPID				= U . EMPID
						AND	U . DISPLAYYN			= 'Y'
						--AND	COALESCE ( DEACTIVE , 'N' )	<> 'Y'
	
			/*UNION ALL
	
			SELECT
						COMPANYCODE
					,	EMPID
					,	MAINDEPTCODE
					,	ACLCOMPANYCODE AS ACLCOMPANYCODE
			FROM
					SESSION . EXT*/
		)
		SELECT
				COMPANYCODE
			,	EMPID
			,	MAINDEPTCODE
			,	ACLCOMPANYCODE
		FROM
				LIST ;
		
		MLIST : BEGIN
			--그룹 멤버
			
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
			SELECT
					M . LOGINID								AS EMPID		-- 업체 로그인 아이디 대문자 P 때문에 LOWER(M.LOGINID)에서 LOWER 제거. 문제시 원복 2017-06-22 장윤호
				,	LOWER ( M . EMPID )							AS REMPID
				,	COALESCE ( M . EXTENSIONNUMBER , '' )			AS EXTENSIONNUMBER
				,	COALESCE ( M . CELLPHONE , '' )				AS CELLPHONE
				,	COALESCE ( M . LOCATIONCODE , '' )				AS LOCATIONCODE
				,	COALESCE ( D . TEAMCHIEFYN , 'N' )			AS TEAMCHIEFYN
				,	COALESCE ( UL . USERLNAME , UL_K . USERLNAME )	AS USERNAME
				,	COALESCE ( M . DISPLAYNAME , '' )				AS DISPLAYNAME
				,	COALESCE ( M . EMAIL , '' )					AS EMAIL
				,	COALESCE ( G . MAINDEPTCODE , '' )				AS DEPTCODE
				,	COALESCE ( DL . DEPTNAME , DL_K . DEPTNAME )	AS DEPTNAME
				,	COALESCE ( CL . COMPANYCODE , '' )				AS COMPANYCODE
				,	COALESCE ( CL . COMPANY , '' )					AS COMPANYNAME
				,	COALESCE ( M . RANKCODE , '' )					AS RANKCODE
				,	COALESCE ( R . RANKNAME , '' )					AS RANKNAME
				,	''										AS JOBCODE
				,	''										AS JOBNAME
				,	COALESCE ( D . DUTYCODE , '' )					AS DUTYCODE
				,	COALESCE ( D . DUTYNAME , '' )					AS DUTYNAME
				,	COALESCE ( M . FAXNUMBER , '' )				AS FAXNUMBER
				,	''										AS SIGNID
				,	COALESCE ( M . LOCATIONCODE , '' )			AS LOCATIONCODE
				,	COALESCE ( M . DATEOFBIRTH , '' )				AS DATEOFBIRTH
				,	COALESCE ( DP . KOSTL , '' )					AS KOSTL
				,	''										AS ICON
				,	COALESCE ( D . SORTNO , 9999 )				AS DSORTNO
				,	COALESCE ( R . SORTNO , 9999 )				AS RSORTNO
			FROM
					SESSION . MST AS G
					INNER JOIN TYJINFWLIB . ORG_USER AS M	
						ON G . EMPID = M . EMPID AND G . COMPANYCODE = M . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_USERLANG AS UL
						ON	M . EMPID = UL . EMPID
						AND	UL . LANGCODE = P_LANGCODE
						AND	M . COMPANYCODE = UL . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_USERLANG AS UL_K
						ON	M . EMPID		= UL_K . EMPID
						AND	UL_K . LANGCODE	= 'KO'
						AND	M . COMPANYCODE	= UL_K . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_DEPTLANG AS DL
						ON	G . MAINDEPTCODE = DL . DEPTCODE
						AND DL . LANGCODE = P_LANGCODE
						AND M . COMPANYCODE = DL . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_DEPTLANG AS DL_K
						ON	G . MAINDEPTCODE = DL_K . DEPTCODE
						AND DL_K . LANGCODE = P_LANGCODE
						AND M . COMPANYCODE = DL_K . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_COMPANYLANG AS CL
						ON	M . COMPANYCODE = CL . COMPANYCODE
						AND	CL . LANGUAGECODE = P_LANGCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_RANK AS R
						ON	M . RANKCODE = R . RANKCODE
						AND	R . LANGCODE = P_LANGCODE
						AND	M . COMPANYCODE = R . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_DUTY AS D
						ON	M . DUTYCODE = D . DUTYCODE
						AND	D . LANGCODE = P_LANGCODE
						AND	M . COMPANYCODE = D . COMPANYCODE
					LEFT OUTER JOIN TYJINFWLIB . ORG_DEPT AS DP
						ON	G . MAINDEPTCODE = DP . DEPTCODE
						AND G . COMPANYCODE = DP . COMPANYCODE
			WHERE
					M . DISPLAYYN				= 'Y'
			AND		G . ACLCOMPANYCODE		= P_COMPANYCODE -- 회사로 그룹멤버필터링
			--AND		COALESCE ( M . DEACTIVE , 'N' )	<> 'Y'
			ORDER BY DSORTNO ASC , TEAMCHIEFYN DESC , RSORTNO ASC , REMPID ASC , USERNAME ASC ;
			OPEN REFCURSOR2 ;
			
		END MLIST ;
	  
	END MAIN2 ;
END                                                                                                         ;
