-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORM_DEPT_LIST_TREE
-- 작성자     : 장경환
-- 작성일     : 2010-07-13
-- 설명       : 부서 트리를 조회한다.
-- 예문       : CALL TYJINFWLIB.ORM_DEPT_LIST_TREE('SEOHAN', '', 'N', 'ko')
-- DB2 변환   : 이전프로시져명 up_OrgChart_Select_DeptTree
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORM_DEPT_LIST_TREE
CREATE PROCEDURE TYJINFWLIB.ORM_DEPT_LIST_TREE
(
		P_COMPANYCODE		VARCHAR(50)
	,	P_PARENTDEPTCODE 	VARCHAR(50)
	,	P_ISRELATIVE		VARCHAR(1)
	,	P_LANGCODE			VARCHAR(10)
)
	LANGUAGE SQL
	RESULT SETS 1
	
P1 : BEGIN
	DECLARE P_COMPANYLANGCODE VARCHAR(10);
		
	PREV : BEGIN
		SET P_COMPANYLANGCODE = P_LANGCODE;
		SET	P_ISRELATIVE = 'N';
		IF COALESCE(P_COMPANYCODE,'') = '' THEN
			SET P_COMPANYCODE = '1000';
		END IF;
	END PREV;
	
	-- 파라미터로 넘어온 LANGUAGE CODE의 데이터가 없을때 영어로 셋팅
	IF NOT EXISTS (SELECT COMPANYCODE FROM TYJINFWLIB.ORG_COMPANYLANG  WHERE LANGUAGECODE = P_COMPANYLANGCODE) THEN
		SET P_COMPANYLANGCODE = 'en';
	END IF;
	
	IF NOT EXISTS(SELECT DEPTCODE FROM TYJINFWLIB.ORG_DEPTLANG  WHERE LANGCODE = P_LANGCODE AND COMPANYCODE = P_COMPANYCODE) THEN
		SET P_LANGCODE = 'en';
	END IF;
	
	IF ( P_ISRELATIVE = 'N' ) THEN
		IF COALESCE(P_PARENTDEPTCODE, '') = '' THEN
			MAIN1 : BEGIN
				DECLARE REFCURSOR1 CURSOR WITH RETURN FOR
				WITH MST AS (
					SELECT
							D.DEPTCODE
						,	COALESCE(DL.DEPTNAME, D.DISPLAYNAME) 			AS DEPTNAME
						,	(
								SELECT
										CASE
											WHEN COUNT(DEPTCODE) > 0 THEN 1
											ELSE 0 END AS HASSUBDEPT 
								FROM
										TYJINFWLIB.ORG_DEPT
								WHERE
										PARENTDEPTCODE	= D.DEPTCODE
								AND 	COMPANYCODE		= P_COMPANYCODE) 	AS HASSUBDEPT
						,	D.DEPTEMAIL
						,	D.COMPANYCODE									AS COMPANYCODE
						,	COALESCE(CL.COMPANY, '')						AS COMPANYNAME
						,	CASE
								WHEN D.PARENTDEPTCODE = P_COMPANYCODE
								THEN '0'
								ELSE '1' END								AS SORT_ONE
						,	D.DEPTORDER
						,	D.PARENTDEPTCODE
					FROM
							TYJINFWLIB.ORG_DEPT AS D 
							LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL 
								ON 	DL.DEPTCODE 	= D.DEPTCODE		
								AND DL.LANGCODE 	= P_LANGCODE
								AND DL.COMPANYCODE 	= D.COMPANYCODE
							LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL 
								ON CL.COMPANYCODE 	= D.COMPANYCODE
								AND CL.LANGUAGECODE = P_COMPANYLANGCODE
					WHERE
							(
								COALESCE(D.PARENTDEPTCODE, '')	= ''
							OR	D.PARENTDEPTCODE				= P_COMPANYCODE
							)
					AND		D.DISPLAYYN							= 'Y'
					AND		D.COMPANYCODE						= P_COMPANYCODE
				)
				, MST2 AS (
					SELECT
							M.*
						,	CASE
								WHEN M.COMPANYCODE = M.PARENTDEPTCODE AND M.HASSUBDEPT > 0 THEN 0
								ELSE 1
							END				AS SORT_TWO
					FROM
							MST AS M
				)
				SELECT
						*
				FROM
						MST2
				ORDER BY SORT_ONE ASC, SORT_TWO ASC, DEPTORDER ASC;
				OPEN REFCURSOR1;
			END MAIN1;
		ELSE
			MAIN2 : BEGIN
				-- 내,외부 협력업체 예외 처리 2017-07-01 장윤호
				DECLARE GLOBAL TEMPORARY TABLE SESSION.T (
						DEPTCODE		VARCHAR(12)
					,	DEPTNAME		VARGRAPHIC(100)	CCSID 1200
					,	HASSUBDEPT		INTEGER
					,	DEPTEMAIL		VARCHAR(20)
					,	COMPANYCODE		VARCHAR(10)
					,	COMPANYNAME		VARGRAPHIC(100)	CCSID 1200
				) WITH REPLACE ;

				INSERT INTO SESSION.T
				SELECT
						D.DEPTCODE
					,	COALESCE(DL.DEPTNAME, D.DISPLAYNAME) 			AS DEPTNAME
					,	(
							SELECT
									CASE
										WHEN COUNT(DEPTCODE) > 0 THEN 1
										ELSE 0 END AS HASSUBDEPT 
							FROM
									TYJINFWLIB.ORG_DEPT
							WHERE
									PARENTDEPTCODE = D.DEPTCODE
							AND 	COMPANYCODE = P_COMPANYCODE) 		AS HASSUBDEPT
					,	D.DEPTEMAIL
					,	D.COMPANYCODE									AS COMPANYCODE
					,	COALESCE(CL.COMPANY, '')						AS COMPANYNAME
				FROM
						TYJINFWLIB.ORG_DEPT AS D 
						LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL 
							ON 	DL.DEPTCODE 	= D.DEPTCODE		
							AND DL.LANGCODE 	= P_LANGCODE
							AND DL.COMPANYCODE 	= D.COMPANYCODE
						LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL 
							ON 	CL.COMPANYCODE 	= D.COMPANYCODE
							AND CL.LANGUAGECODE = P_COMPANYLANGCODE
				WHERE
						D.PARENTDEPTCODE		= P_PARENTDEPTCODE
				AND		D.DISPLAYYN				= 'Y'
				AND		D.COMPANYCODE			= P_COMPANYCODE	
				ORDER BY DEPTORDER;
				
				IF EXISTS (SELECT * FROM TYJINFWLIB.ORG_DEPT WHERE DEPTCODE IN ('EMAAAA', 'ENAAAA', 'GLAAAA', 'KTAAAA', 'KFAAAA', 'SHAAAA', 'SNAAAA', '901000') AND DEPTCODE = P_PARENTDEPTCODE) THEN
					INSERT INTO SESSION.T VALUES('ZZZZZZZZZ0', '내부협력업체', (SELECT
																						CASE
																							WHEN COUNT(DEPTCODE) > 0 THEN 1
																							ELSE 0 END AS HASSUBDEPT 
																				FROM
																						TYJINFWLIB.ORG_DEPT
																				WHERE
																						PARENTDEPTCODE	= 'ZZZZZZZZZ0'
																				AND 	COMPANYCODE		= P_COMPANYCODE), '', P_COMPANYCODE, '');
					INSERT INTO SESSION.T VALUES('ZZZZZZZZZ1', '외부협력업체', 0, '', P_COMPANYCODE, '');
				END IF;

				L1 : BEGIN
					DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
					SELECT
							*
					FROM
							SESSION.T
					FETCH FIRST 100 ROWS ONLY
					;
					OPEN REFCURSOR2;
				END L1;
			END MAIN2;
		END IF;
	END IF;
END P1;



			--MAIN2 : BEGIN
			--	DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
			--	SELECT
			--			D.DEPTCODE
			--		,	COALESCE(DL.DEPTNAME, D.DISPLAYNAME) 			AS DEPTNAME
			--		,	(
			--				SELECT
			--						CASE
			--							WHEN COUNT(DEPTCODE) > 0 THEN 1
			--							ELSE 0 END AS HASSUBDEPT 
			--				FROM
			--						ORG_DEPT
			--				WHERE
			--						PARENTDEPTCODE = D.DEPTCODE
			--				AND 	COMPANYCODE = P_COMPANYCODE) 		AS HASSUBDEPT
			--		,	D.DEPTEMAIL
			--		,	D.COMPANYCODE									AS COMPANYCODE
			--		,	COALESCE(CL.COMPANY, '')						AS COMPANYNAME
			--	FROM
			--			TYJINFWLIB.ORG_DEPT AS D 
			--			LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL 
			--				ON 	DL.DEPTCODE 	= D.DEPTCODE		
			--				AND DL.LANGCODE 	= P_LANGCODE
			--				AND DL.COMPANYCODE 	= D.COMPANYCODE
			--			LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL 
			--				ON 	CL.COMPANYCODE 	= D.COMPANYCODE
			--				AND CL.LANGUAGECODE = P_COMPANYLANGCODE
			--	WHERE
			--			D.PARENTDEPTCODE		= P_PARENTDEPTCODE
			--	AND		D.DISPLAYYN				= 'Y'
			--	AND		D.COMPANYCODE			= P_COMPANYCODE	
			--	ORDER BY DEPTORDER;
			--	OPEN REFCURSOR2;
			--END MAIN2;