--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0002_CHTANK_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0002_CHTANK_LIST ( 
        IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_IPHANG   VARCHAR(8),
	IN P_BONSUN   VARCHAR(3),
	IN P_HWAJU    VARCHAR(3),
	IN P_HWAMUL   VARCHAR(3))  
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0002_CHTANK_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 

PREV : BEGIN  -- 값 설정 
	SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 

      LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			
			WITH TABLE1 AS
			(
			SELECT  
			SVIPHANG,
			SVBONSUN,
			SVHWAJU,
			SVHWAMUL,
			SVTANKNO,    
			SVMTQTY,     
			SVKLQTY,     
			SVCHULQTY,   
			(SVMTQTY - SVCHULQTY) AS SVJGQTY,
			SVGUMJUNG,   
			SVMOGB,      
			SVMOTA       
			FROM TYSCMLIB.UTISURVF              
			WHERE SVIPHANG =  P_IPHANG
			AND   SVBONSUN = P_BONSUN
			AND   SVHWAJU  = P_HWAJU
			AND   SVHWAMUL = P_HWAMUL
			AND   SVMTQTY - SVCHULQTY <> 0       
			), ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER (ORDER BY SVTANKNO) AS ROWNO,
				SVIPHANG,
				SVBONSUN,
				SVHWAJU,
				SVHWAMUL,
				SVTANKNO,    
				SVMTQTY,     
				SVKLQTY,     
				SVCHULQTY,   
				SVJGQTY,
				SVGUMJUNG,   
				SVMOGB,      
				SVMOTA       
			FROM TABLE1
			)
			SELECT
				ROWNO,
				SVIPHANG,
				SVBONSUN,
				SVHWAJU,
				SVHWAMUL,
				SVTANKNO,    
				SVMTQTY,     
				SVKLQTY,     
				SVCHULQTY,   
				SVJGQTY,
				SVGUMJUNG,   
				SVMOGB,      
				SVMOTA       
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC;

		OPEN REFCURSOR ;

	END LIST ; 
  
	PAGING : BEGIN  -- 페이징 					

		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
			WITH TABLE1 AS
			(
			SELECT      
			SVIPHANG,
			SVBONSUN,
			SVHWAJU,
			SVHWAMUL,
			SVTANKNO,    
			SVMTQTY,     
			SVKLQTY,     
			SVCHULQTY,   
			(SVMTQTY - SVCHULQTY) AS SVJGQTY,
			SVGUMJUNG,   
			SVMOGB,      
			SVMOTA       
			FROM TYSCMLIB.UTISURVF              
			WHERE SVIPHANG =  P_IPHANG
			AND   SVBONSUN = P_BONSUN
			AND   SVHWAJU  = P_HWAJU
			AND   SVHWAMUL = P_HWAMUL
			AND   SVMTQTY - SVCHULQTY <> 0       
			), ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER (ORDER BY SVTANKNO) AS ROWNO,
				SVIPHANG,
				SVBONSUN,
				SVHWAJU,
				SVHWAMUL,
				SVTANKNO,    
				SVMTQTY,     
				SVKLQTY,     
				SVCHULQTY,   
				SVJGQTY,
				SVGUMJUNG,   
				SVMOGB,      
				SVMOTA       
			FROM TABLE1
			)
			SELECT
				COUNT(*) AS TOTALCOUNT
			FROM ORIGINAL_DATA;

		OPEN REFCURSOR2 ;

	END PAGING ; 

END MAIN ; 
END  ;

