DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3030_JICONTNUM_UPDATE;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3030_JICONTNUM_UPDATE 
( 
	IN P_JIYYMM		NUMERIC(8, 0) ,   
	IN P_JISEQ		NUMERIC(3, 0),   
	IN P_JICONTNUM		VARCHAR(50)
)										    
    LANGUAGE SQL 
    
	P1 : BEGIN -- Ω√¿€
	
	UPDATE TYSCMLIB.UTIJISIF SET
	JICONTNUM  = P_JICONTNUM
	WHERE JIYYMM = P_JIYYMM
	AND   JISEQ = P_JISEQ
	; 
END