--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0001_JEGO_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0001_JEGO_LIST ( 
        IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_HWAJU    VARCHAR(50),
	IN P_HWAMUL   VARCHAR(3))  
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0001_JEGO_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 

PREV : BEGIN  -- 값 설정 
	SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 

      LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			
			WITH TABLE1 AS
			(
			SELECT     
			CJACTHJ,   
			CJJGHWAJU, 
			VEND.VNSANGHO AS JGVEND, 
			CJIPHANG,  
			CJBONSUN,  
			VSCODE.CDDESC1 AS VSDESC1, 
			CJHWAJU,   
			IPVEND.VNSANGHO AS IPVEND, 
			CJHWAMUL,  
			HMCODE.CDDESC1 AS HMDESC1, 
			CJBLNO,    
			CJMSNSEQ,  
			CJHSNSEQ,  
			CJCUSTIL,  
			CJCHASU,   
			CJYSHWAJU, 
			CJYDHWAJU, 
			CJYSDATE,  
			CJYDSEQ,   
			CJYSSEQ,   
			CJCUQTY,   
			CJCHQTY,   
			(          
			SELECT     
			VALUE(SUM(JISTMTQTY),0)     
			FROM  TYSCMLIB.UTIORDERF    
			WHERE JIIPHANG  = CJIPHANG  
			AND   JIBONSUN  = CJBONSUN  
			AND   JIHWAJU   = CJHWAJU   
			AND   JIHWAMUL  = CJHWAMUL  
			AND   JIBLNO    = CJBLNO    
			AND   JIMSNSEQ  = CJMSNSEQ  
			AND   JIHSNSEQ  = CJHSNSEQ  
			AND   JICUSTIL  = CJCUSTIL  
			AND   JICHASU   = CJCHASU   
			AND   JIACTHJ   = CJACTHJ   
			AND   JIJGHWAJU = CJJGHWAJU 
			AND   JIYSHWAJU = CJYSHWAJU 
			AND   JIYDHWAJU = CJYDHWAJU 
			AND   JIYSDATE  = CJYSDATE  
			AND   JIYDSEQ   = CJYDSEQ   
			AND   JIYSSEQ   = CJYSSEQ   
			AND   JISINO1   = 0         
			) AS JIQTY,                 
			CJJEQTY                     
			FROM TYSCMLIB.UTICUHJF AS CUHJ              
			LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS IPVEND 
			ON    CUHJ.CJHWAJU   = IPVEND.VNCODE        
			LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND   
			ON    CUHJ.CJJGHWAJU = VEND.VNCODE          
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE 
			ON              'HM' = HMCODE.CDINDEX       
			AND    CUHJ.CJHWAMUL = HMCODE.CDCODE        
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS VSCODE 
			ON              'VS' = VSCODE.CDINDEX       
			AND    CUHJ.CJBONSUN = VSCODE.CDCODE        
			WHERE CJJEQTY <> 0                          
			AND   CJJGHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ) 
			AND   CJHWAMUL LIKE P_HWAMUL||'%'
			ORDER BY CJHWAMUL, CJIPHANG, CJBONSUN, CJCUSTIL, CJCHASU 
			), ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER(ORDER BY CJHWAMUL, CJIPHANG, CJBONSUN, CJCUSTIL, CJCHASU) AS ROWNO,
				CJACTHJ,   
				CJJGHWAJU, 
				JGVEND, 
				CJIPHANG,  
				CJBONSUN,  
				VSDESC1, 
				CJHWAJU,   
				IPVEND, 
				CJHWAMUL,  
				HMDESC1, 
				CJBLNO,    
				CJMSNSEQ,  
				CJHSNSEQ,  
				CJCUSTIL,  
				CJCHASU,   
				CJYSHWAJU, 
				CJYDHWAJU, 
				CJYSDATE,  
				CJYDSEQ,   
				CJYSSEQ,   
				CJCUQTY,   
				CJCHQTY,
				JIQTY,                 
				CJJEQTY
			FROM TABLE1   
			)
			SELECT
				ROWNO,
				CJACTHJ,   
				CJJGHWAJU, 
				JGVEND, 
				CJIPHANG,  
				CJBONSUN,  
				VSDESC1, 
				CJHWAJU,   
				IPVEND, 
				CJHWAMUL,  
				HMDESC1, 
				CJBLNO,    
				CJMSNSEQ,  
				CJHSNSEQ,  
				CJCUSTIL,  
				CJCHASU,   
				CJYSHWAJU, 
				CJYDHWAJU, 
				CJYSDATE,  
				CJYDSEQ,   
				CJYSSEQ,   
				TRIM(TO_CHAR(CJCUQTY, '9,999,990.000')) AS CJCUQTY,   
				TRIM(TO_CHAR(CJCHQTY, '9,999,990.000')) AS CJCHQTY,
				TRIM(TO_CHAR(JIQTY, '9,999,990.000')) AS JIQTY,                 
				TRIM(TO_CHAR(CJJEQTY, '9,999,990.000')) AS CJJEQTY
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC;

		OPEN REFCURSOR ;

	END LIST ; 
  
	PAGING : BEGIN  -- 페이징 					

		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
			WITH TABLE1 AS
			(
			SELECT     
			CJACTHJ,   
			CJJGHWAJU, 
			VEND.VNSANGHO AS JGVEND, 
			CJIPHANG,  
			CJBONSUN,  
			VSCODE.CDDESC1 AS VSDESC1, 
			CJHWAJU,   
			IPVEND.VNSANGHO AS IPVEND, 
			CJHWAMUL,  
			HMCODE.CDDESC1 AS HMDESC1, 
			CJBLNO,    
			CJMSNSEQ,  
			CJHSNSEQ,  
			CJCUSTIL,  
			CJCHASU,   
			CJYSHWAJU, 
			CJYDHWAJU, 
			CJYSDATE,  
			CJYDSEQ,   
			CJYSSEQ,   
			CJCUQTY,   
			CJCHQTY,   
			(          
			SELECT     
			VALUE(SUM(JISTMTQTY),0)     
			FROM  TYSCMLIB.UTIORDERF    
			WHERE JIIPHANG  = CJIPHANG  
			AND   JIBONSUN  = CJBONSUN  
			AND   JIHWAJU   = CJHWAJU   
			AND   JIHWAMUL  = CJHWAMUL  
			AND   JIBLNO    = CJBLNO    
			AND   JIMSNSEQ  = CJMSNSEQ  
			AND   JIHSNSEQ  = CJHSNSEQ  
			AND   JICUSTIL  = CJCUSTIL  
			AND   JICHASU   = CJCHASU   
			AND   JIACTHJ   = CJACTHJ   
			AND   JIJGHWAJU = CJJGHWAJU 
			AND   JIYSHWAJU = CJYSHWAJU 
			AND   JIYDHWAJU = CJYDHWAJU 
			AND   JIYSDATE  = CJYSDATE  
			AND   JIYDSEQ   = CJYDSEQ   
			AND   JIYSSEQ   = CJYSSEQ   
			AND   JISINO1   = 0         
			) AS JIQTY,                 
			CJJEQTY                     
			FROM TYSCMLIB.UTICUHJF AS CUHJ              
			LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS IPVEND 
			ON    CUHJ.CJHWAJU   = IPVEND.VNCODE        
			LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND   
			ON    CUHJ.CJJGHWAJU = VEND.VNCODE          
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE 
			ON              'HM' = HMCODE.CDINDEX       
			AND    CUHJ.CJHWAMUL = HMCODE.CDCODE        
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS VSCODE 
			ON              'VS' = VSCODE.CDINDEX       
			AND    CUHJ.CJBONSUN = VSCODE.CDCODE        
			WHERE CJJEQTY <> 0                          
			AND   CJJGHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ) 
			AND   CJHWAMUL LIKE P_HWAMUL||'%'
			ORDER BY CJHWAMUL, CJIPHANG, CJBONSUN, CJCUSTIL, CJCHASU 
			), ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER(ORDER BY CJHWAMUL, CJIPHANG, CJBONSUN, CJCUSTIL, CJCHASU) AS ROWNO,
				CJACTHJ,   
				CJJGHWAJU, 
				JGVEND, 
				CJIPHANG,  
				CJBONSUN,  
				VSDESC1, 
				CJHWAJU,   
				IPVEND, 
				CJHWAMUL,  
				HMDESC1, 
				CJBLNO,    
				CJMSNSEQ,  
				CJHSNSEQ,  
				CJCUSTIL,  
				CJCHASU,   
				CJYSHWAJU, 
				CJYDHWAJU, 
				CJYSDATE,  
				CJYDSEQ,   
				CJYSSEQ,   
				CJCUQTY,   
				CJCHQTY,
				JIQTY,                 
				CJJEQTY
			FROM TABLE1   
			)
			SELECT
				COUNT(*) AS TOTALCOUNT
			FROM ORIGINAL_DATA;

		OPEN REFCURSOR2 ;

	END PAGING ; 

END MAIN ; 
END  ;
