--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0004_CUTANKNO_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0004_CUTANKNO_LIST ( 
	IN P_HWAJU    VARCHAR(50))  
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0004_CUTANKNO_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 

  
MAIN : BEGIN  -- 실행부 

      LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			
			SELECT         
			CUHWAJU,       
			VEND.VNSANGHO, 
			CUHWAMUL,      
			HMCODE.CDDESC1 AS HMDESC1, 
			CUTANKNO,      
			CUDESC         
			FROM TYSCMLIB.UTICUIPTKF AS IPTK            
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE 
			ON             'HM' = HMCODE.CDINDEX        
			AND   IPTK.CUHWAMUL = HMCODE.CDCODE         
			LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND   
			ON    IPTK.CUHWAJU  = VEND.VNCODE           
			WHERE CUHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ) 
			AND   CUNUM <> '99'                         
			ORDER BY CUNUM                                     ;

		OPEN REFCURSOR ;

	END LIST ; 

END MAIN ; 
END  ;



    