DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3021_UTIIPORF_UPDATE;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3021_UTIIPORF_UPDATE 
( 
	IN P_GUBN		VARCHAR(1),
	IN P_IOIPDATE		NUMERIC(8, 0) ,   
	IN P_IOTKNO		NUMERIC(3, 0),   
	IN P_IOHWAJU		VARCHAR(3),  
	IN P_IOHWAMUL		VARCHAR(3),  
	IN P_IOTANKNO		VARCHAR(4),  
	IN P_IOIPQTY		NUMERIC(9, 3),  
	IN P_IOWKTYPE		VARCHAR(2),  
	IN P_IOCARNO		VARCHAR(20),  
	IN P_IOCONTAIN		VARCHAR(50),                        
	IN P_IOSEALNUM		VARCHAR(50),  
	IN P_IOTMGUBN		VARCHAR(1),   
	IN P_IOIPTIME		NUMERIC(4, 0),       
	IN P_IODESC		VARCHAR(300),  	
	IN P_IOHISAB		VARCHAR(6),    
	OUT RET_MSG		VARCHAR(100)		
)										    
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSI3021_UTIIPORF_UPDATE
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
P1 : BEGIN -- Ω√¿€

    
	IF P_GUBN = 'A' THEN

		INSERT INTO TYSCMLIB.UTIIPORF( 
		IOIPDATE,  
		IOTKNO,    
		IOHWAJU,   
		IOHWAMUL,  
		IOTANKNO,  
		IOIPQTY,   
		IOWKTYPE,  
		IOCARNO,   
		IOCONTAIN, 
		IOSEALNUM, 
		IOTMGUBN,  
		IOIPTIME,  
		IODESC,    
		IOHIGB,    
		IOHIDAT,   
		IOHITIM,   
		IOHISAB    
		)          
		VALUES (   
		P_IOIPDATE ,  
		P_IOTKNO ,  
		P_IOHWAJU,  
		P_IOHWAMUL,  
		P_IOTANKNO,  
		P_IOIPQTY ,  
		P_IOWKTYPE,  
		P_IOCARNO,  
		P_IOCONTAIN,  
		P_IOSEALNUM,  
		P_IOTMGUBN,  
		P_IOIPTIME ,  
		P_IODESC,  
		'A',  
		REPLACE(CHAR(CURRENT_DATE),'-',''),   
		REPLACE(CHAR(CURRENT_TIME),'.',''),
		P_IOHISAB    
		)  ;

	END IF;

	IF P_GUBN = 'C' THEN

		UPDATE TYSCMLIB.UTIIPORF SET 
		IOHWAJU   = P_IOHWAJU,  
		IOHWAMUL  = P_IOHWAMUL,  
		IOTANKNO  = P_IOTANKNO,  
		IOIPQTY   = P_IOIPQTY,  
		IOWKTYPE  = P_IOWKTYPE,  
		IOCARNO   = P_IOCARNO,  
		IOCONTAIN = P_IOCONTAIN,  
		IOSEALNUM = P_IOSEALNUM,  
		IOTMGUBN  = P_IOTMGUBN,  
		IOIPTIME  = P_IOIPTIME,  
		IODESC    = P_IODESC,  
		IOHISAB   = P_IOHISAB,  
		IOHIGB    = 'C',
		IOHIDAT   = REPLACE(CHAR(CURRENT_DATE),'-',''),  
		IOHITIM   = REPLACE(CHAR(CURRENT_TIME),'.','')
		WHERE IOIPDATE  = P_IOIPDATE 
		AND   IOTKNO    = P_IOTKNO ;

	END IF;

	IF P_GUBN = 'D' THEN

		DELETE FROM TYSCMLIB.UTIIPORF
		WHERE IOIPDATE  = P_IOIPDATE 
		AND   IOTKNO    = P_IOTKNO ;

	END IF;

	SET RET_MSG = 'SUCCESS!' ; 
END