--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI1120_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI1120_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE    VARCHAR(8),
	IN P_EDATE    VARCHAR(8),
	IN P_HWAJU    VARCHAR(50),
	IN P_HWAMUL   VARCHAR(3),
	IN P_WKTYPE   VARCHAR(20),
	IN P_CHHJ     VARCHAR(3),
	IN P_CHDNST   VARCHAR(3),
	IN P_JIGSPINO VARCHAR(40)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSI1120_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 

      LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			WITH TABLE1 AS
			(
				SELECT
				(CASE WHEN CHWKTYPE = '01' THEN 'TANK LORRY'
				      WHEN CHWKTYPE = '02' THEN 'ISO TANK'
				      WHEN CHWKTYPE = '03' THEN 'FLEXI BAG' END) AS CHWKTYPE,
				CHCHULIL,
				CHBIJUNG,
				CHHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				CHCHTANK,
				CHCONTNUM,
				CHSILNUM,
				CHDNST,
				GSCODE.CDDESC1 AS GSDESC1,
				CHCARNO,
				CHSOSOK,
				SKCODE.CDDESC1 AS SKDESC1,
				SUBSTR(DIGITS(CHCHSTR),1,2)||':'||SUBSTR(DIGITS(CHCHSTR),3,2) AS CHCHSTR,
				SUBSTR(DIGITS(CHCHEND),1,2)||':'||SUBSTR(DIGITS(CHCHEND),3,2) AS CHCHEND,
				CHEMPTY,
				CHTOTAL,
				CHMTQTY,
				ROUND(((CHMTQTY / CHBIJUNG) * 1000),0) AS LTQTY,
				CHCHHJ,
				DCCODE.CDDESC1 AS DCDESC1,	
				CHACTHJ,
				VEND.VNSANGHO,
				'출고' AS GUBUN,
				VALUE(JISI.JICARNO1,'') AS JICARNO1,
				    JISI.JIGSPINO
				FROM TYSCMLIB.UTICHULF AS CHUL
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
				ON             'HM' = HMCODE.CDINDEX
				AND   CHUL.CHHWAMUL = HMCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS DCCODE
				ON             'DC' = DCCODE.CDINDEX
				AND   CHUL.CHCHHJ   = DCCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS GSCODE
				ON             'GS' = GSCODE.CDINDEX
				AND   CHUL.CHDNST   = GSCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS SKCODE
				ON             'SK' = SKCODE.CDINDEX
				AND   CHUL.CHSOSOK  = SKCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND
				ON    CHUL.CHACTHJ  = VEND.VNCODE
				LEFT OUTER JOIN TYSCMLIB.UTIJISIF AS JISI
				ON   JISI.JIYYMM || DIGITS(JISI.JISEQ) = CHJISINUM
				WHERE CHCHULIL BETWEEN P_SDATE AND P_EDATE
				AND   CHHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(CHHWAMUL) END)
					=     (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(P_HWAMUL) END)
				AND   CHWKTYPE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_WKTYPE AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(CHCHHJ) END)
					=     (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(P_CHHJ) END)
				AND  (CASE WHEN P_CHDNST = '' THEN '' ELSE TRIM(CHDNST) END)
					=     (CASE WHEN P_CHDNST = '' THEN '' ELSE TRIM(P_CHDNST) END)
				AND  (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(JIGSPINO) END)
					=     (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(P_JIGSPINO) END)

				UNION ALL

				SELECT
				(CASE WHEN CJWKTYPE = '01' THEN 'TANK LORRY'
				      WHEN CJWKTYPE = '02' THEN 'ISO TANK'
				      WHEN CJWKTYPE = '03' THEN 'FLEXI BAG' END) AS CHWKTYPE,
				CJCHULIL AS CHCHULIL,
				TNBIJUNG AS CHBIJUNG,	
				CJHWAMUL AS CHHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				CJTANKNO1 AS CHCHTANK,
				CJCONTAIN AS CHCONTNUM,
				CJSEALNUM AS CHSILNUM,
				'' AS CHDNST,
				'' AS GSDESC1,
				CJCARNO AS CHCARNO,
				CJSOSOK AS CHSOSOK,
				SKCODE.CDDESC1 AS SKDESC1,
				SUBSTR(DIGITS(CJIPTIME),1,2)||':'||SUBSTR(DIGITS(CJIPTIME),3,2) AS CHCHSTR,
				SUBSTR(DIGITS(CJCHTIME),1,2)||':'||SUBSTR(DIGITS(CJCHTIME),3,2) AS CHCHEND,
				CJEMPTY AS CHEMPTY,
				CJTOTAL AS CHTOTAL,
				CJMTQTY AS CHMTQTY,
				ROUND(((CJMTQTY / TNBIJUNG ) * 1000),0) AS LTQTY,
				CJCHHJ AS CHCHHJ,
				DCCODE.CDDESC1 AS DCDESC1,
				CJACTHJ AS CHACTHJ,
				VEND.VNSANGHO,
				'I계근' AS GUBUN,
				VALUE(JISI.JICARNO1,'') AS JICARNO1,
				    JISI.JIGSPINO
				FROM TYSCMLIB.UTICHJIF AS CHJI
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
				ON                    'HM' = HMCODE.CDINDEX
				AND   CHJI.CJHWAMUL = HMCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS DCCODE
				ON                    'DC' = DCCODE.CDINDEX
				AND   CHJI.CJCHHJ = DCCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS SKCODE
				ON             'SK' = SKCODE.CDINDEX
				AND   CHJI.CJSOSOK  = SKCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND
				ON    CHJI.CJACTHJ  = VEND.VNCODE
				LEFT OUTER JOIN TYSCMLIB.UTITANKF AS TANK
				ON    TRIM(CHJI.CJTANKNO1) = TRIM(TANK.TNTANKNO)
				LEFT OUTER JOIN TYSCMLIB.UTIJISIF AS JISI
				ON   JISI.JIYYMM || DIGITS(JISI.JISEQ) = CJJISINO1
				WHERE CJGUBUN  = 'C'
				AND   CJCHULIL BETWEEN P_SDATE AND P_EDATE
				AND   CJACTHJ IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(CJHWAMUL) END)
					=     (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(P_HWAMUL) END)
				AND   CJWKTYPE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_WKTYPE AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(CJCHHJ) END)
					=     (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(P_CHHJ) END)
				AND  (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(JIGSPINO) END)
					=     (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(P_JIGSPINO) END)

			), ORIGINAL_DATA AS (
			SELECT
			ROW_NUMBER() OVER(ORDER BY CHCHULIL, HMDESC1, GSDESC1, CHCHTANK, CHCHSTR, CHCHEND) AS ROWNO,
			CHCHULIL,
			CHHWAMUL,
			HMDESC1,
			CHCHTANK,
			CHBIJUNG,
			CHCONTNUM,
			'''' || CHSILNUM AS CHSILNUM,
			CHCARNO,
			CHSOSOK,
			SKDESC1,
			CHCHSTR,
			CHCHEND,
			CHEMPTY,
			CHTOTAL,
			CHMTQTY,
			LTQTY,
			CHACTHJ,
			VNSANGHO,
			CHCHHJ,
			DCDESC1,
			CHDNST,
			GSDESC1,
			CHWKTYPE,
			GUBUN,
			JICARNO1,
			JIGSPINO
			FROM TABLE1
			)
			SELECT
			ROWNO,
			(SUBSTR(CHAR(CHCHULIL),1,4)||'/'||SUBSTR(CHAR(CHCHULIL),5,2)||'/'||SUBSTR(CHAR(CHCHULIL),7,2)) AS CHCHULIL,
			CHHWAMUL,
			HMDESC1,
			CHCHTANK,
			TRIM(TO_CHAR(CHBIJUNG, '9,999,990.0000')) AS CHBIJUNG,
			CHCONTNUM,
			CHSILNUM,
			CHCARNO,
			CHSOSOK,
			SKDESC1,
			CHCHSTR,
			CHCHEND,
			TRIM(TO_CHAR(CHEMPTY, '9,999,990.000')) AS CHEMPTY,
			TRIM(TO_CHAR(CHTOTAL, '9,999,990.000')) AS CHTOTAL,
			TRIM(TO_CHAR(CHMTQTY, '9,999,990.000')) AS CHMTQTY,
			TRIM(TO_CHAR(LTQTY, '9,999,990')) AS LTQTY,
			CHACTHJ,
			VNSANGHO,
			CHCHHJ,
			DCDESC1,
			CHDNST,
			GSDESC1,
			CHWKTYPE,
			GUBUN,
			JICARNO1,
			JIGSPINO
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC ;

		OPEN REFCURSOR ;

	END LIST ; 
  
	PAGING : BEGIN  -- 페이징 					

			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
			   WITH TABLE1 AS
			(
				SELECT
				(CASE WHEN CHWKTYPE = '01' THEN 'TANK LORRY'
				      WHEN CHWKTYPE = '02' THEN 'ISO TANK'
				      WHEN CHWKTYPE = '03' THEN 'FLEXI BAG' END) AS CHWKTYPE,
				CHCHULIL,
				CHBIJUNG,
				CHHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				CHCHTANK,
				CHCONTNUM,
				CHSILNUM,
				CHDNST,
				GSCODE.CDDESC1 AS GSDESC1,
				CHCARNO,
				CHSOSOK,
				SKCODE.CDDESC1 AS SKDESC1,
				SUBSTR(DIGITS(CHCHSTR),1,2)||':'||SUBSTR(DIGITS(CHCHSTR),3,2) AS CHCHSTR,
				SUBSTR(DIGITS(CHCHEND),1,2)||':'||SUBSTR(DIGITS(CHCHEND),3,2) AS CHCHEND,
				CHEMPTY,
				CHTOTAL,
				CHMTQTY,
				ROUND(((CHMTQTY / CHBIJUNG) * 1000),0) AS LTQTY,
				CHCHHJ,
				DCCODE.CDDESC1 AS DCDESC1,	
				CHACTHJ,
				VEND.VNSANGHO,
				'출고' AS GUBUN,
				VALUE(JISI.JICARNO1,'') AS JICARNO1,
				    JISI.JIGSPINO
				FROM TYSCMLIB.UTICHULF AS CHUL
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
				ON             'HM' = HMCODE.CDINDEX
				AND   CHUL.CHHWAMUL = HMCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS DCCODE
				ON             'DC' = DCCODE.CDINDEX
				AND   CHUL.CHCHHJ   = DCCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS GSCODE
				ON             'GS' = GSCODE.CDINDEX
				AND   CHUL.CHDNST   = GSCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS SKCODE
				ON             'SK' = SKCODE.CDINDEX
				AND   CHUL.CHSOSOK  = SKCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND
				ON    CHUL.CHACTHJ  = VEND.VNCODE
				LEFT OUTER JOIN TYSCMLIB.UTIJISIF AS JISI
				ON   JISI.JIYYMM || DIGITS(JISI.JISEQ) = CHJISINUM
				WHERE CHCHULIL BETWEEN P_SDATE AND P_EDATE
				AND   CHHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(CHHWAMUL) END)
					=     (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(P_HWAMUL) END)
				AND   CHWKTYPE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_WKTYPE AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(CHCHHJ) END)
					=     (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(P_CHHJ) END)
				AND  (CASE WHEN P_CHDNST = '' THEN '' ELSE TRIM(CHDNST) END)
					=     (CASE WHEN P_CHDNST = '' THEN '' ELSE TRIM(P_CHDNST) END)
				AND  (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(JIGSPINO) END)
					=     (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(P_JIGSPINO) END)

				UNION ALL

				SELECT
				(CASE WHEN CJWKTYPE = '01' THEN 'TANK LORRY'
				      WHEN CJWKTYPE = '02' THEN 'ISO TANK'
				      WHEN CJWKTYPE = '03' THEN 'FLEXI BAG' END) AS CHWKTYPE,
				CJCHULIL AS CHCHULIL,
				TNBIJUNG AS CHBIJUNG,	
				CJHWAMUL AS CHHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				CJTANKNO1 AS CHCHTANK,
				CJCONTAIN AS CHCONTNUM,
				CJSEALNUM AS CHSILNUM,
				'' AS CHDNST,
				'' AS GSDESC1,
				CJCARNO AS CHCARNO,
				CJSOSOK AS CHSOSOK,
				SKCODE.CDDESC1 AS SKDESC1,
				SUBSTR(DIGITS(CJIPTIME),1,2)||':'||SUBSTR(DIGITS(CJIPTIME),3,2) AS CHCHSTR,
				SUBSTR(DIGITS(CJCHTIME),1,2)||':'||SUBSTR(DIGITS(CJCHTIME),3,2) AS CHCHEND,
				CJEMPTY AS CHEMPTY,
				CJTOTAL AS CHTOTAL,
				CJMTQTY AS CHMTQTY,
				ROUND(((CJMTQTY / TNBIJUNG ) * 1000),0) AS LTQTY,
				CJCHHJ AS CHCHHJ,
				DCCODE.CDDESC1 AS DCDESC1,
				CJACTHJ AS CHACTHJ,
				VEND.VNSANGHO,
				'I계근' AS GUBUN,
				VALUE(JISI.JICARNO1,'') AS JICARNO1,
				    JISI.JIGSPINO
				FROM TYSCMLIB.UTICHJIF AS CHJI
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
				ON                    'HM' = HMCODE.CDINDEX
				AND   CHJI.CJHWAMUL = HMCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS DCCODE
				ON                    'DC' = DCCODE.CDINDEX
				AND   CHJI.CJCHHJ = DCCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS SKCODE
				ON             'SK' = SKCODE.CDINDEX
				AND   CHJI.CJSOSOK  = SKCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND
				ON    CHJI.CJACTHJ  = VEND.VNCODE
				LEFT OUTER JOIN TYSCMLIB.UTITANKF AS TANK
				ON    TRIM(CHJI.CJTANKNO1) = TRIM(TANK.TNTANKNO)
				LEFT OUTER JOIN TYSCMLIB.UTIJISIF AS JISI
				ON   JISI.JIYYMM || DIGITS(JISI.JISEQ) = CJJISINO1
				WHERE CJGUBUN  = 'C'
				AND   CJCHULIL BETWEEN P_SDATE AND P_EDATE
				AND   CJACTHJ IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(CJHWAMUL) END)
					=     (CASE WHEN P_HWAMUL = '' THEN '' ELSE TRIM(P_HWAMUL) END)
				AND   CJWKTYPE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_WKTYPE AS VARCHAR(100)), ',')) AS InTable )
				AND  (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(CJCHHJ) END)
					=     (CASE WHEN P_CHHJ = '' THEN '' ELSE TRIM(P_CHHJ) END)
				AND  (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(JIGSPINO) END)
					=     (CASE WHEN P_JIGSPINO = '' THEN '' ELSE TRIM(P_JIGSPINO) END)

			), ORIGINAL_DATA AS (
			SELECT
			ROW_NUMBER() OVER(ORDER BY CHCHULIL, HMDESC1, GSDESC1, CHCHTANK, CHCHSTR, CHCHEND) AS ROWNO,
			CHCHULIL,
			CHHWAMUL,
			HMDESC1,
			CHCHTANK,
			CHBIJUNG,
			CHCONTNUM,
			'''' || CHSILNUM AS CHSILNUM,
			CHCARNO,
			CHSOSOK,
			SKDESC1,
			CHCHSTR,
			CHCHEND,
			CHEMPTY,
			CHTOTAL,
			CHMTQTY,
			LTQTY,
			CHACTHJ,
			VNSANGHO,
			CHCHHJ,
			DCDESC1,
			CHDNST,
			GSDESC1,
			CHWKTYPE,
			GUBUN,
			JICARNO1,
			JIGSPINO
			FROM TABLE1
			)					
				SELECT
					COUNT(*) AS TOTALCOUNT
				FROM ORIGINAL_DATA;

			OPEN REFCURSOR2 ;

	END PAGING ; 

END MAIN ; 
END  ;
