DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3030_CHCHULF_CHECK ; 
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3030_CHCHULF_CHECK ( 
	IN P_JIYYMM VARCHAR(8),
	IN P_JISEQ NUMERIC(3,0)) 
DYNAMIC RESULT SETS 1 
LANGUAGE SQL 
	
P1 : BEGIN  -- 시작 

MAIN : BEGIN  -- 실행부 
	
	LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			CHCONTNUM
			FROM TYSCMLIB.UTICHULF
			WHERE DIGITS(CHJISINUM) = P_JIYYMM || DIGITS(P_JISEQ)
			;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 

