   

--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3011_GET_JISEQ;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3011_GET_JISEQ ( 
	IN  P_JCYYMM NUMERIC(8, 0)) 
	DYNAMIC RESULT SETS 1
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSI3011_GET_JISEQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE V_JISEQ	NUMERIC(3, 0);

  
	MAIN : BEGIN  -- 실행부 

		SELECT                            
		COALESCE(MAX(JCSEQ)+1,1) AS JISEQ INTO V_JISEQ
		FROM TYSCMLIB.UTIORCNF           
		WHERE JCYYMM = P_JCYYMM;

		IF V_JISEQ = 1 THEN

			INSERT INTO TYSCMLIB.UTIORCNF( 
			JCYYMM,    
			JCSEQ)     
			VALUES(    
			P_JCYYMM,
			V_JISEQ) ;

		ELSE

			UPDATE TYSCMLIB.UTIORCNF SET    
			JCSEQ        = V_JISEQ
			WHERE JCYYMM = P_JCYYMM;

		END IF;


		LIST1 : BEGIN

			DECLARE REFCURSOR CURSOR WITH RETURN FOR
				
				SELECT
				V_JISEQ AS JISEQ
				FROM SYSIBM.SYSDUMMY1;

			OPEN REFCURSOR ;

		END LIST1 ; 

	END MAIN ; 

END  ;






 

