--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0001_HWAMUL_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0001_HWAMUL_LIST ( 
        IN P_HWAJU    VARCHAR(50)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0001_HWAMUL_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 

  
MAIN : BEGIN  -- 실행부 

      LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			
			SELECT   
			DISTINCT 
			CDCODE,  
			CDDESC1  
			FROM TYSCMLIB.UTICODEF AS HMCODE 
			LEFT OUTER JOIN TYSCMLIB.UTICUHJF AS CUHJ  
			ON             'HM' = HMCODE.CDINDEX       
			AND   CUHJ.CJHWAMUL = HMCODE.CDCODE        
			WHERE CDINDEX = 'HM'                       
			AND   CJJGHWAJU  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(''|| P_HWAJU ||'' AS VARCHAR(100)), ',')) AS InTable ) 
			AND   CJJEQTY > 0                          
			ORDER BY CDDESC1     ;

		OPEN REFCURSOR ;

	END LIST ; 
  
	PAGING : BEGIN  -- 페이징 					

		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
			WITH TABLE1 AS (
			SELECT   
			DISTINCT 
			CDCODE,  
			CDDESC1  
			FROM TYSCMLIB.UTICODEF AS HMCODE 
			LEFT OUTER JOIN TYSCMLIB.UTICUHJF AS CUHJ  
			ON             'HM' = HMCODE.CDINDEX       
			AND   CUHJ.CJHWAMUL = HMCODE.CDCODE        
			WHERE CDINDEX = 'HM'                       
			AND   CJJGHWAJU  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(''|| P_HWAJU ||'' AS VARCHAR(100)), ',')) AS InTable ) 
			AND   CJJEQTY > 0                          
			ORDER BY CDDESC1     
			)
			SELECT
				COUNT(*) AS TOTALCOUNT
			FROM TABLE1;

		OPEN REFCURSOR2 ;

	END PAGING ; 

END MAIN ; 
END  ;
