DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0006_UTATRUKF_INSERT;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0006_UTATRUKF_INSERT 
( 
	IN P_TRNUMNO1		VARCHAR(12),
	IN P_TRNUMNO2		VARCHAR(4),
	IN P_TRUNSONG		VARCHAR(3),
	IN P_TRHYUNGT		VARCHAR(3),
	IN P_TRUNNAME		VARCHAR(10),
	IN P_TRGITEL		VARCHAR(20),
	IN P_TRJUNGRY		NUMERIC(6, 3),
	OUT RET_MSG		VARCHAR(100)		
)										    
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0006_UTATRUKF_INSERT
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
P1 : BEGIN -- Ω√¿€

	INSERT INTO TYSCMLIB.UTATRUKF( 
	TRNUMNO1,
	TRNUMNO2,
	TRUNSONG,  
	TRHYUNGT,  
	TRUNNAME,  
	TRGITEL,   
	TRJUNGRY)  
	VALUES(    
	P_TRNUMNO1,  
	P_TRNUMNO2,  
	P_TRUNSONG,  
	P_TRHYUNGT,  
	P_TRUNNAME,  
	P_TRGITEL,  
	P_TRJUNGRY)   ;

	SET RET_MSG = 'SUCCESS!' ; 
END