--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3031_LIST ; 
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3031_LIST ( 
	IN P_CHCHULIL NUMERIC(8, 0),
	IN P_JIGSPINO VARCHAR(40)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			WITH MAST AS
			(
				SELECT
				(CASE WHEN CHWKTYPE = '01' THEN 'TANK LORRY'
				      WHEN CHWKTYPE = '02' THEN 'ISO TANK'
				      WHEN CHWKTYPE = '03' THEN 'FLEXI BAG' END) AS CHWKTYPE,
				CHCHULIL,
				CHBIJUNG,
				CHHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				CHCHTANK,
				CHCONTNUM,
				CHSILNUM,
				CHDNST,
				GSCODE.CDDESC1 AS GSDESC1,
				CHCARNO,
				CHSOSOK,
				SKCODE.CDDESC1 AS SKDESC1,
				SUBSTR(DIGITS(CHCHSTR),1,2)||':'||SUBSTR(DIGITS(CHCHSTR),3,2) AS CHCHSTR,
				SUBSTR(DIGITS(CHCHEND),1,2)||':'||SUBSTR(DIGITS(CHCHEND),3,2) AS CHCHEND,
				CHEMPTY,
				CHTOTAL,
				CHMTQTY,
				ROUND(((CHMTQTY / CHBIJUNG) * 1000),0) AS LTQTY,
				CHCHHJ,
				DCCODE.CDDESC1 AS DCDESC1,	
				CHACTHJ,
				VEND.VNSANGHO,
				'출고' AS GUBUN,
				VALUE(JISI.JICARNO1,'') AS JICARNO1,
				    JISI.JIGSPINO
				FROM TYSCMLIB.UTICHULF AS CHUL
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
				ON             'HM' = HMCODE.CDINDEX
				AND   CHUL.CHHWAMUL = HMCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS DCCODE
				ON             'DC' = DCCODE.CDINDEX
				AND   CHUL.CHCHHJ   = DCCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS GSCODE
				ON             'GS' = GSCODE.CDINDEX
				AND   CHUL.CHDNST   = GSCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS SKCODE
				ON             'SK' = SKCODE.CDINDEX
				AND   CHUL.CHSOSOK  = SKCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND
				ON    CHUL.CHACTHJ  = VEND.VNCODE
				LEFT OUTER JOIN TYSCMLIB.UTIJISIF AS JISI
				ON   JISI.JIYYMM || DIGITS(JISI.JISEQ) = CHJISINUM
				WHERE CHCHULIL = P_CHCHULIL
				AND   JIGSPINO = P_JIGSPINO
				AND   JIGSPINO <> ''

				UNION ALL

				SELECT
				(CASE WHEN CJWKTYPE = '01' THEN 'TANK LORRY'
				      WHEN CJWKTYPE = '02' THEN 'ISO TANK'
				      WHEN CJWKTYPE = '03' THEN 'FLEXI BAG' END) AS CHWKTYPE,
				CJCHULIL AS CHCHULIL,
				TNBIJUNG AS CHBIJUNG,	
				CJHWAMUL AS CHHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				CJTANKNO1 AS CHCHTANK,
				CJCONTAIN AS CHCONTNUM,
				CJSEALNUM AS CHSILNUM,
				'' AS CHDNST,
				'' AS GSDESC1,
				CJCARNO AS CHCARNO,
				CJSOSOK AS CHSOSOK,
				SKCODE.CDDESC1 AS SKDESC1,
				SUBSTR(DIGITS(CJIPTIME),1,2)||':'||SUBSTR(DIGITS(CJIPTIME),3,2) AS CHCHSTR,
				SUBSTR(DIGITS(CJCHTIME),1,2)||':'||SUBSTR(DIGITS(CJCHTIME),3,2) AS CHCHEND,
				CJEMPTY AS CHEMPTY,
				CJTOTAL AS CHTOTAL,
				CJMTQTY AS CHMTQTY,
				ROUND(((CJMTQTY / TNBIJUNG ) * 1000),0) AS LTQTY,
				CJCHHJ AS CHCHHJ,
				DCCODE.CDDESC1 AS DCDESC1,
				CJACTHJ AS CHACTHJ,
				VEND.VNSANGHO,
				'I계근' AS GUBUN,
				VALUE(JISI.JICARNO1,'') AS JICARNO1,
				    JISI.JIGSPINO
				FROM TYSCMLIB.UTICHJIF AS CHJI
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
				ON                    'HM' = HMCODE.CDINDEX
				AND   CHJI.CJHWAMUL = HMCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS DCCODE
				ON                    'DC' = DCCODE.CDINDEX
				AND   CHJI.CJCHHJ = DCCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS SKCODE
				ON             'SK' = SKCODE.CDINDEX
				AND   CHJI.CJSOSOK  = SKCODE.CDCODE
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND
				ON    CHJI.CJACTHJ  = VEND.VNCODE
				LEFT OUTER JOIN TYSCMLIB.UTITANKF AS TANK
				ON    TRIM(CHJI.CJTANKNO1) = TRIM(TANK.TNTANKNO)
				LEFT OUTER JOIN TYSCMLIB.UTIJISIF AS JISI
				ON   JISI.JIYYMM || DIGITS(JISI.JISEQ) = CJJISINO1
				WHERE CJGUBUN  = 'C'
				AND   CJCHULIL = P_CHCHULIL
				AND   JIGSPINO = P_JIGSPINO
				AND   JIGSPINO <> ''
			)

			SELECT
			CHCHULIL,
			CHHWAMUL,
			HMDESC1,
			CHCHTANK,
			TRIM(TO_CHAR(CHBIJUNG,'9,999,990.0000')) AS CHBIJUNG,
			CHCONTNUM,
			'''' || CHSILNUM AS CHSILNUM,
			CHCARNO,
			CHSOSOK,
			SKDESC1,
			CHCHSTR,
			CHCHEND,
			TRIM(TO_CHAR(CHEMPTY,'9,999,990.000')) AS CHEMPTY,
			TRIM(TO_CHAR(CHTOTAL,'9,999,990.000')) AS CHTOTAL,
			TRIM(TO_CHAR(CHMTQTY,'9,999,990.000')) AS CHMTQTY,
			TRIM(TO_CHAR(LTQTY,'9,999,990')) AS LTQTY,
			CHACTHJ,
			VNSANGHO,
			CHCHHJ,
			DCDESC1,
			CHDNST,
			GSDESC1,
			CHWKTYPE,
			GUBUN,
			JICARNO1,
			JIGSPINO
			FROM MAST
			ORDER BY CHCHULIL, HMDESC1, GSDESC1, CHCHTANK, CHCHSTR, CHCHEND
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 