DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3021_UTIPJIF_UPDATE;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3021_UTIPJIF_UPDATE 
( 
	IN P_IOIPDATE		NUMERIC(8, 0) ,   
	IN P_IOTKNO		NUMERIC(3, 0),   
	IN P_IOHISAB		VARCHAR(6),  
	OUT RET_MSG		VARCHAR(100)		
)										    
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSI3021_UTIPJIF_UPDATE
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
	P1 : BEGIN -- 시작
	DECLARE V_CNT		NUMERIC(2, 0);
	DECLARE V_IJTKNO	NUMERIC(3, 0);
	DECLARE V_GUBUN		VARCHAR(3);


	SELECT 
	VALUE(MAX(IJTKNO) + 1, 1) INTO V_IJTKNO
	FROM TYSCMLIB.UTIIPJIF            
	WHERE IJIPDATE = P_IOIPDATE;

	-- 지시파일 등록

	INSERT INTO TYSCMLIB.UTIIPJIF 
	(           
	IJIPDATE ,  
	IJTKNO ,    
	IJHWAJU ,   
	IJHWAMUL ,  
	IJTANKNO ,  
	IJIPQTY ,   
	IJCARNO ,   
	IJCONTAIN , 
	IJSEALNUM , 
	IJWKTYPE ,  
	IJTMGUBN ,  
	IJIPTIME ,  
	IJDESC ,    
	IJNUMBER ,  
	IJIPORNUM , 
	IJHIGB ,    
	IJHIDAT ,   
	IJHITIM ,   
	IJHISAB     
	)           
	SELECT        
	IOIPDATE ,    
	V_IJTKNO, 
	IOHWAJU ,     
	IOHWAMUL ,    
	IOTANKNO ,    
	IOIPQTY ,     
	IOCARNO ,     
	IOCONTAIN ,   
	IOSEALNUM ,   
	IOWKTYPE ,    
	IOTMGUBN ,    
	IOIPTIME ,    
	IODESC ,      
	IONUMBER ,    
	 DECIMAL(DIGITS(IOIPDATE)||DIGITS(IOTKNO)), 
	'A' ,         
	CURRENT_DATE, 
	CURRENT_TIME, 
	IOHISAB       
	FROM TYSCMLIB.UTIIPORF      
	WHERE IOIPDATE = P_IOIPDATE 
	AND   IOTKNO   = P_IOTKNO ;

	-- 오더파일 지시번호 업데이트
        UPDATE TYSCMLIB.UTIIPORF SET   
        IOJIDATE = P_IOIPDATE, 
        IOJISEQ  = V_IJTKNO
        WHERE IOIPDATE = P_IOIPDATE
        AND   IOTKNO   = P_IOTKNO  ;

	SET RET_MSG = 'SUCCESS!' ; 
END