--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0003_IPTANK_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0003_IPTANK_LIST ( 
        IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_IPHANG   VARCHAR(8),
	IN P_BONSUN   VARCHAR(3),
	IN P_HWAJU    VARCHAR(3),
	IN P_HWAMUL   VARCHAR(3),
	IN P_JITANKNO VARCHAR(4))  
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0003_IPTANK_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_CNT INTEGER;

PREV : BEGIN  -- 값 설정 
	SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 

	SELECT       
	COUNT(*) INTO P_CNT
	FROM TYSCMLIB.UTISURVF 
	WHERE SVIPHANG = P_IPHANG
	AND   SVBONSUN = P_BONSUN
	AND   SVHWAJU  = P_HWAJU
	AND   SVHWAMUL = P_HWAMUL
	AND   TRIM(SVTANKNO) = P_JITANKNO
	AND   SVMOGB   = ''              
	AND   (SVMTQTY - SVCHULQTY) > 0  ;

	IF P_CNT = 0 THEN 

		LIST1 : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			
			WITH TABLE1 AS
			(
			SELECT    
			COTANKNO, 
			COCONTNO, 
			COMTQTY,  
			COKLQTY,  
			COCHQTY,  
			(COMTQTY - COCHQTY) AS JGQTY 
			FROM TYSCMLIB.UTICOMEF      
			WHERE COIPHANG = P_IPHANG 
			AND   COBONSUN = P_BONSUN
			AND   COHWAJU  = P_HWAJU
			AND   COHWAMUL = P_HWAMUL
			AND   COMTQTY - COCHQTY <> 0 
			), ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER (ORDER BY COTANKNO) AS ROWNO,
				COTANKNO, 
				COCONTNO, 
				COMTQTY,  
				COKLQTY,  
				COCHQTY,  
				JGQTY   
			FROM TABLE1
			)
			SELECT
				ROWNO,
				COTANKNO, 
				COCONTNO, 
				COMTQTY,  
				COKLQTY,  
				COCHQTY,  
				JGQTY   
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC;

			OPEN REFCURSOR ;

		END LIST1 ; 
	  
		PAGING1 : BEGIN  -- 페이징 					

			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			
				WITH TABLE1 AS
				(
				SELECT    
				COTANKNO, 
				COCONTNO, 
				COMTQTY,  
				COKLQTY,  
				COCHQTY,  
				(COMTQTY - COCHQTY) AS JGQTY 
				FROM TYSCMLIB.UTICOMEF      
				WHERE COIPHANG = P_IPHANG 
				AND   COBONSUN = P_BONSUN
				AND   COHWAJU  = P_HWAJU
				AND   COHWAMUL = P_HWAMUL
				AND   COMTQTY - COCHQTY <> 0           
				), ORIGINAL_DATA AS (
				SELECT
					ROW_NUMBER() OVER (ORDER BY COTANKNO) AS ROWNO,
					COTANKNO, 
					COCONTNO, 
					COMTQTY,  
					COKLQTY,  
					COCHQTY,  
					JGQTY   
				FROM TABLE1
				)
				SELECT
					COUNT(*) AS TOTALCOUNT
				FROM ORIGINAL_DATA;

			OPEN REFCURSOR2 ;

		END PAGING1 ; 

	ELSE

		LIST2 : BEGIN  -- 리스트 

		DECLARE REFCURSOR3 CURSOR WITH RETURN FOR
			
			WITH TABLE1 AS
			(
			SELECT    
			COTANKNO, 
			COCONTNO, 
			COMTQTY,  
			COKLQTY,  
			COCHQTY,  
			(COMTQTY - COCHQTY) AS JGQTY 
			FROM TYSCMLIB.UTICOMEF      
			WHERE COIPHANG = P_IPHANG 
			AND   COBONSUN = P_BONSUN
			AND   COHWAJU  = P_HWAJU
			AND   COHWAMUL = P_HWAMUL
			AND   COMTQTY - COCHQTY <> 0 
			AND   TRIM(COTANKNO) = P_JITANKNO
			), ORIGINAL_DATA AS (
			SELECT
				ROW_NUMBER() OVER (ORDER BY COTANKNO) AS ROWNO,
				COTANKNO, 
				COCONTNO, 
				COMTQTY,  
				COKLQTY,  
				COCHQTY,  
				JGQTY   
			FROM TABLE1
			)
			SELECT
				ROWNO,
				COTANKNO, 
				COCONTNO, 
				COMTQTY,  
				COKLQTY,  
				COCHQTY,  
				JGQTY   
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC;

			OPEN REFCURSOR3 ;

		END LIST2 ; 
	  
		PAGING2 : BEGIN  -- 페이징 					

			DECLARE REFCURSOR4 CURSOR WITH RETURN FOR			
				WITH TABLE1 AS
				(
				SELECT    
				COTANKNO, 
				COCONTNO, 
				COMTQTY,  
				COKLQTY,  
				COCHQTY,  
				(COMTQTY - COCHQTY) AS JGQTY 
				FROM TYSCMLIB.UTICOMEF      
				WHERE COIPHANG = P_IPHANG 
				AND   COBONSUN = P_BONSUN
				AND   COHWAJU  = P_HWAJU
				AND   COHWAMUL = P_HWAMUL
				AND   COMTQTY - COCHQTY <> 0           
				), ORIGINAL_DATA AS (
				SELECT
					ROW_NUMBER() OVER (ORDER BY COTANKNO) AS ROWNO,
					COTANKNO, 
					COCONTNO, 
					COMTQTY,  
					COKLQTY,  
					COCHQTY,  
					JGQTY   
				FROM TABLE1
				)
				SELECT
					COUNT(*) AS TOTALCOUNT
				FROM ORIGINAL_DATA;

			OPEN REFCURSOR4 ;

		END PAGING2 ; 

	END IF;

      

END MAIN ; 
END  ;



    