DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3011_UTIJISIF_UPDATE;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3011_UTIJISIF_UPDATE 
( 
	IN P_JIYYMM		NUMERIC(8, 0) ,   
	IN P_JISEQ		NUMERIC(3, 0),   
	IN P_JIHISAB		VARCHAR(6),  
	OUT RET_MSG		VARCHAR(100)		
)										    
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSI3011_UTIJISIF_UPDATE
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
	P1 : BEGIN -- 시작
	DECLARE V_CNT	NUMERIC(2, 0);
	DECLARE V_JCSEQ	NUMERIC(3, 0);
	DECLARE V_GUBUN VARCHAR(3);

    
	-- 지시번호 테이블 존재유무 체크
	SELECT                          
	COUNT(*) INTO V_CNT        
	FROM TYSCMLIB.UTIJICNF          
	WHERE JCYYMM = P_JIYYMM;

	IF V_CNT = 0 THEN

		SET V_GUBUN = 'INS';
	ELSE 
		SET V_GUBUN = 'UPT';
	END IF;

	-- 지시 티켓번호 조회
	SELECT                            
	COALESCE(MAX(JCSEQ)+1,1) INTO V_JCSEQ 
	FROM TYSCMLIB.UTIJICNF           
	WHERE JCYYMM = P_JIYYMM;

	-- 동일자료 존재체크
	SELECT                  
	COUNT(*) INTO V_CNT
	FROM TYSCMLIB.UTIJISIF 
	WHERE JIYYMM = P_JIYYMM
	AND   JISEQ  = V_JCSEQ;

	IF V_CNT > 0 THEN

		SELECT 
		VALUE(MAX(JISEQ) + 1, 1) INTO V_JCSEQ
		FROM TYSCMLIB.UTIJISIF            
		WHERE JIYYMM = P_JIYYMM;

	END IF;

	--지시번호 테이블 업데이트
	IF V_GUBUN = 'INS' THEN

		INSERT INTO TYSCMLIB.UTIJICNF(
		JCYYMM,  
		JCSEQ)   
		VALUES(  
		P_JIYYMM,
		V_JCSEQ);

	ELSE

		UPDATE TYSCMLIB.UTIJICNF SET
		JCSEQ        = V_JCSEQ
		WHERE JCYYMM = P_JIYYMM;

	END IF;

	-- 지시파일 등록

	INSERT INTO TYSCMLIB.UTIJISIF 
	(           
	JIYYMM,     
	JISEQ,      
	JIIPHANG,   
	JIBONSUN,   
	JIHWAJU,    
	JIHWAMUL,   
	JIBLNO,     
	JIMSNSEQ,   
	JIHSNSEQ,   
	JIACTHJ,    
	JICUSTIL,   
	JICHASU,    
	JIJGHWAJU,  
	JIYSHWAJU,  
	JIYDHWAJU,  
	JIYSDATE,   
	JIYDSEQ,    
	JIYSSEQ,    
	JICHHJ,     
	JITANKNO,   
	JIIPTANK,   
	JIIPQTY,    
	JIJEQTY,    
	JIJANQTY,   
	JIJANGB,    
	JITRGUBN,   
	JITRJISI1,  
	JITRJISI2,  
	JICARNO1,   
	JICARNO2,   
	JICHJANG,   
	JICHTYPE,   
	JIUNIT,     
	JIRACK,     
	JIPUMP,     
	JIBCNO1,    
	JIBCNO2,    
	JISTMTQTY,  
	JIEDMTQTY,  
	JISTLTQTY,  
	JIEDLTQTY,  
	JICONTNUM,  
	JISILNUM,   
	JITMGUBN,   
	JIWKTYPE,   
	JITIMEHH,   
	JITIMEMM,   
	JIDNST,     
	JIJICNT,    
	JIHIGB,     
	JIHIDAT,    
	JIHITIM,    
	JIHISAB     
	)           
	SELECT      
	P_JIYYMM, 
	V_JCSEQ, 
	JIIPHANG,   
	JIBONSUN,   
	JIHWAJU,    
	JIHWAMUL,   
	JIBLNO,     
	JIMSNSEQ,   
	JIHSNSEQ,   
	JIACTHJ,    
	JICUSTIL,   
	JICHASU,    
	JIJGHWAJU,  
	JIYSHWAJU,  
	JIYDHWAJU,  
	JIYSDATE,   
	JIYDSEQ,    
	JIYSSEQ,    
	JICHHJ,     
	JITANKNO,   
	JIIPTANK,   
	JIIPQTY,    
	JIJEQTY,    
	JIJANQTY,   
	JIJANGB,    
	JITRGUBN,   
	JITRJISI1,  
	JITRJISI2,  
	JICARNO1,   
	JICARNO2,   
	JICHJANG,   
	JICHTYPE,   
	JIUNIT,     
	JIRACK,     
	JIPUMP,     
	JISINO1,    
	JISINO2,    
	JISTMTQTY,  
	JIEDMTQTY,  
	JISTLTQTY,  
	JIEDLTQTY,  
	JICONTNUM,  
	JISILNUM,   
	JITMGUBN,   
	JIWKTYPE,   
	JITIMEHH,   
	JITIMEMM,   
	JIDNST,     
	'1', 
	'A', 
	CURRENT_DATE,  
	CURRENT_TIME,  
	P_JIHISAB
	FROM TYSCMLIB.UTIORDERF 
	WHERE JIYYMM = P_JIYYMM
	AND   JISEQ  = P_JISEQ;

	-- 오더파일 지시번호 업데이트
	UPDATE TYSCMLIB.UTIORDERF SET 
	JISINO1 = P_JIYYMM, 
	JISINO2 = V_JCSEQ
	WHERE JIYYMM = P_JIYYMM
	AND   JISEQ  = P_JISEQ;

	SET RET_MSG = 'SUCCESS!' ; 
END