DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3020_LIST;

--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	21-07-13 14:46:21 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","LSHPDM" ; 
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3020_LIST (
	IN P_CURRENTPAGEINDEX INTEGER,
	IN P_PAGESIZE         INTEGER,
	IN P_SDATE            VARCHAR(8),
	IN P_EDATE            VARCHAR(8),
	IN P_HWAJU            VARCHAR(50),
	IN P_HWAMUL           VARCHAR(3),
	IN P_CARNO            VARCHAR(4),
	IN P_TANKNO           VARCHAR(4)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSI3020_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD,
	ALWCPYDTA = *OPTIMIZE,
	COMMIT = *NONE,
	DECRESULT = (31, 31, 00),
	DFTRDBCOL = *NONE,
	DYNDFTCOL = *NO,
	DYNUSRPRF = *USER,
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR (4000) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR (4000) ; 
	DECLARE P_TABLE_QUERY			VARCHAR (5000) ; 
	DECLARE P_COUNT_QUERY			VARCHAR (5000) ; 
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = (P_PAGESIZE * (P_CURRENTPAGEINDEX - 1)) + 1 ; 
SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			WITH TABLE1 AS (
			SELECT 
			IOIPDATE,
			IOTKNO,
			IOHWAJU,
			VEND.VNSANGHO,
			IOHWAMUL,
			HMCODE.CDDESC1 AS HMDESC1,
			IOTANKNO,
			IOIPQTY,
			CJIPQTY,
			IOCARNO,
			IOCONTAIN,
			IOSEALNUM,
			(CASE WHEN IOWKTYPE = '01' THEN 'TANK LORRY' 
			      WHEN IOWKTYPE = '02' THEN 'ISO TANK' 
			      WHEN IOWKTYPE = '03' THEN 'FLEXI BAG' END) AS IOWKTYPE,
			(CASE WHEN IOTMGUBN = '1' THEN '일반' 
			      WHEN IOTMGUBN = '2' THEN '조출' 
			      WHEN IOTMGUBN = '3' THEN '특허' END) AS IOTMGUBNM,
			IOIPTIME,
			IODESC,
			IONUMBER,
			(CASE WHEN IPJI.IJIPDATE > 0 THEN 
				(CASE WHEN CHJI.CJIPQTY > 0 THEN 
					'입고완료' 
					WHEN CHJI.CJEMPTY > 0 THEN 
					'입고중' 
				ELSE 
					'지시완료' 
				END) 
			ELSE 
			'대 기' 
			END) AS JISTATUS 
			FROM TYSCMLIB.UTIIPORF AS IPOR 
			LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND 
			ON IPOR.IOHWAJU = VEND.VNCODE 
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE 
			ON 'HM' = HMCODE.CDINDEX 
			AND IPOR.IOHWAMUL = HMCODE.CDCODE 
			LEFT OUTER JOIN TYSCMLIB.UTIIPJIF AS IPJI 
			ON DIGITS (IOIPDATE) || DIGITS (IOTKNO) = DIGITS (IJIPORNUM) 
			LEFT OUTER JOIN TYSCMLIB.UTICHJIF AS CHJI 
			ON DIGITS (IPJI.IJIPDATE) || DIGITS (IPJI.IJTKNO) = DIGITS (CJJISINO1) 
			WHERE IPOR.IOIPDATE BETWEEN P_SDATE AND P_EDATE 
			AND   IPOR.IOHWAJU IN (SELECT * FROM TABLE (TYSCMLIB.SF_GB_REVCOLROW (CAST (P_HWAJU AS VARCHAR (100)),',')) AS INTABLE)
			AND   IPOR.IOHWAMUL LIKE  P_HWAMUL||'%'
			AND   IPOR.IONUMBER LIKE  '%'||P_CARNO||'%'
			AND   TRIM(IPOR.IOTANKNO)  LIKE P_TANKNO||'%'
			ORDER BY IOIPDATE,IOTKNO 
			),ORIGINAL_DATA AS (
			SELECT ROW_NUMBER () OVER (ORDER BY IOIPDATE,IOTKNO) AS ROWNO,
				IOIPDATE,
				IOTKNO,
				IOHWAJU,
				VNSANGHO,
				IOHWAMUL,
				HMDESC1,
				IOTANKNO,
				IOIPQTY,
				CJIPQTY,
				IOCARNO,
				IOCONTAIN,
				IOSEALNUM,
				IOWKTYPE,
				IOTMGUBNM,
				IOIPTIME,
				IODESC,
				IONUMBER,
				JISTATUS 
			FROM TABLE1 
			) 
			SELECT ROWNO,
				IOIPDATE,
				IOTKNO,
				IOHWAJU,
				VNSANGHO,
				IOHWAMUL,
				HMDESC1,
				IOTANKNO,
				IOIPQTY,
				CJIPQTY,
				IOCARNO,
				IOCONTAIN,
				IOSEALNUM,
				IOWKTYPE,
				IOTMGUBNM,
				IOIPTIME,
				IODESC,
				IONUMBER,
				JISTATUS 
			FROM ORIGINAL_DATA 
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM 
			ORDER BY ROWNO ASC ; 
  
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
	PAGING : BEGIN  -- 페이징 					 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR			 
				WITH TABLE1 AS (
				SELECT 
				IOIPDATE,
				IOTKNO,
				IOHWAJU,
				VEND.VNSANGHO,
				IOHWAMUL,
				HMCODE.CDDESC1 AS HMDESC1,
				IOTANKNO,
				IOIPQTY,
				CJIPQTY,
				IOCARNO,
				IOCONTAIN,
				IOSEALNUM,
				(CASE WHEN IOWKTYPE = '01' THEN 'TANK LORRY' 
				      WHEN IOWKTYPE = '02' THEN 'ISO TANK' 
				      WHEN IOWKTYPE = '03' THEN 'FLEXI BAG' END) AS IOWKTYPE,
				(CASE WHEN IOTMGUBN = '1' THEN '일반' 
				      WHEN IOTMGUBN = '2' THEN '조출' 
				      WHEN IOTMGUBN = '3' THEN '특허' END) AS IOTMGUBNM,
				IOIPTIME,
				IODESC,
				IONUMBER,
				(CASE WHEN IPJI.IJIPDATE > 0 THEN 
					(CASE WHEN CHJI.CJIPQTY > 0 THEN 
						'입고완료' 
						WHEN CHJI.CJEMPTY > 0 THEN 
						'입고중' 
					ELSE 
						'지시완료' 
					END) 
				ELSE 
				'대 기' 
				END) AS JISTATUS 
				FROM TYSCMLIB.UTIIPORF AS IPOR 
				LEFT OUTER JOIN TYSCMLIB.UTIVENDF AS VEND 
				ON IPOR.IOHWAJU = VEND.VNCODE 
				LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE 
				ON 'HM' = HMCODE.CDINDEX 
				AND IPOR.IOHWAMUL = HMCODE.CDCODE 
				LEFT OUTER JOIN TYSCMLIB.UTIIPJIF AS IPJI 
				ON DIGITS (IOIPDATE) || DIGITS (IOTKNO) = DIGITS (IJIPORNUM) 
				LEFT OUTER JOIN TYSCMLIB.UTICHJIF AS CHJI 
				ON DIGITS (IPJI.IJIPDATE) || DIGITS (IPJI.IJTKNO) = DIGITS (CJJISINO1) 
				WHERE IPOR.IOIPDATE BETWEEN P_SDATE AND P_EDATE 
				AND   IPOR.IOHWAJU IN (SELECT * FROM TABLE (TYSCMLIB.SF_GB_REVCOLROW (CAST (P_HWAJU AS VARCHAR (100)),',')) AS INTABLE)
				AND   IPOR.IOHWAMUL LIKE  P_HWAMUL||'%'
				AND   IPOR.IONUMBER LIKE  '%'||P_CARNO||'%'
				AND   TRIM(IPOR.IOTANKNO)  LIKE P_TANKNO||'%'
				ORDER BY IOIPDATE,IOTKNO 
				),ORIGINAL_DATA AS (
				SELECT ROW_NUMBER () OVER (ORDER BY IOIPDATE,IOTKNO) AS ROWNO,
					IOIPDATE,
					IOTKNO,
					IOHWAJU,
					VNSANGHO,
					IOHWAMUL,
					HMDESC1,
					IOTANKNO,
					IOIPQTY,
					CJIPQTY,
					IOCARNO,
					IOCONTAIN,
					IOSEALNUM,
					IOWKTYPE,
					IOTMGUBNM,
					IOIPTIME,
					IODESC,
					IONUMBER,
					JISTATUS 
				FROM TABLE1 
				)					 
				SELECT 
					COUNT (*) AS TOTALCOUNT 
				FROM ORIGINAL_DATA ; 
  
			OPEN REFCURSOR2 ; 
  
	END PAGING ; 
  
END MAIN ; 
END  ; 
  
GRANT ALTER,EXECUTE   
ON SPECIFIC PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3020_LIST 
TO LSHPDM WITH GRANT OPTION ;
