--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3030_LIST ; 
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSI3030_LIST ( 
	IN P_JIYYMM NUMERIC(8, 0),
	IN P_JIGSPINO VARCHAR(40)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			JISI.JIYYMM,
			JISI.JISEQ,
			HJCODE.CDDESC1 AS HJDESC,
			HJCODE1.CDDESC1 AS HJDESC1,
			HMCODE.CDDESC1 AS HMDESC1,
			HJCODE3.CDDESC1 AS HJDESC3,
			(CASE WHEN JISI.JISTMTQTY <> 0 THEN JISI.JISTMTQTY ELSE JISI.JISTLTQTY END) AS JISTQTY,
			(CASE WHEN JISI.JIEDMTQTY <> 0 THEN JISI.JIEDMTQTY ELSE JISI.JIEDLTQTY END) AS JIEDQTY,
			JISI.JICHQTY,
			CASE WHEN LENGTH(JISI.JIGSPINO) <= 8 THEN JISI.JITANKNO END AS JITANKNO,
			JISI.JICARNO2,
			JISI.JICARNO1,
			JISI.JIIPHANG,
			VSCODE.CDDESC1 AS VSDESC1,
			JISI.JIBLNO,
			JISI.JIMSNSEQ,
			JISI.JIHSNSEQ,
			JISI.JICUSTIL,
			JISI.JICHASU,
			HJCODE4.CDDESC1 AS YSDESC1,
			HJCODE5.CDDESC1 AS YDDESC1,
			GSCODE.CDDESC1 AS GSDESC1,
			JISI.JIYSDATE,
			JISI.JIYDSEQ,
			JISI.JIYSSEQ,
			JISI.JICONTNUM,
			JISI.JISILNUM,
			(CASE WHEN JISI.JITMGUBN = '1' THEN '일반'
			      WHEN JISI.JITMGUBN = '2' THEN '조출'
			      WHEN JISI.JITMGUBN = '3' THEN '특허' END) AS JITMGUBN,
			(CASE WHEN JISI.JITIMEHH <> '' AND JISI.JITIMEMM <> '' THEN (JISI.JITIMEHH||':'||JISI.JITIMEMM) END) AS JITIME,
			(CASE WHEN JISI.JIWKTYPE = '01' THEN 'TANK LORRY'
			      WHEN JISI.JIWKTYPE = '02' THEN 'ISO CONTAINER'
			      WHEN JISI.JIWKTYPE = '03' THEN 'FLEXI BAG'
			      ELSE 'TANK LORRY' END) AS JIWKTYPE,
			JISI.JIGSPINO,
			(CASE WHEN VALUE(ORDER.JIYYMM,0) <> 0 THEN (ORDER.JIYYMM || '-' || DIGITS(ORDER.JISEQ)) ELSE '' END) AS ORDERSEQ ,
			VALUE(DIGITS(CHUL.CHJISINUM), '') AS CHJISINUM,
			CASE WHEN LENGTH(JISI.JIGSPINO) <= 8 THEN CHMTQTY END CHMTQTY,
			'' AS BLANK
			FROM TYSCMLIB.UTIJISIF AS JISI
			LEFT OUTER JOIN TYSCMLIB.UTICHULF AS CHUL
			ON   DIGITS(CHUL.CHJISINUM) = JISI.JIYYMM || DIGITS(JISI.JISEQ)
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HJCODE
			ON                 'HJ' = HJCODE.CDINDEX
			AND      JISI.JIJGHWAJU = HJCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HJCODE1
			ON                 'HJ' = HJCODE1.CDINDEX
			AND        JISI.JIACTHJ = HJCODE1.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HJCODE3
			ON                 'DC' = HJCODE3.CDINDEX
			AND         JISI.JICHHJ = HJCODE3.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS GSCODE
			ON                 'GS' = GSCODE.CDINDEX
			AND         JISI.JIDNST = GSCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HMCODE
			ON                 'HM' = HMCODE.CDINDEX
			AND       JISI.JIHWAMUL = HMCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS VSCODE
			ON                 'VS' = VSCODE.CDINDEX
			AND       JISI.JIBONSUN = VSCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HJCODE4
			ON                 'HJ' = HJCODE4.CDINDEX
			AND      JISI.JIYSHWAJU = HJCODE4.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTICODEF AS HJCODE5
			ON                 'HJ' = HJCODE5.CDINDEX
			AND      JISI.JIYDHWAJU = HJCODE5.CDCODE
			LEFT OUTER JOIN TYSCMLIB.UTIORDERF AS ORDER
			ON       ORDER.JISINO1 = JISI.JIYYMM
			AND      ORDER.JISINO2 = JISI.JISEQ
			WHERE JISI.JIYYMM = P_JIYYMM
			AND   JISI.JIGSPINO = P_JIGSPINO
			ORDER BY JISI.JIYYMM DESC, JISI.JISEQ DESC
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 