DROP PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0005_UTICODEF_UPDATE;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSI_CSB0005_UTICODEF_UPDATE 
( 
	IN P_CDCODE		VARCHAR(3),
	IN P_CDDESC1		VARCHAR(100),
	OUT RET_MSG		VARCHAR(100)		
)										    
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSI_CSB0005_UTICODEF_UPDATE
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
P1 : BEGIN -- Ω√¿€

	INSERT INTO TYSCMLIB.UTICODEF( 
	CDINDEX,  
	CDCODE,   
	CDDESC1)  
	VALUES(    
	'DC',  
	P_CDCODE, 
	P_CDDESC1
	)  ;

	SET RET_MSG = 'SUCCESS!' ; 
END