-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_ACLGROUP_GET
-- 작성자     : 문광복
-- 작성일     : 2014-04-03
-- 설명       : 사용자의 권한유무를 조회한다.
-- 예문       : CALL CMN_ACLGROUP_GET ('','')
--      DB2 변환 : 이전프로시져명 CMN_ACLGROUP_GET
--		프렌지 변환 : PTCMMBAS10S1 -> CMN_ACL_GET_USER
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.CMN_ACLGROUPUSER_GET
CREATE PROCEDURE TYJINFWLIB.CMN_ACLGROUPUSER_GET
(
    	P_CURRENTPAGEINDEX      INTEGER
	,	P_PAGESIZE              INTEGER
	,	P_LANGCD				VARCHAR(10)
	,	P_PROGRAMID				VARCHAR(50)
	,	P_GRPID					VARCHAR(10)
	,	P_USRTYPE				VARCHAR(10)
	,	P_USRID					VARCHAR(50)
	,	P_EMPNM					VARCHAR(50)
	,	P_RETIREYN				VARCHAR(1)
)
	RESULT SETS 2
	LANGUAGE SQL
M1: BEGIN
	DECLARE P_STNUM			INTEGER;
    DECLARE P_FNNUM			INTEGER;

	PREV : BEGIN -- 값 설정
        SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ;
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ;
    END PREV;

	-- 임시테이블부
	DECLARE GLOBAL TEMPORARY TABLE SESSION.CMN_ACLGROUP_LIST (
			USRNM			NVARCHAR(100)
		,	EMPID			VARCHAR(20)
		,	EMPNM			NVARCHAR(100)
		,	USRTYPE			VARCHAR(10)
		,	RETIREYN		VARCHAR(1)
		,	COMPANYCODE		VARCHAR(10)
    ) WITH REPLACE;
	-- 임시테이블부 끝

	-- 임시테이블 입력부
	INSERT INTO SESSION.CMN_ACLGROUP_LIST
	SELECT
			CASE
				WHEN COALESCE(G.GRPEXT, '') <> ''	THEN GL.GRPNAME
				WHEN GM.USRTYPE = '1'				THEN TYJINFWLIB.UF_USERINFO_USERNAME2(GM.USRID, P_LANGCD)
				WHEN GM.USRTYPE = '2'				THEN '' --TYJINFWLIB.UF_DEPTNAME(GM.USRID, P_LANGCD, GM.COMPANYCODE)
			END AS USRNM
		,	CASE
				WHEN GM.USRTYPE = '1' THEN UM.EMPID
				WHEN GM.USRTYPE = '2' THEN DM.EMPID
			END AS EMPID
		,	TYJINFWLIB.UF_USERINFO_USERNAME2(CASE
				WHEN GM.USRTYPE = '1' THEN UM.EMPID
				WHEN GM.USRTYPE = '2' THEN DM.EMPID
			END, P_LANGCD) AS EMPNM
		,	GM.USRTYPE
		,	CASE
				WHEN COALESCE(CASE
								WHEN GM.USRTYPE = '1'	THEN US.DISPLAYYN
								WHEN GM.USRTYPE = '2'	THEN DS.DISPLAYYN
								END, 'N') = 'N'
				THEN 'Y'
				ELSE 'N'
			END AS RETIREYN
		,	CASE
				WHEN GM.USRTYPE = '1' THEN UM.COMPANYCODE
				WHEN GM.USRTYPE = '2' THEN DM.COMPANYCODE
			END AS COMPANYCODE
	FROM 
			TYJINFWLIB.CMN_ACL AS A
			INNER JOIN	TYJINFWLIB.ORG_GROUP AS G
				ON	A.ACL_GRP			= G.GRPID
			LEFT OUTER JOIN	TYJINFWLIB.ORG_GROUPLANG AS GL
				ON	G.GRPID				= GL.GRPID
				AND	GL.LANGCODE			= P_LANGCD
			LEFT OUTER JOIN TYJINFWLIB.ORG_GROUPUSR AS GM
				ON	G.GRPID				= GM.GRPID
			LEFT JOIN TYJINFWLIB.ORG_DEPTUSR AS DM
				ON	GM.COMPANYCODE		= DM.COMPANYCODE
				AND GM.USRID			= DM.DEPTCODE
				AND GM.USRTYPE			= '2'
			LEFT JOIN TYJINFWLIB.ORG_USER AS DS
				ON	DS.COMPANYCODE		= DM.COMPANYCODE
				AND DS.EMPID			= DM.EMPID
			LEFT JOIN TYJINFWLIB.ORG_USER AS UM
				ON	GM.COMPANYCODE		= UM.COMPANYCODE
				AND GM.USRID			= UM.EMPID
				AND GM.USRTYPE			= '1'
			LEFT JOIN TYJINFWLIB.ORG_USER AS US
				ON	US.COMPANYCODE		= UM.COMPANYCODE
				AND US.EMPID			= UM.EMPID
	WHERE 
			A.ACL_TYPE						= 'MENU' 
	AND		A.ACL_ID						IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE PROGRAMID = P_PROGRAMID)
	AND		(COALESCE(P_GRPID, '')			= '' OR A.ACL_GRP	= P_GRPID)
	AND		(
				COALESCE(P_USRTYPE, '')		IN ('', '9')
			OR	GM.USRID					= P_USRID
			)
	;
	-- 임시테이블 입력부 끝
	
	LIST : BEGIN -- 리스트
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		WITH MST AS (
			SELECT
					ROW_NUMBER() OVER (ORDER BY A.USRTYPE ASC) AS ROWNO
				,   A.*
			FROM
					SESSION.CMN_ACLGROUP_LIST AS A
			WHERE
					A.EMPNM							LIKE '%' || P_EMPNM || '%'
			AND		(
						COALESCE(P_RETIREYN, '')	= ''
					OR	RETIREYN					= 'Y'
					)
		)
		SELECT
				M.*
			,	CL.COMPANY
			,	U.MAINDEPTCODE AS DEPTCD
			,	TYJINFWLIB.UF_DEPTNAME(M.COMPANYCODE, P_LANGCD, U.MAINDEPTCODE) AS DEPTNM
		FROM
				MST AS M
				LEFT OUTER JOIN TYJINFWLIB.ORG_USER AS U
					ON	U.COMPANYCODE		= M.COMPANYCODE
					AND	U.EMPID				= M.EMPID
				LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
					ON	CL.COMPANYCODE		= M.COMPANYCODE
					AND	CL.LANGUAGECODE		= 'ko'
		WHERE
				M.ROWNO		BETWEEN P_STNUM AND P_FNNUM
		;
		OPEN REFCURSOR;
    END LIST;

 

    PAGING : BEGIN -- 페이징
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
		SELECT
				COUNT(*) AS TOTALCOUNT
		FROM
				SESSION.CMN_ACLGROUP_LIST AS A
		WHERE
				A.EMPNM							LIKE '%' || P_EMPNM || '%'
		AND		(
					COALESCE(P_RETIREYN, '')	= ''
				OR	RETIREYN					= 'Y'
				)
		;
		OPEN REFCURSOR2;
    END PAGING;
END M1;