--DROP PROCEDURE TYJINFWLIB.CMN_MENU_SEARCH_GET;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : CMN_MENU_SEARCH_GET
-- 작성자     : 문광복
-- 작성일     : 2015-09-01
-- 설명       : 메뉴목록 콤보박스 검색
-- 예문       : EXEC CMN_MENU_SEARCH_GET 'MENU04'
--		DB2 변환 : 이전프로시져명 SP_MENU_MANAGEMENT_TREE_SELECT_SEARCH
--		프렌지 변환 : PTCMMBAS40L2 -> CMN_MENU_SEARCH_GET
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_MENU_SEARCH_GET
(
	P_MENUID				VARCHAR(50)		-- 메뉴아이디
)
	RESULT SETS 1
	LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH TREE (MENUID, PROGRAMID, PRTMENU, DISPLAYYN, IPYN, KO, EN, ZH, RU, LEV, MENUTYPE , SORTNO)  AS
		(
			SELECT M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, M.IPYN, L.KO, L.EN, L.ZH, L.RU, 1 AS LEV , M.MENUTYPE , M.SORTNO
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TYJINFWLIB.CMN_LANG L 
					ON M.MENUID = L.CODE
			WHERE COALESCE(PRTMENU,'') = '' 
              AND MENUID LIKE '%' || P_MENUID || '%'
	
			UNION ALL
	
			SELECT M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, M.IPYN, L.KO, L.EN, L.ZH, L.RU, (LEV  +  1) AS LEV , M.MENUTYPE, M.SORTNO
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TREE T
					ON T.MENUID = M.PRTMENU
				INNER JOIN TYJINFWLIB.CMN_LANG L 
					ON M.MENUID = L.CODE
			WHERE M.PRTMENU LIKE '%' || P_MENUID || '%'
		)
		SELECT * FROM TREE ORDER BY LEV ASC , SORTNO;

	OPEN REFCURSOR;

END P1

