-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_ACLGROUPMEMBER_GET
-- 작성자     : 장윤호
-- 작성일     : 2017-07-12
-- 설명       : 프로그램별 권한 그룹멤버 조회
-- 예문       : CALL TYJINFWLIB.CMN_ACLGROUPMEMBER_GET ('ko', 'VFCM0102010', 'SEOHAN_VND')
-- DB2 변환   : 이전프로시져명 UP_ACL_SELECT_GROUPMEMBER
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.CMN_ACLGROUPMEMBER_GET
CREATE PROCEDURE TYJINFWLIB.CMN_ACLGROUPMEMBER_GET
(
    	P_LANGCD				VARCHAR(10)
	,	P_PROGRAMID				VARCHAR(50)
	,	P_GRPID					VARCHAR(10)
)
    RESULT SETS 2
    LANGUAGE SQL
M1 : BEGIN
	L1 : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT M.* , 
			CASE	WHEN M.USRTYPE = '2'
					THEN M.DM_CNT + M.EX_CNT
					ELSE NULL
			END AS USR_CNT
		FROM (
			SELECT
					G.GRPID
				,	GL.GRPNAME
				,	GM.USRID
				--,	CASE
				--		WHEN COALESCE(G.GrpExt, '') <> ''		THEN  '권한그룹'
				--		WHEN  GM.USRTYPE = '1'	THEN PORTAL.DBO.FN_GET_LANG('AM0304000', 'TXT22', P_LANGCD)
				--		WHEN  GM.USRTYPE = '2'	THEN PORTAL.DBO.FN_GET_LANG('AM0304000', 'TXT21', P_LANGCD)
				--	END		AS USRTYPENM
				,	GM.USRTYPE
				,	CASE
						WHEN COALESCE(G.GRPEXT, '') <> ''
						THEN '9'
						ELSE GM.USRTYPE
					END AS USRTYPENM
				,	CASE
						WHEN COALESCE(CL.COMPANY, '') = ''
						THEN CL_KO.COMPANY
						ELSE CL.COMPANY
					END AS COMPANY
				,	CASE
						WHEN COALESCE(G.GRPEXT, '') <> ''	THEN GL.GRPNAME
						WHEN GM.USRTYPE = '1'				THEN TYJINFWLIB.UF_USERINFO_USERNAME2(GM.USRID, P_LANGCD)
						WHEN GM.USRTYPE = '2'				THEN TYJINFWLIB.UF_DEPTNAME(GM.COMPANYCODE, P_LANGCD, GM.USRID)
					END AS USRNM
				,	(	SELECT
								COUNT(DISTINCT EMPID) AS DM_CNT
						FROM
								TYJINFWLIB.ORG_DEPTUSR	AS DM
						WHERE
								GM.COMPANYCODE		= DM.COMPANYCODE
						AND		GM.USRID			= DM.DEPTCODE
					) AS DM_CNT
				,	(	SELECT
								COUNT(EMPID)	AS EX_CNT
						FROM
								TABLE(TYJINFWLIB.UF_GET_GRPEXTMEMBERS(COALESCE(G.GRPEXT,''))) AS E
					) AS EX_CNT
			FROM 
					TYJINFWLIB.CMN_ACL AS A
					INNER JOIN	TYJINFWLIB.ORG_GROUP AS G
						ON	A.ACL_GRP				= G.GRPID
					LEFT OUTER JOIN	TYJINFWLIB.ORG_GROUPLANG AS GL
						ON	G.GRPID					= GL.GRPID
						AND	LOWER(GL.LANGCODE)		= 'ko'
					LEFT OUTER JOIN TYJINFWLIB.ORG_GROUPUSR AS GM
						ON	G.GRPID					= GM.GRPID
					LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL
						ON	CL.COMPANYCODE			= GM.COMPANYCODE
						AND	CL.LANGUAGECODE			= P_LANGCD
					LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL_KO
						ON	CL_KO.COMPANYCODE		= GM.COMPANYCODE
						AND	CL_KO.LANGUAGECODE		= 'ko'
			WHERE 
					A.ACL_TYPE		= 'MENU' 
			AND		A.ACL_ID		IN (SELECT MENUID FROM TYJINFWLIB.CMN_MENU WHERE LOWER(MENUID) = LOWER(P_PROGRAMID))
			AND		(COALESCE(P_GRPID, '') = '' OR A.ACL_GRP = P_GRPID)
		) AS M;
		
		OPEN REFCURSOR;
	END L1;
END M1;