--DROP PROCEDURE TYJINFWLIB.CMN_MENU_GET;
-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_MENU_LEFT_TREE_GET
-- 작성자     : 문광복
-- 작성일     : 2015-09-03
-- 설명       : 메뉴트리(좌측메뉴) 조회
-- 예문       : EXEC CMN_MENU_GET 'GRK3672', '3672      '
--		DB2 변환 : 이전프로시져명 SP_TREE_SELECT_MENU_BYSUB
--		프렌지 변환 : PTCMMBAS40L4 -> CMN_MENU_LEFT_TREE_GET
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_MENU_GET
(
	P_EMPID				VARCHAR(20),
	P_COMPANYCODE		VARCHAR(10),
	P_LANGCODE			VARCHAR(2),
	P_MENUTYPE			VARCHAR(10)
)
	
	RESULT SETS 1
	LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT	A.MENUID AS IDX,A. PROGRAMID, A.PRTMENU AS PRTIDX, 
			CASE WHEN P_LANGCODE = 'en' THEN C.EN 
			ELSE C.KO END 
				AS TEXT, 
			A.LEV, B.PROGRAMPATH	
		FROM	(
			SELECT	MENUID, PROGRAMID, PRTMENU, DISPLAYYN, 1 AS LEV, SORTNO
			FROM	TYJINFWLIB.CMN_MENU
			WHERE	PRTMENU = '' -- P_MENUID
					AND MENUTYPE = P_MENUTYPE
                    AND COALESCE(DISPLAYYN,'N') = 'Y'
					AND MENUID IN 
					(
						SELECT	ACL_ID 
						FROM	TYJINFWLIB.CMN_ACL 
						WHERE	ACL_TYPE='MENU' AND ACL_GRP IN 
						(
							SELECT	GRPID 
							FROM	TYJINFWLIB.ORG_GROUPUSR  AS G
							WHERE	(USRID = P_EMPID AND G.UsrType = '1')
							--OR		EXISTS(SELECT * FROM OrgChartNVH.dbo.tb_DeptMember AS D WHERE D.UserCompanyCode = P_COMPANYCODE AND D.EmpID = P_EMPID AND D.CompanyCode = G.Companycode AND D.DeptCode = G.UsrID AND G.UsrType = '2')
						)
					)
					--AND MENUTYPE IN ('GP','GW')
			) A 
			--LEFT JOIN TYJINFWLIB.CMN_PROGRAM B ON A.PROGRAMID = B.PROGRAMID 
            LEFT JOIN TYJINFWLIB.CMN_PROGRAM B ON CASE WHEN A.PROGRAMID = 'VFCM0102010' THEN 'VISR0301010' ELSE A.PROGRAMID END = B.PROGRAMID 
			LEFT JOIN TYJINFWLIB.CMN_LANG C ON C.PROGRAMID='MENU' AND A.MENUID=C.CODE

			ORDER BY SORTNO;
		--WHERE DISPLAYYN = '1';


	OPEN REFCURSOR;

END P1

