-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_MENU_TREE_GET_ACLCHK  
-- 작성자     : 서정민
-- 작성일     : 2015-09-02
-- 설명       : 메뉴트리 조회(권한지정용)
-- 예문       : EXEC CMN_MENU_TREE_GET_ACLCHK   ()
--		DB2 변환 : 이전프로시져명 SP_TREE_SELECT_MENU_ACL
--		프렌지 변환 : PTCMMBAS40S3 -> CMN_MENU_TREE_GET_ACLCHK 
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_MENU_TREE_GET_ACLCHK
(
	P_GRPID VARCHAR(10)
)
	
	RESULT SETS 1
	LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TREE (MENUID, PROGRAMID, PRTMENU, DISPLAYYN, LEV, SORTNO)  AS
		(
			SELECT 
				MENUID
			,	PROGRAMID
			,	PRTMENU
			,	DISPLAYYN
			,	1 AS LEV,SORTNO
			FROM TYJINFWLIB.CMN_MENU
			WHERE PRTMENU IS NULL 
				--AND (MENUID='GW' OR MENUID='AP' OR MENUID='MS' OR MENUID='MD' OR MENUID='PM' OR MENUID='PS' )--OR MENUID='QM' OR MENUID='TS')
	
			UNION ALL

			SELECT 
				M.MENUID
			,	M.PROGRAMID
			,	CASE WHEN M.PRTMENU IS NULL 
					THEN 'TOP' 
					ELSE M.PRTMENU 
				END AS PRTMENU
			,	M.DISPLAYYN
			,	(LEV + 1) AS LVL,M.SORTNO
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TREE T
					ON T.MENUID = M.PRTMENU
		)

		SELECT 
			A.MENUID AS IDX
		,	A.PROGRAMID
		,	A.PRTMENU AS PRTIDX
		,	A.LEV
		,	C.KO AS TEXT
		,	A.SORTNO 
		FROM TREE A 
			LEFT JOIN TYJINFWLIB.CMN_LANG C 
				ON (C.PROGRAMID='MENU' AND A.MENUID = C.CODE)
		WHERE A.DISPLAYYN = 1 
			AND A.MENUID IN
			(
				SELECT ACL_ID 
				FROM TYJINFWLIB.CMN_ACL 
				WHERE ACL_TYPE='MENU' AND ACL_GRP = P_GRPID
			)
		ORDER BY LEV,PRTMENU, SORTNO;
		
	OPEN REFCURSOR;

END P1