--DROP PROCEDURE TYJINFWLIB.CMN_MENU_TREE_GET;
-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_MENU_TREE_GET
-- 작성자     : 문광복
-- 작성일     : 2015-09-01
-- 설명       : 메뉴관리 트리 목록
-- 예문       : EXEC CMN_MENU_TREE_GET 
--		DB2 변환 : 이전프로시져명 SP_MENU_MANAGEMENT_TREE_SELECT_MENU
--		프렌지 변환 : PTCMMBAS40L1 -> CMN_MENU_TREE_GET
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_MENU_TREE_GET()
	RESULT SETS 1
	LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH TREE (MENUID, PROGRAMID, PRTMENU, DISPLAYYN, IPYN, KO, EN, ZH, RU, SORTNO, MENUTYPE, LEV)  AS
		(
			SELECT M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, M.IPYN, L.KO, L.EN, L.ZH, L.RU, M.SORTNO, M.MENUTYPE, 1 AS LEV
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TYJINFWLIB.CMN_LANG L 
					ON M.MENUID = L.CODE
			WHERE COALESCE(PRTMENU,'') = ''
              AND M.DISPLAYYN = 'Y'

			UNION ALL

			SELECT M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, M.IPYN, L.KO, L.EN, L.ZH, L.RU, M.SORTNO, T.MENUTYPE, (LEV  +  1) AS LEV
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TREE T
					ON T.MENUID = M.PRTMENU
				INNER JOIN TYJINFWLIB.CMN_LANG L 
					ON M.MENUID = L.CODE
             WHERE M.DISPLAYYN = 'Y'
		)
		SELECT * FROM TREE
		ORDER BY  LEV, MENUTYPE, COALESCE(SORTNO, 9999);

	OPEN REFCURSOR;

END P1

