-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_MENU_LEFT_TREE_GET
-- 작성자     : 문광복
-- 작성일     : 2015-09-03
-- 설명       : 메뉴트리(좌측메뉴) 조회
-- 예문       : EXEC CMN_MENU_LEFT_TREE_GET 
--		DB2 변환 : 이전프로시져명 SP_TREE_SELECT_MENU_BYSUB
--		프렌지 변환 : PTCMMBAS40L4 -> CMN_MENU_LEFT_TREE_GET
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_MENU_LEFT_TREE_GET
(
	P_MENUID			VARCHAR(50),	-- 메뉴아이디
	P_EMPID				VARCHAR(20),
	P_COMPANYCODE		VARCHAR(10),
	P_LANGCODE			VARCHAR(2)
)
	
	RESULT SETS 1
	LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH TREE (MENUID, PROGRAMID, PRTMENU, DISPLAYYN, LEV, SORTNO) AS
		(
			SELECT	MENUID, PROGRAMID, PRTMENU, DISPLAYYN, 1 AS LEV, SORTNO
			FROM	TYJINFWLIB.CMN_MENU
			WHERE	COALESCE(PRTMENU, '') =  ''
					AND MENUID IN 
					(
						SELECT	ACL_ID 
						FROM	TYJINFWLIB.CMN_ACL 
						WHERE	ACL_TYPE='MENU' AND ACL_GRP IN 
						(
							SELECT	GRPID 
							FROM	TYJINFWLIB.ORG_GROUPUSR  AS G
							WHERE	(USRID = P_EMPID AND G.UsrType = '1')
						)
					)
					AND MENUID = P_MENUID
                    AND DISPLAYYN = 'Y'
			UNION ALL

			SELECT	M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, (LEV + 1) AS LEV, M.SORTNO
			FROM	TYJINFWLIB.CMN_MENU M
						INNER JOIN TREE T
							ON T.MENUID = M.PRTMENU
			WHERE M.MENUID IN 
				(
					SELECT	ACL_ID 
					FROM	TYJINFWLIB.CMN_ACL 
					WHERE	ACL_TYPE='MENU' AND ACL_GRP IN 
						(
							SELECT	GRPID 
							FROM	TYJINFWLIB.ORG_GROUPUSR  AS G
							WHERE	(USRID = P_EMPID AND G.UsrType = '1')
						)
				)
			
		)
/*
		SELECT	A.MENUID AS IDX, A.PROGRAMID, A.PRTMENU AS PRTIDX, C.KO AS TEXT, 1 AS LEV, B.PROGRAMPATH
		FROM	TYJINFWLIB.CMN_MENU A 
			LEFT JOIN TYJINFWLIB.CMN_PROGRAM B ON A.PROGRAMID = B.PROGRAMID
			LEFT JOIN TYJINFWLIB.CMN_LANG C ON C.PROGRAMID='MENU' AND A.MENUID=C.CODE
		WHERE	A.MENUID = P_MENUID
				AND A.MENUID IN 
				(
					SELECT	ACL_ID 
					FROM	TYJINFWLIB.CMN_ACL 
					WHERE	ACL_TYPE='MENU' AND ACL_GRP IN 
					(
						SELECT	GRPID 
						FROM	TYJINFWLIB.ORG_GROUPUSR  AS G
						WHERE	(USRID = P_EMPID AND COMPANYCODE = P_COMPANYCODE AND G.UsrType = '1')
						--OR		EXISTS(SELECT * FROM OrgChartNVH.dbo.tb_DeptMember AS D WHERE D.UserCompanyCode = P_COMPANYCODE AND D.EmpID = P_EMPID AND D.CompanyCode = G.Companycode AND D.DeptCode = G.UsrID AND G.UsrType = '2')
					)
				)

		UNION ALL
*/
		SELECT	A.MENUID AS IDX,A. PROGRAMID, A.PRTMENU AS PRTIDX, 
			CASE WHEN P_LANGCODE = 'en' THEN C.EN 
			ELSE C.KO END 
				AS TEXT, 
			A.LEV, B.PROGRAMPATH, B.POPUP, B.POPUP_SIZE
		FROM	TREE A 
			LEFT JOIN TYJINFWLIB.CMN_PROGRAM B ON A.PROGRAMID = B.PROGRAMID 
			LEFT JOIN TYJINFWLIB.CMN_LANG C ON C.PROGRAMID='MENU' AND A.MENUID=C.CODE
		WHERE DISPLAYYN = 'Y'
		ORDER BY LEV ASC, SORTNO ASC;
		-- WHERE,ORDER BY 추가 2016-11-21 장윤호

	OPEN REFCURSOR;

END P1

