--DROP PROCEDURE TYJINFWLIB.CMN_MENU_EIS_GET;
-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_MENU_EIS_GET
-- 작성자     : 문광복
-- 작성일     : 2017-04-05
-- 설명       : 경영정보 시스템 메뉴 조회
-- 예문       : EXEC CMN_MENU_EIS_GET ('SEOHAN')
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_MENU_EIS_GET
(
	P_COMPANYCODE		VARCHAR(10)
)
	
	RESULT SETS 1
	LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH TREE (MENUID, PROGRAMID, PRTMENU, DISPLAYYN, IPYN, KO, EN, ZH, RU, SORTNO, MENUTYPE, LEV)  AS
		(
			SELECT M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, M.IPYN, L.KO, L.EN, L.ZH, L.RU, M.SORTNO, M.MENUTYPE, 1 AS LEV
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TYJINFWLIB.CMN_LANG L 
					ON M.MENUID = L.CODE
			WHERE PRTMENU = 'EIS_' || RTRIM(P_COMPANYCODE)
              AND M.DISPLAYYN = 'Y'

			UNION ALL

			SELECT M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, M.IPYN, L.KO, L.EN, L.ZH, L.RU, M.SORTNO, T.MENUTYPE, (LEV  +  1) AS LEV
			FROM TYJINFWLIB.CMN_MENU M
				INNER JOIN TREE T
					ON T.MENUID = M.PRTMENU
				INNER JOIN TYJINFWLIB.CMN_LANG L 
					ON M.MENUID = L.CODE
             WHERE M.DISPLAYYN = 'Y'
		)
		SELECT A.*,B.PROGRAMPATH,B.POPUP,B.POPUP_SIZE FROM TREE A LEFT JOIN TYJINFWLIB.CMN_PROGRAM B ON (A.PROGRAMID = B.PROGRAMID)
		ORDER BY  LEV, MENUTYPE, COALESCE(SORTNO, 9999);

	OPEN REFCURSOR;

END P1

