-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_ACLGROUP_GET
-- 작성자     : 문광복
-- 작성일     : 2014-04-03
-- 설명       : 사용자의 권한유무를 조회한다.
-- 예문       : CALL CMN_ACLGROUP_GET ('','')
--      DB2 변환 : 이전프로시져명 CMN_ACLGROUP_GET
--		프렌지 변환 : PTCMMBAS10S1 -> CMN_ACL_GET_USER
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.CMN_ACLGROUP_GET
CREATE PROCEDURE TYJINFWLIB.CMN_ACLGROUP_GET
(
    P_PROGRAMID     VARCHAR(50),
    P_LANGCD		VARCHAR(10)
)
    RESULT SETS 2
    LANGUAGE SQL
M1: BEGIN
    DECLARE REFCURSOR CURSOR WITH RETURN FOR

		/* PROGRAM 명을 조회한다. */
		SELECT
				P_PROGRAMID AS PROGRAMID
			,	CASE P_LANGCD
					WHEN 'EN' THEN (CASE WHEN COALESCE(EN, '') = ''	THEN KO ELSE EN END)
					WHEN 'ZH' THEN (CASE WHEN COALESCE(ZH, '') = ''	THEN KO ELSE ZH END)
					WHEN 'RU' THEN (CASE WHEN COALESCE(RU, '') = ''	THEN KO ELSE RU END)
					ELSE KO
				END AS PROGRAMNM
			,	(	SELECT
							COUNT(*) AS GRP_CNT
					FROM
							TYJINFWLIB.CMN_ACL AS A
					WHERE
							A.ACL_ID		= L.CODE
				) AS GRP_CNT
			,	(	SELECT
							COUNT(DISTINCT E.EMPID)	AS EMP_CNT
					FROM
							TYJINFWLIB.CMN_ACL AS A
							INNER JOIN TYJINFWLIB.ORG_GROUP AS G
								ON	A.ACL_GRP		= G.GRPID
							INNER JOIN (SELECT
												DM.EMPID, GM.GRPID
										FROM
												TYJINFWLIB.ORG_GROUPUSR	AS GM
												INNER JOIN	TYJINFWLIB.ORG_DEPTUSR	AS DM
													ON	GM.COMPANYCODE		= DM.COMPANYCODE
													AND	GM.USRID			= DM.DEPTCODE
										WHERE
												GM.USRTYPE		= '2'

										UNION ALL
		
										SELECT
												UM.EMPID, GM.GRPID
										FROM
												TYJINFWLIB.ORG_GROUPUSR	AS GM
												INNER JOIN	TYJINFWLIB.ORG_USER	AS UM
													ON	GM.COMPANYCODE		= UM.COMPANYCODE
													AND	GM.USRID			= UM.EMPID
										WHERE
												GM.USRTYPE		= '1'
										) AS E
								ON	G.GRPID			= E.GRPID
					WHERE 
							A.ACL_TYPE		= 'MENU' 
					-- 권한 관리시 프로그램 아이디가 없는 메뉴에 권한을 추가하기 위해 수정. 문제시 원복 (2017-09-13 장윤호)
					--AND		A.ACL_ID		IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE PROGRAMID = P_PROGRAMID)
					AND		(
								A.ACL_ID	IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE PROGRAMID = P_PROGRAMID)
							OR	A.ACL_ID	= P_PROGRAMID
							)

				) AS EMP_CNT
		FROM 
				TYJINFWLIB.CMN_LANG AS L
		WHERE	
				PROGRAMID		= 'MENU'
		-- 권한 관리시 프로그램 아이디가 없는 메뉴에 권한을 추가하기 위해 수정. 문제시 원복 (2017-09-13 장윤호)
		--AND		CODE			IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE LOWER(PROGRAMID) = LOWER(P_PROGRAMID))
		AND		(
					CODE		IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE LOWER(PROGRAMID) = LOWER(P_PROGRAMID))
				OR	CODE		= P_PROGRAMID
				)
		;

	/* PROGRAM 설정되어 있는 권한 그룹을 조회한다. */
	DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
	WITH MST AS (
		SELECT
				G.GRPID
			,	CASE
					WHEN COALESCE(GL.GRPNAME, '') = ''
					THEN GLK.GRPNAME
					ELSE GL.GRPNAME
				END AS GRPNAME
			,	G.GRPEXT
			,	(	SELECT
							COUNT(*) AS UM_CNT
					FROM
							TYJINFWLIB.ORG_GROUPUSR	AS GM
							--INNER JOIN TYJINFWLIB.ORG_USER AS UM
							--	ON	GM.COMPANYCODE		= UM.SITECOMPANY
							--	AND	GM.USRID			= UM.EMPID
					WHERE
							GM.GRPID		= G.GRPID
					AND		GM.USRTYPE		= '1'
				) AS GM_CNT
			,	0 AS DM_CNT
			,	(	SELECT
							COUNT(*) AS UM_CNT
					FROM
							TYJINFWLIB.ORG_GROUPUSR	AS GM
							--INNER JOIN	TYJINFWLIB.ORG_USER	AS UM
							--	ON	GM.COMPANYCODE		= UM.SITECOMPANY
							--	AND	GM.USRID			= UM.EMPID
					WHERE
							GM.GRPID		= G.GRPID
					AND		GM.USRTYPE		= '1'
				) AS UM_CNT
			,	(	SELECT
							COUNT(EMPID) AS EX_CNT
					FROM
							TABLE(TYJINFWLIB.UF_GET_GRPEXTMEMBERS(COALESCE(G.GRPEXT,''))) AS GGS
					WHERE
							EMPID != ''				-- 2017-08-18 추가
				) AS EX_CNT
		FROM
				TYJINFWLIB.CMN_ACL AS A
				INNER JOIN	TYJINFWLIB.ORG_GROUP AS G
					ON	A.ACL_GRP			= G.GRPID
				LEFT OUTER JOIN	TYJINFWLIB.ORG_GROUPLANG AS GL
					ON	G.GRPID					= GL.GRPID
					AND	LOWER(GL.LANGCODE)		= P_LANGCD
				LEFT OUTER JOIN	TYJINFWLIB.ORG_GROUPLANG AS GLK
					ON	G.GRPID					= GLK.GRPID
					AND	LOWER(GLK.LANGCODE)		= 'ko'
		WHERE 
				A.ACL_TYPE		= 'MENU' 
		-- 권한 관리시 프로그램 아이디가 없는 메뉴에 권한을 추가하기 위해 수정. 문제시 원복 (2017-09-13 장윤호)
		--AND		A.ACL_ID		IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE LOWER(PROGRAMID) = LOWER(P_PROGRAMID))
		AND		(
					A.ACL_ID	IN (SELECT MENUID FROM TYJINFWLIB.CMN_PROGRAM WHERE LOWER(PROGRAMID) = LOWER(P_PROGRAMID))
				OR	A.ACL_ID	= P_PROGRAMID
				)
	)
	SELECT
			M.*
		, 	DM_CNT + UM_CNT + EX_CNT AS USR_CNT
	FROM
			MST AS M
	;
    OPEN REFCURSOR;
    OPEN REFCURSOR2;

END M1;