-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_SWITCH_LIST 
-- 작성자     : 김희섭
-- 작성일     : 2016-08-16
-- 설명       : 공콩코드 콤보 조회
-- 예문       : CALL TYJINFWLIB.CMN_SWITCH_LIST  ('SEOHAN','CMN0100106', 'IR08', 'KO)
-- DB2 변환   : 
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.CMN_SWITCH_LIST;
CREATE PROCEDURE TYJINFWLIB.CMN_SWITCH_LIST
(
    P_COMPANYCODE CHAR(10),
    P_LANGCODE    CHAR(2)
)

    RESULT SETS 1
    LANGUAGE SQL
    SPECIFIC TYJINFWLIB.CMN_SWITCH_LIST
    SET OPTION ALWCPYDTA = *OPTIMIZE ,
    DFTRDBCOL = TYJINFWLIB

M1: BEGIN
    DECLARE REFCURSOR CURSOR WITH RETURN FOR
    SELECT A.COMPANYCODE
         , B.COMPANY AS COMPANYNAME
         , COALESCE(C.CVYN,'') AS CVYN
      FROM TYJINFWLIB.ORG_COMPANY AS A
      LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS B
        ON A.COMPANYCODE = B.COMPANYCODE
       AND UPPER(B.LANGUAGECODE) = UPPER(P_LANGCODE)
      LEFT OUTER JOIN TYJINFWLIB.CMN_SWITCH AS C
        ON A.COMPANYCODE = C.COMPANYCODE
     WHERE A.COMPANYCODE         = CASE WHEN P_COMPANYCODE  = '' THEN A.COMPANYCODE ELSE P_COMPANYCODE END
     ORDER BY A.COMPANYCODE ASC;

    OPEN REFCURSOR;

END M1