--DROP PROCEDURE TYJINFWLIB.CMN_PROGRAM_GET;
-------------------------------------------------------------------------------------------
-- 프로시저명 : CMN_PROGRAM_GET
-- 작성자     : 문광복
-- 작성일     : 2014-04-03
-- 설명       : 현재 접속한 경로로 프로그램ID를 조회한다.
-- 예문       : CALL CMN_PROGRAM_GET ('2006909','1000','TS1301')
--		DB2 변환 : 이전프로시져명 UP_PROGRAM_SELECT_BYPATH
--		DB2 재변환 : 이전프로시져명 PTCMMBAS50S1
--		프렌지 변환 : PTCMMBAS50S1 -> CMN_PROGRAM_GET
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.CMN_PROGRAM_GET 
(
	P_PROGRAMPATH VARCHAR(2000),
	P_LANGCODE VARCHAR(10),
	P_MENUTYPE VARCHAR(10)
)
	RESULT SETS 2
	LANGUAGE SQL
P1: BEGIN 
	DECLARE P_MENUID VARCHAR(100);

	S1: BEGIN
		SELECT MENUID INTO P_MENUID
		FROM TYJINFWLIB.CMN_PROGRAM
		WHERE PROGRAMPATH LIKE '%' || P_PROGRAMPATH || '%' AND MENUTYPE = P_MENUTYPE
		FETCH FIRST 1 ROWS ONLY;
	END S1;

	S2: BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT * FROM TYJINFWLIB.CMN_PROGRAM
			WHERE PROGRAMPATH LIKE '%' || P_PROGRAMPATH || '%' AND MENUTYPE = P_MENUTYPE;
		OPEN REFCURSOR;
	END S2;

	S3: BEGIN
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
		WITH TREE (MENUID, PROGRAMID, PRTMENU, DISPLAYYN, LEV, SORTNO) AS
		(
			SELECT	MENUID, PROGRAMID, PRTMENU, DISPLAYYN, 1 AS LEV, SORTNO
			FROM	TYJINFWLIB.CMN_MENU
			WHERE	RTRIM(MENUID) =  P_MENUID
					
			UNION ALL

			SELECT	M.MENUID, M.PROGRAMID, M.PRTMENU, M.DISPLAYYN, (LEV + 1) AS LEV, M.SORTNO
			FROM	TYJINFWLIB.CMN_MENU M
						INNER JOIN TREE T
							ON T.PRTMENU = M.MENUID
			
			
		)
		SELECT A.* ,
			CASE WHEN P_LANGCODE = 'ko' THEN KO
				 WHEN P_LANGCODE = 'en' THEN EN
				 WHEN P_LANGCODE = 'zh' THEN ZH
				 WHEN P_LANGCODE = 'ru' THEN RU END AS MENUNAME
		FROM TREE A
			LEFT JOIN TYJINFWLIB.CMN_LANG B ON (A.MENUID = B.CODE AND B.PROGRAMID='MENU') ORDER BY LEV DESC FETCH FIRST 1 ROWS ONLY;
		OPEN REFCURSOR2;
	END S3;

END P1