-- 메뉴정보
-- TB_Menu
CREATE TABLE TYJINFWLIB.CMN_MENU
(
	  MENUID    CHAR (20) NOT NULL
	, PROGRAMID CHAR (50) 
	, PRTMENU   CHAR (20) 
	, DISPLAYYN CHAR (1)
	, SORTNO    INTEGER
	, MENUTYPE  CHAR (10) 
	, IPYN      CHAR (1) 
	, PRIMARY KEY (MENUID)
);

COMMENT ON TABLE TYJINFWLIB.CMN_MENU IS '공통-메뉴'; 

COMMENT ON COLUMN TYJINFWLIB.CMN_MENU
(
	MENUID IS '메뉴ID' , 
	PROGRAMID IS '프로그램ID' , 
	PRTMENU IS '상위메뉴ID' , 
	DISPLAYYN IS '사용여부' , 
	SORTNO IS '정렬순서' , 
	MENUTYPE IS '메뉴타입' , 
	IPYN IS '업체사용여부' 
); 

