-- 권한정보
-- TB_ACL
CREATE TABLE TYJINFWLIB.CMN_ACL
(
	  ACL_TYPE CHAR (10) NOT NULL
	, ACL_ID   CHAR (50) NOT NULL
	, ACL_GRP  CHAR (50) NOT NULL
	, COMPANYCODE CHAR(20) 
	, GRP_TYPE CHAR (1) 
	, MODIFY_FL CHAR (1) 
	, INQUARY_FL CHAR (1) 
	, PRINT_FL CHAR (1) 
	, EXCLUDE_FL CHAR (1) 
	, PRIMARY KEY (ACL_TYPE,ACL_GRP,ACL_ID)
);

COMMENT ON TABLE TYJINFWLIB.CMN_ACL IS '공통-권한관리'; 

COMMENT ON COLUMN TYJINFWLIB.CMN_ACL
(
	ACL_TYPE IS '권한관리타입' , 
	ACL_ID IS '권한관리ID' , 
	ACL_GRP IS '권한그룹',
	COMPANYCODE IS '회사코드',
	GRP_TYPE IS '권한타입',
	MODIFY_FL IS '',
	INQUARY_FL IS '',
	PRINT_FL IS '',
	EXCLUDE_FL IS ''
); 

