--DROP TABLE TYJINFWLIB.CMN_ATTACH;
-- 첨부파일정보
-- TB_ATTACH_FILE
CREATE TABLE TYJINFWLIB.CMN_ATTACH
(
	  ATTACH_TYPE CHAR (50) NOT NULL
	, ATTACH_NO   CHAR (50) NOT NULL
	, ATTACH_UNID CHAR (50) NOT NULL
	, FILE_NAME   VARGRAPHIC (500) ALLOCATE(100) CCSID 1200
	, FILE_SIZE   BIGINT
	, FILE_MIME   VARCHAR (150) 
	, FILE_EXT    VARCHAR (50) 
	, FILE_PATH   VARCHAR (4000) 
	, UPLOAD_PATH VARCHAR (100) 
	, PRIMARY KEY (ATTACH_TYPE,ATTACH_NO,ATTACH_UNID)
);

COMMENT ON TABLE TYJINFWLIB.CMN_ATTACH IS '공통-첨부파일'; 

COMMENT ON COLUMN TYJINFWLIB.CMN_ATTACH
(
	ATTACH_TYPE IS '첨부타입' , 
	ATTACH_NO IS '첨부번호' , 
	ATTACH_UNID IS '첨부ID' , 
	FILE_NAME IS '파일명' , 
	FILE_SIZE IS '파일Size' , 
	FILE_MIME IS 'Mime Type' , 
	FILE_EXT IS '파일확장자' , 
	FILE_PATH IS '첨부파일경로' , 
	UPLOAD_PATH IS '첨부파일 업로드 경로' 
); 




