--DROP TABLE TYJINFWLIB.CMN_CODE;
-- 공통코드
-- TB_GBLCOD
CREATE TABLE TYJINFWLIB.CMN_CODE
(
	  COMPANYCODE   CHAR (10)  NOT NULL
    , DCODE         CHAR(12)  NOT NULL
    , PCODE			CHAR (12) NOT NULL
	, CODE			CHAR (12) NOT NULL
	, SODR			INTEGER
    , CODTXT_KR		VARGRAPHIC (200) CCSID 1200 
	, CODTXT_EN		VARGRAPHIC (200) CCSID 1200  
	, CODTXT_ZH		VARGRAPHIC (200) CCSID 1200 
	, CODTXT_RU		VARGRAPHIC (200) CCSID 1200 
    , ERPCODE       VARCHAR (12)
	, CODEXT1		VARCHAR (50) 
	, CODEXT2		VARCHAR (50) 
	, CODEXT3		VARCHAR (50) 
	, CODEXTN1		INTEGER
	, CODEXTN2		INTEGER
	, CODEXTN3		INTEGER
	, USEYN			CHAR (1) 
	, REGID			VARCHAR (10) NOT NULL
	, REGDT			DATE NOT NULL
	, UPDID			VARCHAR (10) NOT NULL
	, UPDDT			DATE NOT NULL
	, PRIMARY KEY (COMPANYCODE,CODE)
);

COMMENT ON TABLE TYJINFWLIB.CMN_CODE IS '공통-코드마스터'; 

COMMENT ON COLUMN TYJINFWLIB.CMN_CODE
(
	COMPANYCODE IS '회사코드' , 
    DCODE IS '업무 구분' ,
    PCODE IS '상위코드ID' , 
	CODE IS '코드ID' , 
	SODR IS '정렬순서' , 
	CODTXT_KR IS '코드명(한글)' , 
	CODTXT_EN IS '코드명(영어)' , 
	CODTXT_ZH IS '코드명(중국어)' , 
	CODTXT_RU IS '코드명(러시아어)' , 
    ERPCODE IS 'ERP코드',
	CODEXT1 IS '확장코드1' , 
	CODEXT2 IS '확장코드2' , 
	CODEXT3 IS '확장코드3' , 
	CODEXTN1 IS '확장코드1(숫자)' , 
	CODEXTN2 IS '확장코드2(숫자)' , 
	CODEXTN3 IS '확장코드3(숫자)' , 
	USEYN IS '사용여부' , 
	REGID IS '등록자ID' , 
	REGDT IS '등록일자' , 
	UPDID IS '수정자ID' , 
	UPDDT IS '수정일자' 
); 
