--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_LIST;
  
 
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_LIST(
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_DATE VARCHAR(6) , 
	IN P_HWAJU VARCHAR(50)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSS_CSS2020_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER;
	DECLARE P_FNNUM INTEGER;
	DECLARE P_SQLSTRING VARCHAR(4000);
	DECLARE P_SQLTOTALROWCOUNT VARCHAR(4000);
	DECLARE P_TABLE_QUERY			VARCHAR(5000);
	DECLARE P_COUNT_QUERY			VARCHAR(5000);
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM =(P_PAGESIZE *(P_CURRENTPAGEINDEX - 1)) + 1;
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX;
	END PREV;
  
	MAIN : BEGIN  -- 실행부      
	LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR 

				WITH ORIGINAL_DATA AS 
				( 
					SELECT
					HYMCYYMM,
					HYYYMMDD,
					HYHANGCHA,
					HYGOKJONG,
					HYHWAJU,
					VSCODE.CDDESC1 AS VSDESC1,
					GKCODE.CDDESC1 AS GKDESC1,
					SUM(HYHWAKQTY) AS HYHWAKQTY,
					SUM(HYCHQTY) AS HYCHQTY,
					SUM(HYYDQTY) AS HYYDQTY,
					SUM(HYHAYKAMT + HYHAYKVAT) AS TOTAL,
					SUM(HYHAYKAMT) AS GONGHAP,
					SUM(HYHAYKVAT) AS VATHAP
					FROM TYSCMLIB.USIMCHYF 
					LEFT OUTER JOIN TYSCMLIB.USICODEF VSCODE 
					ON        'VS' = VSCODE.CDINDEX 
					AND  HYHANGCHA = VSCODE.CDCODE 
					LEFT OUTER JOIN TYSCMLIB.USICODEF GKCODE 
					ON        'GK' = GKCODE.CDINDEX 
					AND  HYGOKJONG = GKCODE.CDCODE 
					WHERE HYMCYYMM = P_DATE 
					AND   HYHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_REVCOLROW(CAST(P_HWAJU AS VARCHAR(100)),',')) AS INTABLE) 
					GROUP BY HYMCYYMM, HYHANGCHA, HYGOKJONG, HYYYMMDD, HYHWAJU, VSCODE.CDDESC1, GKCODE.CDDESC1
					ORDER BY HYHANGCHA 
				),

				DETAIL AS
				(
					SELECT
					ROW_NUMBER() OVER(ORDER BY HYYYMMDD, HYHANGCHA, HLDATE) AS ROWNO,
					HYMCYYMM,
					HYYYMMDD,
					HYHANGCHA,
					HYGOKJONG,
					HYHWAJU,
					VSDESC1,
					GKDESC1,
					GONGHAP,
					VATHAP,
					TOTAL,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN SUBSTR(CHAR(HYIL.HLDATE),1,4)||'/'||SUBSTR(CHAR(HYIL.HLDATE),5,2) ||'/'||SUBSTR(CHAR(HYIL.HLDATE),7,2)
					      ELSE  SUBSTR(CHAR(HYYYMMDD),1,4)||'/'||SUBSTR(CHAR(HYYYMMDD),5,2) ||'/'||SUBSTR(CHAR(HYYYMMDD),7,2) END) AS CHDAT,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN COALESCE((HYIL.HLCHQTY+HYIL.HLYDQTY),0)
					      ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN COALESCE((HYCHQTY+HYYDQTY),0)
					                 ELSE HYHWAKQTY END)
				              END) AS CHQTY,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN (CASE WHEN HLYDQTY <> 0 THEN '양도분' ELSE '' END) ELSE '입고' END)
					      ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN (CASE WHEN HYYDQTY <> 0 THEN '양도분' ELSE '' END) ELSE '입고' END) END) AS CHBIGO	
					FROM ORIGINAL_DATA
					LEFT OUTER JOIN TYSCMLIB.USIMCHYILF HYIL
					ON     HYMCYYMM  = HYIL.HLMCYYMM
					AND    HYHANGCHA = HYIL.HLHANGCHA
					AND    HYGOKJONG = HYIL.HLGOKJONG
					AND    HYHWAJU   = HYIL.HLHWAJU
					AND    HYYYMMDD  = HYIL.HLYYMMDD
				)

				SELECT
				ROWNO,
				HYMCYYMM,
				HYYYMMDD,
				HYHANGCHA,
				HYGOKJONG,
				HYHWAJU,
				VSDESC1,
				GKDESC1,
				GONGHAP,
				VATHAP,
				TOTAL,
				CHDAT,
				TRIM(TO_CHAR(CHQTY, '9,999,990.000')) AS CHQTY,
				CHBIGO
				FROM DETAIL
				WHERE ROWNO BETWEEN CAST(P_STNUM AS VARCHAR(100)) AND CAST(P_FNNUM AS VARCHAR(100));
			 
			OPEN REFCURSOR;
  
		END LIST;
	 
		PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
				 
				WITH ORIGINAL_DATA AS 
				( 
					SELECT
					HYMCYYMM,
					HYYYMMDD,
					HYHANGCHA,
					HYGOKJONG,
					HYHWAJU,
					VSCODE.CDDESC1 AS VSDESC1,
					GKCODE.CDDESC1 AS GKDESC1,
					SUM(HYHWAKQTY) AS HYHWAKQTY,
					SUM(HYCHQTY) AS HYCHQTY,
					SUM(HYYDQTY) AS HYYDQTY,
					SUM(HYHAYKAMT + HYHAYKVAT) AS TOTAL,
					SUM(HYHAYKAMT) AS GONGHAP,
					SUM(HYHAYKVAT) AS VATHAP
					FROM TYSCMLIB.USIMCHYF 
					LEFT OUTER JOIN TYSCMLIB.USICODEF VSCODE 
					ON        'VS' = VSCODE.CDINDEX 
					AND  HYHANGCHA = VSCODE.CDCODE 
					LEFT OUTER JOIN TYSCMLIB.USICODEF GKCODE 
					ON        'GK' = GKCODE.CDINDEX 
					AND  HYGOKJONG = GKCODE.CDCODE 
					WHERE HYMCYYMM = 202101 
					AND   HYHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_REVCOLROW(CAST('K04' AS VARCHAR(100)),',')) AS INTABLE) 
					GROUP BY HYMCYYMM, HYHANGCHA, HYGOKJONG, HYYYMMDD, HYHWAJU, VSCODE.CDDESC1, GKCODE.CDDESC1
					ORDER BY HYHANGCHA 
				),

				DETAIL AS
				(
					SELECT
					ROW_NUMBER() OVER(ORDER BY HYYYMMDD, HYHANGCHA, HLDATE) AS ROWNO,
					HYMCYYMM,
					HYYYMMDD,
					HYHANGCHA,
					HYGOKJONG,
					HYHWAJU,
					VSDESC1,
					GKDESC1,
					GONGHAP,
					VATHAP,
					TOTAL,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN SUBSTR(CHAR(HYIL.HLDATE),1,4)||'/'||SUBSTR(CHAR(HYIL.HLDATE),5,2) ||'/'||SUBSTR(CHAR(HYIL.HLDATE),7,2)
					      ELSE  SUBSTR(CHAR(HYYYMMDD),1,4)||'/'||SUBSTR(CHAR(HYYYMMDD),5,2) ||'/'||SUBSTR(CHAR(HYYYMMDD),7,2) END) AS CHDAT,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN COALESCE((HYIL.HLCHQTY+HYIL.HLYDQTY),0)
					      ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN COALESCE((HYCHQTY+HYYDQTY),0)
					                 ELSE HYHWAKQTY END)
				              END) AS CHQTY,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN (CASE WHEN HLYDQTY <> 0 THEN '양도분' ELSE '' END) ELSE '입고' END)
					      ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN (CASE WHEN HYYDQTY <> 0 THEN '양도분' ELSE '' END) ELSE '입고' END) END) AS CHBIGO	
					FROM ORIGINAL_DATA
					LEFT OUTER JOIN TYSCMLIB.USIMCHYILF HYIL
					ON     HYMCYYMM  = HYIL.HLMCYYMM
					AND    HYHANGCHA = HYIL.HLHANGCHA
					AND    HYGOKJONG = HYIL.HLGOKJONG
					AND    HYHWAJU   = HYIL.HLHWAJU
					AND    HYYYMMDD  = HYIL.HLYYMMDD
				)
				 
				SELECT 
				COUNT(*) AS TOTALCOUNT 
				FROM DETAIL;
  
			OPEN REFCURSOR2;
  
		END PAGING;
  
	END MAIN;
END P1 ;
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_LIST 
TO KSGPDM WITH GRANT OPTION;



CALL TYJINFWLIB.SP_TYCSS_CSS2020_LIST(1, 15, 202101, 'K04');