--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1030_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1030_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE   VARCHAR(8),
	IN P_EDATE   VARCHAR(8),
        IN P_HWAJU   VARCHAR(50)) 

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부      

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS
				(
					SELECT
					ROW_NUMBER() OVER(ORDER BY IHHANGCHA, IPGOKJONG) AS ROWNO,
					IHHANGCHA,
					VSDESC1,
					IPGOKJONG,
					GKDESC1,
					SKDESC1,
					WNDESC1,
					IHIPHANG,
					IHJAKENDAT,
					IPIPSTDAT,
					IHJUKHANO,
					JBBEJNQTY,
					JBHWAKQTY,
					GAMQTY
					FROM
					(
						SELECT
						DISTINCT
						IPHA.IHHANGCHA,
						VSCODE.CDDESC1 AS VSDESC1,
						IPGO.IPGOKJONG,
						GKCODE.CDDESC1 AS GKDESC1,
						SKCODE.CDDESC1 AS SKDESC1,
						WNCODE.CDDESC1 AS WNDESC1,
						IHIPHANG,
						IHJAKENDAT,
						IPIPSTDAT,
						IHJUKHANO,
						(JBBEJNQTY + JBBEIPQTY - JBBECHQTY) AS JBBEJNQTY,
						(JBHWAKQTY + JBHWIPQTY - JBHWCHQTY) AS JBHWAKQTY,
						((JBBEJNQTY + JBBEIPQTY - JBBECHQTY) - (JBHWAKQTY + JBHWIPQTY - JBHWCHQTY)) AS GAMQTY
						FROM TYSCMLIB.USIIPHAF AS IPHA
						LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO
						ON         IPHA.IHHANGCHA = IPGO.IPHANGCHA
						LEFT OUTER JOIN TYSCMLIB.USIJEBLF AS JEBL
						ON         IPGO.IPHANGCHA = JEBL.JBHANGCHA
						AND        IPGO.IPGOKJONG = JEBL.JBGOKJONG
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE
						ON                   'VS' = VSCODE.CDINDEX
						AND        IPHA.IHHANGCHA = VSCODE.CDCODE
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE
						ON                   'GK' = GKCODE.CDINDEX
						AND        IPGO.IPGOKJONG = GKCODE.CDCODE
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE
						ON                   'SK' = SKCODE.CDINDEX
						AND        IPHA.IHSOSOK   = SKCODE.CDCODE
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS WNCODE
						ON                   'WN' = WNCODE.CDINDEX
						AND        IPHA.IHWONSAN1 = WNCODE.CDCODE
						WHERE SUBSTR(CHAR(IPHA.IHIPHANG),1,6)  BETWEEN P_SDATE AND P_EDATE
						AND   JEBL.JBHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						AND   (JEBL.JBBEJNQTY + JEBL.JBBEIPQTY - JEBL.JBBECHQTY) <> 0
						AND   (JEBL.JBHWAKQTY + JEBL.JBHWIPQTY - JEBL.JBHWCHQTY) <> 0
					) AS TEMP
				)

				SELECT
				ROWNO,
				IHHANGCHA,
				VSDESC1,
				IPGOKJONG,
				GKDESC1,
				SKDESC1,
				WNDESC1,
				IHIPHANG,
				IHJAKENDAT,
				IPIPSTDAT,
				IHJUKHANO,
				TRIM(TO_CHAR(JBBEJNQTY, '9,999,990.000')) AS JBBEJNQTY,
				TRIM(TO_CHAR(JBHWAKQTY, '9,999,990.000')) AS JBHWAKQTY,
				TRIM(TO_CHAR(GAMQTY, '9,999,990.000')) AS GAMQTY
				FROM ORIGINAL_DATA AS A
				WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) )AND CAST ( P_FNNUM AS VARCHAR ( 100 ) )
				ORDER BY ROWNO;

			OPEN REFCURSOR;

		END LIST;

		PAGING : BEGIN  -- 페이징 

			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR

				SELECT
				COUNT(*) AS TOTALCOUNT
				FROM
				(
					SELECT
					DISTINCT
					IHHANGCHA,
					IPGOKJONG
					FROM TYSCMLIB.USIIPHAF AS IPHA
					LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO
					ON         IPHA.IHHANGCHA = IPGO.IPHANGCHA
					LEFT OUTER JOIN TYSCMLIB.USIJEBLF AS JEBL
					ON         IPGO.IPHANGCHA = JEBL.JBHANGCHA
					AND        IPGO.IPGOKJONG = JEBL.JBGOKJONG
					WHERE SUBSTR(CHAR(IPHA.IHIPHANG),1,6)  BETWEEN P_SDATE AND P_EDATE
					AND   JEBL.JBHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
					AND   (JEBL.JBBEJNQTY + JEBL.JBBEIPQTY - JEBL.JBBECHQTY) <> 0
					AND   (JEBL.JBHWAKQTY + JEBL.JBHWIPQTY - JEBL.JBHWCHQTY) <> 0
				) AS TEMP;

			OPEN REFCURSOR2;

		END PAGING;

	END MAIN;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1030_LIST(1, 15, 20200101, 20210430, 'S70');