--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1010_PRINT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1010_PRINT ( 
    IN P_SDATE   VARCHAR(8),
	IN P_EDATE   VARCHAR(8),
	IN P_HWAJU   VARCHAR(30))

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 

	DECLARE V_DATE VARCHAR(30);
  
	PRINT : BEGIN  -- 출력

		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT                   
			IHHANGCHA,               
			VSDESC1,                 
			IHIPHANG,                
			GKDESC1,                 
			SKDESC1,                 
			IHBLQTY1,                
			IPIPDAT,                 
			SUM(IPIPQTY) AS IPIPQTY  
			FROM                     
			(                        
				SELECT                                         
				IHHANGCHA,                                     
				VSCODE.CDDESC1 AS VSDESC1,                     
				IHIPHANG,                                      
				GKCODE.CDDESC1 AS GKDESC1,                     
				SKCODE.CDDESC1 AS SKDESC1,                     
				IHBLQTY1,                                      
				IPIPDAT1 AS IPIPDAT,                           
				IPIPPQTY1 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA                
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX       
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE        
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX       
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE        
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX       
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE        
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO     
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA       
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG       
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))

				AND   IPIPPQTY1 <> 0                           
				UNION ALL                                      
				SELECT                                         
				IHHANGCHA,                                     
				VSCODE.CDDESC1 AS VSDESC1,                     
				IHIPHANG,                                      
				GKCODE.CDDESC1 AS GKDESC1,                     
				SKCODE.CDDESC1 AS SKDESC1,                     
				IHBLQTY1,									   
				IPIPDAT2 AS IPIPDAT,						   
				IPIPPQTY2 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY2 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT3 AS IPIPDAT,						   
				IPIPPQTY3 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY3 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT4 AS IPIPDAT,						   
				IPIPPQTY4 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY4 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT5 AS IPIPDAT,						   
				IPIPPQTY5 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY5 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT6 AS IPIPDAT,						   
				IPIPPQTY6 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY6 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT7 AS IPIPDAT,						   
				IPIPPQTY7 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY7 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT8 AS IPIPDAT,						   
				IPIPPQTY8 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY8 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT9 AS IPIPDAT,						   
				IPIPPQTY9 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY9 <> 0                           
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIPDAT10 AS IPIPDAT,                          
				IPIPPQTY10 AS IPIPQTY                   
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIPPQTY10 <> 0                          
				UNION ALL                                      
				SELECT                                         
				IHHANGCHA,                                     
				VSCODE.CDDESC1 AS VSDESC1,                     
				IHIPHANG,                                      
				GKCODE.CDDESC1 AS GKDESC1,                     
				SKCODE.CDDESC1 AS SKDESC1,                     
				IHBLQTY1,                                      
				IPIDDAT1 AS IPIPDAT,                           
				IPIDQTY1 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA                
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX       
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE        
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX       
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE        
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX       
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE        
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO     
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA       
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG       
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY1 <> 0                            
				UNION ALL                                      
				SELECT                                         
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT2 AS IPIPDAT,						   
				IPIDQTY2 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY2 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT3 AS IPIPDAT,						   
				IPIDQTY3 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY3 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT4 AS IPIPDAT,						   
				IPIDQTY4 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY4 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT5 AS IPIPDAT,						   
				IPIDQTY5 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY5 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT6 AS IPIPDAT,						   
				IPIDQTY6 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY6 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT7 AS IPIPDAT,						   
				IPIDQTY7 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY7 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT8 AS IPIPDAT,						   
				IPIDQTY8 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY8 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT9 AS IPIPDAT,						   
				IPIDQTY9 AS IPIPQTY                     
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY9 <> 0                            
				UNION ALL									   
				SELECT										   
				IHHANGCHA,									   
				VSCODE.CDDESC1 AS VSDESC1,					   
				IHIPHANG,									   
				GKCODE.CDDESC1 AS GKDESC1,					   
				SKCODE.CDDESC1 AS SKDESC1,					   
				IHBLQTY1,									   
				IPIDDAT10 AS IPIPDAT,                          
				IPIDQTY10 AS IPIPQTY                    
				FROM TYSCMLIB.USIIPHAF AS IPHA				   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE   
				ON                 'VS' = VSCODE.CDINDEX	   
				AND      IPHA.IHHANGCHA = VSCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE   
				ON                 'GK' = GKCODE.CDINDEX	   
				AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE   
				ON                 'SK' = SKCODE.CDINDEX	   
				AND     IPHA.IHSOSOK    = SKCODE.CDCODE		   
				LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO	   
				ON      IPHA.IHHANGCHA  = IPGO.IPHANGCHA	   
				AND     IPHA.IHGOKJONG1 = IPGO.IPGOKJONG	   
				WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
				AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
				AND   IPIDQTY10 <> 0                           
			) AS TEMP                                      
			GROUP BY IHHANGCHA, VSDESC1, IHIPHANG, GKDESC1, SKDESC1, IHBLQTY1, IPIPDAT
			ORDER BY IHHANGCHA, IPIPDAT;

		OPEN REFCURSOR;

	END PRINT;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1010_PRINT('20210101', '20210430', 'S70');