--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_DETAIL;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_DETAIL ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE         INTEGER , 
	IN P_HYMCYYMM         VARCHAR(6),
	IN P_HYYYMMDD         VARCHAR(8),
	IN P_HYHANGCHA        VARCHAR(6),
	IN P_HYGOKJONG        VARCHAR(2),
	IN P_HWAJU            VARCHAR(50))

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부      

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS
				(
					SELECT
					ROW_NUMBER() OVER() AS ROWNO,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN SUBSTR(CHAR(HYIL.HLDATE),1,4)||'/'||SUBSTR(CHAR(HYIL.HLDATE),5,2) ||'/'||SUBSTR(CHAR(HYIL.HLDATE),7,2)
					      ELSE  SUBSTR(CHAR(HYYYMMDD),1,4)||'/'||SUBSTR(CHAR(HYYYMMDD),5,2) ||'/'||SUBSTR(CHAR(HYYYMMDD),7,2) END) AS CHDAT,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN COALESCE((HYIL.HLCHQTY+HYIL.HLYDQTY),0)
					      ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN COALESCE((HYCHQTY+HYYDQTY),0)
					                 ELSE HYHWAKQTY END)
					      END) AS CHQTY,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN (CASE WHEN HLYDQTY <> 0 THEN '양도분' ELSE '' END) ELSE '입고' END)
						 ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN (CASE WHEN HYYDQTY <> 0 THEN '양도분' ELSE '' END) ELSE '입고' END) END) AS CHBIGO
					FROM TYSCMLIB.USIMCHYF
					LEFT OUTER JOIN TYSCMLIB.USIMCHYILF HYIL
					ON  HYIL.HLMCYYMM  = HYMCYYMM
					AND HYIL.HLHANGCHA = HYHANGCHA
					AND HYIL.HLGOKJONG = HYGOKJONG
					AND HYIL.HLHWAJU   = HYHWAJU
					AND HYIL.HLYYMMDD  = HYYYMMDD
					WHERE HYMCYYMM  = P_HYMCYYMM
					AND   HYYYMMDD  = P_HYYYMMDD
					AND   HYHANGCHA = P_HYHANGCHA
					AND   HYGOKJONG = P_HYGOKJONG
					AND   HYHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(50)), ',')) AS InTable )
					ORDER BY HYYYMMDD, HLDATE
				)

				SELECT
				ROWNO,
				CHDAT,
				CHQTY,
				CHBIGO
				FROM ORIGINAL_DATA
				WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) )AND CAST ( P_FNNUM AS VARCHAR ( 100 ) );
			
			OPEN REFCURSOR;

		END LIST;
	  
		PAGING : BEGIN  -- 페이징 
			
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
				
				WITH ORIGINAL_DATA AS
				(
					SELECT
					ROW_NUMBER() OVER() AS ROWNO,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN SUBSTR(CHAR(HYIL.HLDATE),1,4)||'/'||SUBSTR(CHAR(HYIL.HLDATE),5,2) ||'/'||SUBSTR(CHAR(HYIL.HLDATE),7,2)
					      ELSE  SUBSTR(CHAR(HYYYMMDD),1,4)||'/'||SUBSTR(CHAR(HYYYMMDD),5,2) ||'/'||SUBSTR(CHAR(HYYYMMDD),7,2) END) AS CHDAT,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN COALESCE((HYIL.HLCHQTY+HYIL.HLYDQTY),0)
					      ELSE (CASE WHEN HYCHQTY+HYYDQTY <> 0 THEN COALESCE((HYCHQTY+HYYDQTY),0)
					                 ELSE HYHWAKQTY END)
					      END) AS CHQTY,
					(CASE WHEN (HYIL.HLMCYYMM IS NOT NULL OR HYIL.HLMCYYMM <> 0) THEN (CASE WHEN HLYDQTY <> 0 THEN '양도분' ELSE '' END)
						 ELSE (CASE WHEN HYYDQTY <> 0 THEN '양도분' ELSE '' END) END) AS CHBIGO
					FROM TYSCMLIB.USIMCHYF
					LEFT OUTER JOIN TYSCMLIB.USIMCHYILF HYIL
					ON  HYIL.HLMCYYMM  = HYMCYYMM
					AND HYIL.HLHANGCHA = HYHANGCHA
					AND HYIL.HLGOKJONG = HYGOKJONG
					AND HYIL.HLHWAJU   = HYHWAJU
					AND HYIL.HLYYMMDD  = HYYYMMDD
					WHERE HYMCYYMM  = P_HYMCYYMM
					AND   HYYYMMDD  = P_HYYYMMDD
					AND   HYHANGCHA = P_HYHANGCHA
					AND   HYGOKJONG = P_HYGOKJONG
					AND   HYHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(50)), ',')) AS InTable )
					ORDER BY HYYYMMDD, HLDATE
				)

				SELECT
				COUNT(*) AS TOTALCOUNT
				FROM ORIGINAL_DATA;

			OPEN REFCURSOR2;

		END PAGING;

	END MAIN;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS2020_DETAIL(1, 15, '202104', '20210406', '202117', '12','C02');