DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1090_LIST;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1090_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE VARCHAR(8) , 
	IN P_EDATE VARCHAR(8) , 
	IN P_HWAJU VARCHAR(50) , 
	IN P_YSGUBUN VARCHAR(1) , 
	IN P_GUBUN VARCHAR(1) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSS_CSS1090_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부 
		IF P_GUBUN = 'S' AND P_YSGUBUN = '' THEN 
  
			LIST1 : BEGIN  -- 리스트 
				DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						CAST ( P_SDATE AS CHAR ( 8 ) ) AS IN_STDATE , 
						CAST ( P_EDATE AS CHAR ( 8 ) ) AS IN_EDDATE 
						FROM SYSIBM . SYSDUMMY1 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) 
  
					SELECT 
					* 
					FROM 
					( 
						SELECT 
						ROW_NUMBER ( ) OVER ( ORDER BY TMHANGCHA , TMGOKJONG , TMBLNO , TMHMNO1 , TMHMNO2 , TMCUSTIL , TMSEQ , TMGUBUN , TMYSDATE ) AS ROWNO , 
						TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						TMBLNO , 
						( TRIM ( CHAR ( TMHMNO1 ) ) || '-' || TRIM ( CHAR ( TMHMNO2 ) ) ) AS TMHMN , 
						TMCUSTIL , 
						TMSEQ , 
						( CASE WHEN TMGUBUN = '2' THEN '양수' 
						WHEN TMGUBUN = '1' THEN '양도' END ) AS TMGUBUN , 
						TMYSDATE , 
						YSCODE . CDDESC1 AS YSDESC1 , 
						TRIM(TO_CHAR(TMYSQTY, '9,999,990.000')) AS TMYSQTY 
						FROM DETAIL AS TMED 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS YSCODE 
						ON 'HJ' = YSCODE . CDINDEX 
						AND TMED . TMYSHWAJU = YSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND TMED . TMHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND TMED . TMGOKJONG = GKCODE . CDCODE 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE TMHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) AS TEMP 
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) ;					 
  
				OPEN REFCURSOR ; 
			 
			END LIST1 ; 
  
			PAGING1 : BEGIN  -- 페이징 
				DECLARE REFCURSOR3 CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						CAST ( P_SDATE AS CHAR ( 8 ) ) AS IN_STDATE , 
						CAST ( P_EDATE AS CHAR ( 8 ) ) AS IN_EDDATE 
						FROM SYSIBM . SYSDUMMY1 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) 
					 
					SELECT 
					COUNT ( * ) AS TOTALCOUNT 
					FROM DETAIL 
					INNER JOIN MAST 
					ON 1 = 1 
					WHERE TMHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ; 
  
				OPEN REFCURSOR3 ; 
  
			END PAGING1 ; 
  
		ELSEIF P_GUBUN = 'S' AND P_YSGUBUN <> '' THEN 
  
			LIST7 : BEGIN  -- 리스트 
				DECLARE REFCURSOR7 CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						CAST ( P_SDATE AS CHAR ( 8 ) ) AS IN_STDATE , 
						CAST ( P_EDATE AS CHAR ( 8 ) ) AS IN_EDDATE , 
						CAST ( P_YSGUBUN AS VARCHAR ( 1 ) ) AS IN_GUBUN 
						FROM SYSIBM . SYSDUMMY1 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						'D' AS DISPLAY , 
						'D' AS GUBUN , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'D' AS DISPLAY , 
						'D' AS GUBUN , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					HAP AS 
					( 
						SELECT 
						'D' AS DISPLAY , 
						'H' AS GUBUN , 
						TMHWAJU , 
						TMHANGCHA AS TMHANGCHA , 
						'소 계' AS TMGOKJONG , 
						'' AS TMBLNO , 
						'' AS TMHMNO1 , 
						'' AS TMHMNO2 , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS TMYSHWAJU , 
						SUM ( TMYSQTY ) AS TMYSQTY 
						FROM DETAIL 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE TRIM ( TMGUBUN ) = TRIM ( P_YSGUBUN ) 
						GROUP BY GROUPING SETS ( ( TMHANGCHA , TMHWAJU ) ) 
  
						UNION ALL 
  
						SELECT 
						'T' AS DISPLAY ,	 
						'H' AS GUBUN , 
						'' AS TMHWAJU , 
						'' AS TMHANGCHA , 
						'총 계' AS TMGOKJONG , 
						'' AS TMBLNO , 
						'' AS TMHMNO1 , 
						'' AS TMHMNO2 , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS TMYSHWAJU , 
						SUM ( TMYSQTY ) AS TMYSQTY 
						FROM DETAIL 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE TRIM ( TMGUBUN ) = TRIM ( P_YSGUBUN ) 
					) 
					 
					SELECT 
					* 
					FROM 
					( 
						SELECT 
						ROW_NUMBER ( ) OVER ( ORDER BY DISPLAY , ( CASE WHEN TMHANGCHA <> '' THEN TMHANGCHA || DISPLAY || GUBUN ELSE DISPLAY || GUBUN || TMHANGCHA END ) , TMBLNO , TMHMN , TMCUSTIL , TMSEQ , TMGUBUN , TMYSDATE ) AS ROWNO , 
						DISPLAY , 
						GUBUN , 
						TMHANGCHA , 
						VSDESC1 , 
						( CASE WHEN ( DISPLAY = 'D' AND GUBUN = 'H' ) THEN '<div style="color:blue" >소   계</div>' 
						WHEN DISPLAY = 'T' THEN '<div style="color:red" >총   계</div>' 
						ELSE GKDESC1 END ) AS GKDESC1 , 
						TMBLNO , 
						TMHMN , 
						TMCUSTIL , 
						TMSEQ , 
						TMGUBUN , 
						TMYSDATE , 
						YSDESC1 , 
						( CASE WHEN ( DISPLAY = 'D' AND GUBUN = 'H' ) THEN '<div style="color:blue" >' || TRIM ( TO_CHAR ( TMYSQTY , '9,999,990.000' ) ) || '</div>' 
						WHEN DISPLAY = 'T' THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( TMYSQTY , '9,999,990.000' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( TMYSQTY , '9,999,990.000' ) ) END ) AS TMYSQTY					 
						FROM 
						( 
							SELECT 
							DISPLAY , 
							GUBUN , 
							TMHANGCHA , 
							VSCODE . CDDESC1 AS VSDESC1 , 
							GKCODE . CDDESC1 AS GKDESC1 , 
							TMBLNO , 
							( TRIM ( CHAR ( TMHMNO1 ) ) || '-' || TRIM ( CHAR ( TMHMNO2 ) ) ) AS TMHMN , 
							DIGITS ( TMCUSTIL ) AS TMCUSTIL , 
							DIGITS ( TMSEQ ) AS TMSEQ , 
							( CASE WHEN TMGUBUN = '2' THEN '양수' 
							WHEN TMGUBUN = '1' THEN '양도' END ) AS TMGUBUN , 
							DIGITS ( TMYSDATE ) AS TMYSDATE , 
							YSCODE . CDDESC1 AS YSDESC1 , 
							TMYSQTY 
							FROM DETAIL AS TMED 
							LEFT OUTER JOIN TYSCMLIB . USICODEF AS YSCODE 
							ON 'HJ' = YSCODE . CDINDEX 
							AND TMED . TMYSHWAJU = YSCODE . CDCODE 
							LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
							ON 'VS' = VSCODE . CDINDEX 
							AND TMED . TMHANGCHA = VSCODE . CDCODE 
							LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
							ON 'GK' = GKCODE . CDINDEX 
							AND TMED . TMGOKJONG = GKCODE . CDCODE 
							INNER JOIN MAST 
							ON 1 = 1 
							WHERE TRIM ( TMGUBUN ) = TRIM ( P_YSGUBUN ) 
	 
							UNION ALL 
	 
							SELECT 
							DISPLAY , 
							GUBUN , 
							TMHANGCHA , 
							VSCODE . CDDESC1 AS VSDESC1 , 
							'' AS GKDESC1 , 
							'' AS TMBLNO , 
							'' AS TMHMN , 
							'' AS TMCUSTIL , 
							'' AS TMSEQ , 
							'' AS TMGUBUN , 
							'' AS TMYSDATE , 
							'' AS YSDESC1 , 
							TMYSQTY 
							FROM HAP AS TMED 
							LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
							ON 'VS' = VSCODE . CDINDEX 
							AND TMED . TMHANGCHA = VSCODE . CDCODE 
						) AS TEMP 
					) AS TEMP1 
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) ; 
  
				OPEN REFCURSOR7 ; 
			 
			END LIST7 ; 
  
			PAGING7 : BEGIN  -- 페이징 
				DECLARE REFCURSOR37 CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						CAST ( P_SDATE AS CHAR ( 8 ) ) AS IN_STDATE , 
						CAST ( P_EDATE AS CHAR ( 8 ) ) AS IN_EDDATE , 
						CAST ( P_YSGUBUN AS VARCHAR ( 1 ) ) AS IN_GUBUN 
						FROM SYSIBM . SYSDUMMY1 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						'D' AS DISPLAY , 
						'D' AS GUBUN , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'D' AS DISPLAY , 
						'D' AS GUBUN , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					HAP AS 
					( 
						SELECT 
						'D' AS DISPLAY , 
						'H' AS GUBUN , 
						TMHWAJU , 
						TMHANGCHA AS TMHANGCHA , 
						'소 계' AS TMGOKJONG , 
						'' AS TMBLNO , 
						'' AS TMHMNO1 , 
						'' AS TMHMNO2 , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS TMYSHWAJU , 
						SUM ( TMYSQTY ) AS TMYSQTY 
						FROM DETAIL 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE TRIM ( TMGUBUN ) = TRIM ( P_YSGUBUN ) 
						GROUP BY GROUPING SETS ( ( TMHANGCHA , TMHWAJU ) ) 
  
						UNION ALL 
  
						SELECT 
						'T' AS DISPLAY ,	 
						'H' AS GUBUN , 
						'' AS TMHWAJU , 
						'' AS TMHANGCHA , 
						'총 계' AS TMGOKJONG , 
						'' AS TMBLNO , 
						'' AS TMHMNO1 , 
						'' AS TMHMNO2 , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS TMYSHWAJU , 
						SUM ( TMYSQTY ) AS TMYSQTY 
						FROM DETAIL 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE TRIM ( TMGUBUN ) = TRIM ( P_YSGUBUN ) 
					) 
  
					SELECT 
					COUNT ( * ) AS TOTALCOUNT 
					FROM 
					( 
						SELECT 
						DISPLAY , 
						GUBUN , 
						TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						TMBLNO , 
						( TRIM ( CHAR ( TMHMNO1 ) ) || '-' || TRIM ( CHAR ( TMHMNO2 ) ) ) AS TMHMN , 
						DIGITS ( TMCUSTIL ) AS TMCUSTIL , 
						DIGITS ( TMSEQ ) AS TMSEQ , 
						( CASE WHEN TMGUBUN = '2' THEN '양수' 
						WHEN TMGUBUN = '1' THEN '양도' END ) AS TMGUBUN , 
						DIGITS ( TMYSDATE ) AS TMYSDATE , 
						YSCODE . CDDESC1 AS YSDESC1 , 
						TMYSQTY 
						FROM DETAIL AS TMED 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS YSCODE 
						ON 'HJ' = YSCODE . CDINDEX 
						AND TMED . TMYSHWAJU = YSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND TMED . TMHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND TMED . TMGOKJONG = GKCODE . CDCODE 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE TRIM ( TMGUBUN ) = TRIM ( P_YSGUBUN ) 
  
						UNION ALL 
  
						SELECT 
						DISPLAY , 
						GUBUN , 
						TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						'' AS GKDESC1 , 
						'' AS TMBLNO , 
						'' AS TMHMN , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS YSDESC1 , 
						TMYSQTY 
						FROM HAP AS TMED 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND TMED . TMHANGCHA = VSCODE . CDCODE 
					) AS TEMP ; 
  
				OPEN REFCURSOR37 ; 
  
			END PAGING7 ; 
  
		ELSE 
  
			PRINT : BEGIN  -- 프린트 
				DECLARE REFCURSOR5 CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						CAST ( P_SDATE AS CHAR ( 8 ) ) AS IN_STDATE , 
						CAST ( P_EDATE AS CHAR ( 8 ) ) AS IN_EDDATE , 
						CAST ( P_YSGUBUN AS VARCHAR ( 1 ) ) AS IN_GUBUN 
						FROM SYSIBM . SYSDUMMY1 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
  
						UNION ALL 
  
						SELECT 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						YNGOKJONG AS TMGOKJONG , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TYSCMLIB . USIYANGNF 
						INNER JOIN MAST 
						ON 1 = 1 
						WHERE YNYSDATE BETWEEN IN_STDATE AND IN_EDDATE 
					) 
  
					SELECT 
					ROW_NUMBER ( ) OVER ( ORDER BY TMHANGCHA , TMGOKJONG , TMBLNO , TMHMNO1 , TMHMNO2 , TMCUSTIL , TMSEQ , TMGUBUN , TMYSDATE ) AS ROWNO , 
					TMHANGCHA , 
					VSCODE . CDDESC1 AS VSDESC1 , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					TMBLNO , 
					( TRIM ( CHAR ( TMHMNO1 ) ) || '-' || TRIM ( CHAR ( TMHMNO2 ) ) ) AS TMHMN , 
					TMCUSTIL , 
					TMSEQ , 
					( CASE WHEN TMGUBUN = '2' THEN '양수' 
					WHEN TMGUBUN = '1' THEN '양도' END ) AS TMGUBUN , 
					TMYSDATE , 
					YSCODE . CDDESC1 AS YSDESC1 , 
					TMYSQTY 
					FROM DETAIL AS TMED 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS YSCODE 
					ON 'HJ' = YSCODE . CDINDEX 
					AND TMED . TMYSHWAJU = YSCODE . CDCODE 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
					ON 'VS' = VSCODE . CDINDEX 
					AND TMED . TMHANGCHA = VSCODE . CDCODE 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND TMED . TMGOKJONG = GKCODE . CDCODE 
					INNER JOIN MAST 
					ON 1 = 1 
					WHERE TMHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					AND ( CASE WHEN IN_GUBUN = '' THEN '' ELSE TRIM ( TMGUBUN ) END ) 
					= ( CASE WHEN IN_GUBUN = '' THEN '' ELSE TRIM ( IN_GUBUN ) END ) ; 
  
				OPEN REFCURSOR5 ; 
  
			END PRINT ; 
  
		END IF ; 
  
	END MAIN ; 
  
END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1090_LIST 
TO KSGPDM WITH GRANT OPTION ; 


CALL TYJINFWLIB.SP_TYCSS_CSS1090_LIST(1,15, '20210101', '20210507', 'C02', '', 'S');