DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1020_LIST;
--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-05-09 16:43:11 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","KSGPDM" ; 
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1020_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_DATE VARCHAR(8) , 
	IN P_GUBUN VARCHAR(1) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSS_CSS1020_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부 
		IF P_GUBUN = 'S' THEN 
  
		LIST : BEGIN  -- 리스트 
				DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
					WITH ORIGINAL_DATA AS 
					( 
						SELECT 
						ROW_NUMBER ( ) OVER ( ORDER BY SHDATE , SHSEQ ) AS ROWNO , 
						( SUBSTR ( SHDATE , 1 , 4 ) || '/' || SUBSTR ( SHDATE , 5 , 2 ) || '/' || SUBSTR ( SHDATE , 7 , 2 ) ) AS SHIPYYMD , 
						SHSEQ AS SHIPYSEQ , 
						SHVESSEL AS SHVSNAME , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						SKCODE . CDDESC1 AS SKDESC1 , 
						WNCODE . CDDESC1 AS WNDESC1 , 
						'울산' AS SHHANGGB , 
						( SUBSTR ( SHETAULSAN , 1 , 4 ) || '/' || SUBSTR ( SHETAULSAN , 5 , 2 ) || '/' || SUBSTR ( SHETAULSAN , 7 , 2 ) ) AS SHJUBDAT , 
						( CASE WHEN SUBSTR ( SHETAULTIME , 1 , 1 ) = '1' THEN 'AM' WHEN SUBSTR ( SHETAULTIME , 1 , 1 ) = '2' THEN 'PM' ELSE '' END ) AS SHSTTIME , 
						( SUBSTR ( CHAR ( IHJAKSTDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHJAKSTDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHJAKSTDAT ) , 7 , 2 ) || ' - ' || SUBSTR ( CHAR ( IHJAKENDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 7 , 2 ) ) AS SHIHSDAT , 
						SHULSANQTY AS SHBLQTY , 
						SHAGENT , 
						'' AS SHICANNY 
						FROM TYSCMLIB . PSM_SHIPSCHEDULE_SILO AS SCHD 
						LEFT OUTER JOIN TYSCMLIB . USIIPHAF AS IPHA 
						ON SCHD . SHHANGCHA = IPHA . IHHANGCHA 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND SCHD . SHGOKJONG = GKCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS SKCODE 
						ON 'SK' = SKCODE . CDINDEX 
						AND SCHD . SHSOSOK = SKCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS WNCODE 
						ON 'WN' = WNCODE . CDINDEX 
						AND SCHD . SHWONSAN = WNCODE . CDCODE 
						WHERE SHHWDATE = SUBSTR(P_DATE,1,6)
					) 
  
					SELECT 
					ROWNO , 
					SHIPYYMD , 
					SHIPYSEQ , 
					SHVSNAME , 
					GKDESC1 , 
					SKDESC1 , 
					WNDESC1 , 
					SHHANGGB , 
					SHJUBDAT , 
					SHSTTIME , 
					SHIHSDAT , 
					TRIM ( TO_CHAR ( SHBLQTY , '9,999,990.000' ) ) AS SHBLQTY , 
					SHAGENT , 
					SHICANNY 
					FROM ORIGINAL_DATA AS A 
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) 
					ORDER BY ROWNO ; 
				 
				OPEN REFCURSOR ; 
  
			END LIST ; 
		 
			PAGING : BEGIN  -- 페이징 
				DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
  
							SELECT 
							COUNT ( * ) AS TOTALCOUNT 
							FROM TYSCMLIB . PSM_SHIPSCHEDULE_SILO 
							WHERE SHHWDATE = SUBSTR(P_DATE,1,6) ; 
  
				OPEN REFCURSOR2 ; 
  
			END PAGING ; 
  
		ELSE 
  
			PRINT : BEGIN  -- 페이징 
				DECLARE REFCURSOR3 CURSOR WITH RETURN FOR 
  
					SELECT 
					( SUBSTR ( SHDATE , 1 , 4 ) || '/' || SUBSTR ( SHDATE , 5 , 2 ) || '/' || SUBSTR ( SHDATE , 7 , 2 ) ) AS SHIPYYMD , 
					SHSEQ AS SHIPYSEQ , 
					SHVESSEL AS SHVSNAME , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					SKCODE . CDDESC1 AS SKDESC1 , 
					WNCODE . CDDESC1 AS WNDESC1 , 
					'울산' AS SHHANGGB , 
					( SUBSTR ( SHETAULSAN , 1 , 4 ) || '/' || SUBSTR ( SHETAULSAN , 5 , 2 ) || '/' || SUBSTR ( SHETAULSAN , 7 , 2 ) ) AS SHJUBDAT , 
					( CASE WHEN SUBSTR ( SHETAULTIME , 1 , 1 ) = '1' THEN 'AM' WHEN SUBSTR ( SHETAULTIME , 1 , 1 ) = '2' THEN 'PM' ELSE '' END ) AS SHSTTIME , 
					( SUBSTR ( CHAR ( IHJAKSTDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHJAKSTDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHJAKSTDAT ) , 7 , 2 ) || ' - ' || SUBSTR ( CHAR ( IHJAKENDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 7 , 2 ) ) AS SHIHSDAT , 
					SHULSANQTY AS SHBLQTY , 
					SHAGENT , 
					'' AS SHICANNY 
					FROM TYSCMLIB . PSM_SHIPSCHEDULE_SILO AS SCHD 
					LEFT OUTER JOIN TYSCMLIB . USIIPHAF AS IPHA 
					ON SCHD . SHHANGCHA = IPHA . IHHANGCHA 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND SCHD . SHGOKJONG = GKCODE . CDCODE 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS SKCODE 
					ON 'SK' = SKCODE . CDINDEX 
					AND SCHD . SHSOSOK = SKCODE . CDCODE 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS WNCODE 
					ON 'WN' = WNCODE . CDINDEX 
					AND SCHD . SHWONSAN = WNCODE . CDCODE 
					WHERE SHHWDATE = SUBSTR(P_DATE,1,6)
					ORDER BY SHDATE , SHIPYYMD , SHIPYSEQ ; 
  
				OPEN REFCURSOR3 ; 
			END PRINT ; 
  
		END IF ; 
  
	END MAIN ; 
END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1020_LIST 
TO KSGPDM WITH GRANT OPTION ;
