--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_PRINT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2020_PRINT(
        IN P_DATE   VARCHAR(6),
	IN P_HWAJU  VARCHAR(50))

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_SQLSTRING VARCHAR(4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR(4000 ) ; 

	DECLARE V_DATE VARCHAR(30);

	PRINT : BEGIN  -- 출력

		DECLARE REFCURSOR CURSOR WITH RETURN FOR

			SELECT
			SUBSTR(VEND.VNSAUPJA,1,3)||'-'||SUBSTR(VEND.VNSAUPJA,4,2)||'-'||SUBSTR(VEND.VNSAUPJA,6,5) AS VNSAUPJA,
			VNSANGHO,
			VNIRUM,
			(CASE WHEN VEND.VNNEWADD = '' THEN VEND.VNTAXJUSO ELSE VEND.VNNEWADD END) AS VNTAXJUSO,
			SUBSTR(CHAR(HYYYMMDD),1,4)|| ' / ' ||SUBSTR(CHAR(HYYYMMDD),5,2) AS MONTH,
			HYHANGCHA,
			CODE.CDDESC1 AS HANGCHANM,
			SUBSTR(CHAR(IPHA.IHIPHANG),1,4)|| ' / ' ||SUBSTR(CHAR(IPHA.IHIPHANG),5,2) || ' / ' ||SUBSTR(CHAR(IPHA.IHIPHANG),7,2) AS IHIPHANG,
			GKCD.CDDESC1 AS GOKJONGNM,
			(CASE WHEN GKCD.CDGUBUN1 = '1' AND HYHAYKAMT <> 0 THEN CONT.CNHAYAMT
			WHEN GKCD.CDGUBUN1 = '2' AND HYHAYKAMT <> 0 THEN CONT.CNBYHAYAMT END) AS HAYAAMT,
			HYYDQTY AS TOTYDQTY,
			HYCHQTY AS TOTCHQTY,
			(HYYDQTY + HYCHQTY) AS TOTQTY,
			(HYYDQTY + HYCHQTY) AS JCHQTY,
			HYHAYKAMT AS HAYKAMT,
			HYHAYKVAT AS HAYKVAT,
			(CASE WHEN HYISQTY = 0 THEN (HYHAYKAMT+HYHAYKVAT) 
			WHEN HYISQTY <> 0 THEN (HYHAYKAMT+HYHAYKVAT + HYISAMT + HYISVAT) END) AS TOTAMT,
			SUBSTR(CHAR(IPHA.IHJAKENDAT),1,4)||' / '||SUBSTR(CHAR(IPHA.IHJAKENDAT),5,2)||' / '||SUBSTR(CHAR(IPHA.IHJAKENDAT),7,2) as IHJAKENDAT,
			HYGOKJONG,
			HYHWAJU,
			(JEGO.JGBEJNQTY + JEGO.JGBEIPQTY - JEGO.JGBECHQTY) AS JGBEJNQTY,
			(JEGO.JGHWAKQTY + JEGO.JGHWIPQTY - JEGO.JGHWCHQTY) AS JGHWAKQTY,
			SUBSTR(CHAR(HYIL.HLDATE),1,4)|| ' / ' ||SUBSTR(CHAR(HYIL.HLDATE),5,2) || ' / ' ||SUBSTR(CHAR(HYIL.HLDATE),7,2) AS CHDAT,
			(HYIL.HLCHQTY+HYIL.HLYDQTY) AS CHQTY,
			(CASE WHEN HLYDQTY <> 0 THEN '양도분'
			WHEN HYISQTY <> 0 THEN '이송량' END ) AS CHBIGO,
			HYISQTY,
			HYISDANGA,
			HYISAMT,
			HYISVAT,
			'' AS CHDAT2,
			0 AS CHQTY2,
			'' AS CHBIGO2,
			(DIGITS(HYYYMMDD)||HYHANGCHA||HYHWAJU||HYGOKJONG||HYJPNO) AS GUBUN,
			HYJPNO
			FROM TYSCMLIB.USIMCHYF
			LEFT OUTER JOIN TYSCMLIB.USIVENDF VEND
			ON   VEND.VNCODE = HYHWAJU
			LEFT OUTER JOIN TYSCMLIB.USICODEF CODE
			ON   CODE.CDINDEX = 'VS'
			AND  CODE.CDCODE = HYHANGCHA
			LEFT OUTER JOIN TYSCMLIB.USIIPHAF IPHA
			ON   IPHA.IHHANGCHA = HYHANGCHA
			LEFT OUTER JOIN TYSCMLIB.USIJEGOF JEGO
			ON   JEGO.JGHANGCHA = HYHANGCHA
			AND  JEGO.JGGOKJONG = HYGOKJONG
			AND  JEGO.JGHWAJU = (CASE WHEN ((HYHANGCHA = '200330' OR HYHANGCHA = '200334') AND HYHWAJU = 'S31') THEN 'S03'
			WHEN HYHANGCHA IN('201128','201131','201132','201137') AND HYHWAJU = 'H59' THEN 'H56'
			WHEN HYHANGCHA IN('201143') AND HYHWAJU = 'J32' THEN 'J29'
			ELSE HYHWAJU
			END)
			LEFT OUTER JOIN TYSCMLIB.USICODEF GKCD
			ON   GKCD.CDINDEX = 'GK'
			AND  GKCD.CDCODE = HYGOKJONG
			LEFT OUTER JOIN TYSCMLIB.USICONTF CONT
			ON   CONT.CNYEAR = DECIMAL(SUBSTR(CHAR(HYCONTNO),1,4))
			AND  CONT.CNSEQ = DECIMAL(SUBSTR(CHAR(HYCONTNO),5,2))
			LEFT OUTER JOIN TYSCMLIB.USIMCHYILF HYIL
			ON   HYIL.HLMCYYMM  = HYMCYYMM
			AND  HYIL.HLHANGCHA = HYHANGCHA
			AND  HYIL.HLGOKJONG = HYGOKJONG
			AND  HYIL.HLHWAJU   = HYHWAJU
			AND  HYIL.HLYYMMDD  = HYYYMMDD
			WHERE HYMCYYMM = P_DATE
			AND   HYHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(50)),',')) AS InTable)
			ORDER BY  HYHANGCHA,HYHWAJU;

		OPEN REFCURSOR;

	END PRINT;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS2020_PRINT('202104', 'K04');