--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1040_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1040_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE    VARCHAR(6),
	IN P_EDATE    VARCHAR(6),
	IN P_HWAJU    VARCHAR(50),
	IN P_GUBUN    VARCHAR(1)) 

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부

		IF P_GUBUN = 'S' THEN

		      LIST : BEGIN  -- 리스트 
				DECLARE REFCURSOR CURSOR WITH RETURN FOR

					WITH ORIGINAL_DATA AS
					(
						SELECT
						ROW_NUMBER() OVER(ORDER BY IHIPHANG, LTHANGCHA ) AS ROWNO,
						(SUBSTR(CHAR(IHIPHANG),1,4)||'-'||SUBSTR(CHAR(IHIPHANG),5,2)||'-'||SUBSTR(CHAR(IHIPHANG),6,2)) AS IHIPHANG,
						LTHANGCHA,
						VSCODE.CDDESC1 AS VSDESC1,
						SKCODE.CDDESC1 AS SKDESC1,
						GKCODE.CDDESC1 AS GKDESC1,
						(SUBSTR(DIGITS(LTSAVE),1,2)||':'||SUBSTR(DIGITS(LTSAVE),3,2)||':'||SUBSTR(DIGITS(LTSAVE),5,2)) AS LTSAVE,
						LTBLQTY,
						LTTOTSAVE,
						(CASE WHEN LTGUBUN = '1' THEN '조출료'
						      WHEN LTGUBUN = '2' THEN '체선료' END) AS LTGUBUN
						FROM TYSCMLIB.USIMCLTF AS MCLT
						LEFT OUTER JOIN TYSCMLIB.USIIPHAF AS IPHA
						ON       MCLT.LTHANGCHA = IPHA.IHHANGCHA
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE
						ON                 'VS' = VSCODE.CDINDEX
						AND      MCLT.LTHANGCHA = VSCODE.CDCODE
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE
						ON                 'SK' = SKCODE.CDINDEX
						AND      IPHA.IHSOSOK   = SKCODE.CDCODE
						LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE
						ON                 'GK' = GKCODE.CDINDEX
						AND      MCLT.LTGOKJONG = GKCODE.CDCODE
						WHERE SUBSTR(CHAR(IPHA.IHIPHANG),1,6) BETWEEN P_SDATE AND P_EDATE
						AND    (   LTHWAJU1  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU2  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU3  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU4  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU5  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU6  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU7  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU8  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU9  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU10 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU11 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU12 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU13 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU14 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU15 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU16 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU17 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU18 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU19 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
							OR LTHWAJU20 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
					)

					SELECT
					ROWNO,
					IHIPHANG,
					LTHANGCHA,
					VSDESC1,
					SKDESC1,
					GKDESC1,
					LTSAVE,
					LTBLQTY,
					LTTOTSAVE,
					LTGUBUN
					FROM ORIGINAL_DATA AS A
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) )AND CAST ( P_FNNUM AS VARCHAR ( 100 ) )
					ORDER BY ROWNO;
				
				OPEN REFCURSOR;

			END LIST;
		  
			PAGING : BEGIN  -- 페이징 
				
				DECLARE REFCURSOR2 CURSOR WITH RETURN FOR

							SELECT
							COUNT(*) AS TOTALCOUNT
							FROM TYSCMLIB.USIMCLTF AS MCLT
							LEFT OUTER JOIN TYSCMLIB.USIIPHAF AS IPHA
							ON       MCLT.LTHANGCHA = IPHA.IHHANGCHA
							WHERE SUBSTR(CHAR(IPHA.IHIPHANG),1,6) BETWEEN P_SDATE AND P_EDATE
							AND    (   LTHWAJU1  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU2  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU3  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU4  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU5  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU6  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU7  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU8  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU9  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU10 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU11 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU12 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU13 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU14 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU15 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU16 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU17 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU18 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU19 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
								OR LTHWAJU20 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ));

				OPEN REFCURSOR2;

			END PAGING;

		ELSE

			PRINT : BEGIN  -- 페이징

				DECLARE REFCURSOR3 CURSOR WITH RETURN FOR

					SELECT
					(SUBSTR(CHAR(IHIPHANG),1,4)||'-'||SUBSTR(CHAR(IHIPHANG),5,2)||'-'||SUBSTR(CHAR(IHIPHANG),6,2)) AS IHIPHANG,
					LTHANGCHA,
					VSCODE.CDDESC1 AS VSDESC1,
					SKCODE.CDDESC1 AS SKDESC1,
					GKCODE.CDDESC1 AS GKDESC1,
					(SUBSTR(DIGITS(LTSAVE),1,2)||':'||SUBSTR(DIGITS(LTSAVE),3,2)||':'||SUBSTR(DIGITS(LTSAVE),5,2)) AS LTSAVE,
					LTBLQTY,
					LTTOTSAVE,
					(CASE WHEN LTGUBUN = '1' THEN '조출료'
					      WHEN LTGUBUN = '2' THEN '체선료' END) AS LTGUBUN
					FROM TYSCMLIB.USIMCLTF AS MCLT
					LEFT OUTER JOIN TYSCMLIB.USIIPHAF AS IPHA
					ON       MCLT.LTHANGCHA = IPHA.IHHANGCHA
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE
					ON                 'VS' = VSCODE.CDINDEX
					AND      MCLT.LTHANGCHA = VSCODE.CDCODE
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE
					ON                 'SK' = SKCODE.CDINDEX
					AND      IPHA.IHSOSOK   = SKCODE.CDCODE
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE
					ON                 'GK' = GKCODE.CDINDEX
					AND      MCLT.LTGOKJONG = GKCODE.CDCODE
					WHERE SUBSTR(CHAR(IPHA.IHIPHANG),1,6) BETWEEN P_SDATE AND P_EDATE
					AND    (   LTHWAJU1  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU2  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU3  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU4  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU5  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU6  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU7  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU8  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU9  IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU10 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU11 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU12 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU13 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU14 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU15 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU16 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU17 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU18 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU19 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
						OR LTHWAJU20 IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
					ORDER BY IHIPHANG, LTHANGCHA;

				OPEN REFCURSOR3;
			END PRINT;

		END IF;

	END MAIN;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1040_LIST(1, 15, '202001', '202104', 'S70', 'S');