--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2060_LIST;

CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2060_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_DATE VARCHAR(6) , 
	IN P_HWAJU VARCHAR(50) , 
	IN P_GUBUN VARCHAR(1) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSS_CSS2060_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부 
		IF P_GUBUN = 'S' THEN 
  
			LIST : BEGIN  -- 리스트 
				DECLARE REFCURSOR CURSOR WITH RETURN FOR 
					 
					WITH ORIGINAL_DATA AS 
					( 
						SELECT 
						HDYYMMDD , 
						( SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 7 , 2 ) ) AS IPHANG , 
						HDHANGCHA , 
						HDGOKJONG , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						HDHWAKQTY , 
						( '11' ) AS DANGA , 
						HDUSEDAMT , 
						HDUSEDVAT , 
						( HDUSEDAMT + HDUSEDVAT ) AS TOTAL 
						FROM TYSCMLIB . USIMCHDF AS MCHD 
						LEFT OUTER JOIN TYSCMLIB . USIIPHAF IPHA 
						ON IPHA . IHHANGCHA = HDHANGCHA 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND MCHD . HDHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND MCHD . HDGOKJONG = GKCODE . CDCODE 
						WHERE HDMCYYMM = P_DATE 
						AND HDHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						'1' AS GUBUN , 
						DIGITS ( HDYYMMDD ) AS HDYYMMDD , 
						IPHANG , 
						HDHANGCHA , 
						HDGOKJONG , 
						VSDESC1 , 
						GKDESC1 , 
						HDHWAKQTY , 
						DANGA , 
						HDUSEDAMT , 
						HDUSEDVAT , 
						TOTAL 
						FROM ORIGINAL_DATA 
  
						UNION ALL 
  
						SELECT 
						'2' AS GUBUN , 
						'' AS HDYYMMDD , 
						'' AS IPHANG , 
						'' AS HDHANGCHA , 
						'' AS HDGOKJONG , 
						'' AS VSDESC1 , 
						'' AS GKDESC1 , 
						0 AS HDHWAKQTY , 
						0 AS DANGA , 
						VALUE ( SUM ( HDUSEDAMT ) , 0 ) AS HDUSEDAMT , 
						VALUE ( SUM ( HDUSEDVAT ) , 0 ) AS HDUSEDVAT , 
						VALUE ( SUM ( TOTAL ) , 0 ) AS TOTAL 
						FROM ORIGINAL_DATA 
					) 
					 
					SELECT 
					ROWNO , 
					HDYYMMDD , 
					IPHANG , 
					HDHANGCHA , 
					HDGOKJONG , 
					VSDESC1 , 
					GKDESC1 , 
					TRIM(TO_CHAR(HDHWAKQTY, '9,999,990.000')) AS HDHWAKQTY , 
					DANGA , 
					HDUSEDAMT , 
					HDUSEDVAT , 
					TOTAL 
					FROM 
					( 
						SELECT 
						ROW_NUMBER ( ) OVER ( ) AS ROWNO , 
						( CASE WHEN GUBUN IN ( '2' ) THEN '<div style="color:red" >합     계</div>' 
				ELSE HDYYMMDD END ) AS HDYYMMDD , 
						IPHANG , 
						HDHANGCHA , 
						HDGOKJONG , 
						VSDESC1 , 
						GKDESC1 , 
						HDHWAKQTY , 
						DANGA , 
						( CASE WHEN GUBUN IN ( '2' ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( HDUSEDAMT , '999,999,999,990' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( HDUSEDAMT , '999,999,999,990' ) ) END ) AS HDUSEDAMT , 
						( CASE WHEN GUBUN IN ( '2' ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( HDUSEDVAT , '999,999,999,990' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( HDUSEDVAT , '999,999,999,990' ) ) END ) AS HDUSEDVAT , 
						( CASE WHEN GUBUN IN ( '2' ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( TOTAL , '999,999,999,990' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( TOTAL , '999,999,999,990' ) ) END ) AS TOTAL 
						FROM DETAIL 
						ORDER BY GUBUN , HDYYMMDD , HDHANGCHA , HDGOKJONG 
					) AS TEMP 
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) ; 
  
				OPEN REFCURSOR ; 
  
			END LIST ; 
  
			PAGING : BEGIN  -- 페이징 
				DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
  
					WITH ORIGINAL_DATA AS 
					( 
						SELECT 
						HDYYMMDD , 
						( SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 7 , 2 ) ) AS IPHANG , 
						HDHANGCHA , 
						HDGOKJONG , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						HDHWAKQTY , 
						( '11' ) AS DANGA , 
						HDUSEDAMT , 
						HDUSEDVAT , 
						( HDUSEDAMT + HDUSEDVAT ) AS TOTAL 
						FROM TYSCMLIB . USIMCHDF AS MCHD 
						LEFT OUTER JOIN TYSCMLIB . USIIPHAF IPHA 
						ON IPHA . IHHANGCHA = HDHANGCHA 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND MCHD . HDHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND MCHD . HDGOKJONG = GKCODE . CDCODE 
						WHERE HDMCYYMM = P_DATE 
						AND HDHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						'1' AS GUBUN , 
						DIGITS ( HDYYMMDD ) AS HDYYMMDD , 
						IPHANG , 
						HDHANGCHA , 
						HDGOKJONG , 
						VSDESC1 , 
						GKDESC1 , 
						TRIM(TO_CHAR(HDHWAKQTY, '9,999,990.000')) AS HDHWAKQTY , 
						DANGA , 
						HDUSEDAMT , 
						HDUSEDVAT , 
						TOTAL 
						FROM ORIGINAL_DATA 
  
						UNION ALL 
  
						SELECT 
						'2' AS GUBUN , 
						'' AS HDYYMMDD , 
						'' AS IPHANG , 
						'' AS HDHANGCHA , 
						'' AS HDGOKJONG , 
						'' AS VSDESC1 , 
						'' AS GKDESC1 , 
						0 AS HDHWAKQTY , 
						0 AS DANGA , 
						VALUE ( SUM ( HDUSEDAMT ) , 0 ) AS HDUSEDAMT , 
						VALUE ( SUM ( HDUSEDVAT ) , 0 ) AS HDUSEDVAT , 
						VALUE ( SUM ( TOTAL ) , 0 ) AS TOTAL 
						FROM ORIGINAL_DATA 
					) 
  
					SELECT 
					COUNT ( * ) AS TOTALCOUNT 
					FROM DETAIL ; 
  
				OPEN REFCURSOR2 ; 
  
			END PAGING ; 
  
		ELSE 
  
			PRINT : BEGIN  -- 페이징 
				DECLARE REFCURSOR3 CURSOR WITH RETURN FOR 
  
					SELECT 
					( SUBSTR ( VEND . VNSAUPJA , 1 , 3 ) || '-' || SUBSTR ( VEND . VNSAUPJA , 4 , 2 ) || '-' || SUBSTR ( VEND . VNSAUPJA , 6 , 5 ) ) AS VNSAUPJA , 
					VEND . VNSANGHO , 
					VEND . VNIRUM , 
					VEND . VNTAXJUSO , 
					( SUBSTR ( CHAR ( HDYYMMDD ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( HDYYMMDD ) , 5 , 2 ) ) AS MONTH , 
					HDYYMMDD , 
					( SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 7 , 2 ) ) AS IPHANG , 
					HDHANGCHA , 
					HDGOKJONG , 
					VSCODE . CDDESC1 AS VSDESC1 , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					HDHWAKQTY , 
					( '11' ) AS DANGA , 
					HDUSEDAMT , 
					HDUSEDVAT , 
					( HDUSEDAMT + HDUSEDVAT ) AS TOTAL , 
					DIGITS ( HDYYMMDD ) || HDHANGCHA || HDGOKJONG AS GUBUN 
					FROM TYSCMLIB . USIMCHDF AS MCHD 
					LEFT OUTER JOIN TYSCMLIB . USIVENDF VEND 
					ON VEND . VNCODE = HDHWAJU 
					LEFT OUTER JOIN TYSCMLIB . USIIPHAF IPHA 
					ON IPHA . IHHANGCHA = HDHANGCHA 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
					ON 'VS' = VSCODE . CDINDEX 
					AND MCHD . HDHANGCHA = VSCODE . CDCODE 
					LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND MCHD . HDGOKJONG = GKCODE . CDCODE 
					WHERE HDMCYYMM = P_DATE 
					AND HDHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					ORDER BY HDYYMMDD , HDHANGCHA , HDGOKJONG ; 
  
				OPEN REFCURSOR3 ; 
  
			END PRINT ; 
  
		END IF ; 
  
	END MAIN ; 
END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2060_LIST 
TO KSGPDM WITH GRANT OPTION ;



CALL TYJINFWLIB.SP_TYCSS_CSS2060_LIST(1, 15, 201710, 'C02', 'P');