--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1030_DETAIL;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1030_DETAIL ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_HANGCHA VARCHAR(6),
	IN P_GOKJONG VARCHAR(2),
        IN P_HWAJU   VARCHAR(50)) 

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부      

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS
				(
					SELECT
					ROW_NUMBER() OVER() AS ROWNO,
					HJCODE.CDDESC1 AS HJDESC1,
					(JBBEJNQTY + JBBEIPQTY - JBBECHQTY) AS JBBEJNQTY,
					(JBHWAKQTY + JBHWIPQTY - JBHWCHQTY) AS JBHWAKQTY,
					((JBBEJNQTY + JBBEIPQTY - JBBECHQTY) - (JBHWAKQTY + JBHWIPQTY - JBHWCHQTY)) AS GAMQTY
					FROM TYSCMLIB.USIJEBLF AS JEBL
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS HJCODE
					ON              'HJ' = HJCODE.CDINDEX
					AND     JEBL.JBHWAJU = HJCODE.CDCODE
					WHERE JEBL.JBHANGCHA = P_HANGCHA
					AND   JEBL.JBGOKJONG = P_GOKJONG
					AND   JEBL.JBHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
					AND   (JEBL.JBBEJNQTY + JEBL.JBBEIPQTY - JEBL.JBBECHQTY) <> 0
					AND   (JEBL.JBHWAKQTY + JEBL.JBHWIPQTY - JEBL.JBHWCHQTY) <> 0					
				)

				SELECT
				*
				FROM ORIGINAL_DATA AS A
				WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) )AND CAST ( P_FNNUM AS VARCHAR ( 100 ) )
				ORDER BY ROWNO;
			
			OPEN REFCURSOR;

		END LIST;
	  
		PAGING : BEGIN  -- 페이징 
			
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR

				SELECT
				COUNT(*) AS TOTALCOUNT
				FROM TYSCMLIB.USIJEBLF AS JEBL
				WHERE JEBL.JBHANGCHA = P_HANGCHA
				AND   JEBL.JBGOKJONG = P_GOKJONG
				AND   JEBL.JBHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
				AND   (JEBL.JBBEJNQTY + JEBL.JBBEIPQTY - JEBL.JBBECHQTY) <> 0
				AND   (JEBL.JBHWAKQTY + JEBL.JBHWIPQTY - JEBL.JBHWCHQTY) <> 0;

			OPEN REFCURSOR2;

		END PAGING;

	END MAIN;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1030_DETAIL(1, 15, '201613','11','S70');
