--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2010_PRINT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2010_PRINT(
        IN P_DATE   VARCHAR(6),
	IN P_HWAJU  VARCHAR(50))

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_SQLSTRING VARCHAR(4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR(4000 ) ; 

	DECLARE V_DATE VARCHAR(30);

	-- 임시테이블 변수
	DECLARE V_DB_VNSAUPJA  VARCHAR(20);
	DECLARE V_DB_VNSANGHO  VARCHAR(50);
	DECLARE V_DB_VNIRUM    VARCHAR(20);
	DECLARE V_DB_VNTAXJUSO VARCHAR(20);
	DECLARE V_DB_MONTH     VARCHAR(50);
	DECLARE V_DB_YSNAME    VARCHAR(50);
	DECLARE V_DB_JBEJNQTY  NUMERIC(12,3);
	DECLARE V_DB_JYSQTY    NUMERIC(12,3);
	DECLARE V_DB_FLDNAME   VARCHAR(50);
	DECLARE V_DB_YDHWAJU   VARCHAR(50);
	DECLARE V_DB_YLINE     VARCHAR(50);
	DECLARE V_DB_HANGCHANM VARCHAR(50);
	DECLARE V_DB_BKHANGCHA VARCHAR(50);
	DECLARE V_DB_BKCHHWAJU VARCHAR(50);
	DECLARE V_DB_IPHANG    VARCHAR(15);
	DECLARE V_DB_JAKENDAT  VARCHAR(15);
	DECLARE V_DB_BDATE     VARCHAR(15);
	DECLARE V_DB_GOKJONGNM VARCHAR(50);
	DECLARE V_DB_JCHQTY    NUMERIC(12,3);
	DECLARE V_DB_CHQTY     NUMERIC(12,3);
	DECLARE V_DB_CHDAT     VARCHAR(15);
	DECLARE V_DB_JEGOQTY   NUMERIC(12,3);
	DECLARE V_DB_DANGA     NUMERIC(6, 2);
	DECLARE V_DB_BOKAMT    NUMERIC(9, 0);
	DECLARE V_DB_BIGO      VARCHAR(50);
	DECLARE V_DB_TOTAMT    NUMERIC(11, 0);
	DECLARE V_DB_TOTVAT    NUMERIC(11, 0);
	DECLARE V_DB_AMOUNT    NUMERIC(12, 0);
	DECLARE V_DB_BKYSDATE  VARCHAR(50);

	-- SELECT 변수
	DECLARE V_BKHWAJU      VARCHAR(3);
	DECLARE V_VNSAUPJA     VARCHAR(20);
	DECLARE V_VNSANGHO     VARCHAR(50);
	DECLARE V_VNIRUM       VARCHAR(20);
	DECLARE V_VNTAXJUSO    VARCHAR(20);
	DECLARE V_MONTH        VARCHAR(20);
	DECLARE V_YSNAME       VARCHAR(50);
	DECLARE V_YDHWAJU      VARCHAR(50);
	DECLARE V_YLINE        VARCHAR(10);
	DECLARE V_HANGCHANM    VARCHAR(50);
	DECLARE V_BDATE        VARCHAR(20);
	DECLARE V_GOKJONGNM    VARCHAR(50);
	DECLARE V_JBEJNQTY     NUMERIC(12,3);
	DECLARE V_JYSQTY       NUMERIC(12,3);
	DECLARE V_JCHQTY       NUMERIC(12,3);
	DECLARE V_CHDAT        VARCHAR(20);
	DECLARE V_CHQTY        NUMERIC(12,3);
	DECLARE V_JEGOQTY      NUMERIC(12,3);
	DECLARE V_DANGA        NUMERIC(6, 2);
	DECLARE V_BOKAMT       NUMERIC(9, 0);
	DECLARE V_BIGO         VARCHAR(20);
	DECLARE V_TOTAMT       NUMERIC(11, 0);
	DECLARE V_TOTVAT       NUMERIC(11, 0);
	DECLARE V_AMOUNT       NUMERIC(12, 0);
	DECLARE V_FLDNAME      VARCHAR(20);
	DECLARE V_BKBOKGB      VARCHAR(3);
	DECLARE V_HWAJU        VARCHAR(3);
	DECLARE V_BKYDHWAJU    VARCHAR(3);
	DECLARE V_JGYSQTY      NUMERIC(12,3);
	DECLARE V_IPHANG       VARCHAR(20);
	DECLARE V_JAKENDAT     VARCHAR(20);
	DECLARE V_BKHANGCHA    VARCHAR(6);
	DECLARE V_BKCHHWAJU    VARCHAR(3);
	DECLARE V_BKYSDATE     VARCHAR(50);
	DECLARE V_BKHANGCHA1   VARCHAR(6);
	DECLARE V_BKGOKJONG1   VARCHAR(3);
	DECLARE V_BKHWAJU1     VARCHAR(3);
	DECLARE V_BKBLMSN1     VARCHAR(4);
	DECLARE V_BKBLHSN1     VARCHAR(4);
	DECLARE V_BKBOKGB1     VARCHAR(3);
	DECLARE V_BKYDHWAJU1   VARCHAR(3);
	DECLARE V_BKCHHWAJU1   VARCHAR(3);
	DECLARE V_BKYSDATE1    VARCHAR(8);
	DECLARE V_BKYSSEQ1     VARCHAR(2);
	DECLARE V_BKYDSEQ1     VARCHAR(2);
	DECLARE V_BKWNHWAJU1   VARCHAR(3);
	DECLARE V_BKYYMMDD     NUMERIC(8,0);








	-- 임시테이블 변수
	SET V_DB_VNSAUPJA  = '';
	SET V_DB_VNSANGHO  = '';
	SET V_DB_VNIRUM    = '';
	SET V_DB_VNTAXJUSO = '';
	SET V_DB_MONTH     = '';
	SET V_DB_YSNAME    = '';
	SET V_DB_JBEJNQTY  = 0;
	SET V_DB_JYSQTY    = 0;
	SET V_DB_FLDNAME   = '';
	SET V_DB_YDHWAJU   = '';
	SET V_DB_YLINE     = '';
	SET V_DB_HANGCHANM = '';
	SET V_DB_BKHANGCHA = '';
	SET V_DB_BKCHHWAJU = '';
	SET V_DB_IPHANG    = '';
	SET V_DB_JAKENDAT  = '';
	SET V_DB_BDATE     = '';
	SET V_DB_GOKJONGNM = '';
	SET V_DB_JCHQTY    = 0;
	SET V_DB_CHQTY     = 0;
	SET V_DB_CHDAT     = '';
	SET V_DB_JEGOQTY   = 0;
	SET V_DB_DANGA     = 0;
	SET V_DB_BOKAMT    = 0;
	SET V_DB_BIGO      = '';
	SET V_DB_TOTAMT    = 0;
	SET V_DB_TOTVAT    = 0;
	SET V_DB_AMOUNT    = 0;
	SET V_DB_BKYSDATE  = '';

	-- SELECT 변수
	SET V_BKHWAJU      = '';
	SET V_VNSAUPJA     = '';
	SET V_VNSANGHO     = '';
	SET V_VNIRUM       = '';
	SET V_VNTAXJUSO    = '';
	SET V_MONTH        = '';
	SET V_YSNAME       = '';
	SET V_YDHWAJU      = '';
	SET V_YLINE        = '';
	SET V_HANGCHANM    = '';
	SET V_BDATE        = '';
	SET V_GOKJONGNM    = '';
	SET V_JBEJNQTY     = 0;
	SET V_JYSQTY       = 0;
	SET V_JCHQTY       = 0;
	SET V_CHDAT        = '';
	SET V_CHQTY        = 0;
	SET V_JEGOQTY      = 0;
	SET V_DANGA        = 0;
	SET V_BOKAMT       = 0;
	SET V_BIGO         = '';
	SET V_TOTAMT       = 0;
	SET V_TOTVAT       = 0;
	SET V_AMOUNT       = 0;
	SET V_FLDNAME      = '';
	SET V_BKBOKGB      = '';
	SET V_HWAJU        = '';
	SET V_BKYDHWAJU    = '';
	SET V_JGYSQTY      = 0;
	SET V_IPHANG       = '';
	SET V_JAKENDAT     = '';
	SET V_BKHANGCHA    = '';
	SET V_BKCHHWAJU    = '';
	SET V_BKYSDATE     = '';
	SET V_BKHANGCHA1   = '';
	SET V_BKGOKJONG1   = '';
	SET V_BKHWAJU1     = '';
	SET V_BKBLMSN1     = '';
	SET V_BKBLHSN1     = '';
	SET V_BKBOKGB1     = '';
	SET V_BKYDHWAJU1   = '';
	SET V_BKCHHWAJU1   = '';
	SET V_BKYSDATE1    = '';
	SET V_BKYSSEQ1     = '';
	SET V_BKYDSEQ1     = '';
	SET V_BKWNHWAJU1   = '';
	SET V_BKYYMMDD     = 0;

	-- 임시테이블부 
	DECLARE GLOBAL TEMPORARY TABLE SESSION . SILO_CSS2010
	( 
		      VNSAUPJA  VARCHAR(20)
		,     VNSANGHO  VARCHAR(50)
		,     VNIRUM    VARCHAR(20)
		,     VNTAXJUSO VARCHAR(20)
		,     MONTH     VARCHAR(50)
		,     YSNAME    VARCHAR(50)
		,     JBEJNQTY  NUMERIC(12,3)
		,     JYSQTY    NUMERIC(12,3)
		,     FLDNAME   VARCHAR(50)
		,     YDHWAJU   VARCHAR(50)
		,     YLINE     VARCHAR(50)
		,     HANGCHANM VARCHAR(50)
		,     BKHANGCHA VARCHAR(50)
		,     BKCHHWAJU VARCHAR(50)
		,     IPHANG    VARCHAR(15)
		,     JAKENDAT  VARCHAR(15)
		,     BDATE     VARCHAR(15)
		,     GOKJONGNM VARCHAR(50)
		,     JCHQTY    NUMERIC(12,3)
		,     CHQTY     NUMERIC(12,3)
		,     CHDAT     VARCHAR(15)
		,     JEGOQTY   NUMERIC(12,3)
		,     DANGA     NUMERIC(6,2)
		,     BOKAMT    NUMERIC(9,0)
		,     BIGO      VARCHAR(50)
		,     TOTAMT    NUMERIC(11,0)
		,     TOTVAT    NUMERIC(11,0)
		,     AMOUNT    NUMERIC(12,0)
		,     BKYSDATE  VARCHAR(50)
	) WITH REPLACE ;


	R1 : FOR C1 AS

			SELECT
			DISTINCT
			TEMP.BKHWAJU,
			TEMP.VNSAUPJA,
			TEMP.VNSANGHO,
			TEMP.VNIRUM,
			TEMP.VNTAXJUSO,
			TEMP.MONTH,
			TEMP.YSNAME,
			TEMP.YDHWAJU,
			TEMP.YLINE,
			TEMP.HANGCHANM,
			TEMP.BDATE,
			TEMP.GOKJONGNM,
			TEMP.JBEJNQTY,
			TEMP.JYSQTY,
			SUM(TEMP.JCHQTY) AS JCHQTY,
			TEMP.CHDAT,
			TEMP.CHQTY,
			TEMP.JEGOQTY,
			TEMP.DANGA,
			TEMP.BOKAMT,
			TEMP.BIGO,
			SUM(TEMP.TOTAMT) AS TOTAMT,
			TEMP.TOTVAT,
			TEMP.AMOUNT,
			TEMP.FLDNAME,
			TEMP.BKBOKGB,
			TEMP.HWAJU,
			TEMP.BKYDHWAJU,
			TEMP.JGYSQTY,
			TEMP.IPHANG,
			TEMP.JAKENDAT,
			TEMP.BKHANGCHA,
			TEMP.BKCHHWAJU,
			TEMP.BKYSDATE,
			TEMP.BKHANGCHA1,
			TEMP.BKGOKJONG1,
			TEMP.BKHWAJU1,
			TEMP.BKBLMSN1,
			TEMP.BKBLHSN1,
			TEMP.BKBOKGB1,
			TEMP.BKYDHWAJU1,
			TEMP.BKCHHWAJU1,
			TEMP.BKYSDATE1,
			TEMP.BKYSSEQ1,
			TEMP.BKYDSEQ1,
			TEMP.BKWNHWAJU1,
			TEMP.BKYYMMDD
			FROM
			(
				SELECT
				MCBK.BKHWAJU AS BKHWAJU,
				(SUBSTR(VNSAUPJA,1,3)||'-'||SUBSTR(VNSAUPJA,4,2)||'-'||SUBSTR(VNSAUPJA,6,5)) AS VNSAUPJA,
				VNSANGHO,
				VNIRUM,
				VNTAXJUSO,
				(SUBSTR(CHAR(MCBK.BKYYMMDD),1,4)||' / '||SUBSTR(CHAR(MCBK.BKYYMMDD),5,2)) AS MONTH,'' AS YSNAME,
				CODE.CDDESC1 AS YDHWAJU,
				'' AS YLINE,
				MCBK.BKHANGCHA,
				VSCD.CDDESC1 AS HANGCHANM,
				(SUBSTR(CHAR(IPHA.IHIPHANG),1,4)||' / '||SUBSTR(CHAR(IPHA.IHIPHANG),5,2)||' / '||SUBSTR(CHAR(IPHA.IHIPHANG),7,2)) AS IPHANG,(SUBSTR(CHAR(IPHA.IHJAKENDAT),1,4)||' / '||SUBSTR(CHAR(IPHA.IHJAKENDAT),5,2)||' / '||SUBSTR(CHAR(IPHA.IHJAKENDAT),7,2)) AS JAKENDAT,(SUBSTR(CHAR(JEGO.JGJESTDAT),1,4)||' / '||SUBSTR(CHAR(JEGO.JGJESTDAT),5,2)||' / '||SUBSTR(CHAR(JEGO.JGJESTDAT),7,2)) AS BDATE,
				GKCD.CDDESC1 AS GOKJONGNM,
				(JEGO.JGBEJNQTY + JEGO.JGBEIPQTY - JEGO.JGBECHQTY) AS JBEJNQTY,
				(JEGO.JGHWAKQTY + JEGO.JGHWIPQTY - JEGO.JGHWCHQTY) AS JYSQTY,
				MCBK.BKCHULQTY AS JCHQTY,
				(SUBSTR(CHAR(MCBK.BKDATE),1,4)||' / '||SUBSTR(CHAR(MCBK.BKDATE),5,2)||' / '||SUBSTR(CHAR(MCBK.BKDATE),7,2)) AS CHDAT,
				MCBK.BKCHULQTY AS CHQTY,
				MCBK.BKJEGOQTY AS JEGOQTY,
				MCBK.BKDANGA AS DANGA,
				MCBK.BKBOKAMT AS BOKAMT,
				'' AS BIGO,
				MCBK.BKBOKAMT AS TOTAMT,
				0 AS TOTVAT,
				0 AS AMOUNT,
				'' AS FLDNAME,
				MCBK.BKBOKGB,
				(CASE WHEN MCBK.BKHWAJU = MCBK.BKYDHWAJU THEN MCBK.BKCHHWAJU ELSE MCBK.BKYDHWAJU END) AS HWAJU,
				MCBK.BKYDHWAJU,
				MCBK.BKCHHWAJU,
				JEGO.JGYSQTY,
				(BKHANGCHA||MCBK.BKGOKJONG||BKHWAJU||DIGITS(BKBLMSN)||DIGITS(BKBLHSN)||BKBOKGB||BKYDHWAJU||BKCHHWAJU||DIGITS(BKYSDATE)||DIGITS(BKYSSEQ)||DIGITS(BKYDSEQ)||BKWNHWAJU) AS BKYSDATE,
				BKHANGCHA AS BKHANGCHA1,
				MCBK.BKGOKJONG AS BKGOKJONG1,
				BKHWAJU AS BKHWAJU1,
				DIGITS(BKBLMSN) AS BKBLMSN1,
				DIGITS(BKBLHSN) AS BKBLHSN1,
				BKBOKGB AS BKBOKGB1,
				BKYDHWAJU AS BKYDHWAJU1,
				BKCHHWAJU AS BKCHHWAJU1,
				DIGITS(BKYSDATE) AS BKYSDATE1,
				DIGITS(BKYSSEQ) AS BKYSSEQ1,
				DIGITS(BKYDSEQ) AS BKYDSEQ1,
				BKWNHWAJU AS BKWNHWAJU1,
				BKYYMMDD
				FROM TYSCMLIB.USIMCBKF MCBK
				LEFT OUTER JOIN TYSCMLIB.USIVENDF VEND
				ON      VEND.VNCODE = MCBK.BKHWAJU
				LEFT OUTER JOIN TYSCMLIB.USICODEF CODE
				ON             'HJ' = CODE.CDINDEX
				AND     CODE.CDCODE =(CASE WHEN MCBK.BKHWAJU = MCBK.BKYDHWAJU THEN MCBK.BKCHHWAJU ELSE MCBK.BKYDHWAJU END)
				LEFT OUTER JOIN TYSCMLIB.USIIPHAF IPHA
				ON   IPHA.IHHANGCHA = MCBK.BKHANGCHA
				LEFT OUTER JOIN TYSCMLIB.USICODEF VSCD
				ON             'VS' = VSCD.CDINDEX
				AND MCBK.BKHANGCHA = VSCD.CDCODE
				LEFT OUTER JOIN TYSCMLIB.USICODEF GKCD
				ON             'GK' = GKCD.CDINDEX
				AND MCBK.BKGOKJONG = GKCD.CDCODE
				LEFT OUTER JOIN TYSCMLIB.USIJEGOF JEGO
				ON  MCBK.BKHANGCHA = JEGO.JGHANGCHA
				AND MCBK.BKGOKJONG = JEGO.JGGOKJONG
				AND JEGO.JGHWAJU    =(CASE WHEN((MCBK.BKHANGCHA = '200330' OR MCBK.BKHANGCHA = '200334') AND MCBK.BKHWAJU = 'S31') THEN 'S03'
							    ELSE MCBK.BKHWAJU END)
				WHERE  MCBK.BKMCYYMM = P_DATE
				AND    MCBK.BKHWAJU   IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)),',')) AS InTable )
			) AS TEMP
			GROUP BY TEMP.BKHWAJU,TEMP.VNSAUPJA,TEMP.VNSANGHO,TEMP.VNIRUM,TEMP.VNTAXJUSO,
			         TEMP.MONTH,TEMP.YSNAME,TEMP.YDHWAJU,TEMP.YLINE,TEMP.HANGCHANM,TEMP.BDATE,
			         TEMP.GOKJONGNM,TEMP.JBEJNQTY,TEMP.JYSQTY,TEMP.CHDAT,TEMP.CHQTY,TEMP.JEGOQTY,
			         TEMP.DANGA,TEMP.BOKAMT,TEMP.BIGO,TEMP.TOTVAT,TEMP.AMOUNT,TEMP.FLDNAME,
			         TEMP.BKBOKGB,TEMP.HWAJU,TEMP.BKYDHWAJU,TEMP.JGYSQTY,TEMP.IPHANG,
			         TEMP.JAKENDAT,TEMP.BKHANGCHA,TEMP.BKCHHWAJU,TEMP.BKYSDATE,
			         TEMP.BKHANGCHA1,TEMP.BKGOKJONG1,TEMP.BKHWAJU1,TEMP.BKBLMSN1,TEMP.BKBLHSN1,
			         TEMP.BKBOKGB1,TEMP.BKYDHWAJU1,TEMP.BKCHHWAJU1,TEMP.BKYSDATE1,TEMP.BKYSSEQ1,
			         TEMP.BKYDSEQ1,TEMP.BKWNHWAJU1, TEMP.BKYYMMDD
			ORDER BY TEMP.BKHANGCHA ,TEMP.BKHWAJU,TEMP.BKCHHWAJU,TEMP.HWAJU,TEMP.BKYSDATE,TEMP.CHDAT

		DO

		-- 임시테이블 변수
		SET V_DB_VNSAUPJA  = '';
		SET V_DB_VNSANGHO  = '';
		SET V_DB_VNIRUM    = '';
		SET V_DB_VNTAXJUSO = '';
		SET V_DB_MONTH     = '';
		SET V_DB_YSNAME    = '';
		SET V_DB_JBEJNQTY  = 0;
		SET V_DB_JYSQTY    = 0;
		SET V_DB_FLDNAME   = '';
		SET V_DB_YDHWAJU   = '';
		SET V_DB_YLINE     = '';
		SET V_DB_HANGCHANM = '';
		SET V_DB_BKHANGCHA = '';
		SET V_DB_BKCHHWAJU = '';
		SET V_DB_IPHANG    = '';
		SET V_DB_JAKENDAT  = '';
		SET V_DB_BDATE     = '';
		SET V_DB_GOKJONGNM = '';
		SET V_DB_JCHQTY    = 0;
		SET V_DB_CHQTY     = 0;
		SET V_DB_CHDAT     = '';
		SET V_DB_JEGOQTY   = 0;
		SET V_DB_DANGA     = 0;
		SET V_DB_BOKAMT    = 0;
		SET V_DB_BIGO      = '';
		SET V_DB_TOTAMT    = 0;
		SET V_DB_TOTVAT    = 0;
		SET V_DB_AMOUNT    = 0;
		SET V_DB_BKYSDATE  = '';

		-- SELECT 변수
		SET V_BKHWAJU      = '';
		SET V_VNSAUPJA     = '';
		SET V_VNSANGHO     = '';
		SET V_VNIRUM       = '';
		SET V_VNTAXJUSO    = '';
		SET V_MONTH        = '';
		SET V_YSNAME       = '';
		SET V_YDHWAJU      = '';
		SET V_YLINE        = '';
		SET V_HANGCHANM    = '';
		SET V_BDATE        = '';
		SET V_GOKJONGNM    = '';
		SET V_JBEJNQTY     = 0;
		SET V_JYSQTY       = 0;
		SET V_JCHQTY       = 0;
		SET V_CHDAT        = '';
		SET V_CHQTY        = 0;
		SET V_JEGOQTY      = 0;
		SET V_DANGA        = 0;
		SET V_BOKAMT       = 0;
		SET V_BIGO         = '';
		SET V_TOTAMT       = 0;
		SET V_TOTVAT       = 0;
		SET V_AMOUNT       = 0;
		SET V_FLDNAME      = '';
		SET V_BKBOKGB      = '';
		SET V_HWAJU        = '';
		SET V_BKYDHWAJU    = '';
		SET V_JGYSQTY      = 0;
		SET V_IPHANG       = '';
		SET V_JAKENDAT     = '';
		SET V_BKHANGCHA    = '';
		SET V_BKCHHWAJU    = '';
		SET V_BKYSDATE     = '';
		SET V_BKHANGCHA1   = '';
		SET V_BKGOKJONG1   = '';
		SET V_BKHWAJU1     = '';
		SET V_BKBLMSN1     = '';
		SET V_BKBLHSN1     = '';
		SET V_BKBOKGB1     = '';
		SET V_BKYDHWAJU1   = '';
		SET V_BKCHHWAJU1   = '';
		SET V_BKYSDATE1    = '';
		SET V_BKYSSEQ1     = '';
		SET V_BKYDSEQ1     = '';
		SET V_BKWNHWAJU1   = '';
		SET V_BKYYMMDD     = 0;

		-- SELECT 변수
		SET V_BKHWAJU      = BKHWAJU;
		SET V_VNSAUPJA     = VNSAUPJA;
		SET V_VNSANGHO     = VNSANGHO;
		SET V_VNIRUM       = VNIRUM;
		SET V_VNTAXJUSO    = VNTAXJUSO;
		SET V_MONTH        = MONTH;
		SET V_YSNAME       = YSNAME;
		SET V_YDHWAJU      = YDHWAJU;
		SET V_YLINE        = YLINE;
		SET V_HANGCHANM    = HANGCHANM;
		SET V_BDATE        = BDATE;
		SET V_GOKJONGNM    = GOKJONGNM;
		SET V_JBEJNQTY     = JBEJNQTY;
		SET V_JYSQTY       = JYSQTY;
		SET V_JCHQTY       = JCHQTY;
		SET V_CHDAT        = CHDAT;
		SET V_CHQTY        = CHQTY;
		SET V_JEGOQTY      = JEGOQTY;
		SET V_DANGA        = DANGA;
		SET V_BOKAMT       = BOKAMT;
		SET V_BIGO         = BIGO;
		SET V_TOTAMT       = TOTAMT;
		SET V_TOTVAT       = TOTVAT;
		SET V_AMOUNT       = AMOUNT;
		SET V_FLDNAME      = FLDNAME;
		SET V_BKBOKGB      = BKBOKGB;
		SET V_HWAJU        = HWAJU;
		SET V_BKYDHWAJU    = BKYDHWAJU;
		SET V_JGYSQTY      = JGYSQTY;
		SET V_IPHANG       = IPHANG;
		SET V_JAKENDAT     = JAKENDAT;
		SET V_BKHANGCHA    = BKHANGCHA;
		SET V_BKCHHWAJU    = BKCHHWAJU;
		SET V_BKYSDATE     = BKYSDATE;
		SET V_BKHANGCHA1   = BKHANGCHA1;
		SET V_BKGOKJONG1   = BKGOKJONG1;
		SET V_BKHWAJU1     = BKHWAJU1;
		SET V_BKBLMSN1     = BKBLMSN1;
		SET V_BKBLHSN1     = BKBLHSN1;
		SET V_BKBOKGB1     = BKBOKGB1;
		SET V_BKYDHWAJU1   = BKYDHWAJU1;
		SET V_BKCHHWAJU1   = BKCHHWAJU1;
		SET V_BKYSDATE1    = BKYSDATE1;
		SET V_BKYSSEQ1     = BKYSSEQ1;
		SET V_BKYDSEQ1     = BKYDSEQ1;
		SET V_BKWNHWAJU1   = BKWNHWAJU1;
		SET V_BKYYMMDD     = BKYYMMDD;




		-- 임시테이블 변수
		SET V_DB_VNSAUPJA  = V_VNSAUPJA;
		SET V_DB_VNSANGHO  = V_VNSANGHO;
		SET V_DB_VNIRUM    = V_VNIRUM;
		SET V_DB_VNTAXJUSO = V_VNTAXJUSO;
		SET V_DB_MONTH     = V_MONTH;

		IF V_BKBOKGB = '1' THEN

			SET V_DB_YSNAME    = '';
			SET V_DB_JBEJNQTY  = V_JBEJNQTY;
			SET V_DB_JYSQTY    = V_JYSQTY;
			SET V_DB_FLDNAME   = '확정량';

		ELSE

			IF V_BKYDHWAJU = V_BKHWAJU THEN

				SET V_DB_YSNAME    = '(양도분)';

			ELSE
				
				SET V_DB_YSNAME    = '(양수분)';

			END IF;

			SET V_DB_YLINE   = '===============';
			SET V_DB_FLDNAME = '양 수 량';

			IF V_BKYDHWAJU = '' THEN

				SET V_DB_JYSQTY = V_JGYSQTY;

			ELSE

				SET V_DB_JYSQTY = 0;

				SELECT
				COALESCE(SUM(COALESCE(TEMP.YNYSQTY, 0)), 0) INTO V_DB_JYSQTY
				FROM  
				(     
					SELECT
					(CASE WHEN YNQTY >= 0 THEN YNQTY ELSE YNYSYDQTY END) AS YNYSQTY
					FROM TYSCMLIB.USIYANGNF
					WHERE YNHANGCHA = V_BKHANGCHA1
					AND   YNGOKJONG = V_BKGOKJONG1
					AND   YNHWAJU   = V_BKYDHWAJU1
					AND   YNBLMSN   = V_BKBLMSN1
					AND   YNBLHSN   = V_BKBLHSN1
					AND   YNYSHWAJU = V_BKHWAJU1
					AND   YNYSDATE  = V_BKYSDATE1
					AND   YNYSSEQ   = V_BKYSSEQ1
					AND   YNYDSEQ   = V_BKYDSEQ1
				) AS TEMP;

			END IF;

		END IF;


		IF V_BKYDHWAJU = '' THEN

			SET V_DB_YDHWAJU   = V_YDHWAJU;

		ELSE

			IF V_BKYYMMDD >= 20200120 THEN

				SELECT
				DISTINCT
				HJCODE.CDDESC1 INTO V_DB_YDHWAJU
				FROM TYSCMLIB.USIMCBKF AS MCBK
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS HJCODE
				ON              'HJ' = HJCODE.CDINDEX
				AND   MCBK.BKYSHWAJU = HJCODE.CDCODE
				WHERE BKMCYYMM  = P_DATE
				AND   BKHANGCHA = V_BKHANGCHA1
				AND   BKGOKJONG = V_BKGOKJONG1
				AND   BKHWAJU   = V_BKHWAJU1
				AND   BKBLMSN   = V_BKBLMSN1
				AND   BKBLHSN   = V_BKBLHSN1
				AND   BKBOKGB   = V_BKBOKGB
				AND   BKYDHWAJU = V_BKYDHWAJU1
				AND   BKCHHWAJU = V_BKCHHWAJU1
				AND   BKYSDATE  = V_BKYSDATE1
				AND   BKYSSEQ   = V_BKYSSEQ1
				AND   BKYDSEQ   = V_BKYDSEQ1
				AND   BKYYMMDD  = V_BKYYMMDD;

			ELSE

				SELECT
				DISTINCT
				HJCODE.CDDESC1 INTO V_DB_YDHWAJU
				FROM TYSCMLIB.USIYANGNF AS YANG
				LEFT OUTER JOIN TYSCMLIB.USICODEF AS HJCODE
				ON              'HJ' = HJCODE.CDINDEX
				AND   YANG.YNYSHWAJU = HJCODE.CDCODE
				WHERE YNHANGCHA = V_BKHANGCHA1
				AND   YNGOKJONG = V_BKGOKJONG1
				AND   YNHWAJU   = V_BKYDHWAJU1
				AND   YNBLMSN   = V_BKBLMSN1
				AND   YNBLHSN   = V_BKBLHSN1
				AND   YNYSDATE  = V_BKYSDATE1
				AND   YNYSSEQ   = V_BKYSSEQ1
				AND   YNYDSEQ   = V_BKYDSEQ1;

			END IF;

		END IF;

		SET V_DB_YLINE     = V_YLINE;


		SET V_DB_HANGCHANM = V_HANGCHANM;
		SET V_DB_BKHANGCHA = V_BKHANGCHA;
		SET V_DB_BKCHHWAJU = V_BKCHHWAJU;
		SET V_DB_IPHANG    = V_IPHANG;
		SET V_DB_JAKENDAT  = V_JAKENDAT;
		SET V_DB_BDATE     = V_BDATE;
		SET V_DB_GOKJONGNM = V_GOKJONGNM;
		SET V_DB_JCHQTY    = V_JCHQTY;
		SET V_DB_CHQTY     = V_CHQTY;
		SET V_DB_CHDAT     = V_CHDAT;
		SET V_DB_JEGOQTY   = V_JEGOQTY;
		SET V_DB_DANGA     = V_DANGA;
		SET V_DB_BOKAMT    = V_BOKAMT;
		SET V_DB_BIGO      = V_BIGO;
		SET V_DB_TOTAMT    = V_TOTAMT;
		SET V_DB_TOTVAT    = DECIMAL(V_TOTAMT * 0.1);
		SET V_DB_AMOUNT    = V_DB_TOTAMT + V_DB_TOTVAT;
		SET V_DB_BKYSDATE  = V_BKYSDATE;


		INSERT INTO SESSION.SILO_CSS2010
		(
			VNSAUPJA,
			VNSANGHO,
			VNIRUM,
			VNTAXJUSO,
			MONTH,
			YSNAME,
			JBEJNQTY,
			JYSQTY,
			FLDNAME,
			YDHWAJU,
			YLINE,
			HANGCHANM,
			BKHANGCHA,
			BKCHHWAJU,
			IPHANG,
			JAKENDAT,
			BDATE,
			GOKJONGNM,
			JCHQTY,
			CHQTY,
			CHDAT,
			JEGOQTY,
			DANGA,
			BOKAMT,
			BIGO,
			TOTAMT,
			TOTVAT,
			AMOUNT,
			BKYSDATE
		)
		VALUES
		(
			V_DB_VNSAUPJA,
			V_DB_VNSANGHO,
			V_DB_VNIRUM,
			V_DB_VNTAXJUSO,
			V_DB_MONTH,
			V_DB_YSNAME,
			V_DB_JBEJNQTY,
			V_DB_JYSQTY,
			V_DB_FLDNAME,
			V_DB_YDHWAJU,
			V_DB_YLINE,
			V_DB_HANGCHANM,
			V_DB_BKHANGCHA,
			V_DB_BKCHHWAJU,
			V_DB_IPHANG,
			V_DB_JAKENDAT,
			V_DB_BDATE,
			V_DB_GOKJONGNM,
			V_DB_JCHQTY,
			V_DB_CHQTY,
			V_DB_CHDAT,
			V_DB_JEGOQTY,
			V_DB_DANGA,
			V_DB_BOKAMT,
			V_DB_BIGO,
			V_DB_TOTAMT,
			V_DB_TOTVAT,
			V_DB_AMOUNT,
			V_DB_BKYSDATE
		);


	END FOR R1;
  
	PRINT : BEGIN  -- 출력

		DECLARE REFCURSOR CURSOR WITH RETURN FOR

			SELECT
			VNSAUPJA,
			VNSANGHO,
			VNIRUM,
			VNTAXJUSO,
			MONTH,
			YSNAME,
			JBEJNQTY,
			JYSQTY,
			FLDNAME,
			YDHWAJU,
			YLINE,
			HANGCHANM,
			BKHANGCHA,
			BKCHHWAJU,
			IPHANG,
			JAKENDAT,
			BDATE,
			GOKJONGNM,
			JCHQTY,
			CHQTY,
			CHDAT,
			JEGOQTY,
			DANGA,
			BOKAMT,
			BIGO,
			TOTAMT,
			TOTVAT,
			AMOUNT,
			BKYSDATE
			FROM SESSION.SILO_CSS2010;

		OPEN REFCURSOR;

	END PRINT;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS2010_PRINT('202104', 'C02');