--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1010_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1010_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE   VARCHAR(8),
	IN P_EDATE   VARCHAR(8),
        IN P_HWAJU   VARCHAR(50)) 

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부      

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS
				(
					SELECT
					IHHANGCHA,
					VSCODE.CDDESC1 AS VSDESC1,
					IHIPHANG,
					IHGOKJONG1,
					GKCODE.CDDESC1 AS GKDESC1,
					SKCODE.CDDESC1 AS SKDESC1,
					IHBLQTY1
					FROM TYSCMLIB.USIIPHAF AS IPHA
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE
					ON                 'GK' = GKCODE.CDINDEX
					AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE
					ON                 'SK' = SKCODE.CDINDEX
					AND     IPHA.IHSOSOK    = SKCODE.CDCODE
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE
					ON                 'VS' = VSCODE.CDINDEX
					AND      IPHA.IHHANGCHA = VSCODE.CDCODE
					WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
					AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF
							 WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
					ORDER BY IHHANGCHA
				),

				DETAIL AS
				(
					SELECT 
					ROW_NUMBER() OVER(ORDER BY IPIPDAT) AS ROWNO,
					IHHANGCHA,
					VSDESC1,
					IHIPHANG,
					IHGOKJONG1,
					GKDESC1,
					SKDESC1,
					IHBLQTY1,
					IPIPDAT, 
					TRIM(TO_CHAR(SUM(IPIPPQTY), '9,999,990.000')) AS IPIPQTY
					FROM 
					(
						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT1 AS IPIPDAT,
						IPIPPQTY1 AS IPIPPQTY
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY1 <> 0

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT2 AS IPIPDAT,    
						IPIPPQTY2 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY2 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT3 AS IPIPDAT,    
						IPIPPQTY3 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY3 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT4 AS IPIPDAT,    
						IPIPPQTY4 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY4 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT5 AS IPIPDAT,    
						IPIPPQTY5 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY5 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT6 AS IPIPDAT,    
						IPIPPQTY6 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY6 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT7 AS IPIPDAT,    
						IPIPPQTY7 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY7 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT8 AS IPIPDAT,    
						IPIPPQTY8 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY8 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT9 AS IPIPDAT,    
						IPIPPQTY9 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY9 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIPDAT10 AS IPIPDAT,   
						IPIPPQTY10 AS IPIPPQTY  
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY10 <> 0   

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT1 AS IPIPDAT,    
						IPIDQTY1 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY1 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT2 AS IPIPDAT,    
						IPIDQTY2 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY2 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT3 AS IPIPDAT,    
						IPIDQTY3 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY3 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT4 AS IPIPDAT,    
						IPIDQTY4 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY4 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT5 AS IPIPDAT,    
						IPIDQTY5 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY5 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT6 AS IPIPDAT,    
						IPIDQTY6 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY6 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT7 AS IPIPDAT,    
						IPIDQTY7 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY7 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT8 AS IPIPDAT,    
						IPIDQTY8 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY8 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT9 AS IPIPDAT,    
						IPIDQTY9 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY9 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IHBLQTY1,
						IPIDDAT10 AS IPIPDAT,   
						IPIDQTY10 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY10 <> 0

					) AS TEMP
					GROUP BY IPIPDAT, IHHANGCHA, VSDESC1, IHIPHANG, IHGOKJONG1, GKDESC1, SKDESC1, IHBLQTY1
				)

				SELECT
				(SELECT COUNT(*) FROM ORIGINAL_DATA) + 1 - A.ROWNO AS NO,A.*
				FROM DETAIL AS A
				WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) )AND CAST ( P_FNNUM AS VARCHAR ( 100 ) )
				ORDER BY ROWNO ASC;
			
			OPEN REFCURSOR;

		END LIST;
	  
		PAGING : BEGIN  -- 페이징 
			
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS
				(
					SELECT
					IHHANGCHA,
					VSCODE.CDDESC1 AS VSDESC1,
					IHIPHANG,
					IHGOKJONG1,
					GKCODE.CDDESC1 AS GKDESC1,
					SKCODE.CDDESC1 AS SKDESC1
					FROM TYSCMLIB.USIIPHAF AS IPHA
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE
					ON                 'GK' = GKCODE.CDINDEX
					AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE
					ON                 'SK' = SKCODE.CDINDEX
					AND     IPHA.IHSOSOK    = SKCODE.CDCODE
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE
					ON                 'VS' = VSCODE.CDINDEX
					AND      IPHA.IHHANGCHA = VSCODE.CDCODE
					WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE
					AND   IHSOSOK = (SELECT VNSOSOK FROM TYSCMLIB.USIVENDF
							 WHERE VNCODE IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable ))
					ORDER BY IHHANGCHA
				),

				DETAIL AS
				(
					SELECT 
					ROW_NUMBER() OVER(ORDER BY IPIPDAT) AS ROWNO,
					IHHANGCHA,
					VSDESC1,
					IHIPHANG,
					IHGOKJONG1,
					GKDESC1,
					SKDESC1,
					IPIPDAT, 
					TRIM(TO_CHAR(SUM(IPIPPQTY), '9,999,990.000')) AS IPIPQTY
					FROM 
					(
						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT1 AS IPIPDAT,
						IPIPPQTY1 AS IPIPPQTY
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY1 <> 0

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT2 AS IPIPDAT,    
						IPIPPQTY2 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY2 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT3 AS IPIPDAT,    
						IPIPPQTY3 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY3 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT4 AS IPIPDAT,    
						IPIPPQTY4 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY4 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT5 AS IPIPDAT,    
						IPIPPQTY5 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY5 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT6 AS IPIPDAT,    
						IPIPPQTY6 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY6 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT7 AS IPIPDAT,    
						IPIPPQTY7 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY7 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT8 AS IPIPDAT,    
						IPIPPQTY8 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY8 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT9 AS IPIPDAT,    
						IPIPPQTY9 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY9 <> 0    

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIPDAT10 AS IPIPDAT,   
						IPIPPQTY10 AS IPIPPQTY  
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIPPQTY10 <> 0   

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT1 AS IPIPDAT,    
						IPIDQTY1 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY1 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT2 AS IPIPDAT,    
						IPIDQTY2 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY2 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT3 AS IPIPDAT,    
						IPIDQTY3 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY3 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT4 AS IPIPDAT,    
						IPIDQTY4 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY4 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT5 AS IPIPDAT,    
						IPIDQTY5 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY5 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT6 AS IPIPDAT,    
						IPIDQTY6 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY6 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT7 AS IPIPDAT,    
						IPIDQTY7 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY7 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT8 AS IPIPDAT,    
						IPIDQTY8 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY8 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT9 AS IPIPDAT,    
						IPIDQTY9 AS IPIPPQTY    
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY9 <> 0     

						UNION ALL               

						SELECT
						IHHANGCHA,
						VSDESC1,
						IHIPHANG,
						IHGOKJONG1,
						GKDESC1,
						SKDESC1,
						IPIDDAT10 AS IPIPDAT,   
						IPIDQTY10 AS IPIPPQTY   
						FROM ORIGINAL_DATA 
						INNER JOIN TYSCMLIB.USIIPGOF 
						ON    IHHANGCHA  = IPHANGCHA
						AND   IHGOKJONG1 = IPGOKJONG
						WHERE IPIDQTY10 <> 0

					) AS TEMP
					GROUP BY IPIPDAT, IHHANGCHA, VSDESC1, IHIPHANG, IHGOKJONG1, GKDESC1, SKDESC1
				)

				SELECT
				COUNT(*) AS TOTALCOUNT
				FROM DETAIL;

			OPEN REFCURSOR2;

		END PAGING;

	END MAIN;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1010_LIST(1, 15, 20200101, 20210430, 'S70');