--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS  

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1010_GETTEXT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1010_GETTEXT ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_HANGCHA VARCHAR(6)) 

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부      

	      LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				WITH ORIGINAL_DATA AS
				(
					SELECT
					ROW_NUMBER() OVER() AS ROWNO,
					IHHANGCHA,                      
					VSCODE.CDDESC1 AS VSDESC1,      
					IHIPHANG,                       
					IHGOKJONG1,                     
					GKCODE.CDDESC1 AS GKDESC1,      
					SKCODE.CDDESC1 AS SKDESC1,      
					IHBLQTY1                        
					FROM TYSCMLIB.USIIPHAF AS IPHA 
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE 
					ON                 'GK' = GKCODE.CDINDEX     
					AND     IPHA.IHGOKJONG1 = GKCODE.CDCODE      
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE 
					ON                 'SK' = SKCODE.CDINDEX     
					AND     IPHA.IHSOSOK    = SKCODE.CDCODE      
					LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE 
					ON                 'VS' = VSCODE.CDINDEX     
					AND      IPHA.IHHANGCHA = VSCODE.CDCODE      
					WHERE IHHANGCHA = P_HANGCHA
				)

				SELECT
				*
				FROM ORIGINAL_DATA AS A
				WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) )AND CAST ( P_FNNUM AS VARCHAR ( 100 ) )
				ORDER BY ROWNO ASC;
			
			OPEN REFCURSOR;

		END LIST;
	  
		PAGING : BEGIN  -- 페이징 
			
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR

						SELECT
						COUNT(*) AS TOTALCOUNT
						FROM TYSCMLIB.USIIPHAF AS IPHA
						WHERE IHHANGCHA = P_HANGCHA;

			OPEN REFCURSOR2;

		END PAGING;

	END MAIN;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1010_GETTEXT(1, 15, '202101');
