--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2040_LIST;
  

SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","KSGPDM" ; 
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2040_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_DATE VARCHAR(6) , 
	IN P_HWAJU VARCHAR(50) , 
	IN P_GUBUN VARCHAR(1) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TYCSS_CSS2040_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부 
		IF P_GUBUN = 'S' THEN 
  
			LIST : BEGIN  -- 리스트 
				DECLARE REFCURSOR CURSOR WITH RETURN FOR 
					 
					WITH ORIGINAL_DATA AS 
					( 
						SELECT 
						LMYYMMDD , 
						( SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) ) AS IHIPHANG , 
						LMHANGCHA , 
						LMGOKJONG , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						LMBEJNQTY , 
						LMHJGONG , 
						LMHJVAT , 
						LMHJAMT AS TOTAL , 
						( DIGITS ( LMYYMMDD ) || LMHANGCHA || LMGOKJONG || LMHWAJU || LMJPNO ) AS GUBUN 
						FROM TYSCMLIB . USIMCLMF AS MCLM 
						LEFT OUTER JOIN TYSCMLIB . USIIPHAF IPHA 
						ON IPHA . IHHANGCHA = LMHANGCHA 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND MCLM . LMHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND MCLM . LMGOKJONG = GKCODE . CDCODE 
						WHERE LMMCYYMM = P_DATE 
						AND LMHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						'1' AS GUBUN1 , 
						DIGITS ( LMYYMMDD ) AS LMYYMMDD , 
						IHIPHANG , 
						LMHANGCHA , 
						LMGOKJONG , 
						VSDESC1 , 
						GKDESC1 , 
						LMBEJNQTY , 
						LMHJGONG , 
						LMHJVAT , 
						TOTAL , 
						GUBUN 
						FROM ORIGINAL_DATA 
  
						UNION ALL 
  
						SELECT 
						'2' AS GUBUN1 , 
						'' AS LMYYMMDD , 
						'' AS IHIPHANG , 
						'' AS LMHANGCHA , 
						'' AS LMGOKJONG , 
						'' AS VSDESC1 , 
						'' AS GKDESC1 , 
						0 AS LMBEJNQTY , 
						VALUE ( SUM ( LMHJGONG ) , 0 ) AS LMHJGONG , 
						VALUE ( SUM ( LMHJVAT ) , 0 ) AS LMHJVAT , 
						VALUE ( SUM ( TOTAL ) , 0 ) AS TOTAL , 
						'' AS GUBUN 
						FROM ORIGINAL_DATA 
					) 
  
					SELECT 
					ROWNO , 
					LMYYMMDD , 
					IHIPHANG , 
					LMHANGCHA , 
					LMGOKJONG , 
					VSDESC1 , 
					GKDESC1 , 
					TRIM(TO_CHAR(LMBEJNQTY, '9,999,990.000')) AS LMBEJNQTY , 
					LMHJGONG , 
					LMHJVAT , 
					TOTAL , 
					GUBUN 
					FROM 
					( 
						SELECT 
						ROW_NUMBER ( ) OVER ( ) AS ROWNO , 
						( CASE WHEN GUBUN1 IN ( '2' ) THEN '<div style="color:red" >합     계</div>' 
				ELSE LMYYMMDD END ) AS LMYYMMDD , 
						IHIPHANG , 
						LMHANGCHA , 
						LMGOKJONG , 
						VSDESC1 , 
						GKDESC1 , 
						LMBEJNQTY , 
						( CASE WHEN GUBUN1 IN ( '2' ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( LMHJGONG , '999,999,999,990' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( LMHJGONG , '999,999,999,990' ) ) END ) AS LMHJGONG , 
						( CASE WHEN GUBUN1 IN ( '2' ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( LMHJVAT , '999,999,999,990' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( LMHJVAT , '999,999,999,990' ) ) END ) AS LMHJVAT , 
						( CASE WHEN GUBUN1 IN ( '2' ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( TOTAL , '999,999,999,990' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( TOTAL , '999,999,999,990' ) ) END ) AS TOTAL , 
						GUBUN 
						FROM DETAIL 
						ORDER BY GUBUN1 , GUBUN 
					) AS TEMP 
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) ; 
  
				OPEN REFCURSOR ; 
  
			END LIST ; 
  
			PAGING : BEGIN  -- 페이징 
				DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
  
					WITH ORIGINAL_DATA AS 
					( 
						SELECT 
						LMYYMMDD , 
						( SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) ) AS IHIPHANG , 
						LMHANGCHA , 
						LMGOKJONG , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						LMBEJNQTY , 
						LMHJGONG , 
						LMHJVAT , 
						LMHJAMT AS TOTAL , 
						( DIGITS ( LMYYMMDD ) || LMHANGCHA || LMGOKJONG || LMHWAJU || LMJPNO ) AS GUBUN 
						FROM TYSCMLIB . USIMCLMF AS MCLM 
						LEFT OUTER JOIN TYSCMLIB . USIIPHAF IPHA 
						ON IPHA . IHHANGCHA = LMHANGCHA 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND MCLM . LMHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TYSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND MCLM . LMGOKJONG = GKCODE . CDCODE 
						WHERE LMMCYYMM = P_DATE 
						AND LMHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						'1' AS GUBUN1 , 
						DIGITS ( LMYYMMDD ) AS LMYYMMDD , 
						IHIPHANG , 
						LMHANGCHA , 
						LMGOKJONG , 
						VSDESC1 , 
						GKDESC1 , 
						TRIM(TO_CHAR(LMBEJNQTY, '9,999,990.000')) AS LMBEJNQTY , 
						LMHJGONG , 
						LMHJVAT , 
						TOTAL , 
						GUBUN 
						FROM ORIGINAL_DATA 
  
						UNION ALL 
  
						SELECT 
						'2' AS GUBUN1 , 
						'' AS LMYYMMDD , 
						'' AS IHIPHANG , 
						'' AS LMHANGCHA , 
						'' AS LMGOKJONG , 
						'' AS VSDESC1 , 
						'' AS GKDESC1 , 
						0 AS LMBEJNQTY , 
						VALUE ( SUM ( LMHJGONG ) , 0 ) AS LMHJGONG , 
						VALUE ( SUM ( LMHJVAT ) , 0 ) AS LMHJVAT , 
						VALUE ( SUM ( TOTAL ) , 0 ) AS TOTAL , 
						'' AS GUBUN 
						FROM ORIGINAL_DATA 
					) 
  
					SELECT 
					COUNT ( * ) AS TOTALCOUNT 
					FROM DETAIL ; 
  
				OPEN REFCURSOR2 ; 
  
			END PAGING ; 
  
		ELSE 
  
			PRINT : BEGIN  -- 페이징 
				DECLARE REFCURSOR3 CURSOR WITH RETURN FOR 
  
					SELECT 
					( SUBSTR ( VEND . VNSAUPJA , 1 , 3 ) || '-' || SUBSTR ( VEND . VNSAUPJA , 4 , 2 ) || '-' || SUBSTR ( VEND . VNSAUPJA , 6 , 5 ) ) AS VNSAUPJA , 
					VEND . VNSANGHO , 
					VEND . VNIRUM , 
					VEND . VNTAXJUSO , 
					( SUBSTR ( CHAR ( LMMCYYMM ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( LMMCYYMM ) , 5 , 2 ) ) AS MONTH , 
					( SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 4 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) || ' / ' || SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 5 , 2 ) ) AS IHIPHANG , 
					VSCD . CDDESC1 AS HANGCHANM , 
					GKCD . CDDESC1 AS GOKJONGNM , 
					( CASE WHEN LMBEJNQTY = 0 THEN ( JEGO . JGBEJNQTY + JEGO . JGBEIPQTY - JEGO . JGBECHQTY ) ELSE LMBEJNQTY END ) AS BEJNQTY , 
					LMHJGONG , 
					LMHJVAT , 
					LMHJAMT , 
					( DIGITS ( LMYYMMDD ) || LMHANGCHA || LMGOKJONG || LMHWAJU || LMJPNO ) AS GUBUN 
					FROM TYSCMLIB . USIMCLMF 
					LEFT OUTER JOIN TYSCMLIB . USIVENDF VEND 
					ON VEND . VNCODE = LMHWAJU 
					LEFT OUTER JOIN TYSCMLIB . USIIPHAF IPHA 
					ON IPHA . IHHANGCHA = LMHANGCHA 
					LEFT OUTER JOIN TYSCMLIB . USICODEF VSCD 
					ON VSCD . CDINDEX = 'VS' 
					AND VSCD . CDCODE = LMHANGCHA 
					LEFT OUTER JOIN TYSCMLIB . USICODEF GKCD 
					ON GKCD . CDINDEX = 'GK' 
					AND GKCD . CDCODE = LMGOKJONG 
					LEFT OUTER JOIN TYSCMLIB . USIJEGOF JEGO 
					ON JEGO . JGHANGCHA = LMHANGCHA 
					AND JEGO . JGGOKJONG = LMGOKJONG 
					AND JEGO . JGHWAJU = ( CASE WHEN LMHANGCHA <= '200336' AND LMHWAJU = 'S31' THEN 'S03' 
								WHEN LMHWAJU = 'P10' THEN 'C15' 
								ELSE LMHWAJU 
							END ) 
					WHERE LMMCYYMM = P_DATE 
					AND LMHWAJU IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					ORDER BY LMMCYYMM , LMHANGCHA , LMGOKJONG ; 
  
				OPEN REFCURSOR3 ; 
  
			END PRINT ; 
  
		END IF ; 
  
	END MAIN ; 
END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE TYJINFWLIB.SP_TYCSS_CSS2040_LIST 
TO KSGPDM WITH GRANT OPTION ; 


CALL TYJINFWLIB.SP_TYCSS_CSS2040_LIST(1, 15, 202103, 'C02', 'S');