--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1030_PRINT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TYCSS_CSS1030_PRINT ( 
	IN P_SDATE   VARCHAR(8),
	IN P_EDATE   VARCHAR(8),
	IN P_HWAJU   VARCHAR(30))

LANGUAGE SQL
RESULT SETS 2
    
P1 : BEGIN  -- 시작 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 

	DECLARE V_DATE VARCHAR(30);
  
	PRINT : BEGIN  -- 출력

		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT                     
			IPHA.IHHANGCHA,
			VSCODE.CDDESC1 AS VSDESC1,
			IPGO.IPGOKJONG,
			GKCODE.CDDESC1 AS GKDESC1,
			SKCODE.CDDESC1 AS SKDESC1,
			WNCODE.CDDESC1 AS WNDESC1,
			(SUBSTR(CHAR(IHIPHANG),1,4)||'/'||SUBSTR(CHAR(IHIPHANG),5,2)||'/'||SUBSTR(CHAR(IHIPHANG),7,2)) AS IHIPHANG,
			(SUBSTR(CHAR(IHJAKENDAT),1,4)||'/'||SUBSTR(CHAR(IHJAKENDAT),5,2)||'/'||SUBSTR(CHAR(IHJAKENDAT),7,2)) AS IHJAKENDAT,
			(SUBSTR(CHAR(IPIPSTDAT),1,4)||'/'||SUBSTR(CHAR(IPIPSTDAT),5,2)||'/'||SUBSTR(CHAR(IPIPSTDAT),7,2)) AS IPIPSTDAT,
			IHJUKHANO,
			(JBBEJNQTY + JBBEIPQTY - JBBECHQTY) AS JBBEJNQTY,
			(JBHWAKQTY + JBHWIPQTY - JBHWCHQTY) AS JBHWAKQTY,
			((JBBEJNQTY + JBBEIPQTY - JBBECHQTY) - (JBHWAKQTY + JBHWIPQTY - JBHWCHQTY)) AS GAMQTY,
			HJCODE.CDDESC1 AS HJDESC1
			FROM TYSCMLIB.USIIPHAF AS IPHA
			LEFT OUTER JOIN TYSCMLIB.USIIPGOF AS IPGO
			ON         IPHA.IHHANGCHA = IPGO.IPHANGCHA
			LEFT OUTER JOIN TYSCMLIB.USIJEBLF AS JEBL
			ON         IPGO.IPHANGCHA = JEBL.JBHANGCHA
			AND        IPGO.IPGOKJONG = JEBL.JBGOKJONG
			LEFT OUTER JOIN TYSCMLIB.USICODEF AS VSCODE
			ON                   'VS' = VSCODE.CDINDEX
			AND        IPHA.IHHANGCHA = VSCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.USICODEF AS GKCODE
			ON                   'GK' = GKCODE.CDINDEX
			AND        IPGO.IPGOKJONG = GKCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.USICODEF AS SKCODE
			ON                   'SK' = SKCODE.CDINDEX
			AND        IPHA.IHSOSOK   = SKCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.USICODEF AS WNCODE
			ON                   'WN' = WNCODE.CDINDEX
			AND        IPHA.IHWONSAN1 = WNCODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.USICODEF AS HJCODE
			ON                   'HJ' = HJCODE.CDINDEX
			AND        JEBL.JBHWAJU   = HJCODE.CDCODE
			WHERE SUBSTR(CHAR(IPHA.IHIPHANG),1,6) BETWEEN P_SDATE AND P_EDATE
			AND   JEBL.JBHWAJU IN(SELECT * FROM TABLE(TYSCMLIB.SF_GB_RevColRow(CAST(P_HWAJU AS VARCHAR(100)), ',')) AS InTable )
			AND   (JEBL.JBBEJNQTY + JEBL.JBBEIPQTY - JEBL.JBBECHQTY) <> 0
			AND   (JEBL.JBHWAKQTY + JEBL.JBHWIPQTY - JEBL.JBHWCHQTY) <> 0
			ORDER BY IPHA.IHHANGCHA, IPGO.IPGOKJONG;

		OPEN REFCURSOR;

	END PRINT;
END P1;


CALL TYJINFWLIB.SP_TYCSS_CSS1030_PRINT('20210101', '20210430', 'S70');

