--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_RUN ( 
	IN P_PBDCNTCODE VARCHAR(2),
	IN P_PBDLCODE VARCHAR(3),
	IN P_PBDMCODE VARCHAR(3),
	IN P_PBDSCODE VARCHAR(3),
	IN P_PBDNUM NUMERIC(3,0),
	IN P_PBDMOSEQ NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PBDLCODE,
		PBDMCODE,
		PBDSCODE,
		PBDNUM,
		PBDMOSEQ,
		PBDMOSABUN,
		INKI.KBHANGL,
		PBDMODESC,
		PBDMODATE
		FROM PSSCMLIB.PSM_BOARD_DETAIL
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS INKI
		ON  INKI.KBSABUN = PBDMOSABUN
		WHERE  PBDCNTCODE = P_PBDCNTCODE
		AND    PBDLCODE = P_PBDLCODE
		AND    PBDMCODE = P_PBDMCODE
		AND    PBDSCODE = P_PBDSCODE
		AND    PBDNUM = P_PBDNUM
		AND    PBDMOSEQ = P_PBDMOSEQ
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 