DROP PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_ADD ( 
	IN P_PBDCNTCODE VARCHAR(2) , 
	IN P_PBDLCODE VARCHAR(3) , 
	IN P_PBDMCODE VARCHAR(3) , 
	IN P_PBDSCODE VARCHAR(3) , 
	IN P_PBDNUM NUMERIC(3,0) , 
	IN P_PBDMOSEQ NUMERIC(3,0) , 
	IN P_PBDMOSABUN VARCHAR(6),
	IN P_PBDMODESC VARCHAR(100),
	IN P_PBDMODATE VARCHAR(8),
	IN P_PBDHISAB VARCHAR(6)) 
	LANGUAGE SQL 
	P1 : BEGIN 

	DECLARE V_PBDMOSEQ NUMERIC(3,0) ; 
	 
	IF P_PBDMOSEQ = 0 THEN
  
		SELECT   VALUE(MAX(PBDMOSEQ), 0) + 1 INTO V_PBDMOSEQ
		FROM PSSCMLIB.PSM_BOARD_DETAIL
		WHERE PBDCNTCODE = P_PBDCNTCODE
		AND   PBDLCODE   = P_PBDLCODE
		AND   PBDMCODE   = P_PBDMCODE
		AND   PBDSCODE   = P_PBDSCODE 
		AND   PBDNUM   = P_PBDNUM ;

		INSERT INTO PSSCMLIB.PSM_BOARD_DETAIL
		(
		PBDCNTCODE ,
		PBDLCODE  ,
		PBDMCODE  ,
		PBDSCODE  ,
		PBDNUM    ,
		PBDMOSEQ  ,	
		PBDMOSABUN,
		PBDMODESC ,
		PBDMODATE ,
		PBDHIGB   ,
		PBDHIDAT  ,
		PBDHITIM  ,
		PBDHISAB  
		)
		VALUES
		(
		P_PBDCNTCODE ,
		P_PBDLCODE  ,
		P_PBDMCODE  ,
		P_PBDSCODE  ,
		P_PBDNUM    ,
		V_PBDMOSEQ ,
		P_PBDMOSABUN ,
		P_PBDMODESC ,
		P_PBDMODATE ,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_PBDHISAB
		);
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_BOARD_DETAIL SET
		PBDMOSABUN = P_PBDMOSABUN,
		PBDMODESC = P_PBDMODESC,
		PBDMODATE = P_PBDMODATE,
		PBDHIGB     = 'C',
		PBDHIDAT    = CURRENT_DATE,
		PBDHITIM    = CURRENT_TIME,
		PBDHISAB    = P_PBDHISAB
		WHERE PBDCNTCODE = P_PBDCNTCODE
		AND   PBDLCODE   = P_PBDLCODE
		AND   PBDMCODE   = P_PBDMCODE
		AND   PBDSCODE   = P_PBDSCODE
		AND   PBDNUM     = P_PBDNUM
		AND   PBDMOSEQ   = P_PBDMOSEQ ;
		
		
  
	END IF ; 
  
END P1  ; 
  
  
