--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE PSSCMLIB.PSM_PSM2010_BOARD_MAST_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2010_BOARD_MAST_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_PBMCNTCODE VARCHAR(2),
	IN P_PBMLCODE VARCHAR(3),
	IN P_PBMMCODE VARCHAR(3),
	IN P_PBMSCODE VARCHAR(3),
	IN P_PBMTITLE VARCHAR(100),
	IN P_PBMPUSABUN VARCHAR(6)) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM2010_BOARD_MAST_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 4000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 4000 ) ; 
  
PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
      LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR  -- 커서생성 
			WITH ORIGINAL_DATA AS (
			SELECT ROW_NUMBER() OVER(ORDER BY PBMLCODE, PBMMCODE, PBMSCODE, PBMNUM DESC) AS ROWNO,
			       PBMLCODE,
				CL1.PBC1NAME,
				PBMMCODE,
				CL2.PBC2NAME,
				PBMSCODE,
				CL3.PBC3NAME,
				PBMNUM,
				SUBSTR(PBMPUDATE,1,4) || '-' || SUBSTR(PBMPUDATE,5,2) || '-' || SUBSTR(PBMPUDATE,7,2) AS PBMPUDATE,
				PBMPUSABUN,
				KBHANGL,
				PBMTITLE
			FROM PSSCMLIB.PSM_BOARD_MAST
			LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS1 AS CL1
			ON   CL1.PBC1NTCODE = PBMCNTCODE
			AND  CL1.PBC1LCODE = PBMLCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS2 AS CL2
			ON  CL2.PBC2NTCODE = PBMCNTCODE
			AND CL2.PBC2LCODE = PBMLCODE
			AND CL2.PBC2MCODE = PBMMCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS3 AS CL3
			ON  CL3.PBC3NTCODE = PBMCNTCODE
			AND CL3.PBC3LCODE = PBMLCODE
			AND CL3.PBC3MCODE = PBMMCODE
			AND CL3.PBC3SCODE = PBMSCODE
			LEFT OUTER JOIN TYSCMLIB.INKIBNMF
			ON   KBSABUN = PBMPUSABUN
			WHERE PBMCNTCODE = P_PBMCNTCODE
			AND    PBMLCODE = P_PBMLCODE
			AND   (CASE WHEN P_PBMMCODE = '' THEN 1 ELSE PBMMCODE END) = (CASE WHEN P_PBMMCODE = '' THEN 1 ELSE P_PBMMCODE END)
			AND   (CASE WHEN P_PBMSCODE = '' THEN 1 ELSE PBMSCODE END) = (CASE WHEN P_PBMSCODE = '' THEN 1 ELSE P_PBMSCODE END)
			AND   (CASE WHEN P_PBMPUSABUN = '' THEN '1' ELSE PBMPUSABUN END) = (CASE WHEN P_PBMPUSABUN = '' THEN '1' ELSE P_PBMPUSABUN END)
			AND   PBMTITLE   LIKE  '%' || PBMTITLE || '%'
			ORDER BY PBMLCODE, PBMMCODE, PBMSCODE, PBMNUM DESC
			)
			SELECT
			*
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC ;

		OPEN REFCURSOR ;

	END LIST ;  

	PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR  -- 커서생성 
				SELECT   COUNT(*) AS TOTALCOUNT
				FROM PSSCMLIB.PSM_BOARD_MAST
				LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS1 AS CL1
				ON   CL1.PBC1NTCODE = PBMCNTCODE
				AND  CL1.PBC1LCODE = PBMLCODE
				LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS2 AS CL2
				ON  CL2.PBC2NTCODE = PBMCNTCODE
				AND CL2.PBC2LCODE = PBMLCODE
				AND CL2.PBC2MCODE = PBMMCODE
				LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS3 AS CL3
				ON  CL3.PBC3NTCODE = PBMCNTCODE
				AND CL3.PBC3LCODE = PBMLCODE
				AND CL3.PBC3MCODE = PBMMCODE
				AND CL3.PBC3SCODE = PBMSCODE
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF
				ON   KBSABUN = PBMPUSABUN
				WHERE PBMCNTCODE = P_PBMCNTCODE
				AND   PBMLCODE = P_PBMLCODE
				AND   (CASE WHEN P_PBMMCODE = '' THEN 1 ELSE PBMMCODE END) = (CASE WHEN P_PBMMCODE = '' THEN 1 ELSE P_PBMMCODE END)
				AND   (CASE WHEN P_PBMSCODE = '' THEN 1 ELSE PBMSCODE END) = (CASE WHEN P_PBMSCODE = '' THEN 1 ELSE P_PBMSCODE END)
				AND   (CASE WHEN P_PBMPUSABUN = '' THEN '1' ELSE PBMPUSABUN END) = (CASE WHEN P_PBMPUSABUN = '' THEN '1' ELSE P_PBMPUSABUN END)
				AND   PBMTITLE   LIKE  '%' || PBMTITLE || '%' ;
			OPEN REFCURSOR2 ; 
	END PAGING ; 
END MAIN ; 
END  ;
