DROP PROCEDURE TYJINFWLIB.PSM_PID_LIST;

CREATE PROCEDURE TYJINFWLIB.PSM_PID_LIST
( 
	
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (
			
					SELECT   DISTINCT
					1 as LVL, 
					'AAA' AS UP_MENU_NO,
					HSPLCODE AS MENU_NO,                        
					HSPLCODE AS MENU_NAME,
					DIGITS(HSINDEX) AS INDEX
					FROM  TYSCMLIB.PSM_Hazoap_Section
			 ), TABLE2 AS (
			SELECT  ROWNUMBER() OVER(order by LVL, int(MENU_NO)) AS rownum,  LVL, UP_MENU_NO, MENU_NO,   MENU_NAME, CDDESC1 AS CODE_NAME
			FROM TABLE1
			LEFT OUTER JOIN TYSCMLIB.PSM_CODEMF
				ON CDINDEX = 'H1'
			  AND CDCODE = MENU_NO
			)
			SELECT LVL, UP_MENU_NO, MENU_NO,   MENU_NAME,  CODE_NAME
			FROM TABLE2
			UNION  ALL
			SELECT   2 AS LVL,
					 A.AFDOCNUM UP_MENU_NO,
					 A.AFDOCNUM||'_'||A.AFSEQ AS MENU_NO,
					 A.AFDOCNUM AS MENU_NAME,
					 A.AFSEQ||'_'||AFFILENAME  AS CODE_NAME
			FROM    TYSCMLIB.PSM_ATTACHFILE A
			WHERE AFDOCID = '01'
			ORDER BY LVL, UP_MENU_NO;

		
	OPEN REFCURSOR;

END