--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_MAST_SEQ ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_MAST_SEQ ( 
	IN P_PBMCNTCODE VARCHAR(2),
	IN P_PBMLCODE VARCHAR(3),
	IN P_PBMMCODE VARCHAR(3),
	IN P_PBMSCODE VARCHAR(3)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM2011_BOARD_MAST_SEQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT   VALUE(MAX(PBMNUM), 0) + 1 AS PBMNUM
			FROM PSSCMLIB.PSM_BOARD_MAST
			WHERE PBMCNTCODE = P_PBMCNTCODE
			AND   PBMLCODE   = P_PBMLCODE
			AND   PBMMCODE   = P_PBMMCODE
			AND   PBMSCODE   = P_PBMSCODE ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 

