--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM2010_PBMMCODE_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2010_PBMMCODE_LIST ( 
	IN P_PBMCNTCODE VARCHAR(2),
	IN P_PBMLCODE VARCHAR(3),
	IN P_GUBUN VARCHAR(1)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM2010_PBMMCODE_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			'' AS PBC2LCODE,
			'' AS PBC2MCODE,
			'전체' AS PBC2NAME,
			'' AS PBC2BIGO
			FROM SYSIBM.SYSDUMMY1
			WHERE CASE WHEN P_GUBUN = '' THEN '1' ELSE '' END = CASE WHEN P_GUBUN = '' THEN '2' ELSE '' END

			UNION ALL
			 
			SELECT
			PBC2LCODE,
			PBC2MCODE,
			PBC2NAME,
			PBC2BIGO
			FROM PSSCMLIB.PSM_BOARD_CLASS2
			WHERE    PBC2NTCODE = P_PBMCNTCODE
			AND      PBC2LCODE = P_PBMLCODE
			ORDER BY PBC2LCODE, PBC2MCODE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 