--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_MAST_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_MAST_DEL ( 
	IN P_PBMCNTCODE VARCHAR(2) , 
	IN P_PBMLCODE VARCHAR(3) , 
	IN P_PBMMCODE VARCHAR(3) , 
	IN P_PBMSCODE VARCHAR(3) , 
	IN P_PBMNUM NUMERIC(3,0)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM2011_BOARD_MAST_DEL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	 
		-- 마스터 삭제
		DELETE FROM PSSCMLIB.PSM_BOARD_MAST
		WHERE PBMCNTCODE = P_PBMCNTCODE
		AND   PBMLCODE = P_PBMLCODE
		AND   PBMMCODE = P_PBMMCODE
		AND   PBMSCODE = P_PBMSCODE
		AND   PBMNUM   = P_PBMNUM ;

		-- 디테일 삭제
		DELETE
		FROM PSSCMLIB.PSM_BOARD_DETAIL
		WHERE PBDCNTCODE = P_PBMCNTCODE
		AND   PBDLCODE = P_PBMLCODE
		AND   PBDMCODE = P_PBMMCODE
		AND   PBDSCODE = P_PBMSCODE
		AND   PBDNUM   = P_PBMNUM ;

		-- 첨부파일 삭제
		DELETE FROM PSSCMLIB . PSM_CMN_ATTACH
		WHERE ATTACH_TYPE = P_PBMCNTCODE
		AND    SUBSTR(ATTACH_NO,1,2) = P_PBMCNTCODE
		AND    SUBSTR(ATTACH_NO,3,3) = P_PBMLCODE
		AND    SUBSTR(ATTACH_NO,6,3) = P_PBMMCODE
		AND    SUBSTR(ATTACH_NO,9,3) = P_PBMSCODE
		AND    CAST(SUBSTR(ATTACH_NO,12,3) AS NUMERIC(3, 0)) = P_PBMNUM ;
  
END P1  ; 
  