--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_MAST_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_MAST_RUN ( 
	IN P_PBMCNTCODE VARCHAR(2),
	IN P_PBMLCODE VARCHAR(3),
	IN P_PBMMCODE VARCHAR(3),
	IN P_PBMSCODE VARCHAR(3),
	IN P_PBMNUM NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM2011_BOARD_MAST_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PBMLCODE,
		CL1.PBC1NAME AS PBMLCODENM,
		PBMMCODE,
		CL2.PBC2NAME AS PBMMCODENM,
		PBMSCODE,
		CL3.PBC3NAME AS PBMSCODENM,
		PBMNUM,
		PBMPUDATE,
		PBMPUSABUN,
		INKI.KBHANGL,
		PBMTITLE
		FROM PSSCMLIB.PSM_BOARD_MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS1 AS CL1
		ON  CL1.PBC1NTCODE = PBMCNTCODE
		AND CL1.PBC1LCODE = PBMLCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS2 AS CL2
		ON  CL2.PBC2NTCODE = PBMCNTCODE
		AND CL2.PBC2LCODE = PBMLCODE
		AND CL2.PBC2MCODE = PBMMCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_BOARD_CLASS3 AS CL3
		ON  CL3.PBC3NTCODE = PBMCNTCODE
		AND CL3.PBC3LCODE = PBMLCODE
		AND CL3.PBC3MCODE = PBMMCODE
		AND CL3.PBC3SCODE = PBMSCODE
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS INKI
		ON  INKI.KBSABUN = PBMPUSABUN
		WHERE PBMCNTCODE = P_PBMCNTCODE
		AND    PBMLCODE = P_PBMLCODE
		AND    PBMMCODE = P_PBMMCODE
		AND    PBMSCODE = P_PBMSCODE
		AND    PBMNUM = P_PBMNUM
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 