--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_CHECK ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_CHECK ( 
	IN P_PBDCNTCODE VARCHAR(2),
	IN P_PBDLCODE VARCHAR(3),
	IN P_PBDMCODE VARCHAR(3),
	IN P_PBDSCODE VARCHAR(3),
	IN P_PBDNUM NUMERIC(3,0),
	IN P_PBDMODATE VARCHAR(8)
	) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM2011_BOARD_DETAIL_CHECK 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			*
			FROM PSSCMLIB.PSM_BOARD_DETAIL
			WHERE PBDCNTCODE = P_PBDCNTCODE
			AND    PBDLCODE = P_PBDLCODE
			AND    PBDMCODE = P_PBDMCODE
			AND    PBDSCODE = P_PBDSCODE
			AND    PBDNUM = P_PBDNUM
			AND    PBDMODATE > P_PBDMODATE
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 