DROP PROCEDURE TYJINFWLIB.PSM_ATTACHFILE_DOWN;

CREATE PROCEDURE TYJINFWLIB.PSM_ATTACHFILE_DOWN
( 
	P_AFFILENAME   VARCHAR(50)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
	SELECT 
		 AFDOCID ,
		 AFDOCNUM,
		 AFSEQ   ,
		 AFFILENAME,
		 AFFILESIZE,
		 AFBINARY  
		FROM TYSCMLIB.PSM_AttachFile
		WHERE  AFFILENAME  = P_AFFILENAME;

		
	OPEN REFCURSOR;

END
;