DROP PROCEDURE PSSCMLIB.PSM_PSM2010_BOARD_MENU_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM2010_BOARD_MENU_LIST
( 
	IN P_PBC1NTCODE   VARCHAR(2)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT
		1 AS LVL,
		'000' AS UP_MENU_NO,
		PBC1LCODE AS MENU_NO,
		PBC1LCODE AS MENU_CODE,
		REPLACE(PBC1NAME, 'amp;','') AS MENU_NAME
		FROM PSSCMLIB.PSM_BOARD_CLASS1
		WHERE PBC1NTCODE = P_PBC1NTCODE
		ORDER BY PBC1LCODE;

		
	OPEN REFCURSOR;

END