
CREATE VIEW PSSCMLIB.CV_PSM_WORKSTATUSLIST ( 
	APP_NUM , 
	WOORTEAM , 
	WOORDATE , 
	WOSEQ , 
	WOORSABUN , 
	WOWORKTITLE FOR COLUMN WOWOR00001 , 
	WOSTATUSCODE FOR COLUMN WOSTA00001 , 
	WOSTATUS ) 
	AS 
	SELECT  
						 WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APP_NUM,  
						 WOORTEAM ,  
						 WOORDATE ,  
						 DIGITS(WOSEQ) AS WOSEQ,  
						 WOORSABUN,  
						 WOWORKTITLE,  
						 PSSCMLIB.SF_PSM_WKORDER_STATUS(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE') AS WOSTATUSCODE,  
						 PSSCMLIB.SF_PSM_WKORDER_STATUS(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'NAME') AS WOSTATUS  
						FROM PSSCMLIB.PSM_W00001 ; 
  
LABEL ON TABLE PSSCMLIB.CV_PSM_WORKSTATUSLIST 
	IS 'PSM 작업요청현재상태표시VIEW' ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_WORKSTATUSLIST 
( WOORTEAM TEXT IS '요청부서' , 
	WOORDATE TEXT IS '요청일자' , 
	WOORSABUN TEXT IS '요청자' , 
	WOWORKTITLE TEXT IS '작업명' ) ; 
  