
CREATE VIEW PSSCMLIB.CV_PSM_WORK_FINAL_APPROVAL ( 
	APP_NUM , 
	WOAPPORSABUN FOR COLUMN WOAPP00001 , 
	WOAPPORSABUNNM FOR COLUMN WOAPP00002 , 
	WOAPPREVSABUN FOR COLUMN WOAPP00003 , 
	WOAPPREVSABUNNM FOR COLUMN WOAPP00004 ) 
	AS 
	SELECT  
						WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APP_NUM,  
						( CASE WHEN WOAPPSOSABUN5 <> '' AND WOAPPSODATE5 <> '' THEN WOAPPSOSABUN5  
						 WHEN WOAPPSOSABUN4 <> '' AND WOAPPSODATE4 <> '' THEN WOAPPSOSABUN4  
						 WHEN WOAPPSOSABUN3 <> '' AND WOAPPSODATE3 <> '' THEN WOAPPSOSABUN3  
						 WHEN WOAPPSOSABUN2 <> '' AND WOAPPSODATE2 <> '' THEN WOAPPSOSABUN2  
						 WHEN WOAPPSOSABUN1 <> '' AND WOAPPSODATE1 <> '' THEN WOAPPSOSABUN1 END ) AS WOAPPORSABUN ,  
						( CASE WHEN WOAPPSOSABUN5 <> '' AND WOAPPSODATE5 <> '' THEN WOAPPSONAME5  
						 WHEN WOAPPSOSABUN4 <> '' AND WOAPPSODATE4 <> '' THEN WOAPPSONAME4  
						 WHEN WOAPPSOSABUN3 <> '' AND WOAPPSODATE3 <> '' THEN WOAPPSONAME3  
						 WHEN WOAPPSOSABUN2 <> '' AND WOAPPSODATE2 <> '' THEN WOAPPSONAME2  
						 WHEN WOAPPSOSABUN1 <> '' AND WOAPPSODATE1 <> '' THEN WOAPPSONAME1 END ) AS WOAPPORSABUNNM ,  
						( CASE WHEN WOAPPRESABUN5 <> '' AND WOAPPREDATE5 <> '' THEN WOAPPRESABUN5  
						 WHEN WOAPPRESABUN4 <> '' AND WOAPPREDATE4 <> '' THEN WOAPPRESABUN4  
						 WHEN WOAPPRESABUN3 <> '' AND WOAPPREDATE3 <> '' THEN WOAPPRESABUN3  
						 WHEN WOAPPRESABUN2 <> '' AND WOAPPREDATE2 <> '' THEN WOAPPRESABUN2  
						 WHEN WOAPPRESABUN1 <> '' AND WOAPPREDATE1 <> '' THEN WOAPPRESABUN1 END ) AS WOAPPREVSABUN ,  
						( CASE WHEN WOAPPRESABUN5 <> '' AND WOAPPREDATE5 <> '' THEN WOAPPRENAME5  
						 WHEN WOAPPRESABUN4 <> '' AND WOAPPREDATE4 <> '' THEN WOAPPRENAME4 
						 WHEN WOAPPRESABUN3 <> '' AND WOAPPREDATE3 <> '' THEN WOAPPRENAME3  
						 WHEN WOAPPRESABUN2 <> '' AND WOAPPREDATE2 <> '' THEN WOAPPRENAME2  
						 WHEN WOAPPRESABUN1 <> '' AND WOAPPREDATE1 <> '' THEN WOAPPRENAME1 END ) AS WOAPPREVSABUNNM  
					FROM PSSCMLIB.PSM_W00001 ; 
  
LABEL ON TABLE PSSCMLIB.CV_PSM_WORK_FINAL_APPROVAL 
	IS 'PSM 작업요청 최종 결재자VIEW' ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_WORK_FINAL_APPROVAL 
( WOAPPORSABUN TEXT IS '요청자' , 
	WOAPPORSABUNNM TEXT IS '요청자명' , 
	WOAPPREVSABUN TEXT IS '수신자' , 
	WOAPPREVSABUNNM TEXT IS '수신자명' ) ; 