
CREATE VIEW PSSCMLIB.CV_PSM_MAINCSAFEDOCNEXT ( 
	SMWKTEAM , 
	SMWKDATE , 
	SMWKSEQ , 
	SMSABUN ) 
	AS 
	WITH TABLE1 AS ( 
			SELECT SMWKTEAM, 
				 SMWKDATE, 
				 SMWKSEQ, 
				 SMWKORAPPDATE, 
				 SMWKORSEQ, 
				SMORSABUN , SMORAPPDATE ,  
				SMGRSABUN , SMGRAPPDATE ,  
				SMCOSABUN , SMCOAPPDATE ,  
				SMSMSABUN , SMSMAPPDATE ,  
				( SELECT COUNT ( * )  
				FROM PSSCMLIB.PSM_S00005  
				WHERE SWWKTEAM = SMWKTEAM  
				AND SWWKDATE = SMWKDATE  
				AND SWWKSEQ = SMWKSEQ  
				AND SWORAPPDATE = SMWKORAPPDATE  
				AND SWORSEQ = SMWKORSEQ  
				AND SWWKCODE >= '04' ) AS SAFECNT  
			FROM PSSCMLIB.PSM_S00004  
			WHERE ( SMORAPPDATE = '' OR SMGRAPPDATE = '' OR SMCOAPPDATE = '' OR SMSMAPPDATE = '' )  
			 AND SMFSSABUN = ''  
			 ), TABLE2 AS ( 
			 SELECT SMWKTEAM, 
				 SMWKDATE, 
				 SMWKSEQ,	  
				 SMWKORAPPDATE, 
				 SMWKORSEQ, 
				 CASE WHEN SAFECNT > 0 THEN 
	  
				 CASE WHEN (SMSMSABUN != '' AND SMSMAPPDATE = '') THEN SMSMSABUN	  
					 WHEN (SMSMSABUN != '' AND SMSMAPPDATE != '') AND (SMCOSABUN != '' AND SMCOAPPDATE = '') THEN SMCOSABUN 
					 WHEN (SMSMSABUN != '' AND SMSMAPPDATE != '') AND (SMCOSABUN != '' AND SMCOAPPDATE != '') AND (SMORSABUN != '' AND SMORAPPDATE = '') THEN SMORSABUN	  
					 WHEN (SMSMSABUN != '' AND SMSMAPPDATE != '') AND (SMCOSABUN != '' AND SMCOAPPDATE != '') AND (SMORSABUN != '' AND SMORAPPDATE != '') AND (SMGRSABUN != '' AND SMGRAPPDATE = '') THEN SMGRSABUN 
						 ELSE '' END  
	  
				 ELSE 
	  
				 CASE WHEN (SMORSABUN != '' AND SMORAPPDATE = '') THEN SMORSABUN 
					 WHEN (SMORSABUN != '' AND SMORAPPDATE != '') AND (SMGRSABUN != '' AND SMGRAPPDATE = '') THEN SMGRSABUN 
					 WHEN (SMORSABUN != '' AND SMORAPPDATE != '') AND (SMGRSABUN != '' AND SMGRAPPDATE != '') AND (SMCOSABUN != '' AND SMCOAPPDATE = '') THEN SMCOSABUN 
					 WHEN (SMORSABUN != '' AND SMORAPPDATE != '') AND (SMGRSABUN != '' AND SMGRAPPDATE != '') AND (SMCOSABUN != '' AND SMCOAPPDATE != '') AND (SMSMSABUN != '' AND SMSMAPPDATE = '') THEN SMSMSABUN	  
				 ELSE '' END  
	  
				 END AS SMSABUN 
			 FROM TABLE1 
			ORDER BY SMWKTEAM, 
				 SMWKDATE, 
				 SMWKSEQ,	  
				 SMWKORAPPDATE, 
				 SMWKORSEQ DESC 
			) 
			SELECT SMWKTEAM, 
				 SMWKDATE, 
				 SMWKSEQ, 
				 MAX(SMSABUN) AS SMSABUN 
			 FROM TABLE2 
			GROUP BY SMWKTEAM, SMWKDATE, SMWKSEQ ; 
  
LABEL ON TABLE PSSCMLIB.CV_PSM_MAINCSAFEDOCNEXT 
	IS 'PSM 안전작업허가서 다음결재자 VIEW' ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_MAINCSAFEDOCNEXT 
( SMWKTEAM TEXT IS '요청부서' , 
	SMWKDATE TEXT IS '요청일자' , 
	SMWKSEQ TEXT IS 'SEQ' , 
	SMSABUN TEXT IS '결재사번' ) ; 
  