
CREATE VIEW PSSCMLIB.CV_PSM_MAINCCHANGEASKDOCNEXT ( 
	CAASKTEAM , 
	CAASKDATE , 
	CAASKSEQ , 
	CAASKSABUN ) 
	AS 
	SELECT CAASKTEAM,  
			 CAASKDATE,  
		 CAASKSEQ,  
			 (CASE WHEN CAASKSABUN1 != '' AND CAASKDATE1 = '' THEN  
					 CAASKSABUN1  
				 WHEN CAASKSABUN2 != '' AND CAASKDATE2 = '' THEN  
					 CAASKSABUN2  
				 WHEN CAASKSABUN3 != '' AND CAASKDATE3 = '' THEN  
					 CAASKSABUN3  
				 WHEN CAASKSABUN4 != '' AND CAASKDATE4 = '' THEN  
					 CAASKSABUN4  
				 WHEN CAASKSABUN5 != '' AND CAASKDATE5 = '' THEN  
					 CAASKSABUN5  
				 WHEN CAASKSABUN6 != '' AND CAASKDATE6 = '' THEN  
					 CAASKSABUN6  
				 ELSE  
				 CASE WHEN CAASKRESABUN1 != '' AND CAASKREDATE1 = '' THEN  
						 CAASKRESABUN1  
					 WHEN CAASKRESABUN2 != '' AND CAASKREDATE2 = '' THEN  
						 CAASKRESABUN2  
					 WHEN CAASKRESABUN3 != '' AND CAASKREDATE3 = '' THEN  
						CAASKRESABUN3  
					 WHEN CAASKRESABUN4 != '' AND CAASKREDATE4 = '' THEN  
						CAASKRESABUN4  
				 ELSE  
					 CAASKRESABUN5  
				 END	  
				 END) AS CAASKSABUN  
			FROM PSSCMLIB.PSM_C00007 ; 
  
LABEL ON TABLE PSSCMLIB.CV_PSM_MAINCCHANGEASKDOCNEXT 
	IS 'PSM 변경요구서 다음결재자 VIEW' ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_MAINCCHANGEASKDOCNEXT 
( CAASKTEAM IS '변경요구팀' , 
	CAASKDATE IS '변경요구일자' , 
	CAASKSEQ IS '변경요구순번' ) ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_MAINCCHANGEASKDOCNEXT 
( CAASKTEAM TEXT IS '요청부서' , 
	CAASKDATE TEXT IS '요청일자' , 
	CAASKSEQ TEXT IS 'SEQ' , 
	CAASKSABUN TEXT IS '결재사번' ) ; 