
CREATE VIEW PSSCMLIB.CV_PSM_MAINWOAPPNEXT ( 
	WOORTEAM , 
	WOORDATE , 
	WOSEQ , 
	WODOCSABUN ) 
	AS 
	SELECT WOORTEAM,  
			 WOORDATE,  
		 WOSEQ,  
			 (CASE WHEN WOAPPSOSABUN1 != '' AND WOAPPSODATE1 = '' THEN  
					 WOAPPSOSABUN1  
				 WHEN WOAPPSOSABUN2 != '' AND WOAPPSODATE2 = '' THEN  
					 WOAPPSOSABUN2  
				 WHEN WOAPPSOSABUN3 != '' AND WOAPPSODATE3 = '' THEN  
					 WOAPPSOSABUN3  
				 WHEN WOAPPSOSABUN4 != '' AND WOAPPSODATE4 = '' THEN  
					 WOAPPSOSABUN4  
				 WHEN WOAPPSOSABUN5 != '' AND WOAPPSODATE5 = '' THEN  
					 WOAPPSOSABUN5  
				 ELSE  
				 CASE WHEN WOAPPRESABUN1 != '' AND WOAPPREDATE1 = '' THEN  
						 WOAPPRESABUN1  
					 WHEN WOAPPRESABUN2 != '' AND WOAPPREDATE2 = '' THEN  
						 WOAPPRESABUN2  
					 WHEN WOAPPRESABUN3 != '' AND WOAPPREDATE3 = '' THEN  
						WOAPPRESABUN3  
					 WHEN WOAPPRESABUN4 != '' AND WOAPPREDATE4 = '' THEN  
						WOAPPRESABUN4  
				 ELSE  
					 WOAPPRESABUN5  
				 END	  
				 END) AS WODOCSABUN  
			FROM PSSCMLIB.PSM_W00001 ; 
  
LABEL ON TABLE PSSCMLIB.CV_PSM_MAINWOAPPNEXT 
	IS 'PSM 작업요청서 다음결재자 VIEW' ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_MAINWOAPPNEXT 
( WOORTEAM TEXT IS '요청부서' , 
	WOORDATE TEXT IS '요청일자' , 
	WOSEQ TEXT IS 'SEQ' , 
	WODOCSABUN TEXT IS '결재사번' ) ; 
