
CREATE VIEW PSSCMLIB.CV_PSM_MAINCCHANGEREVDOCNEXT ( 
	CRREVTEAM , 
	CRREVDATE , 
	CRREVSEQ , 
	CRREVSABUN ) 
	AS 
	SELECT CRREVTEAM, 
		 CRREVDATE, 
	 CRREVSEQ, 
		 (CASE WHEN CRREVSABUN1 != '' AND CRREVDATE1 = '' THEN 
				 CRREVSABUN1 
			 WHEN CRREVSABUN2 != '' AND CRREVDATE2 = '' THEN 
				 CRREVSABUN2 
			 WHEN CRREVSABUN3 != '' AND CRREVDATE3 = '' THEN 
				 CRREVSABUN3 
			 WHEN CRREVSABUN4 != '' AND CRREVDATE4 = '' THEN 
				 CRREVSABUN4  
			 WHEN CRREVSABUN5 != '' AND CRREVDATE5 = '' THEN 
				 CRREVSABUN5 
			 WHEN CRREVSABUN6 != '' AND CRREVDATE6 = '' THEN 
				 CRREVSABUN6 
			 ELSE 
			 '' 
			 END) AS CRREVSABUN 
		FROM PSSCMLIB.PSM_C00008 ; 
  
LABEL ON TABLE PSSCMLIB.CV_PSM_MAINCCHANGEREVDOCNEXT 
	IS 'PSM 변경검토서 다음결재자 VIEW' ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_MAINCCHANGEREVDOCNEXT 
( CRREVTEAM IS '변경검토팀' , 
	CRREVDATE IS '변경검토일자' , 
	CRREVSEQ IS '변경검토순번' ) ; 
  
LABEL ON COLUMN PSSCMLIB.CV_PSM_MAINCCHANGEREVDOCNEXT 
( CRREVTEAM TEXT IS '요청부서' , 
	CRREVDATE TEXT IS '요청일자' , 
	CRREVSEQ TEXT IS 'SEQ' , 
	CRREVSABUN TEXT IS '결재사번' ) ; 
  