
CREATE FUNCTION TYJINFWLIB.UF_DEPTNAME (
    P_COMPANYCODE VARCHAR (10),
    P_LANGCODE VARCHAR (2),
    P_DEPTCODE VARCHAR (12)
    )

    RETURNS VARGRAPHIC(2000) CCSID 1200
    LANGUAGE SQL
    SPECIFIC TYJINFWLIB.UF_DEPTNAME
    NOT DETERMINISTIC
    NO EXTERNAL ACTION
    READS SQL DATA
    CALLED ON NULL INPUT
    FENCED
    DISALLOW PARALLEL
BEGIN
    -- DECLARE THE RETURN VARIABLE HERE
    DECLARE P_DEPTNAME VARGRAPHIC(2000) CCSID 1200;

    -- ADD THE T-SQL STATEMENTS TO COMPUTE THE RETURN VALUE HERE
    SELECT COALESCE ( DL.DEPTNAME , D.DISPLAYNAME )
      INTO P_DEPTNAME
      FROM TYJINFWLIB.ORG_DEPT AS D
      LEFT JOIN TYJINFWLIB.ORG_DEPTLANG AS DL
        ON D.DEPTCODE    = DL.DEPTCODE
       AND D.COMPANYCODE = DL.COMPANYCODE
       AND DL.LANGCODE   = P_LANGCODE
    WHERE  D.COMPANYCODE = P_COMPANYCODE
      AND D.DEPTCODE     = P_DEPTCODE
    FETCH FIRST 1 ROWS ONLY ;


    -- 부서가 없을 경우 법인 제외 하고 검색
    IF TRIM(P_DEPTNAME) = '' THEN
        SELECT COALESCE ( DL.DEPTNAME , D.DISPLAYNAME )
          INTO P_DEPTNAME
          FROM TYJINFWLIB.ORG_DEPT AS D
          LEFT JOIN TYJINFWLIB.ORG_DEPTLANG AS DL
            ON D.DEPTCODE    = DL.DEPTCODE
           AND D.COMPANYCODE = DL.COMPANYCODE
           AND DL.LANGCODE   = P_LANGCODE
         WHERE D.DEPTCODE    = P_DEPTCODE
         FETCH FIRST 1 ROWS ONLY ;
    END IF;

    RETURN P_DEPTNAME ;
END ;

