DROP FUNCTION TYJINFWLIB.UF_GET_GRPEXTMEMBERS;

CREATE FUNCTION TYJINFWLIB.UF_GET_GRPEXTMEMBERS 
(
	P_GRPEXT 	VARCHAR(100)
)
	RETURNS TABLE 
	(
		COMPANYCODE		VARCHAR(50),
		EMPID			VARCHAR(50),
		MAINDEPTCODE	VARCHAR(32)
	)
	LANGUAGE SQL
	NO EXTERNAL ACTION
	DISALLOW PARALLEL  
	MODIFIES SQL DATA
BEGIN
	DECLARE GLOBAL TEMPORARY TABLE SESSION.T
	(
		COMPANYCODE		VARCHAR(50),
		EMPID			VARCHAR(50),
		MAINDEPTCODE	VARCHAR(32)
	) WITH REPLACE;-- NOT LOGGED;
	
	IF (P_GRPEXT = 'OFFICER') THEN
		INSERT INTO SESSION.T
			SELECT
						U.COMPANYCODE
					,	U.EMPID
					,	U.MAINDEPTCODE
			FROM
					TYJINFWLIB.ORG_USER	AS U
			WHERE
					U.DISPLAYYN			= 'Y'
			AND		U.RANKCODE			IN ('01','02','03','04','05','06','07','08','09','10','11','13','14','Z6')
			AND		U.COMPANYCODE		= '1000';
	ELSEIF (P_GRPEXT = 'TEAMCHIEF') THEN
		INSERT INTO SESSION.T
			SELECT
						U.COMPANYCODE
					,	U.EMPID
					,	U.MAINDEPTCODE
			FROM
					TYJINFWLIB.ORG_USER	AS U
			WHERE
					U.DISPLAYYN			= 'Y'
			AND		U.DUTYCODE			IN ('010', '011')
			AND		U.COMPANYCODE		= '1000'
			UNION ALL
			SELECT
						U.COMPANYCODE
					,	U.EMPID
					,	U.DEPTCODE
			FROM
					TYJINFWLIB.ORG_ADDITIONALJOB	AS U
			WHERE
					U.DUTYCODE			IN ('010', '011')
			AND		U.ADDCOMPANYCODE	= '1000';
	ELSE
		INSERT INTO SESSION.T
			SELECT '' AS COMPANYCODE,'' AS EMPID,'' AS DEPTCODE FROM SYSIBM.SYSDUMMY1;
	END IF;

	RETURN (SELECT * FROM SESSION.T);
	
	
END