CREATE FUNCTION TYJINFWLIB.UF_USERINFO_USERNAME2
(
		P_EMPID VARCHAR(80)
	,	P_LOCALE VARCHAR(10)
)
	RETURNS VARCHAR (160)
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.UF_USERINFO_USERNAME2
	NO EXTERNAL ACTION
	DISALLOW PARALLEL  
BEGIN
	-- DECLARE THE RETURN VARIABLE HERE
	DECLARE P_USER_NAME VARCHAR(160);

	IF NOT EXISTS(SELECT USERLNAME FROM TYJINFWLIB.ORG_USERLANG WHERE EMPID = P_EMPID AND LANGCODE = P_LOCALE) THEN
		SET P_LOCALE = 'ko';
	END IF;

	-- ADD THE T-SQL STATEMENTS TO COMPUTE THE RETURN VALUE HERE
	--SET P_USER_NAME = 
	--	(CASE P_LOCALE
	--		WHEN 'EN' THEN (P_FNAME || ' ' || P_LNAME)
	--		ELSE P_LNAME || P_FNAME
	--	END);

--	SELECT 
--				(CASE P_LOCALE
--					WHEN 'en' THEN (USERFNAME || ' ' || USERLNAME)
--					ELSE USERLNAME || USERFNAME
--				END)
--				INTO P_USER_NAME
--	FROM TYJINFWLIB.ORG_USERLANG
--	WHERE 
--		EMPID = P_EMPID
--		AND LANGCODE = P_LOCALE;

-- ¾÷Ã¼ ¾ÆÀÌµð·Î Á¶È¸ ÇÏ±â ¼öÁ¤ 2017.01.16 ±èÈñ¼·
	SELECT COALESCE((CASE ucase(P_LOCALE) WHEN 'EN' 
                                          THEN (USERFNAME || ' ' || USERLNAME)
                                          ELSE USERLNAME || USERFNAME
                                          END),A.DISPLAYNAME)
      INTO P_USER_NAME
      FROM(SELECT A.COMPANYCODE
                , A.EMPID
                , A.DISPLAYNAME
             FROM TYJINFWLIB.ORG_USER AS A
            WHERE A.EMPID       = P_EMPID
      ) AS A
     LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS B
       ON A.COMPANYCODE = B.COMPANYCODE
      AND A.EMPID       = B.EMPID
      AND UCASE(B.LANGCODE)    = ucase(P_LOCALE)
      FETCH FIRST 1 ROWS ONLY;

    RETURN P_USER_NAME;
END