DROP PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1020_PRINT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1020_PRINT ( 
	IN P_SDATE VARCHAR(6) , 
	IN P_EDATE VARCHAR(6) , 
	IN P_HWAJU VARCHAR(50) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TGCSI_CSG1020_PRINT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
  
	DECLARE V_DATE VARCHAR ( 30 ) ; 
  
	PRINT : BEGIN  -- 출력 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
			COMPANY , 
			IHHANGCHA , 
			VSDESC1 , 
			IPGOKJONG , 
			GKDESC1 , 
			SKDESC1 , 
			WNDESC1 , 
			IHIPHANG , 
			IHJAKENDAT , 
			IPIPSTDAT , 
			IHJUKHANO , 
			JBBEJNQTY , 
			JBHWAKQTY , 
			GAMQTY , 
			HJDESC1 , 
			COMPANY || IHHANGCHA || IPGOKJONG AS GUBUN 
			FROM 
			( 
				SELECT 
				'(주) 태영그레인터미널' AS COMPANY , 
				IPHA . IHHANGCHA , 
				VSCODE . CDDESC1 AS VSDESC1 , 
				IPGO . IPGOKJONG , 
				GKCODE . CDDESC1 AS GKDESC1 , 
				SKCODE . CDDESC1 AS SKDESC1 , 
				WNCODE . CDDESC1 AS WNDESC1 , 
				( SUBSTR ( CHAR ( IHIPHANG ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHIPHANG ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHIPHANG ) , 7 , 2 ) ) AS IHIPHANG , 
				( SUBSTR ( CHAR ( IHJAKENDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 7 , 2 ) ) AS IHJAKENDAT , 
				( SUBSTR ( CHAR ( IPIPSTDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IPIPSTDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IPIPSTDAT ) , 7 , 2 ) ) AS IPIPSTDAT , 
				IHJUKHANO , 
				( JBBEJNQTY + JBBEIPQTY - JBBECHQTY ) AS JBBEJNQTY , 
				( JBHWAKQTY + JBHWIPQTY - JBHWCHQTY ) AS JBHWAKQTY , 
				( ( JBBEJNQTY + JBBEIPQTY - JBBECHQTY ) - ( JBHWAKQTY + JBHWIPQTY - JBHWCHQTY ) ) AS GAMQTY , 
				HJCODE . CDDESC1 AS HJDESC1 
				FROM TGSCMLIB . USIIPHAF AS IPHA 
				LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
				ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
				LEFT OUTER JOIN TGSCMLIB . USIJEBLF AS JEBL 
				ON IPGO . IPHANGCHA = JEBL . JBHANGCHA 
				AND IPGO . IPGOKJONG = JEBL . JBGOKJONG 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
				ON 'VS' = VSCODE . CDINDEX 
				AND IPHA . IHHANGCHA = VSCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
				ON 'GK' = GKCODE . CDINDEX 
				AND IPGO . IPGOKJONG = GKCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
				ON 'SK' = SKCODE . CDINDEX 
				AND IPHA . IHSOSOK = SKCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS WNCODE 
				ON 'WN' = WNCODE . CDINDEX 
				AND IPHA . IHWONSAN1 = WNCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS HJCODE 
				ON 'HJ' = HJCODE . CDINDEX 
				AND JEBL . JBHWAJU = HJCODE . CDCODE 
				WHERE SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 6 ) BETWEEN P_SDATE AND P_EDATE 
				AND JEBL . JBHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
				AND ( JEBL . JBBEJNQTY + JEBL . JBBEIPQTY - JEBL . JBBECHQTY ) <> 0 
				AND ( JEBL . JBHWAKQTY + JEBL . JBHWIPQTY - JEBL . JBHWCHQTY ) <> 0 
  
				UNION ALL 
  
				SELECT 
				'주식회사 평택싸이로' AS COMPANY , 
				IPHA . IHHANGCHA , 
				VSCODE . CDDESC1 AS VSDESC1 , 
				IPGO . IPGOKJONG , 
				GKCODE . CDDESC1 AS GKDESC1 , 
				SKCODE . CDDESC1 AS SKDESC1 , 
				WNCODE . CDDESC1 AS WNDESC1 , 
				( SUBSTR ( CHAR ( IHIPHANG ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHIPHANG ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHIPHANG ) , 7 , 2 ) ) AS IHIPHANG , 
				( SUBSTR ( CHAR ( IHJAKENDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IHJAKENDAT ) , 7 , 2 ) ) AS IHJAKENDAT , 
				( SUBSTR ( CHAR ( IPIPSTDAT ) , 1 , 4 ) || '/' || SUBSTR ( CHAR ( IPIPSTDAT ) , 5 , 2 ) || '/' || SUBSTR ( CHAR ( IPIPSTDAT ) , 7 , 2 ) ) AS IPIPSTDAT , 
				IHJUKHANO , 
				( JBBEJNQTY + JBBEIPQTY - JBBECHQTY ) AS JBBEJNQTY , 
				( JBHWAKQTY + JBHWIPQTY - JBHWCHQTY ) AS JBHWAKQTY , 
				( ( JBBEJNQTY + JBBEIPQTY - JBBECHQTY ) - ( JBHWAKQTY + JBHWIPQTY - JBHWCHQTY ) ) AS GAMQTY , 
				HJCODE . CDDESC1 AS HJDESC1 
				FROM PTSCMLIB . USIIPHAF AS IPHA 
				LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
				ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
				LEFT OUTER JOIN PTSCMLIB . USIJEBLF AS JEBL 
				ON IPGO . IPHANGCHA = JEBL . JBHANGCHA 
				AND IPGO . IPGOKJONG = JEBL . JBGOKJONG 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
				ON 'VP' = VSCODE . CDINDEX 
				AND IPHA . IHHANGCHA = VSCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
				ON 'GK' = GKCODE . CDINDEX 
				AND IPGO . IPGOKJONG = GKCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
				ON 'SK' = SKCODE . CDINDEX 
				AND IPHA . IHSOSOK = SKCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS WNCODE 
				ON 'WN' = WNCODE . CDINDEX 
				AND IPHA . IHWONSAN1 = WNCODE . CDCODE 
				LEFT OUTER JOIN TGSCMLIB . USICODEF AS HJCODE 
				ON 'HJ' = HJCODE . CDINDEX 
				AND JEBL . JBHWAJU = HJCODE . CDCODE 
				WHERE SUBSTR ( CHAR ( IPHA . IHIPHANG ) , 1 , 6 ) BETWEEN P_SDATE AND P_EDATE 
				AND JEBL . JBHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
				AND ( JEBL . JBBEJNQTY + JEBL . JBBEIPQTY - JEBL . JBBECHQTY ) <> 0 
				AND ( JEBL . JBHWAKQTY + JEBL . JBHWIPQTY - JEBL . JBHWCHQTY ) <> 0 
			) AS TEMP 
			ORDER BY COMPANY DESC , GUBUN ; 
  
		OPEN REFCURSOR ; 
  
	END PRINT ; 
END P1  ; 

