DROP PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1010_PRINT;
  
CREATE PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1010_PRINT ( 
	IN P_SDATE VARCHAR(8) , 
	IN P_EDATE VARCHAR(8) , 
	IN P_HWAJU VARCHAR(30) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TGCSI_CSG1010_PRINT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
  
	DECLARE V_DATE VARCHAR ( 30 ) ; 
  
	PRINT : BEGIN  -- 출력 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
			SELECT 
			COMPANY , 
			IHHANGCHA , 
			VSDESC1 , 
			IHIPHANG , 
			GKDESC1 , 
			SKDESC1 , 
			IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT , 
			SUM ( IPIPPQTY ) AS IPIPQTY , 
			COMPANY || IHHANGCHA || GKDESC1 AS GUBUN 
			FROM 
			( 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT1 AS IPIPDAT , 
			IPIPPQTY1 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY1 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT2 AS IPIPDAT , 
			IPIPPQTY2 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY2 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT3 AS IPIPDAT , 
			IPIPPQTY3 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY3 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT4 AS IPIPDAT , 
			IPIPPQTY4 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY4 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT5 AS IPIPDAT , 
			IPIPPQTY5 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY5 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT6 AS IPIPDAT , 
			IPIPPQTY6 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY6 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT7 AS IPIPDAT , 
			IPIPPQTY7 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY7 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT8 AS IPIPDAT , 
			IPIPPQTY8 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY8 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT9 AS IPIPDAT , 
			IPIPPQTY9 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY9 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT10 AS IPIPDAT , 
			IPIPPQTY10 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY10 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
  
			 -- 2선석 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT1 AS IPIPDAT , 
			IPIEPQTY1 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY1 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT2 AS IPIPDAT , 
			IPIEPQTY2 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY2 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT3 AS IPIPDAT , 
			IPIEPQTY3 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY3 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT4 AS IPIPDAT , 
			IPIEPQTY4 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY4 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT5 AS IPIPDAT , 
			IPIEPQTY5 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY5 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT6 AS IPIPDAT , 
			IPIEPQTY6 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY6 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT7 AS IPIPDAT , 
			IPIEPQTY7 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY7 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT8 AS IPIPDAT , 
			IPIEPQTY8 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY8 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT9 AS IPIPDAT , 
			IPIEPQTY9 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY9 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT10 AS IPIPDAT , 
			IPIEPQTY10 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY10 <> 0 
			AND IHCOMPGUBN = 'TG' 
  
			UNION ALL 
  
			 --3선석 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT1 AS IPIPDAT , 
			IPISPQTY1 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY1 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT2 AS IPIPDAT , 
			IPISPQTY2 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY2 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT3 AS IPIPDAT , 
			IPISPQTY3 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY3 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT4 AS IPIPDAT , 
			IPISPQTY4 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY4 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT5 AS IPIPDAT , 
			IPISPQTY5 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY5 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT6 AS IPIPDAT , 
			IPISPQTY6 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY6 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT7 AS IPIPDAT , 
			IPISPQTY7 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY7 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT8 AS IPIPDAT , 
			IPISPQTY8 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY8 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT9 AS IPIPDAT , 
			IPISPQTY9 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY9 <> 0 
			AND IHCOMPGUBN = 'TG' 
			UNION ALL 
			SELECT 
			'(주) 태영그레인터미널' AS COMPANY , 
			IHHANGCHA , 
			VSCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT10 AS IPIPDAT , 
			IPISPQTY10 AS IPIPPQTY 
			FROM TGSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
			ON 'VS' = VSCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VSCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY10 <> 0 
			AND IHCOMPGUBN = 'TG' 
  
			UNION ALL 
  
			 -- 주식회사 평택싸이로 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT1 AS IPIPDAT , 
			IPIPPQTY1 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY1 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT2 AS IPIPDAT , 
			IPIPPQTY2 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY2 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT3 AS IPIPDAT , 
			IPIPPQTY3 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY3 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT4 AS IPIPDAT , 
			IPIPPQTY4 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY4 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT5 AS IPIPDAT , 
			IPIPPQTY5 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY5 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT6 AS IPIPDAT , 
			IPIPPQTY6 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY6 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT7 AS IPIPDAT , 
			IPIPPQTY7 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY7 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT8 AS IPIPDAT , 
			IPIPPQTY8 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY8 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT9 AS IPIPDAT , 
			IPIPPQTY9 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY9 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIPDAT10 AS IPIPDAT , 
			IPIPPQTY10 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIPPQTY10 <> 0 
  
			UNION ALL 
  
			 -- 2선석 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT1 AS IPIPDAT , 
			IPIEPQTY1 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY1 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT2 AS IPIPDAT , 
			IPIEPQTY2 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY2 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT3 AS IPIPDAT , 
			IPIEPQTY3 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY3 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT4 AS IPIPDAT , 
			IPIEPQTY4 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY4 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT5 AS IPIPDAT , 
			IPIEPQTY5 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY5 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT6 AS IPIPDAT , 
			IPIEPQTY6 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY6 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT7 AS IPIPDAT , 
			IPIEPQTY7 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY7 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT8 AS IPIPDAT , 
			IPIEPQTY8 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY8 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT9 AS IPIPDAT , 
			IPIEPQTY9 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY9 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPIEDAT10 AS IPIPDAT , 
			IPIEPQTY10 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPIEPQTY10 <> 0 
  
			UNION ALL 
  
			 -- 3선석 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT1 AS IPIPDAT , 
			IPISPQTY1 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY1 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT2 AS IPIPDAT , 
			IPISPQTY2 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY2 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT3 AS IPIPDAT , 
			IPISPQTY3 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY3 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT4 AS IPIPDAT , 
			IPISPQTY4 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY4 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT5 AS IPIPDAT , 
			IPISPQTY5 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY5 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT6 AS IPIPDAT , 
			IPISPQTY6 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY6 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT7 AS IPIPDAT , 
			IPISPQTY7 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY7 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT8 AS IPIPDAT , 
			IPISPQTY8 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY8 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT9 AS IPIPDAT , 
			IPISPQTY9 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY9 <> 0 
			UNION ALL 
			SELECT 
			'주식회사 평택싸이로' AS COMPANY , 
			IHHANGCHA , 
			VPCODE . CDDESC1 AS VSDESC1 , 
			IHIPHANG , 
			IPGOKJONG , 
			GKCODE . CDDESC1 AS GKDESC1 , 
			SKCODE . CDDESC1 AS SKDESC1 , 
			TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY ,  -- B/L량 
			IPTOTQTY ,  -- 확정량 
			IPISDAT10 AS IPIPDAT , 
			IPISPQTY10 AS IPIPPQTY 
			FROM PTSCMLIB . USIIPHAF AS IPHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS VPCODE 
			ON 'VP' = VPCODE . CDINDEX 
			AND IPHA . IHHANGCHA = VPCODE . CDCODE 
			LEFT OUTER JOIN PTSCMLIB . USIIPGOF AS IPGO 
			ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
			ON 'GK' = GKCODE . CDINDEX 
			AND IPGO . IPGOKJONG = GKCODE . CDCODE 
			LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
			ON 'SK' = SKCODE . CDINDEX 
			AND IPHA . IHSOSOK = SKCODE . CDCODE 
			WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
			AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
			AND IPISPQTY10 <> 0 
  
			) AS TEMP 
			GROUP BY COMPANY , IHHANGCHA , VSDESC1 , IHIPHANG , IPGOKJONG , GKDESC1 , SKDESC1 , IHBLQTY , IPTOTQTY , IPIPDAT 
			ORDER BY COMPANY DESC , IHHANGCHA , IPGOKJONG , IPIPDAT ; 
  
		OPEN REFCURSOR ; 
  
	END PRINT ; 
END P1  ; 
  
