DROP PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1050_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1050_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE VARCHAR(8) , 
	IN P_EDATE VARCHAR(8) , 
	IN P_HWAJU VARCHAR(50) , 
	IN P_YSGUBUN VARCHAR(1) , 
	IN P_GUBUN VARCHAR(1) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TGCSI_CSG1050_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부 
		IF P_GUBUN = 'S' THEN 
  
			LIST1 : BEGIN  -- 리스트 
				DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						'(주)태영그레인터미널' AS COMPANY , 
						'G' AS SEQ , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TGSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'(주)태영그레인터미널' AS COMPANY , 
						'G' AS SEQ , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TGSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'주식회사 평택싸이로' AS COMPANY , 
						'T' AS SEQ , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM PTSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VP' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'주식회사 평택싸이로' AS COMPANY , 
						'T' AS SEQ , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM PTSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VP' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						COMPANY , 
						SEQ , 
						'D' AS GUBUN , 
						TMHWAJU , 
						TMHANGCHA , 
						VSDESC1 , 
						TMGOKJONG , 
						GKDESC1 , 
						TMBLNO , 
						DIGITS ( TMHMNO1 ) || '-' || DIGITS ( TMHMNO2 ) AS TMHMN , 
						DIGITS ( TMCUSTIL ) AS TMCUSTIL , 
						DIGITS ( TMSEQ ) AS TMSEQ , 
						TMGUBUN , 
						DIGITS ( TMYSDATE ) AS TMYSDATE , 
						TMYSHWAJU , 
						YSCODE . CDDESC1 AS YSDESC1 , 
						TMYSQTY 
						FROM MAST 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS YSCODE 
						ON 'HJ' = YSCODE . CDINDEX 
						AND TMYSHWAJU = YSCODE . CDCODE 
						WHERE ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( TMGUBUN ) END ) 
						= ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( P_YSGUBUN ) END ) 
  
						UNION ALL 
  
						SELECT 
						COMPANY , 
						SEQ , 
						'H' AS GUBUN , 
						TMHWAJU , 
						TMHANGCHA , 
						'' AS VSDESC1 , 
						'' AS TMGOKJONG , 
						'' AS GKDESC1 , 
						'' AS TMBLNO , 
						'' AS TMHMN , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS TMYSHWAJU , 
						'' AS YSDESC1 , 
						SUM ( TMYSQTY ) AS TMYSQTY 
						FROM MAST 
						WHERE ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( TMGUBUN ) END ) 
						= ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( P_YSGUBUN ) END ) 
						GROUP BY GROUPING SETS ( ( COMPANY , SEQ , TMHANGCHA , TMHWAJU ) , ( COMPANY , SEQ ) , '' ) 
						ORDER BY SEQ , TMHANGCHA , GUBUN , TMHWAJU 
					) 
  
					SELECT 
					ROWNO , 
					COMPANY , 
					SEQ , 
					GUBUN , 
					TMHWAJU , 
					TMHANGCHA , 
					VSDESC1 , 
					TMGOKJONG , 
					GKDESC1 , 
					TMBLNO , 
					TMHMN , 
					TMCUSTIL , 
					TMSEQ , 
					TMGUBUN , 
					TMYSDATE , 
					TMYSHWAJU , 
					YSDESC1 , 
					TMYSQTY 
					FROM 
					( 
						SELECT 
						ROW_NUMBER ( ) OVER ( ORDER BY SEQ , TMHANGCHA , GUBUN , TMGOKJONG , TMBLNO , TMHMN , TMCUSTIL , TMSEQ , TMGUBUN , TMYSDATE ) AS ROWNO , 
						COMPANY , 
						SEQ , 
						GUBUN , 
						TMHWAJU , 
						TMHANGCHA , 
						VSDESC1 , 
						TMGOKJONG , 
						( CASE WHEN ( GUBUN = 'H' AND TMHANGCHA <> '' ) THEN '<div style="color:blue" >모선별 소계</div>' 
						WHEN ( GUBUN = 'H' AND COMPANY IS NOT NULL AND ( TMHANGCHA IS NULL OR TMHANGCHA = '' ) ) THEN '<div style="color:red" >하역사별 소계</div>' 
						WHEN ( GUBUN = 'H' AND ( COMPANY IS NULL OR COMPANY = '' ) ) THEN '<div style="color:blue" >총   계</div>' 
						ELSE GKDESC1 END ) AS GKDESC1 , 
						TMBLNO , 
						TMHMN , 
						TMCUSTIL , 
						TMSEQ , 
						( CASE WHEN TMGUBUN = '2' THEN '양수' 
						WHEN TMGUBUN = '1' THEN '양도' END ) AS TMGUBUN , 
						TMYSDATE , 
						TMYSHWAJU , 
						YSDESC1 , 
						( CASE WHEN ( GUBUN = 'H' AND TMHANGCHA <> '' ) THEN '<div style="color:blue" >' || TRIM ( TO_CHAR ( TMYSQTY , '999,999,990.000' ) ) || '</div>' 
						WHEN ( GUBUN = 'H' AND COMPANY IS NOT NULL AND ( TMHANGCHA IS NULL OR TMHANGCHA = '' ) ) THEN '<div style="color:red" >' || TRIM ( TO_CHAR ( TMYSQTY , '999,999,990.000' ) ) || '</div>' 
						WHEN ( GUBUN = 'H' AND ( COMPANY IS NULL OR COMPANY = '' ) ) THEN '<div style="color:blue" >' || TRIM ( TO_CHAR ( TMYSQTY , '999,999,990.000' ) ) || '</div>' 
						ELSE TRIM ( TO_CHAR ( TMYSQTY , '9,999,990.000' ) ) END ) AS TMYSQTY 
						FROM DETAIL 
					) AS TEMP 
					WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) ; 
  
				OPEN REFCURSOR ; 
			 
			END LIST1 ; 
  
			PAGING1 : BEGIN  -- 페이징 
				DECLARE REFCURSOR3 CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						'(주)태영그레인터미널' AS COMPANY , 
						'G' AS SEQ , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TGSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'(주)태영그레인터미널' AS COMPANY , 
						'G' AS SEQ , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TGSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'주식회사 평택싸이로' AS COMPANY , 
						'T' AS SEQ , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM PTSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VP' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'주식회사 평택싸이로' AS COMPANY , 
						'T' AS SEQ , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM PTSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VP' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) , 
  
					DETAIL AS 
					( 
						SELECT 
						COMPANY , 
						SEQ , 
						'D' AS GUBUN , 
						TMHWAJU , 
						TMHANGCHA , 
						VSDESC1 , 
						TMGOKJONG , 
						GKDESC1 , 
						TMBLNO , 
						DIGITS ( TMHMNO1 ) AS TMHMNO1 , 
						DIGITS ( TMHMNO2 ) AS TMHMNO2 , 
						DIGITS ( TMCUSTIL ) AS TMCUSTIL , 
						DIGITS ( TMSEQ ) AS TMSEQ , 
						TMGUBUN , 
						DIGITS ( TMYSDATE ) AS TMYSDATE , 
						TMYSHWAJU , 
						YSCODE . CDDESC1 AS YSDESC1 , 
						TMYSQTY 
						FROM MAST 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS YSCODE 
						ON 'HJ' = YSCODE . CDINDEX 
						AND TMYSHWAJU = YSCODE . CDCODE 
						WHERE ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( TMGUBUN ) END ) 
						= ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( P_YSGUBUN ) END ) 
  
						UNION ALL 
  
						SELECT 
						COMPANY , 
						SEQ , 
						'H' AS GUBUN , 
						TMHWAJU , 
						TMHANGCHA , 
						'' AS VSDESC1 , 
						'' AS TMGOKJONG , 
						'' AS GKDESC1 , 
						'' AS TMBLNO , 
						'' AS TMHMNO1 , 
						'' AS TMHMNO2 , 
						'' AS TMCUSTIL , 
						'' AS TMSEQ , 
						'' AS TMGUBUN , 
						'' AS TMYSDATE , 
						'' AS TMYSHWAJU , 
						'' AS YSDESC1 , 
						SUM ( TMYSQTY ) AS TMYSQTY 
						FROM MAST 
						WHERE ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( TMGUBUN ) END ) 
						= ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( P_YSGUBUN ) END ) 
						GROUP BY GROUPING SETS ( ( COMPANY , SEQ , TMHANGCHA , TMHWAJU ) , ( COMPANY , SEQ ) , '' ) 
						ORDER BY SEQ , TMHANGCHA , GUBUN , TMHWAJU 
					) 
					 
					SELECT 
					COUNT ( * ) AS TOTALCOUNT 
					FROM DETAIL ; 
  
				OPEN REFCURSOR3 ; 
  
			END PAGING1 ; 
			 
		ELSE 
  
			PRINT : BEGIN  -- 프린트 
				DECLARE REFCURSOR5 CURSOR WITH RETURN FOR 
  
					WITH MAST AS 
					( 
						SELECT 
						'(주)태영그레인터미널' AS COMPANY , 
						'G' AS SEQ , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TGSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'(주)태영그레인터미널' AS COMPANY , 
						'G' AS SEQ , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM TGSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VS' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'주식회사 평택싸이로' AS COMPANY , 
						'T' AS SEQ , 
						YNHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'1' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM PTSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VP' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
  
						UNION ALL 
  
						SELECT 
						'주식회사 평택싸이로' AS COMPANY , 
						'T' AS SEQ , 
						YNYSHWAJU AS TMHWAJU , 
						YNHANGCHA AS TMHANGCHA , 
						VSCODE . CDDESC1 AS VSDESC1 , 
						YNGOKJONG AS TMGOKJONG , 
						GKCODE . CDDESC1 AS GKDESC1 , 
						YNBLNO	AS TMBLNO , 
						YNHMNO1 AS TMHMNO1 , 
						YNHMNO2 AS TMHMNO2 , 
						YNCUSTIL AS TMCUSTIL , 
						YNCUSTCH AS TMSEQ , 
						'2' AS TMGUBUN , 
						YNYSDATE AS TMYSDATE , 
						YNYSHWAJU AS TMYSHWAJU , 
						( CASE WHEN YNYSYDHWAJ = '' THEN YNQTY ELSE YNYSYDQTY END ) AS TMYSQTY 
						FROM PTSCMLIB . USIYANGNF AS YANG 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
						ON 'VP' = VSCODE . CDINDEX 
						AND YANG . YNHANGCHA = VSCODE . CDCODE 
						LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
						ON 'GK' = GKCODE . CDINDEX 
						AND YANG . YNGOKJONG = GKCODE . CDCODE 
						WHERE YNYSDATE BETWEEN P_SDATE AND P_EDATE 
						AND YNYSHWAJU IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) 
					) 
  
					SELECT 
					COMPANY , 
					SEQ , 
					TMHWAJU , 
					TMHANGCHA , 
					VSDESC1 , 
					TMGOKJONG , 
					GKDESC1 , 
					TMBLNO , 
					DIGITS ( TMHMNO1 ) || '-' || DIGITS ( TMHMNO2 ) AS TMHMN , 
					DIGITS ( TMCUSTIL ) AS TMCUSTIL , 
					DIGITS ( TMSEQ ) AS TMSEQ , 
					TMGUBUN , 
					DIGITS ( TMYSDATE ) AS TMYSDATE , 
					TMYSHWAJU , 
					YSCODE . CDDESC1 AS YSDESC1 , 
					TMYSQTY 
					FROM MAST 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS YSCODE 
					ON 'HJ' = YSCODE . CDINDEX 
					AND TMYSHWAJU = YSCODE . CDCODE 
					WHERE ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( TMGUBUN ) END ) 
					= ( CASE WHEN P_YSGUBUN = '' THEN '' ELSE TRIM ( P_YSGUBUN ) END ) 
					ORDER BY SEQ , TMHANGCHA , TMGOKJONG , TMBLNO , TMHMN , TMCUSTIL , TMSEQ , TMGUBUN , TMYSDATE ; 
  
				OPEN REFCURSOR5 ; 
  
			END PRINT ; 
  
		END IF ; 
  
	END MAIN ; 
  
END P1  ; 
  
