DROP PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1010_LIST;
  
CREATE PROCEDURE TYJINFWLIB.SP_TGCSI_CSG1010_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_SDATE VARCHAR(8) , 
	IN P_EDATE VARCHAR(8) , 
	IN P_HWAJU VARCHAR(50) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.SP_TGCSI_CSG1010_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
	DECLARE P_SQLSTRING VARCHAR ( 4000 ) ; 
	DECLARE P_SQLTOTALROWCOUNT VARCHAR ( 4000 ) ; 
	DECLARE P_TABLE_QUERY			VARCHAR ( 5000 ) ; 
	DECLARE P_COUNT_QUERY			VARCHAR ( 5000 ) ; 
  
	PREV : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
	SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
	MAIN : BEGIN  -- 실행부      
	LIST : BEGIN  -- 리스트 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
				WITH ORIGINAL_DATA AS 
				( 
					SELECT 
					IHHANGCHA , 
					VSCODE . CDDESC1 AS VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					SKCODE . CDDESC1 AS SKDESC1 , 
					IHBLQTY1 
					FROM TGSCMLIB . USIIPGOF AS IPGO 
					LEFT OUTER JOIN TGSCMLIB . USIIPHAF AS IPHA 
					ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
					AND IPHA . IHCOMPGUBN = 'TG' 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND IPGO . IPGOKJONG = GKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
					ON 'SK' = SKCODE . CDINDEX 
					AND IPHA . IHSOSOK = SKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
					ON 'VS' = VSCODE . CDINDEX 
					AND IPHA . IHHANGCHA = VSCODE . CDCODE 
					WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
					AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF 
					WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
					ORDER BY IHHANGCHA 
				) , 
  
				DETAIL_GT AS 
				( 
					SELECT 
					'그레인' AS COMPANY , 
					IHHANGCHA , 
					VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKDESC1 , 
					SKDESC1 , 
					TRIM ( TO_CHAR ( SUM ( IHBLQTY1 ) , '999,999,990.000' ) ) AS IHBLQTY1 , 
					IPIPDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIPPQTY ) , '9,999,990.000' ) ) AS IPIPQTY , 
					IPIEDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIEPQTY ) , '9,999,990.000' ) ) AS IPIEPQTY , 
					IPISDAT , 
					TRIM ( TO_CHAR ( SUM ( IPISQTY ) , '9,999,990.000' ) ) AS IPISQTY 
					FROM 
					( 
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT1 AS IPIPDAT , 
						IPIPPQTY1 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT2 AS IPIPDAT , 
						IPIPPQTY2 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT3 AS IPIPDAT , 
						IPIPPQTY3 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT4 AS IPIPDAT , 
						IPIPPQTY4 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT5 AS IPIPDAT , 
						IPIPPQTY5 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT6 AS IPIPDAT , 
						IPIPPQTY6 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT7 AS IPIPDAT , 
						IPIPPQTY7 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT8 AS IPIPDAT , 
						IPIPPQTY8 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT9 AS IPIPDAT , 
						IPIPPQTY9 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT10 AS IPIPDAT , 
						IPIPPQTY10 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT1 AS IPIEDAT , 
						IPIEPQTY1 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT2 AS IPIEDAT , 
						IPIEPQTY2 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT3 AS IPIEDAT , 
						IPIEPQTY3 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT4 AS IPIEDAT , 
						IPIEPQTY4 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT5 AS IPIEDAT , 
						IPIEPQTY5 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT6 AS IPIEDAT , 
						IPIEPQTY6 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT7 AS IPIEDAT , 
						IPIEPQTY7 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT8 AS IPIEDAT , 
						IPIEPQTY8 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT9 AS IPIEDAT , 
						IPIEPQTY9 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT10 AS IPIEDAT , 
						IPIEPQTY10 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT1 AS IPISDAT , 
						IPISPQTY1 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT2 AS IPISDAT , 
						IPISPQTY2 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT3 AS IPISDAT , 
						IPISPQTY3 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT4 AS IPISDAT , 
						IPISPQTY4 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT5 AS IPISDAT , 
						IPISPQTY5 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT6 AS IPISDAT , 
						IPISPQTY6 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT7 AS IPISDAT , 
						IPISPQTY7 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT8 AS IPISDAT , 
						IPISPQTY8 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT9 AS IPISDAT , 
						IPISPQTY9 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT10 AS IPISDAT , 
						IPISPQTY10 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY10 <> 0 
					) AS TEMP 
					GROUP BY IHHANGCHA , VSDESC1 , IHIPHANG , IPGOKJONG , GKDESC1 , SKDESC1 , IHBLQTY1 , IPIPDAT , IPIEDAT , IPISDAT 
				) , 
  
				ORIGINAL_DATA_PT AS 
				( 
					SELECT 
					IHHANGCHA , 
					VSCODE . CDDESC1 AS VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					SKCODE . CDDESC1 AS SKDESC1 , 
					IHBLQTY1 
					FROM PTSCMLIB . USIIPGOF AS IPGO 
					LEFT OUTER JOIN PTSCMLIB . USIIPHAF AS IPHA 
					ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND IPGO . IPGOKJONG = GKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
					ON 'SK' = SKCODE . CDINDEX 
					AND IPHA . IHSOSOK = SKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
					ON 'VP' = VSCODE . CDINDEX 
					AND IPHA . IHHANGCHA = VSCODE . CDCODE 
					WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
					AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF 
					WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
					ORDER BY IHHANGCHA 
				) , 
  
				DETAIL_PT AS 
				( 
					SELECT 
					'평택' AS COMPANY , 
					IHHANGCHA , 
					VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKDESC1 , 
					SKDESC1 , 
					TRIM ( TO_CHAR ( SUM ( IHBLQTY1 ) , '999,999,990.000' ) ) AS IHBLQTY1 , 
					IPIPDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIPPQTY ) , '9,999,990.000' ) ) AS IPIPQTY , 
					IPIEDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIEPQTY ) , '9,999,990.000' ) ) AS IPIEPQTY , 
					IPISDAT , 
					TRIM ( TO_CHAR ( SUM ( IPISQTY ) , '9,999,990.000' ) ) AS IPISQTY 
					FROM 
					( 
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT1 AS IPIPDAT , 
						IPIPPQTY1 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT2 AS IPIPDAT , 
						IPIPPQTY2 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT3 AS IPIPDAT , 
						IPIPPQTY3 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT4 AS IPIPDAT , 
						IPIPPQTY4 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT5 AS IPIPDAT , 
						IPIPPQTY5 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT6 AS IPIPDAT , 
						IPIPPQTY6 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT7 AS IPIPDAT , 
						IPIPPQTY7 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT8 AS IPIPDAT , 
						IPIPPQTY8 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT9 AS IPIPDAT , 
						IPIPPQTY9 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT10 AS IPIPDAT , 
						IPIPPQTY10 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT1 AS IPIEDAT , 
						IPIEPQTY1 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT2 AS IPIEDAT , 
						IPIEPQTY2 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT3 AS IPIEDAT , 
						IPIEPQTY3 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT4 AS IPIEDAT , 
						IPIEPQTY4 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT5 AS IPIEDAT , 
						IPIEPQTY5 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT6 AS IPIEDAT , 
						IPIEPQTY6 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT7 AS IPIEDAT , 
						IPIEPQTY7 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT8 AS IPIEDAT , 
						IPIEPQTY8 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT9 AS IPIEDAT , 
						IPIEPQTY9 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT10 AS IPIEDAT , 
						IPIEPQTY10 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT1 AS IPISDAT , 
						IPISPQTY1 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT2 AS IPISDAT , 
						IPISPQTY2 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT3 AS IPISDAT , 
						IPISPQTY3 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT4 AS IPISDAT , 
						IPISPQTY4 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT5 AS IPISDAT , 
						IPISPQTY5 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT6 AS IPISDAT , 
						IPISPQTY6 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT7 AS IPISDAT , 
						IPISPQTY7 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT8 AS IPISDAT , 
						IPISPQTY8 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT9 AS IPISDAT , 
						IPISPQTY9 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT10 AS IPISDAT , 
						IPISPQTY10 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY10 <> 0 
					) AS TEMP 
					GROUP BY IHHANGCHA , VSDESC1 , IHIPHANG , IPGOKJONG , GKDESC1 , SKDESC1 , IHBLQTY1 , IPIPDAT , IPIEDAT , IPISDAT 
				) , 
  
				LIST AS 
				( 
					SELECT 
					ROW_NUMBER ( ) OVER ( ORDER BY COMPANY , IHHANGCHA , IPGOKJONG , IPIPDAT , IPIEDAT , IPISDAT ) AS ROWNO , 
					COMPANY , 
					IHHANGCHA , 
					VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKDESC1 , 
					SKDESC1 , 
					IHBLQTY1 , 
					IPIPDAT , 
					IPIPQTY , 
					IPIEDAT , 
					IPIEPQTY , 
					IPISDAT , 
					IPISQTY 
					FROM 
					( 
						SELECT 
						COMPANY , 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						IHBLQTY1 , 
						IPIPDAT , 
						IPIPQTY , 
						IPIEDAT , 
						IPIEPQTY , 
						IPISDAT , 
						IPISQTY 
						FROM DETAIL_GT 
  
						UNION ALL 
  
						SELECT 
						COMPANY , 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						IHBLQTY1 , 
						IPIPDAT , 
						IPIPQTY , 
						IPIEDAT , 
						IPIEPQTY , 
						IPISDAT , 
						IPISQTY 
						FROM DETAIL_PT 
					) AS TEMP 
				) 
  
				SELECT 
				ROWNO , 
				COMPANY , 
				IHHANGCHA , 
				VSDESC1 , 
				IHIPHANG , 
				IPGOKJONG , 
				GKDESC1 , 
				SKDESC1 , 
				IHBLQTY1 , 
				IPIPDAT , 
				IPIPQTY , 
				IPIEDAT , 
				IPIEPQTY , 
				IPISDAT , 
				IPISQTY 
				FROM LIST 
				WHERE ROWNO BETWEEN CAST ( P_STNUM AS VARCHAR ( 100 ) ) AND CAST ( P_FNNUM AS VARCHAR ( 100 ) ) 
				ORDER BY ROWNO ASC ; 
			 
			OPEN REFCURSOR ; 
  
		END LIST ; 
	 
		PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
  
				WITH ORIGINAL_DATA AS 
				( 
					SELECT 
					IHHANGCHA , 
					VSCODE . CDDESC1 AS VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					SKCODE . CDDESC1 AS SKDESC1 , 
					IHBLQTY1 
					FROM TGSCMLIB . USIIPGOF AS IPGO 
					LEFT OUTER JOIN TGSCMLIB . USIIPHAF AS IPHA 
					ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
					AND IPHA . IHCOMPGUBN = 'TG' 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND IPGO . IPGOKJONG = GKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
					ON 'SK' = SKCODE . CDINDEX 
					AND IPHA . IHSOSOK = SKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
					ON 'VS' = VSCODE . CDINDEX 
					AND IPHA . IHHANGCHA = VSCODE . CDCODE 
					WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
					AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF 
					WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
					ORDER BY IHHANGCHA 
				) , 
  
				DETAIL_GT AS 
				( 
					SELECT 
					'그레인' AS COMPANY , 
					IHHANGCHA , 
					VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKDESC1 , 
					SKDESC1 , 
					TRIM ( TO_CHAR ( SUM ( IHBLQTY1 ) , '999,999,990.000' ) ) AS IHBLQTY1 , 
					IPIPDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIPPQTY ) , '9,999,990.000' ) ) AS IPIPQTY , 
					IPIEDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIEPQTY ) , '9,999,990.000' ) ) AS IPIEPQTY , 
					IPISDAT , 
					TRIM ( TO_CHAR ( SUM ( IPISQTY ) , '9,999,990.000' ) ) AS IPISQTY 
					FROM 
					( 
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT1 AS IPIPDAT , 
						IPIPPQTY1 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT2 AS IPIPDAT , 
						IPIPPQTY2 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT3 AS IPIPDAT , 
						IPIPPQTY3 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT4 AS IPIPDAT , 
						IPIPPQTY4 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT5 AS IPIPDAT , 
						IPIPPQTY5 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT6 AS IPIPDAT , 
						IPIPPQTY6 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT7 AS IPIPDAT , 
						IPIPPQTY7 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT8 AS IPIPDAT , 
						IPIPPQTY8 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT9 AS IPIPDAT , 
						IPIPPQTY9 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT10 AS IPIPDAT , 
						IPIPPQTY10 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT1 AS IPIEDAT , 
						IPIEPQTY1 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT2 AS IPIEDAT , 
						IPIEPQTY2 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT3 AS IPIEDAT , 
						IPIEPQTY3 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT4 AS IPIEDAT , 
						IPIEPQTY4 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT5 AS IPIEDAT , 
						IPIEPQTY5 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT6 AS IPIEDAT , 
						IPIEPQTY6 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT7 AS IPIEDAT , 
						IPIEPQTY7 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT8 AS IPIEDAT , 
						IPIEPQTY8 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT9 AS IPIEDAT , 
						IPIEPQTY9 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT10 AS IPIEDAT , 
						IPIEPQTY10 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT1 AS IPISDAT , 
						IPISPQTY1 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT2 AS IPISDAT , 
						IPISPQTY2 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT3 AS IPISDAT , 
						IPISPQTY3 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT4 AS IPISDAT , 
						IPISPQTY4 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT5 AS IPISDAT , 
						IPISPQTY5 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT6 AS IPISDAT , 
						IPISPQTY6 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT7 AS IPISDAT , 
						IPISPQTY7 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT8 AS IPISDAT , 
						IPISPQTY8 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT9 AS IPISDAT , 
						IPISPQTY9 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'TG' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT10 AS IPISDAT , 
						IPISPQTY10 AS IPISQTY 
						FROM ORIGINAL_DATA AS ORIGIN 
						INNER JOIN TGSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY10 <> 0 
					) AS TEMP 
					GROUP BY IHHANGCHA , VSDESC1 , IHIPHANG , IPGOKJONG , GKDESC1 , SKDESC1 , IHBLQTY1 , IPIPDAT , IPIEDAT , IPISDAT 
				) , 
  
				ORIGINAL_DATA_PT AS 
				( 
					SELECT 
					IHHANGCHA , 
					VSCODE . CDDESC1 AS VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKCODE . CDDESC1 AS GKDESC1 , 
					SKCODE . CDDESC1 AS SKDESC1 , 
					IHBLQTY1 
					FROM PTSCMLIB . USIIPGOF AS IPGO 
					LEFT OUTER JOIN PTSCMLIB . USIIPHAF AS IPHA 
					ON IPHA . IHHANGCHA = IPGO . IPHANGCHA 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS GKCODE 
					ON 'GK' = GKCODE . CDINDEX 
					AND IPGO . IPGOKJONG = GKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS SKCODE 
					ON 'SK' = SKCODE . CDINDEX 
					AND IPHA . IHSOSOK = SKCODE . CDCODE 
					LEFT OUTER JOIN TGSCMLIB . USICODEF AS VSCODE 
					ON 'VP' = VSCODE . CDINDEX 
					AND IPHA . IHHANGCHA = VSCODE . CDCODE 
					WHERE IHIPHANG BETWEEN P_SDATE AND P_EDATE 
					AND IHSOSOK = ( SELECT VNSOSOK FROM TGSCMLIB . AVENDMF 
					WHERE VNCODE IN ( SELECT * FROM TABLE ( PTSCMLIB . SF_GB_REVCOLROW ( CAST ( P_HWAJU AS VARCHAR ( 100 ) ) , ',' ) ) AS INTABLE ) ) 
					ORDER BY IHHANGCHA 
				) , 
  
				DETAIL_PT AS 
				( 
					SELECT 
					'평택' AS COMPANY , 
					IHHANGCHA , 
					VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKDESC1 , 
					SKDESC1 , 
					TRIM ( TO_CHAR ( SUM ( IHBLQTY1 ) , '999,999,990.000' ) ) AS IHBLQTY1 , 
					IPIPDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIPPQTY ) , '9,999,990.000' ) ) AS IPIPQTY , 
					IPIEDAT , 
					TRIM ( TO_CHAR ( SUM ( IPIEPQTY ) , '9,999,990.000' ) ) AS IPIEPQTY , 
					IPISDAT , 
					TRIM ( TO_CHAR ( SUM ( IPISQTY ) , '9,999,990.000' ) ) AS IPISQTY 
					FROM 
					( 
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT1 AS IPIPDAT , 
						IPIPPQTY1 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT2 AS IPIPDAT , 
						IPIPPQTY2 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT3 AS IPIPDAT , 
						IPIPPQTY3 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT4 AS IPIPDAT , 
						IPIPPQTY4 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT5 AS IPIPDAT , 
						IPIPPQTY5 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT6 AS IPIPDAT , 
						IPIPPQTY6 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT7 AS IPIPDAT , 
						IPIPPQTY7 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT8 AS IPIPDAT , 
						IPIPPQTY8 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT9 AS IPIPDAT , 
						IPIPPQTY9 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						IPIPDAT10 AS IPIPDAT , 
						IPIPPQTY10 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIPPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT1 AS IPIEDAT , 
						IPIEPQTY1 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT2 AS IPIEDAT , 
						IPIEPQTY2 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT3 AS IPIEDAT , 
						IPIEPQTY3 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT4 AS IPIEDAT , 
						IPIEPQTY4 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT5 AS IPIEDAT , 
						IPIEPQTY5 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT6 AS IPIEDAT , 
						IPIEPQTY6 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT7 AS IPIEDAT , 
						IPIEPQTY7 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT8 AS IPIEDAT , 
						IPIEPQTY8 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT9 AS IPIEDAT , 
						IPIEPQTY9 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						IPIEDAT10 AS IPIEDAT , 
						IPIEPQTY10 AS IPIEPQTY , 
						0 AS IPISDAT , 
						0 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPIEPQTY10 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT1 AS IPISDAT , 
						IPISPQTY1 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY1 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT2 AS IPISDAT , 
						IPISPQTY2 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY2 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT3 AS IPISDAT , 
						IPISPQTY3 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY3 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT4 AS IPISDAT , 
						IPISPQTY4 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY4 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT5 AS IPISDAT , 
						IPISPQTY5 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY5 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT6 AS IPISDAT , 
						IPISPQTY6 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY6 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT7 AS IPISDAT , 
						IPISPQTY7 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY7 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT8 AS IPISDAT , 
						IPISPQTY8 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY8 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT9 AS IPISDAT , 
						IPISPQTY9 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY9 <> 0 
  
						UNION ALL 
  
						SELECT 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						ORIGIN . IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						TYJINFWLIB . SF_US_GET_IPHABLQTY ( 'PT' , IPGO . IPHANGCHA , IPGO . IPGOKJONG ) AS IHBLQTY1 , 
						0 AS IPIPDAT , 
						0 AS IPIPPQTY , 
						0 AS IPIEDAT , 
						0 AS IPIEPQTY , 
						IPISDAT10 AS IPISDAT , 
						IPISPQTY10 AS IPISQTY 
						FROM ORIGINAL_DATA_PT AS ORIGIN 
						INNER JOIN PTSCMLIB . USIIPGOF AS IPGO 
						ON IPHANGCHA = IHHANGCHA 
						AND IPGO . IPGOKJONG = ORIGIN . IPGOKJONG 
						AND IPISPQTY10 <> 0 
					) AS TEMP 
					GROUP BY IHHANGCHA , VSDESC1 , IHIPHANG , IPGOKJONG , GKDESC1 , SKDESC1 , IHBLQTY1 , IPIPDAT , IPIEDAT , IPISDAT 
				) , 
  
				LIST AS 
				( 
					SELECT 
					ROW_NUMBER ( ) OVER ( ORDER BY COMPANY , IHHANGCHA , IPGOKJONG ) AS ROWNO , 
					COMPANY , 
					IHHANGCHA , 
					VSDESC1 , 
					IHIPHANG , 
					IPGOKJONG , 
					GKDESC1 , 
					SKDESC1 , 
					IHBLQTY1 , 
					IPIPDAT , 
					IPIPQTY , 
					IPIEDAT , 
					IPIEPQTY , 
					IPISDAT , 
					IPISQTY 
					FROM 
					( 
						SELECT 
						COMPANY , 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						IHBLQTY1 , 
						IPIPDAT , 
						IPIPQTY , 
						IPIEDAT , 
						IPIEPQTY , 
						IPISDAT , 
						IPISQTY 
						FROM DETAIL_GT 
  
						UNION ALL 
  
						SELECT 
						COMPANY , 
						IHHANGCHA , 
						VSDESC1 , 
						IHIPHANG , 
						IPGOKJONG , 
						GKDESC1 , 
						SKDESC1 , 
						IHBLQTY1 , 
						IPIPDAT , 
						IPIPQTY , 
						IPIEDAT , 
						IPIEPQTY , 
						IPISDAT , 
						IPISQTY 
						FROM DETAIL_PT 
					) AS TEMP 
				) 
  
				SELECT 
				COUNT ( * ) AS TOTALCOUNT 
				FROM LIST ; 
  
			OPEN REFCURSOR2 ; 
  
		END PAGING ; 
  
	END MAIN ; 
END P1  ; 
  
