-- 템플릿
CREATE TABLE TYJINFWLIB.TEMPLETE01
(
	  IDX		INT NOT NULL
	, COLUMNS1  CHAR (50) 
	, COLUMNS2	CHAR (50) 
	, COLUMNS3  CHAR (50) 
	, COLUMNS4	CHAR (50) 
	, COLUMNS5  CHAR (50) 
	, COLUMNS6	CHAR (50) 
	, COLUMNS7  CHAR (50) 
	, COLUMNS8	CHAR (50) 
	, COLUMNS9  CHAR (50) 
	, CRTID		CHAR (50) 
	, CRTDT		CHAR (10) 
	, UPDID		CHAR (50) 
	, UPDDT		CHAR (10) 
	, PRIMARY KEY (IDX)
);

COMMENT ON TABLE TYJINFWLIB.TEMPLETE01 IS '템플릿'; 

COMMENT ON COLUMN TYJINFWLIB.TEMPLETE01
(
	IDX IS '문서번호' 
); 

