--DROP PROCEDURE TYJINFWLIB.UTATKHSF_GET_TREND;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKHSF_GET_TREND
-- 작성자     : 이상현
-- 작성일     : 2018-02-07
-- 설명       : 트렌드 조회
-- 예문       : CALL TYJINFWLIB.UTATKJGF_GET_TREND('101','20180101','20180102','')
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.BIN_SYSTEM_CLASS
( 
	IN IN_LOADGUBN VARCHAR(1) , 
	IN IN_SDATE    VARCHAR(8) , 
	IN IN_C2SAUP   VARCHAR(1)  
	
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- 시작

	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
	 
		WITH TABLE1 AS (
			SELECT  C2SAUP,
					C2BCODE||DIGITS(C2MCODE)||'000' AS C2KEYCODE,
					C2NAME ,
					C2XPOINT,
					C2YPOINT,
					C2LXPOINT,
					C2LYPOINT,            
					C2DSGUBN,
					C2SCGUBN,
					'Y' AS SGOKJONGCHECK,
					SGOKJONG,
					( SELECT CDDESC1 FROM TYSCMLIB.USICODEF
					   WHERE CDINDEX = 'GK'
						  AND CDCODE = SGOKJONG) AS SGOKJONGNM,
					'Y' AS SWONSANCHECK,        
				GCOLOR AS SGKCOLOR,
					SWONSAN,
					( SELECT SUBSTR(CDDESC1,1,5) FROM TYSCMLIB.USICODEF
					   WHERE CDINDEX = 'WN'
						  AND CDCODE = SWONSAN) AS SWONSANNM,
					'N' AS SHANGCHACHECK,                 
					SHANGCHA,
					( SELECT SUBSTRING(CDDESC1,1,6) FROM TYSCMLIB.USICODEF
						 WHERE CDINDEX = 'VS'
					 AND CDCODE = SHANGCHA) AS SHANGCHANM,                        
					CASE WHEN  SCLDATE = '' THEN ''
					ELSE SUBSTR(SCLDATE,3,2)||'/'||SUBSTR(SCLDATE,5,2)||'/'||SUBSTR(SCLDATE,7,2) END AS  SCLDATE,            
					SCLDATE as BINCLEDAY,            
					CASE WHEN SIPDATE = '' THEN '' ELSE  SUBSTR(SIPDATE,3,2)||'/'||SUBSTR(SIPDATE,5,2)||'/'||SUBSTR(SIPDATE,7,2)  
								END AS SIPDATE ,
					SCHULQTY,
					SJEGOQTY,
				   VALUE( CASE WHEN TEMP.BINTEMPA >= 999 THEN 0
							WHEN TEMP.BINTEMPA <= -999 THEN 0
					ELSE TEMP.BINTEMPA END ,0) AS STEMPA,
				   VALUE( CASE WHEN TEMP.BINTEMPB >= 999 THEN 0
							WHEN TEMP.BINTEMPB <= -999 THEN 0
					ELSE TEMP.BINTEMPB END ,0) AS STEMPB,
				   VALUE( CASE WHEN TEMP.BINTEMPC >= 999 THEN 0
							WHEN TEMP.BINTEMPC <= -999 THEN 0
					ELSE TEMP.BINTEMPC END ,0) AS STEMPC,
				   VALUE( CASE WHEN TEMP.BINTEMPD >= 999 THEN 0
							WHEN TEMP.BINTEMPD <= -999 THEN 0
					ELSE TEMP.BINTEMPD END ,0) AS STEMPD,
				   VALUE( CASE WHEN TEMP.BINTEMPE >= 999 THEN 0
							WHEN TEMP.BINTEMPE <= -999 THEN 0
					ELSE TEMP.BINTEMPE END ,0) AS STEMPE,
				   VALUE( CASE WHEN TEMP.BINTEMPF >= 999 THEN 0
							WHEN TEMP.BINTEMPF <= -999 THEN 0
					ELSE TEMP.BINTEMPF END ,0) AS STEMPF,
				   VALUE( CASE WHEN TEMP.BINTEMPG >= 999 THEN 0
							WHEN TEMP.BINTEMPG <= -999 THEN 0
					ELSE TEMP.BINTEMPG END ,0) AS STEMPG,
				   VALUE( CASE WHEN TEMP.BINTEMPH >= 999 THEN 0
							WHEN TEMP.BINTEMPH <= -999 THEN 0
					ELSE TEMP.BINTEMPH END ,0) AS STEMPH,
				   VALUE( CASE WHEN TEMP.BINTEMPI >= 999 THEN 0
							WHEN TEMP.BINTEMPI <= -999 THEN 0
					ELSE TEMP.BINTEMPI END ,0) AS STEMPI,     
					VALUE(( SELECT CCAPA FROM TYSCMLIB.BIN_CAPAMF
					   WHERE CBINNO = C2MCODE ),0) AS SCAPA,
				   BTCHULIL,
				   BTTKNO,                                
				   CAST(IN_LOADGUBN AS VARCHAR(1)) AS LOADGUBN             
		FROM TYSCMLIB.BIN_SYSTEM_CLASS2  
		LEFT OUTER JOIN  (  SELECT  BINNO,  BINTEMPA, BINTEMPB, BINTEMPC, BINTEMPD, BINTEMPE, BINTEMPF, BINTEMPG, BINTEMPH, BINTEMPI
					   FROM TYSCMLIB.BINTEMPLISTF
					  WHERE BINDATE = SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTR(CHAR(CURRENT_DATE),6,2)||SUBSTR(CHAR(CURRENT_DATE),9,2) 
						 AND BINTIME = ( SELECT MAX(BINTIME) FROM  TYSCMLIB.BINTEMPLISTF
												   WHERE  BINDATE = SUBSTR(CHAR(CURRENT_DATE),1,4)||SUBSTR(CHAR(CURRENT_DATE),6,2)||SUBSTR(CHAR(CURRENT_DATE),9,2)))  TEMP
				ON TEMP.BINNO = C2MCODE
		LEFT OUTER JOIN TYSCMLIB.USIBNSTF
			 ON BTCHULIL = TRIM(REPLACE(CHAR(CURRENT_DATE) , '-' , ''))
			AND BTINTIME > 0     
			AND BTCHKIN = '*'   
			AND BTBINNO = C2MCODE
		LEFT OUTER JOIN TYSCMLIB.BIN_STATUSMF 
			ON  SDATE = CAST(IN_SDATE AS VARCHAR(8))
		   AND   SBINNO    = C2MCODE  
		LEFT OUTER JOIN TYSCMLIB.BIN_GKCOLORMF
		ON SGOKJONG = GGOKJONG

		WHERE C2SAUP = IN_C2SAUP
		 AND  SUBSTR(C2DSGUBN,1,4) = 'TANK'
		 AND  C2SCGUBN IN ( 'MainA',  'MainB', 'MainC', 'MainD','MainE')
		  AND C2BCODE||DIGITS(C2MCODE)||'000' <= '30904000'
		  )
		SELECT C2SAUP,
			   C2KEYCODE,
					C2NAME ,
					C2XPOINT,
					C2YPOINT,
					C2LXPOINT,
					C2LYPOINT,            
					C2DSGUBN,
					C2SCGUBN,
					 SGOKJONGCHECK,
					CASE WHEN SGOKJONG = '00' THEN '' ELSE  SGOKJONG END SGOKJONG,
					CASE WHEN SGOKJONG = '00' THEN '' ELSE  SGOKJONGNM END SGOKJONGNM,
					CASE WHEN SGKCOLOR = '' THEN 'FFFFFF' ELSE SGKCOLOR END SGKCOLOR,
					SWONSANCHECK,                  
					CASE WHEN SWONSAN = '00' THEN '' ELSE  SWONSAN END SWONSAN,
					CASE WHEN SWONSAN = '00' THEN '' ELSE  SWONSANNM END SWONSANNM,
					SHANGCHACHECK,                 
					SHANGCHA,
					SHANGCHANM,
					SCLDATE,
					CASE WHEN BINCLEDAY != '' THEN TYSCMLIB.SF_SILOBIN_ADDMONTH(BINCLEDAY)
					ELSE 0 END AS BINCLEDAY,
					BINCLEDAY,
					SIPDATE ,
					CASE WHEN SCAPA > 0 THEN SCHULQTY ELSE 0 END SCHULQTY,
					CASE WHEN SCAPA > 0 THEN SJEGOQTY ELSE 0 END SJEGOQTY,
							CASE WHEN SCAPA >0 THEN ( 
							CASE WHEN SGOKJONG <> '00' THEN ( 
									 CASE WHEN SJEGOQTY > 0 THEN  SCAPA - SJEGOQTY ELSE 0 END) 
							ELSE 0 END)  
					ELSE 0 END  SEMPQTY,
					STEMPA,
					STEMPB,
					STEMPC,
					STEMPD,
					STEMPE,
					STEMPF,
					STEMPG,
					STEMPH,
					STEMPI,
					SCAPA,
				   CASE WHEN  BTCHULIL IS NULL THEN '' ELSE BTCHULIL END  BTCHULIL,
				   CASE WHEN  BTTKNO IS NULL THEN 0 ELSE BTTKNO END  BTTKNO,
					CASE WHEN SCAPA = 0 THEN 0
					ELSE  INT( ROUND(( DOUBLE(SJEGOQTY * 100) / SCAPA),0)) END  AS SJEGOQTYRATE,
					( SELECT  VALUE(SUM(SCHULQTY),0)
					  FROM  TABLE1
					  WHERE  SCAPA > 0 )  AS  SCHULQTYTOTAL,  
				( SELECT  VALUE(SUM(SCAPA),0) - VALUE(SUM(SJEGOQTY),0)
						  FROM  TABLE1
            			  WHERE  SGOKJONG <> '00' AND SCAPA > 0 AND SJEGOQTY > 0)  AS EMPQTYTOTAL,     
					( SELECT  VALUE(SUM(SJEGOQTY),0)
					  FROM  TABLE1
					  WHERE  SCAPA > 0 )  AS SJEGOQTYTOTAL,
					CASE WHEN TYSCMLIB.SF_SILOBIN_STATUS(TRIM(REPLACE(CHAR(CURRENT_DATE) , '-' , '')),TRIM(C2NAME),'CODE') != 'END' THEN
							 TYSCMLIB.SF_SILOBIN_STATUS(TRIM(REPLACE(CHAR(CURRENT_DATE) , '-' , '')),TRIM(C2NAME),'CODE')
					 ELSE '' END AS BINSTATUSCODE,
					CASE WHEN TYSCMLIB.SF_SILOBIN_STATUS(TRIM(REPLACE(CHAR(CURRENT_DATE) , '-' , '')),TRIM(C2NAME),'CODE') != 'END' THEN
							 TYSCMLIB.SF_SILOBIN_STATUS(TRIM(REPLACE(CHAR(CURRENT_DATE) , '-' , '')),TRIM(C2NAME),'NAME')
					 ELSE '' END AS BINSTATUSNAME,
					 LOADGUBN
		FROM TABLE1
		ORDER BY C2KEYCODE;

		 
	OPEN REFCURSOR ; 

END
;



