--DROP PROCEDURE TYJINFWLIB.UTATKHSF_GET_TREND;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKHSF_GET_TREND
-- 작성자     : 이상현
-- 작성일     : 2018-02-07
-- 설명       : 트렌드 조회
-- 예문       : CALL TYJINFWLIB.UTATKJGF_GET_TREND('101','20180101','20180102','')
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.UTATKHSF_GET_TREND
( 
	IN IN_TUGOTK VARCHAR(4) , 
	IN IN_TUGOIL VARCHAR(10) , 
	IN IN_TUSTTIME VARCHAR(6) , 
	IN IN_TUEDTIME VARCHAR(6) , 
	IN IN_TUGOTM VARCHAR(200)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- 시작

	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
	 
		SELECT 
			TUGOTK , 
			TUGOIL , 
			TUGOTM , 
			TUGOMASS , 
			TUGOTEMP , 
			TUHIGH , 
			TUGKLQTY , 
			TUNKLQTY , 
			TUHWAMUL , 
			TUHMNAME , 
			JECAPA , 
			TNHIGH,
			JENKLQTY,
			TUPRESS AS JEPRESS
			FROM 
			( 
			SELECT 
			TUGOTK , 
			TUGOIL , 
			SUBSTR ( TUGOTM , 1 , 2 ) || ':' || SUBSTR ( TUGOTM , 3 , 2 ) AS TUGOTM , 
			TUGOMASS , 
			TUGOTEMP , 
			TUHIGH , 
			TUGKLQTY , 
			TUNKLQTY , 
			TUHWAMUL , 
			TUHMNAME , 
			(CEILING((JECAPA/100))*100) AS JECAPA , 
			CEILING(TNHIGH)*100 AS TNHIGH,
			ROUND ( ( JEGOMASS / JEGKLQTY ) * JECAPA , 0 ) AS JENKLQTY , 
			TUPRESS,
			ROWNUMBER ( ) OVER ( PARTITION BY SUBSTR ( TUGOTM , 1 , 4 ) ORDER BY TUGOTM ) AS NUMBER 
			FROM TYSCMLIB . UTATKHGF 
			LEFT OUTER JOIN TYSCMLIB . UTATKJGF 
			ON TRIM ( JEGOTK ) = TRIM ( TUGOTK ) 
			LEFT OUTER JOIN TYSCMLIB.UTITANKF
			ON TRIM(TNTANKNO) = TRIM(TUGOTK)
			WHERE TUGOTK = (CASE WHEN LENGTH(IN_TUGOTK) = 3 THEN ' '|| IN_TUGOTK ELSE IN_TUGOTK END)
			AND TUGOIL = REPLACE ( CHAR ( IN_TUGOIL ) , '-' , '' ) 
			AND TUGOTM BETWEEN IN_TUSTTIME AND IN_TUEDTIME 
			AND SUBSTR ( TUGOTM , 3 , 2 ) IN ( SELECT * FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( CAST ( IN_TUGOTM AS VARCHAR ( 200 ) ) , ',' ) ) AS INTABLE ) 

			UNION ALL 

			SELECT 
			TUGOTK , 
			TUGOIL , 
			'24:00' AS TUGOTM , 
			TUGOMASS , 
			TUGOTEMP , 
			TUHIGH , 
			TUGKLQTY , 
			TUNKLQTY , 
			TUHWAMUL , 
			TUHMNAME , 
			(CEILING((JECAPA/100))*100) AS JECAPA , 
			CEILING(TNHIGH)*100 AS TNHIGH,
			ROUND ( ( JEGOMASS / JEGKLQTY ) * JECAPA , 0 ) AS JENKLQTY , 
			TUPRESS,
			ROWNUMBER ( ) OVER ( PARTITION BY SUBSTR ( TUGOTM , 1 , 4 ) ORDER BY TUGOTM ) AS NUMBER 
			FROM TYSCMLIB . UTATKHGF 
			LEFT OUTER JOIN TYSCMLIB . UTATKJGF 
			ON TRIM ( JEGOTK ) = TRIM ( TUGOTK ) 
			LEFT OUTER JOIN TYSCMLIB.UTITANKF
			ON TRIM(TNTANKNO) = TRIM(TUGOTK)
			WHERE TUGOTK = (CASE WHEN LENGTH(IN_TUGOTK) = 3 THEN ' '|| IN_TUGOTK ELSE IN_TUGOTK END)
			AND TUGOIL = ( SELECT REPLACE ( CHAR ( ( DATE ( IN_TUGOIL ) + 1 DAYS ) , ISO ) , '-' , '' ) FROM SYSIBM . SYSDUMMY1 ) 
			AND TUGOTM BETWEEN '000000' AND '002900' 
			AND SUBSTR ( TUGOTM , 3 , 2 ) IN ( '00' , '30' ) 
			) A 
			WHERE NUMBER = '1' ; 
		 
	OPEN REFCURSOR ; 

END
;



