--DROP PROCEDURE TYJINFWLIB.UTATKJGF_GET_WARNTANK;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKJGF_GET_WARNTANK
-- 작성자     : 이상현
-- 작성일     : 2018-02-07
-- 설명       : 트렌드 조회
-- 예문       : CALL TYJINFWLIB.UTATKJGF_GET_WARNTANK()
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.UTATKJGF_GET_WARNTANK 
( 
	IN_TKSABUN			VARCHAR(8) , 
	IN IN_JALGOIL		VARCHAR(8) 
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- 시작

	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
	 
		WITH TABLE1 AS 
		( 
		SELECT 
		* 
		FROM 
		TYSCMLIB . PSTKMONITORF 
		WHERE TKSABUN = IN_TKSABUN
		) , 
		TABLE2 AS 
		( 
		SELECT 
		TKNO1 AS TKNO 
		FROM TABLE1 
		WHERE TKNO1 <> '' 
		UNION ALL 
		SELECT 
		TKNO2 AS TKNO 
		FROM TABLE1 
		WHERE TKNO2 <> '' 
		UNION ALL 
		SELECT 
		TKNO3 AS TKNO 
		FROM TABLE1 
		WHERE TKNO3 <> '' 
		UNION ALL 
		SELECT 
		TKNO4 AS TKNO 
		FROM TABLE1 
		WHERE TKNO4 <> '' 
		UNION ALL 
		SELECT 
		TKNO5 AS TKNO 
		FROM TABLE1 
		WHERE TKNO5 <> '' 
		UNION ALL 
		SELECT 
		TKNO6 AS TKNO 
		FROM TABLE1 
		WHERE TKNO6 <> '' 
		UNION ALL 
		SELECT 
		TKNO7 AS TKNO 
		FROM TABLE1 
		WHERE TKNO7 <> '' 
		UNION ALL 
		SELECT 
		TKNO8 AS TKNO 
		FROM TABLE1 
		WHERE TKNO8 <> '' 
		UNION ALL 
		SELECT 
		TKNO9 AS TKNO 
		FROM TABLE1 
		WHERE TKNO9 <> '' 
		UNION ALL 
		SELECT 
		TKNO10 AS TKNO 
		FROM TABLE1 
		WHERE TKNO10 <> '' 
		) , 
		TABLE3 AS 
		( 
		SELECT 
		TKNO 
		FROM TABLE2 
		GROUP BY TKNO 
		ORDER BY TKNO 
		) , 
		TABLE4 AS 
		( 
		SELECT 
		JALTKNO , 
		SUBSTR(JALGOIL,1,4) || '-' || SUBSTR(JALGOIL,5,2) || '-' || SUBSTR(JALGOIL,7,2) AS JALGOIL,
		SUBSTR(JALGOTM,1,2) || ':' || SUBSTR(JALGOTM,3,2) || ':' || SUBSTR(JALGOTM,5,2) AS JALGOTM,
		JALALRGN , 
		JALSTVALUE , 
		JALNWVALUE , 
		JALCLGOIL , 
		JALCLGOTM		, 
		1 AS JALGUBN 
		FROM TYSCMLIB . UTAALARMF 
		WHERE JALCLGOIL = '' 
		AND JALCLGOTM = '' 
		UNION ALL 
		SELECT 
		JALTKNO , 
		SUBSTR(JALGOIL,1,4) || '-' || SUBSTR(JALGOIL,5,2) || '-' || SUBSTR(JALGOIL,7,2) AS JALGOIL,
		SUBSTR(JALGOTM,1,2) || ':' || SUBSTR(JALGOTM,3,2) || ':' || SUBSTR(JALGOTM,5,2) AS JALGOTM,
		JALALRGN , 
		JALSTVALUE , 
		JALNWVALUE , 
		SUBSTR(JALCLGOIL,1,4) || '-' || SUBSTR(JALCLGOIL,5,2) || '-' || SUBSTR(JALCLGOIL,7,2) AS JALCLGOIL,
		SUBSTR(JALCLGOTM,1,2) || ':' || SUBSTR(JALCLGOTM,3,2) || ':' || SUBSTR(JALCLGOTM,5,2) AS JALCLGOTM,
		2 AS JALGUBN 
		FROM TYSCMLIB . UTAALARMF 
		WHERE JALCLGOIL <> '' 
		AND JALCLGOTM <> '' 
		AND JALGOIL = IN_JALGOIL
		UNION ALL 
		SELECT 
		JALTKNO , 
		SUBSTR(JALGOIL,1,4) || '-' || SUBSTR(JALGOIL,5,2) || '-' || SUBSTR(JALGOIL,7,2) AS JALGOIL,
		SUBSTR(JALGOTM,1,2) || ':' || SUBSTR(JALGOTM,3,2) || ':' || SUBSTR(JALGOTM,5,2) AS JALGOTM,
		JALALRGN , 
		JALSTVALUE , 
		JALNWVALUE , 
		SUBSTR(JALCLGOIL,1,4) || '-' || SUBSTR(JALCLGOIL,5,2) || '-' || SUBSTR(JALCLGOIL,7,2) AS JALCLGOIL,
		SUBSTR(JALCLGOTM,1,2) || ':' || SUBSTR(JALCLGOTM,3,2) || ':' || SUBSTR(JALCLGOTM,5,2) AS JALCLGOTM,
		2 AS JALGUBN 
		FROM TYSCMLIB . UTAALARMF 
		WHERE JALCLGOIL <> '' 
		AND JALCLGOTM <> '' 
		AND JALCLGOIL >= IN_JALGOIL
		AND JALGOIL < IN_JALGOIL
		) 
		SELECT 
		JALTKNO , 
		JALGOIL , 
		JALGOTM , 
		JALGOIL || JALGOTM AS JALGOILTM , 
		JALALRGN , 
		CASE WHEN JALALRGN = 'HH' THEN 'TEMP-HIGH' ELSE 
		( CASE WHEN JALALRGN = 'HL' THEN 'TEMP-LOW' ELSE 
		( CASE WHEN JALALRGN = 'LV' THEN 'LEVEL-HIGH' ELSE
		( CASE WHEN JALALRGN = 'PH' THEN 'PRESS-HIGH' ELSE
		( CASE WHEN JALALRGN = 'PL' THEN 'PRESS-LOW' ELSE '' 
		END ) END ) END ) END ) END AS JALALRGNNM , 
		JALSTVALUE , 
		JALNWVALUE , 
		JALCLGOIL , 
		JALCLGOTM , 
		JALCLGOIL || JALCLGOTM AS JALCLGOILTM,
		JALGUBN , 
		CASE WHEN TKNO <> '' THEN 1 ELSE 2 END AS JALPGUBN 
		FROM TABLE4 T4 
		LEFT OUTER JOIN TABLE3 T3 
		ON JALTKNO = TKNO 
		ORDER BY JALGUBN , JALPGUBN , JALGOIL DESC , JALGOTM DESC ; 
  
		 
	OPEN REFCURSOR ; 

END
;



-----------

--DROP PROCEDURE TYJINFWLIB.UTATKJGF_GET_WARNTANK_NEW;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKJGF_GET_WARNTANK_NEW
-- 작성자     : 이상현
-- 작성일     : 2018-02-07
-- 설명       : 트렌드 조회
-- 예문       : CALL TYJINFWLIB.UTATKJGF_GET_WARNTANK_NEW()
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.UTATKJGF_GET_WARNTANK_NEW 
( 
	IN_TKSABUN			VARCHAR(8) , 
	IN IN_JALGOIL		VARCHAR(8) 
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- 시작

	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
	 
		WITH TABLE1 AS 
		( 
		SELECT 
		* 
		FROM 
		TYSCMLIB . PSTKMONITORF 
		WHERE TKSABUN = IN_TKSABUN 
		) , 
		TABLE2 AS 
		( 
		SELECT 
		TKNO1 AS TKNO 
		FROM TABLE1 
		WHERE TKNO1 <> '' 
		UNION ALL 
		SELECT 
		TKNO2 AS TKNO 
		FROM TABLE1 
		WHERE TKNO2 <> '' 
		UNION ALL 
		SELECT 
		TKNO3 AS TKNO 
		FROM TABLE1 
		WHERE TKNO3 <> '' 
		UNION ALL 
		SELECT 
		TKNO4 AS TKNO 
		FROM TABLE1 
		WHERE TKNO4 <> '' 
		UNION ALL 
		SELECT 
		TKNO5 AS TKNO 
		FROM TABLE1 
		WHERE TKNO5 <> '' 
		UNION ALL 
		SELECT 
		TKNO6 AS TKNO 
		FROM TABLE1 
		WHERE TKNO6 <> '' 
		UNION ALL 
		SELECT 
		TKNO7 AS TKNO 
		FROM TABLE1 
		WHERE TKNO7 <> '' 
		UNION ALL 
		SELECT 
		TKNO8 AS TKNO 
		FROM TABLE1 
		WHERE TKNO8 <> '' 
		UNION ALL 
		SELECT 
		TKNO9 AS TKNO 
		FROM TABLE1 
		WHERE TKNO9 <> '' 
		UNION ALL 
		SELECT 
		TKNO10 AS TKNO 
		FROM TABLE1 
		WHERE TKNO10 <> '' 
		) , 
		TABLE3 AS 
		( 
		SELECT 
		TKNO 
		FROM TABLE2 
		GROUP BY TKNO 
		ORDER BY TKNO 
		) , 
		TABLE4 AS 
		( 
		SELECT 
		JALTKNO , 
		SUBSTR ( JALGOIL , 1 , 4 ) || '-' || SUBSTR ( JALGOIL , 5 , 2 ) || '-' || SUBSTR ( JALGOIL , 7 , 2 ) AS JALGOIL , 
		SUBSTR ( JALGOTM , 1 , 2 ) || ':' || SUBSTR ( JALGOTM , 3 , 2 ) || ':' || SUBSTR ( JALGOTM , 5 , 2 ) AS JALGOTM , 
		JALALRGN , 
		JALSTVALUE , 
		JALNWVALUE , 
		JALCLGOIL , 
		JALCLGOTM , 
		JALCLVALUE , 
		1 AS JALGUBN 
		FROM TYSCMLIB . UTAALARMF 
		WHERE JALCLGOIL = '' 
		AND JALCLGOTM = '' 
		UNION ALL 
		SELECT 
		JALTKNO , 
		SUBSTR ( JALGOIL , 1 , 4 ) || '-' || SUBSTR ( JALGOIL , 5 , 2 ) || '-' || SUBSTR ( JALGOIL , 7 , 2 ) AS JALGOIL , 
		SUBSTR ( JALGOTM , 1 , 2 ) || ':' || SUBSTR ( JALGOTM , 3 , 2 ) || ':' || SUBSTR ( JALGOTM , 5 , 2 ) AS JALGOTM , 
		JALALRGN , 
		JALSTVALUE , 
		JALNWVALUE , 
		SUBSTR ( JALCLGOIL , 1 , 4 ) || '-' || SUBSTR ( JALCLGOIL , 5 , 2 ) || '-' || SUBSTR ( JALCLGOIL , 7 , 2 ) AS JALCLGOIL , 
		SUBSTR ( JALCLGOTM , 1 , 2 ) || ':' || SUBSTR ( JALCLGOTM , 3 , 2 ) || ':' || SUBSTR ( JALCLGOTM , 5 , 2 ) AS JALCLGOTM , 
		JALCLVALUE , 
		2 AS JALGUBN 
		FROM TYSCMLIB . UTAALARMF 
		WHERE JALCLGOIL <> '' 
		AND JALCLGOTM <> '' 
		AND JALGOIL = IN_JALGOIL 
		UNION ALL 
		SELECT 
		JALTKNO , 
		SUBSTR ( JALGOIL , 1 , 4 ) || '-' || SUBSTR ( JALGOIL , 5 , 2 ) || '-' || SUBSTR ( JALGOIL , 7 , 2 ) AS JALGOIL , 
		SUBSTR ( JALGOTM , 1 , 2 ) || ':' || SUBSTR ( JALGOTM , 3 , 2 ) || ':' || SUBSTR ( JALGOTM , 5 , 2 ) AS JALGOTM , 
		JALALRGN , 
		JALSTVALUE , 
		JALNWVALUE , 
		SUBSTR ( JALCLGOIL , 1 , 4 ) || '-' || SUBSTR ( JALCLGOIL , 5 , 2 ) || '-' || SUBSTR ( JALCLGOIL , 7 , 2 ) AS JALCLGOIL , 
		SUBSTR ( JALCLGOTM , 1 , 2 ) || ':' || SUBSTR ( JALCLGOTM , 3 , 2 ) || ':' || SUBSTR ( JALCLGOTM , 5 , 2 ) AS JALCLGOTM , 
		JALCLVALUE , 
		2 AS JALGUBN 
		FROM TYSCMLIB . UTAALARMF 
		WHERE JALCLGOIL <> '' 
		AND JALCLGOTM <> '' 
		AND JALCLGOIL >= IN_JALGOIL 
		AND JALGOIL < IN_JALGOIL 
		) 
		SELECT 
		JALTKNO , 
		JALGOIL , 
		JALGOTM , 
		JALGOIL || ' / ' || JALGOTM AS JALGOILTM , 
		JALALRGN , 
		CASE WHEN JALALRGN = 'HH' THEN 'TEMP-HIGH' ELSE 
		( CASE WHEN JALALRGN = 'HL' THEN 'TEMP-LOW' ELSE 
		( CASE WHEN JALALRGN = 'LV' THEN 'LEVEL-HIGH' ELSE
		( CASE WHEN JALALRGN = 'PH' THEN 'PRESS-HIGH' ELSE
		( CASE WHEN JALALRGN = 'PL' THEN 'PRESS-LOW' ELSE '' 
		END ) END ) END ) END ) END AS JALALRGNNM , 
		JALSTVALUE , 
		JALNWVALUE , 
		JALCLGOIL , 
		JALCLGOTM , 
		CASE WHEN JALCLGOIL <> '' THEN JALCLGOIL || ' / ' || JALCLGOTM ELSE '' END AS JALCLGOILTM , 
		JALCLVALUE , 
		JALGUBN , 
		CASE WHEN TKNO <> '' THEN ( CASE WHEN JALCLGOIL = '' THEN 1 ELSE 2 END ) ELSE 2 END AS JALPGUBN 
		FROM TABLE4 T4 
		LEFT OUTER JOIN TABLE3 T3 
		ON JALTKNO = TKNO 
		ORDER BY JALGUBN , JALPGUBN , JALGOIL DESC , JALGOTM DESC ; 
  
		 
	OPEN REFCURSOR ; 

END
;



