--DROP PROCEDURE TYJINFWLIB.UTATKJGF_GET_TANKPAGEWARN;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKJGF_GET_TANKPAGEWARN
-- 작성자     : 이상현
-- 작성일     : 2018-02-13
-- 설명       : 예제 리스트
-- 예문       : CALL TYJINFWLIB.UTATKJGF_GET_TANKPAGEWARN ('0403-M')
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.UTATKJGF_GET_TANKPAGEWARN 
( 
	IN_TKSABUN			VARCHAR(8)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- 시작
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (
			SELECT
			*
			FROM 
			TYSCMLIB.PSTKMONITORF
			WHERE TKSABUN = IN_TKSABUN
		),
		TABLE2 AS(
			SELECT
			TKNO1 AS TKNO
			FROM TABLE1
			WHERE TKNO1 <> ''
			UNION ALL
			SELECT
			TKNO2 AS TKNO
			FROM TABLE1
			WHERE TKNO2 <> ''
			UNION ALL
			SELECT
			TKNO3 AS TKNO
			FROM TABLE1
			WHERE TKNO3 <> ''
			UNION ALL
			SELECT
			TKNO4 AS TKNO
			FROM TABLE1
			WHERE TKNO4 <> ''
			UNION ALL
			SELECT
			TKNO5 AS TKNO
			FROM TABLE1
			WHERE TKNO5 <> ''
			UNION ALL
			SELECT
			TKNO6 AS TKNO
			FROM TABLE1
			WHERE TKNO6 <> ''
			UNION ALL
			SELECT
			TKNO7 AS TKNO
			FROM TABLE1
			WHERE TKNO7 <> ''
			UNION ALL
			SELECT
			TKNO8 AS TKNO
			FROM TABLE1
			WHERE TKNO8 <> ''
			UNION ALL
			SELECT
			TKNO9 AS TKNO
			FROM TABLE1
			WHERE TKNO9 <> ''
			UNION ALL
			SELECT
			TKNO10 AS TKNO
			FROM TABLE1
			WHERE TKNO10 <> ''
		)
		SELECT
			JEGOTK,                         
			JEHIGH,                         
			KJWF.TANKLEVEL AS LEVEL_H,                   
			(ANKF.TNL) * 100 AS LEVEL_L,                    
			(TNHIGH * 100) AS LEVEL
		FROM TYSCMLIB.UTATKJGF AS KJGF         
			LEFT OUTER JOIN TYSCMLIB.UTITANKF AS ANKF         
			ON TRIM(ANKF.TNTANKNO) = TRIM(KJGF.JEGOTK)         
			LEFT OUTER JOIN TYSCMLIB.UTAHMBJF BJ 
			ON   BJ.HMCODE = KJGF.JEHWAMUL
			LEFT OUTER JOIN TYSCMLIB.UTATKJWF KJWF
			ON   TRIM(KJWF.TANKNO) = TRIM(KJGF.JEGOTK)    
			LEFT OUTER JOIN TABLE2
			ON TABLE2.TKNO = KJGF.JEGOTK
		WHERE KJWF.TANKLEVEL < JEHIGH
		OR JEPRESS >= 50
		OR JEPRESS <= -40
		AND KJGF.JEGOTK IN (TABLE2.TKNO);
		
	OPEN REFCURSOR;

END



