--DROP PROCEDURE TYJINFWLIB.UTATKJGF_SET_TANKPAGE;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKJGF_SET_TANKPAGE
-- 작성자     : 이상현
-- 작성일     : 2018-02-13
-- 설명       : 예제 리스트
-- 예문       : CALL TYJINFWLIB.UTATKJGF_SET_TANKPAGE ('0403-M',1,'101','101','101','101','101','101','101','101','101','101','A','')
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.UTATKJGF_SET_TANKPAGE 
( 
	IN IN_TKSABUN			VARCHAR(8),
	IN IN_TKINDEX           VARCHAR(2),
	IN IN_TKNO1		        VARCHAR(4),
	IN IN_TKNO2		        VARCHAR(4),
	IN IN_TKNO3		        VARCHAR(4),
	IN IN_TKNO4		        VARCHAR(4),
	IN IN_TKNO5		        VARCHAR(4),
	IN IN_TKNO6		        VARCHAR(4),
	IN IN_TKNO7		        VARCHAR(4),
	IN IN_TKNO8		        VARCHAR(4),
	IN IN_TKNO9		        VARCHAR(4),
	IN IN_TKN10		        VARCHAR(4),
	IN IN_TKGUBN	        VARCHAR(1),
	OUT RET_MSG				VARCHAR(100)
)
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.UTATKJGF_SET_TANKPAGE
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
P1 : BEGIN -- 시작
    
	DECLARE V_CNT	 NUMERIC (2 , 0 ) DEFAULT 0;

	SELECT                         
	COUNT(*) INTO V_CNT
	FROM TYSCMLIB.PSTKMONITORF     
	WHERE TKSABUN = IN_TKSABUN
	AND TKINDEX = IN_TKINDEX;

	IF V_CNT = 0 THEN 
		IF IN_TKGUBN <> 'D' THEN 
			INSERT INTO TYSCMLIB.PSTKMONITORF
			(
			TKSABUN,
			TKINDEX,
			TKNO1,
			TKNO2,
			TKNO3,
			TKNO4,
			TKNO5,
			TKNO6,
			TKNO7,
			TKNO8,
			TKNO9,
			TKNO10,
			TKHIGB,
			TKHIDAT,
			TKHITIM,
			TKHISAB)
			VALUES(                        
			IN_TKSABUN,
			IN_TKINDEX,
			IN_TKNO1,
			IN_TKNO2,
			IN_TKNO3,
			IN_TKNO4,
			IN_TKNO5,
			IN_TKNO6,
			IN_TKNO7,
			IN_TKNO8,
			IN_TKNO9,
			IN_TKN10,
			'A',
			CURRENT_DATE,
			CURRENT_TIME,
			IN_TKSABUN);
		END IF;
	END IF;

	IF V_CNT = 1 THEN 
		IF IN_TKGUBN <> 'D' THEN 
			UPDATE TYSCMLIB.PSTKMONITORF SET
			TKNO1 = IN_TKNO1,
			TKNO2 = IN_TKNO2,
			TKNO3 = IN_TKNO3,
			TKNO4 = IN_TKNO4,
			TKNO5 = IN_TKNO5,
			TKNO6 = IN_TKNO6,
			TKNO7 = IN_TKNO7,
			TKNO8 = IN_TKNO8,
			TKNO9 = IN_TKNO9,
			TKNO10 = IN_TKN10,
			TKHIGB = 'C',
			TKHIDAT = CURRENT_DATE,
			TKHITIM = CURRENT_TIME,
			TKHISAB = IN_TKSABUN
			WHERE TKSABUN = IN_TKSABUN
			AND TKINDEX  = IN_TKINDEX;
		END IF;

		IF IN_TKGUBN = 'D' THEN 
			DELETE FROM TYSCMLIB.PSTKMONITORF
			WHERE TKSABUN = IN_TKSABUN
			AND TKINDEX = IN_TKINDEX;
		END IF;
	END IF;

	SET RET_MSG = 'SUCCESS!' ; 
END