--DROP PROCEDURE TYJINFWLIB.UTATKJGF_SET_TANKTEMP;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : UTATKJGF_SET_TANKTEMP
-- 작성자     : 이상현
-- 작성일     : 2018-02-13
-- 설명       : 예제 리스트
-- 예문       : CALL TYJINFWLIB.UTATKJGF_SET_TANKTEMP ('101','50','0','0403-M','')
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.UTATKJGF_SET_TANKTEMP
( 
	IN_TANKNO			VARCHAR(4),
	IN_TANKTEMPH 		VARCHAR(10),
	IN_TANKTEMPL        VARCHAR(10),
	IN_TANKHISAB	    VARCHAR(8),
	RET_MSG				VARCHAR(100)
)
    LANGUAGE SQL 
	SPECIFIC TYJINFWLIB.UTATKJGF_SET_TANKTEMP
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
    
P1 : BEGIN -- 시작

		UPDATE TYSCMLIB.UTATKJWF SET
		TANKTEMPH = IN_TANKTEMPH,
		TANKTEMPL = IN_TANKTEMPL,
		TANKHIGB  = 'C',
		TANKHIDAT = CURRENT_DATE,
		TANKHITIM = CURRENT_TIME,
		TANKHISAB = IN_TANKHISAB
		WHERE TRIM(TANKNO) = IN_TANKNO;

	SET RET_MSG = 'SUCCESS!' ; 
END