--DROP PROCEDURE TYJINFWLIB.ORG_DEPT_ORGCHART_GROUP_OFFICER_GET;
-------------------------------------------------------------------------------------------
-- 프로시저명 : ORG_DEPT_ORGCHART_GROUP_OFFICER_GET
-- 작성자     : 박제영
-- 작성일     : 2015-10-06
-- 설명       : 조직도 그룹에 속한 임직원을 조회한다.
-- 예문       : CALL ORG_DEPT_ORGCHART_GROUP_OFFICER_GET ()
--		프렌지 변환 : PTORGUSR20L10 -> ORG_DEPT_ORGCHART_GROUP_OFFICER_GET
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.ORG_DEPT_ORGCHART_GROUP_OFFICER_GET 
( 
	IN P_COMPANYCODE CHAR(10),
    IN P_GROUPCODE VARCHAR(50),
    IN P_LANGCODE VARCHAR(10) 
)
	RESULT SETS 2
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.ORG_DEPT_ORGCHART_GROUP_OFFICER_GET

P1 : BEGIN

	S1 : BEGIN -- 값 설정
		SET P_COMPANYCODE = COALESCE ( P_COMPANYCODE , '1000' ) ;
		SET P_LANGCODE = LOWER ( COALESCE ( P_LANGCODE , 'ko' ) ) ;
	END S1 ;
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION . T1 (
			COMPANYCODE VARCHAR ( 50 )
		,	EMPID		VARCHAR ( 50 )
		,	MAINDEPTCODE VARCHAR ( 50 )
	) WITH REPLACE ;
		
	INSERT INTO SESSION . T1 (
			COMPANYCODE
		,	EMPID
		,	MAINDEPTCODE
	)
	WITH CTE ( COMPANYCODE , EMPID ) AS (	
		SELECT COMPANYCODE
			,	USRID AS EMPID
		FROM ORG_GROUPUSR
		WHERE GRPID = P_GROUPCODE
		AND USRTYPE = '1'
		UNION ALL
		SELECT COMPANYCODE
			,	USRID AS EMPID			
		FROM ORG_GROUPUSR AS G
		WHERE G . GRPID = P_GROUPCODE
		AND G . USRTYPE = '2'
	)	SELECT C . COMPANYCODE
			,	UPPER ( C . EMPID )
			,	U . MAINDEPTCODE
		FROM CTE AS C INNER JOIN ORG_USER AS U ON C . COMPANYCODE = U . COMPANYCODE AND UPPER ( C . EMPID ) = UPPER ( U . EMPID ) ;

	
	S2 : BEGIN -- 실행부
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			--그룹
			SELECT	G . GRPID AS GROUPCODE
				,	GL . GRPNAME		AS GROUPNAME
				,	''				AS GROUPMAIL
			FROM ORG_GROUP AS G LEFT JOIN ORG_GROUPLANG AS GL ON G . GRPID = GL . GRPID
			WHERE	G . GRPID		= P_GROUPCODE
			AND		GL . LANGCODE	= P_LANGCODE
			AND		G . USEYN		= 'Y' ;
		OPEN REFCURSOR ;
	END S2 ;
	
	S3 : BEGIN -- 실행부
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT	LOWER ( M . LOGINID )				AS EMPID
				,	LOWER ( M . EMPID )					AS REMPID
				,	COALESCE ( M . EXTENSIONNUMBER , '' )	AS EXTENSIONNUMBER
				,	COALESCE ( M . CELLPHONE , '' )		AS CELLPHONE
				,	COALESCE ( M . LOCATIONCODE , '' )		AS LOCATIONCODE
				,	COALESCE ( D . TEAMCHIEFYN , 'N' )	AS TEAMCHIEFYN
				,	COALESCE ( UL . USERLNAME , '' )	|| COALESCE ( UL . USERFNAME , '' )	AS USERNAME
				,	COALESCE ( M . DISPLAYNAME , '' )		AS DISPLAYNAME
				,	COALESCE ( M . EMAIL , '' )			AS EMAIL
				,	COALESCE ( G . MAINDEPTCODE , '' )		AS DEPTCODE				
				,	COALESCE ( DL . DEPTNAME , '' )		AS DEPTNAME
				, COALESCE ( CL . COMPANYCODE , '' )	AS COMPANYCODE
				, COALESCE ( CL . COMPANY , '' )		AS COMPANYNAME
				, COALESCE ( M . RANKCODE , '' )		AS RANKCODE
				, COALESCE ( R . RANKNAME , '' )		AS RANKNAME
				, COALESCE ( D . DUTYCODE , '' )		AS DUTYCODE
				, COALESCE ( D . DUTYNAME , '' )		AS DUTYNAME
				,	COALESCE ( M . FAXNUMBER , '' )		AS FAXNUMBER
				, COALESCE ( M . DATEOFBIRTH , '' )	AS DATEOFBIRTH
				, COALESCE ( DP . KOSTL , '' )			AS KOSTL
				, COALESCE ( D . SORTNO , 9999 )		AS DSORTNO
				,	COALESCE ( R . SORTNO , 9999 )		AS RSORTNO
			FROM	SESSION . T1 AS G INNER JOIN ORG_USER AS M ON G . EMPID = M . EMPID AND G . COMPANYCODE = M . COMPANYCODE
									LEFT OUTER JOIN ORG_USERLANG AS UL ON	M . EMPID = UL . EMPID AND	UL . LANGCODE = P_LANGCODE AND	M . COMPANYCODE = UL . COMPANYCODE
									LEFT OUTER JOIN ORG_DEPTLANG AS DL ON	G . MAINDEPTCODE = DL . DEPTCODE AND DL . LANGCODE = P_LANGCODE AND M . COMPANYCODE = DL . COMPANYCODE
									LEFT OUTER JOIN ORG_COMPANYLANG AS CL ON	M . COMPANYCODE = CL . COMPANYCODE AND	CL . LANGUAGECODE = P_LANGCODE
									LEFT OUTER JOIN ORG_RANK AS R ON	M . RANKCODE = R . RANKCODE AND	R . LANGCODE = P_LANGCODE AND	M . COMPANYCODE = R . COMPANYCODE
									LEFT OUTER JOIN ORG_DUTY AS D ON	M . DUTYCODE = D . DUTYCODE AND	D . LANGCODE = P_LANGCODE AND	M . COMPANYCODE = D . COMPANYCODE		
									LEFT OUTER JOIN ORG_DEPT AS DP ON	G . MAINDEPTCODE = DP . DEPTCODE AND G . COMPANYCODE = DP . COMPANYCODE									
			WHERE
					M . DISPLAYYN = 'Y'
			AND		G . COMPANYCODE = P_COMPANYCODE -- 회사로 그룹멤버필터링
			ORDER BY D . SORTNO ASC , D . TEAMCHIEFYN DESC , R . SORTNO ASC , M . EMPID ASC , USERNAME ASC ;
		OPEN REFCURSOR ;
	END S3 ;

END P1