--DROP PROCEDURE TYJINFWLIB.ORG_DEPTCOMBO_LIST;
-------------------------------------------------------------------------------------------
-- 프로시저명 : TYJINFWLIB.ORG_DEPTCOMBO_LIST
-- 작성자     : 박제영
-- 작성일     : 2015-09-14
-- 설명       : 부서 콤보박스 목록
-- 예문       : CALL TYJINFWLIB.ORG_DEPTCOMBO_LIST ('1000','KO')
--		DB2 변환 : 이전프로시져명 UP_DEPT_SELECT_CBO
--		프렌지 변환 : PTORGUSR11L1 -> ORG_DEPTCOMBO_LIST
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.ORG_DEPTCOMBO_LIST 
(	
	IN P_COMPANYCODE CHAR(10)
,	IN P_LANGCODE VARCHAR(10)
)
	LANGUAGE SQL
	RESULT SETS 1

P1: BEGIN
	S1 : BEGIN -- 값 설정
		SET P_LANGCODE = LOWER(COALESCE(P_LANGCODE,'ko'));		
END S1 ;

S2 : BEGIN -- 실행부
DECLARE REFCURSOR CURSOR WITH RETURN FOR
	SELECT  COMPANY
		,	DEPTCODE AS CODE
		,	DEPTNAME AS TXT
	FROM TYJINFWLIB.ORG_COMPANYLANG AS A RIGHT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS B ON B.COMPANYCODE = A.COMPANYCODE
	WHERE
		A.COMPANYCODE LIKE CASE WHEN P_COMPANYCODE = '' THEN '%' ELSE P_COMPANYCODE || '%' END
		AND	A.LANGUAGECODE  = P_LANGCODE
		AND B.LANGCODE 		= P_LANGCODE;		
OPEN REFCURSOR;
END S2;

END P1