-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORG_DEPT_LIST_COM_SEARCHVIEW
-- 작성자     : 장윤호
-- 작성일     : 2017-04-14
-- 설명       : 부서 서치뷰(총괄부서 포함)
-- 예문       : CALL TYJINFWLIB.ORG_DEPT_LIST_COM_SEARCHVIEW (1,20,'','ko','KAMTEX')
-- DB2 변환   :
--
-------------------------------------------------------------------------------------------
----DROP PROCEDURE TYJINFWLIB.ORG_DEPT_LIST_COM_SEARCHVIEW 
CREATE PROCEDURE TYJINFWLIB.ORG_DEPT_LIST_COM_SEARCHVIEW 
(
		P_CURRENTPAGEINDEX	INTEGER  
	,	P_PAGESIZE			INTEGER
	,	P_SEARCHCONDITION	VARCHAR(4000)
	,	P_LANGCODE			VARCHAR(2)
	,	P_COMPANYCODE		VARCHAR(50)
)
LANGUAGE SQL
RESULT SETS 2
    
P1: BEGIN
    DECLARE P_STNUM INTEGER ;
    DECLARE P_FNNUM INTEGER ;
    
    DECLARE GLOBAL TEMPORARY TABLE SESSION.T (
			DEPTCODE	VARCHAR (50)                --부서코드
		,	DEPTNAME	VARGRAPHIC(100) CCSID 1200  -- 부서명
		,	COMPANYCODE	VARCHAR(50)
    ) WITH REPLACE ;
    
	S1 : BEGIN -- 값 설정
		SET P_LANGCODE = LOWER(COALESCE(P_LANGCODE, 'ko'));
        SET P_STNUM = (P_PAGESIZE * (P_CURRENTPAGEINDEX - 1)) + 1 ;
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ;
	END S1 ;
    
    INSERT INTO SESSION.T
	SELECT 
			DEPTCODE
		,	DEPTNAME
		,	COMPANYCODE
	FROM
			(	SELECT
						DEPTCODE
					,	DEPTNAME
					,	COMPANYCODE
				FROM
						(	SELECT 
									A.DEPTCODE 
								,	COALESCE(B.DEPTNAME, A.DISPLAYNAME) AS DEPTNAME
								,	A.COMPANYCODE
							FROM
									TYJINFWLIB.ORG_DEPT AS A
									LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS B
										ON	A.COMPANYCODE 	= B.COMPANYCODE
										AND A.DEPTCODE 		= B.DEPTCODE
										AND B.LANGCODE 		= P_LANGCODE
						 ) AS A
				WHERE
						(
							COMPANYCODE 	= P_COMPANYCODE
						OR	COMPANYCODE		IN (SELECT COMPANYCODE FROM ORG_COMPANY WHERE COMMON = '1')
						)
				AND 	(
							A.DEPTCODE 	LIKE P_SEARCHCONDITION || '%'
						OR 	A.DEPTNAME 	LIKE P_SEARCHCONDITION || '%'
						)
			) AS A;
    
	MAIN : BEGIN
        DECLARE REFCURSOR CURSOR WITH RETURN FOR
			WITH MST AS (
				SELECT
						DEPTCODE
					,	DEPTNAME
					,	COMPANYCODE
					,	ROW_NUMBER() OVER (ORDER BY DEPTCODE) AS ROWNO
                 FROM
						SESSION.T
			)
			SELECT
					DEPTCODE
				,	DEPTNAME
				,	COMPANYCODE
			FROM
					MST
			WHERE
					ROWNO	BETWEEN P_STNUM AND P_FNNUM
			;
        OPEN REFCURSOR;
	END MAIN;
    
	TOTAL : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT
					COUNT(*) AS TOTALCOUNT
			FROM
					SESSION.T
			;
		OPEN REFCURSOR;
	END TOTAL;
END P1