-------------------------------------------------------------------------------------------
--
-- 프로시저명  : TYJINFWLIB.ORG_DEPT3_LIST
-- 작성자     : 김희섭
-- 작성일     : 2015-09-16
-- 설명       : 부서 서치뷰2
-- 예문       : CALL TYJINFWLIB.ORG_DEPT3_LIST (1,20,'','ko','KAMTEX')
-- DB2 변환   : 이전프로시져명 UP_DEPT_SEARCHVIEW3
-- 수정 : 이영헌(20151104) : 쿼리정리및 TMPTABLE적용
--		프렌지 변환 : PTORGUSR20L3 -> ORG_DEPT3_LIST 
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.ORG_DEPT3_LIST 
(
		P_CURRENTPAGEINDEX	INTEGER  
	,	P_PAGESIZE			INTEGER
	,	P_SEARCHCONDITION	VARCHAR(4000)
	,	P_LANGCODE			VARCHAR(2)
	,	P_COMPANYCODE		VARCHAR(50)
)
LANGUAGE SQL
RESULT SETS 2
    
P1: BEGIN
    DECLARE P_STNUM INTEGER ;
    DECLARE P_FNNUM INTEGER ;
    
    DECLARE GLOBAL TEMPORARY TABLE SESSION.T (
			DEPTCODE	VARCHAR (50)                --부서코드
		,	DEPTNAME	VARGRAPHIC(100) CCSID 1200  -- 부서명
		,	COMPANYCODE	VARCHAR(50)
    ) WITH REPLACE ;
    
	S1 : BEGIN -- 값 설정
		SET P_LANGCODE = LOWER(COALESCE(P_LANGCODE, 'ko'));
        SET P_STNUM = (P_PAGESIZE * (P_CURRENTPAGEINDEX - 1)) + 1 ;
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ;
	END S1 ;
    
    INSERT INTO SESSION.T
    SELECT 
			DEPTCODE
		,	DEPTNAME
		,	COMPANYCODE
	FROM(
		SELECT
				DEPTCODE
			,	DEPTNAME
			,	COMPANYCODE
		FROM (
			SELECT 
					A.DEPTCODE 
				,	COALESCE(B.DEPTNAME, A.DISPLAYNAME) AS DEPTNAME
				,	A.COMPANYCODE
			FROM TYJINFWLIB.ORG_DEPT AS A
			LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS B
			ON	A.COMPANYCODE = B.COMPANYCODE AND A.DEPTCODE = B.DEPTCODE AND B.LANGCODE = P_LANGCODE
         ) AS A
		WHERE COMPANYCODE = P_COMPANYCODE AND (A.DEPTCODE LIKE P_SEARCHCONDITION || '%' OR A.DEPTNAME LIKE P_SEARCHCONDITION || '%')
	) AS A;
    
	MAIN : BEGIN
        DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT
					DEPTCODE
				,	DEPTNAME
				,	COMPANYCODE
			FROM(
				SELECT
						DEPTCODE
					,	DEPTNAME
					,	COMPANYCODE
					,	ROW_NUMBER() OVER (ORDER BY DEPTCODE) AS ROWNO
                 FROM SESSION.T
			) AS A
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM;
        OPEN REFCURSOR;
	END MAIN;
    
	TOTAL : BEGIN
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT COUNT(*) AS TOTALCOUNT FROM SESSION.T;
		OPEN REFCURSOR;
	END TOTAL;
END P1