-------------------------------------------------------------------------------------------
-- 프로시저명 : TYJINFWLIB.ORG_USER_LST
-- 작성자     : 이영헌
-- 작성일     : 2016-12-08
-- 설명       : 협력업체 정보 리스트
-- 예문       : CALL TYJINFWLIB.ORG_USER_LST(1, 20, 'SEOHAN', '', '1', '', 'ko');
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORG_USER_LST
CREATE PROCEDURE TYJINFWLIB.ORG_USER_LST
(
		IN P_CURRENTPAGEINDEX		INTEGER
	,	IN P_PAGESIZE				INTEGER
	,	IN P_COMPANYCODE			CHAR(10)
	,	IN P_DEPTCD					CHAR(10)
	,	IN P_DPARTNER				CHAR(1)
	,	IN P_SEARCHCONDITION		VARGRAPHIC(1000) CCSID 1200
	,	IN P_LANGCD					CHAR(2)
)
RESULT SETS 2
LANGUAGE SQL

P1 : BEGIN

	DECLARE P_STNUM INTEGER;
	DECLARE P_FNNUM INTEGER;

	DECLARE GLOBAL TEMPORARY TABLE SESSION.T (
			KEYINFO			CHAR(30)
		,	COMPANYCODE		CHAR(10)
		,	EMPID			CHAR(20)
		,	LOGINID			CHAR(20)
		,	USERNAME		VARGRAPHIC(80) CCSID 1200
		,	MAINDEPTCODE	CHAR(10)
		,	DEPTNAME		VARGRAPHIC(40) CCSID 1200
		,	RANKCODE		CHAR(3)
		,	RANKNAME		VARGRAPHIC(40) CCSID 1200
		,	DPARTNER		CHAR(1)
	) WITH REPLACE ;

	S1 : BEGIN -- 값 설정
		SET P_LANGCD = LOWER(COALESCE(P_LANGCD, 'ko'));
		SET P_CURRENTPAGEINDEX = COALESCE(P_CURRENTPAGEINDEX, 1);
		SET P_PAGESIZE = COALESCE(P_PAGESIZE, 10);
		SET P_STNUM = (P_PAGESIZE * (P_CURRENTPAGEINDEX - 1)) + 1;
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX;
	END S1 ;

	INSERT INTO SESSION.T (
			KEYINFO
		,	COMPANYCODE	
		,	EMPID
		,	LOGINID
		,	USERNAME
		,	MAINDEPTCODE
		,	DEPTNAME
		,	RANKCODE
		,	RANKNAME
		,	DPARTNER	
	) 
	SELECT 
			TRIM(USR.COMPANYCODE) || '^' || TRIM(USR.EMPID) AS KEYINFO
		,	USR.COMPANYCODE
		,	USR.EMPID
		,	USR.LOGINID
		,	COALESCE(USRL.USERNAME, USR.DISPLAYNAME) AS USERNAME
		,	USR.MAINDEPTCODE
		,	COALESCE(DPTL.DEPTNAME, '') AS DEPTNAME
		,	USR.RANKCODE
		,	COALESCE(RANKINFO.RANKNAME, '') AS RANKNAME
		,	USR.DPARTNER
	FROM TYJINFWLIB.ORG_USER AS USR
	LEFT OUTER JOIN (
		SELECT
				COMPANYCODE
			,	EMPID
			,	LANGCODE
			,	CASE 
					WHEN LANGCODE = 'ko' 
					THEN COALESCE(USERFNAME, '') || COALESCE(USERLNAME, '') 
					ELSE COALESCE(USERLNAME, '') || ' ' || COALESCE(USERFNAME, '')
				END AS USERNAME
		FROM TYJINFWLIB.ORG_USERLANG
	) AS USRL
	ON USR.COMPANYCODE = USRL.COMPANYCODE AND USR.EMPID = USRL.EMPID AND USRL.LANGCODE = P_LANGCD
	LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DPTL
	ON USR.COMPANYCODE = DPTL.COMPANYCODE AND USR.MAINDEPTCODE = DPTL.DEPTCODE AND DPTL.LANGCODE = P_LANGCD
	LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS RANKINFO
	ON USR.COMPANYCODE = RANKINFO.COMPANYCODE AND USR.RANKCODE = RANKINFO.RANKCODE AND RANKINFO.LANGCODE = P_LANGCD
	WHERE 
		(
			TRIM(USR.SITECOMPANY) = CASE WHEN TRIM(COALESCE(P_COMPANYCODE, '')) = '' THEN TRIM(USR.SITECOMPANY) ELSE TRIM(P_COMPANYCODE) END
			OR	
			TRIM(USR.COMPANYCODE) = CASE WHEN TRIM(COALESCE(P_COMPANYCODE, '')) = '' THEN TRIM(USR.COMPANYCODE) ELSE TRIM(P_COMPANYCODE) END
		)
	AND COALESCE(USR.DPARTNER,'0') = CASE WHEN COALESCE(P_DPARTNER,'') = '' THEN COALESCE(USR.DPARTNER,'0') ELSE COALESCE(P_DPARTNER,'') END
	AND COALESCE(USR.MAINDEPTCODE,'') = CASE WHEN COALESCE(P_DEPTCD,'') = '' THEN COALESCE(USR.MAINDEPTCODE,'') ELSE P_DEPTCD END
    AND COALESCE(USR.RANKCODE, '')			NOT IN ('01','02', '03')
	AND	(USR.EMPID LIKE '%' || P_SEARCHCONDITION || '%'
    OR USR.LOGINID LIKE '%' || P_SEARCHCONDITION || '%'
	OR COALESCE(USRL.USERNAME, USR.DISPLAYNAME) LIKE '%' || P_SEARCHCONDITION || '%')
	;

	S2 : BEGIN -- 실행부
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT 
					B.*
			FROM (
				SELECT 
						ROW_NUMBER() OVER(ORDER BY A.USERNAME ASC) AS ROWNO
					,	A.*
				FROM SESSION.T AS A
			) AS B
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM;
		OPEN REFCURSOR ;
	END S2;
	
	S3 : BEGIN -- 실행부
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT COUNT(*) AS TOTALCOUNT FROM SESSION.T AS A;
		OPEN REFCURSOR ;
	END S3;

END P1;