-------------------------------------------------------------------------------------------
-- 프로시저명 : ORG_DEPT_ORGCHART_OFFICER_GET_CARD
-- 작성자     : 장윤호
-- 작성일     : 2017-09-01
-- 설명       : 조직도임직원조회2
-- 예문       : CALL TYJINFWLIB.ORG_DEPT_ORGCHART_OFFICER_GET_CARD('2040448', 'PLANNING', 'ko', '4060125')
-- DB2 변환   :
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORG_DEPT_ORGCHART_OFFICER_GET_CARD
CREATE PROCEDURE TYJINFWLIB.ORG_DEPT_ORGCHART_OFFICER_GET_CARD
(
		P_EMPID				VARCHAR(20)
	,	P_COMPANYCODE		VARCHAR(10)
	,	P_LANGCODE			VARCHAR(10)
	,	P_REGID				VARCHAR(20)
)
	RESULT SETS 2
	LANGUAGE SQL

P1 : BEGIN
	S1 : BEGIN -- 값 설정
		SET P_COMPANYCODE	= COALESCE(P_COMPANYCODE, '');
		SET P_LANGCODE		= LOWER(COALESCE(P_LANGCODE, 'ko'));
	END S1 ;
	
    DECLARE GLOBAL TEMPORARY TABLE SESSION.T (
			EMPID					VARCHAR(20)
		,	LOGINID					VARCHAR(20)
		,	EMAIL					VARCHAR(40)
		,	MAINDEPTCODE			VARCHAR(10)
		,	MAINDEPTNAME			VARGRAPHIC(1000)	CCSID 1200
		,	CREATEDDT				VARCHAR(10)
		,	DISPLAYNAME				VARGRAPHIC(1000)	CCSID 1200
		,	USERNAME				VARGRAPHIC(1000)	CCSID 1200
		,	DUTYCODE				VARCHAR(3)
		,	DUTYNAME				VARGRAPHIC(1000)	CCSID 1200
		,	RANKNAME				VARGRAPHIC(1000)	CCSID 1200
		,	CELLPHONE				VARCHAR(100)
		,	FAXNUMBER				VARCHAR(20)
		,	EXTENSIONNUMBER			VARCHAR(100)
		,	LOCATIONCODE			VARCHAR(4)
		,	COMPANYNAME				VARGRAPHIC(1000)	CCSID 1200
		,	DATEOFBIRTH				VARCHAR(10)
		,	TEAMCHIEFYN				VARCHAR(1)
		,	PHONE1					VARCHAR(30)
		,	PHONE2					VARCHAR(30)
		,	JOBDESC					VARGRAPHIC(1000)	CCSID 1200
		,	COMPANYCODE				VARCHAR(10)
    ) WITH REPLACE ;
	
	INSERT INTO SESSION.T
	SELECT
			U.EMPID
		,	U.LOGINID
		,	U.EMAIL
		,	CASE
				WHEN U.DUTYCODE = '15' OR U.DUTYCODE = '17' OR U.DUTYCODE = '98' OR U.DUTYCODE = '99'
				THEN D.DEPTCODE
				ELSE COALESCE(D.DEPTCODE, P_COMPANYCODE)
			END AS MAINDEPTCODE
		,	DP.DEPTNAME AS MAINDEPTNAME
		,	U.CREATEDDT
		,	U.DISPLAYNAME
		,	UL.USERLNAME || ( CASE WHEN P_LANGCODE NOT IN ( 'ko' , 'en' , 'cn' , 'ru' ) THEN ' ' ELSE '' END ) || UL.USERFNAME AS USERNAME
		,	U.DUTYCODE
		,	DU.DUTYNAME
		,	RA.RANKNAME
		,	U.CELLPHONE
		,	U.FAXNUMBER
		,	U.EXTENSIONNUMBER
		,	U.LOCATIONCODE
		,	COM.COMPANY AS COMPANYNAME
		,	U.DATEOFBIRTH
		,	COALESCE(DU.TEAMCHIEFYN, 'N') AS TEAMCHIEFYN
		,	U.PHONE1
		,	U.PHONE2
		,	U.JOBDESC
		,	U.COMPANYCODE
	FROM
			TYJINFWLIB.ORG_USER AS U
			LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL
				ON	U.EMPID				= UL.EMPID
				AND	U.COMPANYCODE		= UL.COMPANYCODE
				AND	UL.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS D
				ON	U.COMPANYCODE		= D.COMPANYCODE
				AND	U.MAINDEPTCODE		= D.DEPTCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DP
				ON	U.MAINDEPTCODE		= DP.DEPTCODE
				AND DP.COMPANYCODE		= P_COMPANYCODE
				AND DP.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS DU
				ON  U.DUTYCODE			= DU.DUTYCODE
				AND DU.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS RA
				ON  U.RANKCODE			= RA.RANKCODE
				AND RA.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS COM
				ON	U.COMPANYCODE		= COM.COMPANYCODE
				AND COM.LANGUAGECODE	= P_LANGCODE 
	WHERE
			(
				LOWER(U.EMPID)		= LOWER(P_EMPID)
			OR	LOWER(U.LOGINID)	= LOWER(P_EMPID)
			)
	AND		U.COMPANYCODE			= CASE
										WHEN P_COMPANYCODE = ''
										THEN U.COMPANYCODE
										ELSE P_COMPANYCODE
									END
	AND		U.DISPLAYYN				= 'Y'


	UNION ALL

	SELECT
			U.EMPID
		,	U.LOGINID
		,	U.EMAIL
		,	CASE
				WHEN A.DUTYCODE = '15' OR A.DUTYCODE = '17' OR A.DUTYCODE = '98' OR A.DUTYCODE = '99'
				THEN D.DEPTCODE
				ELSE COALESCE(D.DEPTCODE, P_COMPANYCODE)
			END AS MAINDEPTCODE
		,	DP.DEPTNAME AS MAINDEPTNAME
		,	U.CREATEDDT
		,	U.DISPLAYNAME
		,	UL.USERLNAME || ( CASE WHEN P_LANGCODE NOT IN ( 'ko' , 'en' , 'cn' , 'ru' ) THEN ' ' ELSE '' END ) || UL.USERFNAME AS USERNAME
		,	A.DUTYCODE
		,	DU.DUTYNAME
		,	RA.RANKNAME
		,	U.CELLPHONE
		,	U.FAXNUMBER
		,	U.EXTENSIONNUMBER
		,	U.LOCATIONCODE
		,	COM.COMPANY AS COMPANYNAME
		,	U.DATEOFBIRTH
		,	COALESCE(DU.TEAMCHIEFYN, 'N') AS TEAMCHIEFYN
		,	U.PHONE1
		,	U.PHONE2
		,	U.JOBDESC
		,	U.COMPANYCODE
	FROM
			TYJINFWLIB.ORG_ADDITIONALJOB AS A
			LEFT JOIN TYJINFWLIB.ORG_USER AS U
				ON A.EMPID 				= U.EMPID
			LEFT OUTER JOIN TYJINFWLIB.ORG_USERLANG AS UL
				ON	U.EMPID				= UL.EMPID
				AND	U.COMPANYCODE 		= UL.COMPANYCODE
				AND	UL.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS D
				ON	A.COMPANYCODE		= D.COMPANYCODE
				AND	A.DEPTCODE			= D.DEPTCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DP
				ON	A.DEPTCODE			= DP.DEPTCODE
				AND DP.COMPANYCODE		= P_COMPANYCODE
				AND DP.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_DUTY AS DU
				ON  A.DUTYCODE			= DU.DUTYCODE
				AND DU.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_RANK AS RA
				ON  A.RANKCODE			= RA.RANKCODE
				AND RA.LANGCODE			= P_LANGCODE
			LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS COM
				ON	A.COMPANYCODE		= COM.COMPANYCODE
				AND COM.LANGUAGECODE	= P_LANGCODE
	WHERE
			(
				LOWER(A.EMPID)		= LOWER(P_EMPID)
			OR	LOWER(A.LOGINID)	= LOWER(P_EMPID)
			)
	AND		A.COMPANYCODE			= CASE
										WHEN P_COMPANYCODE = ''
										THEN A.COMPANYCODE
										ELSE P_COMPANYCODE
									END
	AND		U.DISPLAYYN				= 'Y'
	;

	S2 : BEGIN -- 실행부
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		SELECT
				*
		FROM
				SESSION.T AS M
		FETCH FIRST 1 ROW ONLY;
		OPEN REFCURSOR ;
	END S2 ;

	S3 : BEGIN
		DECLARE REFCURSOR1 CURSOR WITH RETURN FOR
		WITH MST (COMPANYCODE, DEPTCODE) AS (
			SELECT
					COMPANYCODE
				,	DEPTCODE
			FROM
					(
						SELECT
								COMPANYCODE
							,	DEPTCODE
						FROM
								TYJINFWLIB.ORG_DEPT
					
						UNION ALL
					
						SELECT
								P_COMPANYCODE AS COMPANYCODE
							,	P_COMPANYCODE AS DEPTCODE
						FROM
								SYSIBM.SYSDUMMY1
					) AS D
			WHERE
					COMPANYCODE 		= P_COMPANYCODE
			AND		DEPTCODE		IN (	SELECT
													CASE
														WHEN U.DUTYCODE = '15' OR U.DUTYCODE = '17' OR U.DUTYCODE = '98' OR U.DUTYCODE = '99'			-- 15(파트장), 17(사원), 98(직위없음), 99(기타)
														THEN D.DEPTCODE
														ELSE COALESCE(D.DEPTCODE, P_COMPANYCODE)
													END AS DEPTCODE
											FROM
													TYJINFWLIB.ORG_USER AS U
													LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS D
														ON	U.COMPANYCODE		= D.COMPANYCODE
														AND	U.MAINDEPTCODE		= D.DEPTCODE
											WHERE
													U.COMPANYCODE		= P_COMPANYCODE
											AND		U.EMPID 			= P_REGID
											AND		U.DUTYCODE			NOT IN ('15', '17', '98', '99')
	
											UNION ALL
	
											SELECT
													CASE
														WHEN AJ.DUTYCODE = '15' OR AJ.DUTYCODE = '17' OR AJ.DUTYCODE = '98' OR AJ.DUTYCODE = '99'			-- 15(파트장), 17(사원), 98(직위없음), 99(기타)
														THEN D.DEPTCODE
														ELSE COALESCE(D.DEPTCODE, P_COMPANYCODE)
													END AS DEPTCODE
											FROM
													TYJINFWLIB.ORG_ADDITIONALJOB AS AJ
													LEFT OUTER JOIN TYJINFWLIB.ORG_DEPT AS D
														ON	AJ.COMPANYCODE		= D.COMPANYCODE
														AND	AJ.DEPTCODE			= D.DEPTCODE
											WHERE
													AJ.COMPANYCODE		= P_COMPANYCODE
											AND		AJ.EMPID 			= P_REGID
											AND		AJ.DUTYCODE			NOT IN ('15', '17', '98', '99')
										)
	
			UNION ALL
	
			SELECT
					D.COMPANYCODE
				,	D.DEPTCODE
			FROM
					TYJINFWLIB.ORG_DEPT AS D
					INNER JOIN MST AS M
						ON	D.COMPANYCODE 		= M.COMPANYCODE
						AND	D.PARENTDEPTCODE	= M.DEPTCODE
			FETCH FIRST 200 ROWS ONLY
		)
		SELECT
				*
		FROM
				SESSION.T
		WHERE
				MAINDEPTCODE	IN (	SELECT
												DEPTCODE
										FROM
												MST
										FETCH FIRST 200 ROWS ONLY
									)
		;
		OPEN REFCURSOR1;
	END S3;
END P1