-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORG_USER_GET_USERINFO
-- 작성자     : 장윤호
-- 작성일     : 2017-02-23
-- 설명       : 로그인계정으로 사용자정보조회
-- 예문       : CALL TYJINFWLIB.ORG_USER_GET_USERINFO('SEOHAN', 'grren', 'ko')
-- DB2 변환   : 이전프로시져명 up_List_UserInfo, up_List_UserInfo2 통합 (P_COMPANYCODE를 공백으로 던져도됨)
--
-------------------------------------------------------------------------------------------
--DROP PROCEDURE TYJINFWLIB.ORG_USER_GET_USERINFO
CREATE PROCEDURE TYJINFWLIB.ORG_USER_GET_USERINFO
(
		P_COMPANYCODE			VARCHAR(10)			-- 법인코드
	,	P_LOGINID				VARCHAR(20)			-- 로그인 아이디
	,	P_LANGCD				VARCHAR(10)
)
	LANGUAGE SQL
	RESULT SETS 3
	
M1 : BEGIN
	-- 법인코드 파라메타에 값이 없을시 셋팅
	IF COALESCE(P_COMPANYCODE, '') = '' THEN
		S1 : BEGIN
			SELECT
					COMPANYCODE INTO P_COMPANYCODE
			FROM
					ORG_USER
			WHERE
					LOGINID		= P_LOGINID
			;
		END S1;
	END IF;

	IF NOT EXISTS (SELECT EMPID FROM ORG_USERLANG WHERE LANGCODE = P_LANGCD AND COMPANYCODE = P_COMPANYCODE) THEN
		S2 : BEGIN
			SET P_LANGCD = 'ko';
		END S2;
	END IF;
	
	S3 : BEGIN
		DECLARE REFCURSOR1 CURSOR WITH RETURN FOR
		SELECT 
				LOWER(M.EMPID) AS EMPID
			,	LOWER(M.LOGINID) AS LOGINID
			,	TYJINFWLIB.UF_USERINFO_USERNAME(M.COMPANYCODE, M.EMPID, P_LANGCD) AS USERNAME
			,	M.MAINDEPTCODE AS DEPTCODE
			,	TYJINFWLIB.UF_DEPTNAME(M.COMPANYCODE, P_LANGCD, M.MAINDEPTCODE) AS DEPTNAME
			,	COALESCE(R.RANKCODE,'') AS RANKCODE
			,	COALESCE(R.RANKNAME,'') AS RANKNAME
			,	COALESCE(DT.DUTYCODE,'') AS DUTYCODE
			,	COALESCE(DT.DUTYNAME,'') AS DUTYNAME
			,	COALESCE(M.EMAIL,'') AS EMAIL
			,	COALESCE(M.JOBCODE, '') AS JOBCODE
			,	'' AS JOBNAME
			,	M.EXTENSIONNUMBER AS EXTENSIONNUMBER
			,	M.CELLPHONE AS CELLPHONE
			,	M.FAXNUMBER AS FAXNUMBER
			,	M.COMPANYCODE	AS COMPANYCODE
			,	CG.COMPANY		AS COMPANYNAME
			,	'' AS SIGNID
		FROM
				ORG_USER AS M	
				LEFT OUTER JOIN ORG_RANK AS R
					ON	M.RANKCODE			= R.RANKCODE
					AND	R.LANGCODE			= P_LANGCD
				LEFT OUTER JOIN ORG_DUTY AS DT 
					ON	M.DUTYCODE			= DT.DUTYCODE
					AND	DT.LANGCODE			= P_LANGCD
				LEFT OUTER JOIN ORG_COMPANYLANG AS CG
					ON	M.COMPANYCODE		= CG.COMPANYCODE
					AND CG.LANGUAGECODE		= P_LANGCD
		WHERE 
				M.COMPANYCODE	= P_COMPANYCODE
		AND		(
					M.LOGINID	= P_LOGINID
				OR	M.EMPID		= P_LOGINID
				)
		;
		OPEN REFCURSOR1;
	END S3;

	S4 : BEGIN
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR
		SELECT 
				(	SELECT
							COUNT(EMPID)
					FROM
							ORG_USER
					WHERE
							MAINDEPTCODE	= A.DEPTCODE
					AND		COMPANYCODE		= P_COMPANYCODE
					AND		(
								EMPID		= P_LOGINID
							OR	LOGINID		= P_LOGINID
							)
				) AS MainDeptYN
		,		A.DEPTCODE AS DeptCode
		,		TYJINFWLIB.UF_DEPTNAME(P_COMPANYCODE, P_LANGCD, A.DeptCode) AS DeptName
		,		(	SELECT
							PARENTDEPTCODE
					FROM
							ORG_DEPT
					WHERE
							DEPTCODE		= A.DEPTCODE
					AND		COMPANYCODE		= P_COMPANYCODE
				) AS ParentDeptCode
		,		(	SELECT
							DEPTNAME
					FROM
							ORG_DEPTLANG
					WHERE
							DEPTCODE	= (	SELECT
													PARENTDEPTCODE
											FROM
													ORG_DEPT
											WHERE
													DEPTCODE		= A.DeptCode
											AND		COMPANYCODE		= P_COMPANYCODE
										)
					AND		LANGCODE	= P_LANGCD
					AND		COMPANYCODE = P_COMPANYCODE
				) AS ParentDeptName
		,	CASE
				WHEN COALESCE((	SELECT	U.EMPID 
								FROM	ORG_USER AS U
								WHERE	U.COMPANYCODE	= P_COMPANYCODE
								AND		U.MAINDEPTCODE	= A.DEPTCODE
								AND		U.TEAMCHIEFYN	= 'Y'), '') = ''
				THEN (	SELECT	DISTINCT U.EMPID
						FROM	ORG_USER AS U
								INNER JOIN ORG_ADDITIONALJOB AS B
									ON	U.COMPANYCODE	= B.COMPANYCODE
									AND U.EMPID			= B.EMPID
						WHERE	B.DEPTCODE				= A.DEPTCODE
						AND		B.ADDCOMPANYCODE		= P_COMPANYCODE)
				ELSE (	SELECT	U.EMPID
						FROM	ORG_USER AS U
						WHERE	U.COMPANYCODE	= P_COMPANYCODE
						AND		U.MAINDEPTCODE	= A.DEPTCODE
						AND		U.TEAMCHIEFYN = 'Y')
				END AS TeamChifID
		,	CASE
				WHEN COALESCE((	SELECT	TYJINFWLIB.UF_USERINFO_USERNAME(U.COMPANYCODE, U.EMPID, P_LANGCD) AS UserName
								FROM	ORG_USER AS U
								WHERE	U.COMPANYCODE	= P_COMPANYCODE
								AND		U.MAINDEPTCODE	= A.DEPTCODE
								AND		U.TEAMCHIEFYN	= 'Y'), '') = ''
				THEN (	SELECT  DISTINCT TYJINFWLIB.UF_USERINFO_USERNAME(U.COMPANYCODE, U.EMPID, P_LANGCD)
						FROM	ORG_USER AS U
								INNER JOIN ORG_ADDITIONALJOB AS B
									ON	U.COMPANYCODE	= B.COMPANYCODE
									AND U.EMPID			= B.EMPID
						WHERE	B.DEPTCODE				= A.DEPTCODE
						AND		B.ADDCOMPANYCODE		= P_COMPANYCODE)
				ELSE (	SELECT	TYJINFWLIB.UF_USERINFO_USERNAME(U.COMPANYCODE, U.EMPID, P_LANGCD) AS UserName
						FROM	ORG_USER AS U
						WHERE	U.COMPANYCODE	= P_COMPANYCODE
						AND		U.MAINDEPTCODE	= A.DEPTCODE
						AND		U.TEAMCHIEFYN	= 'Y')
				END AS TeamChifName
		FROM
				ORG_USER AS M	
				INNER JOIN ORG_ADDITIONALJOB AS A
					ON	M.LOGINID		= A.LOGINID
					AND M.COMPANYCODE	= A.COMPANYCODE
		WHERE 
			M.COMPANYCODE	= P_COMPANYCODE
		AND (
				M.LOGINID	= P_LOGINID
			OR	M.EMPID		= P_LOGINID
			)
		;
		OPEN REFCURSOR2;
	END S4;
END M1;