
----DROP PROCEDURE TYJINFWLIB.ORG_USER_GET_LOGINID;
-------------------------------------------------------------------------------------------
--
-- 프로시저명 : ORG_USER_GET_LOGINID 
-- 작성자     : 문광복
-- 작성일     : 2014-04-03
-- 설명       : 로그인아이디로 페이지를 로그인한다.
-- 예문       : CALL TYJINFWLIB.ORG_USER_GET_LOGINID  ('B2020202','ko')
--		DB2 변환 : 이전프로시져명 UP_USERINFO_LOGIN
--		프렌지 변환 : PTORGUSR70S1 -> ORG_USER_GET_LOGINID  
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.ORG_USER_GET_LOGINID  
(
	P_LOGINID CHAR(20),
	P_LANGCODE CHAR(2)
)
	RESULT SETS 1
	LANGUAGE SQL
	SET OPTION
	ALWCPYDTA = *OPTIMIZE
M1: BEGIN 
	
	DECLARE P_TOTALCNT INTEGER;
	
	S1 : BEGIN
		--SET P_TOTALCNT = UF_USERINFO_MAX_USERLANG(P_LOGINID, P_LANGCODE);

		SELECT COUNT(TU.EMPID) INTO P_TOTALCNT
		FROM
			TYJINFWLIB.ORG_USER TU
				INNER JOIN TYJINFWLIB.ORG_USERLANG TL
					ON TL.EMPID = TU.EMPID AND TL.COMPANYCODE = TU.COMPANYCODE
		WHERE
			(TU.LOGINID = P_LOGINID) OR (TU.EMPID = P_LOGINID)
			AND LANGCODE = P_LANGCODE;
		
		IF P_TOTALCNT < 1 THEN
			SET P_LANGCODE = 'ko';
		END IF;
	END S1;
	
	P1: BEGIN
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
			SELECT
					CASE WHEN COALESCE(DP.DPARTNER, '') = '1' THEN U.LOGINID ELSE U.LOGINID END AS LOGINID		-- ELSE 쪽 LOGINID에 LOWER 제거 문제시 원복 2017-08-30 장윤호
				,	CASE WHEN COALESCE(DP.DPARTNER, '') = '1' THEN U.EMPID ELSE U.EMPID END AS EMPID
				,	COALESCE(U.EMAIL, '') AS EMAIL
				,	(UL.USERLNAME || UL.USERFNAME) AS USERNAME
				,	COALESCE(U.CULTURE, UL.LANGCODE)		AS USERLANG
				,	COALESCE(U.MAINDEPTCODE, '') AS DEPTCODE
				,	RTRIM(COALESCE(DEPT.DEPTNAME, '')) AS DEPTNAME
				,	COALESCE(U.DUTYCODE, '') AS DUTYCODE
				,	COALESCE(D.DUTYNAME, '') AS DUTYNAME
				,	COALESCE(U.RANKCODE, '') AS RANKCODE
				,	COALESCE(RK.RANKNAME, '') AS RANKNAME
				,	COALESCE(U.TEAMCHIEFYN, 'N') AS ISCHIEF
				,	COALESCE(U.CELLPHONE, '') AS CELLPHONE
				,	COALESCE(U.EXTENSIONNUMBER, '') AS EXTENSIONNUMBER
				,	COALESCE(U.EMAIL, '') || '?' || UL.USERLNAME || UL.USERFNAME AS EMAILDISP
				,	COALESCE(U.COMPANYCODE, '')	AS COMPANYCODE
				,	COALESCE(CG.COMPANY, '') AS COMPANYNAME
				,	COALESCE(U.LOCATIONCODE, '')	AS LOCATIONCODE
				,	COALESCE(L.LOCATIONNAME, '')	AS LOCATIONNAME
				,	COALESCE(LC.LOCATIONGROUP, '')	AS LOCATIONGROUP
				,	COALESCE(U.JOBCODE, '')	AS JOBCODE
				,	U.DPARTNER
				,	COALESCE(U.KOSTL, '')		AS KOSTL
				--,	COALESCE(DP.KOSTL, '')		AS KOSTL
				--,	COALESCE(U.JOBDESC, '') AS JOBDESC
				,	COALESCE(U.SITECOMPANY, '' ) AS SITECOMPANY
				,	COALESCE(PW.PASSWORD, '' ) AS PASSWORD
				,	COALESCE(U.EMPERNAME, '')	AS JOBNAME    --담당자이름
			FROM
				TYJINFWLIB.ORG_USER	U
				INNER JOIN	TYJINFWLIB.ORG_USERLANG	UL
					ON	U.EMPID			= UL.EMPID 
					AND	U.COMPANYCODE	= UL.COMPANYCODE
					AND	UL.LANGCODE		= P_LANGCODE
				LEFT JOIN	TYJINFWLIB.ORG_COMPANYLANG	CG
					ON	U.COMPANYCODE	= CG.COMPANYCODE
					AND	LANGUAGECODE	= P_LANGCODE
				LEFT JOIN	TYJINFWLIB.ORG_LOCATIONLANG		L
					ON	U.LOCATIONCODE	= L.LOCATIONCODE
					AND	L.LANGCODE		= P_LANGCODE	
				LEFT JOIN	TYJINFWLIB.ORG_LOCATION	LC
					ON	U.LOCATIONCODE	= LC.LOCATIONCODE
				LEFT JOIN TYJINFWLIB.ORG_DEPT DP
					ON U.MAINDEPTCODE = DP.DEPTCODE
				LEFT JOIN TYJINFWLIB.ORG_DUTY		D
					ON	U.DUTYCODE		= D.DUTYCODE
					--AND D.COMPANYCODE  = U.COMPANYCODE
					AND	D.LANGCODE		= P_LANGCODE
				LEFT JOIN TYJINFWLIB.ORG_DEPTLANG	DEPT
					ON	DEPT.DEPTCODE	= U.MAINDEPTCODE
					AND	DEPT.LANGCODE	= UL.LANGCODE
					AND DEPT.COMPANYCODE= U.COMPANYCODE
				LEFT JOIN TYJINFWLIB.ORG_RANK	RK
					ON U.RANKCODE		= RK.RANKCODE
					AND RK.LANGCODE		= P_LANGCODE
					--AND RK.COMPANYCODE	= U.COMPANYCODE
				LEFT JOIN TYJINFWLIB.ORG_PASSWORD PW
					ON U.EMPID	= PW.EMPID
			WHERE
					(U.LOGINID		= P_LOGINID OR U.EMPID = P_LOGINID)
            
			AND		U.DISPLAYYN		= 'Y'
			--AND		U.DPARTNER		= '0'
			
			UNION ALL
			
			SELECT
					U.LOGINID AS LOGINID						-- LOGINID에 LOWER 제거 문제시 원복 2017-08-30 장윤호
				,	U.EMPID AS EMPID							-- EMPID에 LOWER 제거 문제시 원복 2017-08-30 장윤호
				,	COALESCE(U.EMAIL, '') AS EMAIL
				,	(UL.USERLNAME || UL.USERFNAME) AS USERNAME
				,	COALESCE(U.CULTURE, UL.LANGCODE)		AS USERLANG
				,	COALESCE(AJ.DEPTCODE, '') AS DEPTCODE
				,	RTRIM(COALESCE(DEPT.DEPTNAME, '')) AS DEPTNAME
				,	COALESCE(U.DUTYCODE, '') AS DUTYCODE
				,	COALESCE(D.DUTYNAME, '') AS DUTYNAME
				,	COALESCE(AJ.RANKCODE, '') AS RANKCODE
				,	COALESCE(RK.RANKNAME, '') AS RANKNAME
				,	COALESCE(AJ.TEAMCHIEFYN, 'N') AS ISCHIEF
				,	COALESCE(U.CELLPHONE, '') AS CELLPHONE
				,	COALESCE(U.EXTENSIONNUMBER, '') AS EXTENSIONNUMBER
				,	COALESCE(U.EMAIL, '') || '?' || UL.USERLNAME || UL.USERFNAME AS EMAILDISP
				,	COALESCE(U.COMPANYCODE, '')	AS COMPANYCODE
				,	COALESCE(CG.COMPANY, '') AS COMPANYNAME
				,	COALESCE(U.LOCATIONCODE, '')	AS LOCATIONCODE
				,	COALESCE(L.LOCATIONNAME, '')	AS LOCATIONNAME
				,	COALESCE(LC.LOCATIONGROUP, '')	AS LOCATIONGROUP
				,	COALESCE(AJ.JOBCODE, '')	AS JOBCODE
				,	U.DPARTNER
				,	COALESCE(U.KOSTL, '')		AS KOSTL
				--,	COALESCE(DP.KOSTL, '')		AS KOSTL
				--,	COALESCE(AJ.JOBDESC, '') AS JOBDESC
				,	COALESCE(U.SITECOMPANY, '' ) AS SITECOMPANY
				,	COALESCE(PW.PASSWORD, '' ) AS PASSWORD
				,	COALESCE(U.EMPERNAME, '')	AS JOBNAME    --담당자이름
			FROM
				TYJINFWLIB.ORG_ADDITIONALJOB	AJ
				INNER JOIN	TYJINFWLIB.ORG_USER	U
					ON	AJ.COMPANYCODE	= U.COMPANYCODE
					AND	AJ.LOGINID		= U.LOGINID
					AND	U.DISPLAYYN		= 'Y'
				INNER JOIN	TYJINFWLIB.ORG_USERLANG	UL
					ON	U.EMPID			= UL.EMPID 
					AND	U.COMPANYCODE	= UL.COMPANYCODE
					AND	UL.LANGCODE		= P_LANGCODE
				LEFT JOIN	TYJINFWLIB.ORG_COMPANYLANG	CG
					ON	U.COMPANYCODE	= CG.COMPANYCODE
					AND	LANGUAGECODE	= P_LANGCODE
				LEFT JOIN	TYJINFWLIB.ORG_LOCATIONLANG		L
					ON	U.LOCATIONCODE	= L.LOCATIONCODE
					AND	L.LANGCODE		= P_LANGCODE	
				LEFT JOIN	TYJINFWLIB.ORG_LOCATION	LC
					ON	U.LOCATIONCODE	= LC.LOCATIONCODE
				LEFT JOIN TYJINFWLIB.ORG_DEPT DP
					ON AJ.DEPTCODE = DP.DEPTCODE
				LEFT JOIN TYJINFWLIB.ORG_DEPTLANG	DEPT
					ON	DEPT.DEPTCODE	= AJ.DEPTCODE
					AND	DEPT.LANGCODE	= UL.LANGCODE
					AND DEPT.COMPANYCODE= AJ.ADDCOMPANYCODE
				LEFT JOIN TYJINFWLIB.ORG_DUTY		D
					ON	U.DUTYCODE		= D.DUTYCODE
					--AND D.COMPANYCODE  = U.COMPANYCODE 
					AND	D.LANGCODE		= P_LANGCODE
				LEFT JOIN TYJINFWLIB.ORG_RANK	RK
					ON U.RANKCODE		= RK.RANKCODE
					AND RK.LANGCODE		= P_LANGCODE
					--AND RK.COMPANYCODE	= U.COMPANYCODE
				LEFT JOIN TYJINFWLIB.ORG_PASSWORD PW
					ON U.EMPID	= PW.EMPID
			WHERE
					(AJ.LOGINID		= P_LOGINID OR AJ.EMPID = P_LOGINID);

		OPEN REFCURSOR;
	
	END P1;
	
END M1