--DROP PROCEDURE TYJINFWLIB.ORG_DEPT_ORGCHART_TREE_GET;
-------------------------------------------------------------------------------------------
-- 프로시저명 : ORG_DEPT_ORGCHART_TREE_GET 
-- 작성자     : 박제영
-- 작성일     : 2015-10-06
-- 설명       : 조직도 부서를 조회한다.
-- 예문       : CALL ORG_DEPT_ORGCHART_TREE_GET  ()
--		프렌지 변환 : PTORGUSR20L7 -> ORG_DEPT_ORGCHART_TREE_GET    
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.ORG_DEPT_ORGCHART_TREE_GET  
( 
	IN P_COMPANYCODE CHAR(10),
    IN P_LANGCODE VARCHAR(10),
    IN P_SEARCHSTRING VARCHAR(100) 
)
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC TYJINFWLIB.ORG_DEPT_ORGCHART_TREE_GET

P1 : BEGIN
	
	DECLARE P_COMPANYLANGCODE VARCHAR ( 10 ) ;
	
	DECLARE GLOBAL TEMPORARY TABLE SESSION.T1 (
				NODE_PATH		VARCHAR ( 50 )
			,	DEPTCODE		VARCHAR ( 50 )
			--,	HASSUBDEPT		VARCHAR ( 50 )
			,	DEPTEMAIL		VARCHAR ( 80 )
			,	COMPANYCODE	VARCHAR ( 50 )
			,	PARENTDEPTCODE	VARCHAR ( 50 )
			,	DEPTORDER		VARCHAR ( 50 )
			--,	LVL				INTEGER		
	) WITH REPLACE ;
		
	S1 : BEGIN -- 값 설정
		SET P_LANGCODE = LOWER ( COALESCE ( P_LANGCODE , 'ko' ) ) ;
		--SET P_COMPANYCODE = COALESCE ( P_COMPANYCODE , '1000' ) ;
		
		-- 파라미터로 넘어온 LANGUAGE CODE의 데이터가 없을때 영어로 셋팅
		IF NOT EXISTS ( SELECT COMPANYCODE FROM TYJINFWLIB.ORG_COMPANYLANG WHERE LANGUAGECODE = P_COMPANYLANGCODE ) THEN
			SET P_COMPANYLANGCODE = 'en' ;
		END IF ;
		
		IF NOT EXISTS ( SELECT DEPTCODE FROM TYJINFWLIB.ORG_DEPTLANG WHERE LANGCODE = P_LANGCODE AND COMPANYCODE = P_COMPANYCODE ) THEN
			SET P_LANGCODE = 'en' ;
		END IF ;		
	END S1 ;
				
		INSERT INTO SESSION.T1 (		
				NODE_PATH
			,	DEPTCODE
			--,	HASSUBDEPT
			,	DEPTEMAIL
			,	COMPANYCODE
			,	PARENTDEPTCODE
			,	DEPTORDER
			--,	LVL
		)
		WITH CTE_RESULT ( NODE_PATH , DEPTCODE , DEPTEMAIL , COMPANYCODE , PARENTDEPTCODE , DEPTORDER ) AS (
			SELECT
					CASE LENGTH ( D.PARENTDEPTCODE ) WHEN 0 THEN '0' ELSE D.PARENTDEPTCODE END AS NODE_PATH
				,	D.DEPTCODE
				--,	CASE WHEN ( SELECT COUNT ( DEPTCODE ) FROM TYJINFWLIB.ORG_DEPT WHERE PARENTDEPTCODE = D.DEPTCODE AND COMPANYCODE = P_COMPANYCODE ) > 0 THEN '1' ELSE '0' END AS HASSUBDEPT
				,	D.DEPTEMAIL
				,	D.COMPANYCODE AS COMPANYCODE
				,	D.PARENTDEPTCODE
				,	D.DEPTORDER
				--,	1	AS LVL			
			FROM TYJINFWLIB.ORG_DEPT AS D
			WHERE 
			D.DISPLAYYN = 'Y'
			AND D.PARENTDEPTCODE = 'Z00000'
			UNION ALL
			SELECT
					CASE A.NODE_PATH WHEN '0' THEN D.PARENTDEPTCODE ELSE A.NODE_PATH || '/' || D.PARENTDEPTCODE END AS NODE_PATH
				,	D.DEPTCODE
				--,	CASE WHEN ( SELECT COUNT ( DEPTCODE ) FROM TYJINFWLIB.ORG_DEPT WHERE PARENTDEPTCODE = D.DEPTCODE AND COMPANYCODE = P_COMPANYCODE ) > 0 THEN '1' ELSE '0' END AS HASSUBDEPT
				,	D.DEPTEMAIL
				,	D.COMPANYCODE AS COMPANYCODE
				,	D.PARENTDEPTCODE
				,	D.DEPTORDER
				--,	A.LVL + 1 AS LVL
			FROM CTE_RESULT AS A INNER JOIN TYJINFWLIB.ORG_DEPT AS D ON A.DEPTCODE = D.PARENTDEPTCODE												
		)
		SELECT
				NODE_PATH
			,	DEPTCODE
			--,	HASSUBDEPT
			,	DEPTEMAIL
			,	COMPANYCODE
			,	PARENTDEPTCODE
			,	DEPTORDER
			--,	LVL
		FROM CTE_RESULT ;					
		
	S2 : BEGIN -- 실행부
		DECLARE REFCURSOR CURSOR WITH RETURN FOR
			SELECT D.DEPTCODE AS IDX
				,	D.PARENTDEPTCODE AS PRTIDX
				,	COALESCE ( DL.DEPTNAME , '' ) AS TEXT
				,	'D'	AS ORGTYPE
			FROM SESSION.T1 AS D LEFT OUTER JOIN TYJINFWLIB.ORG_DEPTLANG AS DL ON DL.DEPTCODE = D.DEPTCODE AND DL.LANGCODE = P_LANGCODE AND DL.COMPANYCODE = D.COMPANYCODE
								LEFT OUTER JOIN TYJINFWLIB.ORG_COMPANYLANG AS CL ON CL.COMPANYCODE = D.COMPANYCODE AND CL.LANGUAGECODE = P_COMPANYLANGCODE
			WHERE COALESCE ( DL.DEPTNAME , '' ) <> ''
			ORDER BY 
				--LVL ASC , 
				DEPTORDER ASC , 
				--HASSUBDEPT , 
				D.DEPTCODE ;


		OPEN REFCURSOR ;
	END S2 ;		
END P1
