



--DROP PROCEDURE TYJINFWLIB.ORG_USER_PASS_MOD;
-------------------------------------------------------------------------------------------
-- 프로시저명 : ORG_USER_PASS_MOD 
-- 작성자     : 
-- 작성일     : 2017-06-28
-- 설명       : 비밀번호 변경
-------------------------------------------------------------------------------------------
CREATE PROCEDURE TYJINFWLIB.ORG_USER_PASS_MOD  
(
    P_COMPANYCODE CHAR(20)
  , P_LOGINID     CHAR(20)
  , P_PASSWORD    CHAR(200)
  , P_NEWPASS     CHAR(200)
)
  RESULT SETS 1
  LANGUAGE SQL
  SET OPTION
  ALWCPYDTA = *OPTIMIZE
M1: BEGIN 
  
    DECLARE P_CHK_FLG VARCHAR(10);

    CK1 : BEGIN

		IF P_COMPANYCODE = 'TY' THEN	

			SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'C' END
			  INTO P_CHK_FLG
			  FROM (
				SELECT PASSWORD FROM TYJINFWLIB.ORG_PASSWORD WHERE COMPANYCODE = P_COMPANYCODE AND EMPID = P_LOGINID AND PASSWORD = P_PASSWORD
			  ) AS A
			  ;

		END IF;

		IF P_COMPANYCODE = 'UT' OR  P_COMPANYCODE = 'US' THEN	

		   SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'C' END
			  INTO P_CHK_FLG
			  FROM (
				SELECT EMPASSWD FROM TYSCMLIB.WEDIUSEF WHERE EMUSERID = P_LOGINID AND  EMPASSWD = P_PASSWORD
			  ) AS A
			  ;	
		END IF;

		IF P_COMPANYCODE = 'TG' THEN	

		   SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'C' END
			  INTO P_CHK_FLG
			  FROM (
				SELECT EMPASSWD FROM TGSCMLIB.WEDIUSEF WHERE EMUSERID = P_LOGINID AND  EMPASSWD = P_PASSWORD
			  ) AS A
			  ;	
		END IF;
	

    END CK1;

	IF P_CHK_FLG = 'Y' THEN
	 

		IF P_COMPANYCODE = 'TY' THEN	

		     UPDATE TYJINFWLIB.ORG_PASSWORD
			SET PASSWORD    = P_NEWPASS
			WHERE COMPANYCODE = P_COMPANYCODE
			AND EMPID     = P_LOGINID;


		END IF;

		IF P_COMPANYCODE = 'UT' OR  P_COMPANYCODE = 'US' THEN	

		    UPDATE TYSCMLIB.WEDIUSEF
		     SET EMPASSWD =  P_NEWPASS
		     WHERE EMUSERID = P_LOGINID;       

		END IF;

		IF P_COMPANYCODE = 'TG' THEN	

		  UPDATE TGSCMLIB.WEDIUSEF
		     SET EMPASSWD =  P_NEWPASS
		     WHERE EMUSERID = P_LOGINID;       

		END IF;
		
	END IF;


    R1 : BEGIN
        DECLARE REFCURSOR CURSOR WITH RETURN FOR
        SELECT P_CHK_FLG AS CHK_FLG FROM SYSIBM.SYSDUMMY1;

        OPEN REFCURSOR;
    END R1;
  
END M1