--DROP VIEW TYJINFWLIB.ORG_DEPTLANG;
-- 부서코드명
-- 이전 테이블 명 : PTORGUSR21
-- TB_DEPTLANG
CREATE VIEW TYJINFWLIB.ORG_DEPTLANG
AS

WITH N ( LEVEL, ENTER_CD, ORG_CD, EAYYMM,  PRIOR_ORG_CD,  SEQ, ROWNUM) AS 
( 
	SELECT   1 AS LEVEL, 
            ENTER_CD,
           ORG_CD,
              EAYYMM,
              PRIOR_ORG_CD,
              SEQ,
                   ROWNUM
FROM TYSCMLIB.EIORGALLMF
WHERE   ENTER_CD =  CAST('TY' AS VARCHAR(2))
   AND  EAYYMM = CAST(VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYYMM') AS VARCHAR(6))
   AND  PRIOR_ORG_CD = '0'
  UNION ALL
 SELECT N.LEVEL+1,
           NPLUS1.ENTER_CD,
        NPLUS1.ORG_CD,
           NPLUS1.EAYYMM,
           NPLUS1.PRIOR_ORG_CD,
           NPLUS1.SEQ,
           NPLUS1.ROWNUM
  FROM TYSCMLIB.EIORGALLMF AS NPLUS1,  N
  WHERE N.ORG_CD = NPLUS1.PRIOR_ORG_CD
   AND  NPLUS1.ENTER_CD = CAST('TY' AS VARCHAR(2))
   AND  NPLUS1.EAYYMM = CAST(VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYYMM') AS VARCHAR(6)) 
)
SELECT
	'TY' AS COMPANYCODE,
	ORG_CD AS DEPTCODE,
	'ko' AS LANGCODE,
	TYSCMLIB.SF_GB_EISORGNAME( ENTER_CD, ORG_CD,EAYYMM||'01') AS DEPTNAME,
	'' AS IFYN
FROM N

UNION 

SELECT
	'UT' AS COMPANYCODE,
	'T10000' AS DEPTCODE,
	'ko' AS LANGCODE,
	'고객사' AS DEPTNAME,
	'' AS IFYN
FROM N

UNION

SELECT
	'UT' AS COMPANYCODE,
	'T10000' AS DEPTCODE,
	'en' AS LANGCODE,
	'CUSTOMER' AS DEPTNAME,
	'' AS IFYN
FROM N

UNION 

SELECT
	'US' AS COMPANYCODE,
	'S10000' AS DEPTCODE,
	'ko' AS LANGCODE,
	'고객사' AS DEPTNAME,
	'' AS IFYN
FROM N

UNION

SELECT
	'US' AS COMPANYCODE,
	'S10000' AS DEPTCODE,
	'en' AS LANGCODE,
	'CUSTOMER' AS DEPTNAME,
	'' AS IFYN
FROM N

