--DROP TABLE TYJINFWLIB.ORG_GROUPUSR;
-- 그룹멤버
-- 이전 테이블 명 : PTORGUSR42
-- TB_GroupMember
CREATE TABLE TYJINFWLIB.ORG_GROUPUSR
(
	  GRPID       CHAR (10) NOT NULL
	, USRID       CHAR (12) NOT NULL
	, COMPANYCODE CHAR (10) NOT NULL
	, USRTYPE     CHAR	  (1)
	, PRIMARY KEY (GRPID,USRID,COMPANYCODE)
);

COMMENT ON TABLE TYJINFWLIB.ORG_GROUPUSR IS '공통-그룹멤버'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_GROUPUSR
(
	GRPID IS '그룹ID' , 
	USRID IS '사용자ID' , 
	COMPANYCODE IS '회사코드' , 
	USRTYPE IS '언어코드' 
); 
