--DROP TABLE TYJINFWLIB.ORG_DEPTUSR;
-- 부서멤버
-- TB_DEPT
CREATE TABLE TYJINFWLIB.ORG_DEPTUSR
(
	  COMPANYCODE		VARGRAPHIC(50) CCSID 1200 
	, DEPTCODE			VARCHAR (50) 
	, USERCOMPANYCODE	VARGRAPHIC(50) CCSID 1200 
	, EMPID				VARCHAR (50) 
	, LOGINID			VARCHAR (50) 
);

COMMENT ON TABLE TYJINFWLIB.ORG_DEPTUSR IS '공통-부서멤버'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_DEPTUSR
(
	COMPANYCODE		 IS '',
	DEPTCODE		IS	'', 
	USERCOMPANYCODE	 IS '',
	EMPID			IS	'', 
	LOGINID			 IS ''
); 
