--DROP VIEW TYJINFWLIB.ORG_RANK;
-- 직책코드
-- 이전 테이블 명 : PTORGUSR60
-- TB_DUTY
CREATE VIEW TYJINFWLIB.ORG_RANK 

AS

	SELECT '' AS COMPANYCODE, 
	CDCODE AS RANKCODE, 
	'ko' AS LANGCODE, 
	'' AS PRGTYPE,
	CDDESC1 AS RANKNAME,
	'N' AS TEAMCHIEFYN,
	CDCODE AS SORTNO,
	'' AS JOBGROUP
FROM TYSCMLIB.INCODEMF WHERE CDINDEX=  'JY'
--ORDER BY CDCODE ASC
