
--DROP VIEW TYJINFWLIB.ORG_COMPANYLANG;
-- 회사코드명
-- 이전 테이블 명 : PTORGUSR11
-- TB_COMPANYGLOBAL
CREATE VIEW TYJINFWLIB.ORG_COMPANYLANG

AS

	SELECT 'TY' AS COMPANYCODE,
	'ko' AS LANGUAGECODE,
	'태영' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1
	
	UNION

	SELECT 'TY' AS COMPANYCODE,
	'en' AS LANGUAGECODE,
	'TAEYOUNG' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1

	UNION 

	SELECT 'TG' AS COMPANYCODE,
	'ko' AS LANGUAGECODE,
	'태영그레인' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1

	UNION 

	SELECT 'TG' AS COMPANYCODE,
	'en' AS LANGUAGECODE,
	'TAEYOUNG GRAIN' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1

	UNION

	SELECT 'TS' AS COMPANYCODE,
	'ko' AS LANGUAGECODE,
	'평택싸이로' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1

	UNION

	SELECT 'TS' AS COMPANYCODE,
	'en' AS LANGUAGECODE,
	'PYEONGTAEK SILO' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1
	
	UNION 
		
	SELECT 'UT' AS COMPANYCODE,
	'ko' AS LANGUAGECODE,
	'T고객사' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1

	UNION

	SELECT 'UT' AS COMPANYCODE,
	'en' AS LANGUAGECODE,
	'TCUSTOMER' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1
	
	UNION 
		
	SELECT 'US' AS COMPANYCODE,
	'ko' AS LANGUAGECODE,
	'S고객사' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1

	UNION

	SELECT 'US' AS COMPANYCODE,
	'en' AS LANGUAGECODE,
	'SCUSTOMER' AS COMPANY,
	'' AS ABBCOMPANY
	FROM SYSIBM.SYSDUMMY1;

