
--DROP VIEW TYJINFWLIB.ORG_DEPT;
-- 부서코드
-- 이전 테이블 명 : PTORGUSR20
-- TB_DEPT
CREATE VIEW TYJINFWLIB.ORG_DEPT
AS


WITH N ( LEVEL, ENTER_CD, ORG_CD, EAYYMM,  PRIOR_ORG_CD,  SEQ, ROWNUM) AS 
( 
	SELECT   1 AS LEVEL, 
            ENTER_CD,
           ORG_CD,
              EAYYMM,
              PRIOR_ORG_CD,
              SEQ,
                   ROWNUM
FROM TYSCMLIB.EIORGALLMF
WHERE   ENTER_CD =  CAST('TY' AS VARCHAR(2))
   AND  EAYYMM = CAST(VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYYMM') AS VARCHAR(6))
   AND  PRIOR_ORG_CD = '0'
  UNION ALL
 SELECT N.LEVEL+1,
           NPLUS1.ENTER_CD,
        NPLUS1.ORG_CD,
           NPLUS1.EAYYMM,
           NPLUS1.PRIOR_ORG_CD,
           NPLUS1.SEQ,
           NPLUS1.ROWNUM
  FROM TYSCMLIB.EIORGALLMF AS NPLUS1,  N
  WHERE N.ORG_CD = NPLUS1.PRIOR_ORG_CD
   AND  NPLUS1.ENTER_CD = CAST('TY' AS VARCHAR(2))
   AND  NPLUS1.EAYYMM = CAST(VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYYMM') AS VARCHAR(6)) 
)
SELECT
	'TY' AS COMPANYCODE,
	ORG_CD AS DEPTCODE,
	'' AS DEPTORDER,
	LEVEL AS DEPTLEVEL,
	CASE WHEN PRIOR_ORG_CD = '0' THEN NULL ELSE PRIOR_ORG_CD END AS PARENTDEPTCODE,
	'' AS CREATEDDT,
	'' AS DEPTEMAIL,
	TYSCMLIB.SF_GB_EISORGNAME( ENTER_CD, ORG_CD,EAYYMM||'01') AS DISPLAYNAME,
	'' AS LEGACYEXCHANGEDN,
	'Y' AS DISPLAYYN,
	'' AS PRGTYPE,
	'' AS LOCATION,
	'' AS DPARTNER,
	'' AS KOSTL,
	'' AS ORG_CD,
	'' AS FEVOR,
	'' AS IFYN,
	'' AS SAPID,
	'' AS REGID,
	'' AS REGDT,
	'' AS UPDID,
	'' AS UPDDT,
	'' AS ORGLEVEL
FROM N

UNION 

SELECT
	'UT' AS COMPANYCODE,
	'T10000' AS DEPTCODE,
	'' AS DEPTORDER,
	1 AS DEPTLEVEL,
	'' AS PARENTDEPTCODE,
	'' AS CREATEDDT,
	'' AS DEPTEMAIL,
	'고객사' AS DISPLAYNAME,
	'' AS LEGACYEXCHANGEDN,
	'Y' AS DISPLAYYN,
	'' AS PRGTYPE,
	'' AS LOCATION,
	'' AS DPARTNER,
	'' AS KOSTL,
	'' AS ORG_CD,
	'' AS FEVOR,
	'' AS IFYN,
	'' AS SAPID,
	'' AS REGID,
	'' AS REGDT,
	'' AS UPDID,
	'' AS UPDDT,
	'' AS ORGLEVEL
FROM SYSIBM.SYSDUMMY1

UNION 

SELECT
	'US' AS COMPANYCODE,
	'S10000' AS DEPTCODE,
	'' AS DEPTORDER,
	1 AS DEPTLEVEL,
	'' AS PARENTDEPTCODE,
	'' AS CREATEDDT,
	'' AS DEPTEMAIL,
	'고객사' AS DISPLAYNAME,
	'' AS LEGACYEXCHANGEDN,
	'Y' AS DISPLAYYN,
	'' AS PRGTYPE,
	'' AS LOCATION,
	'' AS DPARTNER,
	'' AS KOSTL,
	'' AS ORG_CD,
	'' AS FEVOR,
	'' AS IFYN,
	'' AS SAPID,
	'' AS REGID,
	'' AS REGDT,
	'' AS UPDID,
	'' AS UPDDT,
	'' AS ORGLEVEL
FROM SYSIBM.SYSDUMMY1

UNION 

SELECT
	'TG' AS COMPANYCODE,
	'G10000' AS DEPTCODE,
	'' AS DEPTORDER,
	1 AS DEPTLEVEL,
	'' AS PARENTDEPTCODE,
	'' AS CREATEDDT,
	'' AS DEPTEMAIL,
	'고객사' AS DISPLAYNAME,
	'' AS LEGACYEXCHANGEDN,
	'Y' AS DISPLAYYN,
	'' AS PRGTYPE,
	'' AS LOCATION,
	'' AS DPARTNER,
	'' AS KOSTL,
	'' AS ORG_CD,
	'' AS FEVOR,
	'' AS IFYN,
	'' AS SAPID,
	'' AS REGID,
	'' AS REGDT,
	'' AS UPDID,
	'' AS UPDDT,
	'' AS ORGLEVEL
FROM SYSIBM.SYSDUMMY1
--ORDER BY LEVEL, ROWNUM, ORG_CD

