-- 협력업체 로그인정보	   
CREATE TABLE TYJINFWLIB.ORG_PASSWORD
	(
	  COMPANYCODE CHAR (10) NOT NULL
	, LOGINID     CHAR (20) NOT NULL
	, EMPID       CHAR (20) NOT NULL
	, PASSWORD    VARCHAR(200)
	, PRIMARY KEY (COMPANYCODE, LOGINID, EMPID)
	);
COMMENT ON TABLE TYJINFWLIB.ORG_PASSWORD IS '비밀번호'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_PASSWORD.COMPANYCODE IS '회사코드';
COMMENT ON COLUMN TYJINFWLIB.ORG_PASSWORD.LOGINID IS '로그인아이디';
COMMENT ON COLUMN TYJINFWLIB.ORG_PASSWORD.EMPID IS '사번';
COMMENT ON COLUMN TYJINFWLIB.ORG_PASSWORD.PASSWORD IS '비밀번호';

