--DROP VIEW TYJINFWLIB.ORG_USERLANG;
-- 사용자명
-- 이전 테이블 명 : PTORGUSR71
-- TB_UserLang
CREATE VIEW TYJINFWLIB.ORG_USERLANG
AS
SELECT
	'TY' AS COMPANYCODE,
   KBSABUN AS EMPID,
   'ko' AS LANGCODE,
   KBHANGL AS USERLNAME,
   '' AS USERFNAME,
   '' AS IFYN
FROM TYSCMLIB.INKIBNMF
UNION ALL
SELECT  CASE WHEN EMGUBUN = 'T' THEN  'UT' ELSE 'US' END AS COMPANYCODE,
       EMUSERID AS EMPID,
       'ko' AS LANGCODE,       
	   CASE WHEN VNSANGHO IS NOT  NULL THEN VNSANGHO ELSE EMISANGHO END AS USERLNAME,
       '' AS USERFNAME,
       '' AS IFYN
FROM TYSCMLIB.WEDIUSEF
LEFT OUTER JOIN TYSCMLIB.UTIVENDF
   ON   VNCODE = CASE WHEN EMGUBUN = 'T' THEN EMHWAJU ELSE '' END 
UNION ALL
SELECT   'TG'  AS COMPANYCODE,
       EMUSERID AS EMPID,
       'ko' AS LANGCODE,
       EMUSNAME AS USERLNAME,
       '' AS USERFNAME,
       '' AS IFYN
FROM TGSCMLIB.WEDIUSEF


