--DROP TABLE TYJINFWLIB.ORG_LOCATION;
-- 지역코드
-- 이전 테이블 명 : PTORGUSR50
-- TB_Location
CREATE TABLE TYJINFWLIB.ORG_LOCATION 
(
	  LOCATIONCODE  CHAR (4) NOT NULL
	, DISPLAYORDER  CHAR (2) 
	, DISPLAYYN     CHAR (1) 
	, LOCATIONGROUP CHAR (4)
	, PRIMARY KEY (LOCATIONCODE)
);

COMMENT ON TABLE TYJINFWLIB.ORG_LOCATION IS '공통-지역정보'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_LOCATION
(
	LOCATIONCODE IS '지역코드(중국-북경, 중국-상해..)' , 
	DISPLAYORDER IS '정렬순서' , 
	DISPLAYYN IS '사용유무' , 
	LOCATIONGROUP IS '지역그룹(중국..)' 
); 


