--DROP VIEW TYJINFWLIB.ORG_DUTY;
-- 직책코드
-- 이전 테이블 명 : PTORGUSR30
-- TB_DUTY
CREATE VIEW TYJINFWLIB.ORG_DUTY 

AS

	SELECT '' AS COMPANYCODE, 
	CDCODE AS DUTYCODE, 
	'ko' AS LANGCODE, 
	'' AS REGULARITYYN,
	CDDESC1 AS DUTYNAME,
	'N' AS TEAMCHIEFYN,
	CDCODE AS SORTNO
FROM TYSCMLIB.INCODEMF WHERE CDINDEX=  'JK'
--ORDER BY CDCODE ASC
