--DROP VIEW TYJINFWLIB.ORG_COMPANY;
-- 회사코드
-- 이전 테이블 명 : PTORGUSR10
-- TB_COMPANY
CREATE VIEW TYJINFWLIB.ORG_COMPANY

AS

	SELECT 'TY' AS COMPANYCODE,
	'10' AS DISPLAYORDER,
	'TY' AS DOMAINNAME,
	'' AS COMMON
	FROM SYSIBM.SYSDUMMY1

	UNION 

	SELECT 'TG' AS COMPANYCODE,
	'20' AS DISPLAYORDER,
	'TG' AS DOMAINNAME,
	'' AS COMMON
	FROM SYSIBM.SYSDUMMY1

	UNION

	SELECT 'TS' AS COMPANYCODE,
	'30' AS DISPLAYORDER,
	'TS' AS DOMAINNAME,
	'' AS COMMON
	FROM SYSIBM.SYSDUMMY1

	UNION 

	SELECT 'UT' AS COMPANYCODE,
	'40' AS DISPLAYORDER,
	'UT' AS DOMAINNAME,
	'' AS COMMON
	FROM SYSIBM.SYSDUMMY1

	UNION

	SELECT 'US' AS COMPANYCODE,
	'50' AS DISPLAYORDER,
	'US' AS DOMAINNAME,
	'' AS COMMON
	FROM SYSIBM.SYSDUMMY1
