--DROP TABLE TYJINFWLIB.ORG_ADDITIONALJOB;
-- 겸직정보
-- 이전 테이블 명 : PTORGUSR80
-- TB_ADDITIONALJOB
CREATE TABLE TYJINFWLIB.ORG_ADDITIONALJOB
(
	  COMPANYCODE    CHAR (10) NOT NULL
	, EMPID          CHAR (10) NOT NULL
	, SEQNO          CHAR (2) NOT NULL
	, LOGINID        CHAR (12) NOT NULL
	, TYPECODE       CHAR (5) 
	, ADDCOMPANYCODE CHAR (4) 
	, DEPTCODE       CHAR (10) 
	, JOBCODE        CHAR (3) 
	, DUTYCODE       CHAR (3) 
	, DUTYTYPE       CHAR (5) 
	, RANKCODE       CHAR (3) 
	, TEAMCHIEFYN    CHAR (1) 
	, DEPTCODEOTHER  CHAR (2) 
	, JOBDESC		   VARGRAPHIC (200) CCSID 1200
	, PRIMARY KEY (COMPANYCODE,EMPID,SEQNO)
);

COMMENT ON TABLE TYJINFWLIB.ORG_ADDITIONALJOB IS '공통-겸직정보'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_ADDITIONALJOB
(
	COMPANYCODE IS '회사코드' , 
	EMPID IS '사번' , 
	SEQNO IS '순번' , 
	LOGINID IS '로그인아이디' , 
	TYPECODE IS '' , 
	ADDCOMPANYCODE IS '' , 
	DEPTCODE IS '부서코드' , 
	JOBCODE IS '' , 
	DUTYCODE IS '직책코드' , 
	DUTYTYPE IS '' , 
	RANKCODE IS '직위코드' , 
	TEAMCHIEFYN IS '팀장여부' , 
	DEPTCODEOTHER IS '' 
); 

