--DROP TABLE TYJINFWLIB.ORG_LOCATIONLANG;
-- 지역코드명
-- 이전 테이블 명 : PTORGUSR52
-- TB_LocationLang
CREATE TABLE TYJINFWLIB.ORG_LOCATIONLANG
(
	  LOCATIONCODE CHAR (4) NOT NULL
	, LANGCODE     CHAR (2) NOT NULL
	, LOCATIONNAME VARGRAPHIC (40) ALLOCATE(20) CCSID 1200 NOT NULL
	, PRIMARY KEY (LOCATIONCODE,LANGCODE)
);

COMMENT ON TABLE TYJINFWLIB.ORG_LOCATIONLANG IS '공통-지역정보명'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_LOCATIONLANG
(
	LOCATIONCODE IS '지역코드' , 
	LANGCODE IS '언어코드' , 
	LOCATIONNAME IS '지역코드명' 
); 