--DROP TABLE TYJINFWLIB.ORG_GROUPLANG;
-- 그룹코드명
-- 이전 테이블 명 : PTORGUSR41
-- TB_GroupLang
CREATE TABLE TYJINFWLIB.ORG_GROUPLANG
(
	  GRPID    CHAR (10) NOT NULL
	, LANGCODE CHAR (2) NOT NULL
	, GRPNAME  VARGRAPHIC (40) ALLOCATE(20) CCSID 1200
	, PRIMARY KEY (GRPID,LANGCODE)
);

COMMENT ON TABLE TYJINFWLIB.ORG_GROUPLANG IS '공통-그룹명'; 

COMMENT ON COLUMN TYJINFWLIB.ORG_GROUPLANG
(
	GRPID IS '그룹ID' , 
	LANGCODE IS '언어코드' , 
	GRPNAME IS '그룹명' 
); 
