DROP PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_RECEIPT_UPT;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_RECEIPT_UPT(
	IN P_CAASKTEAM VARCHAR(6),    -- 변경요구번호(팀)
	IN P_CAASKDATE VARCHAR(8),    -- 변경요구번호(일자)
	IN P_CAASKSEQ  NUMERIC(3,0)   -- 변경요구번호(순번)
)

DYNAMIC RESULT SETS 1

P1 : BEGIN 

	DECLARE V_CNT NUMERIC ( 3, 0 );

	DECLARE V_CAASKACYEAR      VARCHAR(4);   -- 접수번호년도
    DECLARE V_CAASKACSEQ       NUMERIC(4,0); -- 접수번호순번
	DECLARE V_CARECEIPTDATE    VARCHAR(8);   -- 접수일자

	SELECT
		CAASKACYEAR,
		CAASKACSEQ,
		CARECEIPTDATE INTO V_CAASKACYEAR, V_CAASKACSEQ, V_CARECEIPTDATE
	FROM PSSCMLIB.PSM_CHANGEASK_DOC
	WHERE CAASKTEAM = P_CAASKTEAM
	AND   CAASKDATE = P_CAASKDATE
	AND   CAASKSEQ  = P_CAASKSEQ;

	IF(V_CAASKACYEAR = '' AND V_CAASKACSEQ = 0 AND V_CARECEIPTDATE = '') THEN

		SET V_CAASKACYEAR   = SUBSTR(P_CAASKDATE,1,4);   -- 접수번호년도
		SET V_CAASKACSEQ    = 0; -- 접수번호순번
		SET V_CARECEIPTDATE = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' );   -- 접수일자

		SELECT
		VALUE(MAX(CAASKACSEQ) + 1, 1) INTO V_CAASKACSEQ
		FROM PSSCMLIB.PSM_CHANGEASK_DOC
		WHERE CAASKACYEAR = V_CAASKACYEAR;

		UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
			CAASKACYEAR   = V_CAASKACYEAR,
			CAASKACSEQ    = V_CAASKACSEQ,
			CARECEIPTDATE = V_CARECEIPTDATE
		WHERE CAASKTEAM = P_CAASKTEAM
		AND   CAASKDATE = P_CAASKDATE
		AND   CAASKSEQ  = P_CAASKSEQ;

	END IF;

	MAIN : BEGIN  -- 실행부 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR

			SELECT
				CAASKACYEAR,
				CAASKACSEQ,
				CARECEIPTDATE
			FROM PSSCMLIB.PSM_CHANGEASK_DOC
			WHERE CAASKTEAM = P_CAASKTEAM
			AND   CAASKDATE = P_CAASKDATE
			AND   CAASKSEQ  = P_CAASKSEQ;

		OPEN REFCURSOR;

	END MAIN;

END P1;