DROP PROCEDURE PSSCMLIB.PSM_PSM4041_WORKORDER_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_WORKORDER_RUN ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0)) 

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- Ω√¿€
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
		WORETEAM AS WOSOTEAM,
		TYSCMLIB.SF_GB_ORGNAME(WORETEAM, CAST(WOORDATE AS VARCHAR(8))) AS WOSOTEAMNM,
		WOLOCATIONCODE1,
		( CASE WHEN WOLOCATIONCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE1 ) ELSE '' END ) AS WOLOCATIONCODE1NM , 
		LCT1.FXC3LINKCODE1 AS C3CODE11,
		( CASE WHEN LCT1.FXC3LINKCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT1.FXC3LINKCODE1 ) ELSE '' END ) AS C3CODE11NM , 
		LCT1.FXC3LINKCODE2 AS C3CODE12,
		( CASE WHEN LCT1.FXC3LINKCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT1.FXC3LINKCODE2 ) ELSE '' END ) AS C3CODE12NM , 
		WOLOCATIONCODE2,
		( CASE WHEN WOLOCATIONCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE2 ) ELSE '' END ) AS WOLOCATIONCODE2NM , 
		LCT2.FXC3LINKCODE1 AS C3CODE21,
		( CASE WHEN LCT2.FXC3LINKCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT2.FXC3LINKCODE1 ) ELSE '' END ) AS C3CODE21NM , 
		LCT2.FXC3LINKCODE2 AS C3CODE22,
		( CASE WHEN LCT2.FXC3LINKCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT2.FXC3LINKCODE2 ) ELSE '' END ) AS C3CODE22NM , 
		WOLOCATIONCODE3,
		( CASE WHEN WOLOCATIONCODE3 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE3 ) ELSE '' END ) AS WOLOCATIONCODE3NM , 
		LCT3.FXC3LINKCODE1 AS C3CODE31,
		( CASE WHEN LCT3.FXC3LINKCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT3.FXC3LINKCODE1 ) ELSE '' END ) AS C3CODE31NM , 
		LCT3.FXC3LINKCODE2 AS C3CODE32,
		( CASE WHEN LCT3.FXC3LINKCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT3.FXC3LINKCODE2 ) ELSE '' END ) AS C3CODE32NM , 
		WOLOCATIONCODE4,
		( CASE WHEN WOLOCATIONCODE4 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE4 ) ELSE '' END ) AS WOLOCATIONCODE4NM , 
		LCT4.FXC3LINKCODE1 AS C3CODE41,
		( CASE WHEN LCT4.FXC3LINKCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT4.FXC3LINKCODE1 ) ELSE '' END ) AS C3CODE41NM , 
		LCT4.FXC3LINKCODE2 AS C3CODE42,
		( CASE WHEN LCT4.FXC3LINKCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT4.FXC3LINKCODE2 ) ELSE '' END ) AS C3CODE42NM , 
		WOLOCATIONCODE5,
		( CASE WHEN WOLOCATIONCODE5 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE5 ) ELSE '' END ) AS WOLOCATIONCODE5NM , 
		LCT5.FXC3LINKCODE1 AS C3CODE51,
		( CASE WHEN LCT5.FXC3LINKCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT5.FXC3LINKCODE1 ) ELSE '' END ) AS C3CODE51NM , 
		LCT5.FXC3LINKCODE2 AS C3CODE52,
		( CASE WHEN LCT5.FXC3LINKCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( LCT5.FXC3LINKCODE2 ) ELSE '' END ) AS C3CODE52NM , 
		WOAREACODE1,
		( CASE WHEN WOAREACODE1 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE1 ) ELSE '' END ) AS WOAREACODE1NM , 
		WOAREACODE2,
		( CASE WHEN WOAREACODE2 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE2 ) ELSE '' END ) AS WOAREACODE2NM , 
		WOAREACODE3,
		( CASE WHEN WOAREACODE3 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE3 ) ELSE '' END ) AS WOAREACODE3NM , 
		WOAREACODE4,
		( CASE WHEN WOAREACODE4 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE4 ) ELSE '' END ) AS WOAREACODE4NM , 
		WOAREACODE5,
		( CASE WHEN WOAREACODE5 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE5 ) ELSE '' END ) AS WOAREACODE5NM , 
		WOWORKTITLE
		FROM PSSCMLIB.PSM_WorkOrder
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 AS LCT1
		ON   WOLOCATIONCODE1 = LCT1.FXC3SAUP||LCT1.FXC3BCODE||DIGITS(LCT1.FXC3MCODE)||DIGITS(LCT1.FXC3SCODE)
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 AS LCT2
		ON   WOLOCATIONCODE2 = LCT2.FXC3SAUP||LCT2.FXC3BCODE||DIGITS(LCT2.FXC3MCODE)||DIGITS(LCT2.FXC3SCODE)
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 AS LCT3
		ON   WOLOCATIONCODE3 = LCT3.FXC3SAUP||LCT3.FXC3BCODE||DIGITS(LCT3.FXC3MCODE)||DIGITS(LCT3.FXC3SCODE)
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 AS LCT4
		ON   WOLOCATIONCODE4 = LCT4.FXC3SAUP||LCT4.FXC3BCODE||DIGITS(LCT4.FXC3MCODE)||DIGITS(LCT4.FXC3SCODE)
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 AS LCT5
		ON   WOLOCATIONCODE5 = LCT5.FXC3SAUP||LCT5.FXC3BCODE||DIGITS(LCT5.FXC3MCODE)||DIGITS(LCT5.FXC3SCODE)
		WHERE WOORTEAM = P_WOORTEAM
		AND   WOORDATE = P_WOORDATE
		AND   WOSEQ    = P_WOSEQ;
	
	OPEN REFCURSOR;

END;