DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_OPERA_UPT;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_OPERA_UPT
(
	IN P_SMOPSABUN        VARCHAR(6),
	IN P_SMOPAPPDATE      VARCHAR(8),
	IN P_SMOPAPPTIME      VARCHAR(6),
	IN P_SMOPCOMMENT      VARCHAR(300),
	IN P_SMWKTEAM         VARCHAR(6),
	IN P_SMWKDATE         VARCHAR(8),
	IN P_SMWKSEQ          NUMERIC(3,0),
	IN P_SMWKORAPPDATE    VARCHAR(8),
	IN P_SMWKORSEQ        NUMERIC(3,0)
)
	
LANGUAGE SQL

P1: BEGIN

	UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
		SMOPSABUN   = P_SMOPSABUN,
		SMOPAPPDATE = P_SMOPAPPDATE,
		SMOPAPPTIME = P_SMOPAPPTIME,
		SMOPCOMMENT = P_SMOPCOMMENT
	WHERE SMWKTEAM      = P_SMWKTEAM
	AND   SMWKDATE      = P_SMWKDATE
	AND   SMWKSEQ       = P_SMWKSEQ
	AND   SMWKORAPPDATE = P_SMWKORAPPDATE
	AND   SMWKORSEQ     = P_SMWKORSEQ;

END P1;