--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_GET_SOSABUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_GET_SOSABUN
( 
	IN P_WOORTEAM   VARCHAR(6),
	IN P_WOORDATE   VARCHAR(8),
	IN P_WOSEQ      NUMERIC(3,0)
)
    DYNAMIC RESULT SETS 1 
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH MAST AS
		(
			SELECT
				CAST(P_WOORTEAM AS VARCHAR(6)) AS TEAM,
				CAST(P_WOORDATE AS VARCHAR(8)) AS DATE,
				CAST(P_WOSEQ    AS VARCHAR(3)) AS SEQ
			FROM SYSIBM.SYSDUMMY1
		)

		SELECT
			1 AS NUM,
			WOAPPSOSABUN1 AS SABUN,
			WOAPPSODATE1 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_WORKORDER
		ON     WOORTEAM = TEAM
		AND    WOORDATE = DATE
		AND    WOSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     WOAPPSOSABUN1 = KBSABUN
		WHERE WOAPPSOSABUN1 <> ''
		AND   WOAPPSODATE1 <> ''

		UNION ALL

		SELECT
			2 AS NUM,
			WOAPPSOSABUN2 AS SABUN,
			WOAPPSODATE2 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_WORKORDER
		ON     WOORTEAM = TEAM
		AND    WOORDATE = DATE
		AND    WOSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     WOAPPSOSABUN2 = KBSABUN
		WHERE WOAPPSOSABUN2 <> ''
		AND   WOAPPSODATE2 <> ''

		UNION ALL

		SELECT
			3 AS NUM,
			WOAPPSOSABUN3 AS SABUN,
			WOAPPSODATE3 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_WORKORDER
		ON     WOORTEAM = TEAM
		AND    WOORDATE = DATE
		AND    WOSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     WOAPPSOSABUN3 = KBSABUN
		WHERE WOAPPSOSABUN3 <> ''
		AND   WOAPPSODATE3 <> ''

		UNION ALL

		SELECT
			4 AS NUM,
			WOAPPSOSABUN4 AS SABUN,
			WOAPPSODATE4 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_WORKORDER
		ON     WOORTEAM = TEAM
		AND    WOORDATE = DATE
		AND    WOSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     WOAPPSOSABUN4 = KBSABUN
		WHERE WOAPPSOSABUN4 <> ''
		AND   WOAPPSODATE4 <> ''

		UNION ALL

		SELECT
			5 AS NUM,
			WOAPPSOSABUN5 AS SABUN,
			WOAPPSODATE5 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_WORKORDER
		ON     WOORTEAM = TEAM
		AND    WOORDATE = DATE
		AND    WOSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     WOAPPSOSABUN5 = KBSABUN
		WHERE WOAPPSOSABUN5 <> ''
		AND   WOAPPSODATE5 <> '';

	OPEN REFCURSOR;

END;

CALL PSSCMLIB.PSM_PSM4011_GET_SOSABUN('A20000', '20230726', 5);