DROP PROCEDURE PSSCMLIB.PSM_PSM4072_EXAM_CHECK_CONTENTS_COPY;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4072_EXAM_CHECK_CONTENTS_COPY ( 
	IN P_PECCGUBUN VARCHAR(1) , 
	IN P_PECCDATE VARCHAR (8) ,
	IN P_PECCSEQ NUMERIC(1,0) , 
	IN P_COPYPECCGUBUN VARCHAR(1) , 
	IN P_COPYPECCDATE VARCHAR(8) , 
	IN P_COPYPECCSEQ NUMERIC(1,0) , 
	IN P_PECCHISAB VARCHAR(6)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4072_EXAM_CHECK_CONTENTS_COPY 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 

	INSERT INTO PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
	(
	PECCGUBUN,
	PECCDATE,
	PECCSEQ,
	PECCNUM,
	PECCDESC,
	PECLEVEL,
	PECCCHECK,
	PECCHIGB,
	PECCHIDAT,
	PECCHITIM,
	PECCHISAB
	)
	SELECT
	CAST(P_COPYPECCGUBUN AS VARCHAR(1)) AS PECCGUBUN,
	CAST(P_COPYPECCDATE AS VARCHAR(8)) AS PECCDATE,
	CAST(P_COPYPECCSEQ AS NUMERIC(1,0)) PECCSEQ,
	PECCNUM,
	PECCDESC,
	PECLEVEL,
	PECCCHECK,
	'A' AS PECCHIGB,
	CURRENT_DATE,
	CURRENT_TIME,
	CAST(P_PECCHISAB AS VARCHAR(6)) AS PECCHISAB
	FROM PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
	WHERE PECCGUBUN = P_PECCGUBUN
	AND   PECCDATE = P_PECCDATE
	AND   PECCSEQ = P_PECCSEQ	;
  
END P1  ; 


