--DROP PROCEDURE PSSCMLIB.PSM_PSM4020_CHANGEASK_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4020_CHANGEASK_LIST ( 
	IN P_CAWOTEAM VARCHAR(6),
	IN P_CAWODATE VARCHAR(8),
	IN P_CAWOSEQ  NUMERIC(3,0)
) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 

	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				CAWOTEAM  || '-' || CAWODATE  || '-' || DIGITS ( CAWOSEQ ) AS APP_NUM , 
				CAASKTEAM || '-' || CAASKDATE || '-' || DIGITS ( CAASKSEQ ) AS ASK_NUM , 
				CAASKCONTENT,    -- 설비명
				CAASKBUSEO,      -- 부서코드
				TYSCMLIB.SF_GB_ORGNAME ( CAASKBUSEO , CAST ( CAASKDATE AS VARCHAR ( 8 ) ) ) AS CAASKBUSEONM ,  -- 부서명
				CAASKCLASS,      -- 변경등급
				(CASE WHEN CAASKSTEPGN = '1' THEN '화물(청소 미포함)'
				      WHEN CAASKSTEPGN = '2' THEN '화물(청소 포함)'
				      WHEN CAASKSTEPGN = '3' THEN '정상'
				      WHEN CAASKSTEPGN = '4' THEN '비상'
				      WHEN CAASKSTEPGN = '5' THEN '임시'
				      END) AS CAASKSTEPGN, -- 변경 종류
				CAASKSUMMARY,    -- 변경개요
				(CASE WHEN CAASKACYEAR <> '' THEN (CAASKACYEAR || '-' || DIGITS(CAASKACSEQ))
				      ELSE '' END) AS CAASKNO , -- 접수번호
				CARECEIPTDATE    -- 접수일자
			FROM PSSCMLIB.PSM_CHANGEASK_DOC
			WHERE CAWOTEAM = P_CAWOTEAM
			AND   CAWODATE = P_CAWODATE 
			AND   CAWOSEQ  = P_CAWOSEQ;
  
		OPEN REFCURSOR;
	END MAIN;
END;

CALL PSSCMLIB.PSM_PSM4020_CHANGEASK_LIST('A20000', '20230925', 1);