--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MASTER_SEQ ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MASTER_SEQ ( 
	IN P_JSMWKGUBN   VARCHAR(1),
	IN P_JSMPOTEAM   VARCHAR(6),
	IN P_JSMPODATE   VARCHAR(8),
	IN P_JSMPOSEQ   NUMERIC(3,0),
	IN P_JSMDATE   VARCHAR(8),
	IN P_JSMMSEQ   NUMERIC(3,0),
	IN P_JSMBLASS   VARCHAR(2),
	IN P_JSMMLASS   VARCHAR(2),
	IN P_JSMSLASS   VARCHAR(3)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT   VALUE(MAX(JSMSEQ), 0) + 1 AS JSMSEQ
			FROM PSSCMLIB.PSM_JSACHANGE_MASTER
			WHERE JSMWKGUBN = P_JSMWKGUBN
			AND   JSMPOTEAM = P_JSMPOTEAM
			AND   JSMPODATE = P_JSMPODATE
			AND   JSMPOSEQ  = P_JSMPOSEQ
			AND   JSMDATE   = P_JSMDATE
			AND   JSMMSEQ   = P_JSMMSEQ
			AND   JSMBLASS  = P_JSMBLASS
			AND   JSMMLASS  = P_JSMMLASS
			AND   JSMSLASS  = P_JSMSLASS  ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 