--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_SACODE_SAV;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_SACODE_SAV
( 	
	IN P_SSWKTEAM       VARCHAR(6),
    IN P_SSWKDATE       VARCHAR(8),
	IN P_SSWKSEQ        NUMERIC(3,0),
	IN P_SSORAPPDATE    VARCHAR(8),
	IN P_SSORSEQ        NUMERIC(3,0),
	IN P_SSSACODE       VARCHAR(3),
	IN P_SSCODENAME     VARCHAR(100),
	IN P_SSPUBSEL       VARCHAR(1),
	IN P_SSREVSEL       VARCHAR(1),
	IN P_SSFIXSEL       VARCHAR(1),
	IN P_SSHISAB        VARCHAR(6)
)

LANGUAGE SQL

P1: BEGIN

	INSERT INTO PSSCMLIB.PSM_SAFEORDER_SACODE
	(
		SSWKTEAM,
		SSWKDATE,
		SSWKSEQ,
		SSORAPPDATE,
		SSORSEQ,
		SSSACODE,
		SSCODENAME,
		SSPUBSEL,
		SSREVSEL,
		SSFIXSEL,
		SSHIGB,
		SSHIDAT,
		SSHITIM,
		SSHISAB
	)
	VALUES
	(
		P_SSWKTEAM,
		P_SSWKDATE,
		P_SSWKSEQ,
		P_SSORAPPDATE,
		P_SSORSEQ,
		P_SSSACODE,
		P_SSCODENAME,
		P_SSPUBSEL,
		P_SSREVSEL,
		P_SSFIXSEL,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_SSHISAB
	);	

END P1;