--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_DEL ( 
	IN P_JSDWKGUBN VARCHAR(1),
	IN P_JSDPOTEAM VARCHAR(6),
	IN P_JSDPODATE VARCHAR(8),
	IN P_JSDPOSEQ NUMERIC(3,0),
	IN P_JSDDATE VARCHAR(8),
	IN P_JSDMSEQ NUMERIC(3,0),
	IN P_JSDBLASS VARCHAR(2) , 
	IN P_JSDMLASS VARCHAR(2) , 
	IN P_JSDSLASS VARCHAR(3) , 
	IN P_JSDSEQ NUMERIC(3,0), 
	IN P_JSDITEMSEQ NUMERIC(3,0)) 
	LANGUAGE SQL 

	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_DETAIL
		WHERE JSDWKGUBN  = P_JSDWKGUBN
		AND   JSDPOTEAM  = P_JSDPOTEAM
		AND   JSDPODATE  = P_JSDPODATE
		AND   JSDPOSEQ   = P_JSDPOSEQ 
		AND   JSDDATE    = P_JSDDATE  
		AND   JSDMSEQ    = P_JSDMSEQ  
		AND   JSDBLASS   = P_JSDBLASS
		AND   JSDMLASS   = P_JSDMLASS
		AND   JSDSLASS   = P_JSDSLASS
		AND   JSDSEQ     = P_JSDSEQ
		AND   JSDITEMSEQ = P_JSDITEMSEQ ;

		-- 첨부파일 삭제
		DELETE FROM PSSCMLIB . PSM_CMN_ATTACH
		WHERE ATTACH_TYPE = 'JSA'
		AND    SUBSTR(ATTACH_NO,1,1) = P_JSDWKGUBN
		AND    SUBSTR(ATTACH_NO,2,6) = P_JSDPOTEAM
		AND    SUBSTR(ATTACH_NO,8,8) = P_JSDPODATE
		AND    CAST  (SUBSTR(ATTACH_NO,16,3) AS NUMERIC(3 , 0)) = P_JSDPOSEQ
		AND    SUBSTR(ATTACH_NO,19,8) = P_JSDDATE
		AND    CAST  (SUBSTR(ATTACH_NO,27,3) AS NUMERIC(3 , 0)) = P_JSDMSEQ
		AND    SUBSTR(ATTACH_NO,30,2) = P_JSDBLASS
		AND    SUBSTR(ATTACH_NO,32,2) = P_JSDMLASS
		AND    SUBSTR(ATTACH_NO,34,3) = P_JSDSLASS
		AND    CAST  (SUBSTR(ATTACH_NO,37,3) AS NUMERIC(3 , 0)) = P_JSDSEQ
		AND    CAST  (SUBSTR(ATTACH_NO,40,3) AS NUMERIC(3 , 0)) = P_JSDITEMSEQ
		;
  
END P1  ; 
  