--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CHECK ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CHECK ( 
	IN P_PECSGUBUN VARCHAR(1), 
	IN P_PECSDATE VARCHAR(8),
	IN P_PECSSEQ NUMERIC(1,0)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT  *
			FROM PSSCMLIB.PSM_EXAM_CHECK
			WHERE PECSGUBUN = P_PECSGUBUN
			AND    PECSDATE = P_PECSDATE
			AND    PECSSEQ = P_PECSSEQ ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 