DROP  PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_PRT;
CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_PRT ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0) ) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				WOORTEAM , 
				WOORDATE , 
				WOSEQ , 
				/* 요청승인자, 수신승인자 */ 
				WOAPPSOSABUN1 , 
				WOAPPSONAME1 , 
				WOAPPSOJKCD1 , 
				WOAPPSOJKCDNM1 , 
				CASE WHEN WOAPPSODATE1 <> '' THEN 
				SUBSTR ( WOAPPSODATE1 , 1 , 4 ) || '-' || SUBSTR ( WOAPPSODATE1 , 5 , 2 ) || '-' || SUBSTR ( WOAPPSODATE1 , 7 , 2 ) ELSE WOAPPSODATE1 END AS WOAPPSODATE1 , 
				CASE WHEN WOAPPSOTIME1 <> '' THEN 
				SUBSTR ( WOAPPSOTIME1 , 1 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME1 , 3 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME1 , 5 , 2 ) ELSE WOAPPSOTIME1 END AS WOAPPSOTIME1 , 
				WOAPPSOSABUN2 , 
				WOAPPSONAME2 , 
				WOAPPSOJKCD2 , 
				WOAPPSOJKCDNM2 , 
				CASE WHEN WOAPPSODATE2 <> '' THEN 
				SUBSTR ( WOAPPSODATE2 , 1 , 4 ) || '-' || SUBSTR ( WOAPPSODATE2 , 5 , 2 ) || '-' || SUBSTR ( WOAPPSODATE2 , 7 , 2 ) ELSE WOAPPSODATE2 END AS WOAPPSODATE2 , 
				CASE WHEN WOAPPSOTIME2 <> '' THEN 
				SUBSTR ( WOAPPSOTIME2 , 1 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME2 , 3 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME2 , 5 , 2 ) ELSE WOAPPSOTIME2 END AS WOAPPSOTIME2 , 
				WOAPPSOSABUN3 , 
				WOAPPSONAME3 , 
				WOAPPSOJKCD3 , 
				WOAPPSOJKCDNM3 , 
				CASE WHEN WOAPPSODATE3 <> '' THEN 
				SUBSTR ( WOAPPSODATE3 , 1 , 4 ) || '-' || SUBSTR ( WOAPPSODATE3 , 5 , 2 ) || '-' || SUBSTR ( WOAPPSODATE3 , 7 , 2 ) ELSE WOAPPSODATE3 END AS WOAPPSODATE3 , 
				CASE WHEN WOAPPSOTIME3 <> '' THEN 
				SUBSTR ( WOAPPSOTIME3 , 1 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME3 , 3 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME3 , 5 , 2 ) ELSE WOAPPSOTIME3 END AS WOAPPSOTIME3 , 
				WOAPPSOSABUN4 , 
				WOAPPSONAME4 , 
				WOAPPSOJKCD4 , 
				WOAPPSOJKCDNM4 , 
				CASE WHEN WOAPPSODATE4 <> '' THEN 
				SUBSTR ( WOAPPSODATE4 , 1 , 4 ) || '-' || SUBSTR ( WOAPPSODATE4 , 5 , 2 ) || '-' || SUBSTR ( WOAPPSODATE4 , 7 , 2 ) ELSE WOAPPSODATE4 END AS WOAPPSODATE4 , 
				CASE WHEN WOAPPSOTIME4 <> '' THEN 
				SUBSTR ( WOAPPSOTIME4 , 1 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME4 , 3 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME4 , 5 , 2 ) ELSE WOAPPSOTIME4 END AS WOAPPSOTIME4 , 
				WOAPPSOSABUN5 , 
				WOAPPSONAME5 , 
				WOAPPSOJKCD5 , 
				WOAPPSOJKCDNM5 , 
				CASE WHEN WOAPPSODATE5 <> '' THEN 
				SUBSTR ( WOAPPSODATE5 , 1 , 4 ) || '-' || SUBSTR ( WOAPPSODATE5 , 5 , 2 ) || '-' || SUBSTR ( WOAPPSODATE5 , 7 , 2 ) ELSE WOAPPSODATE5 END AS WOAPPSODATE5 , 
				CASE WHEN WOAPPSOTIME5 <> '' THEN 
				SUBSTR ( WOAPPSOTIME5 , 1 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME5 , 3 , 2 ) || ':' || SUBSTR ( WOAPPSOTIME5 , 5 , 2 ) ELSE WOAPPSOTIME5 END AS WOAPPSOTIME5 , 
				WOAPPRESABUN1 , 
				WOAPPRENAME1 , 
				WOAPPREJKCD1 , 
				WOAPPREJKCDNM1 , 
				CASE WHEN WOAPPREDATE1 <> '' THEN 
				SUBSTR ( WOAPPREDATE1 , 1 , 4 ) || '-' || SUBSTR ( WOAPPREDATE1 , 5 , 2 ) || '-' || SUBSTR ( WOAPPREDATE1 , 7 , 2 ) ELSE WOAPPREDATE1 END AS WOAPPREDATE1 , 
				CASE WHEN WOAPPRETIME1 <> '' THEN 
				SUBSTR ( WOAPPRETIME1 , 1 , 2 ) || ':' || SUBSTR ( WOAPPRETIME1 , 3 , 2 ) || ':' || SUBSTR ( WOAPPRETIME1 , 5 , 2 ) ELSE WOAPPRETIME1 END AS WOAPPRETIME1 , 
				WOAPPRESABUN2 , 
				WOAPPRENAME2 , 
				WOAPPREJKCD2 , 
				WOAPPREJKCDNM2 , 
				CASE WHEN WOAPPREDATE2 <> '' THEN 
				SUBSTR ( WOAPPREDATE2 , 1 , 4 ) || '-' || SUBSTR ( WOAPPREDATE2 , 5 , 2 ) || '-' || SUBSTR ( WOAPPREDATE2 , 7 , 2 ) ELSE WOAPPREDATE2 END AS WOAPPREDATE2 , 
				CASE WHEN WOAPPRETIME2 <> '' THEN 
				SUBSTR ( WOAPPRETIME2 , 1 , 2 ) || ':' || SUBSTR ( WOAPPRETIME2 , 3 , 2 ) || ':' || SUBSTR ( WOAPPRETIME2 , 5 , 2 ) ELSE WOAPPRETIME2 END AS WOAPPRETIME2 , 
				WOAPPRESABUN3 , 
				WOAPPRENAME3 , 
				WOAPPREJKCD3 , 
				WOAPPREJKCDNM3 , 
				CASE WHEN WOAPPREDATE3 <> '' THEN 
				SUBSTR ( WOAPPREDATE3 , 1 , 4 ) || '-' || SUBSTR ( WOAPPREDATE3 , 5 , 2 ) || '-' || SUBSTR ( WOAPPREDATE3 , 7 , 2 ) ELSE WOAPPREDATE3 END AS WOAPPREDATE3 , 
				CASE WHEN WOAPPRETIME3 <> '' THEN 
				SUBSTR ( WOAPPRETIME3 , 1 , 2 ) || ':' || SUBSTR ( WOAPPRETIME3 , 3 , 2 ) || ':' || SUBSTR ( WOAPPRETIME3 , 5 , 2 ) ELSE WOAPPRETIME3 END AS WOAPPRETIME3 , 
				WOAPPRESABUN4 , 
				WOAPPRENAME4 , 
				WOAPPREJKCD4 , 
				WOAPPREJKCDNM4 , 
				CASE WHEN WOAPPREDATE4 <> '' THEN 
				SUBSTR ( WOAPPREDATE4 , 1 , 4 ) || '-' || SUBSTR ( WOAPPREDATE4 , 5 , 2 ) || '-' || SUBSTR ( WOAPPREDATE4 , 7 , 2 ) ELSE WOAPPREDATE4 END AS WOAPPREDATE4 , 
				CASE WHEN WOAPPRETIME4 <> '' THEN 
				SUBSTR ( WOAPPRETIME4 , 1 , 2 ) || ':' || SUBSTR ( WOAPPRETIME4 , 3 , 2 ) || ':' || SUBSTR ( WOAPPRETIME4 , 5 , 2 ) ELSE WOAPPRETIME4 END AS WOAPPRETIME4 , 
				WOAPPRESABUN5 , 
				WOAPPRENAME5 , 
				WOAPPREJKCD5 , 
				WOAPPREJKCDNM5 , 
				CASE WHEN WOAPPREDATE5 <> '' THEN 
				SUBSTR ( WOAPPREDATE5 , 1 , 4 ) || '-' || SUBSTR ( WOAPPREDATE5 , 5 , 2 ) || '-' || SUBSTR ( WOAPPREDATE5 , 7 , 2 ) ELSE WOAPPREDATE5 END AS WOAPPREDATE5 , 
				CASE WHEN WOAPPRETIME5 <> '' THEN 
				SUBSTR ( WOAPPRETIME5 , 1 , 2 ) || ':' || SUBSTR ( WOAPPRETIME5 , 3 , 2 ) || ':' || SUBSTR ( WOAPPRETIME5 , 5 , 2 ) ELSE WOAPPRETIME5 END AS WOAPPRETIME5 , 
				/* 사인 */ 
				 
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN1 
				) AS SOIMGNAME1 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN1 
				) AS SOIMGSIZE1 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN1 
				) AS SOIMGSIGN1 , 
  
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN2 
				) AS SOIMGNAME2 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN2 
				) AS SOIMGSIZE2 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN2 
				) AS SOIMGSIGN2 , 
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN3 
				) AS SOIMGNAME3 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN3 
				) AS SOIMGSIZE3 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN3 
				) AS SOIMGSIGN3 , 
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN4 
				) AS SOIMGNAME4 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN4 
				) AS SOIMGSIZE4 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN4 
				) AS SOIMGSIGN4 , 
  
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN5 
				) AS SOIMGNAME5 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN5 
				) AS SOIMGSIZE5 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPSOSABUN5 
				) AS SOIMGSIGN5 , 
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN1 
				) AS REIMGNAME1 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN1 
				) AS REIMGSIZE1 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN1 
				) AS REIMGSIGN1 , 
  
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN2 
				) AS REIMGNAME2 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN2 
				) AS REIMGSIZE2 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN2 
				) AS REIMGSIGN2 , 
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN3 
				) AS REIMGNAME3 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN3 
				) AS REIMGSIZE3 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN3 
				) AS REIMGSIGN3 , 
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN4 
				) AS REIMGNAME4 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN4 
				) AS REIMGSIZE4 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN4 
				) AS REIMGSIGN4 , 
  
  
				( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN5 
				) AS REIMGNAME5 , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN5 
				) AS REIMGSIZE5 , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = WOAPPRESABUN5 
				) AS REIMGSIGN5 , 
  
  
				/* 
				SOIMG1 . FILE_NAME AS SOIMGNAME1 ,  
				SOIMG1 . FILE_SIZE AS SOIMGSIZE1 ,  
				SOIMG1 . ATTACH_BYTE AS SOIMGSIGN1 ,  
				SOIMG2 . FILE_NAME AS SOIMGNAME2 ,  
				SOIMG2 . FILE_SIZE AS SOIMGSIZE2 ,  
				SOIMG2 . ATTACH_BYTE AS SOIMGSIGN2 ,  
				SOIMG3 . FILE_NAME AS SOIMGNAME3 ,  
				SOIMG3 . FILE_SIZE AS SOIMGSIZE3 ,  
				SOIMG3 . ATTACH_BYTE AS SOIMGSIGN3 ,  
				SOIMG4 . FILE_NAME AS SOIMGNAME4 ,  
				SOIMG4 . FILE_SIZE AS SOIMGSIZE4 ,  
				SOIMG4 . ATTACH_BYTE AS SOIMGSIGN4 ,  
				SOIMG5 . FILE_NAME AS SOIMGNAME5 ,  
				SOIMG5 . FILE_SIZE AS SOIMGSIZE5 ,  
				SOIMG5 . ATTACH_BYTE AS SOIMGSIGN5 ,  
				REIMG1 . FILE_NAME AS REIMGNAME1 ,  
				REIMG1 . FILE_SIZE AS REIMGSIZE1 ,  
				REIMG1 . ATTACH_BYTE AS REIMGSIGN1 ,  
				REIMG2 . FILE_NAME AS REIMGNAME2 ,  
				REIMG2 . FILE_SIZE AS REIMGSIZE2 ,  
				REIMG2 . ATTACH_BYTE AS REIMGSIGN2 ,  
				REIMG3 . FILE_NAME AS REIMGNAME3 ,  
				REIMG3 . FILE_SIZE AS REIMGSIZE3 ,  
				REIMG3 . ATTACH_BYTE AS REIMGSIGN3 ,  
				REIMG4 . FILE_NAME AS REIMGNAME4 ,  
				REIMG4 . FILE_SIZE AS REIMGSIZE4 ,  
				REIMG4 . ATTACH_BYTE AS REIMGSIGN4 ,  
				REIMG5 . FILE_NAME AS REIMGNAME5 ,  
				REIMG5 . FILE_SIZE AS REIMGSIZE5 ,  
				REIMG5 . ATTACH_BYTE AS REIMGSIGN5 ,  
				*/ 
				/* 의견 */ 
				WOAPPSOCOMMENT1 , 
				WOAPPSOCOMMENT2 , 
				WOAPPSOCOMMENT3 , 
				WOAPPSOCOMMENT4 , 
				WOAPPSOCOMMENT5 , 
				WOAPPRECOMMENT1 , 
				WOAPPRECOMMENT2 , 
				WOAPPRECOMMENT3 , 
				WOAPPRECOMMENT4 , 
				WOAPPRECOMMENT5 , 
				/* 작업내용 */ 
				WOORSABUN , 
				PSSCMLIB . SF_PSM_HANGL ( WOORSABUN ) AS WOORSABUNNM , 
				WOSOTEAM , 
				TYSCMLIB . SF_GB_ORGNAME ( WOSOTEAM , CAST ( WOORDATE AS VARCHAR ( 8 ) ) ) AS WOSOTEAMNM , 
				WOSAFESABUN , 
				WORETEAM , 
				TYSCMLIB . SF_GB_ORGNAME ( WORETEAM , CAST ( WOORDATE AS VARCHAR ( 8 ) ) ) AS WORETEAMNM , 
				CASE WHEN WODSDATE1 <> '' THEN 
				SUBSTR ( WODSDATE1 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE1 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE1 , 7 , 2 ) ELSE WODSDATE1 END AS WODSDATE1 , 
				CASE WHEN WODSDATE2 <> '' THEN 
				SUBSTR ( WODSDATE2 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE2 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE2 , 7 , 2 ) ELSE WODSDATE2 END AS WODSDATE2 , 
				/* 설비명 */ 
				WOLOCATIONCODE1 , 
				( CASE WHEN WOLOCATIONCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE1 ) ELSE '' END ) AS WOLOCATIONCODE1NM , 
				WOLOCATIONCODE2 , 
				( CASE WHEN WOLOCATIONCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE2 ) ELSE '' END ) AS WOLOCATIONCODE2NM , 
				WOLOCATIONCODE3 , 
				( CASE WHEN WOLOCATIONCODE3 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE3 ) ELSE '' END ) AS WOLOCATIONCODE3NM , 
				WOLOCATIONCODE4 , 
				( CASE WHEN WOLOCATIONCODE4 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE4 ) ELSE '' END ) AS WOLOCATIONCODE4NM , 
				WOLOCATIONCODE5 , 
				( CASE WHEN WOLOCATIONCODE5 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE5 ) ELSE '' END ) AS WOLOCATIONCODE5NM , 
				/* 작업구역 */ 
				WOAREACODE1 , 
				( CASE WHEN WOAREACODE1 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE1 ) ELSE '' END ) AS WOAREACODE1NM , 
				WOAREACODE2 , 
				( CASE WHEN WOAREACODE2 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE2 ) ELSE '' END ) AS WOAREACODE2NM , 
				WOAREACODE3 , 
				( CASE WHEN WOAREACODE3 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE3 ) ELSE '' END ) AS WOAREACODE3NM , 
				WOAREACODE4 , 
				( CASE WHEN WOAREACODE4 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE4 ) ELSE '' END ) AS WOAREACODE4NM , 
				WOAREACODE5 , 
				( CASE WHEN WOAREACODE5 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE5 ) ELSE '' END ) AS WOAREACODE5NM , 
				/* 작업명 */ 
				WOWORKTITLE , 
				/* 완료일자, 승인자 */ 
				CASE WHEN WOFINISHDATE <> '' THEN 
				SUBSTR ( WOFINISHDATE , 1 , 4 ) || '-' || SUBSTR ( WOFINISHDATE , 5 , 2 ) || '-' || SUBSTR ( WOFINISHDATE , 7 , 2 ) ELSE WOFINISHDATE END AS WOFINISHDATE , 
				WOFINISHSABUN , 
				PSSCMLIB . SF_PSM_HANGL ( WOFINISHSABUN ) AS WOFINISHSABUNNM , 
				/* 변경관리판정 */ 
				WOCHANGEWKJOB , 
				WOCHANGEWKDIV , 
				/* 요청승인취소이력 */ 
				WOCANCELSABUN1 , 
				PSSCMLIB . SF_PSM_HANGL ( WOCANCELSABUN1 ) AS WOCANCELSABUN1NM , 
				WOCANCELDATE1 , 
				WOCANCELTIME1 , 
				WOCANCELCOMMENT1 , 
				WOCANCELSABUN2 , 
				PSSCMLIB . SF_PSM_HANGL ( WOCANCELSABUN2 ) AS WOCANCELSABUN2NM , 
				WOCANCELDATE2 , 
				WOCANCELTIME2 , 
				WOCANCELCOMMENT2 , 
				WOCANCELSABUN3 , 
				PSSCMLIB . SF_PSM_HANGL ( WOCANCELSABUN3 ) AS WOCANCELSABUN3NM , 
				WOCANCELDATE3 , 
				WOCANCELTIME3 , 
				WOCANCELCOMMENT3 , 
				/* 진행상태 */ 
				WOSTATUS , 
				WOGRDOC1 , 
				WOGRURL1 , 
				WOGRDOC2 , 
				WOGRURL2 , 
				 --WOFINISHTEXT , 
				REPLACE ( WOFINISHTEXT , '<br />' , CHR ( 10 ) ) AS WOFINISHTEXT , 
				( CASE WHEN WOIMMEDDATE <> '' THEN SUBSTR ( WOIMMEDDATE , 1 , 4 ) || '-' || SUBSTR ( WOIMMEDDATE , 5 , 2 ) || '-' || SUBSTR ( WOIMMEDDATE , 7 , 2 ) ELSE WOIMMEDDATE END ) AS WOIMMEDDATE , 
				WOIMMEDSABUN , 
				PSSCMLIB . SF_PSM_HANGL ( WOIMMEDSABUN ) AS WOIMMEDSABUNNM , 
				WOIMMEDTEXT , 
				 --WOWORKDOC , 
				REPLACE ( WOWORKDOC , '<br />' , CHR ( 10 ) ) AS WOWORKDOC , 
				WOPONUM1 , 
				WOPONUM2 , 
				WOPONUM3 , 
				WOPONUM4 , 
				WOPONUM5 , 
				( 
					SELECT 
						COALESCE ( MAX ( SMWKORAPPDATE ) , '' ) 
					FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
					WHERE SMWKTEAM = WOORTEAM 
					AND SMWKDATE = WOORDATE 
					AND SMWKSEQ = WOSEQ 
				) AS SMWKORAPPDATE ,				 
				( 
				SELECT 
				COALESCE ( RMWKTEAM , '' ) 
				FROM PSSCMLIB . PSM_RISK_MASTER 
				WHERE RMWKTEAM = WOORTEAM 
				AND RMWKDATE = WOORDATE 
				AND RMWKSEQ = WOSEQ 
				) AS RMWKTEAM , 
			RESABUN , 
			RENAME 
			FROM PSSCMLIB . PSM_WORKORDER 
			/* 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS SOIMG1 
			ON    SOIMG1.ATTACH_TYPE = 'SG' 
			AND    SOIMG1.ATTACH_NO   = WOAPPSOSABUN1 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS SOIMG2 
			ON    SOIMG2.ATTACH_TYPE = 'SG' 
			AND    SOIMG2.ATTACH_NO   = WOAPPSOSABUN2 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS SOIMG3 
			ON    SOIMG3.ATTACH_TYPE = 'SG' 
			AND    SOIMG3.ATTACH_NO   = WOAPPSOSABUN3 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS SOIMG4 
			ON    SOIMG4.ATTACH_TYPE = 'SG' 
			AND    SOIMG4.ATTACH_NO   = WOAPPSOSABUN4 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS SOIMG5 
			ON    SOIMG4.ATTACH_TYPE = 'SG' 
			AND    SOIMG4.ATTACH_NO   = WOAPPSOSABUN5 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS REIMG1 
			ON    REIMG1.ATTACH_TYPE = 'SG' 
			AND    REIMG1.ATTACH_NO   = WOAPPRESABUN1 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS REIMG2 
			ON    REIMG2.ATTACH_TYPE = 'SG' 
			AND    REIMG2.ATTACH_NO   = WOAPPRESABUN2 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS REIMG3 
			ON    REIMG3.ATTACH_TYPE = 'SG' 
			AND    REIMG3.ATTACH_NO   = WOAPPRESABUN3 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS REIMG4 
			ON    REIMG4.ATTACH_TYPE = 'SG' 
			AND    REIMG4.ATTACH_NO   = WOAPPRESABUN4 
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS REIMG5 
			ON    REIMG5.ATTACH_TYPE = 'SG' 
			AND    REIMG5.ATTACH_NO   = WOAPPRESABUN5 
			*/ 
			LEFT OUTER JOIN PSSCMLIB . PSM_REFERENCE 
			ON REDOCID = '01' 
			AND REDOCNUM = WOORTEAM || WOORDATE || DIGITS ( WOSEQ ) 
			WHERE WOORTEAM = P_WOORTEAM 
			AND WOORDATE = P_WOORDATE 
			AND WOSEQ = P_WOSEQ ; 
  
		OPEN REFCURSOR;
END MAIN;

END;