--DROP PROCEDURE PSSCMLIB.PSM_PSM4021_GET_SOSABUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_GET_SOSABUN
( 
	IN P_CAASKTEAM   VARCHAR(6),
	IN P_CAASKDATE   VARCHAR(8),
	IN P_CAASKSEQ    NUMERIC(3,0)
)
    DYNAMIC RESULT SETS 1 
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		WITH MAST AS
		(
			SELECT
				CAST(P_CAASKTEAM AS VARCHAR(6)) AS TEAM,
				CAST(P_CAASKDATE AS VARCHAR(8)) AS DATE,
				CAST(P_CAASKSEQ  AS VARCHAR(3)) AS SEQ
			FROM SYSIBM.SYSDUMMY1
		)

		SELECT
			1 AS NUM,
			CAASKSABUN1 AS SABUN,
			CAASKDATE1 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC
		ON     CAASKTEAM = TEAM
		AND    CAASKDATE = DATE
		AND    CAASKSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     CAASKSABUN1 = KBSABUN
		WHERE CAASKSABUN1 <> ''
		AND   CAASKDATE1 <> ''

		UNION ALL

		SELECT
			2 AS NUM,
			CAASKSABUN2 AS SABUN,
			CAASKDATE2 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC
		ON     CAASKTEAM = TEAM
		AND    CAASKDATE = DATE
		AND    CAASKSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     CAASKSABUN2 = KBSABUN
		WHERE CAASKSABUN2 <> ''
		AND   CAASKDATE2 <> ''

		UNION ALL

		SELECT
			3 AS NUM,
			CAASKSABUN3 AS SABUN,
			CAASKDATE3 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC
		ON     CAASKTEAM = TEAM
		AND    CAASKDATE = DATE
		AND    CAASKSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     CAASKSABUN3 = KBSABUN
		WHERE CAASKSABUN3 <> ''
		AND   CAASKDATE3 <> ''

		UNION ALL

		SELECT
			4 AS NUM,
			CAASKSABUN4 AS SABUN,
			CAASKDATE4 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC
		ON     CAASKTEAM = TEAM
		AND    CAASKDATE = DATE
		AND    CAASKSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     CAASKSABUN4 = KBSABUN
		WHERE CAASKSABUN4 <> ''
		AND   CAASKDATE4 <> ''

		UNION ALL

		SELECT
			5 AS NUM,
			CAASKSABUN5 AS SABUN,
			CAASKDATE5 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC
		ON     CAASKTEAM = TEAM
		AND    CAASKDATE = DATE
		AND    CAASKSEQ    = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON     CAASKSABUN5 = KBSABUN
		WHERE CAASKSABUN5 <> ''
		AND   CAASKDATE5 <> '';

	OPEN REFCURSOR;

END;

CALL PSSCMLIB.PSM_PSM4021_GET_SOSABUN('A20000', '20230726', 5);