
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_GET_SABUN ( 
	IN P_PECTEAM VARCHAR(6) , 
	IN P_PECDATE VARCHAR(8) , 
	IN P_PECSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- Ω√¿€ 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
		WITH MAST AS 
		( 
			SELECT 
				CAST ( P_PECTEAM AS VARCHAR ( 6 ) ) AS TEAM , 
				CAST ( P_PECDATE AS VARCHAR ( 8 ) ) AS DATE , 
				CAST ( P_PECSEQ AS VARCHAR ( 3 ) ) AS SEQ 
			FROM SYSIBM . SYSDUMMY1 
		) 

		SELECT
			1 AS NUM,
			PECSABUN1 AS SABUN,
			PECDATE1 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK
		ON    PECTEAM = TEAM
		AND  PECDATE = DATE
		AND  PECSEQ = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  PECSABUN1 = KBSABUN
		WHERE PECSABUN1 <> ''
		AND    PECDATE1 <> ''

		UNION ALL

		SELECT
			2 AS NUM,
			PECSABUN2 AS SABUN,
			PECDATE2 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK
		ON    PECTEAM = TEAM
		AND  PECDATE = DATE
		AND  PECSEQ = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  PECSABUN2 = KBSABUN
		WHERE PECSABUN2 <> ''
		AND    PECDATE2 <> ''

		UNION ALL

		SELECT
			3 AS NUM,
			PECSABUN3 AS SABUN,
			PECDATE3 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK
		ON    PECTEAM = TEAM
		AND  PECDATE = DATE
		AND  PECSEQ = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  PECSABUN3 = KBSABUN
		WHERE PECSABUN3 <> ''
		AND    PECDATE3 <> ''

		UNION ALL

		SELECT
			4 AS NUM,
			PECSABUN4 AS SABUN,
			PECDATE4 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK
		ON    PECTEAM = TEAM
		AND  PECDATE = DATE
		AND  PECSEQ = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  PECSABUN4 = KBSABUN
		WHERE PECSABUN4 <> ''
		AND    PECDATE4 <> ''

		UNION ALL

		SELECT
			5 AS NUM,
			PECSABUN5 AS SABUN,
			PECDATE5 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK
		ON    PECTEAM = TEAM
		AND  PECDATE = DATE
		AND  PECSEQ = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  PECSABUN5 = KBSABUN
		WHERE PECSABUN5 <> ''
		AND    PECDATE5 <> ''

		UNION ALL

		SELECT
			6 AS NUM,
			PECSABUN6 AS SABUN,
			PECDATE6 AS DATE,
			KBMAILID
		FROM MAST
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK
		ON    PECTEAM = TEAM
		AND  PECDATE = DATE
		AND  PECSEQ = SEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  PECSABUN6 = KBSABUN
		WHERE PECSABUN6 <> ''
		AND    PECDATE6 <> '' ; 
  
	OPEN REFCURSOR ; 
  
END  ; 
