-- DROP PROCEDURE PSSCMLIB.PSM_PSM4030_CHANGEASK_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4030_CHANGEASK_LIST ( 
	IN P_STDATE VARCHAR(8) , 
	IN P_EDDATE VARCHAR(8) , 
	IN P_WKSAUP VARCHAR(1) , 
	IN P_WKTEAM VARCHAR(6) , 
	IN P_DEPT VARCHAR(6) , 
	IN P_CAASKSABUN VARCHAR(6) , 
	IN P_CAASKCONTENT VARCHAR(120) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4030_CHANGEASK_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				ROWNUMBER ( ) OVER ( ) AS ROWNO , 
			       ( CASE WHEN ( SELECT COUNT ( * ) FROM PSSCMLIB . PSM_CHANGEREV_DOC 
				             WHERE CAASKTEAM = CRASKTEAM 
					     AND   CAASKDATE = CRASKDATE 
					     AND   CAASKSEQ  = CRASKSEQ ) = 0 THEN '<img src="/Resources/Images/Icon/icon_new.png" style="cursor:pointer" onclick="gridClick();" />' ELSE '' END ) AS REV_ADD , 
				CAASKTEAM || '-' || CAASKDATE || '-' || DIGITS ( CAASKSEQ ) AS ASK_NUM , 
				CAWOTEAM || '-' || CAWODATE || '-' || DIGITS ( CAWOSEQ ) AS WORK_NUM , 
				CAASKCONTENT ,  -- 설비명 
				CAASKBUSEO ,  -- 부서코드 
				TYSCMLIB . SF_GB_ORGNAME ( CAASKBUSEO , CAST ( CAASKDATE AS VARCHAR ( 8 ) ) ) AS CAASKBUSEONM ,  -- 부서명 
				CAASKCLASS ,  -- 변경 등급
				CAASKSTEPGN,  -- 변경 종류
				( CASE WHEN CAASKSTEPGN = '1' THEN '화물(청소 미포함)' 
				       WHEN CAASKSTEPGN = '2' THEN '화물(청소 포함)' 
				       WHEN CAASKSTEPGN = '3' THEN '정상' 
				       WHEN CAASKSTEPGN = '4' THEN '비상' 
				       WHEN CAASKSTEPGN = '5' THEN '임시' 
				       END ) AS CAASKSTEPGNNM ,  -- 변경 종류명
				CAASKSUMMARY ,  -- 변경개요 
				( CASE WHEN CAASKACYEAR <> '' THEN ( CAASKACYEAR || '-' || DIGITS ( CAASKACSEQ ) ) 
				ELSE '' END ) AS CAASKNO ,  -- 접수순번 
				CARECEIPTDATE  -- 접수일자 
			FROM PSSCMLIB . PSM_CHANGEASK_DOC 
  
			LEFT OUTER JOIN ( SELECT CAST ( P_STDATE AS VARCHAR ( 8 ) ) AS SDATE , 
						CAST ( P_EDDATE AS VARCHAR ( 8 ) ) AS EDATE , 
						CAST ( P_WKSAUP AS VARCHAR ( 1 ) ) AS WKSAUP , 
						CAST ( P_WKTEAM AS VARCHAR ( 6 ) ) AS WKTEAM , 
						CAST ( P_DEPT AS VARCHAR ( 6 ) ) AS DEPT 
				FROM SYSIBM . SYSDUMMY1 ) AS PAR 
			ON 1 = 1 
			WHERE CAASKDATE BETWEEN SDATE AND EDATE 
			AND ( SUBSTR ( CAASKTEAM , 1 , 1 ) LIKE '%' || PAR . WKSAUP || '%' OR CAASKTEAM = PAR . DEPT ) 
			AND CAASKTEAM LIKE '%' || PAR . WKTEAM || '%' 
			AND CAASKSABUN1 LIKE P_CAASKSABUN || '%' 
			AND CAASKCONTENT LIKE '%' || P_CAASKCONTENT || '%' 
			AND CAASKCLASS <> 'C'
			AND CAASKACYEAR <> ''
			AND (CASE WHEN CAASKRESABUN5 <> '' THEN (CASE WHEN CAASKREDATE5 <> '' THEN 'FINISH' ELSE '' END)
			          WHEN CAASKRESABUN4 <> '' THEN (CASE WHEN CAASKREDATE4 <> '' THEN 'FINISH' ELSE '' END)
				  WHEN CAASKRESABUN3 <> '' THEN (CASE WHEN CAASKREDATE3 <> '' THEN 'FINISH' ELSE '' END)
				  WHEN CAASKRESABUN2 <> '' THEN (CASE WHEN CAASKREDATE2 <> '' THEN 'FINISH' ELSE '' END)
				  WHEN CAASKRESABUN1 <> '' THEN (CASE WHEN CAASKREDATE1 <> '' THEN 'FINISH' ELSE '' END)
		             END) = 'FINISH';
			     
		OPEN REFCURSOR ; 
	END MAIN ; 
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE PSSCMLIB.PSM_PSM4030_CHANGEASK_LIST 
TO KSGPDM WITH GRANT OPTION ;

CALL PSSCMLIB.PSM_PSM4030_CHANGEASK_LIST('20230708','20230808','','','','','');