DROP PROCEDURE PSSCMLIB.PSM_PSM4041_BUSEO_EQUAL_CHECK;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_BUSEO_EQUAL_CHECK ( 
	IN P_KBSABUN VARCHAR(6) , 
	IN P_LOGINID VARCHAR(6) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4041_BUSEO_EQUAL_CHECK 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
	LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
			SELECT 
				KBSABUN , 
				KBHANGL , 
				KBBUSEO , 
				KBJUSO , 
				KBSEXGB , 
				KBHOBN , 
				KBJKCD , 
				KBGUNMU , 
				KBMOBILE , 
				KBMAILID 
			FROM TYSCMLIB . INKIBNMF 
			WHERE KBCOMPANY = '2' 
			AND KBBALCD NOT IN ( '900' , '560' ) 
			AND SUBSTR ( KBBUSEO , 1 , 2 ) = ( SELECT SUBSTR ( KBBUSEO , 1 , 2 ) AS BUSEO FROM TYSCMLIB . INKIBNMF 
				WHERE KBCOMPANY = '2' 
									AND KBBALCD NOT IN ( '900' , '560' ) 
									AND KBSABUN = P_KBSABUN ) 
			AND KBJJCD IN ( '090' , '110' , '130' , '150', '180')			 
			AND KBSABUN NOT IN ( '0040-M' ) 
			AND ( CASE WHEN P_LOGINID = '' THEN '' ELSE KBSABUN END ) 
			= ( CASE WHEN P_LOGINID = '' THEN '' ELSE P_LOGINID END ) 
			ORDER BY KBBUSEO , KBJKCD , KBSABUN ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END;