DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_APPROVAL;
--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-07-31 10:14:20 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","KSGPDM" ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_APPROVAL ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0) , 
	IN P_WOORSABUN VARCHAR(6) , 
	IN P_WOWORKTITLE VARCHAR(120) , 
	IN P_WOLOCATIONCODE1 VARCHAR(10) , 
	IN P_WOLOCATIONCODE2 VARCHAR(10) , 
	IN P_WOLOCATIONCODE3 VARCHAR(10) , 
	IN P_WOLOCATIONCODE4 VARCHAR(10) , 
	IN P_WOLOCATIONCODE5 VARCHAR(10) , 
	IN P_WOAREACODE1 VARCHAR(9) , 
	IN P_WOAREACODE2 VARCHAR(9) , 
	IN P_WOAREACODE3 VARCHAR(9) , 
	IN P_WOAREACODE4 VARCHAR(9) , 
	IN P_WOAREACODE5 VARCHAR(9) , 
	IN P_WODSDATE1 VARCHAR(8) , 
	IN P_WODSDATE2 VARCHAR(8) , 
	IN P_WOSOTEAM VARCHAR(6) , 
	IN P_WORETEAM VARCHAR(6) , 
	IN P_WOSAFESABUN VARCHAR(6) , 
	IN P_WOCHANGEWKJOB VARCHAR(2) , 
	IN P_WOCHANGEWKDIV VARCHAR(1) , 
	IN P_WOAPPSOSABUN1 VARCHAR(6) , 
	IN P_WOAPPSONAME1 VARCHAR(20) , 
	IN P_WOAPPSOJKCD1 VARCHAR(3) , 
	IN P_WOAPPSOJKCDNM1 VARCHAR(20) , 
	IN P_WOAPPSOCOMMENT1 VARCHAR(100) , 
	IN P_WOAPPSOSABUN2 VARCHAR(6) , 
	IN P_WOAPPSONAME2 VARCHAR(20) , 
	IN P_WOAPPSOJKCD2 VARCHAR(3) , 
	IN P_WOAPPSOJKCDNM2 VARCHAR(20) , 
	IN P_WOAPPSOCOMMENT2 VARCHAR(100) , 
	IN P_WOAPPSOSABUN3 VARCHAR(6) , 
	IN P_WOAPPSONAME3 VARCHAR(20) , 
	IN P_WOAPPSOJKCD3 VARCHAR(3) , 
	IN P_WOAPPSOJKCDNM3 VARCHAR(20) , 
	IN P_WOAPPSOCOMMENT3 VARCHAR(100) , 
	IN P_WOAPPSOSABUN4 VARCHAR(6) , 
	IN P_WOAPPSONAME4 VARCHAR(20) , 
	IN P_WOAPPSOJKCD4 VARCHAR(3) , 
	IN P_WOAPPSOJKCDNM4 VARCHAR(20) , 
	IN P_WOAPPSOCOMMENT4 VARCHAR(100) , 
	IN P_WOAPPSOSABUN5 VARCHAR(6) , 
	IN P_WOAPPSONAME5 VARCHAR(20) , 
	IN P_WOAPPSOJKCD5 VARCHAR(3) , 
	IN P_WOAPPSOJKCDNM5 VARCHAR(20) , 
	IN P_WOAPPSOCOMMENT5 VARCHAR(100) , 
	IN P_WOAPPRESABUN1 VARCHAR(6) , 
	IN P_WOAPPRENAME1 VARCHAR(20) , 
	IN P_WOAPPREJKCD1 VARCHAR(3) , 
	IN P_WOAPPREJKCDNM1 VARCHAR(20) , 
	IN P_WOAPPRECOMMENT1 VARCHAR(100) , 
	IN P_WOAPPRESABUN2 VARCHAR(6) , 
	IN P_WOAPPRENAME2 VARCHAR(20) , 
	IN P_WOAPPREJKCD2 VARCHAR(3) , 
	IN P_WOAPPREJKCDNM2 VARCHAR(20) , 
	IN P_WOAPPRECOMMENT2 VARCHAR(100) , 
	IN P_WOAPPRESABUN3 VARCHAR(6) , 
	IN P_WOAPPRENAME3 VARCHAR(20) , 
	IN P_WOAPPREJKCD3 VARCHAR(3) , 
	IN P_WOAPPREJKCDNM3 VARCHAR(20) , 
	IN P_WOAPPRECOMMENT3 VARCHAR(100) , 
	IN P_WOAPPRESABUN4 VARCHAR(6) , 
	IN P_WOAPPRENAME4 VARCHAR(20) , 
	IN P_WOAPPREJKCD4 VARCHAR(3) , 
	IN P_WOAPPREJKCDNM4 VARCHAR(20) , 
	IN P_WOAPPRECOMMENT4 VARCHAR(100) , 
	IN P_WOAPPRESABUN5 VARCHAR(6) , 
	IN P_WOAPPRENAME5 VARCHAR(20) , 
	IN P_WOAPPREJKCD5 VARCHAR(3) , 
	IN P_WOAPPREJKCDNM5 VARCHAR(20) , 
	IN P_WOAPPRECOMMENT5 VARCHAR(100) , 
	IN P_WOGRDOC1 VARCHAR(100) , 
	IN P_WOGRURL1 VARCHAR(250) , 
	IN P_WOGRDOC2 VARCHAR(100) , 
	IN P_WOGRURL2 VARCHAR(250) , 
	IN P_WOSTATUS VARCHAR(2) , 
	IN P_WOWORKDOC VARCHAR(2500) , 
	IN P_WOPONUM1 VARCHAR(12) , 
	IN P_WOPONUM2 VARCHAR(12) , 
	IN P_WOPONUM3 VARCHAR(12) , 
	IN P_WOPONUM4 VARCHAR(12) , 
	IN P_WOPONUM5 VARCHAR(12) , 
	IN P_WOHISAB VARCHAR(6) , 
	IN P_RESABUN VARCHAR(1000) , 
	IN P_RENAME VARCHAR(2000) , 
	IN P_SOCOUNT NUMERIC(1, 0) , 
	IN P_RECOUNT NUMERIC(1, 0) , 
	IN P_SOAPPROVAL VARCHAR(1) , 
	IN P_REAPPROVAL VARCHAR(1) , 
	IN P_GUBUN VARCHAR(20) ) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4011_WORKORDER_APPROVAL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
	DECLARE V_CNT NUMERIC ( 3 , 0 ) ; 
  
	DECLARE V_SYULBI VARCHAR ( 10 ) ; 
	DECLARE V_SILOBIN VARCHAR ( 10 ) ; 
	 
	SET V_CNT = 0 ; 
  
	SELECT 
		COUNT ( * ) INTO V_CNT 
	FROM PSSCMLIB . PSM_WORKORDER 
	WHERE WOORTEAM = P_WOORTEAM 
	AND WOORDATE = P_WOORDATE 
	AND WOSEQ = P_WOSEQ ; 
  
	IF ( V_CNT = 0 ) THEN 
  
		INSERT INTO PSSCMLIB . PSM_WORKORDER 
		( 
			WOORTEAM , 
			WOORDATE , 
			WOSEQ , 
			WOORSABUN , 
			WOWORKTITLE , 
			WOLOCATIONCODE1 , 
			WOLOCATIONCODE2 , 
			WOLOCATIONCODE3 , 
			WOLOCATIONCODE4 , 
			WOLOCATIONCODE5 , 
			WOAREACODE1 , 
			WOAREACODE2 , 
			WOAREACODE3 , 
			WOAREACODE4 , 
			WOAREACODE5 , 
			WODSDATE1 , 
			WODSDATE2 , 
			WOSOTEAM , 
			WORETEAM , 
			WOSAFESABUN , 
			WOCHANGEWKJOB , 
			WOCHANGEWKDIV , 
			WOAPPSOSABUN1 , 
			WOAPPSONAME1 , 
			WOAPPSOJKCD1 , 
			WOAPPSOJKCDNM1 , 
			WOAPPSOCOMMENT1 , 
			WOAPPSOSABUN2 , 
			WOAPPSONAME2 , 
			WOAPPSOJKCD2 , 
			WOAPPSOJKCDNM2 , 
			WOAPPSOCOMMENT2 , 
			WOAPPSOSABUN3 , 
			WOAPPSONAME3 , 
			WOAPPSOJKCD3 , 
			WOAPPSOJKCDNM3 , 
			WOAPPSOCOMMENT3 , 
			WOAPPSOSABUN4 , 
			WOAPPSONAME4 , 
			WOAPPSOJKCD4 , 
			WOAPPSOJKCDNM4 , 
			WOAPPSOCOMMENT4 , 
			WOAPPSOSABUN5 , 
			WOAPPSONAME5 , 
			WOAPPSOJKCD5 , 
			WOAPPSOJKCDNM5 , 
			WOAPPSOCOMMENT5 , 
			WOAPPRESABUN1 , 
			WOAPPRENAME1 , 
			WOAPPREJKCD1 , 
			WOAPPREJKCDNM1 , 
			WOAPPRECOMMENT1 , 
			WOAPPRESABUN2 , 
			WOAPPRENAME2 , 
			WOAPPREJKCD2 , 
			WOAPPREJKCDNM2 , 
			WOAPPRECOMMENT2 , 
			WOAPPRESABUN3 , 
			WOAPPRENAME3 , 
			WOAPPREJKCD3 , 
			WOAPPREJKCDNM3 , 
			WOAPPRECOMMENT3 , 
			WOAPPRESABUN4 , 
			WOAPPRENAME4 , 
			WOAPPREJKCD4 , 
			WOAPPREJKCDNM4 , 
			WOAPPRECOMMENT4 , 
			WOAPPRESABUN5 , 
			WOAPPRENAME5 , 
			WOAPPREJKCD5 , 
			WOAPPREJKCDNM5 , 
			WOAPPRECOMMENT5 , 
			WOGRDOC1 , 
			WOGRURL1 , 
			WOGRDOC2 , 
			WOGRURL2 , 
			WOSTATUS , 
			WOWORKDOC , 
			WOPONUM1 , 
			WOPONUM2 , 
			WOPONUM3 , 
			WOPONUM4 , 
			WOPONUM5 , 
			WOHIGB , 
			WOHIDAT , 
			WOHITIM , 
			WOHISAB 
		) 
		VALUES 
		( 
			P_WOORTEAM , 
			P_WOORDATE , 
			P_WOSEQ , 
			P_WOORSABUN , 
			P_WOWORKTITLE , 
			P_WOLOCATIONCODE1 , 
			P_WOLOCATIONCODE2 , 
			P_WOLOCATIONCODE3 , 
			P_WOLOCATIONCODE4 , 
			P_WOLOCATIONCODE5 , 
			P_WOAREACODE1 , 
			P_WOAREACODE2 , 
			P_WOAREACODE3 , 
			P_WOAREACODE4 , 
			P_WOAREACODE5 , 
			P_WODSDATE1 , 
			P_WODSDATE2 , 
			P_WOSOTEAM , 
			P_WORETEAM , 
			P_WOSAFESABUN , 
			P_WOCHANGEWKJOB , 
			P_WOCHANGEWKDIV , 
			P_WOAPPSOSABUN1 , 
			P_WOAPPSONAME1 , 
			P_WOAPPSOJKCD1 , 
			P_WOAPPSOJKCDNM1 , 
			P_WOAPPSOCOMMENT1 , 
			P_WOAPPSOSABUN2 , 
			P_WOAPPSONAME2 , 
			P_WOAPPSOJKCD2 , 
			P_WOAPPSOJKCDNM2 , 
			P_WOAPPSOCOMMENT2 , 
			P_WOAPPSOSABUN3 , 
			P_WOAPPSONAME3 , 
			P_WOAPPSOJKCD3 , 
			P_WOAPPSOJKCDNM3 , 
			P_WOAPPSOCOMMENT3 , 
			P_WOAPPSOSABUN4 , 
			P_WOAPPSONAME4 , 
			P_WOAPPSOJKCD4 , 
			P_WOAPPSOJKCDNM4 , 
			P_WOAPPSOCOMMENT4 , 
			P_WOAPPSOSABUN5 , 
			P_WOAPPSONAME5 , 
			P_WOAPPSOJKCD5 , 
			P_WOAPPSOJKCDNM5 , 
			P_WOAPPSOCOMMENT5 , 
			P_WOAPPRESABUN1 , 
			P_WOAPPRENAME1 , 
			P_WOAPPREJKCD1 , 
			P_WOAPPREJKCDNM1 , 
			P_WOAPPRECOMMENT1 , 
			P_WOAPPRESABUN2 , 
			P_WOAPPRENAME2 , 
			P_WOAPPREJKCD2 , 
			P_WOAPPREJKCDNM2 , 
			P_WOAPPRECOMMENT2 , 
			P_WOAPPRESABUN3 , 
			P_WOAPPRENAME3 , 
			P_WOAPPREJKCD3 , 
			P_WOAPPREJKCDNM3 , 
			P_WOAPPRECOMMENT3 , 
			P_WOAPPRESABUN4 , 
			P_WOAPPRENAME4 , 
			P_WOAPPREJKCD4 , 
			P_WOAPPREJKCDNM4 , 
			P_WOAPPRECOMMENT4 , 
			P_WOAPPRESABUN5 , 
			P_WOAPPRENAME5 , 
			P_WOAPPREJKCD5 , 
			P_WOAPPREJKCDNM5 , 
			P_WOAPPRECOMMENT5 , 
			P_WOGRDOC1 , 
			P_WOGRURL1 , 
			P_WOGRDOC2 , 
			P_WOGRURL2 , 
			P_WOSTATUS , 
			P_WOWORKDOC , 
			P_WOPONUM1 , 
			P_WOPONUM2 , 
			P_WOPONUM3 , 
			P_WOPONUM4 , 
			P_WOPONUM5 , 
			'A' , 
			CURRENT_DATE , 
			CURRENT_TIME , 
			P_WOHISAB 
		) ; 
	ELSE 
		 
		UPDATE PSSCMLIB . PSM_WORKORDER SET 
			WOORSABUN = P_WOORSABUN , 
			WOWORKTITLE = P_WOWORKTITLE , 
			WOLOCATIONCODE1 = P_WOLOCATIONCODE1 , 
			WOLOCATIONCODE2 = P_WOLOCATIONCODE2 , 
			WOLOCATIONCODE3 = P_WOLOCATIONCODE3 , 
			WOLOCATIONCODE4 = P_WOLOCATIONCODE4 , 
			WOLOCATIONCODE5 = P_WOLOCATIONCODE5 , 
			WOAREACODE1 = P_WOAREACODE1 , 
			WOAREACODE2 = P_WOAREACODE2 , 
			WOAREACODE3 = P_WOAREACODE3 , 
			WOAREACODE4 = P_WOAREACODE4 , 
			WOAREACODE5 = P_WOAREACODE5 , 
			WODSDATE1 = P_WODSDATE1 , 
			WODSDATE2 = P_WODSDATE2 , 
			WOSOTEAM = P_WOSOTEAM , 
			WORETEAM = P_WORETEAM , 
			WOSAFESABUN = P_WOSAFESABUN , 
			WOCHANGEWKJOB = P_WOCHANGEWKJOB , 
			WOCHANGEWKDIV = P_WOCHANGEWKDIV , 
			WOAPPSOSABUN1 = P_WOAPPSOSABUN1 , 
			WOAPPSONAME1 = P_WOAPPSONAME1 , 
			WOAPPSOJKCD1 = P_WOAPPSOJKCD1 , 
			WOAPPSOJKCDNM1 = P_WOAPPSOJKCDNM1 , 
			WOAPPSOCOMMENT1 = P_WOAPPSOCOMMENT1 , 
			WOAPPSOSABUN2 = P_WOAPPSOSABUN2 , 
			WOAPPSONAME2 = P_WOAPPSONAME2 , 
			WOAPPSOJKCD2 = P_WOAPPSOJKCD2 , 
			WOAPPSOJKCDNM2 = P_WOAPPSOJKCDNM2 , 
			WOAPPSOCOMMENT2 = P_WOAPPSOCOMMENT2 , 
			WOAPPSOSABUN3 = P_WOAPPSOSABUN3 , 
			WOAPPSONAME3 = P_WOAPPSONAME3 , 
			WOAPPSOJKCD3 = P_WOAPPSOJKCD3 , 
			WOAPPSOJKCDNM3 = P_WOAPPSOJKCDNM3 , 
			WOAPPSOCOMMENT3 = P_WOAPPSOCOMMENT3 , 
			WOAPPSOSABUN4 = P_WOAPPSOSABUN4 , 
			WOAPPSONAME4 = P_WOAPPSONAME4 , 
			WOAPPSOJKCD4 = P_WOAPPSOJKCD4 , 
			WOAPPSOJKCDNM4 = P_WOAPPSOJKCDNM4 , 
			WOAPPSOCOMMENT4 = P_WOAPPSOCOMMENT4 , 
			WOAPPSOSABUN5 = P_WOAPPSOSABUN5 , 
			WOAPPSONAME5 = P_WOAPPSONAME5 , 
			WOAPPSOJKCD5 = P_WOAPPSOJKCD5 , 
			WOAPPSOJKCDNM5 = P_WOAPPSOJKCDNM5 , 
			WOAPPSOCOMMENT5 = P_WOAPPSOCOMMENT5 , 
			WOAPPRESABUN1 = P_WOAPPRESABUN1 , 
			WOAPPRENAME1 = P_WOAPPRENAME1 , 
			WOAPPREJKCD1 = P_WOAPPREJKCD1 , 
			WOAPPREJKCDNM1 = P_WOAPPREJKCDNM1 , 
			WOAPPRECOMMENT1 = P_WOAPPRECOMMENT1 , 
			WOAPPRESABUN2 = P_WOAPPRESABUN2 , 
			WOAPPRENAME2 = P_WOAPPRENAME2 , 
			WOAPPREJKCD2 = P_WOAPPREJKCD2 , 
			WOAPPREJKCDNM2 = P_WOAPPREJKCDNM2 , 
			WOAPPRECOMMENT2 = P_WOAPPRECOMMENT2 , 
			WOAPPRESABUN3 = P_WOAPPRESABUN3 , 
			WOAPPRENAME3 = P_WOAPPRENAME3 , 
			WOAPPREJKCD3 = P_WOAPPREJKCD3 , 
			WOAPPREJKCDNM3 = P_WOAPPREJKCDNM3 , 
			WOAPPRECOMMENT3 = P_WOAPPRECOMMENT3 , 
			WOAPPRESABUN4 = P_WOAPPRESABUN4 , 
			WOAPPRENAME4 = P_WOAPPRENAME4 , 
			WOAPPREJKCD4 = P_WOAPPREJKCD4 , 
			WOAPPREJKCDNM4 = P_WOAPPREJKCDNM4 , 
			WOAPPRECOMMENT4 = P_WOAPPRECOMMENT4 , 
			WOAPPRESABUN5 = P_WOAPPRESABUN5 , 
			WOAPPRENAME5 = P_WOAPPRENAME5 , 
			WOAPPREJKCD5 = P_WOAPPREJKCD5 , 
			WOAPPREJKCDNM5 = P_WOAPPREJKCDNM5 , 
			WOAPPRECOMMENT5 = P_WOAPPRECOMMENT5 , 
			WOGRDOC1 = P_WOGRDOC1 , 
			WOGRURL1 = P_WOGRURL1 , 
			WOGRDOC2 = P_WOGRDOC2 , 
			WOGRURL2 = P_WOGRURL2 , 
			WOSTATUS = P_WOSTATUS , 
			WOWORKDOC = P_WOWORKDOC , 
			WOPONUM1 = P_WOPONUM1 , 
			WOPONUM2 = P_WOPONUM2 , 
			WOPONUM3 = P_WOPONUM3 , 
			WOPONUM4 = P_WOPONUM4 , 
			WOPONUM5 = P_WOPONUM5 , 
			WOHIGB = 'C' , 
			WOHIDAT = CURRENT_DATE , 
			WOHITIM = CURRENT_TIME , 
			WOHISAB		= P_WOHISAB 
		WHERE WOORTEAM = P_WOORTEAM 
		AND WOORDATE = P_WOORDATE 
		AND WOSEQ = P_WOSEQ ; 
  
	END IF ; 
  
	IF P_GUBUN = 'APPROVAL' THEN 
  
		UPDATE PSSCMLIB . PSM_WORKORDER SET 
			WOORSABUN = P_WOORSABUN , 
			WOWORKTITLE = P_WOWORKTITLE , 
			WOLOCATIONCODE1 = P_WOLOCATIONCODE1 , 
			WOLOCATIONCODE2 = P_WOLOCATIONCODE2 , 
			WOLOCATIONCODE3 = P_WOLOCATIONCODE3 , 
			WOLOCATIONCODE4 = P_WOLOCATIONCODE4 , 
			WOLOCATIONCODE5 = P_WOLOCATIONCODE5 , 
			WOAREACODE1 = P_WOAREACODE1 , 
			WOAREACODE2 = P_WOAREACODE2 , 
			WOAREACODE3 = P_WOAREACODE3 , 
			WOAREACODE4 = P_WOAREACODE4 , 
			WOAREACODE5 = P_WOAREACODE5 , 
			WODSDATE1 = P_WODSDATE1 , 
			WODSDATE2 = P_WODSDATE2 , 
			WOSOTEAM = P_WOSOTEAM , 
			WORETEAM = P_WORETEAM , 
			WOSAFESABUN = P_WOSAFESABUN , 
			WOCHANGEWKJOB = P_WOCHANGEWKJOB , 
			WOCHANGEWKDIV = P_WOCHANGEWKDIV , 
			WOAPPSOSABUN1 = P_WOAPPSOSABUN1 , 
			WOAPPSONAME1 = P_WOAPPSONAME1 , 
			WOAPPSOJKCD1 = P_WOAPPSOJKCD1 , 
			WOAPPSOJKCDNM1 = P_WOAPPSOJKCDNM1 , 
			WOAPPSOCOMMENT1 = P_WOAPPSOCOMMENT1 , 
			WOAPPSOSABUN2 = P_WOAPPSOSABUN2 , 
			WOAPPSONAME2 = P_WOAPPSONAME2 , 
			WOAPPSOJKCD2 = P_WOAPPSOJKCD2 , 
			WOAPPSOJKCDNM2 = P_WOAPPSOJKCDNM2 , 
			WOAPPSOCOMMENT2 = P_WOAPPSOCOMMENT2 , 
			WOAPPSOSABUN3 = P_WOAPPSOSABUN3 , 
			WOAPPSONAME3 = P_WOAPPSONAME3 , 
			WOAPPSOJKCD3 = P_WOAPPSOJKCD3 , 
			WOAPPSOJKCDNM3 = P_WOAPPSOJKCDNM3 , 
			WOAPPSOCOMMENT3 = P_WOAPPSOCOMMENT3 , 
			WOAPPSOSABUN4 = P_WOAPPSOSABUN4 , 
			WOAPPSONAME4 = P_WOAPPSONAME4 , 
			WOAPPSOJKCD4 = P_WOAPPSOJKCD4 , 
			WOAPPSOJKCDNM4 = P_WOAPPSOJKCDNM4 , 
			WOAPPSOCOMMENT4 = P_WOAPPSOCOMMENT4 , 
			WOAPPSOSABUN5 = P_WOAPPSOSABUN5 , 
			WOAPPSONAME5 = P_WOAPPSONAME5 , 
			WOAPPSOJKCD5 = P_WOAPPSOJKCD5 , 
			WOAPPSOJKCDNM5 = P_WOAPPSOJKCDNM5 , 
			WOAPPSOCOMMENT5 = P_WOAPPSOCOMMENT5 , 
			WOAPPRESABUN1 = P_WOAPPRESABUN1 , 
			WOAPPRENAME1 = P_WOAPPRENAME1 , 
			WOAPPREJKCD1 = P_WOAPPREJKCD1 , 
			WOAPPREJKCDNM1 = P_WOAPPREJKCDNM1 , 
			WOAPPRECOMMENT1 = P_WOAPPRECOMMENT1 , 
			WOAPPRESABUN2 = P_WOAPPRESABUN2 , 
			WOAPPRENAME2 = P_WOAPPRENAME2 , 
			WOAPPREJKCD2 = P_WOAPPREJKCD2 , 
			WOAPPREJKCDNM2 = P_WOAPPREJKCDNM2 , 
			WOAPPRECOMMENT2 = P_WOAPPRECOMMENT2 , 
			WOAPPRESABUN3 = P_WOAPPRESABUN3 , 
			WOAPPRENAME3 = P_WOAPPRENAME3 , 
			WOAPPREJKCD3 = P_WOAPPREJKCD3 , 
			WOAPPREJKCDNM3 = P_WOAPPREJKCDNM3 , 
			WOAPPRECOMMENT3 = P_WOAPPRECOMMENT3 , 
			WOAPPRESABUN4 = P_WOAPPRESABUN4 , 
			WOAPPRENAME4 = P_WOAPPRENAME4 , 
			WOAPPREJKCD4 = P_WOAPPREJKCD4 , 
			WOAPPREJKCDNM4 = P_WOAPPREJKCDNM4 , 
			WOAPPRECOMMENT4 = P_WOAPPRECOMMENT4 , 
			WOAPPRESABUN5 = P_WOAPPRESABUN5 , 
			WOAPPRENAME5 = P_WOAPPRENAME5 , 
			WOAPPREJKCD5 = P_WOAPPREJKCD5 , 
			WOAPPREJKCDNM5 = P_WOAPPREJKCDNM5 , 
			WOAPPRECOMMENT5 = P_WOAPPRECOMMENT5 , 
			WOGRDOC1 = P_WOGRDOC1 , 
			WOGRURL1 = P_WOGRURL1 , 
			WOGRDOC2 = P_WOGRDOC2 , 
			WOGRURL2 = P_WOGRURL2 , 
			WOSTATUS = P_WOSTATUS , 
			WOWORKDOC = P_WOWORKDOC , 
			WOPONUM1 = P_WOPONUM1 , 
			WOPONUM2 = P_WOPONUM2 , 
			WOPONUM3 = P_WOPONUM3 , 
			WOPONUM4 = P_WOPONUM4 , 
			WOPONUM5 = P_WOPONUM5 
		WHERE WOORTEAM = P_WOORTEAM 
		AND WOORDATE = P_WOORDATE 
		AND WOSEQ = P_WOSEQ ; 
  
		IF P_SOAPPROVAL = '' THEN 
  
			SET P_SOAPPROVAL = '0' ; 
  
		END IF ; 
  
		 -- 결재일자와 시간 업데이트 
		 -- 요청자 결재일자 및 시간 업데이트 
		IF P_SOCOUNT = ( INT ( P_SOAPPROVAL ) + 1 ) THEN 
  
			IF P_SOCOUNT = 1 THEN 
  
				UPDATE PSSCMLIB . PSM_WORKORDER SET 
					WOAPPSODATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					WOAPPSOTIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE WOORTEAM = P_WOORTEAM 
				AND WOORDATE = P_WOORDATE 
				AND WOSEQ = P_WOSEQ ; 
  
			ELSEIF P_SOCOUNT = 2 THEN 
  
				UPDATE PSSCMLIB . PSM_WORKORDER SET 
					WOAPPSODATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					WOAPPSOTIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE WOORTEAM = P_WOORTEAM 
				AND WOORDATE = P_WOORDATE 
				AND WOSEQ = P_WOSEQ ; 
  
			ELSEIF P_SOCOUNT = 3 THEN 
  
				UPDATE PSSCMLIB . PSM_WORKORDER SET 
					WOAPPSODATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					WOAPPSOTIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE WOORTEAM = P_WOORTEAM 
				AND WOORDATE = P_WOORDATE 
				AND WOSEQ = P_WOSEQ ; 
  
			ELSEIF P_SOCOUNT = 4 THEN 
  
				UPDATE PSSCMLIB . PSM_WORKORDER SET 
					WOAPPSODATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					WOAPPSOTIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE WOORTEAM = P_WOORTEAM 
				AND WOORDATE = P_WOORDATE 
				AND WOSEQ = P_WOSEQ ; 
  
			ELSEIF P_SOCOUNT = 5 THEN 
  
				UPDATE PSSCMLIB . PSM_WORKORDER SET 
					WOAPPSODATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					WOAPPSOTIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE WOORTEAM = P_WOORTEAM 
				AND WOORDATE = P_WOORDATE 
				AND WOSEQ = P_WOSEQ ; 
  
			END IF ; 
		ELSE 
  
			IF P_SOCOUNT <> INT ( P_SOAPPROVAL ) THEN 
  
				IF P_SOAPPROVAL = '0' THEN 
  
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPSODATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPSOTIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
  
				ELSEIF P_SOAPPROVAL = '1' THEN 
  
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPSODATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPSOTIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
  
				ELSEIF P_SOAPPROVAL = '2' THEN 
  
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPSODATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPSOTIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
  
				ELSEIF P_SOAPPROVAL = '3' THEN 
  
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPSODATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPSOTIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
  
				ELSEIF P_SOAPPROVAL = '4' THEN 
  
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPSODATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPSOTIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
		 -- 수신자 결재일자 및 시간 업데이트 
		IF P_SOCOUNT = INT ( P_SOAPPROVAL ) THEN 
  
			IF P_RECOUNT = ( INT ( P_REAPPROVAL ) + 1 ) THEN 
  
				IF P_RECOUNT = 1 THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_RECOUNT = 2 THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_RECOUNT = 3 THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_RECOUNT = 4 THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_RECOUNT = 5 THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				END IF ; 
  
			ELSE 
  
				IF P_REAPPROVAL = '0' THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_REAPPROVAL = '1' THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_REAPPROVAL = '2' THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_REAPPROVAL = '3' THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				ELSEIF P_REAPPROVAL = '4' THEN 
	 
					UPDATE PSSCMLIB . PSM_WORKORDER SET 
						WOAPPREDATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						WOAPPRETIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE WOORTEAM = P_WOORTEAM 
					AND WOORDATE = P_WOORDATE 
					AND WOSEQ = P_WOSEQ ; 
	 
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
  
  
  
		SET V_SYULBI = '' ; 
		SET V_SILOBIN = '' ; 
  
		IF ( P_WOLOCATIONCODE1 <> '' ) THEN 
  
			SET V_SYULBI = P_WOLOCATIONCODE1 ; 
  
			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 
  
				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC ; 
  
			END IF ; 
  
		END IF ; 
  
		IF ( V_SILOBIN = '' ) THEN 
  
			IF ( P_WOLOCATIONCODE2 <> '' ) THEN 
  
				SET V_SYULBI = P_WOLOCATIONCODE2 ; 
  
				IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 
  
					SELECT 
					FXC2DESC INTO V_SILOBIN 
					FROM TYSCMLIB . ACFIXCLASS2 
					WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
					AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
					AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
					AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
					AND CHAR ( FXC2MCODE ) = FXC2DESC ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
		IF ( V_SILOBIN = '' ) THEN 
  
			IF ( P_WOLOCATIONCODE3 <> '' ) THEN 
  
				SET V_SYULBI = P_WOLOCATIONCODE3 ; 
  
				IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 
  
					SELECT 
					FXC2DESC INTO V_SILOBIN 
					FROM TYSCMLIB . ACFIXCLASS2 
					WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
					AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
					AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
					AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
					AND CHAR ( FXC2MCODE ) = FXC2DESC ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
		IF ( V_SILOBIN = '' ) THEN 
  
			IF ( P_WOLOCATIONCODE4 <> '' ) THEN 
  
				SET V_SYULBI = P_WOLOCATIONCODE4 ; 
  
				IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 
  
					SELECT 
					FXC2DESC INTO V_SILOBIN 
					FROM TYSCMLIB . ACFIXCLASS2 
					WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
					AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
					AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
					AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
					AND CHAR ( FXC2MCODE ) = FXC2DESC ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
		IF ( V_SILOBIN = '' ) THEN 
  
			IF ( P_WOLOCATIONCODE5 <> '' ) THEN 
  
				SET V_SYULBI = P_WOLOCATIONCODE5 ; 
  
				IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 
  
					SELECT 
					FXC2DESC INTO V_SILOBIN 
					FROM TYSCMLIB . ACFIXCLASS2 
					WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
					AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
					AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
					AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
					AND CHAR ( FXC2MCODE ) = FXC2DESC ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
		 -- 요청 결재후 수신 마지막 결재일 경우(2016.04.26일 이전 로직) 
-- 요청 전결후 참조자 메일 발송(2016.04.26일 윤원영 요청) 
		IF P_SOCOUNT = INT ( P_SOAPPROVAL ) THEN 
  
			 -- 빈 상태관리 업데이트 (4:작업준비) 
			IF ( V_SILOBIN <> '' ) THEN 
				 
				UPDATE TYSCMLIB . BIN_STATUSMF SET 
					SBINSTATUS = '4' 
				WHERE SDATE = ( SELECT MAX ( SDATE ) FROM TYSCMLIB . BIN_STATUSMF ) 
				AND TRIM ( SBINNO ) = TRIM ( V_SILOBIN ) ; 
  
			END IF ; 
  
		END IF ; 
  
		 -- 요청 첫 결재일 경우 
		IF ( V_SILOBIN <> '' ) THEN 
  
			IF ( P_SOAPPROVAL = '' ) THEN 
  
				UPDATE TYSCMLIB . BIN_STATUSMF SET 
					SBINSTATUS = '3' 
				WHERE SDATE = ( SELECT MAX ( SDATE ) FROM TYSCMLIB . BIN_STATUSMF ) 
				AND TRIM ( SBINNO ) = TRIM ( V_SILOBIN ) ; 
  
			END IF ; 
  
		END IF ; 
  
	END IF ; 
  
  
	 -- 참조자 저장 
	CALL PSSCMLIB . PSM_REFERENCE_UPDATE ( 'A' , '01' , P_WOORTEAM || P_WOORDATE || DIGITS ( P_WOSEQ ) , P_RESABUN , P_RENAME , P_WOHISAB ) ; 
  
END P1;