--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_APPSTATUS_UPT;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_APPSTATUS_UPT ( 
	IN P_WOAPPSTATUS   VARCHAR(1),
	IN P_WOORTEAM      VARCHAR(6),
	IN P_WOORDATE      VARCHAR(8),
	IN P_WOSEQ         NUMERIC(3,0))
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4011_WORKORDER_APPSTATUS_UPT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 

	UPDATE PSSCMLIB.PSM_WorkOrder SET
		WOAPPSTATUS  = P_WOAPPSTATUS
	WHERE WOORTEAM = P_WOORTEAM
	AND   WOORDATE = P_WOORDATE
	AND   WOSEQ    = P_WOSEQ;

END P1;