--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_INSPECT_NEXTAPPR ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_INSPECT_NEXTAPPR ( 
	IN P_PEICTEAM VARCHAR(6),
	IN P_PEICDATE VARCHAR(8),
	IN P_PEICSEQ NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PEINUM,
		PEISABUN,
		CASE WHEN PEICHKDATE <> '' THEN SUBSTR(PEICHKDATE,1,4) || '-' || SUBSTR(PEICHKDATE,5,2) || '-' || SUBSTR(PEICHKDATE,7,2) ELSE '' END AS PEICHKDATE,

		KBMAILID,
		KBHANGL
		FROM PSSCMLIB.PSM_EXAM_INSPECT
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON  KBSABUN = PEISABUN
		WHERE PEICTEAM = P_PEICTEAM
		AND    PEICDATE = P_PEICDATE
		AND    PEICSEQ  = P_PEICSEQ
		AND  PEICHKDATE = ''
		ORDER BY PEINUM
		FETCH FIRST 1 ROWS ONLY
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 