DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_RUN; 
CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_RUN ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0) ) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				WOORTEAM , 
				WOORDATE , 
				WOSEQ , 
				/* 요청승인자, 수신승인자 */ 
				WOAPPSOSABUN1 , 
				WOAPPSONAME1 , 
				WOAPPSOJKCD1 , 
				WOAPPSOJKCDNM1 , 
				WOAPPSODATE1 , 
				WOAPPSOTIME1 , 
				WOAPPSOSABUN2 , 
				WOAPPSONAME2 , 
				WOAPPSOJKCD2 , 
				WOAPPSOJKCDNM2 , 
				WOAPPSODATE2 , 
				WOAPPSOTIME2 , 
				WOAPPSOSABUN3 , 
				WOAPPSONAME3 , 
				WOAPPSOJKCD3 , 
				WOAPPSOJKCDNM3 , 
				WOAPPSODATE3 , 
				WOAPPSOTIME3 , 
				WOAPPSOSABUN4 , 
				WOAPPSONAME4 , 
				WOAPPSOJKCD4 , 
				WOAPPSOJKCDNM4 , 
				WOAPPSODATE4 , 
				WOAPPSOTIME4 , 
				WOAPPSOSABUN5 , 
				WOAPPSONAME5 , 
				WOAPPSOJKCD5 , 
				WOAPPSOJKCDNM5 , 
				WOAPPSODATE5 , 
				WOAPPSOTIME5 , 
				WOAPPRESABUN1 , 
				WOAPPRENAME1 , 
				WOAPPREJKCD1 , 
				WOAPPREJKCDNM1 , 
				WOAPPREDATE1 , 
				WOAPPRETIME1 , 
				WOAPPRESABUN2 , 
				WOAPPRENAME2 , 
				WOAPPREJKCD2 , 
				WOAPPREJKCDNM2 , 
				WOAPPREDATE2 , 
				WOAPPRETIME2 , 
				WOAPPRESABUN3 , 
				WOAPPRENAME3 , 
				WOAPPREJKCD3 , 
				WOAPPREJKCDNM3 , 
				WOAPPREDATE3 , 
				WOAPPRETIME3 , 
				WOAPPRESABUN4 , 
				WOAPPRENAME4 , 
				WOAPPREJKCD4 , 
				WOAPPREJKCDNM4 , 
				WOAPPREDATE4 , 
				WOAPPRETIME4 , 
				WOAPPRESABUN5 , 
				WOAPPRENAME5 , 
				WOAPPREJKCD5 , 
				WOAPPREJKCDNM5 , 
				WOAPPREDATE5 , 
				WOAPPRETIME5 , 
				/* 사인 */

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN1
				) AS SOIMGNAME1, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN1
				) AS SOIMGSIZE1, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN1
				) AS SOIMGSIGN1,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN2
				) AS SOIMGNAME2, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN2
				) AS SOIMGSIZE2, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN2
				) AS SOIMGSIGN2, 

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN3
				) AS SOIMGNAME3, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN3
				) AS SOIMGSIZE3, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN3
				) AS SOIMGSIGN3,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN4
				) AS SOIMGNAME4, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN4
				) AS SOIMGSIZE4,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN4
				) AS SOIMGSIGN4,


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN5
				) AS SOIMGNAME5, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN5
				) AS SOIMGSIZE5,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN5
				) AS SOIMGSIGN5,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN1
				) AS REIMGNAME1, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN1
				) AS REIMGSIZE1, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN1
				) AS REIMGSIGN1, 


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN2
				) AS REIMGNAME2, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN2
				) AS REIMGSIZE2, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN2
				) AS REIMGSIGN2, 

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN3
				) AS REIMGNAME3, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN3
				) AS REIMGSIZE3, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN3
				) AS REIMGSIGN3,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN4
				) AS REIMGNAME4, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN4
				) AS REIMGSIZE4,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN4
				) AS REIMGSIGN4,


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN5
				) AS REIMGNAME5, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN5
				) AS REIMGSIZE5,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN5
				) AS REIMGSIGN5,

				/* 의견 */ 
				WOAPPSOCOMMENT1 , 
				WOAPPSOCOMMENT2 , 
				WOAPPSOCOMMENT3 , 
				WOAPPSOCOMMENT4 , 
				WOAPPSOCOMMENT5 , 
				WOAPPRECOMMENT1 , 
				WOAPPRECOMMENT2 , 
				WOAPPRECOMMENT3 , 
				WOAPPRECOMMENT4 , 
				WOAPPRECOMMENT5 , 
				/* 작업내용 */ 
				WOORSABUN , 
				PSSCMLIB . SF_PSM_HANGL ( WOORSABUN ) AS WOORSABUNNM , 
				WOSOTEAM , 
				TYSCMLIB . SF_GB_ORGNAME ( WOSOTEAM , CAST ( WOORDATE AS VARCHAR ( 8 ) ) ) AS WOSOTEAMNM , 
				WOSAFESABUN , 
				WORETEAM , 
				TYSCMLIB . SF_GB_ORGNAME ( WORETEAM , CAST ( WOORDATE AS VARCHAR ( 8 ) ) ) AS WORETEAMNM , 
				WODSDATE1 , 
				WODSDATE2 , 
				/* 설비명 */ 
				WOLOCATIONCODE1 , 
				( CASE WHEN WOLOCATIONCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE1 ) ELSE '' END ) AS WOLOCATIONCODE1NM , 
				WOLOCATIONCODE2 , 
				( CASE WHEN WOLOCATIONCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE2 ) ELSE '' END ) AS WOLOCATIONCODE2NM , 
				WOLOCATIONCODE3 , 
				( CASE WHEN WOLOCATIONCODE3 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE3 ) ELSE '' END ) AS WOLOCATIONCODE3NM , 
				WOLOCATIONCODE4 , 
				( CASE WHEN WOLOCATIONCODE4 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE4 ) ELSE '' END ) AS WOLOCATIONCODE4NM , 
				WOLOCATIONCODE5 , 
				( CASE WHEN WOLOCATIONCODE5 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( WOLOCATIONCODE5 ) ELSE '' END ) AS WOLOCATIONCODE5NM , 
				/* 작업구역 */ 
				WOAREACODE1 , 
				( CASE WHEN WOAREACODE1 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE1 ) ELSE '' END ) AS WOAREACODE1NM , 
				WOAREACODE2 , 
				( CASE WHEN WOAREACODE2 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE2 ) ELSE '' END ) AS WOAREACODE2NM , 
				WOAREACODE3 , 
				( CASE WHEN WOAREACODE3 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE3 ) ELSE '' END ) AS WOAREACODE3NM , 
				WOAREACODE4 , 
				( CASE WHEN WOAREACODE4 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE4 ) ELSE '' END ) AS WOAREACODE4NM , 
				WOAREACODE5 , 
				( CASE WHEN WOAREACODE5 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( WOAREACODE5 ) ELSE '' END ) AS WOAREACODE5NM , 
				/* 작업명 */ 
				WOWORKTITLE , 
				/* 완료일자, 승인자 */ 
				WOFINISHDATE , 
				WOFINISHSABUN , 
				PSSCMLIB . SF_PSM_HANGL ( WOFINISHSABUN ) AS WOFINISHSABUNNM , 
				/* 변경관리판정 */ 
				WOCHANGEWKJOB , 
				WOCHANGEWKDIV , 
				/* 요청승인취소이력 */ 
				WOCANCELSABUN1 , 
				PSSCMLIB . SF_PSM_HANGL ( WOCANCELSABUN1 ) AS WOCANCELSABUN1NM , 
				WOCANCELDATE1 , 
				WOCANCELTIME1 , 
				WOCANCELCOMMENT1 , 
				WOCANCELSABUN2 , 
				PSSCMLIB . SF_PSM_HANGL ( WOCANCELSABUN2 ) AS WOCANCELSABUN2NM , 
				WOCANCELDATE2 , 
				WOCANCELTIME2 , 
				WOCANCELCOMMENT2 , 
				WOCANCELSABUN3 , 
				PSSCMLIB . SF_PSM_HANGL ( WOCANCELSABUN3 ) AS WOCANCELSABUN3NM , 
				WOCANCELDATE3 , 
				WOCANCELTIME3 , 
				WOCANCELCOMMENT3 , 
				/* 진행상태 */ 
				WOSTATUS , 
				WOGRDOC1 , 
				WOGRURL1 , 
				WOGRDOC2 , 
				WOGRURL2 , 
				WOFINISHTEXT , 
				WOIMMEDDATE , 
				WOIMMEDSABUN , 
				PSSCMLIB . SF_PSM_HANGL ( WOIMMEDSABUN ) AS WOIMMEDSABUNNM , 
				WOIMMEDTEXT , 
				WOWORKDOC , 
				WOPONUM1 , 
				WOPONUM2 , 
				WOPONUM3 , 
				WOPONUM4 , 
				WOPONUM5 , 
				( 
					SELECT 
						COALESCE ( MAX ( SMWKORAPPDATE ) , '' ) 
					FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
					WHERE SMWKTEAM = WOORTEAM 
					AND SMWKDATE = WOORDATE 
					AND SMWKSEQ = WOSEQ 
				) AS SMWKORAPPDATE ,				 
				( 
				SELECT 
				COALESCE ( RMWKTEAM , '' ) 
				FROM PSSCMLIB . PSM_RISK_MASTER 
				WHERE RMWKTEAM = WOORTEAM 
				AND RMWKDATE = WOORDATE 
				AND RMWKSEQ = WOSEQ 
				) AS RMWKTEAM 
			FROM PSSCMLIB . PSM_WORKORDER
			WHERE WOORTEAM = P_WOORTEAM 
			AND WOORDATE = P_WOORDATE 
			AND WOSEQ = P_WOSEQ ; 
  
		OPEN REFCURSOR ; 
END MAIN ; 
END;
