--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_DEL ( 
	IN P_PECCGUBUN VARCHAR(1),
	IN P_PECCDATE VARCHAR(8),
	IN P_PECCSEQ NUMERIC(1,0)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
		WHERE PECCGUBUN = P_PECCGUBUN
		AND    PECCDATE = P_PECCDATE
		AND    PECCSEQ = P_PECCSEQ ;
  
END P1  ; 
  