DROP PROCEDURE PSSCMLIB.PSM_PSM4010_WORKORDER_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4010_WORKORDER_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOAPPRESABUN1 VARCHAR(6) , 
	IN P_WOWORKTITLE VARCHAR(300) , 
	IN P_WKGUBN VARCHAR(1) , 
	IN P_WKSTATUS VARCHAR(10) , 
	IN P_WKTEAM VARCHAR(1) , 
	IN P_DEPT VARCHAR(6) , 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORSABUN VARCHAR(6) ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4010_WORKORDER_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 
  
	S1 : BEGIN  -- 값 설정 
		SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
		SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END S1 ; 
  
	LIST : BEGIN 
	 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			WITH TABLE1 AS ( 
			SELECT 
				WOORTEAM || '-' || WOORDATE || '-' || DIGITS ( WOSEQ ) AS APP_NUM , 
				WOORTEAM , 
				WOORDATE , 
				DIGITS ( WOSEQ ) AS WOSEQ , 
				WOORSABUN , 
				K1 . KBHANGL AS WOORSABUNNM , 
				WOWORKTITLE , 
				WOLOCATIONCODE1 , 
				S1 . FXC3DESC AS WOLOCATIONCODE1NM ,  --설비명 
				WOLOCATIONCODE2 , 
				S2 . FXC3DESC AS WOLOCATIONCODE2NM ,  --설비명 
				WOLOCATIONCODE3 , 
				S3 . FXC3DESC AS WOLOCATIONCODE3NM ,  --설비명 
				WOLOCATIONCODE4 , 
				S4 . FXC3DESC AS WOLOCATIONCODE4NM ,  --설비명 
				WOLOCATIONCODE5 , 
				S5 . FXC3DESC AS WOLOCATIONCODE5NM ,  --설비명 
				WOAREACODE1 , 
				WOAREACODE2 , 
				WOAREACODE3 , 
				WOAREACODE4 , 
				WOAREACODE5 , 
				CASE WHEN WODSDATE1 = '' THEN '' ELSE 
				SUBSTR ( WODSDATE1 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE1 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE1 , 7 , 2 ) 
				END AS WODSDATE1 , 
				CASE WHEN WODSDATE2 = '' THEN '' ELSE 
				SUBSTR ( WODSDATE2 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE2 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE2 , 7 , 2 ) 
				END AS WODSDATE2 , 
				CASE WHEN WODSDATE1 = '' THEN '' ELSE 
				SUBSTR ( WODSDATE1 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE1 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE1 , 7 , 2 ) 
				END || ' ~ ' || 
				CASE WHEN WODSDATE2 = '' THEN '' ELSE 
				SUBSTR ( WODSDATE2 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE2 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE2 , 7 , 2 ) 
				END AS WOFROMTODATE , 
				WOSOTEAM , 
				TYSCMLIB . SF_GB_ORGNAME ( WOSOTEAM , WOORDATE ) AS WOSOTEAMNM , 
				WORETEAM , 
				TYSCMLIB . SF_GB_ORGNAME ( WORETEAM , WOORDATE ) AS WORETEAMNM , 
				WOSAFESABUN , 
				K2 . KBHANGL AS WOSAFESABUNNM , 
				WOFINISHDATE , 
				WOFINISHSABUN , 
				WOCHANGEWKJOB , 
				WOCHANGEWKDIV , 
				WOAPPSOSABUN1 , 
				WOAPPSODATE1 , 
				WOAPPSOTIME1 , 
				WOAPPSOCOMMENT1 , 
				WOAPPSOSABUN2 , 
				WOAPPSODATE2 , 
				WOAPPSOTIME2 , 
				WOAPPSOCOMMENT2 , 
				WOAPPSOSABUN3 , 
				WOAPPSODATE3 , 
				WOAPPSOTIME3 , 
				WOAPPSOCOMMENT3 , 
				WOAPPSOSABUN4 , 
				WOAPPSODATE4 , 
				WOAPPSOTIME4 , 
				WOAPPSOCOMMENT4 , 
				WOAPPSOSABUN5 , 
				WOAPPSODATE5 , 
				WOAPPSOTIME5 , 
				WOAPPSOCOMMENT5 , 
				WOAPPRESABUN1 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = WOAPPRESABUN1 ) AS WOAPPRESABUN1NM , 
				WOAPPREDATE1 , 
				WOAPPRETIME1 , 
				WOAPPRECOMMENT1 , 
				WOAPPRESABUN2 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = WOAPPRESABUN2 ) AS WOAPPRESABUN2NM , 
				WOAPPREDATE2 , 
				WOAPPRETIME2 , 
				WOAPPRECOMMENT2 , 
				WOAPPRESABUN3 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = WOAPPRESABUN3 ) AS WOAPPRESABUN3NM , 
				WOAPPREDATE3 , 
				WOAPPRETIME3 , 
				WOAPPRECOMMENT3 , 
				WOAPPRESABUN4 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = WOAPPRESABUN4 ) AS WOAPPRESABUN4NM , 
				WOAPPREDATE4 , 
				WOAPPRETIME4 , 
				WOAPPRECOMMENT4 , 
				WOAPPRESABUN5 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = WOAPPRESABUN5 ) AS WOAPPRESABUN5NM , 
				WOAPPREDATE5 , 
				WOAPPRETIME5 , 
				WOAPPRECOMMENT5 , 
				WOCANCELSABUN1 , 
				WOCANCELDATE1 , 
				WOCANCELTIME1 , 
				WOCANCELCOMMENT1 , 
				WOCANCELSABUN2 , 
				WOCANCELDATE2 , 
				WOCANCELTIME2 , 
				WOCANCELCOMMENT2 , 
				WOCANCELSABUN3 , 
				WOCANCELDATE3 , 
				WOCANCELTIME3 , 
				WOCANCELCOMMENT3 , 
				WOGRDOC1 , 
				WOGRURL1 , 
				WOGRDOC2 , 
				WOGRURL2 , 
				--( SELECT A . WOSTATUSCODE 
				--FROM PSSCMLIB . CV_PSM_WORKSTATUSLIST A 
				--WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOSTATUSCODE , 
  
				( CASE WHEN C . WOSTATUS = '1' AND C . WOAPPSTATUS = 'F' THEN '작업요청 완료' 
				WHEN C . WOSTATUS = '1' AND C . WOAPPSTATUS = '' THEN '작업요청중' 
				WHEN C . WOSTATUS = '2' AND ( SELECT COUNT ( * ) FROM PSSCMLIB . PSM_SAFEORDER_MASTER WHERE SMWKTEAM = C . WOORTEAM AND SMWKDATE = WOORDATE AND SMWKSEQ = WOSEQ ) > 0 THEN '안전작업허가 작업중' 
				WHEN C . WOSTATUS = '2' AND C . WOAPPSTATUS = 'F' THEN 'JSA 완료' 
				WHEN C . WOSTATUS = '3' AND C . WOAPPSTATUS = 'F' THEN '가동전점검 완료' 
				WHEN C . WOSTATUS = '5' AND C . WOAPPSTATUS = 'F' THEN '공사 완료' 
				WHEN C . WOSTATUS = 'A' AND C . WOAPPSTATUS = 'F' THEN '변경요구서 완료' 
				WHEN C . WOSTATUS = 'R' AND C . WOAPPSTATUS = 'F' THEN '변경검토서 완료' 
				ELSE ( SELECT A . WOSTATUS 
				FROM PSSCMLIB . CV_PSM_WORKSTATUSLIST A 
					WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) END ) AS WOSTATUS , 
  
				( SELECT A . WOAPPORSABUN 
				FROM PSSCMLIB . CV_PSM_WORK_FINAL_APPROVAL A 
				WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOAPPORSABUN , 
				( SELECT A . WOAPPORSABUNNM 
				FROM PSSCMLIB . CV_PSM_WORK_FINAL_APPROVAL A 
				WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOAPPORSABUNNM , 
				( SELECT A . WOAPPREVSABUN 
				FROM PSSCMLIB . CV_PSM_WORK_FINAL_APPROVAL A 
				WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOAPPREVSABUN , 
				( SELECT A . WOAPPREVSABUNNM 
				FROM PSSCMLIB . CV_PSM_WORK_FINAL_APPROVAL A 
				WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOAPPREVSABUNNM , 
				PAR . WKSTATUS AS WKSTATUS ,				 
				( CASE WHEN C . WOSTATUS = '5' AND C . WOAPPSTATUS = 'F' THEN '5'  -- 공사완료 
			ELSE '1' END ) AS WORKSTATUS  -- 진행중 
			FROM PSSCMLIB . PSM_WORKORDER C 
			LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S1 
			ON S1 . FXC3SAUP || S1 . FXC3BCODE || DIGITS ( S1 . FXC3MCODE ) || DIGITS ( S1 . FXC3SCODE ) = WOLOCATIONCODE1 
			LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S2 
			ON S2 . FXC3SAUP || S2 . FXC3BCODE || DIGITS ( S2 . FXC3MCODE ) || DIGITS ( S2 . FXC3SCODE ) = WOLOCATIONCODE2 
			LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S3 
			ON S3 . FXC3SAUP || S3 . FXC3BCODE || DIGITS ( S3 . FXC3MCODE ) || DIGITS ( S3 . FXC3SCODE ) = WOLOCATIONCODE3 
			LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S4 
			ON S4 . FXC3SAUP || S4 . FXC3BCODE || DIGITS ( S4 . FXC3MCODE ) || DIGITS ( S4 . FXC3SCODE ) = WOLOCATIONCODE4 
			LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S5 
			ON S5 . FXC3SAUP || S5 . FXC3BCODE || DIGITS ( S5 . FXC3MCODE ) || DIGITS ( S5 . FXC3SCODE ) = WOLOCATIONCODE5 
			LEFT OUTER JOIN TYSCMLIB . INKIBNMF K1 
			ON K1 . KBSABUN = WOORSABUN 
			LEFT OUTER JOIN TYSCMLIB . INKIBNMF K2 
			ON K2 . KBSABUN = WOSAFESABUN 
			LEFT OUTER JOIN ( SELECT CAST ( P_WKGUBN AS VARCHAR ( 1 ) ) AS WKGUBN , 
						CAST ( P_WKSTATUS AS VARCHAR ( 10 ) ) AS WKSTATUS , 
					CAST ( P_WKTEAM AS VARCHAR ( 1 ) ) AS WKTEAM , 
						CAST ( P_DEPT AS VARCHAR ( 6 ) ) AS DEPT 
				FROM SYSIBM . SYSDUMMY1 ) AS PAR 
			ON 1 = 1 
			WHERE WOORDATE <= P_WOORDATE 
			AND WOWORKTITLE LIKE '%' || P_WOWORKTITLE || '%' 
			AND ( SUBSTR ( WOSOTEAM , 1 , 1 ) || SUBSTR ( WORETEAM , 1 , 1 ) LIKE '%' || PAR . WKTEAM || '%' 
				OR WOSOTEAM = PAR . DEPT ) 
			 
			 -- 23.12.04 속도가 느려서 주석 처리 함 
			 --OR ( CASE WHEN PAR . DEPT = 'E10100' THEN WOSOTEAM 
			 --WHEN PAR . DEPT = 'E10200' THEN WOSOTEAM 
			 --	ELSE '' END ) 
			 --= ( CASE WHEN PAR . DEPT = 'E10100' THEN 'D10100' 
			 --	WHEN PAR . DEPT = 'E10200' THEN 'D10200' 
			 --	ELSE '' END ) 
			AND ( CASE WHEN P_WOORTEAM = '' THEN '' ELSE WOORTEAM END ) 
			= ( CASE WHEN P_WOORTEAM = '' THEN '' ELSE P_WOORTEAM END ) 
			AND ( CASE WHEN P_WOORSABUN = '' THEN '' ELSE WOORSABUN END ) 
			= ( CASE WHEN P_WOORSABUN = '' THEN '' ELSE P_WOORSABUN END ) 
			AND ( CASE WHEN P_WOAPPRESABUN1 = '' THEN '' ELSE WOAPPRESABUN1 END ) 
			= ( CASE WHEN P_WOAPPRESABUN1 = '' THEN '' ELSE P_WOAPPRESABUN1 END ) 
			AND ( CASE WHEN WKGUBN = 'A' THEN '1' ELSE WOCHANGEWKDIV END ) 
			= ( CASE WHEN WKGUBN = 'A' THEN '1' ELSE WKGUBN END ) 
			) , 
  
			DETAIL AS 
			( 
				SELECT ROWNUMBER ( ) OVER ( ORDER BY WOORDATE DESC , APP_NUM DESC  ) AS ROWNO , A . * 
				FROM TABLE1 A 
				WHERE WORKSTATUS IN ( SELECT DATA FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( WKSTATUS , ',' ) ) AS INTABLE ) 
			) 
  
			SELECT 
			* 
			FROM DETAIL 
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
	PAGING : BEGIN 
	 
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
			 
			WITH TABLE1 AS ( 
			SELECT 
				WOORTEAM || '-' || WOORDATE || '-' || DIGITS ( WOSEQ ) AS APP_NUM , 
				--( SELECT A . WOSTATUSCODE 
				--FROM PSSCMLIB . CV_PSM_WORKSTATUSLIST A 
				--WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOSTATUSCODE , 
				( SELECT A . WOSTATUS 
				FROM PSSCMLIB . CV_PSM_WORKSTATUSLIST A 
				WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) AS WOSTATUS , 
				PAR . WKSTATUS AS WKSTATUS , 
				( CASE WHEN C . WOSTATUS = '5' AND C . WOAPPSTATUS = 'F' THEN '5'  -- 공사완료 
			ELSE '1' END ) AS WORKSTATUS  -- 진행중 
			FROM PSSCMLIB . PSM_WORKORDER C 
			LEFT OUTER JOIN ( SELECT CAST ( P_WKGUBN AS VARCHAR ( 1 ) ) AS WKGUBN , 
						CAST ( P_WKSTATUS AS VARCHAR ( 10 ) ) AS WKSTATUS , 
					CAST ( P_WKTEAM AS VARCHAR ( 1 ) ) AS WKTEAM , 
						CAST ( P_DEPT AS VARCHAR ( 6 ) ) AS DEPT 
				FROM SYSIBM . SYSDUMMY1 ) AS PAR 
			ON 1 = 1 
			WHERE WOORDATE <= P_WOORDATE 
			AND WOWORKTITLE LIKE '%' || P_WOWORKTITLE || '%' 
			AND ( SUBSTR ( WOSOTEAM , 1 , 1 ) || SUBSTR ( WORETEAM , 1 , 1 ) LIKE '%' || PAR . WKTEAM || '%' 
				OR WOSOTEAM = PAR . DEPT ) 
			 
			 -- 23.12.04 속도가 느려서 주석 처리 함 
			 --OR ( CASE WHEN PAR . DEPT = 'E10100' THEN WOSOTEAM 
			 --WHEN PAR . DEPT = 'E10200' THEN WOSOTEAM 
			 --	ELSE '' END ) 
			 --= ( CASE WHEN PAR . DEPT = 'E10100' THEN 'D10100' 
			 --	WHEN PAR . DEPT = 'E10200' THEN 'D10200' 
			 --	ELSE '' END ) 
			AND ( CASE WHEN P_WOORTEAM = '' THEN '' ELSE WOORTEAM END ) 
			= ( CASE WHEN P_WOORTEAM = '' THEN '' ELSE P_WOORTEAM END ) 
			AND ( CASE WHEN P_WOORSABUN = '' THEN '' ELSE WOORSABUN END ) 
			= ( CASE WHEN P_WOORSABUN = '' THEN '' ELSE P_WOORSABUN END ) 
			AND ( CASE WHEN P_WOAPPRESABUN1 = '' THEN '' ELSE WOAPPRESABUN1 END ) 
			= ( CASE WHEN P_WOAPPRESABUN1 = '' THEN '' ELSE P_WOAPPRESABUN1 END )			 
			AND ( CASE WHEN WKGUBN = 'A' THEN '1' ELSE WOCHANGEWKDIV END ) 
			= ( CASE WHEN WKGUBN = 'A' THEN '1' ELSE WKGUBN END ) 
			) 
  
  
			SELECT COUNT ( * ) AS TOTALCOUNT 
			FROM TABLE1 A 
			WHERE WORKSTATUS IN ( SELECT DATA FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( WKSTATUS , ',' ) ) AS INTABLE ) ; 
  
		OPEN REFCURSOR2 ; 
  
	END PAGING ; 
END  ; 
  
call PSSCMLIB.PSM_PSM4010_WORKORDER_LIST(1,70,'20231110','','','A','1,5','A','','','');