--DROP PROCEDURE PSSCMLIB.PSM_PSM4021_GET_MAX_SEQ;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_GET_MAX_SEQ ( 
	IN P_CAASKTEAM VARCHAR(6),
	IN P_CAASKDATE VARCHAR(8)) 

	DYNAMIC RESULT SETS 1 

P1 : BEGIN
	
	MAIN : BEGIN  -- ½ÇÇàºÎ
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				VALUE(MAX(CAASKSEQ) + 1, 1) AS CAASKSEQ
			FROM PSSCMLIB.PSM_CHANGEASK_DOC
			WHERE CAASKTEAM = P_CAASKTEAM
			AND   CAASKDATE = P_CAASKDATE;

		OPEN REFCURSOR;

	END MAIN;

END P1;

CALL PSSCMLIB.PSM_PSM4021_GET_MAX_SEQ('A20000', '20231004');