DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_SACODE_LIST1;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_SACODE_LIST1
( 
	IN P_SSWKTEAM    VARCHAR(6),
	IN P_SSWKDATE    VARCHAR(8),
	IN P_SSWKSEQ     NUMERIC(3,0),
	IN P_SSORAPPDATE VARCHAR(8),
	IN P_SSORSEQ     NUMERIC(3,0)
) 

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- Ω√¿€
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
			SSSACODE,
			SSPUBSEL,
			SSREVSEL,
			SSFIXSEL
		FROM PSSCMLIB.PSM_SAFEORDER_SACODE
		WHERE  SSWKTEAM    = P_SSWKTEAM
		AND    SSWKDATE    = P_SSWKDATE
		AND    SSWKSEQ     = P_SSWKSEQ
		AND    SSORAPPDATE = P_SSORAPPDATE
		AND    SSORSEQ     = P_SSORSEQ
		ORDER BY SSSACODE;

	OPEN REFCURSOR;
END;