DROP PROCEDURE PSSCMLIB.PSM_OUTSIDECONSTRUCT_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_OUTSIDECONSTRUCT_RUN
( 
	P_OSDATE    VARCHAR(8),
    P_OSSEQ     NUMERIC(3, 0)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- 시작
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR						
		
              SELECT OSDATE		,
                    DIGITS(OSSEQ) AS OSSEQ,
                    OSLOCATIONCODE1 ,
                    S1 . FXC3DESC AS OSLOCATIONCODE1NM ,  --설비명 
                    OSAREACODE1	,
                    L1 . L3NAME AS OSAREACODE1NM ,
                    OSLOCATIONCODE2 ,
                    S2 . FXC3DESC AS OSLOCATIONCODE2NM ,  --설비명 
                    OSAREACODE2	,
                    L2 . L3NAME AS OSAREACODE2NM ,
                    OSLOCATIONCODE3 ,
                    S3 . FXC3DESC AS OSLOCATIONCODE3NM ,  --설비명 
                    OSAREACODE3	,
                    L3 . L3NAME AS OSAREACODE3NM ,
                    OSLOCATIONCODE4 ,
                    S4 . FXC3DESC AS OSLOCATIONCODE4NM ,  --설비명 
                    OSAREACODE4	,
                    L4 . L3NAME AS OSAREACODE4NM ,
                    OSLOCATIONCODE5 ,
                    S5 . FXC3DESC AS OSLOCATIONCODE5NM ,  --설비명 
                    OSAREACODE5	,
                    L5 . L3NAME AS OSAREACODE5NM ,
                    OSMETHODCODE	,
                    OSCOMPANY	,
                    OSBUSEO		,
                    TYSCMLIB.SF_GB_ORGNAME(OSBUSEO, OSDATE) AS OSBUSEONM,
                    OSSABUN		,
                    KBHANGL AS OSSABUNNM,
                    OSWKSDATE	,
                    OSWKEDATE	,
                    OSWKCLOSE	,
                    OSWKCLDATE	 
				FROM PSSCMLIB.PSM_OutSideConstruct
                LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S1 
			    ON S1 . FXC3SAUP || S1 . FXC3BCODE || DIGITS ( S1 . FXC3MCODE ) || DIGITS ( S1 . FXC3SCODE ) = OSLOCATIONCODE1 
			    LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S2 
			    ON S2 . FXC3SAUP || S2 . FXC3BCODE || DIGITS ( S2 . FXC3MCODE ) || DIGITS ( S2 . FXC3SCODE ) = OSLOCATIONCODE2 
			    LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S3 
			    ON S3 . FXC3SAUP || S3 . FXC3BCODE || DIGITS ( S3 . FXC3MCODE ) || DIGITS ( S3 . FXC3SCODE ) = OSLOCATIONCODE3 
			    LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S4 
			    ON S4 . FXC3SAUP || S4 . FXC3BCODE || DIGITS ( S4 . FXC3MCODE ) || DIGITS ( S4 . FXC3SCODE ) = OSLOCATIONCODE4 
			    LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S5 
			    ON S5 . FXC3SAUP || S5 . FXC3BCODE || DIGITS ( S5 . FXC3MCODE ) || DIGITS ( S5 . FXC3SCODE ) = OSLOCATIONCODE5 

                LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L1 
			    ON L1.L3SAUP||L1.L3BCODE||DIGITS(L1.L3MCODE)||DIGITS(L1.L3SCODE) = OSAREACODE1 
			    LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L2 
			    ON L2.L3SAUP||L2.L3BCODE||DIGITS(L2.L3MCODE)||DIGITS(L2.L3SCODE) = OSAREACODE2
			    LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L3 
			    ON L3.L3SAUP||L3.L3BCODE||DIGITS(L3.L3MCODE)||DIGITS(L3.L3SCODE) = OSAREACODE3 
			    LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L4 
			    ON L4.L3SAUP||L4.L3BCODE||DIGITS(L4.L3MCODE)||DIGITS(L4.L3SCODE) = OSAREACODE4 
			    LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L5 
			    ON L5.L3SAUP||L5.L3BCODE||DIGITS(L5.L3MCODE)||DIGITS(L5.L3SCODE) = OSAREACODE5

                LEFT OUTER JOIN TYSCMLIB.INKIBNMF
                   ON KBSABUN = OSSABUN
		        WHERE OSDATE = P_OSDATE
                  AND OSSEQ  = P_OSSEQ;

	OPEN REFCURSOR;

END