--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4048_JSA_MASTER_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4048_JSA_MASTER_LIST ( 
	IN P_JSMBLASS VARCHAR(2),
	IN P_JSMMLASS VARCHAR(2),
	IN P_JSMSLASS VARCHAR(3),
	IN P_JSMWKNAME VARCHAR(400)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
			JSMBLASS,
			J1NAME AS JBCODE,
			JSMMLASS,
			J2NAME AS JMCODE,
			JSMSLASS,
			J3NAME AS JSCODE,
			JSMSEQ       ,
			JSMWKNAME    ,
			JSMSECTIONNUM,
			H1CODE.CDDESC1 AS H1CODE,
			DIGITS(JSMMSDSCODE)||'-'||DIGITS(JSMMSDSSEQ) AS JSMMSDS
			FROM PSSCMLIB.PSM_JSA_MASTER
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
			ON    JSMBLASS = J1CODE
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2
			ON    JSMBLASS = J2BCODE
			AND   JSMMLASS = J2MCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3
			ON    JSMBLASS = J3BCODE
			AND   JSMMLASS = J3MCODE
			AND   JSMSLASS = J3SCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF AS H1CODE
			ON             'H1' = H1CODE.CDINDEX
			AND   JSMSECTIONNUM = H1CODE.CDCODE
			WHERE JSMBLASS LIKE  '%' || P_JSMBLASS || '%'
			AND   JSMMLASS LIKE  '%' || P_JSMMLASS || '%'
			AND   JSMSLASS LIKE  '%' || P_JSMSLASS || '%'
			AND   JSMWKNAME LIKE  '%' || P_JSMWKNAME || '%'
						 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 