--DROP PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_RUN ( 
	IN P_CRREVTEAM VARCHAR(6) , 
	IN P_CRREVDATE VARCHAR(8) , 
	IN P_CRREVSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4031_CHANGEREV_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				CRREVCONTENT , 
				CRREVDATA , 
				CRREVSUMMARY , 
				CRREVAPPROVAL , 
				CRREVREASION , 
				/* 요청승인자 */ 
				CRREVSABUN1 , 
				CRREVNAME1 , 
				CRREVJKCD1 , 
				CRREVJKCDNM1 , 
				CRREVDATE1 , 
				CRREVTIME1 , 
				CRREVSABUN2 , 
				CRREVNAME2 , 
				CRREVJKCD2 , 
				CRREVJKCDNM2 , 
				CRREVDATE2 , 
				CRREVTIME2 , 
				CRREVSABUN3 , 
				CRREVNAME3 , 
				CRREVJKCD3 , 
				CRREVJKCDNM3 , 
				CRREVDATE3 , 
				CRREVTIME3 , 
				CRREVSABUN4 , 
				CRREVNAME4 , 
				CRREVJKCD4 , 
				CRREVJKCDNM4 , 
				CRREVDATE4 , 
				CRREVTIME4 , 
				CRREVSABUN5 , 
				CRREVNAME5 , 
				CRREVJKCD5 , 
				CRREVJKCDNM5 , 
				CRREVDATE5 , 
				CRREVTIME5 , 
  
				CRREVSABUN6 , 
				CRREVNAME6 , 
				CRREVJKCD6 , 
				CRREVJKCDNM6 , 
				CRREVDATE6 , 
				CRREVTIME6 , 
  
				/* 사인 */ 
				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN1
				) AS SOIMGNAME1, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN1
				) AS SOIMGSIZE1, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN1
				) AS SOIMGSIGN1,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN2
				) AS SOIMGNAME2, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN2
				) AS SOIMGSIZE2, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN2
				) AS SOIMGSIGN2, 

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN3
				) AS SOIMGNAME3, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN3
				) AS SOIMGSIZE3, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN3
				) AS SOIMGSIGN3,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN4
				) AS SOIMGNAME4, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN4
				) AS SOIMGSIZE4,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN4
				) AS SOIMGSIGN4,


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN5
				) AS SOIMGNAME5, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN5
				) AS SOIMGSIZE5,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN5
				) AS SOIMGSIGN5,


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN6
				) AS SOIMGNAME6, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN6
				) AS SOIMGSIZE6,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = CRREVSABUN6
				) AS SOIMGSIGN6, 
				/* 의견 */ 
				CRREVCOMMENT1 , 
				CRREVCOMMENT2 , 
				CRREVCOMMENT3 , 
				CRREVCOMMENT4 , 
				CRREVCOMMENT5 , 
				CRREVCOMMENT6 
			FROM PSSCMLIB . PSM_CHANGEREV_DOC 			
			WHERE CRREVTEAM = P_CRREVTEAM 
			AND CRREVDATE = P_CRREVDATE 
			AND CRREVSEQ = P_CRREVSEQ ; 
  
		OPEN REFCURSOR ; 
	END MAIN ; 
END;