--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4070_EXAM_CHECK_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4070_EXAM_CHECK_LIST ( 
	IN P_PECWOTEAM VARCHAR(6),
	IN P_PECWODATE VARCHAR(8),
	IN P_PECWOSEQ NUMERIC(3,0),
	IN P_PECSGUBUN VARCHAR(1))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PECWOTEAM || '-' || PECWODATE || '-' || DIGITS(PECWOSEQ) AS APP_NUM,
		PECTEAM || '-' || PECDATE || '-' || DIGITS(PECSEQ) AS PEC_NUM,
		PECTEAM,
		PECDATE,
		PECSEQ,
		PECWOTEAM,
		PECWODATE,
		PECWOSEQ,
		PECTITLE,
		CASE WHEN PECINSDATE <> '' THEN SUBSTR(PECINSDATE,1,4) || '-' || SUBSTR(PECINSDATE,5,2) || '-' || SUBSTR(PECINSDATE,7,2) ELSE '' END AS PECINSDATE,
		CASE WHEN PECSGUBUN = '1' THEN '일반' ELSE '화물' END AS PECSGUBUN,
		CASE WHEN PECRDATE <> '' THEN PECRDATE || '-' || DIGITS(PECRSEQ) ELSE '' END PECRNUM
		FROM PSSCMLIB.PSM_EXAM_CHECK
		WHERE PECWOTEAM = P_PECWOTEAM
		AND   PECWODATE = P_PECWODATE
		AND   PECWOSEQ  = P_PECWOSEQ
		AND   PECSGUBUN = P_PECSGUBUN
		ORDER BY PECTEAM,PECDATE DESC ,PECSEQ DESC
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 


UP_GET_EXAM_CHECK_LIST