--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_GET_MAX_WOSEQ;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_GET_MAX_WOSEQ ( 
	IN P_WOORTEAM VARCHAR(6),
	IN P_WOORDATE VARCHAR(8)) 

	DYNAMIC RESULT SETS 1 

P1 : BEGIN
	
	MAIN : BEGIN  -- ½ÇÇàºÎ
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				VALUE(MAX(WOSEQ) + 1, 1) AS WOSEQ
			FROM PSSCMLIB.PSM_WorkOrder
			WHERE WOORTEAM = P_WOORTEAM
			AND   WOORDATE = P_WOORDATE;

		OPEN REFCURSOR;

	END MAIN;

END P1;

CALL PSSCMLIB.PSM_PSM4011_GET_MAX_WOSEQ('0311-M', '20230719');