DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_INSPECT_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_INSPECT_ADD ( 
	IN P_PEICTEAM  VARCHAR(6),
	IN P_PEICDATE  VARCHAR(8),
	IN P_PEICSEQ   NUMERIC(3,0),
	IN P_PEINUM     NUMERIC(3,0),
	IN P_PEISABUN    VARCHAR(6),
	IN P_PEICHKDATE   VARCHAR(8),
	IN P_PEIHISAB   VARCHAR(6), 
	IN P_GUBUN       VARCHAR(1)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 

	IF P_GUBUN = 'A' THEN

		IF P_PEINUM = '1' THEN 

			DELETE FROM PSSCMLIB.PSM_EXAM_INSPECT
			WHERE PEICTEAM = P_PEICTEAM
			AND   PEICDATE = P_PEICDATE
			AND   PEICSEQ  = P_PEICSEQ;

		END IF;

		INSERT INTO PSSCMLIB.PSM_EXAM_INSPECT
		(
		PEICTEAM  ,
		PEICDATE  ,
		PEICSEQ   ,
		PEINUM    ,
		PEISABUN  ,
		PEICHKDATE,
		PEIHIGB   ,
		PEIHIDAT  ,		
		PEIHITIM  ,		
		PEIHISAB  		
		)
		VALUES
		(
		P_PEICTEAM  ,
		P_PEICDATE  ,
		P_PEICSEQ   ,
		P_PEINUM    ,
		P_PEISABUN  ,
		P_PEICHKDATE,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_PEIHISAB
		)
		;
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_EXAM_INSPECT SET
		PEISABUN     = P_PEISABUN   ,
		PEICHKDATE    = P_PEICHKDATE ,
		PEIHIGB     = 'C'          ,
		PEIHIDAT    = CURRENT_DATE ,
		PEIHITIM    = CURRENT_TIME ,
		PEIHISAB    = PEIHISAB
		WHERE PEICTEAM = P_PEICTEAM
		AND   PEICDATE = P_PEICDATE
		AND   PEICSEQ  = P_PEICSEQ
		AND   PEINUM  = P_PEINUM ;
  
	END IF ; 
  
END P1  ; 
  