DROP PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_ADD ( 
	IN P_PECCGUBUN VARCHAR(1),
	IN P_PECCDATE VARCHAR(8),
	IN P_PECCSEQ NUMERIC(1,0),
	IN P_PECCNUM NUMERIC(3,0),
	IN P_PECCDESC VARCHAR(300),
	IN P_PECLEVEL VARCHAR(1),
	IN P_PECCCHECK VARCHAR(1) , 
	IN P_PECCHISAB VARCHAR(6)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 
	 
	INSERT INTO PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
	(
	PECCGUBUN,
	PECCDATE,
	PECCSEQ,
	PECCNUM,
	PECCDESC,
	PECLEVEL,
	PECCCHECK,
	PECCHIGB,
	PECCHIDAT,
	PECCHITIM,
	PECCHISAB
	)
	VALUES
	(
	P_PECCGUBUN,
	P_PECCDATE,
	P_PECCSEQ,
	P_PECCNUM,
	P_PECCDESC,
	P_PECLEVEL,
	P_PECCCHECK,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_PECCHISAB
	)
	;
 
  
END P1  ; 
  