--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_DEL ( 
	IN P_PECTEAM VARCHAR(6),
	IN P_PECDATE VARCHAR(8),
	IN P_PECSEQ NUMERIC(3,0),
	IN P_PECDGUBUN VARCHAR(1),
	IN P_PECDDATE VARCHAR(8),
	IN P_PECDSEQ NUMERIC(1,0)) 
	LANGUAGE SQL 

	P1 : BEGIN 
  
		-- 점검표 마스타
		DELETE 
		FROM PSSCMLIB.PSM_EXAM_CHECK
		WHERE PECTEAM = P_PECTEAM
		AND   PECDATE = P_PECDATE
		AND   PECSEQ = P_PECSEQ
		;

		-- 점검표 내역
		DELETE
		FROM PSSCMLIB.PSM_EXAM_CHECK_DETAIL
		WHERE PECDTCTEAM = P_PECTEAM
		AND   PECDTCDATE = P_PECDATE
		AND   PECDTCSEQ = P_PECSEQ
		AND   PECDGUBUN = P_PECDGUBUN
		AND   PECDDATE = P_PECDDATE
		AND   PECDSEQ = P_PECDSEQ
		;

		-- 점검자 목록
		DELETE
		FROM PSSCMLIB.PSM_EXAM_INSPECT
		WHERE PEICTEAM = P_PECTEAM
		AND   PEICDATE = P_PECDATE
		AND   PEICSEQ = P_PECSEQ;
  
END P1  ; 
  