--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_AFTER_CHECK;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_AFTER_CHECK
( 
	IN P_TEAM    VARCHAR(6),
	IN P_DATE    VARCHAR(8),
	IN P_SEQ     NUMERIC(3,0)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH MAST AS
		(
			SELECT
				CAST(P_TEAM AS VARCHAR(6)) AS TEAM,
				CAST(P_DATE AS VARCHAR(8)) AS DATE,
				CAST(P_SEQ AS VARCHAR(3)) AS SEQ
			FROM SYSIBM.SYSDUMMY1
		)

		SELECT
			'1' AS GUBUN
		FROM PSSCMLIB.PSM_RISK_MASTER
		LEFT OUTER JOIN MAST
		ON     1 = 1
		WHERE RMWKTEAM = TEAM
		AND   RMWKDATE = DATE
		AND   RMWKSEQ  =  SEQ

		UNION ALL

		SELECT
			'2' AS GUBUN
		FROM PSSCMLIB.PSM_SafeOrder_MASTER
		LEFT OUTER JOIN MAST
		ON     1 = 1
		WHERE SMWKTEAM = TEAM
		AND   SMWKDATE = DATE
		AND   SMWKSEQ  =  SEQ;

	OPEN REFCURSOR;

END;

CALL PSSCMLIB.PSM_PSM4011_AFTER_CHECK('A20000', '20230320', 1);