DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_LIST
( 
	IN P_DRWKTEAM    VARCHAR(6),
	IN P_DRWKDATE    VARCHAR(8),
	IN P_DRWKSEQ     NUMERIC(3,0),
	IN P_DRORAPPDATE VARCHAR(8),
	IN P_DRORSEQ     NUMERIC(3,0)
) 

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- Ω√¿€
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
			DRCODE,
			DRYESSEL,
			DRNOSEL,
			DRNASEL,
			DRSORT,
			DRSTAND,
			DRDEPTH,
			DRSABUN,
			KBHANGL
		FROM PSSCMLIB.PSM_SAFEORDER_DRCODE
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
		ON              DRSABUN = KBSABUN
		WHERE  DRWKTEAM    = P_DRWKTEAM
		AND    DRWKDATE    = P_DRWKDATE
		AND    DRWKSEQ     = P_DRWKSEQ
		AND    DRORAPPDATE = P_DRORAPPDATE
		AND    DRORSEQ     = P_DRORSEQ
		ORDER BY DRCODE;

	OPEN REFCURSOR;
END;