--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_CANCEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_CANCEL
(
	  IN P_WOORTEAM VARCHAR(6),
	  IN P_WOORDATE VARCHAR(8),
	  IN P_WOSEQ    NUMERIC(3,0)
)
LANGUAGE SQL

P1: BEGIN
	
	UPDATE PSSCMLIB.PSM_WORKORDER SET
		WOAPPSODATE1    = '',
		WOAPPSOTIME1    = '',
		WOAPPSODATE2    = '',
		WOAPPSOTIME2    = '',
		WOAPPSODATE3    = '',
		WOAPPSOTIME3    = '',
		WOAPPSODATE4    = '',
		WOAPPSOTIME4    = '',
		WOAPPSODATE5    = '',
		WOAPPSOTIME5    = '',
		WOAPPREDATE1    = '',
		WOAPPRETIME1    = '',
		WOAPPREDATE2    = '',
		WOAPPRETIME2    = '',
		WOAPPREDATE3    = '',
		WOAPPRETIME3    = '',
		WOAPPREDATE4    = '',
		WOAPPRETIME4    = '',
		WOAPPREDATE5    = '',
		WOAPPRETIME5    = ''
	WHERE WOORTEAM = P_WOORTEAM
	AND   WOORDATE = P_WOORDATE
	AND   WOSEQ    = P_WOSEQ;

END P1;