DROP PROCEDURE PSSCMLIB.PSM_PSM4091_EXAM_CHECK_PRT;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4091_EXAM_CHECK_PRT ( 
	IN P_PECTEAM VARCHAR(6) , 
	IN P_PECDATE VARCHAR(8) , 
	IN P_PECSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- ¸¶½ºÅ¸ 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
			PECTITLE , 
			PECTANKNO,
			PECFAULTNM,
			PECIMPROVE,
			CASE WHEN PECINSDATE <> '' THEN SUBSTR ( PECINSDATE , 1 , 4 ) || '-' || SUBSTR ( PECINSDATE , 5 , 2 ) || '-' || SUBSTR ( PECINSDATE , 7 , 2 ) ELSE '' END PECINSDATE , 
			PECDDESC , 
			PECLEVEL , 
			PECCCHECK , 
			CASE WHEN PECDCHECK = 'G' THEN 'Y' ELSE '' END AS PECDCHECK_G , 
			CASE WHEN PECDCHECK = 'F' THEN 'Y' ELSE '' END AS PECDCHECK_F , 
			CASE WHEN PECDCHECK = 'N' THEN 'Y' ELSE '' END AS PECDCHECK_N ,
			PECJKCD1   ,
			PECJKCDNM1 ,
			PECNAME1   ,
			PECSABUN1  ,
			PECDATE1   ,
			PECTIME1   ,
			PECCOMMENT1,
			PECJKCD2   ,
			PECJKCDNM2 ,
			PECNAME2   ,
			PECSABUN2  ,
			PECDATE2   ,
			PECTIME2   ,
			PECCOMMENT2,
			PECJKCD3   ,
			PECJKCDNM3 ,
			PECNAME3   ,
			PECSABUN3  ,
			PECDATE3   ,
			PECTIME3   ,
			PECCOMMENT3,
			PECJKCD4   ,
			PECJKCDNM4 ,
			PECNAME4   ,
			PECSABUN4  ,
			PECDATE4   ,
			PECTIME4   ,
			PECCOMMENT4,
			PECJKCD5   ,
			PECJKCDNM5 ,
			PECNAME5   ,
			PECSABUN5  ,
			PECDATE5   ,
			PECTIME5   ,
			PECCOMMENT5,
			PECJKCD6   ,
			PECJKCDNM6 ,
			PECNAME6   ,
			PECSABUN6  ,
			PECDATE6   ,
			PECTIME6   ,
			PECCOMMENT6,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN1 
			) AS IMGNAME1 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN1 
			) AS IMGSIZE1 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN1 
			) AS IMGSIGN1,  
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN2 
			) AS IMGNAME2 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN2 
			) AS IMGSIZE2 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN2
			) AS IMGSIGN2,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN3 
			) AS IMGNAME3 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN3 
			) AS IMGSIZE3 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN3 
			) AS IMGSIGN3,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN4 
			) AS IMGNAME4 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN4 
			) AS IMGSIZE4 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN4 
			) AS IMGSIGN4,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN5 
			) AS IMGNAME5 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN5 
			) AS IMGSIZE5 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN5 
			) AS IMGSIGN5,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN6 
			) AS IMGNAME6 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN6 
			) AS IMGSIZE6 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = PECSABUN6 
			) AS IMGSIGN6
			/*
			IMG1 . FILE_NAME AS IMGNAME1 , 
			IMG1 . FILE_SIZE AS IMGSIZE1 , 
			IMG1 . ATTACH_BYTE AS IMGSIGN1, 
			IMG2 . FILE_NAME AS IMGNAME2 , 
			IMG2 . FILE_SIZE AS IMGSIZE2 , 
			IMG2 . ATTACH_BYTE AS IMGSIGN2, 
			IMG3 . FILE_NAME AS IMGNAME3 , 
			IMG3 . FILE_SIZE AS IMGSIZE3 , 
			IMG3 . ATTACH_BYTE AS IMGSIGN3, 
			IMG4 . FILE_NAME AS IMGNAME4 , 
			IMG4 . FILE_SIZE AS IMGSIZE4 , 
			IMG4 . ATTACH_BYTE AS IMGSIGN4, 
			IMG5 . FILE_NAME AS IMGNAME5 , 
			IMG5 . FILE_SIZE AS IMGSIZE5 , 
			IMG5 . ATTACH_BYTE AS IMGSIGN5, 
			IMG6 . FILE_NAME AS IMGNAME6 , 
			IMG6 . FILE_SIZE AS IMGSIZE6 , 
			IMG6 . ATTACH_BYTE AS IMGSIGN6 
			*/
			FROM PSSCMLIB . PSM_EXAM_CHECK 
			LEFT OUTER JOIN PSSCMLIB . PSM_EXAM_CHECK_DETAIL 
			ON PECDTCTEAM = PECTEAM 
			AND PECDTCDATE = PECDATE 
			AND PECDTCSEQ = PECSEQ 
			AND PECDGUBUN = PECSGUBUN 
			AND PECDDATE = PECSDATE 
			AND PECDSEQ = PECSSEQ 
			LEFT OUTER JOIN PSSCMLIB . PSM_EXAM_CHECK_CONTENTS 
			ON PECCGUBUN = PECDGUBUN 
			AND PECCDATE = PECDDATE 
			AND PECCSEQ = PECDSEQ 
			AND PECCNUM = PECDNUM 
			/*
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG1 
			ON IMG1 . ATTACH_TYPE = 'SG' 
			AND IMG1 . ATTACH_NO = PECSABUN1 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG2 
			ON IMG2 . ATTACH_TYPE = 'SG' 
			AND IMG2 . ATTACH_NO = PECSABUN2 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG3 
			ON IMG3 . ATTACH_TYPE = 'SG' 
			AND IMG3 . ATTACH_NO = PECSABUN3 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG4 
			ON IMG4 . ATTACH_TYPE = 'SG' 
			AND IMG4 . ATTACH_NO = PECSABUN4 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG5 
			ON IMG5 . ATTACH_TYPE = 'SG' 
			AND IMG5 . ATTACH_NO = PECSABUN5 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG6 
			ON IMG6 . ATTACH_TYPE = 'SG' 
			AND IMG6 . ATTACH_NO = PECSABUN6 
			*/
			WHERE PECTEAM = P_PECTEAM 
			AND PECDATE = P_PECDATE 
			AND PECSEQ = P_PECSEQ 
			ORDER BY PECDNUM ; 
  
		OPEN REFCURSOR ; 
	END P1 ; 
  