--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_ATTACH_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_ATTACH_LIST ( 
	IN P_JSMWKGUBN VARCHAR(1) , 
	IN P_JSMPOTEAM VARCHAR(6) , 
	IN P_JSMPODATE VARCHAR(8) , 
	IN P_JSMPOSEQ NUMERIC(3,0) , 
	IN P_JSMDATE VARCHAR(8) , 
	IN P_JSMMSEQ NUMERIC(3,0) , 
	IN P_JSMBLASS VARCHAR(2) , 
	IN P_JSMMLASS VARCHAR(2) , 
	IN P_JSMSLASS VARCHAR(3) , 
	IN P_JSMSEQ NUMERIC(3,0)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 


LIST : BEGIN  -- 리스트 

		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		ATTACH_NO,
		SUBSTR(ATTACH_NO,40,3) AS SEQ,
		SUBSTR(ATTACH_NO,44) AS GUBUN,
		ATTACH_BYTE
		FROM PSSCMLIB.PSM_CMN_ATTACH
		WHERE ATTACH_TYPE = 'JSA'
		AND    SUBSTR(ATTACH_NO,1,1) = P_JSMWKGUBN
		AND    SUBSTR(ATTACH_NO,2,6) = P_JSMPOTEAM
		AND    SUBSTR(ATTACH_NO,8,8) = P_JSMPODATE
		AND    CAST  (SUBSTR(ATTACH_NO,16,3) AS NUMERIC(3 , 0)) = P_JSMPOSEQ
		AND    SUBSTR(ATTACH_NO,19,8) = P_JSMDATE
		AND    CAST  (SUBSTR(ATTACH_NO,27,3) AS NUMERIC(3 , 0)) = P_JSMMSEQ
		AND    SUBSTR(ATTACH_NO,30,2) = P_JSMBLASS
		AND    SUBSTR(ATTACH_NO,32,2) = P_JSMMLASS
		AND    SUBSTR(ATTACH_NO,34,3) = P_JSMSLASS
		AND    CAST  (SUBSTR(ATTACH_NO,37,3) AS NUMERIC(3 , 0)) = P_JSMSEQ 
		ORDER BY ATTACH_NO
			 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 