--DROP PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_CANCEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_CANCEL
(
	IN P_CRREVTEAM      VARCHAR(6),    -- 변경검토번호(팀)
	IN P_CRREVDATE      VARCHAR(8),    -- 변경검토번호(일자)
	IN P_CRREVSEQ       NUMERIC(3,0)   -- 변경검토번호(순번)
)
LANGUAGE SQL

P1: BEGIN

	UPDATE PSSCMLIB.PSM_CHANGEREV_DOC SET
		CRREVDATE1    = '',
		CRREVTIME1    = '',
		CRREVDATE2    = '',
		CRREVTIME2    = '',
		CRREVDATE3    = '',
		CRREVTIME3    = '',
		CRREVDATE4    = '',
		CRREVTIME4    = '',
		CRREVDATE5    = '',
		CRREVTIME5    = '',
		CRREVDATE6    = '',
		CRREVTIME6    = ''
	WHERE CRREVTEAM = P_CRREVTEAM
	AND   CRREVDATE = P_CRREVDATE
	AND   CRREVSEQ  = P_CRREVSEQ;

END P1;