--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_DEL
(
	  IN P_WOORTEAM VARCHAR(6),
	  IN P_WOORDATE VARCHAR(8),
	  IN P_WOSEQ    NUMERIC(3,0)
)
LANGUAGE SQL

P1: BEGIN
	
	DELETE FROM PSSCMLIB.PSM_WorkOrder
	WHERE WOORTEAM = P_WOORTEAM
	AND   WOORDATE = P_WOORDATE
	AND   WOSEQ    = P_WOSEQ;

END P1;