--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_SEQ ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_SEQ ( 
	IN P_PECCGUBUN VARCHAR(1),
	IN P_PECCDATE VARCHAR(8)) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_SEQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT   VALUE(MAX(PECCSEQ), 0) + 1 AS PECCSEQ
			FROM PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
			WHERE PECCGUBUN = P_PECCGUBUN
			  AND PECCDATE = P_PECCDATE  ;
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 