--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_APPROVAL_UPT;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_APPROVAL_UPT ( 
	IN P_SMWKTEAM      VARCHAR(6) , 
	IN P_SMWKDATE      VARCHAR(8) , 
	IN P_SMWKSEQ       NUMERIC(3, 0),
	IN P_SMWKORAPPDATE VARCHAR(8) , 
	IN P_SMWKORSEQ     NUMERIC(3, 0),
	IN P_APPROVALSITE  VARCHAR(1)
) 
LANGUAGE SQL 

P1 : BEGIN 
	 
	IF P_APPROVALSITE = '' THEN
		-- 요청자 결재
		UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
			SMORAPPDATE = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ),
			SMORAPPTIME = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' )
		WHERE SMWKTEAM      = P_SMWKTEAM
		AND   SMWKDATE      = P_SMWKDATE
		AND   SMWKSEQ       = P_SMWKSEQ
		AND   SMWKORAPPDATE = P_SMWKORAPPDATE
		AND   SMWKORSEQ     = P_SMWKORSEQ;

	ELSEIF P_APPROVALSITE = '1' THEN

		-- 승인자 결재
		UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
			SMGRAPPDATE = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ),
			SMGRAPPTIME = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' )
		WHERE SMWKTEAM      = P_SMWKTEAM
		AND   SMWKDATE      = P_SMWKDATE
		AND   SMWKSEQ       = P_SMWKSEQ
		AND   SMWKORAPPDATE = P_SMWKORAPPDATE
		AND   SMWKORSEQ     = P_SMWKORSEQ;

	ELSEIF P_APPROVALSITE = '2' THEN

		-- 감독자 결재
		UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
			SMTATIME1   = SUBSTR(REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ),1,4),
			SMCOAPPDATE = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ),
			SMCOAPPTIME = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' )
		WHERE SMWKTEAM      = P_SMWKTEAM
		AND   SMWKDATE      = P_SMWKDATE
		AND   SMWKSEQ       = P_SMWKSEQ
		AND   SMWKORAPPDATE = P_SMWKORAPPDATE
		AND   SMWKORSEQ     = P_SMWKORSEQ;

	END IF;

END P1;