--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_RUN ( 
	IN P_SMWKTEAM VARCHAR(6) , 
	IN P_SMWKDATE VARCHAR(8) , 
	IN P_SMWKSEQ NUMERIC(3, 0) , 
	IN P_SMWKORAPPDATE VARCHAR(8) , 
	IN P_SMWKORSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_RUN 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
		 
		SELECT 
			SMREVTEAM , 
			TYSCMLIB . SF_GB_ORGNAME ( SMREVTEAM , CAST ( SMWKORAPPDATE AS VARCHAR ( 8 ) ) ) AS SMREVTEAMNM , 
			SMWKMETHOD , 
			SMWORKTITLE , 
			SMFIREINS , 
			SMSUBVEND , 
			SMSUBPERSON , 
			SMSUBTEL , 
			SMRESSABUN , 
			SMWKMAN , 
			SMTADATE1 , 
			SUBSTR ( SMTATIME1 , 1 , 2 ) AS SMTATIME1_HH , 
			SUBSTR ( SMTATIME1 , 3 , 2 ) AS SMTATIME1_MM , 
			SMTADATE2 , 
			SUBSTR ( SMTATIME2 , 1 , 2 ) AS SMTATIME2_HH , 
			SUBSTR ( SMTATIME2 , 3 , 2 ) AS SMTATIME2_MM , 
			SMOTDATE1 , 
			SUBSTR ( SMOTTIME1 , 1 , 2 ) AS SMOTTIME1_HH , 
			SUBSTR ( SMOTTIME1 , 3 , 2 ) AS SMOTTIME1_MM , 
			SMOTDATE2 , 
			SUBSTR ( SMOTTIME2 , 1 , 2 ) AS SMOTTIME2_HH , 
			SUBSTR ( SMOTTIME2 , 3 , 2 ) AS SMOTTIME2_MM , 
			SMOTAPPSABUN , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMOTAPPSABUN ) AS SMOTAPPSABUNNM , 
			SMSYSTEMCODE1 , 
			( CASE WHEN SMSYSTEMCODE1 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMSYSTEMCODE1 ) ELSE '' END ) AS SMSYSTEMCODE1NM , 
			SMSYSTEMCODE2 , 
			( CASE WHEN SMSYSTEMCODE2 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMSYSTEMCODE2 ) ELSE '' END ) AS SMSYSTEMCODE2NM , 
			SMSYSTEMCODE3 , 
			( CASE WHEN SMSYSTEMCODE3 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMSYSTEMCODE3 ) ELSE '' END ) AS SMSYSTEMCODE3NM , 
			SMSYSTEMCODE4 , 
			( CASE WHEN SMSYSTEMCODE4 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMSYSTEMCODE4 ) ELSE '' END ) AS SMSYSTEMCODE4NM , 
			SMSYSTEMCODE5 , 
			( CASE WHEN SMSYSTEMCODE5 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMSYSTEMCODE5 ) ELSE '' END ) AS SMSYSTEMCODE5NM , 
			SMCONNCODE11 , 
			( CASE WHEN SMCONNCODE11 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE11 ) ELSE '' END ) AS SMCONNCODE11NM , 
			SMCONNCODE12 , 
			( CASE WHEN SMCONNCODE12 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE12 ) ELSE '' END ) AS SMCONNCODE12NM , 
			SMCONNCODE21 , 
			( CASE WHEN SMCONNCODE21 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE21 ) ELSE '' END ) AS SMCONNCODE21NM , 
			SMCONNCODE22 , 
			( CASE WHEN SMCONNCODE22 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE22 ) ELSE '' END ) AS SMCONNCODE22NM , 
			SMCONNCODE31 , 
			( CASE WHEN SMCONNCODE31 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE31 ) ELSE '' END ) AS SMCONNCODE31NM , 
			SMCONNCODE32 , 
			( CASE WHEN SMCONNCODE32 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE32 ) ELSE '' END ) AS SMCONNCODE32NM , 
			SMCONNCODE41 , 
			( CASE WHEN SMCONNCODE41 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE41 ) ELSE '' END ) AS SMCONNCODE41NM , 
			SMCONNCODE42 , 
			( CASE WHEN SMCONNCODE42 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE42 ) ELSE '' END ) AS SMCONNCODE42NM , 
			SMCONNCODE51 , 
			( CASE WHEN SMCONNCODE51 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE51 ) ELSE '' END ) AS SMCONNCODE51NM , 
			SMCONNCODE52 , 
			( CASE WHEN SMCONNCODE52 <> '' THEN PSSCMLIB . SF_PSM_LOCATION_NAME ( SMCONNCODE52 ) ELSE '' END ) AS SMCONNCODE52NM , 
			SMAREACODE1 , 
			( CASE WHEN SMAREACODE1 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( SMAREACODE1 ) ELSE '' END ) AS SMAREACODE1NM , 
			SMAREACODE2 , 
			( CASE WHEN SMAREACODE2 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( SMAREACODE2 ) ELSE '' END ) AS SMAREACODE2NM , 
			SMAREACODE3 , 
			( CASE WHEN SMAREACODE3 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( SMAREACODE3 ) ELSE '' END ) AS SMAREACODE3NM , 
			SMAREACODE4 , 
			( CASE WHEN SMAREACODE4 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( SMAREACODE4 ) ELSE '' END ) AS SMAREACODE4NM , 
			SMAREACODE5 ,			 
			( CASE WHEN SMAREACODE5 <> '' THEN PSSCMLIB . SF_PSM_AREA_NAME ( SMAREACODE5 ) ELSE '' END ) AS SMAREACODE5NM , 
			SMAREATEXT1 , 
			SMAREATEXT2 , 
			SMAREATEXT3 , 
			SMAREATEXT4 , 
			SMAREATEXT5 , 
			SMMATERTEXT1 , 
			SMMATERTEXT2 , 
			SMNOTE_BURN , 
			SMNOTE_SUFF , 
			SMNOTE_ELE , 
			SMNOTE_FIR , 
			SMNOTE_EXP , 
			SMNOTE_DROP , 
			SMNOTE_LEAK , 
			SMNOTE_NARR , 
			SMNOTE_COLL , 
			SMCHKSABUN1 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN1 ) AS SMCHKSABUN1NM , 
			SUBSTR ( SMCHKTIME1 , 1 , 2 ) AS SMCHKTIME1_HH , 
			SUBSTR ( SMCHKTIME1 , 3 , 2 ) AS SMCHKTIME1_MM , 
			SMCHKOXYGEN1 , 
			SMCHKOXYGENUNIT1 , 
			SMCHKTOXNUM1 , 
			SMCHKTOXUNIT1 , 
			SMCHKTOXNUM1DS , 
			SMCHKTOXUNIT1DS , 
			SMCHKTOXNUM1CO2 , 
			SMCHKTOXUNIT1CO2 , 
			SMCHKTOXNUM1CO , 
			SMCHKTOXUNIT1CO , 
			SMCHKTOXNUM1H2S , 
			SMCHKTOXUNIT1H2S , 
			SMCHKSABUN2 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN2 ) AS SMCHKSABUN2NM , 
			SUBSTR ( SMCHKTIME2 , 1 , 2 ) AS SMCHKTIME2_HH , 
			SUBSTR ( SMCHKTIME2 , 3 , 2 ) AS SMCHKTIME2_MM , 
			SMCHKOXYGEN2 , 
			SMCHKOXYGENUNIT2 , 
			SMCHKTOXNUM2 , 
			SMCHKTOXUNIT2 , 
			SMCHKTOXNUM2DS , 
			SMCHKTOXUNIT2DS , 
			SMCHKTOXNUM2CO2 , 
			SMCHKTOXUNIT2CO2 , 
			SMCHKTOXNUM2CO , 
			SMCHKTOXUNIT2CO , 
			SMCHKTOXNUM2H2S , 
			SMCHKTOXUNIT2H2S , 
			SMCHKSABUN3 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN3 ) AS SMCHKSABUN3NM , 
			SUBSTR ( SMCHKTIME3 , 1 , 2 ) AS SMCHKTIME3_HH , 
			SUBSTR ( SMCHKTIME3 , 3 , 2 ) AS SMCHKTIME3_MM , 
			SMCHKOXYGEN3 , 
			SMCHKOXYGENUNIT3 , 
			SMCHKTOXNUM3 , 
			SMCHKTOXUNIT3 , 
			SMCHKTOXNUM3DS , 
			SMCHKTOXUNIT3DS , 
			SMCHKTOXNUM3CO2 , 
			SMCHKTOXUNIT3CO2 , 
			SMCHKTOXNUM3CO , 
			SMCHKTOXUNIT3CO , 
			SMCHKTOXNUM3H2S , 
			SMCHKTOXUNIT3H2S , 
			SMCHKSABUN4 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN4 ) AS SMCHKSABUN4NM , 
			SUBSTR ( SMCHKTIME4 , 1 , 2 ) AS SMCHKTIME4_HH , 
			SUBSTR ( SMCHKTIME4 , 3 , 2 ) AS SMCHKTIME4_MM , 
			SMCHKOXYGEN4 , 
			SMCHKOXYGENUNIT4 , 
			SMCHKTOXNUM4 , 
			SMCHKTOXUNIT4 , 
			SMCHKTOXNUM4DS , 
			SMCHKTOXUNIT4DS , 
			SMCHKTOXNUM4CO2 , 
			SMCHKTOXUNIT4CO2 , 
			SMCHKTOXNUM4CO , 
			SMCHKTOXUNIT4CO , 
			SMCHKTOXNUM4H2S , 
			SMCHKTOXUNIT4H2S , 
			SMCHKSABUN5 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN5 ) AS SMCHKSABUN5NM , 
			SUBSTR ( SMCHKTIME5 , 1 , 2 ) AS SMCHKTIME5_HH , 
			SUBSTR ( SMCHKTIME5 , 3 , 2 ) AS SMCHKTIME5_MM , 
			SMCHKOXYGEN5 , 
			SMCHKOXYGENUNIT5 , 
			SMCHKTOXNUM5 , 
			SMCHKTOXUNIT5 , 
			SMCHKTOXNUM5DS , 
			SMCHKTOXUNIT5DS , 
			SMCHKTOXNUM5CO2 , 
			SMCHKTOXUNIT5CO2 , 
			SMCHKTOXNUM5CO , 
			SMCHKTOXUNIT5CO , 
			SMCHKTOXNUM5H2S , 
			SMCHKTOXUNIT5H2S , 
			SMCHKSABUN6 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN6 ) AS SMCHKSABUN6NM , 
			SUBSTR ( SMCHKTIME6 , 1 , 2 ) AS SMCHKTIME6_HH , 
			SUBSTR ( SMCHKTIME6 , 3 , 2 ) AS SMCHKTIME6_MM , 
			SMCHKOXYGEN6 , 
			SMCHKOXYGENUNIT6 , 
			SMCHKTOXNUM6 , 
			SMCHKTOXUNIT6 , 
			SMCHKTOXNUM6DS , 
			SMCHKTOXUNIT6DS , 
			SMCHKTOXNUM6CO2 , 
			SMCHKTOXUNIT6CO2 , 
			SMCHKTOXNUM6CO , 
			SMCHKTOXUNIT6CO , 
			SMCHKTOXNUM6H2S , 
			SMCHKTOXUNIT6H2S , 
			SMCHKSABUN7 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN7 ) AS SMCHKSABUN7NM , 
			SUBSTR ( SMCHKTIME7 , 1 , 2 ) AS SMCHKTIME7_HH , 
			SUBSTR ( SMCHKTIME7 , 3 , 2 ) AS SMCHKTIME7_MM , 
			SMCHKOXYGEN7 , 
			SMCHKOXYGENUNIT7 , 
			SMCHKTOXNUM7 , 
			SMCHKTOXUNIT7 , 
			SMCHKTOXNUM7DS , 
			SMCHKTOXUNIT7DS , 
			SMCHKTOXNUM7CO2 , 
			SMCHKTOXUNIT7CO2 , 
			SMCHKTOXNUM7CO , 
			SMCHKTOXUNIT7CO , 
			SMCHKTOXNUM7H2S , 
			SMCHKTOXUNIT7H2S , 
			SMCHKSABUN8 , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCHKSABUN8 ) AS SMCHKSABUN8NM , 
			SUBSTR ( SMCHKTIME8 , 1 , 2 ) AS SMCHKTIME8_HH , 
			SUBSTR ( SMCHKTIME8 , 3 , 2 ) AS SMCHKTIME8_MM , 
			SMCHKOXYGEN8 , 
			SMCHKOXYGENUNIT8 , 
			SMCHKTOXNUM8 , 
			SMCHKTOXUNIT8 , 
			SMCHKTOXNUM8DS , 
			SMCHKTOXUNIT8DS , 
			SMCHKTOXNUM8CO2 , 
			SMCHKTOXUNIT8CO2 , 
			SMCHKTOXNUM8CO , 
			SMCHKTOXUNIT8CO , 
			SMCHKTOXNUM8H2S , 
			SMCHKTOXUNIT8H2S , 
			SMORDERTEXT1 , 
			SMORDERTEXT2 , 
			SMORSABUN , 
			SMORNAME , 
			SMORJKCD , 
			SMORJKCDNM , 
			SMORAPPDATE , 
			SMORAPPTIME , 
			SMGRSABUN , 
			SMGRNAME , 
			SMGRJKCD , 
			SMGRJKCDNM , 
			SMGRAPPDATE , 
			SMGRAPPTIME , 
			SMCOSABUN , 
			SMCONAME , 
			SMCOJKCD , 
			SMCOJKCDNM , 
			SMCOAPPDATE , 
			SMCOAPPTIME , 
			SMSMSABUN , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMSMSABUN ) AS SMSMSABUNNM , 
			SMSMNAME , 
			SMSMJKCD , 
			SMSMJKCDNM , 
			SMSMAPPDATE , 
			SMSMAPPTIME , 
			SMFSSABUN , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMFSSABUN ) AS SMFSSABUNNM , 
			SMFSDATE , 
			SMFSTIME , 
			KIBN . KBHANGL , 
			SMSMCOMMENT , 
			CASE WHEN SMFSWKCLOSE <> 'Y' THEN 'N' ELSE 'Y' END AS SMFSWKCLOSE , 
			SMFSWKTEXT , 
			WOWORKTITLE , 
			SMCHKTOXGUBN1 , 
			SMCHKTOXGUBN2 , 
			SMCHKTOXGUBN3 , 
			SMCHKTOXGUBN4 , 
			SMCHKTOXGUBN5 , 
			SMCHKTOXGUBN6 , 
			SMCNSABUN , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCNSABUN ) AS SMCNSABUNNM , 
			SMCNDATE , 
			SMCNTIME , 
			SMCNREASON , 
			SMOPSABUN , 
			( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMOPSABUN ) AS SMOPSABUNNM , 
			SMOPNAME , 
			SMOPJKCD , 
			SMOPJKCDNM , 
			SMOPAPPDATE , 
			SMOPAPPTIME , 
			SMOPCOMMENT , 
			KIBN1 . KBHANGL AS SMOPHANGL , 
			/* 사인 */ 
			(SELECT
				FILE_NAME
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMORSABUN
			) AS ORIMGNAME, 
			(SELECT
				FILE_SIZE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMORSABUN
			) AS ORIMGSIZE, 
			(SELECT
				ATTACH_BYTE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMORSABUN
			) AS ORIMGSIGN,

			(SELECT
				FILE_NAME
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMGRSABUN
			) AS GRIMGNAME, 
			(SELECT
				FILE_SIZE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMGRSABUN
			) AS GRIMGSIZE, 
			(SELECT
				ATTACH_BYTE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMGRSABUN
			) AS GRIMGSIGN, 

			(SELECT
				FILE_NAME
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMCOSABUN
			) AS COIMGNAME, 
			(SELECT
				FILE_SIZE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMCOSABUN
			) AS COIMGSIZE, 
			(SELECT
				ATTACH_BYTE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMCOSABUN
			) AS COIMGSIGN
		FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
		LEFT OUTER JOIN PSSCMLIB . PSM_WORKORDER 
		ON WOORTEAM = SMWKTEAM 
		AND WOORDATE = SMWKDATE 
		AND WOSEQ = SMWKSEQ 
		LEFT OUTER JOIN TYSCMLIB . INKIBNMF AS KIBN 
		ON '2' = KIBN . KBCOMPANY 
		AND SMSMSABUN = KIBN . KBSABUN 
		LEFT OUTER JOIN TYSCMLIB . INKIBNMF AS KIBN1 
		ON '2' = KIBN1 . KBCOMPANY 
		AND SMOPSABUN = KIBN1 . KBSABUN 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L1 
			ON L1 . L3SAUP || L1 . L3BCODE || DIGITS ( L1 . L3MCODE ) || DIGITS ( L1 . L3SCODE ) = SMAREACODE1 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L2 
			ON L2 . L3SAUP || L2 . L3BCODE || DIGITS ( L2 . L3MCODE ) || DIGITS ( L2 . L3SCODE ) = SMAREACODE2 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L3 
			ON L3 . L3SAUP || L3 . L3BCODE || DIGITS ( L3 . L3MCODE ) || DIGITS ( L3 . L3SCODE ) = SMAREACODE3 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L4 
			ON L4 . L3SAUP || L4 . L3BCODE || DIGITS ( L4 . L3MCODE ) || DIGITS ( L4 . L3SCODE ) = SMAREACODE4 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L5 
			ON L5 . L3SAUP || L5 . L3BCODE || DIGITS ( L5 . L3MCODE ) || DIGITS ( L5 . L3SCODE ) = SMAREACODE5 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT1 
		ON SMSYSTEMCODE1 = LCT1 . FXC3SAUP || LCT1 . FXC3BCODE || DIGITS ( LCT1 . FXC3MCODE ) || DIGITS ( LCT1 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT2 
		ON SMSYSTEMCODE2 = LCT2 . FXC3SAUP || LCT2 . FXC3BCODE || DIGITS ( LCT2 . FXC3MCODE ) || DIGITS ( LCT2 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT3 
		ON SMSYSTEMCODE3 = LCT3 . FXC3SAUP || LCT3 . FXC3BCODE || DIGITS ( LCT3 . FXC3MCODE ) || DIGITS ( LCT3 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT4 
		ON SMSYSTEMCODE4 = LCT4 . FXC3SAUP || LCT4 . FXC3BCODE || DIGITS ( LCT4 . FXC3MCODE ) || DIGITS ( LCT4 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT5 
		ON SMSYSTEMCODE5 = LCT5 . FXC3SAUP || LCT5 . FXC3BCODE || DIGITS ( LCT5 . FXC3MCODE ) || DIGITS ( LCT5 . FXC3SCODE ) 
  
		WHERE SMWKTEAM = P_SMWKTEAM 
		AND SMWKDATE = P_SMWKDATE 
		AND SMWKSEQ = P_SMWKSEQ 
		AND SMWKORAPPDATE = P_SMWKORAPPDATE 
		AND SMWKORSEQ = P_SMWKORSEQ ; 
	 
	OPEN REFCURSOR;

END;