--DROP PROCEDURE PSSCMLIB.PSM_OutSideConstruct_WKCODE_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_OutSideConstruct_WKCODE_DEL
(
	P_OSWKDATE	VARCHAR(8)    ,
	P_OSWKSEQ	NUMERIC(3, 0) 
	
)
	LANGUAGE SQL
P1: BEGIN
	

	DELETE FROM PSSCMLIB.PSM_OutSideConstruct_WKCODE		
		WHERE OSWKDATE = P_OSWKDATE
		  AND OSWKSEQ  = P_OSWKSEQ;
		  

END P1