DROP PROCEDURE PSSCMLIB.PSM_PSM4048_JSACHANGE_CREATE;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4048_JSACHANGE_CREATE ( 
	IN P_JSLWKGUBN VARCHAR(1) , 
	IN P_JSLWKTEAM VARCHAR (6) ,
	IN P_JSLWKDATE VARCHAR(8) , 
	IN P_JSLWKSEQ NUMERIC(3,0), 
	IN P_JSLDATE VARCHAR(8) , 
	IN P_JSMBLASS VARCHAR(2) , 
	IN P_JSMMLASS VARCHAR(2) , 
	IN P_JSMSLASS VARCHAR(3), 
	IN P_JSMSEQ NUMERIC(3,0), 
	IN P_JSLHISAB VARCHAR(6)) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4048_JSACHANGE_CREATE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 

	DECLARE V_JSLSEQ	NUMERIC ( 3, 0 ) ; 
	 
	-- 순번 생성
	SELECT VALUE(MAX(JSLSEQ),0) + 1 INTO V_JSLSEQ
	FROM PSSCMLIB.PSM_JSALOG_MASTER
	WHERE JSLWKGUBN = P_JSLWKGUBN
	AND JSLWKTEAM = P_JSLWKTEAM
	AND JSLWKDATE = P_JSLWKDATE
	AND JSLWKSEQ = P_JSLWKSEQ
	AND JSLDATE = P_JSLDATE ;

	-- JSA(변경관리) 작성 마스터 복사
	INSERT INTO PSSCMLIB.PSM_JSALOG_MASTER
	(
	JSLWKGUBN,
	JSLWKTEAM,
	JSLWKDATE,
	JSLWKSEQ,
	JSLDATE,
	JSLSEQ,
	JSLWRSABUN,
	JSLENDDATE,
	JSLENDTIME,
	JSLHIGB,
	JSLHIDAT,
	JSLHITIM,
	JSLHISAB
	)
	VALUES
	(
	P_JSLWKGUBN,
	P_JSLWKTEAM,
	P_JSLWKDATE,
	P_JSLWKSEQ,
	P_JSLDATE,
	V_JSLSEQ,
	P_JSLHISAB,
	REPLACE(CHAR(CURRENT_DATE),'-',''),
	REPLACE(CHAR(CURRENT_TIME),'.',''),
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_JSLHISAB
	);

	-- JSA(변경관리) 마스터 복사
	INSERT INTO PSSCMLIB.PSM_JSACHANGE_MASTER
	(
	JSMWKGUBN,
	JSMPOTEAM,
	JSMPODATE,
	JSMPOSEQ,
	JSMDATE,
	JSMMSEQ,
	JSMBLASS     ,
	JSMMLASS     ,
	JSMSLASS     ,
	JSMSEQ       ,
	JSMWKNAME    ,
	JSMSYSTEM    ,
	JSMWKDATE    ,
	JSMADDATE    ,
	JSMADCHASU   ,
	JSMWKSABUN   ,
	JSMSANAME    ,
	JSMSECTIONNUM,
	JSMMSDSCODE  ,
	JSMMSDSSEQ   ,
	JSMWKSUMMARY ,
	JSMNEEDDATA  ,
	JSMRISKCASE  ,
	JSMSELFNAME1 ,
	JSMSELFTEXT1 ,
	JSMSELFNAME2 ,
	JSMSELFTEXT2 ,
	JSMSELFNAME3 ,
	JSMSELFTEXT3 ,
	JSMSELFNAME4 ,
	JSMSELFTEXT4 ,
	JSMSELFNAME5 ,
	JSMSELFTEXT5 ,
	JSMSCOMNAME1 ,
	JSMSCOMTEXT1 ,
	JSMSCOMNAME2 ,
	JSMSCOMTEXT2 ,
	JSMHIGB      ,
	JSMHIDAT     ,
	JSMHITIM     ,
	JSMHISAB
	)
	SELECT
	P_JSLWKGUBN,
	P_JSLWKTEAM,
	P_JSLWKDATE,
	P_JSLWKSEQ,
	P_JSLDATE,
	V_JSLSEQ,
	JSMBLASS     ,
	JSMMLASS     ,
	JSMSLASS     ,
	JSMSEQ       ,
	JSMWKNAME    ,
	JSMSYSTEM    ,
	JSMWKDATE    ,
	JSMADDATE    ,
	JSMADCHASU   ,
	JSMWKSABUN   ,
	JSMSANAME    ,
	JSMSECTIONNUM,
	JSMMSDSCODE  ,
	JSMMSDSSEQ   ,
	JSMWKSUMMARY ,
	JSMNEEDDATA  ,
	JSMRISKCASE  ,
	JSMSELFNAME1 ,
	JSMSELFTEXT1 ,
	JSMSELFNAME2 ,
	JSMSELFTEXT2 ,
	JSMSELFNAME3 ,
	JSMSELFTEXT3 ,
	JSMSELFNAME4 ,
	JSMSELFTEXT4 ,
	JSMSELFNAME5 ,
	JSMSELFTEXT5 ,
	JSMSCOMNAME1 ,
	JSMSCOMTEXT1 ,
	JSMSCOMNAME2 ,
	JSMSCOMTEXT2 ,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_JSLHISAB
	FROM PSSCMLIB.PSM_JSA_MASTER
	WHERE JSMBLASS  = P_JSMBLASS
	AND    JSMMLASS = P_JSMMLASS
	AND    JSMSLASS  = P_JSMSLASS
	AND    JSMSEQ     = P_JSMSEQ ;

	-- JSA(변경관리) 마스터 안전장비 복사
	INSERT INTO PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
	(
	JSTWKGUBN,
	JSTPOTEAM,
	JSTPODATE,
	JSTPOSEQ,
	JSTDATE,
	JSTMSEQ,
	JSTBLASS,
	JSTMLASS,
	JSTSLASS,
	JSTSEQ,
	JSTINDX,
	JSTCODEGUBN,
	JSTSAFECODE,
	JSTSAFENAME,
	JSTHIGB,
	JSTHIDAT,
	JSTHITIM,
	JSTHISAB
	)
	SELECT
	P_JSLWKGUBN,
	P_JSLWKTEAM,
	P_JSLWKDATE,
	P_JSLWKSEQ,
	P_JSLDATE,
	V_JSLSEQ,
	JSTBLASS,
	JSTMLASS,
	JSTSLASS,
	JSTSEQ,
	JSTINDX,
	JSTCODEGUBN,
	JSTSAFECODE,
	JSTSAFENAME,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_JSLHISAB
	FROM PSSCMLIB.PSM_JSA_MSAFETOOL
	WHERE JSTBLASS = P_JSMBLASS
	AND   JSTMLASS = P_JSMMLASS
	AND   JSTSLASS = P_JSMSLASS
	AND   JSTSEQ   = P_JSMSEQ ;

	-- JSA(변경관리) 디테일 복사
	INSERT INTO PSSCMLIB.PSM_JSACHANGE_DETAIL
	(
	JSDWKGUBN,
	JSDPOTEAM,
	JSDPODATE,
	JSDPOSEQ,
	JSDDATE,
	JSDMSEQ,
	JSDBLASS,
	JSDMLASS,
	JSDSLASS,
	JSDSEQ,
	JSDITEMSEQ,
	JSDITEMTEXT,
	JSDTOOLTEXT,
	JSDHIGB,
	JSDHIDAT,
	JSDHITIM,
	JSDHISAB
	)
	SELECT
	P_JSLWKGUBN,
	P_JSLWKTEAM,
	P_JSLWKDATE,
	P_JSLWKSEQ,
	P_JSLDATE,
	V_JSLSEQ,
	JSDBLASS,
	JSDMLASS,
	JSDSLASS,
	JSDSEQ,
	JSDITEMSEQ,
	JSDITEMTEXT,
	JSDTOOLTEXT,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_JSLHISAB
	FROM PSSCMLIB.PSM_JSA_DETAIL
	WHERE JSDBLASS   = P_JSMBLASS
	AND   JSDMLASS   = P_JSMMLASS
	AND   JSDSLASS   = P_JSMSLASS
	AND   JSDSEQ     = P_JSMSEQ ;

	-- JSA(변경관리) 위험성 복사
	INSERT INTO PSSCMLIB.PSM_JSACHANGE_RISK
	(
	JSRWKGUBN,
	JSRPOTEAM,
	JSRPODATE,
	JSRPOSEQ,
	JSRDATE,
	JSRMSEQ,
	JSRBLASS,
	JSRMLASS,
	JSRSLASS,
	JSRSEQ,
	JSRITEMSEQ,
	JSRSUBSEQ,
	JSRRISKTEXT,
	JSRRISKCNT,
	JSRRISKSOLID,
	JSRRISKDEGREE,
	JSRHIGB,
	JSRHIDAT,
	JSRHITIM,
	JSRHISAB
	)
	SELECT
	P_JSLWKGUBN,
	P_JSLWKTEAM,
	P_JSLWKDATE,
	P_JSLWKSEQ,
	P_JSLDATE,
	V_JSLSEQ,
	JSRBLASS,
	JSRMLASS,
	JSRSLASS,
	JSRSEQ,
	JSRITEMSEQ,
	JSRSUBSEQ,
	JSRRISKTEXT,
	JSRRISKCNT,
	JSRRISKSOLID,
	JSRRISKDEGREE,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_JSLHISAB
	FROM PSSCMLIB.PSM_JSA_RISK
	WHERE JSRBLASS = P_JSMBLASS
	AND   JSRMLASS = P_JSMMLASS
	AND   JSRSLASS = P_JSMSLASS
	AND   JSRSEQ   = P_JSMSEQ ;

	-- JSA(변경관리) 개선대책 복사
	INSERT INTO PSSCMLIB.PSM_JSACHANGE_REFORM
	(
	JSEWKGUBN,
	JSEPOTEAM,
	JSEPODATE,
	JSEPOSEQ,
	JSEDATE,
	JSEMSEQ,
	JSEBLASS,
	JSEMLASS,
	JSESLASS,
	JSESEQ,
	JSEITEMSEQ,
	JSESUBSEQ,
	JSEREFORMTEXT,
	JSEREFORMCNT,
	JSEREFORMSOLID,
	JSEREFORMDEGREE,
	JSEHIGB,
	JSEHIDAT,
	JSEHITIM,
	JSEHISAB
	)
	SELECT
	P_JSLWKGUBN,
	P_JSLWKTEAM,
	P_JSLWKDATE,
	P_JSLWKSEQ,
	P_JSLDATE,
	V_JSLSEQ,
	JSEBLASS,
	JSEMLASS,
	JSESLASS,
	JSESEQ,
	JSEITEMSEQ,
	JSESUBSEQ,
	JSEREFORMTEXT,
	JSEREFORMCNT,
	JSEREFORMSOLID,
	JSEREFORMDEGREE,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_JSLHISAB
	FROM PSSCMLIB.PSM_JSA_REFORM
	WHERE JSEBLASS = P_JSMBLASS
	AND   JSEMLASS = P_JSMMLASS
	AND   JSESLASS = P_JSMSLASS
	AND   JSESEQ   = P_JSMSEQ ;

	-- 첨부파일 복사
	INSERT INTO PSSCMLIB.PSM_CMN_ATTACH
	(
	ATTACH_TYPE,
	ATTACH_NO,
	ATTACH_UNID,
	FILE_NAME,
	FILE_SIZE,
	FILE_MIME,
	FILE_EXT,
	FILE_PATH,
	UPLOAD_PATH,
	ATTACH_BYTE
	)
	SELECT
	ATTACH_TYPE,
	P_JSLWKGUBN || P_JSLWKTEAM || P_JSLWKDATE || DIGITS(P_JSLWKSEQ) || P_JSLDATE || DIGITS(V_JSLSEQ) || ATTACH_NO AS ATTACH_NO,
	ATTACH_UNID,
	FILE_NAME,
	FILE_SIZE,
	FILE_MIME,
	FILE_EXT,
	FILE_PATH,
	UPLOAD_PATH,
	ATTACH_BYTE
	FROM PSSCMLIB . PSM_CMN_ATTACH
	WHERE ATTACH_TYPE = 'JSA'
	AND    SUBSTR(ATTACH_NO,1,2) = P_JSMBLASS
	AND    SUBSTR(ATTACH_NO,3,2) = P_JSMMLASS
	AND    SUBSTR(ATTACH_NO,5,3) = P_JSMSLASS
	AND    CAST(SUBSTR(ATTACH_NO,8,3) AS NUMERIC(3, 0)) = P_JSMSEQ ;

  
END P1  ; 