DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_EXTENSION_UPT;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_EXTENSION_UPT
(
	IN P_SMOTDATE1        VARCHAR(8),
	IN P_SMOTTIME1        VARCHAR(4),
	IN P_SMOTDATE2        VARCHAR(8),
	IN P_SMOTTIME2        VARCHAR(4),
	IN P_SMOTAPPSABUN     VARCHAR(6),
	IN P_SMWKTEAM         VARCHAR(6),
    IN P_SMWKDATE         VARCHAR(8),
	IN P_SMWKSEQ          NUMERIC(3,0),
	IN P_SMWKORAPPDATE    VARCHAR(8),
	IN P_SMWKORSEQ        NUMERIC(3,0)
)
	
LANGUAGE SQL

P1: BEGIN

	UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
		SMOTDATE1    = P_SMOTDATE1,
		SMOTTIME1    = P_SMOTTIME1,
		SMOTDATE2    = P_SMOTDATE2,
		SMOTTIME2    = P_SMOTTIME2,
		SMOTAPPSABUN = P_SMOTAPPSABUN
	WHERE SMWKTEAM      = P_SMWKTEAM
	AND   SMWKDATE      = P_SMWKDATE
	AND   SMWKSEQ       = P_SMWKSEQ
	AND   SMWKORAPPDATE = P_SMWKORAPPDATE
	AND   SMWKORSEQ     = P_SMWKORSEQ;

END P1;