DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_WORK_CANCEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_WORK_CANCEL
(
	IN P_SMCNSABUN        VARCHAR(6),
	IN P_SMCNDATE         VARCHAR(8),
	IN P_SMCNTIME         VARCHAR(6),
	IN P_SMCNREASON       VARCHAR(500),
	IN P_SMWKTEAM         VARCHAR(6),
	IN P_SMWKDATE         VARCHAR(8),
	IN P_SMWKSEQ          NUMERIC(3,0),
	IN P_SMWKORAPPDATE    VARCHAR(8),
	IN P_SMWKORSEQ        NUMERIC(3,0)
)
	
LANGUAGE SQL

P1: BEGIN

	UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
		SMCNSABUN   = P_SMCNSABUN,
		SMCNDATE    = P_SMCNDATE,
		SMCNTIME    = P_SMCNTIME,
		SMCNREASON  = P_SMCNREASON
	WHERE SMWKTEAM      = P_SMWKTEAM
	AND   SMWKDATE      = P_SMWKDATE
	AND   SMWKSEQ       = P_SMWKSEQ
	AND   SMWKORAPPDATE = P_SMWKORAPPDATE
	AND   SMWKORSEQ     = P_SMWKORSEQ;

END P1;