DROP PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MSAFETOOL_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MSAFETOOL_ADD ( 
	IN P_JSTWKGUBN   VARCHAR(1),
	IN P_JSTPOTEAM   VARCHAR(6),
	IN P_JSTPODATE   VARCHAR(8),
	IN P_JSTPOSEQ   NUMERIC(3,0),
	IN P_JSTDATE   VARCHAR(8),
	IN P_JSTMSEQ   NUMERIC(3,0),
	IN P_JSTBLASS VARCHAR(2) , 
	IN P_JSTMLASS VARCHAR(2) , 
	IN P_JSTSLASS VARCHAR(3) , 
	IN P_JSTSEQ NUMERIC(3,0) , 
	IN P_JSTINDX NUMERIC(3,0) , 
	IN P_JSTCODEGUBN VARCHAR(1) , 
	IN P_JSTSAFECODE VARCHAR(3) , 
	IN P_JSTSAFENAME VARCHAR(100) , 
	IN P_SWHISAB VARCHAR(6))
	LANGUAGE SQL 
	
	P1 : BEGIN 
	 
	INSERT INTO PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
	(
	JSTWKGUBN,
	JSTPOTEAM,
	JSTPODATE,
	JSTPOSEQ,
	JSTDATE,
	JSTMSEQ,
	JSTBLASS,
	JSTMLASS,
	JSTSLASS,
	JSTSEQ,
	JSTINDX,
	JSTCODEGUBN,
	JSTSAFECODE,
	JSTSAFENAME,
	JSTHIGB,
	JSTHIDAT,
	JSTHITIM,
	JSTHISAB
	)
	VALUES
	(
	P_JSTWKGUBN,
	P_JSTPOTEAM,
	P_JSTPODATE,
	P_JSTPOSEQ,
	P_JSTDATE,
	P_JSTMSEQ,
	P_JSTBLASS,
	P_JSTMLASS,
	P_JSTSLASS,
	P_JSTSEQ,
	P_JSTINDX,
	P_JSTCODEGUBN,
	P_JSTSAFECODE,
	P_JSTSAFENAME,
	'A',
	CURRENT_DATE,
	CURRENT_TIME,
	P_SWHISAB
	); 
  
END P1  ; 
  

