DROP PROCEDURE PSSCMLIB.PSM_PSM4047_JSACHANGE_RISK_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4047_JSACHANGE_RISK_ADD ( 
	IN P_JSRWKGUBN VARCHAR(1),
	IN P_JSRPOTEAM VARCHAR(6),
	IN P_JSRPODATE VARCHAR(8),
	IN P_JSRPOSEQ NUMERIC(3,0),
	IN P_JSRDATE VARCHAR(8),
	IN P_JSRMSEQ NUMERIC(3,0),
	IN P_JSRBLASS VARCHAR(2) , 
	IN P_JSRMLASS VARCHAR(2) , 
	IN P_JSRSLASS VARCHAR(3) , 
	IN P_JSRSEQ NUMERIC(3,0) , 
	IN P_JSRITEMSEQ NUMERIC(3,0) ,
	IN P_JSRSUBSEQ NUMERIC(3,0),
	IN P_JSRRISKTEXT VARCHAR(400),
	IN P_JSRRISKCNT NUMERIC(1,0),
	IN P_JSRRISKSOLID NUMERIC(1,0),
	IN P_JSRRISKDEGREE NUMERIC(1,0),
	IN P_JSRHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_JSACHANGE_RISK
		(
		JSRWKGUBN,
		JSRPOTEAM,
		JSRPODATE,
		JSRPOSEQ,
		JSRDATE,
		JSRMSEQ,
		JSRBLASS,
		JSRMLASS,
		JSRSLASS,
		JSRSEQ,
		JSRITEMSEQ,
		JSRSUBSEQ,
		JSRRISKTEXT,
		JSRRISKCNT,
		JSRRISKSOLID,
		JSRRISKDEGREE,
		JSRHIGB,
		JSRHIDAT,
		JSRHITIM,
		JSRHISAB
		)
		VALUES
		(
		P_JSRWKGUBN,
		P_JSRPOTEAM,
		P_JSRPODATE,
		P_JSRPOSEQ,
		P_JSRDATE,
		P_JSRMSEQ,
		P_JSRBLASS,
		P_JSRMLASS,
		P_JSRSLASS,
		P_JSRSEQ,
		P_JSRITEMSEQ,
		P_JSRSUBSEQ,
		P_JSRRISKTEXT,
		P_JSRRISKCNT,
		P_JSRRISKSOLID,
		P_JSRRISKDEGREE,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_JSRHISAB
		)
		;
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_JSACHANGE_RISK SET
		JSRRISKTEXT   = P_JSRRISKTEXT,
		JSRRISKCNT    = P_JSRRISKCNT,
		JSRRISKSOLID  = P_JSRRISKSOLID,
		JSRRISKDEGREE = P_JSRRISKDEGREE,
		JSRHIGB       = 'C',
		JSRHIDAT      = CURRENT_DATE,
		JSRHITIM      = CURRENT_TIME,
		JSRHISAB      = P_JSRHISAB
		WHERE JSRWKGUBN  = P_JSRWKGUBN
		AND   JSRPOTEAM  = P_JSRPOTEAM
		AND   JSRPODATE  = P_JSRPODATE
		AND   JSRPOSEQ   = P_JSRPOSEQ
		AND   JSRDATE    = P_JSRDATE
		AND   JSRMSEQ    = P_JSRMSEQ  
		AND   JSRBLASS   = P_JSRBLASS
		AND   JSRMLASS   = P_JSRMLASS
		AND   JSRSLASS   = P_JSRSLASS
		AND   JSRSEQ     = P_JSRSEQ
		AND   JSRITEMSEQ = P_JSRITEMSEQ
		AND   JSRSUBSEQ  = P_JSRSUBSEQ ;
  
	END IF ; 
  
END P1  ; 
  