DROP PROCEDURE PSSCMLIB.PSM_PSM4041_BIN_CLEANING_INS;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_BIN_CLEANING_INS
(
	IN P_CLWKTEAM      VARCHAR(6),
	IN P_CLWKDATE      VARCHAR(8),
	IN P_CLWKSEQ       NUMERIC(3, 0),
	IN P_CLWKORAPPDATE VARCHAR(8),
	IN P_CLWKORSEQ     NUMERIC(3, 0),
	IN P_CLBINNO       VARCHAR(3),
	IN P_CLWORKTEXT    VARCHAR(300),
	IN P_CLCOSABUN     VARCHAR(6),
	IN P_CLSTATIME     VARCHAR(4),
	IN P_CLETATIME     VARCHAR(4),
	IN P_CLHISAB       VARCHAR(6)
)
	
LANGUAGE SQL

P1: BEGIN

	INSERT INTO TYSCMLIB.BIN_CLEANF
	(
		CLWKTEAM,
		CLWKDATE,
		CLWKSEQ,
		CLWKORAPPDATE,
		CLWKORSEQ,
		CLBINNO,
		CLWORKTEXT,
		CLCOSABUN,
		CLSTATIME,
		CLETATIME,
		CLHIGB,
		CLHIDAT,
		CLHITIM,
		CLHISAB
	)
	VALUES
	(
		P_CLWKTEAM,
		P_CLWKDATE,
		P_CLWKSEQ,
		P_CLWKORAPPDATE,
		P_CLWKORSEQ,
		P_CLBINNO,
		P_CLWORKTEXT,
		P_CLCOSABUN,
		P_CLSTATIME,
		P_CLETATIME,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_CLHISAB
	);

END P1;