-- DROP PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_DOC_APPROVAL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_DOC_APPROVAL (	
	IN P_CAASKTEAM        VARCHAR(6),    -- 변경요구번호(팀)
	IN P_CAASKDATE        VARCHAR(8),    -- 변경요구번호(일자)
	IN P_CAASKSEQ         NUMERIC(3,0),  -- 변경요구번호(순번)
	IN P_CAWOTEAM         VARCHAR(6),    -- 요청번호(팀)
	IN P_CAWODATE         VARCHAR(8),    -- 요청번호(일자)
	IN P_CAWOSEQ          NUMERIC(3,0),  -- 요청번호(순번)
	IN P_CAASKCONTENT     VARCHAR(1000), -- 설비명 또는 변경요소
	IN P_CAASKBUSEO       VARCHAR(6),    -- 발의부서
	IN P_CAASKCLASS       VARCHAR(1),    -- 변경등급
	IN P_CAASKSTEPGN      VARCHAR(1),    -- 변경종류(1=정상,2=임시,3=비상,4=화물(청소포함),5=화물(청소미포함)
	IN P_CAASKSUMMARY     VARCHAR(2500), -- 변경개요
	IN P_CAASKSABUN1      VARCHAR(6),    -- 사번1
	IN P_CAASKNAME1       VARCHAR(20),   -- 이름1
	IN P_CAASKJKCD1       VARCHAR(3),    -- 직책1
	IN P_CAASKJKCDNM1     VARCHAR(20),   -- 직책명1
 	IN P_CAASKCOMMENT1    VARCHAR(200),  -- 결재의견1
	IN P_CAASKSABUN2      VARCHAR(6),    -- 사번2
	IN P_CAASKNAME2       VARCHAR(20),   -- 이름2
	IN P_CAASKJKCD2       VARCHAR(3),    -- 직책2
	IN P_CAASKJKCDNM2     VARCHAR(20),   -- 직책명2
 	IN P_CAASKCOMMENT2    VARCHAR(200),  -- 결재의견2
	IN P_CAASKSABUN3      VARCHAR(6),    -- 사번3
	IN P_CAASKNAME3       VARCHAR(20),   -- 이름3
	IN P_CAASKJKCD3       VARCHAR(3),    -- 직책3
	IN P_CAASKJKCDNM3     VARCHAR(20),   -- 직책명3
 	IN P_CAASKCOMMENT3    VARCHAR(200),  -- 결재의견3
	IN P_CAASKSABUN4      VARCHAR(6),    -- 사번4
	IN P_CAASKNAME4       VARCHAR(20),   -- 이름4
	IN P_CAASKJKCD4       VARCHAR(3),    -- 직책4
	IN P_CAASKJKCDNM4     VARCHAR(20),   -- 직책명4
 	IN P_CAASKCOMMENT4    VARCHAR(200),  -- 결재의견4
	IN P_CAASKSABUN5      VARCHAR(6),    -- 사번5
	IN P_CAASKNAME5       VARCHAR(20),   -- 이름5
	IN P_CAASKJKCD5       VARCHAR(3),    -- 직책5
	IN P_CAASKJKCDNM5     VARCHAR(20),   -- 직책명5
 	IN P_CAASKCOMMENT5    VARCHAR(200),  -- 결재의견5
	IN P_CAASKRESABUN1    VARCHAR(6),    -- 수신팀승인자1
	IN P_CAASKRENAME1     VARCHAR(20),   -- 수신팀승인자이름1
	IN P_CAASKREJKCD1     VARCHAR(3),    -- 수신팀승인자직급코드1
	IN P_CAASKREJKCDNM1   VARCHAR(20),   -- 수신팀승인자직급명1
	IN P_CAASKRECOMMENT1  VARCHAR(100),  -- 수신팀승인자의견1
	IN P_CAASKRESABUN2    VARCHAR(6),    -- 수신팀승인자2
	IN P_CAASKRENAME2     VARCHAR(20),   -- 수신팀승인자이름2
	IN P_CAASKREJKCD2     VARCHAR(3),    -- 수신팀승인자직급코드2
	IN P_CAASKREJKCDNM2   VARCHAR(20),   -- 수신팀승인자직급명2
	IN P_CAASKRECOMMENT2  VARCHAR(100),  -- 수신팀승인자의견2
	IN P_CAASKRESABUN3    VARCHAR(6),    -- 수신팀승인자3
	IN P_CAASKRENAME3     VARCHAR(20),   -- 수신팀승인자이름3
	IN P_CAASKREJKCD3     VARCHAR(3),    -- 수신팀승인자직급코드3
	IN P_CAASKREJKCDNM3   VARCHAR(20),   -- 수신팀승인자직급명3
	IN P_CAASKRECOMMENT3  VARCHAR(100),  -- 수신팀승인자의견3
	IN P_CAASKRESABUN4    VARCHAR(6),    -- 수신팀승인자4
	IN P_CAASKRENAME4     VARCHAR(20),   -- 수신팀승인자이름4
	IN P_CAASKREJKCD4     VARCHAR(3),    -- 수신팀승인자직급코드4
	IN P_CAASKREJKCDNM4   VARCHAR(20),   -- 수신팀승인자직급명4
	IN P_CAASKRECOMMENT4  VARCHAR(100),  -- 수신팀승인자의견4
	IN P_CAASKRESABUN5    VARCHAR(6),    -- 수신팀승인자5
	IN P_CAASKRENAME5     VARCHAR(20),   -- 수신팀승인자이름5
	IN P_CAASKREJKCD5     VARCHAR(3),    -- 수신팀승인자직급코드5
	IN P_CAASKREJKCDNM5   VARCHAR(20),   -- 수신팀승인자직급명5
	IN P_CAASKRECOMMENT5  VARCHAR(100),  -- 수신팀승인자의견5
	IN P_CAASKHISAB       VARCHAR(6),    -- 작성사번
	IN P_RESABUN          VARCHAR(1000),
	IN P_RENAME           VARCHAR(2000),
	IN P_SOCOUNT          NUMERIC(1, 0),
	IN P_RECOUNT          NUMERIC(1, 0),
	IN P_SOAPPROVAL       VARCHAR(1),
	IN P_REAPPROVAL       VARCHAR(1),
	IN P_GUBUN            VARCHAR(20))

DYNAMIC RESULT SETS 1

P1 : BEGIN 

	DECLARE V_CNT NUMERIC ( 3, 0 );

	DECLARE V_SYULBI VARCHAR ( 10 );
	DECLARE V_SILOBIN VARCHAR ( 10 );

	SET V_CNT = 0;

	SELECT 
		COUNT ( * ) INTO V_CNT 
	FROM PSSCMLIB.PSM_CHANGEASK_DOC 
	WHERE CAASKTEAM = P_CAASKTEAM
	AND   CAASKDATE = P_CAASKDATE
	AND   CAASKSEQ  = P_CAASKSEQ;

	IF ( V_CNT = 0 ) THEN 

		INSERT INTO PSSCMLIB.PSM_CHANGEASK_DOC 
		(
			CAASKTEAM,
			CAASKDATE,
			CAASKSEQ,
			CAWOTEAM,
			CAWODATE,
			CAWOSEQ,
			CAASKCONTENT,
			CAASKBUSEO,
			CAASKCLASS,
			CAASKSTEPGN,
			CAASKSUMMARY,
			CAASKJKCD1,
			CAASKJKCDNM1,
			CAASKNAME1,
			CAASKSABUN1,
			CAASKCOMMENT1,
			CAASKJKCD2,
			CAASKJKCDNM2,
			CAASKNAME2,
			CAASKSABUN2,
			CAASKCOMMENT2,
			CAASKJKCD3,
			CAASKJKCDNM3,
			CAASKNAME3,
			CAASKSABUN3,
			CAASKCOMMENT3,
			CAASKJKCD4,
			CAASKJKCDNM4,
			CAASKNAME4,
			CAASKSABUN4,
			CAASKCOMMENT4,
			CAASKJKCD5,
			CAASKJKCDNM5,
			CAASKNAME5,
			CAASKSABUN5,
			CAASKCOMMENT5,
			CAASKREJKCD1,
			CAASKREJKCDNM1,
			CAASKRENAME1,
			CAASKRESABUN1,
			CAASKRECOMMENT1,
			CAASKREJKCD2,
			CAASKREJKCDNM2,
			CAASKRENAME2,
			CAASKRESABUN2,
			CAASKRECOMMENT2,
			CAASKREJKCD3,
			CAASKREJKCDNM3,
			CAASKRENAME3,
			CAASKRESABUN3,
			CAASKRECOMMENT3,
			CAASKREJKCD4,
			CAASKREJKCDNM4,
			CAASKRENAME4,
			CAASKRESABUN4,
			CAASKRECOMMENT4,
			CAASKREJKCD5,
			CAASKREJKCDNM5,
			CAASKRENAME5,
			CAASKRESABUN5,
			CAASKRECOMMENT5,
			CAASKHIGB, 
			CAASKHIDAT, 
			CAASKHITIM, 
			CAASKHISAB			
		) 
		VALUES 
		( 
			P_CAASKTEAM,
			P_CAASKDATE,
			P_CAASKSEQ,
			P_CAWOTEAM,
			P_CAWODATE,
			P_CAWOSEQ,
			P_CAASKCONTENT,
			P_CAASKBUSEO,
			P_CAASKCLASS,
			P_CAASKSTEPGN,
			P_CAASKSUMMARY,
			P_CAASKJKCD1,
			P_CAASKJKCDNM1,
			P_CAASKNAME1,
			P_CAASKSABUN1,
			P_CAASKCOMMENT1,
			P_CAASKJKCD2,
			P_CAASKJKCDNM2,
			P_CAASKNAME2,
			P_CAASKSABUN2,
			P_CAASKCOMMENT2,
			P_CAASKJKCD3,
			P_CAASKJKCDNM3,
			P_CAASKNAME3,
			P_CAASKSABUN3,
			P_CAASKCOMMENT3,
			P_CAASKJKCD4,
			P_CAASKJKCDNM4,
			P_CAASKNAME4,
			P_CAASKSABUN4,
			P_CAASKCOMMENT4,
			P_CAASKJKCD5,
			P_CAASKJKCDNM5,
			P_CAASKNAME5,
			P_CAASKSABUN5,
			P_CAASKCOMMENT5,
			P_CAASKREJKCD1,
			P_CAASKREJKCDNM1,
			P_CAASKRENAME1,
			P_CAASKRESABUN1,
			P_CAASKRECOMMENT1,
			P_CAASKREJKCD2,
			P_CAASKREJKCDNM2,
			P_CAASKRENAME2,
			P_CAASKRESABUN2,
			P_CAASKRECOMMENT2,
			P_CAASKREJKCD3,
			P_CAASKREJKCDNM3,
			P_CAASKRENAME3,
			P_CAASKRESABUN3,
			P_CAASKRECOMMENT3,
			P_CAASKREJKCD4,
			P_CAASKREJKCDNM4,
			P_CAASKRENAME4,
			P_CAASKRESABUN4,
			P_CAASKRECOMMENT4,
			P_CAASKREJKCD5,
			P_CAASKREJKCDNM5,
			P_CAASKRENAME5,
			P_CAASKRESABUN5,
			P_CAASKRECOMMENT5,
			'A', 
			CURRENT_DATE, 
			CURRENT_TIME, 
			P_CAASKHISAB
		);
	ELSE 

		UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
			CAWOTEAM        = P_CAWOTEAM,
			CAWODATE        = P_CAWODATE,
			CAWOSEQ         = P_CAWOSEQ,
			CAASKCONTENT    = P_CAASKCONTENT,
			CAASKBUSEO      = P_CAASKBUSEO,
			CAASKCLASS      = P_CAASKCLASS,
			CAASKSTEPGN     = P_CAASKSTEPGN,
			CAASKSUMMARY    = P_CAASKSUMMARY,
			CAASKJKCD1      = P_CAASKJKCD1,
			CAASKJKCDNM1    = P_CAASKJKCDNM1,
			CAASKNAME1      = P_CAASKNAME1,
			CAASKSABUN1     = P_CAASKSABUN1,
			CAASKCOMMENT1   = P_CAASKCOMMENT1,
			CAASKJKCD2      = P_CAASKJKCD2,
			CAASKJKCDNM2    = P_CAASKJKCDNM2,
			CAASKNAME2      = P_CAASKNAME2,
			CAASKSABUN2     = P_CAASKSABUN2,
			CAASKCOMMENT2   = P_CAASKCOMMENT2,
			CAASKJKCD3      = P_CAASKJKCD3,
			CAASKJKCDNM3    = P_CAASKJKCDNM3,
			CAASKNAME3      = P_CAASKNAME3,
			CAASKSABUN3     = P_CAASKSABUN3,
			CAASKCOMMENT3   = P_CAASKCOMMENT3,
			CAASKJKCD4      = P_CAASKJKCD4,
			CAASKJKCDNM4    = P_CAASKJKCDNM4,
			CAASKNAME4      = P_CAASKNAME4,
			CAASKSABUN4     = P_CAASKSABUN4,
			CAASKCOMMENT4   = P_CAASKCOMMENT4,
			CAASKJKCD5      = P_CAASKJKCD5,
			CAASKJKCDNM5    = P_CAASKJKCDNM5,
			CAASKNAME5      = P_CAASKNAME5,
			CAASKSABUN5     = P_CAASKSABUN5,
			CAASKCOMMENT5   = P_CAASKCOMMENT5,
			CAASKREJKCD1    = P_CAASKREJKCD1,
			CAASKREJKCDNM1  = P_CAASKREJKCDNM1,
			CAASKRENAME1    = P_CAASKRENAME1,
			CAASKRESABUN1   = P_CAASKRESABUN1,
			CAASKRECOMMENT1 = P_CAASKRECOMMENT1,
			CAASKREJKCD2    = P_CAASKREJKCD2,
			CAASKREJKCDNM2  = P_CAASKREJKCDNM2,
			CAASKRENAME2    = P_CAASKRENAME2,
			CAASKRESABUN2   = P_CAASKRESABUN2,
			CAASKRECOMMENT2 = P_CAASKRECOMMENT2,
			CAASKREJKCD3    = P_CAASKREJKCD3,
			CAASKREJKCDNM3  = P_CAASKREJKCDNM3,
			CAASKRENAME3    = P_CAASKRENAME3,
			CAASKRESABUN3   = P_CAASKRESABUN3,
			CAASKRECOMMENT3 = P_CAASKRECOMMENT3,
			CAASKREJKCD4    = P_CAASKREJKCD4,
			CAASKREJKCDNM4  = P_CAASKREJKCDNM4,
			CAASKRENAME4    = P_CAASKRENAME4,
			CAASKRESABUN4   = P_CAASKRESABUN4,
			CAASKRECOMMENT4 = P_CAASKRECOMMENT4,
			CAASKREJKCD5    = P_CAASKREJKCD5,
			CAASKREJKCDNM5  = P_CAASKREJKCDNM5,
			CAASKRENAME5    = P_CAASKRENAME5,
			CAASKRESABUN5   = P_CAASKRESABUN5,
			CAASKRECOMMENT5 = P_CAASKRECOMMENT5,
			CAASKHIGB       = 'C', 
			CAASKHIDAT      = CURRENT_DATE, 
			CAASKHITIM      = CURRENT_TIME, 
			CAASKHISAB	    = P_CAASKHISAB
		WHERE CAASKTEAM = P_CAASKTEAM
		AND   CAASKDATE = P_CAASKDATE
		AND   CAASKSEQ  = P_CAASKSEQ;

	END IF;

	IF P_GUBUN = 'APPROVAL' THEN 

		UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
			CAWOTEAM        = P_CAWOTEAM,
			CAWODATE        = P_CAWODATE,
			CAWOSEQ         = P_CAWOSEQ,
			CAASKCONTENT    = P_CAASKCONTENT,
			CAASKBUSEO      = P_CAASKBUSEO,
			CAASKCLASS      = P_CAASKCLASS,
			CAASKSTEPGN     = P_CAASKSTEPGN,
			CAASKSUMMARY    = P_CAASKSUMMARY,
			CAASKJKCD1      = P_CAASKJKCD1,
			CAASKJKCDNM1    = P_CAASKJKCDNM1,
			CAASKNAME1      = P_CAASKNAME1,
			CAASKSABUN1     = P_CAASKSABUN1,
			CAASKCOMMENT1   = P_CAASKCOMMENT1,
			CAASKJKCD2      = P_CAASKJKCD2,
			CAASKJKCDNM2    = P_CAASKJKCDNM2,
			CAASKNAME2      = P_CAASKNAME2,
			CAASKSABUN2     = P_CAASKSABUN2,
			CAASKCOMMENT2   = P_CAASKCOMMENT2,
			CAASKJKCD3      = P_CAASKJKCD3,
			CAASKJKCDNM3    = P_CAASKJKCDNM3,
			CAASKNAME3      = P_CAASKNAME3,
			CAASKSABUN3     = P_CAASKSABUN3,
			CAASKCOMMENT3   = P_CAASKCOMMENT3,
			CAASKJKCD4      = P_CAASKJKCD4,
			CAASKJKCDNM4    = P_CAASKJKCDNM4,
			CAASKNAME4      = P_CAASKNAME4,
			CAASKSABUN4     = P_CAASKSABUN4,
			CAASKCOMMENT4   = P_CAASKCOMMENT4,
			CAASKJKCD5      = P_CAASKJKCD5,
			CAASKJKCDNM5    = P_CAASKJKCDNM5,
			CAASKNAME5      = P_CAASKNAME5,
			CAASKSABUN5     = P_CAASKSABUN5,
			CAASKCOMMENT5   = P_CAASKCOMMENT5,
			CAASKREJKCD1    = P_CAASKREJKCD1,
			CAASKREJKCDNM1  = P_CAASKREJKCDNM1,
			CAASKRENAME1    = P_CAASKRENAME1,
			CAASKRESABUN1   = P_CAASKRESABUN1,
			CAASKRECOMMENT1 = P_CAASKRECOMMENT1,
			CAASKREJKCD2    = P_CAASKREJKCD2,
			CAASKREJKCDNM2  = P_CAASKREJKCDNM2,
			CAASKRENAME2    = P_CAASKRENAME2,
			CAASKRESABUN2   = P_CAASKRESABUN2,
			CAASKRECOMMENT2 = P_CAASKRECOMMENT2,
			CAASKREJKCD3    = P_CAASKREJKCD3,
			CAASKREJKCDNM3  = P_CAASKREJKCDNM3,
			CAASKRENAME3    = P_CAASKRENAME3,
			CAASKRESABUN3   = P_CAASKRESABUN3,
			CAASKRECOMMENT3 = P_CAASKRECOMMENT3,
			CAASKREJKCD4    = P_CAASKREJKCD4,
			CAASKREJKCDNM4  = P_CAASKREJKCDNM4,
			CAASKRENAME4    = P_CAASKRENAME4,
			CAASKRESABUN4   = P_CAASKRESABUN4,
			CAASKRECOMMENT4 = P_CAASKRECOMMENT4,
			CAASKREJKCD5    = P_CAASKREJKCD5,
			CAASKREJKCDNM5  = P_CAASKREJKCDNM5,
			CAASKRENAME5    = P_CAASKRENAME5,
			CAASKRESABUN5   = P_CAASKRESABUN5,
			CAASKRECOMMENT5 = P_CAASKRECOMMENT5
		WHERE CAASKTEAM = P_CAASKTEAM
		AND   CAASKDATE = P_CAASKDATE
		AND   CAASKSEQ  = P_CAASKSEQ;

		IF P_SOAPPROVAL = '' THEN 

			SET P_SOAPPROVAL = '0';

		END IF;

		-- 결재일자와 시간 업데이트 
		-- 요청자 결재일자 및 시간 업데이트 
		IF P_SOCOUNT = ( INT ( P_SOAPPROVAL ) + 1 ) THEN 

			IF P_SOCOUNT = 1 THEN 

				UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
					CAASKDATE1 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
					CAASKTIME1 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
				WHERE CAASKTEAM = P_CAASKTEAM
				AND   CAASKDATE = P_CAASKDATE
				AND   CAASKSEQ  = P_CAASKSEQ;

			ELSEIF P_SOCOUNT = 2 THEN 

				UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
					CAASKDATE2 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
					CAASKTIME2 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
				WHERE CAASKTEAM = P_CAASKTEAM
				AND   CAASKDATE = P_CAASKDATE
				AND   CAASKSEQ  = P_CAASKSEQ;

			ELSEIF P_SOCOUNT = 3 THEN 

				UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
					CAASKDATE3 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
					CAASKTIME3 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
				WHERE CAASKTEAM = P_CAASKTEAM
				AND   CAASKDATE = P_CAASKDATE
				AND   CAASKSEQ  = P_CAASKSEQ;

			ELSEIF P_SOCOUNT = 4 THEN 

				UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
					CAASKDATE4 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
					CAASKTIME4 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
				WHERE CAASKTEAM = P_CAASKTEAM
				AND   CAASKDATE = P_CAASKDATE
				AND   CAASKSEQ  = P_CAASKSEQ;

			ELSEIF P_SOCOUNT = 5 THEN 

				UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
					CAASKDATE5 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
					CAASKTIME5 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
				WHERE CAASKTEAM = P_CAASKTEAM
				AND   CAASKDATE = P_CAASKDATE
				AND   CAASKSEQ  = P_CAASKSEQ;

			END IF;
		ELSE 

			IF P_SOCOUNT <> INT ( P_SOAPPROVAL ) THEN 

				IF P_SOAPPROVAL = '0' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKDATE1 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKTIME1 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_SOAPPROVAL = '1' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKDATE2 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKTIME2 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_SOAPPROVAL = '2' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKDATE3 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKTIME3 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_SOAPPROVAL = '3' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKDATE4 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKTIME4 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_SOAPPROVAL = '4' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKDATE5 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKTIME5 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				END IF;

			END IF;

		END IF;

		-- 수신자 결재일자 및 시간 업데이트 
		IF P_SOCOUNT = INT ( P_SOAPPROVAL ) THEN 

			IF P_RECOUNT = ( INT ( P_REAPPROVAL ) + 1 ) THEN 

				IF P_RECOUNT = 1 THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE1 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME1 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_RECOUNT = 2 THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE2 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME2 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_RECOUNT = 3 THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE3 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME3 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_RECOUNT = 4 THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE4 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME4 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_RECOUNT = 5 THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE5 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME5 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				END IF;

			ELSE 

				IF P_REAPPROVAL = '0' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE1 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME1 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_REAPPROVAL = '1' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE2 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME2 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_REAPPROVAL = '2' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE3 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME3 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_REAPPROVAL = '3' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE4 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME4 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				ELSEIF P_REAPPROVAL = '4' THEN 

					UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET 
						CAASKREDATE5 = REPLACE ( CHAR ( CURRENT_DATE ), '-', '' ), 
						CAASKRETIME5 = REPLACE ( CHAR ( CURRENT_TIME ), '.', '' ) 
					WHERE CAASKTEAM = P_CAASKTEAM
				        AND   CAASKDATE = P_CAASKDATE
					AND   CAASKSEQ  = P_CAASKSEQ;

				END IF;

			END IF;

		END IF;


		MAIN : BEGIN  -- 실행부 

			DECLARE REFCURSOR CURSOR WITH RETURN FOR
				
				SELECT
					P_GUBUN AS GUBUN,
					CAASKACYEAR,
					CAASKACSEQ,
					CARECEIPTDATE,
					CAASKDATE1,
					CAASKTIME1,
					CAASKDATE2,
					CAASKTIME2,
					CAASKDATE3,
					CAASKTIME3,
					CAASKDATE4,
					CAASKTIME4,
					CAASKDATE5,
					CAASKTIME5,
					CAASKREDATE1,
					CAASKRETIME1,
					CAASKREDATE2,
					CAASKRETIME2,
					CAASKREDATE3,
					CAASKRETIME3,
					CAASKREDATE4,
					CAASKRETIME4,
					CAASKREDATE5,
					CAASKRETIME5,
					CAASKSABUN1,
					CAASKSABUN2,
					CAASKSABUN3,
					CAASKSABUN4,
					CAASKSABUN5,
					CAASKRESABUN1,
					CAASKRESABUN2,
					CAASKRESABUN3,
					CAASKRESABUN4,
					CAASKRESABUN5,
					/* 사인 */ 
					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN1
					) AS SOIMGNAME1, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN1
					) AS SOIMGSIZE1, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN1
					) AS SOIMGSIGN1,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN2
					) AS SOIMGNAME2, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN2
					) AS SOIMGSIZE2, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN2
					) AS SOIMGSIGN2, 

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN3
					) AS SOIMGNAME3, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN3
					) AS SOIMGSIZE3, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN3
					) AS SOIMGSIGN3,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN4
					) AS SOIMGNAME4, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN4
					) AS SOIMGSIZE4,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN4
					) AS SOIMGSIGN4,


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN5
					) AS SOIMGNAME5, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN5
					) AS SOIMGSIZE5,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN5
					) AS SOIMGSIGN5,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN1
					) AS REIMGNAME1, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN1
					) AS REIMGSIZE1, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN1
					) AS REIMGSIGN1, 


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN2
					) AS REIMGNAME2, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN2
					) AS REIMGSIZE2, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN2
					) AS REIMGSIGN2, 

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN3
					) AS REIMGNAME3, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN3
					) AS REIMGSIZE3, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN3
					) AS REIMGSIGN3,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN4
					) AS REIMGNAME4, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN4
					) AS REIMGSIZE4,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN4
					) AS REIMGSIGN4,


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN5
					) AS REIMGNAME5, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN5
					) AS REIMGSIZE5,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN5
					) AS REIMGSIGN5
				FROM PSSCMLIB.PSM_CHANGEASK_DOC
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS SOIMG1 
				ON SOIMG1.IMGSABUN = CAASKSABUN1 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS SOIMG2 
				ON SOIMG2.IMGSABUN = CAASKSABUN2 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS SOIMG3 
				ON SOIMG3.IMGSABUN = CAASKSABUN3 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS SOIMG4 
				ON SOIMG4.IMGSABUN = CAASKSABUN4 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS SOIMG5 
				ON SOIMG5.IMGSABUN = CAASKSABUN5 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS REIMG1 
				ON REIMG1.IMGSABUN = CAASKRESABUN1 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS REIMG2 
				ON REIMG2.IMGSABUN = CAASKRESABUN2 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS REIMG3 
				ON REIMG3.IMGSABUN = CAASKRESABUN3 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS REIMG4 
				ON REIMG4.IMGSABUN = CAASKRESABUN4 
				LEFT JOIN PSSCMLIB.PSM_IMGSIGN AS REIMG5 
				ON REIMG5.IMGSABUN = CAASKRESABUN5
				WHERE CAASKTEAM = P_CAASKTEAM
				AND   CAASKDATE = P_CAASKDATE
				AND   CAASKSEQ  = P_CAASKSEQ;

			OPEN REFCURSOR;

		END MAIN;

	ELSE
		-- 저장이면 없음
		MAIN1 : BEGIN  -- 실행부 

			DECLARE REFCURSOR1 CURSOR WITH RETURN FOR

				SELECT
					P_GUBUN AS GUBUN
				FROM SYSIBM.SYSDUMMY1;

			OPEN REFCURSOR1;

		END MAIN1;

	END IF;

	-- 참조자 저장 
	CALL PSSCMLIB.PSM_REFERENCE_UPDATE ('A', 'CA', P_CAASKTEAM||P_CAASKDATE||DIGITS(P_CAASKSEQ)||P_CAWOTEAM||P_CAWODATE||DIGITS(P_CAWOSEQ), P_RESABUN, P_RENAME, P_CAASKHISAB);

END P1;

CALL PSSCMLIB.PSM_PSM4021_CHANGEASK_DOC_APPROVAL('A20000','20231016',001,'A20000','20230925',001,'test','A20000','A',1,'test','0311-M','김상권','130','과장','','0403-M','이상현','150','대리','','','','','','','','','','','','','','','','','0403-M','이상현','150','대리','','','','','','','','','','','','','','','','','','','','','','0311-M','','','2','1','0','0','SAVE');