DROP PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_DOC_PRT;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_DOC_PRT ( 
	IN P_CAASKTEAM VARCHAR(6) , 
	IN P_CAASKDATE VARCHAR(8) , 
	IN P_CAASKSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- ¸¶½ºÅ¸ 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT
			CASE WHEN CAASKDATE <> '' THEN SUBSTR(CAASKDATE,1,4) || '.' || SUBSTR(CAASKDATE,5,2) || '.' || SUBSTR(CAASKDATE,7,2) ELSE '' END AS CAASKDATE,
			CAASKBUSEO,
			TYSCMLIB.SF_GB_ORGNAME ( CAASKBUSEO , CAST ( CAASKDATE AS VARCHAR ( 8 ) ) ) AS CAASKBUSEONM,
			CAASKJKCD1,
			CAASKJKCDNM1,
			CAASKNAME1,
			CAASKSABUN1,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CAASKSABUN1 
			) AS IMGNAME , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CAASKSABUN1 
			) AS IMGSIZE , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CAASKSABUN1 
			) AS IMGSIGN , 
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN, 
			*/
			CAASKCONTENT,
			CAASKCLASS,
			CASE WHEN CAASKSTEPGN = '3' THEN 'Y' ELSE '' END AS CAASKSTEPGN1,
			CASE WHEN CAASKSTEPGN = '4' THEN 'Y' ELSE '' END AS CAASKSTEPGN2,
			CASE WHEN CAASKSTEPGN = '5' THEN 'Y' ELSE '' END AS CAASKSTEPGN3,
			CASE WHEN CAASKSTEPGN = '1' OR CAASKSTEPGN = '2' THEN 'Y' ELSE '' END AS CAASKSTEPGN4,
			REPLACE(CAASKSUMMARY,'<br />', chr(10)) AS CAASKSUMMARY,
			CAASKACYEAR || '-' || DIGITS(CAASKACSEQ) AS CAASKACSEQ,
			CASE WHEN CARECEIPTDATE <> '' THEN SUBSTR(CARECEIPTDATE,1,4) || '.' || SUBSTR(CARECEIPTDATE,5,2) || '.' || SUBSTR(CARECEIPTDATE,7,2) ELSE '' END  AS CARECEIPTDATE ,
			ATT.FILE_NAME
			FROM PSSCMLIB.PSM_CHANGEASK_DOC
			/*
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG 
			ON   IMG . ATTACH_TYPE = 'SG' 
			AND IMG . ATTACH_NO = CAASKSABUN1 
			*/
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH ATT
			ON    ATT. ATTACH_TYPE = 'CA'
			AND  ATT. ATTACH_NO = CAASKTEAM || CAASKDATE || DIGITS(CAASKSEQ)
			WHERE CAASKTEAM = P_CAASKTEAM
			AND    CAASKDATE = P_CAASKDATE
			AND    CAASKSEQ = P_CAASKSEQ; 
  
		OPEN REFCURSOR ; 
	END P1 ; 
  