DROP PROCEDURE PSSCMLIB.PSM_PSM4081_EXAM_REPORT_SEQ;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4081_EXAM_REPORT_SEQ ( 
	IN P_PERTCTEAM VARCHAR(6) , 
	IN P_PERTCDATE VARCHAR(8) ,
	IN P_PERTCSEQ NUMERIC(3,0),
	IN P_PERDATE VARCHAR(8) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
			SELECT VALUE ( MAX ( PERSEQ ) , 0 ) + 1 AS PERSEQ 
			FROM PSSCMLIB . PSM_EXAM_REPORT 
			WHERE PERTCTEAM = P_PERTCTEAM 
			AND   PERTCDATE = P_PERTCDATE 
			AND   PERTCSEQ = P_PERTCSEQ 
			AND   PERDATE = P_PERDATE 
			; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 
  