DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SYSTEM_HISTORY_INS;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SYSTEM_HISTORY_INS
(
    IN P_HISAUP      VARCHAR(1),
	IN P_HIBCODE     VARCHAR(2),
	IN P_HIMCODE     NUMERIC(4,0),
	IN P_HISCODE     NUMERIC(3,0),
	IN P_HISEQ       NUMERIC(4,0),
	IN P_HIPONUM     VARCHAR(12),
	IN P_HIMDDATE    VARCHAR(8),
	IN P_HIASSETNM   VARCHAR(100),
	IN P_HIITEM      VARCHAR(12),
	IN P_HIQUALITY   DECIMAL(4, 0),
	IN P_HIAMT       DECIMAL(15, 0),
	IN P_HICOMPANY   VARCHAR(40),
	IN P_HIWKSTDATE  VARCHAR(8),
	IN P_HIWKEDDATE  VARCHAR(8),
	IN P_HIWKNUM     VARCHAR(17),
	IN P_HIBIGO      VARCHAR(100),
	IN P_HIHISAB     VARCHAR(6)
)
	
LANGUAGE SQL

P1: BEGIN

	INSERT INTO PSSCMLIB.PSM_SYSTEM_HISTORY
	(
		HISAUP,
		HIBCODE,
		HIMCODE,
		HISCODE,
		HISEQ,
		HIPONUM,
		HIMDDATE,
		HIASSETNM,
		HIITEM,
		HIQUALITY,
		HIAMT,
		HICOMPANY,
		HIWKSTDATE,
		HIWKEDDATE,
		HIWKNUM,
		HIBIGO,
		HIHIGB,
		HIHIDAT,
		HIHITIM,
		HIHISAB
	)
	VALUES	
	(
		P_HISAUP,
		P_HIBCODE,
		P_HIMCODE,
		P_HISCODE,
		P_HISEQ,
		P_HIPONUM,
		P_HIMDDATE,
		P_HIASSETNM,
		P_HIITEM,
		P_HIQUALITY,
		P_HIAMT,
		P_HICOMPANY,
		P_HIWKSTDATE,
		P_HIWKEDDATE,
		P_HIWKNUM,
		P_HIBIGO,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_HIHISAB
	);

END P1;