DROP PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_ADD ( 
	IN P_JSDWKGUBN VARCHAR(1),
	IN P_JSDPOTEAM VARCHAR(6),
	IN P_JSDPODATE VARCHAR(8),
	IN P_JSDPOSEQ NUMERIC(3,0),
	IN P_JSDDATE VARCHAR(8),
	IN P_JSDMSEQ NUMERIC(3,0),
	IN P_JSDBLASS VARCHAR(2) , 
	IN P_JSDMLASS VARCHAR(2) , 
	IN P_JSDSLASS VARCHAR(3) , 
	IN P_JSDSEQ NUMERIC(3,0) , 
	IN P_JSDITEMSEQ NUMERIC(3,0),
	IN P_JSDITEMTEXT VARCHAR(400),
	IN P_JSDTOOLTEXT VARCHAR(400),
	IN P_JSDHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 

	P1 : BEGIN 
	 
	IF P_GUBUN = 'A' THEN
  
		INSERT INTO PSSCMLIB.PSM_JSACHANGE_DETAIL
		(
		JSDWKGUBN,
		JSDPOTEAM,
		JSDPODATE,
		JSDPOSEQ,
		JSDDATE,
		JSDMSEQ,
		JSDBLASS,
		JSDMLASS,
		JSDSLASS,
		JSDSEQ,
		JSDITEMSEQ,
		JSDITEMTEXT,
		JSDTOOLTEXT,
		JSDHIGB,
		JSDHIDAT,
		JSDHITIM,
		JSDHISAB
		)
		VALUES
		(
		P_JSDWKGUBN,
		P_JSDPOTEAM,
		P_JSDPODATE,
		P_JSDPOSEQ,
		P_JSDDATE,
		P_JSDMSEQ,
		P_JSDBLASS,
		P_JSDMLASS,
		P_JSDSLASS,
		P_JSDSEQ,
		P_JSDITEMSEQ,
		P_JSDITEMTEXT,
		P_JSDTOOLTEXT,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_JSDHISAB
		) ;
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_JSACHANGE_DETAIL SET
		JSDITEMTEXT = P_JSDITEMTEXT,
		JSDTOOLTEXT = P_JSDTOOLTEXT,
		JSDHIGB     = 'C',
		JSDHIDAT    = CURRENT_DATE,
		JSDHITIM    = CURRENT_TIME,
		JSDHISAB    = P_JSDHISAB
		WHERE JSDWKGUBN  = P_JSDWKGUBN
		AND   JSDPOTEAM  = P_JSDPOTEAM
		AND   JSDPODATE  = P_JSDPODATE
		AND   JSDPOSEQ   = P_JSDPOSEQ 
		AND   JSDDATE    = P_JSDDATE  
		AND   JSDMSEQ    = P_JSDMSEQ  
		AND   JSDBLASS   = P_JSDBLASS
		AND   JSDMLASS   = P_JSDMLASS
		AND   JSDSLASS   = P_JSDSLASS
		AND   JSDSEQ     = P_JSDSEQ
		AND   JSDITEMSEQ = P_JSDITEMSEQ ;
  
	END IF ; 
  
END P1  ; 
  