--DROP PROCEDURE PSSCMLIB.PSM_WORKORDER_IMMED_VERIFY;
  
CREATE PROCEDURE PSSCMLIB.PSM_WORKORDER_IMMED_VERIFY ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_WORKORDER_IMMED_VERIFY 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   

P1 : BEGIN

	MAIN : BEGIN  -- ½ÇÇàºÎ
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APNUM,
				WOORTEAM,
				WOORDATE,
				DIGITS(WOSEQ) AS WOSEQ,
				WOWORKTITLE,
				WOFINISHTEXT,
				WOIMMEDTEXT,
				WOIMMEDDATE,
				WOWORKDOC
			FROM PSSCMLIB.PSM_WORKORDER
			WHERE WOORTEAM = P_WOORTEAM
			AND   WOORDATE = P_WOORDATE
			AND   WOSEQ    = P_WOSEQ
			AND   WOIMMEDDATE <> '';
  
		OPEN REFCURSOR;
	END MAIN;

END P1;