--DROP PROCEDURE PSSCMLIB.PSM_SAFEORDER_FINISH_UPT;
  
CREATE PROCEDURE PSSCMLIB.PSM_SAFEORDER_FINISH_UPT ( 
	IN P_WOFINISHDATE  VARCHAR(8),
	IN P_WOFINISHTIME  VARCHAR(6),
	IN P_WOFINISHSABUN VARCHAR(6),
	IN P_WOFINISHTEXT  VARCHAR(200),
	IN P_WOORTEAM      VARCHAR(6),
	IN P_WOORDATE      VARCHAR(8),
	IN P_WOSEQ         NUMERIC(3,0))
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_SAFEORDER_FINISH_UPT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 

	DECLARE	V_SMWKTEAM         VARCHAR(6);
        DECLARE	V_SMWKDATE         VARCHAR(8);
	DECLARE	V_SMWKSEQ          NUMERIC(3,0);
	DECLARE	V_SMWKORAPPDATE    VARCHAR(8);
	DECLARE	V_SMWKORSEQ        NUMERIC(3,0);
	DECLARE	V_SMFSSABUN       VARCHAR(6);
	DECLARE	V_SMFSDATE        VARCHAR(8);
	DECLARE	V_SMFSTIME        VARCHAR(6);

	SET V_SMWKTEAM = '';
	SET V_SMWKDATE = '';
	SET V_SMWKSEQ = 0;
	SET V_SMWKORAPPDATE = '';
	SET V_SMWKORSEQ = 0;
	SET V_SMFSSABUN = '';
	SET V_SMFSDATE = '';
	SET V_SMFSTIME = '';

	SELECT
	SMWKTEAM,
	SMWKDATE,
	SMWKSEQ,
	SMWKORAPPDATE,
	SMWKORSEQ,
	SMFSSABUN,
	SMFSDATE,
	SMFSTIME
	INTO V_SMWKTEAM, V_SMWKDATE, V_SMWKSEQ, V_SMWKORAPPDATE, V_SMWKORSEQ, V_SMFSSABUN, V_SMFSDATE, V_SMFSTIME
	FROM PSSCMLIB.PSM_SAFEORDER_MASTER
	WHERE SMWKTEAM = P_WOORTEAM
	AND    SMWKDATE = P_WOORDATE
	AND    SMWKSEQ  = P_WOSEQ
	ORDER BY SMWKORAPPDATE DESC, SMWKORSEQ DESC
	FETCH FIRST 1 ROWS ONLY  ;

	--IF V_SMFSSABUN = '' AND V_SMFSDATE = '' AND V_SMFSTIME = '' THEN

		UPDATE PSSCMLIB.PSM_SAFEORDER_MASTER SET
			--SMFSSABUN  = P_WOFINISHSABUN,
			--SMFSDATE  = P_WOFINISHDATE,
			--SMFSTIME  = P_WOFINISHTIME,
			SMFSWKCLOSE = 'Y',
			SMFSWKTEXT = P_WOFINISHTEXT
		WHERE SMWKTEAM = P_WOORTEAM
		AND   SMWKDATE = P_WOORDATE
		AND   SMWKSEQ  = P_WOSEQ
		AND   SMWKORAPPDATE = V_SMWKORAPPDATE
		AND   SMWKORSEQ = V_SMWKORSEQ
		;

	--END IF;


	

END P1;

