DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_CANCEL_SEQ;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_CANCEL_SEQ ( 
	IN P_SMWKTEAM      VARCHAR(6),
	IN P_SMWKDATE      VARCHAR(8),
	IN P_SMWKSEQ       NUMERIC(3, 0),
	IN P_SMWKORAPPDATE VARCHAR(8),
	IN P_SMWKORSEQ     NUMERIC(3, 0)
)

DYNAMIC RESULT SETS 1 
LANGUAGE SQL 

P1 : BEGIN  -- 시작
	
	MAIN : BEGIN  -- 실행부 
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT			
				MAX(NUM) AS NUM,
				KBMAILID,
				SABUN
			FROM
			(
				SELECT
				1 AS NUM,
				KBMAILID,
				SMORSABUN   AS SABUN
				FROM PSSCMLIB.PSM_SafeOrder_MASTER
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF
				ON    KBCOMPANY     = '2'
				AND   KBIGUBN NOT IN ('560','900')
				AND   KBMAILID     <> ''
				AND   KBSABUN       = SMORSABUN
				WHERE SMWKTEAM      = P_SMWKTEAM
				AND   SMWKDATE      = P_SMWKDATE
				AND   SMWKSEQ       = P_SMWKSEQ
				AND   SMWKORAPPDATE = P_SMWKORAPPDATE
				AND   SMWKORSEQ     = P_SMWKORSEQ
				AND   SMORSABUN     <> ''
				AND   SMORAPPDATE   <> ''

				UNION ALL

				SELECT
				2 AS NUM,
				KBMAILID,
				SMGRSABUN   AS SABUN
				FROM PSSCMLIB.PSM_SafeOrder_MASTER
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF
				ON    KBCOMPANY     = '2'
				AND   KBIGUBN NOT IN ('560','900')
				AND   KBMAILID     <> ''
				AND   KBSABUN       = SMGRSABUN
				WHERE SMWKTEAM      = P_SMWKTEAM
				AND   SMWKDATE      = P_SMWKDATE
				AND   SMWKSEQ       = P_SMWKSEQ
				AND   SMWKORAPPDATE = P_SMWKORAPPDATE
				AND   SMWKORSEQ     = P_SMWKORSEQ
				AND   SMGRSABUN     <> ''
				AND   SMGRAPPDATE   <> ''

				UNION ALL

				SELECT
				3 AS NUM,
				KBMAILID,
				SMCOSABUN   AS SABUN
				FROM PSSCMLIB.PSM_SafeOrder_MASTER
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF
				ON    KBCOMPANY     = '2'
				AND   KBIGUBN NOT IN ('560','900')
				AND   KBMAILID     <> ''
				AND   KBSABUN       = SMCOSABUN
				WHERE SMWKTEAM      = P_SMWKTEAM
				AND   SMWKDATE      = P_SMWKDATE
				AND   SMWKSEQ       = P_SMWKSEQ
				AND   SMWKORAPPDATE = P_SMWKORAPPDATE
				AND   SMWKORSEQ     = P_SMWKORSEQ
				AND   SMCOSABUN     <> ''
				AND   SMCOAPPDATE   <> ''
				ORDER BY NUM
			) AS TEMP
			GROUP BY KBMAILID, SABUN;
  
		OPEN REFCURSOR;
	END MAIN;
END P1;