-- DROP PROCEDURE PSSCMLIB.PSM_PSM4040_WORKORDER_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_WORKORDER_LIST ( 
	IN P_STDATE VARCHAR(8) , 
	IN P_EDDATE VARCHAR(8) , 
	IN P_WKSAUP VARCHAR(1) , 
	IN P_WKTEAM VARCHAR(6) , 
	IN P_DEPT VARCHAR(6) , 
	IN P_ORSABUN VARCHAR(6) , 
	IN P_TITLE VARCHAR(120) , 
	IN P_STATUS VARCHAR(20) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4040_WORKORDER_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN  -- 시작 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		 
		WITH TABLE1 AS ( 
		SELECT ROWNUMBER ( ) OVER ( ) AS ROWNO , 
			( CASE WHEN C . WOFINISHDATE <> '' OR C . WOIMMEDDATE <> '' THEN '' ELSE '<img src="/Resources/Images/Icon/icon_new.png" style="cursor:pointer" onclick="grdWorkJSAClick();" />' END ) AS JSA_ADD , 
			( CASE WHEN C . WOFINISHDATE <> '' OR C . WOIMMEDDATE <> '' THEN '' ELSE '<img src="/Resources/Images/Icon/icon_new.png" style="cursor:pointer" onclick="grdWorkSAFEClick();" />' END ) AS SAFE_ADD , 
			WOORTEAM || '-' || WOORDATE || '-' || DIGITS ( WOSEQ ) AS APP_NUM , 
			WOWORKTITLE , 
			WOLOCATIONCODE1 , 
			S1 . FXC3DESC AS WOLOCATIONCODE1NM ,  --설비명 
			WOSOTEAM , 
			TYSCMLIB . SF_GB_ORGNAME ( WOSOTEAM , WOORDATE ) AS WOSOTEAMNM , 
			WORETEAM , 
			TYSCMLIB . SF_GB_ORGNAME ( WORETEAM , WOORDATE ) AS WORETEAMNM , 
			PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'CODE' , 'OR' ) AS WOAPPORSABUN , 
			PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'NAME' , 'OR' ) AS WOAPPORSABUNNM , 
			PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'CODE' , 'RE' ) AS WOAPPREVSABUN , 
			PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'NAME' , 'RE' ) AS WOAPPREVSABUNNM , 
			CASE WHEN WODSDATE1 = '' THEN '' ELSE 
			SUBSTR ( WODSDATE1 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE1 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE1 , 7 , 2 ) 
			END AS WODSDATE1 , 
			CASE WHEN WODSDATE2 = '' THEN '' ELSE 
			SUBSTR ( WODSDATE2 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE2 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE2 , 7 , 2 ) 
			END AS WODSDATE2 , 
			( CASE WHEN C . WOSTATUS = '1' AND C . WOAPPSTATUS = 'F' THEN '작업요청 완료' 
			WHEN C . WOSTATUS = '1' AND C . WOAPPSTATUS = '' THEN '작업요청중' 
			WHEN C . WOSTATUS = '2' AND ( SELECT COUNT ( * ) FROM PSSCMLIB . PSM_SAFEORDER_MASTER WHERE SMWKTEAM = C . WOORTEAM AND SMWKDATE = WOORDATE AND SMWKSEQ = WOSEQ ) > 0 THEN '안전작업허가 작업중' 
				WHEN C . WOSTATUS = '2' AND C . WOAPPSTATUS = 'F' THEN 'JSA 완료' 
			WHEN C . WOSTATUS = '3' AND C . WOAPPSTATUS = 'F' THEN '가동전점검 완료' 
			WHEN C . WOSTATUS = '5' AND C . WOAPPSTATUS = 'F' THEN '공사 완료' 
			WHEN C . WOSTATUS = 'A' AND C . WOAPPSTATUS = 'F' THEN '변경요구서 완료' 
			WHEN C . WOSTATUS = 'R' AND C . WOAPPSTATUS = 'F' THEN '변경검토서 완료' 
			ELSE ( SELECT A . WOSTATUS 
			FROM PSSCMLIB . CV_PSM_WORKSTATUSLIST A 
				WHERE A . APP_NUM = C . WOORTEAM || '-' || C . WOORDATE || '-' || DIGITS ( C . WOSEQ ) ) END ) AS WOSTATUS , 
  
			( SELECT VALUE ( MAX ( SMWKORAPPDATE ) , 0 ) 
			FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
			WHERE SMWKTEAM = WOORTEAM 
			AND SMWKDATE = WOORDATE 
			AND SMWKSEQ = WOSEQ ) AS SMWKORAPPDATE , 
			( CASE WHEN C . WOCHANGEWKDIV = '1' THEN 'FINISH'  -- 단순교체이면 조회되게 함 
			ELSE ( CASE WHEN C . WOSTATUS IN ( 'A' , '2' , '3' , '5' ) AND ( SELECT COUNT ( * ) FROM PSSCMLIB . PSM_CHANGEASK_DOC 
				WHERE CAWOTEAM = C . WOORTEAM 
																	AND CAWODATE = C . WOORDATE 
																	AND CAWOSEQ = C . WOSEQ 
																	AND CAASKCLASS = 'C' ) = 1 THEN 'FINISH' 
					WHEN C . WOSTATUS IN ( 'R' , '2' , '3' , '5' ) AND ( SELECT COUNT ( * ) FROM PSSCMLIB . PSM_CHANGEASK_DOC 
							WHERE CAWOTEAM = C . WOORTEAM 
																	AND CAWODATE = C . WOORDATE 
																	AND CAWOSEQ = C . WOSEQ 
																	AND CAASKCLASS <> 'C' 
																	AND CAASKSTEPGN <> '1' ) = 1 THEN 'FINISH' 
END ) 
			END ) AS GUBUN , 
  
			( CASE WHEN C . WOSTATUS = '5' AND C . WOAPPSTATUS = 'F' THEN '5'  -- 공사완료 
			ELSE '1' END ) AS WORKSTATUS  -- 진행중 
		FROM PSSCMLIB . PSM_WORKORDER C 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S1 
		ON S1 . FXC3SAUP || S1 . FXC3BCODE || DIGITS ( S1 . FXC3MCODE ) || DIGITS ( S1 . FXC3SCODE ) = WOLOCATIONCODE1 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S2 
		ON S2 . FXC3SAUP || S2 . FXC3BCODE || DIGITS ( S2 . FXC3MCODE ) || DIGITS ( S2 . FXC3SCODE ) = WOLOCATIONCODE2 
		LEFT OUTER JOIN TYSCMLIB . INKIBNMF K1 
		ON K1 . KBSABUN = WOORSABUN 
		LEFT OUTER JOIN TYSCMLIB . INKIBNMF K2 
		ON K2 . KBSABUN = WOSAFESABUN 
		LEFT OUTER JOIN ( SELECT CAST ( P_STDATE AS VARCHAR ( 8 ) ) AS SDATE , 
					CAST ( P_EDDATE AS VARCHAR ( 8 ) ) AS EDATE , 
					CAST ( P_WKSAUP AS VARCHAR ( 1 ) ) AS WKSAUP , 
					CAST ( P_WKTEAM AS VARCHAR ( 6 ) ) AS WKTEAM , 
					CAST ( P_STATUS AS VARCHAR ( 20 ) ) AS STATUS , 
					CAST ( P_DEPT AS VARCHAR ( 6 ) ) AS DEPT 
			FROM SYSIBM . SYSDUMMY1 ) AS PAR 
		ON 1 = 1 
		WHERE WOORDATE BETWEEN SDATE AND EDATE 
		AND ( SUBSTR ( WOSOTEAM , 1 , 1 ) || SUBSTR ( WORETEAM , 1 , 1 ) LIKE '%' || PAR . WKSAUP || '%' OR WOSOTEAM = PAR . DEPT ) 
		AND WOSOTEAM LIKE '%' || PAR . WKTEAM || '%' 
		AND WOORSABUN LIKE P_ORSABUN || '%' 
		AND WOWORKTITLE LIKE '%' || P_TITLE || '%' 
		AND WOAPPSTATUS = 'F' 
		) 
  
		SELECT 
		* 
		FROM TABLE1 
		WHERE GUBUN = 'FINISH' 
		AND WORKSTATUS IN ( SELECT DATA FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( P_STATUS , ',' ) ) AS INTABLE ) 
		ORDER BY SMWKORAPPDATE DESC , APP_NUM DESC ; 
		 
	OPEN REFCURSOR ; 
  
END;