DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_WKCODE_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_WKCODE_LIST
( 
	IN P_SWWKTEAM    VARCHAR(6),
	IN P_SWWKDATE    VARCHAR(8),
	IN P_SWWKSEQ     NUMERIC(3,0),
	IN P_SWORAPPDATE VARCHAR(8),
	IN P_SWORSEQ     NUMERIC(3,0)
) 

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- Ω√¿€
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
			SWWKCODE
		FROM PSSCMLIB.PSM_SAFEORDER_WKCODE
		WHERE SWWKTEAM    = P_SWWKTEAM
		AND   SWWKDATE    = P_SWWKDATE
		AND   SWWKSEQ     = P_SWWKSEQ
		AND   SWORAPPDATE = P_SWORAPPDATE
		AND   SWORSEQ     = P_SWORSEQ;

	OPEN REFCURSOR;
END;