--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MAIL_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MAIL_LIST ( 
	IN P_KBSABUN VARCHAR(3000),
	IN P_GUBUN   VARCHAR(1)) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 矫累 

	IF(P_GUBUN = '') THEN

		MAIN : BEGIN  -- 角青何 

			DECLARE REFCURSOR CURSOR WITH RETURN FOR

				SELECT
					DISTINCT
					KBSABUN,
					KBMAILID,					
					KBHANGL
				FROM TYSCMLIB.INKIBNMF
				WHERE KBCOMPANY = '2'
				AND   KBSABUN   IN(SELECT * FROM TABLE(PSSCMLIB.SF_GB_RevColRow(P_KBSABUN, ',')) AS InTable )
				AND    KBIGUBN NOT IN ('560','900')
				AND   KBMAILID <> '';

			OPEN REFCURSOR;

		END MAIN;

	ELSE

		MAIN1 : BEGIN  -- 角青何 

			DECLARE REFCURSOR1 CURSOR WITH RETURN FOR

				SELECT
					DISTINCT
					KBSABUN,
					KBMAILID,
					KBHANGL
				FROM TYSCMLIB.INKIBNMF
				WHERE KBCOMPANY = '2'
				AND   KBSABUN   IN(SELECT * FROM TABLE(PSSCMLIB.SF_GB_RevColRow(P_KBSABUN, ',')) AS InTable )
				AND   SUBSTR(KBBUSEO,1,1) <> 'D'
				AND   KBMAILID <> '';

			OPEN REFCURSOR1;

		END MAIN1;		
	
	END IF;
END;


CALL PSSCMLIB.PSM_PSM4041_SAFEORDER_MAIL_LIST('0287-M', '');