--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_AUTH;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_AUTH ( 
	IN P_USRID VARCHAR(6)) 

	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4041_SAFEORDER_AUTH 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   

P1 : BEGIN

	MAIN : BEGIN  -- ½ÇÇàºÎ
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				GRPID
			FROM TYJINFWLIB.ORG_GROUPUSR 
			WHERE SUBSTR(GRPID,1,4) = 'SAFE'
			AND   USRID = P_USRID;

		OPEN REFCURSOR;
	END MAIN;

END P1;