--DROP PROCEDURE PSSCMLIB.PSM_PSM4030_CHANGEREV_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4030_CHANGEREV_LIST ( 
	IN P_CRASKTEAM VARCHAR(6),
	IN P_CRASKDATE VARCHAR(8),
	IN P_CRASKSEQ  NUMERIC(3,0)
)

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 

	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				CAASKACYEAR||'-'||DIGITS(CAASKACSEQ) AS CAASKNO, -- 요구접수번호
				CRASKTEAM || '-' || CRASKDATE || '-' || DIGITS ( CRASKSEQ ) AS ASK_NUM , 
				CRWOTEAM  || '-' || CRWODATE || '-' || DIGITS ( CRWOSEQ ) AS WORK_NUM , 
				CRREVTEAM || '-' || CRREVDATE || '-' || DIGITS ( CRREVSEQ ) AS REV_NUM , 
				CRREVCONTENT,    -- 검토항목
				CRREVREASION,    -- 검토사유
				(CASE WHEN CRREVAPPROVAL = 'Y' THEN '승인' ELSE '미승인' END) AS CRREVAPPROVAL,   -- 승인, 미승인
				CRREVAPPSABUN,   -- 검토자사번
				KBHANGL,         -- 검토자
				CRREVAPPDATE,    -- 검토완료일자
				CARECEIPTDATE,   -- 접수일자
				CAASKSTEPGN,     -- 변경 종류
			FROM PSSCMLIB.PSM_CHANGEREV_DOC AS REV
			LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
			ON    CRREVAPPSABUN = KBSABUN
			LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC AS ASK
			ON    CRASKTEAM = CAASKTEAM
			AND   CRASKDATE = CAASKDATE
			AND   CRASKSEQ  = CAASKSEQ
			WHERE CRASKTEAM = P_CRASKTEAM
			AND   CRASKDATE = P_CRASKDATE
			AND   CRASKSEQ  = P_CRASKSEQ;

		OPEN REFCURSOR;
	END MAIN;
END;

CALL PSSCMLIB.PSM_PSM4030_CHANGEREV_LIST('A20000', '20230925', 1);