--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MASTER_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MASTER_DEL ( 
	IN P_JSMWKGUBN VARCHAR(1) , 
	IN P_JSMPOTEAM VARCHAR(6) , 
	IN P_JSMPODATE VARCHAR(8) , 
	IN P_JSMPOSEQ NUMERIC(3,0) , 
	IN P_JSMDATE VARCHAR(8) , 
	IN P_JSMMSEQ NUMERIC(3,0) , 
	IN P_JSMBLASS VARCHAR(2) , 
	IN P_JSMMLASS VARCHAR(2) , 
	IN P_JSMSLASS VARCHAR(3) , 
	IN P_JSMSEQ NUMERIC(3,0)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 

		-- 작성 마스터 삭제
		DELETE FROM PSSCMLIB.PSM_JSALOG_MASTER
		WHERE  JSLWKGUBN = P_JSMWKGUBN
		AND    JSLWKTEAM = P_JSMPOTEAM
		AND    JSLWKDATE = P_JSMPODATE
		AND    JSLWKSEQ = P_JSMPOSEQ
		AND    JSLDATE = P_JSMDATE
		AND    JSLSEQ = P_JSMMSEQ ;
	 
		-- 마스터 삭제
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_MASTER
		WHERE JSMWKGUBN = P_JSMWKGUBN
		AND   JSMPOTEAM = P_JSMPOTEAM
		AND   JSMPODATE = P_JSMPODATE
		AND   JSMPOSEQ  = P_JSMPOSEQ
		AND   JSMDATE   = P_JSMDATE
		AND   JSMMSEQ   = P_JSMMSEQ
		AND   JSMBLASS  = P_JSMBLASS
		AND   JSMMLASS  = P_JSMMLASS
		AND   JSMSLASS  = P_JSMSLASS
		AND   JSMSEQ    = P_JSMSEQ ;

		-- 안전장비 삭제
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
		WHERE JSTWKGUBN = P_JSMWKGUBN
		AND   JSTPOTEAM = P_JSMPOTEAM
		AND   JSTPODATE = P_JSMPODATE
		AND   JSTPOSEQ  = P_JSMPOSEQ  
		AND   JSTDATE   = P_JSMDATE  
		AND   JSTMSEQ   = P_JSMMSEQ  
		AND   JSTBLASS  = P_JSMBLASS 
		AND   JSTMLASS  = P_JSMMLASS 
		AND   JSTSLASS  = P_JSMSLASS
		AND   JSTSEQ    = P_JSMSEQ ;

		-- 디테일 삭제
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_DETAIL
		WHERE JSDWKGUBN = P_JSMWKGUBN
		AND   JSDPOTEAM = P_JSMPOTEAM
		AND   JSDPODATE = P_JSMPODATE
		AND   JSDPOSEQ  = P_JSMPOSEQ
		AND   JSDDATE   = P_JSMDATE
		AND   JSDMSEQ   = P_JSMMSEQ
		AND   JSDBLASS  = P_JSMBLASS
		AND   JSDMLASS  = P_JSMMLASS
		AND   JSDSLASS  = P_JSMSLASS
		AND   JSDSEQ    = P_JSMSEQ ;

		-- 위험성 삭제
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_RISK
		WHERE JSRWKGUBN = P_JSMWKGUBN
		AND   JSRPOTEAM = P_JSMPOTEAM
		AND   JSRPODATE = P_JSMPODATE
		AND   JSRPOSEQ  = P_JSMPOSEQ
		AND   JSRDATE   = P_JSMDATE
		AND   JSRMSEQ   = P_JSMMSEQ
		AND   JSRBLASS  = P_JSMBLASS
		AND   JSRMLASS  = P_JSMMLASS
		AND   JSRSLASS  = P_JSMSLASS
		AND   JSRSEQ    = P_JSMSEQ ;

		-- 개선대책 삭제
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_REFORM
		WHERE JSEWKGUBN = P_JSMWKGUBN
		AND   JSEPOTEAM = P_JSMPOTEAM
		AND   JSEPODATE = P_JSMPODATE
		AND   JSEPOSEQ  = P_JSMPOSEQ
		AND   JSEDATE   = P_JSMDATE
		AND   JSEMSEQ   = P_JSMMSEQ
		AND   JSEBLASS  = P_JSMBLASS
		AND   JSEMLASS  = P_JSMMLASS
		AND   JSESLASS  = P_JSMSLASS
		AND   JSESEQ    = P_JSMSEQ ;

		-- 첨부파일 삭제 (수정해야함)
		DELETE FROM PSSCMLIB . PSM_CMN_ATTACH
		WHERE ATTACH_TYPE = 'JSA'
		AND    SUBSTR(ATTACH_NO,1,1) = P_JSMWKGUBN
		AND    SUBSTR(ATTACH_NO,2,6) = P_JSMPOTEAM
		AND    SUBSTR(ATTACH_NO,8,8) = P_JSMPODATE
		AND    CAST  (SUBSTR(ATTACH_NO,16,3) AS NUMERIC(3 , 0)) = P_JSMPOSEQ
		AND    SUBSTR(ATTACH_NO,19,8) = P_JSMDATE
		AND    CAST  (SUBSTR(ATTACH_NO,27,3) AS NUMERIC(3 , 0)) = P_JSMMSEQ
		AND    SUBSTR(ATTACH_NO,30,2) = P_JSMBLASS
		AND    SUBSTR(ATTACH_NO,32,2) = P_JSMMLASS
		AND    SUBSTR(ATTACH_NO,34,3) = P_JSMSLASS
		AND    CAST  (SUBSTR(ATTACH_NO,37,3) AS NUMERIC(3 , 0)) = P_JSMSEQ ;
  
END P1  ; 
  