--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_CANCEL_ADD;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_CANCEL_ADD
(
	  IN P_WOORTEAM        VARCHAR(6),
	  IN P_WOORDATE        VARCHAR(8),
	  IN P_WOSEQ           NUMERIC(3,0),
	  IN P_WOCANCELSABUN   VARCHAR(6),
	  IN P_WOCANCELCOMMENT VARCHAR(100),
	  IN P_GUBUN           VARCHAR(1)
)

LANGUAGE SQL

P1: BEGIN

	IF P_GUBUN = '1' THEN

		UPDATE PSSCMLIB.PSM_WORKORDER SET
			WOCANCELSABUN1   = P_WOCANCELSABUN,
			WOCANCELCOMMENT1 = P_WOCANCELCOMMENT,
			WOCANCELDATE1    = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ),
			WOCANCELTIME1    = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' )
		WHERE WOORTEAM = P_WOORTEAM
		AND   WOORDATE = P_WOORDATE
		AND   WOSEQ    = P_WOSEQ;

	ELSEIF P_GUBUN = '2' THEN

		UPDATE PSSCMLIB.PSM_WORKORDER SET
			WOCANCELSABUN2   = P_WOCANCELSABUN,
			WOCANCELCOMMENT2 = P_WOCANCELCOMMENT,
			WOCANCELDATE2    = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ),
			WOCANCELTIME2    = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' )
		WHERE WOORTEAM = P_WOORTEAM
		AND   WOORDATE = P_WOORDATE
		AND   WOSEQ    = P_WOSEQ;

	ELSEIF P_GUBUN = '3' THEN

		UPDATE PSSCMLIB.PSM_WORKORDER SET
			WOCANCELSABUN3   = P_WOCANCELSABUN,
			WOCANCELCOMMENT3 = P_WOCANCELCOMMENT,
			WOCANCELDATE3    = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ),
			WOCANCELTIME3    = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' )
		WHERE WOORTEAM = P_WOORTEAM
		AND   WOORDATE = P_WOORDATE
		AND   WOSEQ    = P_WOSEQ;

	END IF;	

END P1;