DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_FINISH_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_FINISH_RUN ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0) ) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR

			SELECT
				(CASE WHEN WOIMMEDGUBN <> 'Y' THEN 'N' ELSE 'Y' END) AS WOIMMEDGUBN,
				WOIMMEDTEXT
			FROM PSSCMLIB.PSM_WorkOrder
			WHERE WOORTEAM = P_WOORTEAM
			AND   WOORDATE = P_WOORDATE
			AND   WOSEQ    = P_WOSEQ;

		OPEN REFCURSOR;
	END MAIN;
END;