--DROP PROCEDURE PSSCMLIB.PSM_PSM4040_REFERENCE_COPY;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_REFERENCE_COPY
(
	IN P_NEW_REDOCNUM  VARCHAR(50),
	IN P_HISAB         VARCHAR(6),
	IN P_REDOCID       VARCHAR(2),
	IN P_REDOCNUM      VARCHAR(50)
)

LANGUAGE SQL

P1: BEGIN

	IF EXISTS(SELECT REDOCID FROM PSSCMLIB.PSM_Reference WHERE REDOCID  = P_REDOCID
	                                                     AND   REDOCNUM = P_REDOCNUM
							     AND   RESABUN <> '') THEN

		INSERT INTO PSSCMLIB.PSM_Reference
		(
			REDOCID,
			REDOCNUM,
			RESABUN,
			RENAME,
			REHIGB,
			REHIDAT,
			REHITIM,
			REHISAB
		)
		SELECT
			REDOCID,
			CAST(P_NEW_REDOCNUM AS VARCHAR(28)) AS REDOCNUM,
			RESABUN,
			RENAME,
			'A' AS SMHIGB,
			CURRENT_DATE AS SMHIDAT,
			CURRENT_TIME AS SMHITIM,
			CAST(P_HISAB AS VARCHAR(6)) AS SMHISAB
		FROM PSSCMLIB.PSM_Reference
		WHERE REDOCID  = P_REDOCID
		AND   REDOCNUM = P_REDOCNUM;

	END IF;

END P1;