--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_MENU_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_MENU_LIST ( 
	IN P_PECCGUBUN VARCHAR(1),
	IN P_PECCDATE VARCHAR(8))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PECCGUBUN,
		CASE WHEN PECCGUBUN = '1' THEN '일반' ELSE '화물' END PECCGUBUNNM,
		PECCDATE,
		PECCSEQ,
		'선택' AS BTN_SEL
		FROM PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
		WHERE (CASE WHEN P_PECCGUBUN = '' THEN '1' ELSE PECCGUBUN END) = (CASE WHEN P_PECCGUBUN = '' THEN '1' ELSE P_PECCGUBUN END)
		AND   (CASE WHEN P_PECCDATE = '' THEN '1' ELSE PECCDATE END) = (CASE WHEN P_PECCDATE = '' THEN '1' ELSE P_PECCDATE END)
		GROUP BY PECCGUBUN, PECCDATE, PECCSEQ
		ORDER BY PECCGUBUN, PECCDATE DESC, PECCSEQ DESC
		 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 