--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4047_JSACHANGE_REFORM_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4047_JSACHANGE_REFORM_RUN ( 
	IN P_JSEWKGUBN VARCHAR(1),
	IN P_JSEPOTEAM VARCHAR(6),
	IN P_JSEPODATE VARCHAR(8),
	IN P_JSEPOSEQ NUMERIC(3,0),
	IN P_JSEDATE VARCHAR(8),
	IN P_JSEMSEQ NUMERIC(3,0),
	IN P_JSEBLASS VARCHAR(2),
	IN P_JSEMLASS VARCHAR(2),
	IN P_JSESLASS VARCHAR(3),
	IN P_JSESEQ NUMERIC(3,0),
	IN P_JSEITEMSEQ NUMERIC(3,0),
	IN P_JSESUBSEQ NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		JSESUBSEQ,
		JSEREFORMTEXT,
		JSEREFORMCNT,
		JSEREFORMSOLID,
		JSEREFORMDEGREE
		FROM PSSCMLIB.PSM_JSACHANGE_REFORM
		WHERE JSEWKGUBN  = P_JSEWKGUBN
		AND   JSEPOTEAM  = P_JSEPOTEAM
		AND   JSEPODATE  = P_JSEPODATE
		AND   JSEPOSEQ   = P_JSEPOSEQ
		AND   JSEDATE    = P_JSEDATE
		AND   JSEMSEQ    = P_JSEMSEQ  
		AND   JSEBLASS   = P_JSEBLASS
		AND   JSEMLASS   = P_JSEMLASS
		AND   JSESLASS   = P_JSESLASS
		AND   JSESEQ     = P_JSESEQ
		AND   JSEITEMSEQ = P_JSEITEMSEQ
		AND   JSESUBSEQ  = P_JSESUBSEQ
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 