DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SYULBI_CHECK;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SYULBI_CHECK (
	IN P_SMSYSTEMCODE1   VARCHAR(10),
	IN P_SMSYSTEMCODE2   VARCHAR(10),
	IN P_SMSYSTEMCODE3   VARCHAR(10),
	IN P_SMSYSTEMCODE4   VARCHAR(10),
	IN P_SMSYSTEMCODE5   VARCHAR(10),
	IN P_SMWKTEAM         VARCHAR(6),
	IN P_SMWKDATE         VARCHAR(8),
	IN P_SMWKSEQ          NUMERIC(3,0),
	IN P_SMWKORAPPDATE    VARCHAR(8),
	IN P_SMWKORSEQ        NUMERIC(3,0)) 

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- 矫累

	DECLARE V_SYULBI  VARCHAR(10);
	DECLARE V_SILOBIN VARCHAR(10);

	SET V_SYULBI  = '';
	SET V_SILOBIN = '';

	IF ( P_SMSYSTEMCODE1 <> '' ) THEN 

		SET V_SYULBI = P_SMSYSTEMCODE1;

		IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN

			SELECT
			FXC2DESC INTO V_SILOBIN 
			FROM TYSCMLIB . ACFIXCLASS2 
			WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
			AND FXC2SAUP  = SUBSTR ( V_SYULBI , 1 , 1 ) 
			AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
			AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
			AND CHAR ( FXC2MCODE ) = FXC2DESC;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE2 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE2;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE3 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE3;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE4 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE4;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE5 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE5;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	
IF ( V_SILOBIN <> '' ) THEN 
		
		MAIN : BEGIN  -- 角青何

			DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
				SELECT
				CLWKTEAM
				FROM TYSCMLIB.BIN_CLEANF
				WHERE CLWKTEAM      = P_SMWKTEAM
				AND   CLWKDATE      = P_SMWKDATE
				AND   CLWKSEQ       = P_SMWKSEQ
				AND   CLWKORAPPDATE = P_SMWKORAPPDATE
				AND   CLWKORSEQ     = P_SMWKORSEQ
				AND   CLBINNO       = V_SILOBIN
				AND   CLSSUTIME     <> ''
				AND   CLESUTIME     = '';
	
			OPEN REFCURSOR;

		END MAIN;

	ELSE
	LIST : BEGIN  -- 角青何

			DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
				SELECT '' AS CLWKTEAM
				FROM SYSIBM.SYSDUMMY1;

			OPEN REFCURSOR;

		END LIST;

	END IF;
END;


CALL PSSCMLIB.PSM_PSM4041_SYULBI_CHECK('S300311008','','','','','S10000','20230827',5,'20230830',1);