--DROP PROCEDURE PSSCMLIB.PSM_PSM4040_SAFEORDER_CHK;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_SAFEORDER_CHK
(
	IN P_SMWKTEAM      VARCHAR(6),
	IN P_SMWKDATE      VARCHAR(8),
	IN P_SMWKSEQ       NUMERIC(3,0),
    IN P_SMWKORAPPDATE VARCHAR(8)
)

RESULT SETS 1
LANGUAGE SQL

P1: BEGIN

	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT
		*
		FROM PSSCMLIB.PSM_SafeOrder_MASTER
		WHERE SMWKTEAM      = P_SMWKTEAM
		AND   SMWKDATE      = P_SMWKDATE
		AND   SMWKSEQ       = P_SMWKSEQ
		AND   SMWKORAPPDATE = P_SMWKORAPPDATE;

	OPEN REFCURSOR;

END P1;