--DROP PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_DEL
(
	IN P_CRREVTEAM      VARCHAR(6),    -- 변경검토번호(팀)
	IN P_CRREVDATE      VARCHAR(8),    -- 변경검토번호(일자)
	IN P_CRREVSEQ       NUMERIC(3,0)   -- 변경검토번호(순번)
)

LANGUAGE SQL

P1: BEGIN
	
	DELETE FROM PSSCMLIB.PSM_CHANGEREV_DOC
	WHERE CRREVTEAM = P_CRREVTEAM
	AND   CRREVDATE = P_CRREVDATE
	AND   CRREVSEQ  = P_CRREVSEQ;

END P1;