DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_GET_APPDATE;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_GET_APPDATE ( 
	IN P_SMWKTEAM VARCHAR(6),
	IN P_SMWKDATE VARCHAR(8),
	IN P_SMWKSEQ  NUMERIC(3,0)) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- Ω√¿€ 

	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT
			MIN(SMWKORAPPDATE) AS STDATE,
			MAX(SMWKORAPPDATE) AS EDDATE
		FROM PSSCMLIB.PSM_SafeOrder_MASTER
		WHERE SMWKTEAM = P_SMWKTEAM
		AND   SMWKDATE = P_SMWKDATE
		AND   SMWKSEQ  = P_SMWKSEQ;
		 
	OPEN REFCURSOR;
  
END;