--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_SAV;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_SAV ( 

	IN P_DRWKTEAM        VARCHAR(6),
    IN P_DRWKDATE        VARCHAR(8),
	IN P_DRWKSEQ         NUMERIC(3,0),
	IN P_DRORAPPDATE     VARCHAR(8),
	IN P_DRORSEQ         NUMERIC(3,0),
	IN P_DRCODE          VARCHAR(3),
	IN P_DRCODENAME      VARCHAR(100),
	IN P_DRYESSEL        VARCHAR(1),
	IN P_DRNOSEL         VARCHAR(1),
	IN P_DRNASEL         VARCHAR(1),
	IN P_DRSORT          VARCHAR(30),
	IN P_DRSTAND         VARCHAR(30),
	IN P_DRDEPTH         VARCHAR(30),
	IN P_DRSABUN         VARCHAR(6),
	IN P_DRHISAB         VARCHAR(6)
)

LANGUAGE SQL

P1: BEGIN  

	INSERT INTO PSSCMLIB.PSM_SAFEORDER_DRCODE
	(
		DRWKTEAM,
		DRWKDATE,
		DRWKSEQ,
		DRORAPPDATE,
		DRORSEQ,
		DRCODE,
		DRCODENAME,
		DRYESSEL,
		DRNOSEL,
		DRNASEL,
		DRSORT,
		DRSTAND,
		DRDEPTH,
		DRSABUN,
		DRHIGB,
		DRHIDAT,
		DRHITIM,
		DRHISAB
	)
	VALUES
	(
		P_DRWKTEAM,
		P_DRWKDATE,
		P_DRWKSEQ,
		P_DRORAPPDATE,
		P_DRORSEQ,
		P_DRCODE1,
		P_DRCODENAME,
		P_DRYESSEL,
		P_DRNOSEL,
		P_DRNASEL,
		P_DRSORT,
		P_DRSTAND,
		P_DRDEPTH,
		P_DRSABUN,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_DRHISAB
	);

END P1;