--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_LAST_CHECK;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_LAST_CHECK ( 
	IN P_SMWKTEAM VARCHAR(6) , 
	IN P_SMWKDATE VARCHAR(8) , 
	IN P_SMWKSEQ  NUMERIC(3, 0)
	) 

DYNAMIC RESULT SETS 1
LANGUAGE SQL 
	
MAIN : BEGIN  -- 시작 
	P1 : BEGIN  -- 마스타 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				SMWKTEAM,
				SMWKDATE,
				SMWKSEQ,
				SMWKORAPPDATE,
				SMWKORSEQ
			FROM PSSCMLIB.PSM_SAFEORDER_MASTER
			WHERE SMWKTEAM = P_SMWKTEAM
			AND   SMWKDATE = P_SMWKDATE
			AND   SMWKSEQ  = P_SMWKSEQ
			ORDER BY SMWKORAPPDATE DESC, SMWKORSEQ DESC
			FETCH FIRST 1 ROWS ONLY;

		OPEN REFCURSOR;
	END P1;
END;

CALL PSSCMLIB.PSM_PSM4041_SAFEORDER_LAST_CHECK('A20000','20230327', 1);