--DROP PROCEDURE PSSCMLIB.PSM_PSM4040_GET_MAX_SMWKORSEQ;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_GET_MAX_SMWKORSEQ ( 
	IN P_SMWKTEAM      VARCHAR(6),
	IN P_SMWKDATE      VARCHAR(8),
	IN P_SMWKSEQ       NUMERIC(3,0),
	IN P_SMWKORAPPDATE VARCHAR(8)
	) 

	DYNAMIC RESULT SETS 1 

P1 : BEGIN
	
	MAIN : BEGIN  -- ½ÇÇàºÎ

		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				VALUE(MAX(SMWKORSEQ) + 1, 1) AS SMWKORSEQ
			FROM PSSCMLIB.PSM_SafeOrder_MASTER
			WHERE SMWKTEAM      = P_SMWKTEAM
			AND   SMWKDATE      = P_SMWKDATE
			AND   SMWKSEQ       = P_SMWKSEQ
			AND   SMWKORAPPDATE = P_SMWKORAPPDATE;

		OPEN REFCURSOR;

	END MAIN;

END P1;

CALL PSSCMLIB.PSM_PSM4040_GET_MAX_SMWKORSEQ('A20000','20230703', 1, '20230803');