DROP PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_APP_DSP;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_WORKORDER_APP_DSP ( 
	IN P_WOORTEAM VARCHAR(6) , 
	IN P_WOORDATE VARCHAR(8) , 
	IN P_WOSEQ NUMERIC(3, 0) ) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 
	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				WOAPPSODATE1 , 
				WOAPPSOTIME1 , 
				WOAPPSODATE2 , 
				WOAPPSOTIME2 , 
				WOAPPSODATE3 , 
				WOAPPSOTIME3 , 
				WOAPPSODATE4 , 
				WOAPPSOTIME4 , 
				WOAPPSODATE5 , 
				WOAPPSOTIME5 , 
				WOAPPREDATE1 , 
				WOAPPRETIME1 , 
				WOAPPREDATE2 , 
				WOAPPRETIME2 , 
				WOAPPREDATE3 , 
				WOAPPRETIME3 , 
				WOAPPREDATE4 , 
				WOAPPRETIME4 , 
				WOAPPREDATE5 , 
				WOAPPRETIME5 , 
				WOAPPSOSABUN1 , 
				WOAPPSOSABUN2 , 
				WOAPPSOSABUN3 , 
				WOAPPSOSABUN4 , 
				WOAPPSOSABUN5 , 
				WOAPPRESABUN1 , 
				WOAPPRESABUN2 , 
				WOAPPRESABUN3 , 
				WOAPPRESABUN4 , 
				WOAPPRESABUN5 ,

				/* 사인 */

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN1
				) AS SOIMGNAME1, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN1
				) AS SOIMGSIZE1, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN1
				) AS SOIMGSIGN1,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN2
				) AS SOIMGNAME2, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN2
				) AS SOIMGSIZE2, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN2
				) AS SOIMGSIGN2, 

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN3
				) AS SOIMGNAME3, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN3
				) AS SOIMGSIZE3, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN3
				) AS SOIMGSIGN3,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN4
				) AS SOIMGNAME4, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN4
				) AS SOIMGSIZE4,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN4
				) AS SOIMGSIGN4,


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN5
				) AS SOIMGNAME5, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN5
				) AS SOIMGSIZE5,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPSOSABUN5
				) AS SOIMGSIGN5,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN1
				) AS REIMGNAME1, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN1
				) AS REIMGSIZE1, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN1
				) AS REIMGSIGN1, 


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN2
				) AS REIMGNAME2, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN2
				) AS REIMGSIZE2, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN2
				) AS REIMGSIGN2, 

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN3
				) AS REIMGNAME3, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN3
				) AS REIMGSIZE3, 
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN3
				) AS REIMGSIGN3,

				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN4
				) AS REIMGNAME4, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN4
				) AS REIMGSIZE4,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN4
				) AS REIMGSIGN4,


				(SELECT
					FILE_NAME
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN5
				) AS REIMGNAME5, 
				(SELECT
					FILE_SIZE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN5
				) AS REIMGSIZE5,
				(SELECT
					ATTACH_BYTE
				 FROM PSSCMLIB.PSM_CMN_ATTACH
				 WHERE ATTACH_TYPE = 'SG'
				 AND   ATTACH_NO = WOAPPRESABUN5
				) AS REIMGSIGN5
				/* 사인 */
				/*
				SOIMG1 . IMGFILENAME AS SOIMGNAME1 , 
				SOIMG1 . IMGFILESIZE AS SOIMGSIZE1 , 
				SOIMG1 . IMGSIGN AS SOIMGSIGN1 , 
				SOIMG2 . IMGFILENAME AS SOIMGNAME2 , 
				SOIMG2 . IMGFILESIZE AS SOIMGSIZE2 , 
				SOIMG2 . IMGSIGN AS SOIMGSIGN2 , 
				SOIMG3 . IMGFILENAME AS SOIMGNAME3 , 
				SOIMG3 . IMGFILESIZE AS SOIMGSIZE3 , 
				SOIMG3 . IMGSIGN AS SOIMGSIGN3 , 
				SOIMG4 . IMGFILENAME AS SOIMGNAME4 , 
				SOIMG4 . IMGFILESIZE AS SOIMGSIZE4 , 
				SOIMG4 . IMGSIGN AS SOIMGSIGN4 , 
				SOIMG5 . IMGFILENAME AS SOIMGNAME5 , 
				SOIMG5 . IMGFILESIZE AS SOIMGSIZE5 , 
				SOIMG5 . IMGSIGN AS SOIMGSIGN5 , 
				REIMG1 . IMGFILENAME AS REIMGNAME1 , 
				REIMG1 . IMGFILESIZE AS REIMGSIZE1 , 
				REIMG1 . IMGSIGN AS REIMGSIGN1 , 
				REIMG2 . IMGFILENAME AS REIMGNAME2 , 
				REIMG2 . IMGFILESIZE AS REIMGSIZE2 , 
				REIMG2 . IMGSIGN AS REIMGSIGN2 , 
				REIMG3 . IMGFILENAME AS REIMGNAME3 , 
				REIMG3 . IMGFILESIZE AS REIMGSIZE3 , 
				REIMG3 . IMGSIGN AS REIMGSIGN3 , 
				REIMG4 . IMGFILENAME AS REIMGNAME4 , 
				REIMG4 . IMGFILESIZE AS REIMGSIZE4 , 
				REIMG4 . IMGSIGN AS REIMGSIGN4 , 
				REIMG5 . IMGFILENAME AS REIMGNAME5 , 
				REIMG5 . IMGFILESIZE AS REIMGSIZE5 , 
				REIMG5 . IMGSIGN AS REIMGSIGN5
				*/
			FROM PSSCMLIB . PSM_WORKORDER 
			/*
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS SOIMG1 
			ON SOIMG1 . IMGSABUN = WOAPPSOSABUN1 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS SOIMG2 
			ON SOIMG2 . IMGSABUN = WOAPPSOSABUN2 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS SOIMG3 
			ON SOIMG3 . IMGSABUN = WOAPPSOSABUN3 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS SOIMG4 
			ON SOIMG4 . IMGSABUN = WOAPPSOSABUN4 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS SOIMG5 
			ON SOIMG5 . IMGSABUN = WOAPPSOSABUN5 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS REIMG1 
			ON REIMG1 . IMGSABUN = WOAPPRESABUN1 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS REIMG2 
			ON REIMG2 . IMGSABUN = WOAPPRESABUN2 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS REIMG3 
			ON REIMG3 . IMGSABUN = WOAPPRESABUN3 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS REIMG4 
			ON REIMG4 . IMGSABUN = WOAPPRESABUN4 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS REIMG5 
			ON REIMG5 . IMGSABUN = WOAPPRESABUN5
			*/
			WHERE WOORTEAM = P_WOORTEAM 
			AND WOORDATE = P_WOORDATE 
			AND WOSEQ = P_WOSEQ ; 
  
		OPEN REFCURSOR ; 
  
END MAIN ; 
  
END;