--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_DEL
(
	IN P_DRWKTEAM      VARCHAR(6) , 
	IN P_DRWKDATE      VARCHAR(8) , 
	IN P_DRWKSEQ       NUMERIC(3, 0),
	IN P_DRORAPPDATE   VARCHAR(8) , 
	IN P_DRORSEQ       NUMERIC(3, 0)
)
LANGUAGE SQL

P1: BEGIN

	DELETE FROM PSSCMLIB.PSM_SAFEORDER_DRCODE
	WHERE DRWKTEAM    = P_DRWKTEAM
	AND   DRWKDATE    = P_DRWKDATE
	AND   DRWKSEQ     = P_DRWKSEQ
	AND   DRORAPPDATE = P_DRORAPPDATE
	AND   DRORSEQ     = P_DRORSEQ;

END P1;