DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_APPROVAL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_APPROVAL ( 
	IN P_PECTEAM     VARCHAR(6),
	IN P_PECDATE     VARCHAR(8),
	IN P_PECSEQ      NUMERIC(3,0),
	IN P_PECWOTEAM   VARCHAR(6),
	IN P_PECWODATE   VARCHAR(8),
	IN P_PECWOSEQ    NUMERIC(3,0),
	IN P_PECTITLE    VARCHAR(200),
	IN P_PECINSDATE  VARCHAR(8),
	IN P_PECSGUBUN   VARCHAR(1),
	IN P_PECSDATE    VARCHAR(8),
	IN P_PECSSEQ     NUMERIC(1,0),
	IN P_PECTANKNO   VARCHAR(4),
	IN P_PECFAULTNM  VARCHAR(200),
	IN P_PECIMPROVE  VARCHAR(200),
	IN P_PECJKCD1    VARCHAR(3),
	IN P_PECJKCDNM1  VARCHAR(20),
	IN P_PECNAME1    VARCHAR(20),
	IN P_PECSABUN1   VARCHAR(6),
	IN P_PECCOMMENT1 VARCHAR(200),
	IN P_PECJKCD2  	 VARCHAR(3), 
	IN P_PECJKCDNM2  VARCHAR(20),
	IN P_PECNAME2  	 VARCHAR(20),
	IN P_PECSABUN2   VARCHAR(6), 
	IN P_PECCOMMENT2 VARCHAR(200),
	IN P_PECJKCD3  	 VARCHAR(3), 
	IN P_PECJKCDNM3  VARCHAR(20),
	IN P_PECNAME3  	 VARCHAR(20),
	IN P_PECSABUN3   VARCHAR(6), 
	IN P_PECCOMMENT3 VARCHAR(200),
	IN P_PECJKCD4    VARCHAR(3), 
	IN P_PECJKCDNM4  VARCHAR(20),
	IN P_PECNAME4    VARCHAR(20),
	IN P_PECSABUN4   VARCHAR(6), 
	IN P_PECCOMMENT4 VARCHAR(200),
	IN P_PECJKCD5    VARCHAR(3), 
	IN P_PECJKCDNM5  VARCHAR(20),
	IN P_PECNAME5    VARCHAR(20),
	IN P_PECSABUN5   VARCHAR(6), 
	IN P_PECCOMMENT5 VARCHAR(200),
	IN P_PECJKCD6    VARCHAR(3), 
	IN P_PECJKCDNM6  VARCHAR(20),
	IN P_PECNAME6  	 VARCHAR(20),
	IN P_PECSABUN6   VARCHAR(6), 
	IN P_PECCOMMENT6 VARCHAR(200),
	IN P_PECHISAB    VARCHAR(6), 
	IN P_COUNT       NUMERIC(1, 0) , 
	IN P_APPROVAL    VARCHAR(1) , 
	IN P_GUBUN VARCHAR (20)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 

	DECLARE V_CNT NUMERIC ( 3 , 0 ) ; 

	SET V_CNT = 0 ; 

	SELECT 
		COUNT ( * ) INTO V_CNT 
	FROM PSSCMLIB . PSM_EXAM_CHECK 
	WHERE PECTEAM   = P_PECTEAM
	AND   PECDATE   = P_PECDATE
	AND   PECSEQ    = P_PECSEQ
	AND   PECWOTEAM = P_PECWOTEAM
	AND   PECWODATE = P_PECWODATE
	AND   PECWOSEQ  = P_PECWOSEQ ; 

	IF ( V_CNT = 0 ) THEN 

		INSERT INTO PSSCMLIB.PSM_EXAM_CHECK
		(
		PECTEAM ,
		PECDATE ,
		PECSEQ ,           
		PECWOTEAM ,
		PECWODATE ,
		PECWOSEQ ,
		PECTITLE ,
		PECINSDATE ,
		PECSGUBUN ,
		PECSDATE ,
		PECSSEQ ,
		PECTANKNO ,
		PECFAULTNM ,
		PECIMPROVE ,
		PECJKCD1 ,
		PECJKCDNM1 ,
		PECNAME1 ,
		PECSABUN1 ,
		PECCOMMENT1,
		PECJKCD2 ,
		PECJKCDNM2 ,
		PECNAME2 ,
		PECSABUN2 ,
		PECCOMMENT2,
		PECJKCD3 ,
		PECJKCDNM3 ,
		PECNAME3 ,
		PECSABUN3 ,
		PECCOMMENT3,
		PECJKCD4 ,
		PECJKCDNM4 ,
		PECNAME4 ,
		PECSABUN4 ,
		PECCOMMENT4,
		PECJKCD5 ,
		PECJKCDNM5 ,
		PECNAME5 ,
		PECSABUN5 ,
		PECCOMMENT5,
		PECJKCD6 ,
		PECJKCDNM6 ,
		PECNAME6 ,
		PECSABUN6 ,
		PECCOMMENT6,
		PECHIGB ,
		PECHIDAT ,
		PECHITIM ,
		PECHISAB   
		)
		VALUES
		(
		P_PECTEAM ,
		P_PECDATE ,
		P_PECSEQ ,           
		P_PECWOTEAM ,
		P_PECWODATE ,
		P_PECWOSEQ ,
		P_PECTITLE ,
		P_PECINSDATE ,
		P_PECSGUBUN ,
		P_PECSDATE ,
		P_PECSSEQ ,
		P_PECTANKNO ,
		P_PECFAULTNM ,
		P_PECIMPROVE ,
		P_PECJKCD1 ,
		P_PECJKCDNM1 ,
		P_PECNAME1 ,
		P_PECSABUN1 ,
		P_PECCOMMENT1,
		P_PECJKCD2 ,
		P_PECJKCDNM2 ,
		P_PECNAME2 ,
		P_PECSABUN2 ,
		P_PECCOMMENT2,
		P_PECJKCD3 ,
		P_PECJKCDNM3 ,
		P_PECNAME3 ,
		P_PECSABUN3 ,
		P_PECCOMMENT3,
		P_PECJKCD4 ,
		P_PECJKCDNM4 ,
		P_PECNAME4 ,
		P_PECSABUN4 ,
		P_PECCOMMENT4,
		P_PECJKCD5 ,
		P_PECJKCDNM5 ,
		P_PECNAME5 ,
		P_PECSABUN5 ,
		P_PECCOMMENT5,
		P_PECJKCD6 ,
		P_PECJKCDNM6 ,
		P_PECNAME6 ,
		P_PECSABUN6 ,
		P_PECCOMMENT6,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_PECHISAB
		)
		;
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_EXAM_CHECK SET
		PECTITLE    = P_PECTITLE   ,
		PECINSDATE  = P_PECINSDATE ,
		PECSGUBUN   = P_PECSGUBUN  ,
		PECSDATE    = P_PECSDATE   ,
		PECSSEQ     = P_PECSSEQ    ,
		PECTANKNO   = P_PECTANKNO  ,
		PECFAULTNM  = P_PECFAULTNM ,
		PECIMPROVE  = P_PECIMPROVE ,
		PECJKCD1    = P_PECJKCD1   ,
		PECJKCDNM1  = P_PECJKCDNM1 ,
		PECNAME1    = P_PECNAME1   ,
		PECSABUN1   = P_PECSABUN1  ,
		PECCOMMENT1 = P_PECCOMMENT1,
		PECJKCD2    = P_PECJKCD2   ,
		PECJKCDNM2  = P_PECJKCDNM2 ,
		PECNAME2    = P_PECNAME2   ,
		PECSABUN2   = P_PECSABUN2  ,
		PECCOMMENT2 = P_PECCOMMENT2,
		PECJKCD3    = P_PECJKCD3   ,
		PECJKCDNM3  = P_PECJKCDNM3 ,
		PECNAME3    = P_PECNAME3   ,
		PECSABUN3   = P_PECSABUN3  ,
		PECCOMMENT3 = P_PECCOMMENT3,
		PECJKCD4    = P_PECJKCD4   ,
		PECJKCDNM4  = P_PECJKCDNM4 ,
		PECNAME4    = P_PECNAME4   ,
		PECSABUN4   = P_PECSABUN4  ,
		PECCOMMENT4 = P_PECCOMMENT4,
		PECJKCD5    = P_PECJKCD5   ,
		PECJKCDNM5  = P_PECJKCDNM5 ,
		PECNAME5    = P_PECNAME5   ,
		PECSABUN5   = P_PECSABUN5  ,
		PECCOMMENT5 = P_PECCOMMENT5,
		PECJKCD6    = P_PECJKCD6   ,
		PECJKCDNM6  = P_PECJKCDNM6 ,
		PECNAME6    = P_PECNAME6   ,
		PECSABUN6   = P_PECSABUN6  ,
		PECCOMMENT6 = P_PECCOMMENT6,
		PECHIGB     = 'C'          ,
		PECHIDAT    = CURRENT_DATE ,
		PECHITIM    = CURRENT_TIME ,
		PECHISAB    = P_PECHISAB
		WHERE PECTEAM   = P_PECTEAM
		AND   PECDATE   = P_PECDATE
		AND   PECSEQ    = P_PECSEQ;
  
	END IF ; 

	IF P_GUBUN = 'APPROVAL' THEN 
  
		IF P_APPROVAL = '' THEN 
  
			SET P_APPROVAL = '0' ; 
  
		END IF ; 
  
		 -- 결재일자와 시간 업데이트 
		 -- 요청자 결재일자 및 시간 업데이트 
		IF P_COUNT = ( INT ( P_APPROVAL ) + 1 ) THEN 
  
			IF P_COUNT = 1 THEN 
  
				UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
					PECDATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					PECTIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE PECTEAM   = P_PECTEAM
				AND   PECDATE   = P_PECDATE
				AND   PECSEQ    = P_PECSEQ; 
  
			ELSEIF P_COUNT = 2 THEN 
  
				UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
					PECDATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					PECTIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE PECTEAM   = P_PECTEAM
				AND   PECDATE   = P_PECDATE
				AND   PECSEQ    = P_PECSEQ; 
  
			ELSEIF P_COUNT = 3 THEN 
  
				UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
					PECDATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					PECTIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE PECTEAM   = P_PECTEAM
				AND   PECDATE   = P_PECDATE
				AND   PECSEQ    = P_PECSEQ; 
  
			ELSEIF P_COUNT = 4 THEN 
  
				UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
					PECDATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					PECTIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE PECTEAM   = P_PECTEAM
				AND   PECDATE   = P_PECDATE
				AND   PECSEQ    = P_PECSEQ; 
  
			ELSEIF P_COUNT = 5 THEN 
  
				UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
					PECDATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					PECTIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE PECTEAM   = P_PECTEAM
				AND   PECDATE   = P_PECDATE
				AND   PECSEQ    = P_PECSEQ; 

			ELSEIF P_COUNT = 6 THEN 
  
				UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
					PECDATE6 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					PECTIME6 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE PECTEAM   = P_PECTEAM
				AND   PECDATE   = P_PECDATE
				AND   PECSEQ    = P_PECSEQ; 
  
			END IF ; 
		ELSE 
  
			IF P_COUNT <> INT ( P_APPROVAL ) THEN 
  
				IF P_APPROVAL = '0' THEN 
  
					UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
						PECDATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						PECTIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE PECTEAM   = P_PECTEAM
					AND   PECDATE   = P_PECDATE
					AND   PECSEQ    = P_PECSEQ; 
  
				ELSEIF P_APPROVAL = '1' THEN 
  
					UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
						PECDATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						PECTIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE PECTEAM   = P_PECTEAM
					AND   PECDATE   = P_PECDATE
					AND   PECSEQ    = P_PECSEQ; 
  
				ELSEIF P_APPROVAL = '2' THEN 
  
					UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
						PECDATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						PECTIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE PECTEAM   = P_PECTEAM
					AND   PECDATE   = P_PECDATE
					AND   PECSEQ    = P_PECSEQ; 
  
				ELSEIF P_APPROVAL = '3' THEN 
  
					UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
						PECDATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						PECTIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE PECTEAM   = P_PECTEAM
					AND   PECDATE   = P_PECDATE
					AND   PECSEQ    = P_PECSEQ; 
  
				ELSEIF P_APPROVAL = '4' THEN 
  
					UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
						PECDATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						PECTIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE PECTEAM   = P_PECTEAM
					AND   PECDATE   = P_PECDATE
					AND   PECSEQ    = P_PECSEQ; 

				ELSEIF P_APPROVAL = '5' THEN 
  
					UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
						PECDATE6 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						PECTIME6 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE PECTEAM   = P_PECTEAM
					AND   PECDATE   = P_PECDATE
					AND   PECSEQ    = P_PECSEQ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
   
	END IF ; 
  
END P1  ; 
  