--DROP PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_RUN;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_RUN ( 

	IN P_CAASKTEAM VARCHAR(6),
	IN P_CAASKDATE VARCHAR(8),
	IN P_CAASKSEQ  NUMERIC(3,0)
) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 

	MAIN : BEGIN  -- 실행부 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT 
				CAWOTEAM,
				CAWODATE,
				CAWOSEQ,
				CAASKCONTENT,
				CAASKBUSEO,
				TYSCMLIB.SF_GB_ORGNAME ( CAASKBUSEO , CAST ( CAASKDATE AS VARCHAR ( 8 ) ) ) AS CAASKBUSEONM , 
				CAASKCLASS,
				CAASKSTEPGN,
				CAASKSUMMARY,
				CAASKACYEAR,
				CAASKACSEQ,
				CARECEIPTDATE,
				/* 요청승인자, 수신승인자 */ 
				CAASKSABUN1 , 
				CAASKNAME1 , 
				CAASKJKCD1 , 
				CAASKJKCDNM1 , 
				CAASKDATE1 , 
				CAASKTIME1 , 
				CAASKSABUN2 , 
				CAASKNAME2 , 
				CAASKJKCD2 , 
				CAASKJKCDNM2 , 
				CAASKDATE2 , 
				CAASKTIME2 , 
				CAASKSABUN3 , 
				CAASKNAME3 , 
				CAASKJKCD3 , 
				CAASKJKCDNM3 , 
				CAASKDATE3 , 
				CAASKTIME3 , 
				CAASKSABUN4 , 
				CAASKNAME4 , 
				CAASKJKCD4 , 
				CAASKJKCDNM4 , 
				CAASKDATE4 , 
				CAASKTIME4 , 
				CAASKSABUN5 , 
				CAASKNAME5 , 
				CAASKJKCD5 , 
				CAASKJKCDNM5 , 
				CAASKDATE5 , 
				CAASKTIME5 , 
				CAASKRESABUN1 , 
				CAASKRENAME1 , 
				CAASKREJKCD1 , 
				CAASKREJKCDNM1 , 
				CAASKREDATE1 , 
				CAASKRETIME1 , 
				CAASKRESABUN2 , 
				CAASKRENAME2 , 
				CAASKREJKCD2 , 
				CAASKREJKCDNM2 , 
				CAASKREDATE2 , 
				CAASKRETIME2 , 
				CAASKRESABUN3 , 
				CAASKRENAME3 , 
				CAASKREJKCD3 , 
				CAASKREJKCDNM3 , 
				CAASKREDATE3 , 
				CAASKRETIME3 , 
				CAASKRESABUN4 , 
				CAASKRENAME4 , 
				CAASKREJKCD4 , 
				CAASKREJKCDNM4 , 
				CAASKREDATE4 , 
				CAASKRETIME4 , 
				CAASKRESABUN5 , 
				CAASKRENAME5 , 
				CAASKREJKCD5 , 
				CAASKREJKCDNM5 , 
				CAASKREDATE5 , 
				CAASKRETIME5 , 
				/* 사인 */ 
				(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN1
					) AS SOIMGNAME1, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN1
					) AS SOIMGSIZE1, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN1
					) AS SOIMGSIGN1,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN2
					) AS SOIMGNAME2, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN2
					) AS SOIMGSIZE2, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN2
					) AS SOIMGSIGN2, 

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN3
					) AS SOIMGNAME3, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN3
					) AS SOIMGSIZE3, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN3
					) AS SOIMGSIGN3,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN4
					) AS SOIMGNAME4, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN4
					) AS SOIMGSIZE4,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN4
					) AS SOIMGSIGN4,


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN5
					) AS SOIMGNAME5, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN5
					) AS SOIMGSIZE5,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKSABUN5
					) AS SOIMGSIGN5,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN1
					) AS REIMGNAME1, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN1
					) AS REIMGSIZE1, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN1
					) AS REIMGSIGN1, 


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN2
					) AS REIMGNAME2, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN2
					) AS REIMGSIZE2, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN2
					) AS REIMGSIGN2, 

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN3
					) AS REIMGNAME3, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN3
					) AS REIMGSIZE3, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN3
					) AS REIMGSIGN3,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN4
					) AS REIMGNAME4, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN4
					) AS REIMGSIZE4,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN4
					) AS REIMGSIGN4,


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN5
					) AS REIMGNAME5, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN5
					) AS REIMGSIZE5,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CAASKRESABUN5
					) AS REIMGSIGN5,
				/* 의견 */ 
				CAASKCOMMENT1 , 
				CAASKCOMMENT2 , 
				CAASKCOMMENT3 , 
				CAASKCOMMENT4 , 
				CAASKCOMMENT5 , 
				CAASKRECOMMENT1 , 
				CAASKRECOMMENT2 , 
				CAASKRECOMMENT3 , 
				CAASKRECOMMENT4 , 
				CAASKRECOMMENT5
			FROM PSSCMLIB.PSM_CHANGEASK_DOC
			WHERE CAASKTEAM = P_CAASKTEAM
			AND   CAASKDATE = P_CAASKDATE 
			AND   CAASKSEQ  = P_CAASKSEQ;
  
		OPEN REFCURSOR;
	END MAIN;
END;