
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_CANCEL ( 
	IN P_PECTEAM VARCHAR(6) , 
	IN P_PECDATE VARCHAR(8) , 
	IN P_PECSEQ NUMERIC(3, 0) ) 
	LANGUAGE SQL 

	P1 : BEGIN 
	 
	UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
		PECDATE1 = '' , 
		PECTIME1 = '' , 
		PECDATE2 = '' , 
		PECTIME2 = '' , 
		PECDATE3 = '' , 
		PECTIME3 = '' , 
		PECDATE4 = '' , 
		PECTIME4 = '' , 
		PECDATE5 = '' , 
		PECTIME5 = '' , 
		PECDATE6 = '' , 
		PECTIME6 = ''
	WHERE PECTEAM = P_PECTEAM 
	AND PECDATE = P_PECDATE 
	AND PECSEQ = P_PECSEQ ; 
  
END P1  ; 
  
