DROP PROCEDURE PSSCMLIB.PSM_PSM4020_WORKORDER_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4020_WORKORDER_LIST ( 
	IN P_STDATE  VARCHAR(8),
	IN P_EDDATE  VARCHAR(8),
	IN P_WKSAUP  VARCHAR(1),
	IN P_WKTEAM  VARCHAR(6),
	IN P_DEPT    VARCHAR(6),
	IN P_ORSABUN VARCHAR(6),
	IN P_TITLE   VARCHAR(120),
	IN P_STATUS  VARCHAR(20) ) 
DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 

	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		WITH TABLE1 AS (
		SELECT  ROWNUMBER() OVER() AS ROWNO,
			(CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_CHANGEASK_DOC
			            WHERE WOORTEAM = CAWOTEAM
				    AND   WOORDATE = CAWODATE
				    AND   WOSEQ    = CAWOSEQ) = 0 THEN '<img src="/Resources/Images/Icon/icon_new.png" style="cursor:pointer" onclick="grdWorkJSAClick();" />' ELSE '' END) AS ASK_ADD,
			WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APP_NUM,
			WOWORKTITLE,
			WOLOCATIONCODE1,
			S1.FXC3DESC AS WOLOCATIONCODE1NM, --설비명
			WOSOTEAM,       
			TYSCMLIB.SF_GB_ORGNAME(WOSOTEAM, WOORDATE) AS WOSOTEAMNM,
			WORETEAM,         
			TYSCMLIB.SF_GB_ORGNAME(WORETEAM, WOORDATE) AS WORETEAMNM,
			TYSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE', 'OR') AS WOAPPORSABUN,
			TYSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'NAME', 'OR') AS WOAPPORSABUNNM,
			TYSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE', 'RE') AS WOAPPREVSABUN,
			TYSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'NAME', 'RE') AS WOAPPREVSABUNNM,
			CASE WHEN WODSDATE1 = '' THEN '' ELSE
			     SUBSTR(WODSDATE1,1,4)||'-'||SUBSTR(WODSDATE1,5,2)||'-'||SUBSTR(WODSDATE1,7,2)
			END AS WODSDATE1,
			CASE WHEN WODSDATE2 = '' THEN '' ELSE
			     SUBSTR(WODSDATE2,1,4)||'-'||SUBSTR(WODSDATE2,5,2)||'-'||SUBSTR(WODSDATE2,7,2)
			END AS WODSDATE2,
			( SELECT A.WOSTATUS
			  FROM PSSCMLIB.CV_PSM_WORKSTATUSLIST A   
			  WHERE A.APP_NUM = C.WOORTEAM||'-'||C.WOORDATE||'-'||DIGITS(C.WOSEQ) ) AS WOSTATUS,
			( SELECT VALUE(MAX(SMWKORAPPDATE),0)
			  FROM PSSCMLIB.PSM_SafeOrder_MASTER
			  WHERE SMWKTEAM = WOORTEAM
			    AND SMWKDATE = WOORDATE
			    AND SMWKSEQ  = WOSEQ) AS SMWKORAPPDATE,
			(CASE WHEN WOCHANGEWKDIV = '1' THEN 'FINISH' -- 단순교체이면 조회되게 함
			      ELSE '' END) AS GUBUN                  -- 변경이면 조건에 따라 조회되게 함(로직 추가해야 함)
		FROM PSSCMLIB.PSM_WORKORDER C
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 S1
		      ON   S1.FXC3SAUP||S1.FXC3BCODE||DIGITS(S1.FXC3MCODE)||DIGITS(S1.FXC3SCODE) = WOLOCATIONCODE1
		LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 S2
		      ON   S2.FXC3SAUP||S2.FXC3BCODE||DIGITS(S2.FXC3MCODE)||DIGITS(S2.FXC3SCODE) = WOLOCATIONCODE2
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF K1
		     ON K1.KBSABUN =  WOORSABUN
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF K2
		     ON K2.KBSABUN =  WOSAFESABUN
		 LEFT OUTER JOIN (SELECT CAST(P_STDATE AS VARCHAR(8))  AS SDATE, 
					 CAST(P_EDDATE AS VARCHAR(8))  AS EDATE,
					 CAST(P_WKSAUP AS VARCHAR(1))  AS WKSAUP,
					 CAST(P_WKTEAM AS VARCHAR(6))  AS WKTEAM,
					 CAST(P_STATUS AS VARCHAR(20)) AS STATUS,
					 CAST(P_DEPT   AS VARCHAR(6))  AS DEPT
			     FROM SYSIBM.SYSDUMMY1) AS PAR
		    ON 1 = 1
		WHERE  WOORDATE BETWEEN SDATE AND EDATE
		 AND   ( SUBSTR(WOSOTEAM,1,1)||SUBSTR(WORETEAM,1,1) LIKE  '%'||PAR.WKSAUP||'%' OR WOSOTEAM =  PAR.DEPT )
		 AND   WOSOTEAM   LIKE  '%'||PAR.WKTEAM||'%'
		 --AND   TYSCMLIB.SF_PSM_WKORDER_STATUS(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE') IN  
		 --	    (SELECT DATA FROM TABLE(TYSCMLIB.SF_GB_RevColRow(PAR.STATUS, ',')) AS InTable )  
		 AND   WOORSABUN LIKE P_ORSABUN ||'%'
		 AND   WOWORKTITLE LIKE '%'|| P_TITLE  ||'%'
		 AND   WOCHANGEWKDIV = '2'
		 AND   WOAPPSTATUS = 'F'
		)

		SELECT
		*
		FROM TABLE1
		--WHERE GUBUN = 'FINISH'
		ORDER BY SMWKORAPPDATE DESC , APP_NUM DESC; 
		 
	OPEN REFCURSOR;
  
END;

CALL PSSCMLIB.PSM_PSM4020_WORKORDER_LIST('20230708','20230808','','','','','','9,10,11,12,13,14,15');