DROP PROCEDURE PSSCMLIB.PSM_PSM4040_SAFEORDER_WKCODE_SAV;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_SAFEORDER_WKCODE_SAV ( 

	IN P_SWWKTEAM        VARCHAR(6),
        IN P_SWWKDATE        VARCHAR(8),
	IN P_SWWKSEQ         NUMERIC(3,0),
	IN P_SWORAPPDATE     VARCHAR(8),
	IN P_SWORSEQ         NUMERIC(3,0),
	IN P_SWWKCODE        VARCHAR(2),
	IN P_SWWKNAME        VARCHAR(30),
	IN P_SWRISKRATE      VARCHAR(1),
	IN P_SWCHECKGN       VARCHAR(1),
	IN P_SWHISAB         VARCHAR(6)
)

LANGUAGE SQL

P1: BEGIN  

	INSERT INTO PSSCMLIB.PSM_SAFEORDER_WKCODE 
	( 
		SWWKTEAM , 
		SWWKDATE , 
		SWWKSEQ , 
		SWORAPPDATE , 
		SWORSEQ , 
		SWWKCODE , 
		SWWKNAME , 
		SWRISKRATE , 
		SWCHECKGN , 
		SWHIGB , 
		SWHIDAT , 
		SWHITIM , 
		SWHISAB 
	)
	VALUES
	(
		P_SWWKTEAM,
		P_SWWKDATE,
		P_SWWKSEQ,
		P_SWORAPPDATE,
		P_SWORSEQ,
		P_SWWKCODE,
		P_SWWKNAME,
		P_SWRISKRATE,
		P_SWCHECKGN,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_SWHISAB
	);

END P1;