--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4043_JSACHANGE_MASTER_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4043_JSACHANGE_MASTER_LIST ( 
	IN P_JSMWKGUBN VARCHAR(1),
	IN P_JSMPOTEAM VARCHAR(6),
	IN P_JSMPODATE VARCHAR(8),
	IN P_JSMPOSEQ NUMERIC(3,0),
	IN P_JSMDATE VARCHAR(8))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		JSMDATE,
		JSMMSEQ,
		JSMBLASS     ,
		J1NAME AS JBCODE,
		JSMMLASS     ,
		J2NAME AS JMCODE,
		JSMSLASS     ,
		J3NAME AS JSCODE,
		JSMSEQ       ,
		JSMWKNAME    ,
		JSMSYSTEM    ,
		JSMWKDATE    ,
		JSMADDATE    ,
		JSMADCHASU   ,
		JSMWKSABUN   ,
		KBHANGL AS JSMWKSABUNNM,
		JSMSECTIONNUM,
		H1CODE.CDDESC1 AS H1CODE,
		JSMMSDSCODE  ,
		JSMMSDSSEQ   ,
		JSMWKSUMMARY ,
		JSMNEEDDATA  ,
		JSMRISKCASE  ,
		JSMSELFNAME1 ,
		JSMSELFTEXT1 ,
		JSMSELFNAME2 ,
		JSMSELFTEXT2 ,
		JSMSELFNAME3 ,
		JSMSELFTEXT3 ,
		JSMSELFNAME4 ,
		JSMSELFTEXT4 ,
		JSMSELFNAME5 ,
		JSMSELFTEXT5 ,
		JSMSCOMNAME1 ,
		JSMSCOMTEXT1 ,
		JSMSCOMNAME2 ,
		JSMSCOMTEXT2
		FROM PSSCMLIB.PSM_JSACHANGE_MASTER
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
		ON    JSMBLASS = J1CODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2
		ON    JSMBLASS = J2BCODE
		AND   JSMMLASS = J2MCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3
		ON    JSMBLASS = J3BCODE
		AND   JSMMLASS = J3MCODE
		AND   JSMSLASS = J3SCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF AS H1CODE
		ON             'H1' = H1CODE.CDINDEX
		AND   JSMSECTIONNUM = H1CODE.CDCODE
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF KB
		ON  KB.KBSABUN = JSMWKSABUN
		WHERE JSMWKGUBN = P_JSMWKGUBN
		AND   JSMPOTEAM = P_JSMPOTEAM
		AND   JSMPODATE = P_JSMPODATE
		AND   JSMPOSEQ  = P_JSMPOSEQ
		AND   JSMDATE = P_JSMDATE
		ORDER BY JSMDATE, JSMMSEQ
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 

