DROP PROCEDURE PSSCMLIB.PSM_PSM4081_EXAM_REPORT_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4081_EXAM_REPORT_ADD ( 
	IN P_PERTCTEAM VARCHAR(6),
	IN P_PERTCDATE VARCHAR(8),
	IN P_PERTCSEQ NUMERIC(3,0),
	IN P_PERDATE VARCHAR(8),
	IN P_PERSEQ NUMERIC(1,0),
	IN P_PERNUM NUMERIC(3,0),
	IN P_PERSUBJECTS VARCHAR(200) , 
	IN P_PERRESULTS VARCHAR(500) , 
	IN P_PERSABUN VARCHAR(6) , 
	IN P_PERCONTENTS VARCHAR(500) , 
	IN P_PERBIGO VARCHAR(500) , 
	IN P_PERHISAB VARCHAR(6),
	IN P_GUBUN VARCHAR (1)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 

	DECLARE V_PERNUM NUMERIC(3,0) ;
	 
	IF P_GUBUN = 'A' THEN

		SELECT   VALUE(MAX(PERNUM), 0) + 1 INTO V_PERNUM
		FROM PSSCMLIB.PSM_EXAM_REPORT
		WHERE PERTCTEAM  = P_PERTCTEAM
		AND   PERTCDATE  = P_PERTCDATE
		AND   PERTCSEQ   = P_PERTCSEQ
		AND   PERDATE    = P_PERDATE
		AND   PERSEQ     = P_PERSEQ ;
  
		INSERT INTO PSSCMLIB.PSM_EXAM_REPORT
		(
		PERTCTEAM  ,
		PERTCDATE  ,
		PERTCSEQ   ,
		PERDATE    ,
		PERSEQ     ,
		PERNUM     ,
		PERSUBJECTS,
		PERRESULTS ,
		PERSABUN   ,
		PERCONTENTS,
		PERBIGO    ,
		PERHIGB    ,
		PERHIDAT   ,
		PERHITIM   ,
		PERHISAB   
		)
		VALUES
		(
		P_PERTCTEAM  ,
		P_PERTCDATE  ,
		P_PERTCSEQ   ,
		P_PERDATE    ,
		P_PERSEQ     ,
		V_PERNUM     ,
		P_PERSUBJECTS,
		P_PERRESULTS ,
		P_PERSABUN   ,
		P_PERCONTENTS,
		P_PERBIGO    ,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		P_PERHISAB
		)
		;

		UPDATE PSSCMLIB . PSM_EXAM_CHECK SET 
		PECRDATE = P_PERDATE , 
		PECRSEQ = P_PERSEQ 
		WHERE PECTEAM = P_PERTCTEAM 
		AND PECDATE = P_PERTCDATE 
		AND PECSEQ = P_PERTCSEQ ; 
  
	ELSE 
  
		UPDATE PSSCMLIB.PSM_EXAM_REPORT SET
		PERSUBJECTS   = P_PERSUBJECTS,
		PERRESULTS    = P_PERRESULTS,
		PERSABUN      = P_PERSABUN,
		PERCONTENTS   = P_PERCONTENTS,
		PERBIGO       = P_PERBIGO,
		PERHIGB       = 'C',
		PERHIDAT      = CURRENT_DATE,
		PERHITIM      = CURRENT_TIME,
		PERHISAB      = P_PERHISAB
		WHERE PERTCTEAM  = P_PERTCTEAM
		AND   PERTCDATE  = P_PERTCDATE
		AND   PERTCSEQ   = P_PERTCSEQ
		AND   PERDATE    = P_PERDATE
		AND   PERSEQ     = P_PERSEQ
		AND   PERNUM     = P_PERNUM ;
  
	END IF ; 
  
END P1  ; 
  