--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_LIST ( 
	IN P_JSDWKGUBN VARCHAR(1),
	IN P_JSDPOTEAM VARCHAR(6),
	IN P_JSDPODATE VARCHAR(8),
	IN P_JSDPOSEQ NUMERIC(3,0),
	IN P_JSDDATE VARCHAR(8),
	IN P_JSDMSEQ NUMERIC(3,0),
	IN P_JSDBLASS VARCHAR(2),
	IN P_JSDMLASS VARCHAR(2),
	IN P_JSDSLASS VARCHAR(3),
	IN P_JSDSEQ NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		J1NAME AS JBCODE,
		J2NAME AS JMCODE,
		J3NAME AS JSCODE,
		JSMWKNAME,
		JSDITEMSEQ,
		JSDITEMTEXT,
		JSDTOOLTEXT
		FROM PSSCMLIB.PSM_JSACHANGE_MASTER
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
		ON    JSMBLASS = J1CODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2
		ON    JSMBLASS = J2BCODE
		AND   JSMMLASS = J2MCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3
		ON    JSMBLASS = J3BCODE
		AND   JSMMLASS = J3MCODE
		AND   JSMSLASS = J3SCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSACHANGE_DETAIL
		ON    JSMWKGUBN = JSDWKGUBN
		AND   JSMPOTEAM = JSDPOTEAM
		AND   JSMPODATE = JSDPODATE
		AND   JSMPOSEQ  = JSDPOSEQ
		AND   JSMDATE   = JSDDATE
		AND   JSMMSEQ   = JSDMSEQ
		AND   JSMBLASS  = JSDBLASS
		AND   JSMMLASS  = JSDMLASS
		AND   JSMSLASS  = JSDSLASS
		AND   JSMSEQ    = JSDSEQ
		WHERE JSDWKGUBN = P_JSDWKGUBN
		AND   JSDPOTEAM = P_JSDPOTEAM
		AND   JSDPODATE = P_JSDPODATE
		AND   JSDPOSEQ  = P_JSDPOSEQ 
		AND   JSDDATE   = P_JSDDATE  
		AND   JSDMSEQ   = P_JSDMSEQ  
		AND   JSDBLASS  = P_JSDBLASS
		AND   JSDMLASS  = P_JSDMLASS
		AND   JSDSLASS  = P_JSDSLASS
		AND   JSDSEQ    = P_JSDSEQ
							 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 