--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_ALL_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_ALL_DEL
(
	IN P_SMWKTEAM      VARCHAR(6) , 
	IN P_SMWKDATE      VARCHAR(8) , 
	IN P_SMWKSEQ       NUMERIC(3, 0),
	IN P_SMWKORAPPDATE VARCHAR(8) , 
	IN P_SMWKORSEQ     NUMERIC(3, 0)
)
LANGUAGE SQL

P1: BEGIN
	
	-- 안전작업허가서 삭제
	CALL PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_DEL(P_SMWKTEAM, P_SMWKDATE, P_SMWKSEQ, P_SMWKORAPPDATE, P_SMWKORSEQ);

	-- 안전작업허가서 작업내용 삭제
	CALL PSSCMLIB.PSM_PSM4041_SAFEORDER_WKCODE_DEL(P_SMWKTEAM, P_SMWKDATE, P_SMWKSEQ, P_SMWKORAPPDATE, P_SMWKORSEQ);

	-- 안전작업허가서 조치요구사항 삭제
	CALL PSSCMLIB.PSM_PSM4041_SAFEORDER_SACODE_DEL(P_SMWKTEAM, P_SMWKDATE, P_SMWKSEQ, P_SMWKORAPPDATE, P_SMWKORSEQ);

	-- 안전작업허가서 굴착 조치요구사항 삭제
	CALL PSSCMLIB.PSM_PSM4041_SAFEORDER_DRCODE_DEL(P_SMWKTEAM, P_SMWKDATE, P_SMWKSEQ, P_SMWKORAPPDATE, P_SMWKORSEQ);

END P1;