--  Generate SQL 
--  Version:                   	V6R1M0 080215 
--  Generated on:              	18/10/16 08:29:28 
--  Relational Database:       	S65685C2 
--  Standards Option:          	DB2 i5/OS 

DROP PROCEDURE PSSCMLIB.PSM_PSM4050_SAFEWORKOR_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4050_SAFEWORKOR_LIST ( 
	IN P_CURRENTPAGEINDEX INTEGER , 
	IN P_PAGESIZE INTEGER , 	
	IN P_SDATE     VARCHAR(8),
    IN P_EDATE     VARCHAR(8),
    IN P_WKSAUP     VARCHAR(1),
    IN P_WKTEAM     VARCHAR(6),
    IN P_STATUS     VARCHAR(20),
    IN P_DEPT       VARCHAR(6),
    IN P_ORSABUN    VARCHAR(6)
) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4050_SAFEWORKOR_LIST 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	CLOSQLCSR = *ENDMOD , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   

P1 : BEGIN  -- 시작 

	DECLARE P_STNUM INTEGER ; 
	DECLARE P_FNNUM INTEGER ; 	
  
PREV : BEGIN  -- 값 설정 
	SET P_STNUM = ( P_PAGESIZE * ( P_CURRENTPAGEINDEX - 1 ) ) + 1 ; 
        SET P_FNNUM = P_PAGESIZE * P_CURRENTPAGEINDEX ; 
	END PREV ; 
  
MAIN : BEGIN  -- 실행부 
      LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR  -- 커서생성 

			WITH ORIGINAL_DATA AS (
			        SELECT  ROWNUMBER() OVER() AS ROWNO,
					WOORTEAM||'-'||WOORDATE||'-'||DIGITS(WOSEQ) AS APP_NUM,
					WOORTEAM ,  
					WOORDATE ,  
					DIGITS(WOSEQ) AS WOSEQ,  
					WOORSABUN,  
					K1.KBHANGL AS  WOORSABUNNM,
					WOWORKTITLE,
					WOLOCATIONCODE1,
					S1.FXC3DESC AS WOLOCATIONCODE1NM, --설비명
					WOLOCATIONCODE2,
					S1.FXC3DESC AS WOLOCATIONCODE1NM, --설비명
					WOLOCATIONCODE3,
					WOLOCATIONCODE4,
					WOLOCATIONCODE5,
					WOAREACODE1,
					WOAREACODE2,
					WOAREACODE3,
					WOAREACODE4,
					WOAREACODE5,
					CASE WHEN WODSDATE1 = '' THEN '' ELSE
					     SUBSTR(WODSDATE1,1,4)||'-'||SUBSTR(WODSDATE1,5,2)||'-'||SUBSTR(WODSDATE1,7,2)
					END AS WODSDATE1,
					CASE WHEN WODSDATE2 = '' THEN '' ELSE
					     SUBSTR(WODSDATE2,1,4)||'-'||SUBSTR(WODSDATE2,5,2)||'-'||SUBSTR(WODSDATE2,7,2)
					END AS WODSDATE2,
					CASE WHEN WODSDATE1 = '' THEN '' ELSE
					     SUBSTR(WODSDATE1,1,4)||'-'||SUBSTR(WODSDATE1,5,2)||'-'||SUBSTR(WODSDATE1,7,2)
					END || ' ~ ' ||
					CASE WHEN WODSDATE2 = '' THEN '' ELSE
					     SUBSTR(WODSDATE2,1,4)||'-'||SUBSTR(WODSDATE2,5,2)||'-'||SUBSTR(WODSDATE2,7,2)
					END AS WOFROMTODATE,              
					WOSOTEAM,       
					TYSCMLIB.SF_GB_ORGNAME(WOSOTEAM, WOORDATE) AS WOSOTEAMNM,
					WORETEAM,         
					TYSCMLIB.SF_GB_ORGNAME(WORETEAM, WOORDATE) AS WORETEAMNM,
					WOSAFESABUN,
					K2.KBHANGL AS  WOSAFESABUNNM,
					WOFINISHDATE, 
					WOFINISHSABUN,
					WOCHANGEWKJOB,
					WOCHANGEWKDIV,
					WOAPPSOSABUN1,      
					WOAPPSODATE1 ,      
					WOAPPSOTIME1 ,      
					WOAPPSOCOMMENT1,    
					WOAPPSOSABUN2  ,    
					WOAPPSODATE2   ,    
					WOAPPSOTIME2   ,    
					WOAPPSOCOMMENT2,    
					WOAPPSOSABUN3  ,    
					WOAPPSODATE3   ,    
					WOAPPSOTIME3   ,    
					WOAPPSOCOMMENT3,    
					WOAPPSOSABUN4  ,    
					WOAPPSODATE4   ,    
					WOAPPSOTIME4   ,    
					WOAPPSOCOMMENT4,    
					WOAPPSOSABUN5  ,    
					WOAPPSODATE5   ,    
					WOAPPSOTIME5   ,    
					WOAPPSOCOMMENT5,    
					WOAPPRESABUN1 ,     
				    (SELECT KBHANGL FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = WOAPPRESABUN1) AS WOAPPRESABUN1NM,
					WOAPPREDATE1  ,     
					WOAPPRETIME1  ,     
					WOAPPRECOMMENT1,    
					WOAPPRESABUN2  ,    
				    (SELECT KBHANGL FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = WOAPPRESABUN2) AS WOAPPRESABUN2NM,
					WOAPPREDATE2   ,    
					WOAPPRETIME2   ,    
					WOAPPRECOMMENT2,    
					WOAPPRESABUN3  ,    
				    (SELECT KBHANGL FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = WOAPPRESABUN3) AS WOAPPRESABUN3NM,
					WOAPPREDATE3   ,    
					WOAPPRETIME3   ,    
					WOAPPRECOMMENT3,    
					WOAPPRESABUN4  ,    
				    (SELECT KBHANGL FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = WOAPPRESABUN4) AS WOAPPRESABUN4NM,
					WOAPPREDATE4   ,    
					WOAPPRETIME4   ,    
					WOAPPRECOMMENT4,    
					WOAPPRESABUN5  ,    
				    (SELECT KBHANGL FROM TYSCMLIB.INKIBNMF WHERE KBSABUN = WOAPPRESABUN5) AS WOAPPRESABUN5NM,
					WOAPPREDATE5   ,    
					WOAPPRETIME5   ,    
					WOAPPRECOMMENT5,       
					WOCANCELSABUN1,     
					WOCANCELDATE1 ,     
					WOCANCELTIME1 ,     
					WOCANCELCOMMENT1,   
					WOCANCELSABUN2 ,    
					WOCANCELDATE2  ,    
					WOCANCELTIME2  ,    
					WOCANCELCOMMENT2,   
					WOCANCELSABUN3  ,   
					WOCANCELDATE3   ,   
					WOCANCELTIME3   ,   
					WOCANCELCOMMENT3,
					WOGRDOC1     ,      
					WOGRURL1     ,      
					WOGRDOC2     ,      
					WOGRURL2     ,      
					( SELECT A.WOSTATUSCODE
					  FROM PSSCMLIB.CV_PSM_WORKSTATUSLIST A   
					  WHERE A.APP_NUM = C.WOORTEAM||'-'||C.WOORDATE||'-'||DIGITS(C.WOSEQ) ) AS WOSTATUSCODE,
					( SELECT A.WOSTATUS
					  FROM PSSCMLIB.CV_PSM_WORKSTATUSLIST A   
					  WHERE A.APP_NUM = C.WOORTEAM||'-'||C.WOORDATE||'-'||DIGITS(C.WOSEQ) ) AS WOSTATUS,
					PSSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE', 'OR') AS WOAPPORSABUN,
					 PSSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'NAME', 'OR') AS WOAPPORSABUNNM,
					PSSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE', 'RE') AS WOAPPREVSABUN,
					 PSSCMLIB.SF_PSM_WOAPPNEXT(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'NAME', 'RE') AS WOAPPREVSABUNNM,
					 ( SELECT VALUE(MAX(SMWKORAPPDATE),0)
					  FROM PSSCMLIB.PSM_SafeOrder_MASTER
					  WHERE SMWKTEAM = WOORTEAM
					    AND SMWKDATE = WOORDATE
					    AND SMWKSEQ  = WOSEQ) AS SMWKORAPPDATE,
					 ( SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'N' END
					FROM PSSCMLIB.PSM_JSALOG_MASTER
				       WHERE JSLWKGUBN = 'C'
					 AND JSLWKTEAM = WOORTEAM
					 AND JSLWKDATE = WOORDATE
					 AND JSLWKSEQ  = WOSEQ ) AS CHANGEJSA,
					 ( SELECT CASE WHEN COUNT(*) > 0 THEN 'Y' ELSE 'N' END
					FROM PSSCMLIB.PSM_JSALOG_MASTER
				       WHERE JSLWKGUBN = 'D'
					 AND JSLWKTEAM = WOORTEAM
					 AND JSLWKDATE = WOORDATE
					 AND JSLWKSEQ  = WOSEQ ) AS DAYJSA
				FROM PSSCMLIB.PSM_WORKORDER C
				LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 S1
				      ON   S1.FXC3SAUP||S1.FXC3BCODE||DIGITS(S1.FXC3MCODE)||DIGITS(S1.FXC3SCODE) = WOLOCATIONCODE1
				LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 S2
				      ON   S2.FXC3SAUP||S2.FXC3BCODE||DIGITS(S2.FXC3MCODE)||DIGITS(S2.FXC3SCODE) = WOLOCATIONCODE2
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF K1
				     ON K1.KBSABUN =  WOORSABUN
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF K2
				     ON K2.KBSABUN =  WOSAFESABUN
				 LEFT OUTER JOIN (SELECT CAST(P_SDATE  AS VARCHAR(8)) AS SDATE, 
							 CAST(P_EDATE  AS VARCHAR(8)) AS EDATE,
							 CAST(P_WKSAUP AS  VARCHAR(1)) AS WKSAUP,
							 CAST(P_WKTEAM AS  VARCHAR(6)) AS WKTEAM,
							 CAST(P_STATUS AS  VARCHAR(20)) AS STATUS,
							 CAST(P_DEPT AS  VARCHAR(6)) AS DEPT
					     FROM SYSIBM.SYSDUMMY1) AS PAR
				    ON 1 = 1
				WHERE  WOORDATE BETWEEN SDATE AND EDATE
				 AND   ( SUBSTR(WOSOTEAM,1,1)||SUBSTR(WORETEAM,1,1) LIKE  '%'||PAR.WKSAUP||'%' OR WOSOTEAM =  PAR.DEPT )
				 AND   WOSOTEAM   LIKE  '%'||PAR.WKTEAM||'%'
				 AND   PSSCMLIB.SF_PSM_WKORDER_STATUS(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE') IN  
					    (SELECT DATA FROM TABLE(TYSCMLIB.SF_GB_RevColRow(PAR.STATUS, ',')) AS InTable )  
				 AND   WOORSABUN LIKE P_ORSABUN||'%'
			)
			SELECT	*
			FROM ORIGINAL_DATA
			WHERE ROWNO BETWEEN P_STNUM AND P_FNNUM
			ORDER BY ROWNO ASC ;

		OPEN REFCURSOR ;

	END LIST ;  

	PAGING : BEGIN  -- 페이징 
			DECLARE REFCURSOR2 CURSOR WITH RETURN FOR  -- 커서생성 			
			
 			    SELECT  COUNT(*) AS TOTALCOUNT                       
				FROM PSSCMLIB.PSM_WORKORDER C
				LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 S1
				      ON   S1.FXC3SAUP||S1.FXC3BCODE||DIGITS(S1.FXC3MCODE)||DIGITS(S1.FXC3SCODE) = WOLOCATIONCODE1
				LEFT OUTER JOIN TYSCMLIB.ACFIXCLASS3 S2
				      ON   S2.FXC3SAUP||S2.FXC3BCODE||DIGITS(S2.FXC3MCODE)||DIGITS(S2.FXC3SCODE) = WOLOCATIONCODE2
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF K1
				     ON K1.KBSABUN =  WOORSABUN
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF K2
				     ON K2.KBSABUN =  WOSAFESABUN
				 LEFT OUTER JOIN (SELECT CAST(P_SDATE  AS VARCHAR(8)) AS SDATE, 
							 CAST(P_EDATE  AS VARCHAR(8)) AS EDATE,
							 CAST(P_WKSAUP AS  VARCHAR(1)) AS WKSAUP,
							 CAST(P_WKTEAM AS  VARCHAR(6)) AS WKTEAM,
							 CAST(P_STATUS AS  VARCHAR(20)) AS STATUS,
							 CAST(P_DEPT AS  VARCHAR(6)) AS DEPT
					     FROM SYSIBM.SYSDUMMY1) AS PAR
				    ON 1 = 1
				WHERE  WOORDATE BETWEEN SDATE AND EDATE
				 AND   ( SUBSTR(WOSOTEAM,1,1)||SUBSTR(WORETEAM,1,1) LIKE  '%'||PAR.WKSAUP||'%' OR WOSOTEAM =  PAR.DEPT )
				 AND   WOSOTEAM   LIKE  '%'||PAR.WKTEAM||'%'
				 AND   PSSCMLIB.SF_PSM_WKORDER_STATUS(WOORTEAM,WOORDATE,DIGITS(WOSEQ), 'CODE') IN  
					    (SELECT DATA FROM TABLE(TYSCMLIB.SF_GB_RevColRow(PAR.STATUS, ',')) AS InTable )  
				 AND   WOORSABUN LIKE P_ORSABUN||'%';

			OPEN REFCURSOR2 ; 
	END PAGING ; 
END MAIN ; 
END  ;
