
DROP  PROCEDURE PSSCMLIB.PSM_PSM4070_WORKORDER_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4070_WORKORDER_LIST ( 
	IN P_STDATE VARCHAR(8) , 
	IN P_EDDATE VARCHAR(8) , 
	IN P_WKSAUP VARCHAR(1) , 
	IN P_WKTEAM VARCHAR(6) , 
	IN P_DEPT VARCHAR(6) , 
	IN P_ORSABUN VARCHAR(6) , 
	IN P_TITLE VARCHAR(120) , 
	IN P_STATUS VARCHAR(20) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		 
		WITH TABLE1 AS (
		SELECT
		( CASE WHEN WK . WOFINISHDATE <> '' OR WK . WOIMMEDDATE <> '' OR (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_CHECK WHERE PEC.PECWOTEAM = WK.WOORTEAM AND  PEC.PECWODATE = WK.WOORDATE AND  PEC.PECWOSEQ = WK.WOSEQ) > 0 THEN '' ELSE '<img src="/Resources/Images/Icon/icon_new.png" style="cursor:pointer" onclick="grdWorkEXAMClick();" />' END ) AS EXAM_ADD , 
		WOORTEAM,
		WOORDATE,
		DIGITS(WOSEQ) AS WOSEQ,
		WOORTEAM || '-' || WOORDATE || '-' || DIGITS ( WOSEQ ) AS APP_NUM , 
		WOWORKTITLE,
		WOLOCATIONCODE1,
		S1 . FXC3DESC AS WOLOCATIONCODE1NM ,  --설비명
		WOSOTEAM , 
		WOORSABUN,
		TYSCMLIB . SF_GB_ORGNAME ( WOSOTEAM , WOORDATE ) AS WOSOTEAMNM , 
		WORETEAM , 
		TYSCMLIB . SF_GB_ORGNAME ( WORETEAM , WOORDATE ) AS WORETEAMNM , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'CODE' , 'OR' ) AS WOAPPORSABUN , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'NAME' , 'OR' ) AS WOAPPORSABUNNM , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'CODE' , 'RE' ) AS WOAPPREVSABUN , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'NAME' , 'RE' ) AS WOAPPREVSABUNNM  ,
		CASE WHEN WODSDATE1 = '' THEN '' ELSE 
		SUBSTR ( WODSDATE1 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE1 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE1 , 7 , 2 ) 
		END AS WODSDATE1 , 
		CASE WHEN WODSDATE2 = '' THEN '' ELSE 
		SUBSTR ( WODSDATE2 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE2 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE2 , 7 , 2 ) 
		END AS WODSDATE2 ,
		CAASKCLASS,
		(CASE WHEN CAASKSTEPGN = '1' THEN '화물(청소미포함)'
		WHEN CAASKSTEPGN = '2' THEN '화물(청소포함)'
		WHEN CAASKSTEPGN = '3' THEN '정상'
		WHEN CAASKSTEPGN = '4' THEN '비상' ELSE '임시' END ) AS CAASKSTEPGN,
		( CASE WHEN WK . WOSTATUS = '2' AND (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_CHECK WHERE PEC.PECWOTEAM = WK.WOORTEAM AND  PEC.PECWODATE = WK.WOORDATE AND  PEC.PECWOSEQ = WK.WOSEQ) > 0 THEN '가동전 점검 중'
		WHEN WK . WOSTATUS = '5' AND WK.WOAPPSTATUS = 'F' THEN '공사 완료' ELSE '안전작업허가 완료' END) AS WOSTATUS,
		( CASE WHEN WK . WOSTATUS = '5' AND WK . WOAPPSTATUS = 'F' THEN '5'  -- 공사완료 
		ELSE '1' END ) AS WORKSTATUS  -- 진행중 
		FROM PSSCMLIB.PSM_WORKORDER AS WK
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC AS CA
		ON     CA.CAWOTEAM = WK.WOORTEAM
		AND   CA.CAWODATE = WK.WOORDATE
		AND   CA.CAWOSEQ = WK.WOSEQ
		LEFT OUTER JOIN PSSCMLIB.PSM_SAFEORDER_MASTER AS SM
		ON     SM.SMWKTEAM = WK.WOORTEAM
		AND   SM.SMWKDATE = WK.WOORDATE
		AND   SM.SMWKSEQ = WK.WOSEQ
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S1 
		ON S1 . FXC3SAUP || S1 . FXC3BCODE || DIGITS ( S1 . FXC3MCODE ) || DIGITS ( S1 . FXC3SCODE ) = WK.WOLOCATIONCODE1 
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK AS PEC
		ON    PEC.PECWOTEAM = WK.WOORTEAM
		AND  PEC.PECWODATE = WK.WOORDATE
		AND  PEC.PECWOSEQ = WK.WOSEQ
		WHERE WK.WOCHANGEWKDIV = '2'
		AND    WK.WOAPPSTATUS = 'F'
		AND   CA.CAASKCLASS = ('C')
		AND    SM.SMCOAPPDATE <> ''
		AND    SM.SMCOAPPTIME <> ''

		UNION ALL

		SELECT
		( CASE WHEN WK . WOFINISHDATE <> '' OR WK . WOIMMEDDATE <> '' OR (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_CHECK WHERE PEC.PECWOTEAM = WK.WOORTEAM AND  PEC.PECWODATE = WK.WOORDATE AND  PEC.PECWOSEQ = WK.WOSEQ) > 0 THEN '' ELSE '<img src="/Resources/Images/Icon/icon_new.png" style="cursor:pointer" onclick="grdWorkEXAMClick();" />' END ) AS EXAM_ADD , 
		WOORTEAM,
		WOORDATE,
		DIGITS(WOSEQ) AS WOSEQ,
		WOORTEAM || '-' || WOORDATE || '-' || DIGITS ( WOSEQ ) AS APP_NUM , 
		WOWORKTITLE,
		WOLOCATIONCODE1,
		S1 . FXC3DESC AS WOLOCATIONCODE1NM ,  --설비명
		WOSOTEAM , 
		WOORSABUN,
		TYSCMLIB . SF_GB_ORGNAME ( WOSOTEAM , WOORDATE ) AS WOSOTEAMNM , 
		WORETEAM , 
		TYSCMLIB . SF_GB_ORGNAME ( WORETEAM , WOORDATE ) AS WORETEAMNM , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'CODE' , 'OR' ) AS WOAPPORSABUN , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'NAME' , 'OR' ) AS WOAPPORSABUNNM , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'CODE' , 'RE' ) AS WOAPPREVSABUN , 
		PSSCMLIB . SF_PSM_WOAPPNEXT ( WOORTEAM , WOORDATE , DIGITS ( WOSEQ ) , 'NAME' , 'RE' ) AS WOAPPREVSABUNNM  ,
		CASE WHEN WODSDATE1 = '' THEN '' ELSE 
		SUBSTR ( WODSDATE1 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE1 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE1 , 7 , 2 ) 
		END AS WODSDATE1 , 
		CASE WHEN WODSDATE2 = '' THEN '' ELSE 
		SUBSTR ( WODSDATE2 , 1 , 4 ) || '-' || SUBSTR ( WODSDATE2 , 5 , 2 ) || '-' || SUBSTR ( WODSDATE2 , 7 , 2 ) 
		END AS WODSDATE2 ,
		CAASKCLASS,
		(CASE WHEN CAASKSTEPGN = '1' THEN '화물(청소미포함)'
		WHEN CAASKSTEPGN = '2' THEN '화물(청소포함)'
		WHEN CAASKSTEPGN = '3' THEN '정상'
		WHEN CAASKSTEPGN = '4' THEN '비상' ELSE '임시' END ) AS CAASKSTEPGN,
		( CASE WHEN WK . WOSTATUS = '2' AND (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_CHECK WHERE PEC.PECWOTEAM = WK.WOORTEAM AND  PEC.PECWODATE = WK.WOORDATE AND  PEC.PECWOSEQ = WK.WOSEQ) > 0 THEN '가동전 점검 중'
		WHEN WK . WOSTATUS = '5' AND WK.WOAPPSTATUS = 'F' THEN '공사 완료' ELSE '안전작업허가 완료' END) AS WOSTATUS,
		( CASE WHEN WK . WOSTATUS = '5' AND WK . WOAPPSTATUS = 'F' THEN '5'  -- 공사완료 
		ELSE '1' END ) AS WORKSTATUS  -- 진행중 
		FROM PSSCMLIB.PSM_WORKORDER AS WK
		LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC AS CA
		ON     CA.CAWOTEAM = WK.WOORTEAM
		AND   CA.CAWODATE = WK.WOORDATE
		AND   CA.CAWOSEQ = WK.WOSEQ
		LEFT OUTER JOIN PSSCMLIB.PSM_SAFEORDER_MASTER AS SM
		ON     SM.SMWKTEAM = WK.WOORTEAM
		AND   SM.SMWKDATE = WK.WOORDATE
		AND   SM.SMWKSEQ = WK.WOSEQ
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 S1 
		ON S1 . FXC3SAUP || S1 . FXC3BCODE || DIGITS ( S1 . FXC3MCODE ) || DIGITS ( S1 . FXC3SCODE ) = WK.WOLOCATIONCODE1 
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK AS PEC
		ON    PEC.PECWOTEAM = WK.WOORTEAM
		AND  PEC.PECWODATE = WK.WOORDATE
		AND  PEC.PECWOSEQ = WK.WOSEQ
		WHERE WK.WOCHANGEWKDIV = '2'
		AND    WK.WOAPPSTATUS = 'F'
		AND   CA.CAASKCLASS IN ('A','B')
		AND   CA.CAASKSTEPGN IN ('3','4','5')
		AND    SM.SMCOAPPDATE <> ''
		AND    SM.SMCOAPPTIME <> ''
		)
		SELECT
		ROWNUMBER ( ) OVER ( ) AS ROWNO , 
		EXAM_ADD,
		APP_NUM , 
		WOWORKTITLE,
		WOLOCATIONCODE1,
		WOLOCATIONCODE1NM ,
		WOSOTEAM , 
		WOSOTEAMNM , 
		WORETEAM , 
		WORETEAMNM , 
		WOAPPORSABUN , 
		WOAPPORSABUNNM , 
		WOAPPREVSABUN , 
		WOAPPREVSABUNNM  ,
		WODSDATE1 , 
		WODSDATE2 ,
		CAASKCLASS,
		CAASKSTEPGN,
		WOSTATUS,
		WORKSTATUS
		FROM TABLE1
		LEFT OUTER JOIN ( SELECT CAST ( P_STDATE AS VARCHAR ( 8 ) ) AS SDATE , 
		CAST ( P_EDDATE AS VARCHAR ( 8 ) ) AS EDATE , 
		CAST ( P_WKSAUP AS VARCHAR ( 1 ) ) AS WKSAUP , 
		CAST ( P_WKTEAM AS VARCHAR ( 6 ) ) AS WKTEAM , 
		CAST ( P_STATUS AS VARCHAR ( 20 ) ) AS STATUS , 
		CAST ( P_DEPT AS VARCHAR ( 6 ) ) AS DEPT 
		FROM SYSIBM . SYSDUMMY1 ) AS PAR 
		ON 1 = 1 
		WHERE WOORDATE BETWEEN SDATE AND EDATE 
		AND ( SUBSTR ( WOSOTEAM , 1 , 1 ) || SUBSTR ( WORETEAM , 1 , 1 ) LIKE '%' || PAR . WKSAUP || '%' OR WOSOTEAM = PAR . DEPT ) 
		AND WOSOTEAM LIKE '%' || PAR . WKTEAM || '%' 
		AND WOORSABUN LIKE P_ORSABUN || '%' 
		AND WOWORKTITLE LIKE '%' || P_TITLE || '%' 
		AND WORKSTATUS IN ( SELECT DATA FROM TABLE ( TYSCMLIB . SF_GB_REVCOLROW ( P_STATUS , ',' ) ) AS INTABLE ) 
		GROUP BY EXAM_ADD, APP_NUM , WOWORKTITLE,WOLOCATIONCODE1,WOLOCATIONCODE1NM ,WOSOTEAM , WOSOTEAMNM , WORETEAM , 
		WORETEAMNM , WOAPPORSABUN , WOAPPORSABUNNM , WOAPPREVSABUN , WOAPPREVSABUNNM  ,WODSDATE1 , WODSDATE2 ,CAASKCLASS,
		CAASKSTEPGN,WOSTATUS,WORKSTATUS
		ORDER BY APP_NUM; 
		 
	OPEN REFCURSOR ; 
  
END  ; 