DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_ADD;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_ADD ( 
	IN P_SMWKTEAM VARCHAR(6) , 
	IN P_SMWKDATE VARCHAR(8) , 
	IN P_SMWKSEQ NUMERIC(3, 0) , 
	IN P_SMWKORAPPDATE VARCHAR(8) , 
	IN P_SMWKORSEQ NUMERIC(3, 0) , 
	IN P_SMREVTEAM VARCHAR(6) , 
	IN P_SMWKMETHOD VARCHAR(1) , 
	IN P_SMSUBVEND VARCHAR(40) , 
	IN P_SMSUBPERSON VARCHAR(20) , 
	IN P_SMSUBTEL VARCHAR(20) , 
	IN P_SMRESSABUN VARCHAR(6) , 
	IN P_SMWKMAN VARCHAR(6) , 
	IN P_SMTADATE1 VARCHAR(8) , 
	IN P_SMTATIME1 VARCHAR(4) , 
	IN P_SMTADATE2 VARCHAR(8) , 
	IN P_SMTATIME2 VARCHAR(4) , 
	IN P_SMOTDATE1 VARCHAR(8) , 
	IN P_SMOTTIME1 VARCHAR(4) , 
	IN P_SMOTDATE2 VARCHAR(8) , 
	IN P_SMOTTIME2 VARCHAR(4) , 
	IN P_SMOTAPPSABUN VARCHAR(6) , 
	IN P_SMSYSTEMCODE1 VARCHAR(20) , 
	IN P_SMSYSTEMCODE2 VARCHAR(20) , 
	IN P_SMSYSTEMCODE3 VARCHAR(20) , 
	IN P_SMSYSTEMCODE4 VARCHAR(20) , 
	IN P_SMSYSTEMCODE5 VARCHAR(20) , 
	IN P_SMCONNCODE11 VARCHAR(20) , 
	IN P_SMCONNCODE12 VARCHAR(20) , 
	IN P_SMCONNCODE21 VARCHAR(20) , 
	IN P_SMCONNCODE22 VARCHAR(20) , 
	IN P_SMCONNCODE31 VARCHAR(20) , 
	IN P_SMCONNCODE32 VARCHAR(20) , 
	IN P_SMCONNCODE41 VARCHAR(20) , 
	IN P_SMCONNCODE42 VARCHAR(20) , 
	IN P_SMCONNCODE51 VARCHAR(20) , 
	IN P_SMCONNCODE52 VARCHAR(20) , 
	IN P_SMAREACODE1 VARCHAR(20) , 
	IN P_SMAREACODE2 VARCHAR(20) , 
	IN P_SMAREACODE3 VARCHAR(20) , 
	IN P_SMAREACODE4 VARCHAR(20) , 
	IN P_SMAREACODE5 VARCHAR(20) , 
	IN P_SMAREATEXT1 VARCHAR(200) , 
	IN P_SMAREATEXT2 VARCHAR(200) , 
	IN P_SMAREATEXT3 VARCHAR(200) , 
	IN P_SMAREATEXT4 VARCHAR(200) , 
	IN P_SMAREATEXT5 VARCHAR(200) , 
	IN P_SMMATERTEXT1 VARCHAR(100) , 
	IN P_SMMATERTEXT2 VARCHAR(100) , 
	IN P_SMNOTE_BURN VARCHAR(1) , 
	IN P_SMNOTE_SUFF VARCHAR(1) , 
	IN P_SMNOTE_ELE VARCHAR(1) , 
	IN P_SMNOTE_FIR VARCHAR(1) , 
	IN P_SMNOTE_EXP VARCHAR(1) , 
	IN P_SMNOTE_DROP VARCHAR(1) , 
	IN P_SMNOTE_LEAK VARCHAR(1) , 
	IN P_SMNOTE_NARR VARCHAR(1) , 
	IN P_SMNOTE_COLL VARCHAR(1) , 
	IN P_SMCHKSABUN1 VARCHAR(6) , 
	IN P_SMCHKTIME1 VARCHAR(4) , 
	IN P_SMCHKOXYGEN1 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT1 VARCHAR(1) , 
	IN P_SMCHKTOXNUM1 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT1 VARCHAR(1) , 
	IN P_SMCHKTOXNUM1DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT1DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM1CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT1CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM1CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT1CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM1H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT1H2S VARCHAR(1) , 
	IN P_SMCHKSABUN2 VARCHAR(6) , 
	IN P_SMCHKTIME2 VARCHAR(4) , 
	IN P_SMCHKOXYGEN2 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM2DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT2DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM2CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT2CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM2CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT2CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM2H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT2H2S VARCHAR(1) , 
	IN P_SMCHKSABUN3 VARCHAR(6) , 
	IN P_SMCHKTIME3 VARCHAR(4) , 
	IN P_SMCHKOXYGEN3 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT3 VARCHAR(1) , 
	IN P_SMCHKTOXNUM3 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT3 VARCHAR(1) , 
	IN P_SMCHKTOXNUM3DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT3DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM3CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT3CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM3CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT3CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM3H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT3H2S VARCHAR(1) , 
	IN P_SMCHKSABUN4 VARCHAR(6) , 
	IN P_SMCHKTIME4 VARCHAR(4) , 
	IN P_SMCHKOXYGEN4 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT4 VARCHAR(1) , 
	IN P_SMCHKTOXNUM4 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT4 VARCHAR(1) , 
	IN P_SMCHKTOXNUM4DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT4DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM4CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT4CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM4CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT4CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM4H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT4H2S VARCHAR(1) , 
	IN P_SMCHKSABUN5 VARCHAR(6) , 
	IN P_SMCHKTIME5 VARCHAR(4) , 
	IN P_SMCHKOXYGEN5 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT5 VARCHAR(1) , 
	IN P_SMCHKTOXNUM5 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT5 VARCHAR(1) , 
	IN P_SMCHKTOXNUM5DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT5DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM5CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT5CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM5CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT5CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM5H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT5H2S VARCHAR(1) , 
	IN P_SMCHKSABUN6 VARCHAR(6) , 
	IN P_SMCHKTIME6 VARCHAR(4) , 
	IN P_SMCHKOXYGEN6 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT6 VARCHAR(1) , 
	IN P_SMCHKTOXNUM6 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT6 VARCHAR(1) , 
	IN P_SMCHKTOXNUM6DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT6DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM6CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT6CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM6CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT6CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM6H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT6H2S VARCHAR(1) , 
	IN P_SMCHKSABUN7 VARCHAR(6) , 
	IN P_SMCHKTIME7 VARCHAR(4) , 
	IN P_SMCHKOXYGEN7 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT7 VARCHAR(1) , 
	IN P_SMCHKTOXNUM7 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT7 VARCHAR(1) , 
	IN P_SMCHKTOXNUM7DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT7DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM7CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT7CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM7CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT7CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM7H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT7H2S VARCHAR(1) , 
	IN P_SMCHKSABUN8 VARCHAR(6) , 
	IN P_SMCHKTIME8 VARCHAR(4) , 
	IN P_SMCHKOXYGEN8 VARCHAR(10) , 
	IN P_SMCHKOXYGENUNIT8 VARCHAR(1) , 
	IN P_SMCHKTOXNUM8 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT8 VARCHAR(1) , 
	IN P_SMCHKTOXNUM8DS NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT8DS VARCHAR(1) , 
	IN P_SMCHKTOXNUM8CO2 NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT8CO2 VARCHAR(1) , 
	IN P_SMCHKTOXNUM8CO NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT8CO VARCHAR(1) , 
	IN P_SMCHKTOXNUM8H2S NUMERIC(10, 2) , 
	IN P_SMCHKTOXUNIT8H2S VARCHAR(1) , 
	IN P_SMCHKTOXGUBN1 VARCHAR(1) , 
	IN P_SMCHKTOXGUBN2 VARCHAR(1) , 
	IN P_SMCHKTOXGUBN3 VARCHAR(1) , 
	IN P_SMCHKTOXGUBN4 VARCHAR(1) , 
	IN P_SMCHKTOXGUBN5 VARCHAR(1) , 
	IN P_SMCHKTOXGUBN6 VARCHAR(1) , 
	IN P_SMORDERTEXT1 VARCHAR(500) , 
	IN P_SMORDERTEXT2 VARCHAR(500) , 
	IN P_SMORSABUN VARCHAR(6) , 
	IN P_SMORNAME VARCHAR(20) , 
	IN P_SMORJKCD VARCHAR(3) , 
	IN P_SMORJKCDNM VARCHAR(20) , 
	IN P_SMGRSABUN VARCHAR(6) , 
	IN P_SMGRNAME VARCHAR(20) , 
	IN P_SMGRJKCD VARCHAR(3) , 
	IN P_SMGRJKCDNM VARCHAR(20) , 
	IN P_SMCOSABUN VARCHAR(6) , 
	IN P_SMCONAME VARCHAR(20) , 
	IN P_SMCOJKCD VARCHAR(3) , 
	IN P_SMCOJKCDNM VARCHAR(20) , 
	IN P_SMSMSABUN VARCHAR(6) , 
	IN P_SMSMCOMMENT VARCHAR(300) , 
	IN P_SMWORKTITLE VARCHAR(120) , 
	IN P_SMOPSABUN VARCHAR(6) , 
	IN P_SMOPCOMMENT VARCHAR(300) , 
	IN P_SMFIREINS VARCHAR(30) , 
	IN P_RESABUN VARCHAR(1000) , 
	IN P_RENAME VARCHAR(2000) , 
	IN P_SMHISAB VARCHAR(6) , 
	IN P_WKGUBUN VARCHAR(10) , 
	IN P_GUBUN VARCHAR(10) , 
	IN P_SWWKCODE1 VARCHAR(1) , 
	IN P_SWWKCODE2 VARCHAR(1) , 
	IN P_SWWKCODE3 VARCHAR(1) , 
	IN P_SWWKCODE4 VARCHAR(1) , 
	IN P_SWWKCODE5 VARCHAR(1) , 
	IN P_SWWKCODE6 VARCHAR(1) , 
	IN P_SWWKCODE7 VARCHAR(1) , 
	IN P_SWWKCODE8 VARCHAR(1) , 
	IN P_SWWKCODE9 VARCHAR(1) , 
	IN P_SWWKCODE10 VARCHAR(1) , 
	IN P_SITE VARCHAR(1) , 
	IN P_801_DRCODE VARCHAR(3) , 
	IN P_801_DRCODENAME VARCHAR(100) , 
	IN P_801_DRYESSEL VARCHAR(1) , 
	IN P_801_DRNOSEL VARCHAR(1) , 
	IN P_801_DRNASEL VARCHAR(1) , 
	IN P_801_DRSORT VARCHAR(30) , 
	IN P_801_DRSTAND VARCHAR(30) , 
	IN P_801_DRDEPTH VARCHAR(30) , 
	IN P_801_DRSABUN VARCHAR(6) , 
	IN P_802_DRCODE VARCHAR(3) , 
	IN P_802_DRCODENAME VARCHAR(100) , 
	IN P_802_DRYESSEL VARCHAR(1) , 
	IN P_802_DRNOSEL VARCHAR(1) , 
	IN P_802_DRNASEL VARCHAR(1) , 
	IN P_802_DRSORT VARCHAR(30) , 
	IN P_802_DRSTAND VARCHAR(30) , 
	IN P_802_DRDEPTH VARCHAR(30) , 
	IN P_802_DRSABUN VARCHAR(6) , 
	IN P_803_DRCODE VARCHAR(3) , 
	IN P_803_DRCODENAME VARCHAR(100) , 
	IN P_803_DRYESSEL VARCHAR(1) , 
	IN P_803_DRNOSEL VARCHAR(1) , 
	IN P_803_DRNASEL VARCHAR(1) , 
	IN P_803_DRSORT VARCHAR(30) , 
	IN P_803_DRSTAND VARCHAR(30) , 
	IN P_803_DRDEPTH VARCHAR(30) , 
	IN P_803_DRSABUN VARCHAR(6) , 
	IN P_804_DRCODE VARCHAR(3) , 
	IN P_804_DRCODENAME VARCHAR(100) , 
	IN P_804_DRYESSEL VARCHAR(1) , 
	IN P_804_DRNOSEL VARCHAR(1) , 
	IN P_804_DRNASEL VARCHAR(1) , 
	IN P_804_DRSORT VARCHAR(30) , 
	IN P_804_DRSTAND VARCHAR(30) , 
	IN P_804_DRDEPTH VARCHAR(30) , 
	IN P_804_DRSABUN VARCHAR(6) , 
	IN P_805_DRCODE VARCHAR(3) , 
	IN P_805_DRCODENAME VARCHAR(100) , 
	IN P_805_DRYESSEL VARCHAR(1) , 
	IN P_805_DRNOSEL VARCHAR(1) , 
	IN P_805_DRNASEL VARCHAR(1) , 
	IN P_805_DRSORT VARCHAR(30) , 
	IN P_805_DRSTAND VARCHAR(30) , 
	IN P_805_DRDEPTH VARCHAR(30) , 
	IN P_805_DRSABUN VARCHAR(6) , 
	IN P_101_SACODE VARCHAR(3) , 
	IN P_102_SACODE VARCHAR(3) , 
	IN P_103_SACODE VARCHAR(3) , 
	IN P_104_SACODE VARCHAR(3) , 
	IN P_105_SACODE VARCHAR(3) , 
	IN P_106_SACODE VARCHAR(3) , 
	IN P_107_SACODE VARCHAR(3) , 
	IN P_108_SACODE VARCHAR(3) , 
	IN P_109_SACODE VARCHAR(3) , 
	IN P_110_SACODE VARCHAR(3) , 
	IN P_111_SACODE VARCHAR(3) , 
	IN P_112_SACODE VARCHAR(3) , 
	IN P_113_SACODE VARCHAR(3) , 
	IN P_114_SACODE VARCHAR(3) , 
	IN P_115_SACODE VARCHAR(3) , 
	IN P_116_SACODE VARCHAR(3) , 
	IN P_201_SACODE VARCHAR(3) , 
	IN P_202_SACODE VARCHAR(3) , 
	IN P_203_SACODE VARCHAR(3) , 
	IN P_204_SACODE VARCHAR(3) , 
	IN P_205_SACODE VARCHAR(3) , 
	IN P_206_SACODE VARCHAR(3) , 
	IN P_207_SACODE VARCHAR(3) , 
	IN P_208_SACODE VARCHAR(3) , 
	IN P_209_SACODE VARCHAR(3) , 
	IN P_210_SACODE VARCHAR(3) , 
	IN P_211_SACODE VARCHAR(3) , 
	IN P_212_SACODE VARCHAR(3) , 
	IN P_213_SACODE VARCHAR(3) , 
	IN P_214_SACODE VARCHAR(3) , 
	IN P_215_SACODE VARCHAR(3) , 
	IN P_216_SACODE VARCHAR(3) , 
	IN P_217_SACODE VARCHAR(3) , 
	IN P_218_SACODE VARCHAR(3) , 
	IN P_301_SACODE VARCHAR(3) , 
	IN P_302_SACODE VARCHAR(3) , 
	IN P_303_SACODE VARCHAR(3) , 
	IN P_304_SACODE VARCHAR(3) , 
	IN P_305_SACODE VARCHAR(3) , 
	IN P_306_SACODE VARCHAR(3) , 
	IN P_307_SACODE VARCHAR(3) , 
	IN P_308_SACODE VARCHAR(3) , 
	IN P_309_SACODE VARCHAR(3) , 
	IN P_310_SACODE VARCHAR(3) , 
	IN P_311_SACODE VARCHAR(3) , 
	IN P_312_SACODE VARCHAR(3) , 
	IN P_313_SACODE VARCHAR(3) , 
	IN P_314_SACODE VARCHAR(3) , 
	IN P_401_SACODE VARCHAR(3) , 
	IN P_402_SACODE VARCHAR(3) , 
	IN P_403_SACODE VARCHAR(3) , 
	IN P_404_SACODE VARCHAR(3) , 
	IN P_405_SACODE VARCHAR(3) , 
	IN P_406_SACODE VARCHAR(3) , 
	IN P_407_SACODE VARCHAR(3) , 
	IN P_408_SACODE VARCHAR(3) , 
	IN P_409_SACODE VARCHAR(3) , 
	IN P_501_SACODE VARCHAR(3) , 
	IN P_502_SACODE VARCHAR(3) , 
	IN P_503_SACODE VARCHAR(3) , 
	IN P_504_SACODE VARCHAR(3) , 
	IN P_601_SACODE VARCHAR(3) , 
	IN P_602_SACODE VARCHAR(3) , 
	IN P_603_SACODE VARCHAR(3) , 
	IN P_701_SACODE VARCHAR(3) , 
	IN P_702_SACODE VARCHAR(3) , 
	IN P_703_SACODE VARCHAR(3) , 
	IN P_704_SACODE VARCHAR(3) , 
	IN P_705_SACODE VARCHAR(3) , 
	IN P_706_SACODE VARCHAR(3) , 
	IN P_707_SACODE VARCHAR(3) , 
	IN P_708_SACODE VARCHAR(3) , 
	IN P_901_SACODE VARCHAR(3) , 
	IN P_902_SACODE VARCHAR(3) , 
	IN P_903_SACODE VARCHAR(3) , 
	IN P_904_SACODE VARCHAR(3) , 
	IN P_905_SACODE VARCHAR(3) , 
	IN P_906_SACODE VARCHAR(3) , 
	IN P_907_SACODE VARCHAR(3) , 
	IN P_908_SACODE VARCHAR(3) , 
	IN P_909_SACODE VARCHAR(3) , 
	IN P_910_SACODE VARCHAR(3) , 
	IN P_911_SACODE VARCHAR(3) , 
	IN P_912_SACODE VARCHAR(3) , 
	IN P_913_SACODE VARCHAR(3) , 
	IN P_914_SACODE VARCHAR(3) , 
	IN P_915_SACODE VARCHAR(3) , 
	IN P_916_SACODE VARCHAR(3) , 
	IN P_101_SACODENM VARCHAR(100) , 
	IN P_102_SACODENM VARCHAR(100) , 
	IN P_103_SACODENM VARCHAR(100) , 
	IN P_104_SACODENM VARCHAR(100) , 
	IN P_105_SACODENM VARCHAR(100) , 
	IN P_106_SACODENM VARCHAR(100) , 
	IN P_107_SACODENM VARCHAR(100) , 
	IN P_108_SACODENM VARCHAR(100) , 
	IN P_109_SACODENM VARCHAR(100) , 
	IN P_110_SACODENM VARCHAR(100) , 
	IN P_111_SACODENM VARCHAR(100) , 
	IN P_112_SACODENM VARCHAR(100) , 
	IN P_113_SACODENM VARCHAR(100) , 
	IN P_114_SACODENM VARCHAR(100) , 
	IN P_115_SACODENM VARCHAR(100) , 
	IN P_116_SACODENM VARCHAR(100) , 
	IN P_201_SACODENM VARCHAR(100) , 
	IN P_202_SACODENM VARCHAR(100) , 
	IN P_203_SACODENM VARCHAR(100) , 
	IN P_204_SACODENM VARCHAR(100) , 
	IN P_205_SACODENM VARCHAR(100) , 
	IN P_206_SACODENM VARCHAR(100) , 
	IN P_207_SACODENM VARCHAR(100) , 
	IN P_208_SACODENM VARCHAR(100) , 
	IN P_209_SACODENM VARCHAR(100) , 
	IN P_210_SACODENM VARCHAR(100) , 
	IN P_211_SACODENM VARCHAR(100) , 
	IN P_212_SACODENM VARCHAR(100) , 
	IN P_213_SACODENM VARCHAR(100) , 
	IN P_214_SACODENM VARCHAR(100) , 
	IN P_215_SACODENM VARCHAR(100) , 
	IN P_216_SACODENM VARCHAR(100) , 
	IN P_217_SACODENM VARCHAR(100) , 
	IN P_218_SACODENM VARCHAR(100) , 
	IN P_301_SACODENM VARCHAR(100) , 
	IN P_302_SACODENM VARCHAR(100) , 
	IN P_303_SACODENM VARCHAR(100) , 
	IN P_304_SACODENM VARCHAR(100) , 
	IN P_305_SACODENM VARCHAR(100) , 
	IN P_306_SACODENM VARCHAR(100) , 
	IN P_307_SACODENM VARCHAR(100) , 
	IN P_308_SACODENM VARCHAR(100) , 
	IN P_309_SACODENM VARCHAR(100) , 
	IN P_310_SACODENM VARCHAR(100) , 
	IN P_311_SACODENM VARCHAR(100) , 
	IN P_312_SACODENM VARCHAR(100) , 
	IN P_313_SACODENM VARCHAR(100) , 
	IN P_314_SACODENM VARCHAR(100) , 
	IN P_401_SACODENM VARCHAR(100) , 
	IN P_402_SACODENM VARCHAR(100) , 
	IN P_403_SACODENM VARCHAR(100) , 
	IN P_404_SACODENM VARCHAR(100) , 
	IN P_405_SACODENM VARCHAR(100) , 
	IN P_406_SACODENM VARCHAR(100) , 
	IN P_407_SACODENM VARCHAR(100) , 
	IN P_408_SACODENM VARCHAR(100) , 
	IN P_409_SACODENM VARCHAR(100) , 
	IN P_501_SACODENM VARCHAR(100) , 
	IN P_502_SACODENM VARCHAR(100) , 
	IN P_503_SACODENM VARCHAR(100) , 
	IN P_504_SACODENM VARCHAR(100) , 
	IN P_601_SACODENM VARCHAR(100) , 
	IN P_602_SACODENM VARCHAR(100) , 
	IN P_603_SACODENM VARCHAR(100) , 
	IN P_701_SACODENM VARCHAR(100) , 
	IN P_702_SACODENM VARCHAR(100) , 
	IN P_703_SACODENM VARCHAR(100) , 
	IN P_704_SACODENM VARCHAR(100) , 
	IN P_705_SACODENM VARCHAR(100) , 
	IN P_706_SACODENM VARCHAR(100) , 
	IN P_707_SACODENM VARCHAR(100) , 
	IN P_708_SACODENM VARCHAR(100) , 
	IN P_901_SACODENM VARCHAR(100) , 
	IN P_902_SACODENM VARCHAR(100) , 
	IN P_903_SACODENM VARCHAR(100) , 
	IN P_904_SACODENM VARCHAR(100) , 
	IN P_905_SACODENM VARCHAR(100) , 
	IN P_906_SACODENM VARCHAR(100) , 
	IN P_907_SACODENM VARCHAR(100) , 
	IN P_908_SACODENM VARCHAR(100) , 
	IN P_909_SACODENM VARCHAR(100) , 
	IN P_910_SACODENM VARCHAR(100) , 
	IN P_911_SACODENM VARCHAR(100) , 
	IN P_912_SACODENM VARCHAR(100) , 
	IN P_913_SACODENM VARCHAR(100) , 
	IN P_914_SACODENM VARCHAR(100) , 
	IN P_915_SACODENM VARCHAR(100) , 
	IN P_916_SACODENM VARCHAR(100) , 
	IN P_101_SSPUBSEL VARCHAR(1) , 
	IN P_102_SSPUBSEL VARCHAR(1) , 
	IN P_103_SSPUBSEL VARCHAR(1) , 
	IN P_104_SSPUBSEL VARCHAR(1) , 
	IN P_105_SSPUBSEL VARCHAR(1) , 
	IN P_106_SSPUBSEL VARCHAR(1) , 
	IN P_107_SSPUBSEL VARCHAR(1) , 
	IN P_108_SSPUBSEL VARCHAR(1) , 
	IN P_109_SSPUBSEL VARCHAR(1) , 
	IN P_110_SSPUBSEL VARCHAR(1) , 
	IN P_111_SSPUBSEL VARCHAR(1) , 
	IN P_112_SSPUBSEL VARCHAR(1) , 
	IN P_113_SSPUBSEL VARCHAR(1) , 
	IN P_114_SSPUBSEL VARCHAR(1) , 
	IN P_115_SSPUBSEL VARCHAR(1) , 
	IN P_116_SSPUBSEL VARCHAR(1) , 
	IN P_101_SSREVSEL VARCHAR(1) , 
	IN P_102_SSREVSEL VARCHAR(1) , 
	IN P_103_SSREVSEL VARCHAR(1) , 
	IN P_104_SSREVSEL VARCHAR(1) , 
	IN P_105_SSREVSEL VARCHAR(1) , 
	IN P_106_SSREVSEL VARCHAR(1) , 
	IN P_107_SSREVSEL VARCHAR(1) , 
	IN P_108_SSREVSEL VARCHAR(1) , 
	IN P_109_SSREVSEL VARCHAR(1) , 
	IN P_110_SSREVSEL VARCHAR(1) , 
	IN P_111_SSREVSEL VARCHAR(1) , 
	IN P_112_SSREVSEL VARCHAR(1) , 
	IN P_113_SSREVSEL VARCHAR(1) , 
	IN P_114_SSREVSEL VARCHAR(1) , 
	IN P_115_SSREVSEL VARCHAR(1) , 
	IN P_116_SSREVSEL VARCHAR(1) , 
	IN P_101_SSFIXSEL VARCHAR(1) , 
	IN P_102_SSFIXSEL VARCHAR(1) , 
	IN P_103_SSFIXSEL VARCHAR(1) , 
	IN P_104_SSFIXSEL VARCHAR(1) , 
	IN P_105_SSFIXSEL VARCHAR(1) , 
	IN P_106_SSFIXSEL VARCHAR(1) , 
	IN P_107_SSFIXSEL VARCHAR(1) , 
	IN P_108_SSFIXSEL VARCHAR(1) , 
	IN P_109_SSFIXSEL VARCHAR(1) , 
	IN P_110_SSFIXSEL VARCHAR(1) , 
	IN P_111_SSFIXSEL VARCHAR(1) , 
	IN P_112_SSFIXSEL VARCHAR(1) , 
	IN P_113_SSFIXSEL VARCHAR(1) , 
	IN P_114_SSFIXSEL VARCHAR(1) , 
	IN P_115_SSFIXSEL VARCHAR(1) , 
	IN P_116_SSFIXSEL VARCHAR(1) , 
	IN P_201_SSPUBSEL VARCHAR(1) , 
	IN P_202_SSPUBSEL VARCHAR(1) , 
	IN P_203_SSPUBSEL VARCHAR(1) , 
	IN P_204_SSPUBSEL VARCHAR(1) , 
	IN P_205_SSPUBSEL VARCHAR(1) , 
	IN P_206_SSPUBSEL VARCHAR(1) , 
	IN P_207_SSPUBSEL VARCHAR(1) , 
	IN P_208_SSPUBSEL VARCHAR(1) , 
	IN P_209_SSPUBSEL VARCHAR(1) , 
	IN P_210_SSPUBSEL VARCHAR(1) , 
	IN P_211_SSPUBSEL VARCHAR(1) , 
	IN P_212_SSPUBSEL VARCHAR(1) , 
	IN P_213_SSPUBSEL VARCHAR(1) , 
	IN P_214_SSPUBSEL VARCHAR(1) , 
	IN P_215_SSPUBSEL VARCHAR(1) , 
	IN P_216_SSPUBSEL VARCHAR(1) , 
	IN P_217_SSPUBSEL VARCHAR(1) , 
	IN P_218_SSPUBSEL VARCHAR(1) , 
	IN P_201_SSREVSEL VARCHAR(1) , 
	IN P_202_SSREVSEL VARCHAR(1) , 
	IN P_203_SSREVSEL VARCHAR(1) , 
	IN P_204_SSREVSEL VARCHAR(1) , 
	IN P_205_SSREVSEL VARCHAR(1) , 
	IN P_206_SSREVSEL VARCHAR(1) , 
	IN P_207_SSREVSEL VARCHAR(1) , 
	IN P_208_SSREVSEL VARCHAR(1) , 
	IN P_209_SSREVSEL VARCHAR(1) , 
	IN P_210_SSREVSEL VARCHAR(1) , 
	IN P_211_SSREVSEL VARCHAR(1) , 
	IN P_212_SSREVSEL VARCHAR(1) , 
	IN P_213_SSREVSEL VARCHAR(1) , 
	IN P_214_SSREVSEL VARCHAR(1) , 
	IN P_215_SSREVSEL VARCHAR(1) , 
	IN P_216_SSREVSEL VARCHAR(1) , 
	IN P_217_SSREVSEL VARCHAR(1) , 
	IN P_218_SSREVSEL VARCHAR(1) , 
	IN P_201_SSFIXSEL VARCHAR(1) , 
	IN P_202_SSFIXSEL VARCHAR(1) , 
	IN P_203_SSFIXSEL VARCHAR(1) , 
	IN P_204_SSFIXSEL VARCHAR(1) , 
	IN P_205_SSFIXSEL VARCHAR(1) , 
	IN P_206_SSFIXSEL VARCHAR(1) , 
	IN P_207_SSFIXSEL VARCHAR(1) , 
	IN P_208_SSFIXSEL VARCHAR(1) , 
	IN P_209_SSFIXSEL VARCHAR(1) , 
	IN P_210_SSFIXSEL VARCHAR(1) , 
	IN P_211_SSFIXSEL VARCHAR(1) , 
	IN P_212_SSFIXSEL VARCHAR(1) , 
	IN P_213_SSFIXSEL VARCHAR(1) , 
	IN P_214_SSFIXSEL VARCHAR(1) , 
	IN P_215_SSFIXSEL VARCHAR(1) , 
	IN P_216_SSFIXSEL VARCHAR(1) , 
	IN P_217_SSFIXSEL VARCHAR(1) , 
	IN P_218_SSFIXSEL VARCHAR(1) , 
	IN P_301_SSPUBSEL VARCHAR(1) , 
	IN P_302_SSPUBSEL VARCHAR(1) , 
	IN P_303_SSPUBSEL VARCHAR(1) , 
	IN P_304_SSPUBSEL VARCHAR(1) , 
	IN P_305_SSPUBSEL VARCHAR(1) , 
	IN P_306_SSPUBSEL VARCHAR(1) , 
	IN P_307_SSPUBSEL VARCHAR(1) , 
	IN P_308_SSPUBSEL VARCHAR(1) , 
	IN P_309_SSPUBSEL VARCHAR(1) , 
	IN P_310_SSPUBSEL VARCHAR(1) , 
	IN P_311_SSPUBSEL VARCHAR(1) , 
	IN P_312_SSPUBSEL VARCHAR(1) , 
	IN P_313_SSPUBSEL VARCHAR(1) , 
	IN P_314_SSPUBSEL VARCHAR(1) , 
	IN P_301_SSREVSEL VARCHAR(1) , 
	IN P_302_SSREVSEL VARCHAR(1) , 
	IN P_303_SSREVSEL VARCHAR(1) , 
	IN P_304_SSREVSEL VARCHAR(1) , 
	IN P_305_SSREVSEL VARCHAR(1) , 
	IN P_306_SSREVSEL VARCHAR(1) , 
	IN P_307_SSREVSEL VARCHAR(1) , 
	IN P_308_SSREVSEL VARCHAR(1) , 
	IN P_309_SSREVSEL VARCHAR(1) , 
	IN P_310_SSREVSEL VARCHAR(1) , 
	IN P_311_SSREVSEL VARCHAR(1) , 
	IN P_312_SSREVSEL VARCHAR(1) , 
	IN P_313_SSREVSEL VARCHAR(1) , 
	IN P_314_SSREVSEL VARCHAR(1) , 
	IN P_301_SSFIXSEL VARCHAR(1) , 
	IN P_302_SSFIXSEL VARCHAR(1) , 
	IN P_303_SSFIXSEL VARCHAR(1) , 
	IN P_304_SSFIXSEL VARCHAR(1) , 
	IN P_305_SSFIXSEL VARCHAR(1) , 
	IN P_306_SSFIXSEL VARCHAR(1) , 
	IN P_307_SSFIXSEL VARCHAR(1) , 
	IN P_308_SSFIXSEL VARCHAR(1) , 
	IN P_309_SSFIXSEL VARCHAR(1) , 
	IN P_310_SSFIXSEL VARCHAR(1) , 
	IN P_311_SSFIXSEL VARCHAR(1) , 
	IN P_312_SSFIXSEL VARCHAR(1) , 
	IN P_313_SSFIXSEL VARCHAR(1) , 
	IN P_314_SSFIXSEL VARCHAR(1) , 
	IN P_401_SSPUBSEL VARCHAR(1) , 
	IN P_402_SSPUBSEL VARCHAR(1) , 
	IN P_403_SSPUBSEL VARCHAR(1) , 
	IN P_404_SSPUBSEL VARCHAR(1) , 
	IN P_405_SSPUBSEL VARCHAR(1) , 
	IN P_406_SSPUBSEL VARCHAR(1) , 
	IN P_407_SSPUBSEL VARCHAR(1) , 
	IN P_408_SSPUBSEL VARCHAR(1) , 
	IN P_409_SSPUBSEL VARCHAR(1) , 
	IN P_401_SSREVSEL VARCHAR(1) , 
	IN P_402_SSREVSEL VARCHAR(1) , 
	IN P_403_SSREVSEL VARCHAR(1) , 
	IN P_404_SSREVSEL VARCHAR(1) , 
	IN P_405_SSREVSEL VARCHAR(1) , 
	IN P_406_SSREVSEL VARCHAR(1) , 
	IN P_407_SSREVSEL VARCHAR(1) , 
	IN P_408_SSREVSEL VARCHAR(1) , 
	IN P_409_SSREVSEL VARCHAR(1) , 
	IN P_401_SSFIXSEL VARCHAR(1) , 
	IN P_402_SSFIXSEL VARCHAR(1) , 
	IN P_403_SSFIXSEL VARCHAR(1) , 
	IN P_404_SSFIXSEL VARCHAR(1) , 
	IN P_405_SSFIXSEL VARCHAR(1) , 
	IN P_406_SSFIXSEL VARCHAR(1) , 
	IN P_407_SSFIXSEL VARCHAR(1) , 
	IN P_408_SSFIXSEL VARCHAR(1) , 
	IN P_409_SSFIXSEL VARCHAR(1) , 
	IN P_501_SSPUBSEL VARCHAR(1) , 
	IN P_502_SSPUBSEL VARCHAR(1) , 
	IN P_503_SSPUBSEL VARCHAR(1) , 
	IN P_504_SSPUBSEL VARCHAR(1) , 
	IN P_501_SSREVSEL VARCHAR(1) , 
	IN P_502_SSREVSEL VARCHAR(1) , 
	IN P_503_SSREVSEL VARCHAR(1) , 
	IN P_504_SSREVSEL VARCHAR(1) , 
	IN P_501_SSFIXSEL VARCHAR(1) , 
	IN P_502_SSFIXSEL VARCHAR(1) , 
	IN P_503_SSFIXSEL VARCHAR(1) , 
	IN P_504_SSFIXSEL VARCHAR(1) , 
	IN P_601_SSPUBSEL VARCHAR(1) , 
	IN P_602_SSPUBSEL VARCHAR(1) , 
	IN P_603_SSPUBSEL VARCHAR(1) , 
	IN P_601_SSREVSEL VARCHAR(1) , 
	IN P_602_SSREVSEL VARCHAR(1) , 
	IN P_603_SSREVSEL VARCHAR(1) , 
	IN P_601_SSFIXSEL VARCHAR(1) , 
	IN P_602_SSFIXSEL VARCHAR(1) , 
	IN P_603_SSFIXSEL VARCHAR(1) , 
	IN P_701_SSPUBSEL VARCHAR(1) , 
	IN P_702_SSPUBSEL VARCHAR(1) , 
	IN P_703_SSPUBSEL VARCHAR(1) , 
	IN P_704_SSPUBSEL VARCHAR(1) , 
	IN P_705_SSPUBSEL VARCHAR(1) , 
	IN P_706_SSPUBSEL VARCHAR(1) , 
	IN P_707_SSPUBSEL VARCHAR(1) , 
	IN P_708_SSPUBSEL VARCHAR(1) , 
	IN P_701_SSREVSEL VARCHAR(1) , 
	IN P_702_SSREVSEL VARCHAR(1) , 
	IN P_703_SSREVSEL VARCHAR(1) , 
	IN P_704_SSREVSEL VARCHAR(1) , 
	IN P_705_SSREVSEL VARCHAR(1) , 
	IN P_706_SSREVSEL VARCHAR(1) , 
	IN P_707_SSREVSEL VARCHAR(1) , 
	IN P_708_SSREVSEL VARCHAR(1) , 
	IN P_701_SSFIXSEL VARCHAR(1) , 
	IN P_702_SSFIXSEL VARCHAR(1) , 
	IN P_703_SSFIXSEL VARCHAR(1) , 
	IN P_704_SSFIXSEL VARCHAR(1) , 
	IN P_705_SSFIXSEL VARCHAR(1) , 
	IN P_706_SSFIXSEL VARCHAR(1) , 
	IN P_707_SSFIXSEL VARCHAR(1) , 
	IN P_708_SSFIXSEL VARCHAR(1) , 
	IN P_901_SSPUBSEL VARCHAR(1) , 
	IN P_902_SSPUBSEL VARCHAR(1) , 
	IN P_903_SSPUBSEL VARCHAR(1) , 
	IN P_904_SSPUBSEL VARCHAR(1) , 
	IN P_905_SSPUBSEL VARCHAR(1) , 
	IN P_906_SSPUBSEL VARCHAR(1) , 
	IN P_907_SSPUBSEL VARCHAR(1) , 
	IN P_908_SSPUBSEL VARCHAR(1) , 
	IN P_909_SSPUBSEL VARCHAR(1) , 
	IN P_910_SSPUBSEL VARCHAR(1) , 
	IN P_911_SSPUBSEL VARCHAR(1) , 
	IN P_912_SSPUBSEL VARCHAR(1) , 
	IN P_913_SSPUBSEL VARCHAR(1) , 
	IN P_914_SSPUBSEL VARCHAR(1) , 
	IN P_915_SSPUBSEL VARCHAR(1) , 
	IN P_916_SSPUBSEL VARCHAR(1) , 
	IN P_901_SSREVSEL VARCHAR(1) , 
	IN P_902_SSREVSEL VARCHAR(1) , 
	IN P_903_SSREVSEL VARCHAR(1) , 
	IN P_904_SSREVSEL VARCHAR(1) , 
	IN P_905_SSREVSEL VARCHAR(1) , 
	IN P_906_SSREVSEL VARCHAR(1) , 
	IN P_907_SSREVSEL VARCHAR(1) , 
	IN P_908_SSREVSEL VARCHAR(1) , 
	IN P_909_SSREVSEL VARCHAR(1) , 
	IN P_910_SSREVSEL VARCHAR(1) , 
	IN P_911_SSREVSEL VARCHAR(1) , 
	IN P_912_SSREVSEL VARCHAR(1) , 
	IN P_913_SSREVSEL VARCHAR(1) , 
	IN P_914_SSREVSEL VARCHAR(1) , 
	IN P_915_SSREVSEL VARCHAR(1) , 
	IN P_916_SSREVSEL VARCHAR(1) , 
	IN P_901_SSFIXSEL VARCHAR(1) , 
	IN P_902_SSFIXSEL VARCHAR(1) , 
	IN P_903_SSFIXSEL VARCHAR(1) , 
	IN P_904_SSFIXSEL VARCHAR(1) , 
	IN P_905_SSFIXSEL VARCHAR(1) , 
	IN P_906_SSFIXSEL VARCHAR(1) , 
	IN P_907_SSFIXSEL VARCHAR(1) , 
	IN P_908_SSFIXSEL VARCHAR(1) , 
	IN P_909_SSFIXSEL VARCHAR(1) , 
	IN P_910_SSFIXSEL VARCHAR(1) , 
	IN P_911_SSFIXSEL VARCHAR(1) , 
	IN P_912_SSFIXSEL VARCHAR(1) , 
	IN P_913_SSFIXSEL VARCHAR(1) , 
	IN P_914_SSFIXSEL VARCHAR(1) , 
	IN P_915_SSFIXSEL VARCHAR(1) , 
	IN P_916_SSFIXSEL VARCHAR(1) ) 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4041_SAFEORDER_MASTER_ADD 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
	DECLARE V_SWWKCODE VARCHAR ( 02 ) ; 
DECLARE V_SWWKNAME VARCHAR ( 30 ) ; 
  
	DECLARE V_CNT NUMERIC ( 3 , 0 ) ; 
  
	SET V_SWWKCODE = '' ; 
SET V_SWWKNAME = '' ; 
  
	SET V_CNT = 0 ; 
	 
	SELECT 
		COUNT ( * ) INTO V_CNT 
	FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
	WHERE SMWKTEAM = P_SMWKTEAM 
	AND SMWKDATE = P_SMWKDATE 
	AND SMWKSEQ = P_SMWKSEQ 
	AND SMWKORAPPDATE = P_SMWKORAPPDATE 
	AND SMWKORSEQ = P_SMWKORSEQ ; 
  
	IF ( V_CNT = 0 ) THEN 
  
		INSERT INTO PSSCMLIB . PSM_SAFEORDER_MASTER 
		( 
			SMWKTEAM , 
			SMWKDATE , 
			SMWKSEQ , 
			SMWKORAPPDATE , 
			SMWKORSEQ , 
			SMREVTEAM , 
			SMWKMETHOD , 
			SMSUBVEND , 
			SMSUBPERSON , 
			SMSUBTEL , 
			SMRESSABUN , 
			SMWKMAN , 
			SMTADATE1 , 
			SMTATIME1 , 
			SMTADATE2 , 
			SMTATIME2 , 
			SMOTDATE1 , 
			SMOTTIME1 , 
			SMOTDATE2 , 
			SMOTTIME2 , 
			SMOTAPPSABUN , 
			SMSYSTEMCODE1 , 
			SMSYSTEMCODE2 , 
			SMSYSTEMCODE3 , 
			SMSYSTEMCODE4 , 
			SMSYSTEMCODE5 , 
			SMCONNCODE11 , 
			SMCONNCODE12 , 
			SMCONNCODE21 , 
			SMCONNCODE22 , 
			SMCONNCODE31 , 
			SMCONNCODE32 , 
			SMCONNCODE41 , 
			SMCONNCODE42 , 
			SMCONNCODE51 , 
			SMCONNCODE52 , 
			SMAREACODE1 , 
			SMAREACODE2 , 
			SMAREACODE3 , 
			SMAREACODE4 , 
			SMAREACODE5 , 
			SMAREATEXT1 , 
			SMAREATEXT2 , 
			SMAREATEXT3 , 
			SMAREATEXT4 , 
			SMAREATEXT5 , 
			SMMATERTEXT1 , 
			SMMATERTEXT2 , 
			SMNOTE_BURN , 
			SMNOTE_SUFF , 
			SMNOTE_ELE , 
			SMNOTE_FIR , 
			SMNOTE_EXP , 
			SMNOTE_DROP , 
			SMNOTE_LEAK , 
			SMNOTE_NARR , 
			SMNOTE_COLL , 
			SMCHKSABUN1 , 
			SMCHKTIME1 , 
			SMCHKOXYGEN1 , 
			SMCHKOXYGENUNIT1 , 
			SMCHKTOXNUM1 , 
			SMCHKTOXUNIT1 , 
			SMCHKTOXNUM1DS , 
			SMCHKTOXUNIT1DS , 
			SMCHKTOXNUM1CO2 , 
			SMCHKTOXUNIT1CO2 , 
			SMCHKTOXNUM1CO , 
			SMCHKTOXUNIT1CO , 
			SMCHKTOXNUM1H2S , 
			SMCHKTOXUNIT1H2S , 
			SMCHKSABUN2 , 
			SMCHKTIME2 , 
			SMCHKOXYGEN2 , 
			SMCHKOXYGENUNIT2 , 
			SMCHKTOXNUM2 , 
			SMCHKTOXUNIT2 , 
			SMCHKTOXNUM2DS , 
			SMCHKTOXUNIT2DS , 
			SMCHKTOXNUM2CO2 , 
			SMCHKTOXUNIT2CO2 , 
			SMCHKTOXNUM2CO , 
			SMCHKTOXUNIT2CO , 
			SMCHKTOXNUM2H2S , 
			SMCHKTOXUNIT2H2S , 
			SMCHKSABUN3 , 
			SMCHKTIME3 , 
			SMCHKOXYGEN3 , 
			SMCHKOXYGENUNIT3 , 
			SMCHKTOXNUM3 , 
			SMCHKTOXUNIT3 , 
			SMCHKTOXNUM3DS , 
			SMCHKTOXUNIT3DS , 
			SMCHKTOXNUM3CO2 , 
			SMCHKTOXUNIT3CO2 , 
			SMCHKTOXNUM3CO , 
			SMCHKTOXUNIT3CO , 
			SMCHKTOXNUM3H2S , 
			SMCHKTOXUNIT3H2S , 
			SMCHKSABUN4 , 
			SMCHKTIME4 , 
			SMCHKOXYGEN4 , 
			SMCHKOXYGENUNIT4 , 
			SMCHKTOXNUM4 , 
			SMCHKTOXUNIT4 , 
			SMCHKTOXNUM4DS , 
			SMCHKTOXUNIT4DS , 
			SMCHKTOXNUM4CO2 , 
			SMCHKTOXUNIT4CO2 , 
			SMCHKTOXNUM4CO , 
			SMCHKTOXUNIT4CO , 
			SMCHKTOXNUM4H2S , 
			SMCHKTOXUNIT4H2S , 
			SMCHKSABUN5 , 
			SMCHKTIME5 , 
			SMCHKOXYGEN5 , 
			SMCHKOXYGENUNIT5 , 
			SMCHKTOXNUM5 , 
			SMCHKTOXUNIT5 , 
			SMCHKTOXNUM5DS , 
			SMCHKTOXUNIT5DS , 
			SMCHKTOXNUM5CO2 , 
			SMCHKTOXUNIT5CO2 , 
			SMCHKTOXNUM5CO , 
			SMCHKTOXUNIT5CO , 
			SMCHKTOXNUM5H2S , 
			SMCHKTOXUNIT5H2S , 
			SMCHKSABUN6 , 
			SMCHKTIME6 , 
			SMCHKOXYGEN6 , 
			SMCHKOXYGENUNIT6 , 
			SMCHKTOXNUM6 , 
			SMCHKTOXUNIT6 , 
			SMCHKTOXNUM6DS , 
			SMCHKTOXUNIT6DS , 
			SMCHKTOXNUM6CO2 , 
			SMCHKTOXUNIT6CO2 , 
			SMCHKTOXNUM6CO , 
			SMCHKTOXUNIT6CO , 
			SMCHKTOXNUM6H2S , 
			SMCHKTOXUNIT6H2S , 
			SMCHKSABUN7 , 
			SMCHKTIME7 , 
			SMCHKOXYGEN7 , 
			SMCHKOXYGENUNIT7 , 
			SMCHKTOXNUM7 , 
			SMCHKTOXUNIT7 , 
			SMCHKTOXNUM7DS , 
			SMCHKTOXUNIT7DS , 
			SMCHKTOXNUM7CO2 , 
			SMCHKTOXUNIT7CO2 , 
			SMCHKTOXNUM7CO , 
			SMCHKTOXUNIT7CO , 
			SMCHKTOXNUM7H2S , 
			SMCHKTOXUNIT7H2S , 
			SMCHKSABUN8 , 
			SMCHKTIME8 , 
			SMCHKOXYGEN8 , 
			SMCHKOXYGENUNIT8 , 
			SMCHKTOXNUM8 , 
			SMCHKTOXUNIT8 , 
			SMCHKTOXNUM8DS , 
			SMCHKTOXUNIT8DS , 
			SMCHKTOXNUM8CO2 , 
			SMCHKTOXUNIT8CO2 , 
			SMCHKTOXNUM8CO , 
			SMCHKTOXUNIT8CO , 
			SMCHKTOXNUM8H2S , 
			SMCHKTOXUNIT8H2S , 
			SMORDERTEXT1 , 
			SMORDERTEXT2 , 
			SMORSABUN , 
			SMORNAME , 
			SMORJKCD , 
			SMORJKCDNM , 
			SMGRSABUN , 
			SMGRNAME , 
			SMGRJKCD , 
			SMGRJKCDNM , 
			SMCOSABUN , 
			SMCONAME , 
			SMCOJKCD , 
			SMCOJKCDNM , 
			SMSMSABUN , 
			SMSMCOMMENT , 
			SMCHKTOXGUBN1 , 
			SMCHKTOXGUBN2 , 
			SMCHKTOXGUBN3 , 
			SMCHKTOXGUBN4 , 
			SMCHKTOXGUBN5 , 
			SMCHKTOXGUBN6 , 
			SMWORKTITLE , 
			SMOPSABUN , 
			SMOPCOMMENT , 
			SMFIREINS,
			SMHIGB , 
			SMHIDAT , 
			SMHITIM , 
			SMHISAB 
		) 
		VALUES 
		( 
			P_SMWKTEAM , 
			P_SMWKDATE ,			 
			P_SMWKSEQ ,				 
			P_SMWKORAPPDATE , 
			P_SMWKORSEQ ,				 
			P_SMREVTEAM ,				 
			P_SMWKMETHOD ,				 
			P_SMSUBVEND ,				 
			P_SMSUBPERSON ,				 
			P_SMSUBTEL ,				 
			P_SMRESSABUN ,				 
			P_SMWKMAN ,				 
			P_SMTADATE1 ,			 
			P_SMTATIME1 ,				 
			P_SMTADATE2 ,				 
			P_SMTATIME2 ,				 
			P_SMOTDATE1 ,				 
			P_SMOTTIME1 ,				 
			P_SMOTDATE2 ,				 
			P_SMOTTIME2 ,				 
			P_SMOTAPPSABUN ,				 
			P_SMSYSTEMCODE1 , 
			P_SMSYSTEMCODE2 , 
			P_SMSYSTEMCODE3 , 
			P_SMSYSTEMCODE4 ,			 
			P_SMSYSTEMCODE5 , 
			P_SMCONNCODE11 ,				 
			P_SMCONNCODE12 ,			 
			P_SMCONNCODE21 ,			 
			P_SMCONNCODE22 ,			 
			P_SMCONNCODE31 ,			 
			P_SMCONNCODE32 ,			 
			P_SMCONNCODE41 ,			 
			P_SMCONNCODE42 ,			 
			P_SMCONNCODE51 ,			 
			P_SMCONNCODE52 ,			 
			P_SMAREACODE1 ,			 
			P_SMAREACODE2 ,				 
			P_SMAREACODE3 ,				 
			P_SMAREACODE4 ,				 
			P_SMAREACODE5 ,				 
			P_SMAREATEXT1 ,				 
			P_SMAREATEXT2 ,				 
			P_SMAREATEXT3 ,				 
			P_SMAREATEXT4 ,				 
			P_SMAREATEXT5 ,				 
			P_SMMATERTEXT1 ,				 
			P_SMMATERTEXT2 ,				 
			P_SMNOTE_BURN ,				 
			P_SMNOTE_SUFF ,				 
			P_SMNOTE_ELE ,				 
			P_SMNOTE_FIR ,				 
			P_SMNOTE_EXP ,				 
			P_SMNOTE_DROP ,				 
			P_SMNOTE_LEAK ,				 
			P_SMNOTE_NARR ,				 
			P_SMNOTE_COLL ,				 
			P_SMCHKSABUN1 ,			 
			P_SMCHKTIME1 ,		 
			P_SMCHKOXYGEN1 ,			 
			P_SMCHKOXYGENUNIT1 , 
			P_SMCHKTOXNUM1 ,			 
			P_SMCHKTOXUNIT1 ,			 
			P_SMCHKTOXNUM1DS ,			 
			P_SMCHKTOXUNIT1DS ,			 
			P_SMCHKTOXNUM1CO2 ,			 
			P_SMCHKTOXUNIT1CO2 , 
			P_SMCHKTOXNUM1CO ,			 
			P_SMCHKTOXUNIT1CO , 
			P_SMCHKTOXNUM1H2S ,			 
			P_SMCHKTOXUNIT1H2S , 
			P_SMCHKSABUN2 ,			 
			P_SMCHKTIME2 ,			 
			P_SMCHKOXYGEN2 ,		 
			P_SMCHKOXYGENUNIT2 , 
			P_SMCHKTOXNUM2 ,			 
			P_SMCHKTOXUNIT2 ,			 
			P_SMCHKTOXNUM2DS ,			 
			P_SMCHKTOXUNIT2DS ,			 
			P_SMCHKTOXNUM2CO2 ,			 
			P_SMCHKTOXUNIT2CO2 ,			 
			P_SMCHKTOXNUM2CO ,			 
			P_SMCHKTOXUNIT2CO , 
			P_SMCHKTOXNUM2H2S ,			 
			P_SMCHKTOXUNIT2H2S , 
			P_SMCHKSABUN3 ,			 
			P_SMCHKTIME3 ,			 
			P_SMCHKOXYGEN3 ,			 
			P_SMCHKOXYGENUNIT3 ,		 
			P_SMCHKTOXNUM3 ,			 
			P_SMCHKTOXUNIT3 ,			 
			P_SMCHKTOXNUM3DS ,			 
			P_SMCHKTOXUNIT3DS ,			 
			P_SMCHKTOXNUM3CO2 ,			 
			P_SMCHKTOXUNIT3CO2 , 
			P_SMCHKTOXNUM3CO ,			 
			P_SMCHKTOXUNIT3CO , 
			P_SMCHKTOXNUM3H2S ,			 
			P_SMCHKTOXUNIT3H2S , 
			P_SMCHKSABUN4 ,			 
			P_SMCHKTIME4 ,			 
			P_SMCHKOXYGEN4 ,			 
			P_SMCHKOXYGENUNIT4 , 
			P_SMCHKTOXNUM4 ,		 
			P_SMCHKTOXUNIT4 ,			 
			P_SMCHKTOXNUM4DS ,			 
			P_SMCHKTOXUNIT4DS ,			 
			P_SMCHKTOXNUM4CO2 ,			 
			P_SMCHKTOXUNIT4CO2 , 
			P_SMCHKTOXNUM4CO ,			 
			P_SMCHKTOXUNIT4CO ,			 
			P_SMCHKTOXNUM4H2S ,			 
			P_SMCHKTOXUNIT4H2S , 
			P_SMCHKSABUN5 ,			 
			P_SMCHKTIME5 ,			 
			P_SMCHKOXYGEN5 ,			 
			P_SMCHKOXYGENUNIT5 , 
			P_SMCHKTOXNUM5 ,			 
			P_SMCHKTOXUNIT5 ,		 
			P_SMCHKTOXNUM5DS ,			 
			P_SMCHKTOXUNIT5DS ,			 
			P_SMCHKTOXNUM5CO2 ,			 
			P_SMCHKTOXUNIT5CO2 , 
			P_SMCHKTOXNUM5CO ,			 
			P_SMCHKTOXUNIT5CO , 
			P_SMCHKTOXNUM5H2S ,			 
			P_SMCHKTOXUNIT5H2S , 
			P_SMCHKSABUN6 ,			 
			P_SMCHKTIME6 ,			 
			P_SMCHKOXYGEN6 ,			 
			P_SMCHKOXYGENUNIT6 , 
			P_SMCHKTOXNUM6 ,			 
			P_SMCHKTOXUNIT6 ,			 
			P_SMCHKTOXNUM6DS ,		 
			P_SMCHKTOXUNIT6DS ,			 
			P_SMCHKTOXNUM6CO2 ,			 
			P_SMCHKTOXUNIT6CO2 , 
			P_SMCHKTOXNUM6CO ,			 
			P_SMCHKTOXUNIT6CO , 
			P_SMCHKTOXNUM6H2S ,			 
			P_SMCHKTOXUNIT6H2S ,			 
			P_SMCHKSABUN7 ,			 
			P_SMCHKTIME7 ,			 
			P_SMCHKOXYGEN7 ,			 
			P_SMCHKOXYGENUNIT7 , 
			P_SMCHKTOXNUM7 ,			 
			P_SMCHKTOXUNIT7 ,			 
			P_SMCHKTOXNUM7DS ,			 
			P_SMCHKTOXUNIT7DS ,			 
			P_SMCHKTOXNUM7CO2 ,			 
			P_SMCHKTOXUNIT7CO2 , 
			P_SMCHKTOXNUM7CO ,			 
			P_SMCHKTOXUNIT7CO , 
			P_SMCHKTOXNUM7H2S ,			 
			P_SMCHKTOXUNIT7H2S ,			 
			P_SMCHKSABUN8 ,			 
			P_SMCHKTIME8 ,			 
			P_SMCHKOXYGEN8 ,			 
			P_SMCHKOXYGENUNIT8 , 
			P_SMCHKTOXNUM8 ,			 
			P_SMCHKTOXUNIT8 ,			 
			P_SMCHKTOXNUM8DS ,			 
			P_SMCHKTOXUNIT8DS ,			 
			P_SMCHKTOXNUM8CO2 ,			 
			P_SMCHKTOXUNIT8CO2 , 
			P_SMCHKTOXNUM8CO ,			 
			P_SMCHKTOXUNIT8CO , 
			P_SMCHKTOXNUM8H2S ,			 
			P_SMCHKTOXUNIT8H2S ,			 
			P_SMORDERTEXT1 ,	 
			P_SMORDERTEXT2 ,				 
			P_SMORSABUN ,	 
			P_SMORNAME ,	 
			P_SMORJKCD ,	 
			P_SMORJKCDNM ,				 
			P_SMGRSABUN ,				 
			P_SMGRNAME ,				 
			P_SMGRJKCD ,				 
			P_SMGRJKCDNM ,			 
			P_SMCOSABUN ,				 
			P_SMCONAME ,				 
			P_SMCOJKCD ,				 
			P_SMCOJKCDNM ,				 
			P_SMSMSABUN ,				 
			P_SMSMCOMMENT , 
			P_SMCHKTOXGUBN1 , 
			P_SMCHKTOXGUBN2 , 
			P_SMCHKTOXGUBN3 , 
			P_SMCHKTOXGUBN4 , 
			P_SMCHKTOXGUBN5 , 
			P_SMCHKTOXGUBN6 , 
			P_SMWORKTITLE ,				 
			P_SMOPSABUN ,				 
			P_SMOPCOMMENT ,
			P_SMFIREINS,
			'A' ,					 
			CURRENT_DATE ,				 
			CURRENT_TIME ,			 
			P_SMHISAB				 
		) ; 
  
	ELSE 
  
		IF ( TRIM ( P_GUBUN ) = 'APPROVAL' ) THEN 
			 
			UPDATE PSSCMLIB . PSM_SAFEORDER_MASTER SET 
				SMREVTEAM = P_SMREVTEAM , 
				SMWKMETHOD = P_SMWKMETHOD , 
				SMSUBVEND = P_SMSUBVEND , 
				SMSUBPERSON = P_SMSUBPERSON , 
				SMSUBTEL = P_SMSUBTEL , 
				SMRESSABUN = P_SMRESSABUN , 
				SMWKMAN = P_SMWKMAN , 
				SMTADATE1 = P_SMTADATE1 , 
				SMTATIME1 = P_SMTATIME1 , 
				SMTADATE2 = P_SMTADATE2 , 
				SMTATIME2 = P_SMTATIME2 , 
				SMOTDATE1 = P_SMOTDATE1 , 
				SMOTTIME1 = P_SMOTTIME1 , 
				SMOTDATE2 = P_SMOTDATE2 , 
				SMOTTIME2 = P_SMOTTIME2 , 
				SMOTAPPSABUN = P_SMOTAPPSABUN , 
				SMSYSTEMCODE1 = P_SMSYSTEMCODE1 , 
				SMSYSTEMCODE2 = P_SMSYSTEMCODE2 , 
				SMSYSTEMCODE3 = P_SMSYSTEMCODE3 , 
				SMSYSTEMCODE4 = P_SMSYSTEMCODE4 , 
				SMSYSTEMCODE5 = P_SMSYSTEMCODE5 , 
				SMCONNCODE11 = P_SMCONNCODE11 , 
				SMCONNCODE12 = P_SMCONNCODE12 , 
				SMCONNCODE21 = P_SMCONNCODE21 , 
				SMCONNCODE22 = P_SMCONNCODE22 , 
				SMCONNCODE31 = P_SMCONNCODE31 , 
				SMCONNCODE32 = P_SMCONNCODE32 , 
				SMCONNCODE41 = P_SMCONNCODE41 , 
				SMCONNCODE42 = P_SMCONNCODE42 , 
				SMCONNCODE51 = P_SMCONNCODE51 , 
				SMCONNCODE52 = P_SMCONNCODE52 , 
				SMAREACODE1 = P_SMAREACODE1 , 
				SMAREACODE2 = P_SMAREACODE2 , 
				SMAREACODE3 = P_SMAREACODE3 , 
				SMAREACODE4 = P_SMAREACODE4 , 
				SMAREACODE5 = P_SMAREACODE5 , 
				SMAREATEXT1 = P_SMAREATEXT1 , 
				SMAREATEXT2 = P_SMAREATEXT2 , 
				SMAREATEXT3 = P_SMAREATEXT3 , 
				SMAREATEXT4 = P_SMAREATEXT4 , 
				SMAREATEXT5 = P_SMAREATEXT5 , 
				SMMATERTEXT1 = P_SMMATERTEXT1 , 
				SMMATERTEXT2 = P_SMMATERTEXT2 , 
				SMNOTE_BURN = P_SMNOTE_BURN , 
				SMNOTE_SUFF = P_SMNOTE_SUFF , 
				SMNOTE_ELE = P_SMNOTE_ELE , 
				SMNOTE_FIR = P_SMNOTE_FIR , 
				SMNOTE_EXP = P_SMNOTE_EXP , 
				SMNOTE_DROP = P_SMNOTE_DROP , 
				SMNOTE_LEAK = P_SMNOTE_LEAK , 
				SMNOTE_NARR = P_SMNOTE_NARR , 
				SMNOTE_COLL = P_SMNOTE_COLL , 
				SMCHKSABUN1 = P_SMCHKSABUN1 , 
				SMCHKTIME1 = P_SMCHKTIME1 , 
				SMCHKOXYGEN1 = P_SMCHKOXYGEN1 , 
				SMCHKOXYGENUNIT1 = P_SMCHKOXYGENUNIT1 , 
				SMCHKTOXNUM1 = P_SMCHKTOXNUM1 , 
				SMCHKTOXUNIT1 = P_SMCHKTOXUNIT1 , 
				SMCHKTOXNUM1DS = P_SMCHKTOXNUM1DS , 
				SMCHKTOXUNIT1DS = P_SMCHKTOXUNIT1DS , 
				SMCHKTOXNUM1CO2 = P_SMCHKTOXNUM1CO2 , 
				SMCHKTOXUNIT1CO2 = P_SMCHKTOXUNIT1CO2 , 
				SMCHKTOXNUM1CO = P_SMCHKTOXNUM1CO , 
				SMCHKTOXUNIT1CO = P_SMCHKTOXUNIT1CO , 
				SMCHKTOXNUM1H2S = P_SMCHKTOXNUM1H2S , 
				SMCHKTOXUNIT1H2S = P_SMCHKTOXUNIT1H2S , 
				SMCHKSABUN2 = P_SMCHKSABUN2 , 
				SMCHKTIME2 = P_SMCHKTIME2 , 
				SMCHKOXYGEN2 = P_SMCHKOXYGEN2 , 
				SMCHKOXYGENUNIT2 = P_SMCHKOXYGENUNIT2 , 
				SMCHKTOXNUM2 = P_SMCHKTOXNUM2 , 
				SMCHKTOXUNIT2 = P_SMCHKTOXUNIT2 , 
				SMCHKTOXNUM2DS = P_SMCHKTOXNUM2DS , 
				SMCHKTOXUNIT2DS = P_SMCHKTOXUNIT2DS , 
				SMCHKTOXNUM2CO2 = P_SMCHKTOXNUM2CO2 , 
				SMCHKTOXUNIT2CO2 = P_SMCHKTOXUNIT2CO2 , 
				SMCHKTOXNUM2CO = P_SMCHKTOXNUM2CO , 
				SMCHKTOXUNIT2CO = P_SMCHKTOXUNIT2CO , 
				SMCHKTOXNUM2H2S = P_SMCHKTOXNUM2H2S , 
				SMCHKTOXUNIT2H2S = P_SMCHKTOXUNIT2H2S , 
				SMCHKSABUN3 = P_SMCHKSABUN3 , 
				SMCHKTIME3 = P_SMCHKTIME3 , 
				SMCHKOXYGEN3 = P_SMCHKOXYGEN3 , 
				SMCHKOXYGENUNIT3 = P_SMCHKOXYGENUNIT3 , 
				SMCHKTOXNUM3 = P_SMCHKTOXNUM3 , 
				SMCHKTOXUNIT3 = P_SMCHKTOXUNIT3 , 
				SMCHKTOXNUM3DS = P_SMCHKTOXNUM3DS , 
				SMCHKTOXUNIT3DS = P_SMCHKTOXUNIT3DS , 
				SMCHKTOXNUM3CO2 = P_SMCHKTOXNUM3CO2 , 
				SMCHKTOXUNIT3CO2 = P_SMCHKTOXUNIT3CO2 , 
				SMCHKTOXNUM3CO = P_SMCHKTOXNUM3CO , 
				SMCHKTOXUNIT3CO = P_SMCHKTOXUNIT3CO , 
				SMCHKTOXNUM3H2S = P_SMCHKTOXNUM3H2S , 
				SMCHKTOXUNIT3H2S = P_SMCHKTOXUNIT3H2S , 
				SMCHKSABUN4 = P_SMCHKSABUN4 , 
				SMCHKTIME4 = P_SMCHKTIME4 , 
				SMCHKOXYGEN4 = P_SMCHKOXYGEN4 , 
				SMCHKOXYGENUNIT4 = P_SMCHKOXYGENUNIT4 , 
				SMCHKTOXNUM4 = P_SMCHKTOXNUM4 , 
				SMCHKTOXUNIT4 = P_SMCHKTOXUNIT4 , 
				SMCHKTOXNUM4DS = P_SMCHKTOXNUM4DS , 
				SMCHKTOXUNIT4DS = P_SMCHKTOXUNIT4DS , 
				SMCHKTOXNUM4CO2 = P_SMCHKTOXNUM4CO2 , 
				SMCHKTOXUNIT4CO2 = P_SMCHKTOXUNIT4CO2 , 
				SMCHKTOXNUM4CO = P_SMCHKTOXNUM4CO , 
				SMCHKTOXUNIT4CO = P_SMCHKTOXUNIT4CO , 
				SMCHKTOXNUM4H2S = P_SMCHKTOXNUM4H2S , 
				SMCHKTOXUNIT4H2S = P_SMCHKTOXUNIT4H2S , 
				SMCHKSABUN5 = P_SMCHKSABUN5 , 
				SMCHKTIME5 = P_SMCHKTIME5 , 
				SMCHKOXYGEN5 = P_SMCHKOXYGEN5 , 
				SMCHKOXYGENUNIT5 = P_SMCHKOXYGENUNIT5 , 
				SMCHKTOXNUM5 = P_SMCHKTOXNUM5 , 
				SMCHKTOXUNIT5 = P_SMCHKTOXUNIT5 , 
				SMCHKTOXNUM5DS = P_SMCHKTOXNUM5DS , 
				SMCHKTOXUNIT5DS = P_SMCHKTOXUNIT5DS , 
				SMCHKTOXNUM5CO2 = P_SMCHKTOXNUM5CO2 , 
				SMCHKTOXUNIT5CO2 = P_SMCHKTOXUNIT5CO2 , 
				SMCHKTOXNUM5CO = P_SMCHKTOXNUM5CO , 
				SMCHKTOXUNIT5CO = P_SMCHKTOXUNIT5CO , 
				SMCHKTOXNUM5H2S = P_SMCHKTOXNUM5H2S , 
				SMCHKTOXUNIT5H2S = P_SMCHKTOXUNIT5H2S , 
				SMCHKSABUN6 = P_SMCHKSABUN6 , 
				SMCHKTIME6 = P_SMCHKTIME6 , 
				SMCHKOXYGEN6 = P_SMCHKOXYGEN6 , 
				SMCHKOXYGENUNIT6 = P_SMCHKOXYGENUNIT6 , 
				SMCHKTOXNUM6 = P_SMCHKTOXNUM6 , 
				SMCHKTOXUNIT6 = P_SMCHKTOXUNIT6 , 
				SMCHKTOXNUM6DS = P_SMCHKTOXNUM6DS , 
				SMCHKTOXUNIT6DS = P_SMCHKTOXUNIT6DS , 
				SMCHKTOXNUM6CO2 = P_SMCHKTOXNUM6CO2 , 
				SMCHKTOXUNIT6CO2 = P_SMCHKTOXUNIT6CO2 , 
				SMCHKTOXNUM6CO = P_SMCHKTOXNUM6CO , 
				SMCHKTOXUNIT6CO = P_SMCHKTOXUNIT6CO , 
				SMCHKTOXNUM6H2S = P_SMCHKTOXNUM6H2S , 
				SMCHKTOXUNIT6H2S = P_SMCHKTOXUNIT6H2S , 
				SMCHKSABUN7 = P_SMCHKSABUN7 , 
				SMCHKTIME7 = P_SMCHKTIME7 , 
				SMCHKOXYGEN7 = P_SMCHKOXYGEN7 , 
				SMCHKOXYGENUNIT7 = P_SMCHKOXYGENUNIT7 , 
				SMCHKTOXNUM7 = P_SMCHKTOXNUM7 , 
				SMCHKTOXUNIT7 = P_SMCHKTOXUNIT7 , 
				SMCHKTOXNUM7DS = P_SMCHKTOXNUM7DS , 
				SMCHKTOXUNIT7DS = P_SMCHKTOXUNIT7DS , 
				SMCHKTOXNUM7CO2 = P_SMCHKTOXNUM7CO2 , 
				SMCHKTOXUNIT7CO2 = P_SMCHKTOXUNIT7CO2 , 
				SMCHKTOXNUM7CO = P_SMCHKTOXNUM7CO , 
				SMCHKTOXUNIT7CO = P_SMCHKTOXUNIT7CO , 
				SMCHKTOXNUM7H2S = P_SMCHKTOXNUM7H2S , 
				SMCHKTOXUNIT7H2S = P_SMCHKTOXUNIT7H2S , 
				SMCHKSABUN8 = P_SMCHKSABUN8 , 
				SMCHKTIME8 = P_SMCHKTIME8 , 
				SMCHKOXYGEN8 = P_SMCHKOXYGEN8 , 
				SMCHKOXYGENUNIT8 = P_SMCHKOXYGENUNIT8 , 
				SMCHKTOXNUM8 = P_SMCHKTOXNUM8 , 
				SMCHKTOXUNIT8 = P_SMCHKTOXUNIT8 , 
				SMCHKTOXNUM8DS = P_SMCHKTOXNUM8DS , 
				SMCHKTOXUNIT8DS = P_SMCHKTOXUNIT8DS , 
				SMCHKTOXNUM8CO2 = P_SMCHKTOXNUM8CO2 , 
				SMCHKTOXUNIT8CO2 = P_SMCHKTOXUNIT8CO2 , 
				SMCHKTOXNUM8CO = P_SMCHKTOXNUM8CO , 
				SMCHKTOXUNIT8CO = P_SMCHKTOXUNIT8CO , 
				SMCHKTOXNUM8H2S = P_SMCHKTOXNUM8H2S , 
				SMCHKTOXUNIT8H2S = P_SMCHKTOXUNIT8H2S , 
				SMORDERTEXT1 = P_SMORDERTEXT1 , 
				SMORDERTEXT2 = P_SMORDERTEXT2 , 
				SMORSABUN = P_SMORSABUN , 
				SMORNAME	= P_SMORNAME , 
				SMORJKCD	= P_SMORJKCD , 
				SMORJKCDNM	= P_SMORJKCDNM , 
				SMGRSABUN	= P_SMGRSABUN , 
				SMGRNAME	= P_SMGRNAME , 
				SMGRJKCD	= P_SMGRJKCD , 
				SMGRJKCDNM	= P_SMGRJKCDNM , 
				SMCOSABUN	= P_SMCOSABUN , 
				SMCONAME	= P_SMCONAME , 
				SMCOJKCD	= P_SMCOJKCD , 
				SMCOJKCDNM	= P_SMCOJKCDNM , 
				SMSMSABUN	= P_SMSMSABUN , 
				SMSMCOMMENT = P_SMSMCOMMENT , 
				SMCHKTOXGUBN1 = P_SMCHKTOXGUBN1 , 
				SMCHKTOXGUBN2	= P_SMCHKTOXGUBN2 , 
				SMCHKTOXGUBN3	= P_SMCHKTOXGUBN3 , 
				SMCHKTOXGUBN4	= P_SMCHKTOXGUBN4 , 
				SMCHKTOXGUBN5	= P_SMCHKTOXGUBN5 , 
				SMCHKTOXGUBN6	= P_SMCHKTOXGUBN6 , 
				SMWORKTITLE	= P_SMWORKTITLE , 
				SMOPSABUN	= P_SMOPSABUN , 
				SMOPCOMMENT	= P_SMOPCOMMENT , 
				SMFIREINS       = P_SMFIREINS,
				SMHIGB		= 'C' , 
				SMHIDAT		= CURRENT_DATE , 
				SMHITIM		= CURRENT_TIME 
			WHERE SMWKTEAM = P_SMWKTEAM 
			AND SMWKDATE = P_SMWKDATE 
			AND SMWKSEQ = P_SMWKSEQ 
			AND SMWKORAPPDATE = P_SMWKORAPPDATE 
			AND SMWKORSEQ = P_SMWKORSEQ ; 
  
		ELSE 
  
			UPDATE PSSCMLIB . PSM_SAFEORDER_MASTER SET 
				SMREVTEAM = P_SMREVTEAM , 
				SMWKMETHOD = P_SMWKMETHOD , 
				SMSUBVEND = P_SMSUBVEND , 
				SMSUBPERSON = P_SMSUBPERSON , 
				SMSUBTEL = P_SMSUBTEL , 
				SMRESSABUN = P_SMRESSABUN , 
				SMWKMAN = P_SMWKMAN , 
				SMTADATE1 = P_SMTADATE1 , 
				SMTATIME1 = P_SMTATIME1 , 
				SMTADATE2 = P_SMTADATE2 , 
				SMTATIME2 = P_SMTATIME2 , 
				SMOTDATE1 = P_SMOTDATE1 , 
				SMOTTIME1 = P_SMOTTIME1 , 
				SMOTDATE2 = P_SMOTDATE2 , 
				SMOTTIME2 = P_SMOTTIME2 , 
				SMOTAPPSABUN = P_SMOTAPPSABUN , 
				SMSYSTEMCODE1 = P_SMSYSTEMCODE1 , 
				SMSYSTEMCODE2 = P_SMSYSTEMCODE2 , 
				SMSYSTEMCODE3 = P_SMSYSTEMCODE3 , 
				SMSYSTEMCODE4 = P_SMSYSTEMCODE4 , 
				SMSYSTEMCODE5 = P_SMSYSTEMCODE5 , 
				SMCONNCODE11 = P_SMCONNCODE11 , 
				SMCONNCODE12 = P_SMCONNCODE12 , 
				SMCONNCODE21 = P_SMCONNCODE21 , 
				SMCONNCODE22 = P_SMCONNCODE22 , 
				SMCONNCODE31 = P_SMCONNCODE31 , 
				SMCONNCODE32 = P_SMCONNCODE32 , 
				SMCONNCODE41 = P_SMCONNCODE41 , 
				SMCONNCODE42 = P_SMCONNCODE42 , 
				SMCONNCODE51 = P_SMCONNCODE51 , 
				SMCONNCODE52 = P_SMCONNCODE52 , 
				SMAREACODE1 = P_SMAREACODE1 , 
				SMAREACODE2 = P_SMAREACODE2 , 
				SMAREACODE3 = P_SMAREACODE3 , 
				SMAREACODE4 = P_SMAREACODE4 , 
				SMAREACODE5 = P_SMAREACODE5 , 
				SMAREATEXT1 = P_SMAREATEXT1 , 
				SMAREATEXT2 = P_SMAREATEXT2 , 
				SMAREATEXT3 = P_SMAREATEXT3 , 
				SMAREATEXT4 = P_SMAREATEXT4 , 
				SMAREATEXT5 = P_SMAREATEXT5 , 
				SMMATERTEXT1 = P_SMMATERTEXT1 , 
				SMMATERTEXT2 = P_SMMATERTEXT2 , 
				SMNOTE_BURN = P_SMNOTE_BURN , 
				SMNOTE_SUFF = P_SMNOTE_SUFF , 
				SMNOTE_ELE = P_SMNOTE_ELE , 
				SMNOTE_FIR = P_SMNOTE_FIR , 
				SMNOTE_EXP = P_SMNOTE_EXP , 
				SMNOTE_DROP = P_SMNOTE_DROP , 
				SMNOTE_LEAK = P_SMNOTE_LEAK , 
				SMNOTE_NARR = P_SMNOTE_NARR , 
				SMNOTE_COLL = P_SMNOTE_COLL , 
				SMCHKSABUN1 = P_SMCHKSABUN1 , 
				SMCHKTIME1 = P_SMCHKTIME1 , 
				SMCHKOXYGEN1 = P_SMCHKOXYGEN1 , 
				SMCHKOXYGENUNIT1 = P_SMCHKOXYGENUNIT1 , 
				SMCHKTOXNUM1 = P_SMCHKTOXNUM1 , 
				SMCHKTOXUNIT1 = P_SMCHKTOXUNIT1 , 
				SMCHKTOXNUM1DS = P_SMCHKTOXNUM1DS , 
				SMCHKTOXUNIT1DS = P_SMCHKTOXUNIT1DS , 
				SMCHKTOXNUM1CO2 = P_SMCHKTOXNUM1CO2 , 
				SMCHKTOXUNIT1CO2 = P_SMCHKTOXUNIT1CO2 , 
				SMCHKTOXNUM1CO = P_SMCHKTOXNUM1CO , 
				SMCHKTOXUNIT1CO = P_SMCHKTOXUNIT1CO , 
				SMCHKTOXNUM1H2S = P_SMCHKTOXNUM1H2S , 
				SMCHKTOXUNIT1H2S = P_SMCHKTOXUNIT1H2S , 
				SMCHKSABUN2 = P_SMCHKSABUN2 , 
				SMCHKTIME2 = P_SMCHKTIME2 , 
				SMCHKOXYGEN2 = P_SMCHKOXYGEN2 , 
				SMCHKOXYGENUNIT2 = P_SMCHKOXYGENUNIT2 , 
				SMCHKTOXNUM2 = P_SMCHKTOXNUM2 , 
				SMCHKTOXUNIT2 = P_SMCHKTOXUNIT2 , 
				SMCHKTOXNUM2DS = P_SMCHKTOXNUM2DS , 
				SMCHKTOXUNIT2DS = P_SMCHKTOXUNIT2DS , 
				SMCHKTOXNUM2CO2 = P_SMCHKTOXNUM2CO2 , 
				SMCHKTOXUNIT2CO2 = P_SMCHKTOXUNIT2CO2 , 
				SMCHKTOXNUM2CO = P_SMCHKTOXNUM2CO , 
				SMCHKTOXUNIT2CO = P_SMCHKTOXUNIT2CO , 
				SMCHKTOXNUM2H2S = P_SMCHKTOXNUM2H2S , 
				SMCHKTOXUNIT2H2S = P_SMCHKTOXUNIT2H2S , 
				SMCHKSABUN3 = P_SMCHKSABUN3 , 
				SMCHKTIME3 = P_SMCHKTIME3 , 
				SMCHKOXYGEN3 = P_SMCHKOXYGEN3 , 
				SMCHKOXYGENUNIT3 = P_SMCHKOXYGENUNIT3 , 
				SMCHKTOXNUM3 = P_SMCHKTOXNUM3 , 
				SMCHKTOXUNIT3 = P_SMCHKTOXUNIT3 , 
				SMCHKTOXNUM3DS = P_SMCHKTOXNUM3DS , 
				SMCHKTOXUNIT3DS = P_SMCHKTOXUNIT3DS , 
				SMCHKTOXNUM3CO2 = P_SMCHKTOXNUM3CO2 , 
				SMCHKTOXUNIT3CO2 = P_SMCHKTOXUNIT3CO2 , 
				SMCHKTOXNUM3CO = P_SMCHKTOXNUM3CO , 
				SMCHKTOXUNIT3CO = P_SMCHKTOXUNIT3CO , 
				SMCHKTOXNUM3H2S = P_SMCHKTOXNUM3H2S , 
				SMCHKTOXUNIT3H2S = P_SMCHKTOXUNIT3H2S , 
				SMCHKSABUN4 = P_SMCHKSABUN4 , 
				SMCHKTIME4 = P_SMCHKTIME4 , 
				SMCHKOXYGEN4 = P_SMCHKOXYGEN4 , 
				SMCHKOXYGENUNIT4 = P_SMCHKOXYGENUNIT4 , 
				SMCHKTOXNUM4 = P_SMCHKTOXNUM4 , 
				SMCHKTOXUNIT4 = P_SMCHKTOXUNIT4 , 
				SMCHKTOXNUM4DS = P_SMCHKTOXNUM4DS , 
				SMCHKTOXUNIT4DS = P_SMCHKTOXUNIT4DS , 
				SMCHKTOXNUM4CO2 = P_SMCHKTOXNUM4CO2 , 
				SMCHKTOXUNIT4CO2 = P_SMCHKTOXUNIT4CO2 , 
				SMCHKTOXNUM4CO = P_SMCHKTOXNUM4CO , 
				SMCHKTOXUNIT4CO = P_SMCHKTOXUNIT4CO , 
				SMCHKTOXNUM4H2S = P_SMCHKTOXNUM4H2S , 
				SMCHKTOXUNIT4H2S = P_SMCHKTOXUNIT4H2S , 
				SMCHKSABUN5 = P_SMCHKSABUN5 , 
				SMCHKTIME5 = P_SMCHKTIME5 , 
				SMCHKOXYGEN5 = P_SMCHKOXYGEN5 , 
				SMCHKOXYGENUNIT5 = P_SMCHKOXYGENUNIT5 , 
				SMCHKTOXNUM5 = P_SMCHKTOXNUM5 , 
				SMCHKTOXUNIT5 = P_SMCHKTOXUNIT5 , 
				SMCHKTOXNUM5DS = P_SMCHKTOXNUM5DS , 
				SMCHKTOXUNIT5DS = P_SMCHKTOXUNIT5DS , 
				SMCHKTOXNUM5CO2 = P_SMCHKTOXNUM5CO2 , 
				SMCHKTOXUNIT5CO2 = P_SMCHKTOXUNIT5CO2 , 
				SMCHKTOXNUM5CO = P_SMCHKTOXNUM5CO , 
				SMCHKTOXUNIT5CO = P_SMCHKTOXUNIT5CO , 
				SMCHKTOXNUM5H2S = P_SMCHKTOXNUM5H2S , 
				SMCHKTOXUNIT5H2S = P_SMCHKTOXUNIT5H2S , 
				SMCHKSABUN6 = P_SMCHKSABUN6 , 
				SMCHKTIME6 = P_SMCHKTIME6 , 
				SMCHKOXYGEN6 = P_SMCHKOXYGEN6 , 
				SMCHKOXYGENUNIT6 = P_SMCHKOXYGENUNIT6 , 
				SMCHKTOXNUM6 = P_SMCHKTOXNUM6 , 
				SMCHKTOXUNIT6 = P_SMCHKTOXUNIT6 , 
				SMCHKTOXNUM6DS = P_SMCHKTOXNUM6DS , 
				SMCHKTOXUNIT6DS = P_SMCHKTOXUNIT6DS , 
				SMCHKTOXNUM6CO2 = P_SMCHKTOXNUM6CO2 , 
				SMCHKTOXUNIT6CO2 = P_SMCHKTOXUNIT6CO2 , 
				SMCHKTOXNUM6CO = P_SMCHKTOXNUM6CO , 
				SMCHKTOXUNIT6CO = P_SMCHKTOXUNIT6CO , 
				SMCHKTOXNUM6H2S = P_SMCHKTOXNUM6H2S , 
				SMCHKTOXUNIT6H2S = P_SMCHKTOXUNIT6H2S , 
				SMCHKSABUN7 = P_SMCHKSABUN7 , 
				SMCHKTIME7 = P_SMCHKTIME7 , 
				SMCHKOXYGEN7 = P_SMCHKOXYGEN7 , 
				SMCHKOXYGENUNIT7 = P_SMCHKOXYGENUNIT7 , 
				SMCHKTOXNUM7 = P_SMCHKTOXNUM7 , 
				SMCHKTOXUNIT7 = P_SMCHKTOXUNIT7 , 
				SMCHKTOXNUM7DS = P_SMCHKTOXNUM7DS , 
				SMCHKTOXUNIT7DS = P_SMCHKTOXUNIT7DS , 
				SMCHKTOXNUM7CO2 = P_SMCHKTOXNUM7CO2 , 
				SMCHKTOXUNIT7CO2 = P_SMCHKTOXUNIT7CO2 , 
				SMCHKTOXNUM7CO = P_SMCHKTOXNUM7CO , 
				SMCHKTOXUNIT7CO = P_SMCHKTOXUNIT7CO , 
				SMCHKTOXNUM7H2S = P_SMCHKTOXNUM7H2S , 
				SMCHKTOXUNIT7H2S = P_SMCHKTOXUNIT7H2S , 
				SMCHKSABUN8 = P_SMCHKSABUN8 , 
				SMCHKTIME8 = P_SMCHKTIME8 , 
				SMCHKOXYGEN8 = P_SMCHKOXYGEN8 , 
				SMCHKOXYGENUNIT8 = P_SMCHKOXYGENUNIT8 , 
				SMCHKTOXNUM8 = P_SMCHKTOXNUM8 , 
				SMCHKTOXUNIT8 = P_SMCHKTOXUNIT8 , 
				SMCHKTOXNUM8DS = P_SMCHKTOXNUM8DS , 
				SMCHKTOXUNIT8DS = P_SMCHKTOXUNIT8DS , 
				SMCHKTOXNUM8CO2 = P_SMCHKTOXNUM8CO2 , 
				SMCHKTOXUNIT8CO2 = P_SMCHKTOXUNIT8CO2 , 
				SMCHKTOXNUM8CO = P_SMCHKTOXNUM8CO , 
				SMCHKTOXUNIT8CO = P_SMCHKTOXUNIT8CO , 
				SMCHKTOXNUM8H2S = P_SMCHKTOXNUM8H2S , 
				SMCHKTOXUNIT8H2S = P_SMCHKTOXUNIT8H2S , 
				SMORDERTEXT1 = P_SMORDERTEXT1 , 
				SMORDERTEXT2 = P_SMORDERTEXT2 , 
				SMORSABUN = P_SMORSABUN , 
				SMORNAME	= P_SMORNAME , 
				SMORJKCD	= P_SMORJKCD , 
				SMORJKCDNM	= P_SMORJKCDNM , 
				SMGRSABUN	= P_SMGRSABUN , 
				SMGRNAME	= P_SMGRNAME , 
				SMGRJKCD	= P_SMGRJKCD , 
				SMGRJKCDNM	= P_SMGRJKCDNM , 
				SMCOSABUN	= P_SMCOSABUN , 
				SMCONAME	= P_SMCONAME , 
				SMCOJKCD	= P_SMCOJKCD , 
				SMCOJKCDNM	= P_SMCOJKCDNM , 
				SMSMSABUN	= P_SMSMSABUN , 
				SMSMCOMMENT = P_SMSMCOMMENT , 
				SMCHKTOXGUBN1 = P_SMCHKTOXGUBN1 , 
				SMCHKTOXGUBN2	= P_SMCHKTOXGUBN2 , 
				SMCHKTOXGUBN3	= P_SMCHKTOXGUBN3 , 
				SMCHKTOXGUBN4	= P_SMCHKTOXGUBN4 , 
				SMCHKTOXGUBN5	= P_SMCHKTOXGUBN5 , 
				SMCHKTOXGUBN6	= P_SMCHKTOXGUBN6 , 
				SMWORKTITLE	= P_SMWORKTITLE , 
				SMOPSABUN	= P_SMOPSABUN , 
				SMOPCOMMENT	= P_SMOPCOMMENT , 
				SMFIREINS       = P_SMFIREINS,
				SMHIGB		= 'C' , 
				SMHIDAT		= CURRENT_DATE , 
				SMHITIM		= CURRENT_TIME , 
				SMHISAB		= P_SMHISAB 
			WHERE SMWKTEAM = P_SMWKTEAM 
			AND SMWKDATE = P_SMWKDATE 
			AND SMWKSEQ = P_SMWKSEQ 
			AND SMWKORAPPDATE = P_SMWKORAPPDATE 
			AND SMWKORSEQ = P_SMWKORSEQ ; 
  
		END IF ; 
  
	END IF ; 
  
	 -- 참조자 저장 
	CALL PSSCMLIB . PSM_REFERENCE_UPDATE ( 'A' , '05' , P_SMWKTEAM || P_SMWKDATE || DIGITS ( P_SMWKSEQ ) || P_SMWKORAPPDATE || DIGITS ( P_SMWKORSEQ ) , P_RESABUN , P_RENAME , P_SMHISAB ) ; 
  
	 -- 안전작업허가서 작업내용 삭제 
	CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_WKCODE_DEL ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ ) ; 
  
	IF ( P_SWWKCODE1 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '01' ; 
		SET V_SWWKNAME = '일반위험작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE2 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '02' ; 
		SET V_SWWKNAME = '열간(화기)작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE3 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '03' ; 
		SET V_SWWKNAME = '밀폐공간출입작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE4 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '04' ; 
		SET V_SWWKNAME = 'Tank Cleaning' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE5 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '05' ; 
		SET V_SWWKNAME = 'Bin Cleaning' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE6 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '06' ; 
		SET V_SWWKNAME = '전기(정전)작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE7 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '07' ; 
		SET V_SWWKNAME = '방사선사용작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE8 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '08' ; 
		SET V_SWWKNAME = '고소작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE9 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '09' ; 
		SET V_SWWKNAME = '인양(중장비사용)작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
	END IF ; 
  
	IF ( P_SWWKCODE10 = 'Y' ) THEN 
		 
		SET V_SWWKCODE = '10' ; 
		SET V_SWWKNAME = '굴착작업' ; 
  
		 -- 작업내용 등록 
		CALL PSSCMLIB . PSM_PSM4040_SAFEORDER_WKCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , V_SWWKCODE , V_SWWKNAME , '' , 'Y' , P_SMHISAB ) ; 
  
		IF ( P_SITE = '' OR P_SITE = '1' OR P_SITE = '2' OR P_SITE = '3' OR P_SITE = '4' ) THEN 
  
			 -- 안전작업허가서 굴착 조치요구사항 삭제 
			CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_DEL ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ ) ; 
			 
			 -- 굴착 조치요구사항 등록 
			CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
			P_801_DRCODE , P_801_DRCODENAME , P_801_DRYESSEL , P_801_DRNOSEL , P_801_DRNASEL , 
								P_801_DRSORT , P_801_DRSTAND , P_801_DRDEPTH , P_801_DRSABUN , P_SMHISAB ) ; 
  
			CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
			P_802_DRCODE , P_802_DRCODENAME , P_802_DRYESSEL , P_802_DRNOSEL , P_802_DRNASEL , 
								P_802_DRSORT , P_802_DRSTAND , P_802_DRDEPTH , P_802_DRSABUN , P_SMHISAB ) ; 
  
			CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
			P_803_DRCODE , P_803_DRCODENAME , P_803_DRYESSEL , P_803_DRNOSEL , P_803_DRNASEL , 
								P_803_DRSORT , P_803_DRSTAND , P_803_DRDEPTH , P_803_DRSABUN , P_SMHISAB ) ; 
			 
			CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
			P_804_DRCODE , P_804_DRCODENAME , P_804_DRYESSEL , P_804_DRNOSEL , P_804_DRNASEL , 
								P_804_DRSORT , P_804_DRSTAND , P_804_DRDEPTH , P_804_DRSABUN , P_SMHISAB ) ; 
  
			CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
			P_805_DRCODE , P_805_DRCODENAME , P_805_DRYESSEL , P_805_DRNOSEL , P_805_DRNASEL , 
								P_805_DRSORT , P_805_DRSTAND , P_805_DRDEPTH , P_805_DRSABUN , P_SMHISAB ) ; 
  
		END IF ; 
  
	ELSE 
  
		 -- 안전작업허가서 굴착 조치요구사항 삭제 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_DRCODE_DEL ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ ) ; 
  
	END IF ;	 
  
  
	IF ( P_SITE = '' OR P_SITE = '1' OR P_SITE = '2' OR P_SITE = '3' OR P_SITE = '4' ) THEN 
		 
		 -- 안전작업허가서 조치요구사항 삭제 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_DEL ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_101_SACODE , P_101_SACODENM , P_101_SSPUBSEL , P_101_SSREVSEL , P_101_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_102_SACODE , P_102_SACODENM , P_102_SSPUBSEL , P_102_SSREVSEL , P_102_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_103_SACODE , P_103_SACODENM , P_103_SSPUBSEL , P_103_SSREVSEL , P_103_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_104_SACODE , P_104_SACODENM , P_104_SSPUBSEL , P_104_SSREVSEL , P_104_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_105_SACODE , P_105_SACODENM , P_105_SSPUBSEL , P_105_SSREVSEL , P_105_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_106_SACODE , P_106_SACODENM , P_106_SSPUBSEL , P_106_SSREVSEL , P_106_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_107_SACODE , P_107_SACODENM , P_107_SSPUBSEL , P_107_SSREVSEL , P_107_SSFIXSEL , 
							P_SMHISAB ) ; 
							 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_108_SACODE , P_108_SACODENM , P_108_SSPUBSEL , P_108_SSREVSEL , P_108_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_109_SACODE , P_109_SACODENM , P_109_SSPUBSEL , P_109_SSREVSEL , P_109_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_110_SACODE , P_110_SACODENM , P_110_SSPUBSEL , P_110_SSREVSEL , P_110_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_111_SACODE , P_111_SACODENM , P_111_SSPUBSEL , P_111_SSREVSEL , P_111_SSFIXSEL , 
							P_SMHISAB ) ; 
  
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_112_SACODE , P_112_SACODENM , P_112_SSPUBSEL , P_112_SSREVSEL , P_112_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_113_SACODE , P_113_SACODENM , P_113_SSPUBSEL , P_113_SSREVSEL , P_113_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_114_SACODE , P_114_SACODENM , P_114_SSPUBSEL , P_114_SSREVSEL , P_114_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_115_SACODE , P_115_SACODENM , P_115_SSPUBSEL , P_115_SSREVSEL , P_115_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_116_SACODE , P_116_SACODENM , P_116_SSPUBSEL , P_116_SSREVSEL , P_116_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_201_SACODE , P_201_SACODENM , P_201_SSPUBSEL , P_201_SSREVSEL , P_201_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_202_SACODE , P_202_SACODENM , P_202_SSPUBSEL , P_202_SSREVSEL , P_202_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_203_SACODE , P_203_SACODENM , P_203_SSPUBSEL , P_203_SSREVSEL , P_203_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_204_SACODE , P_204_SACODENM , P_204_SSPUBSEL , P_204_SSREVSEL , P_204_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_205_SACODE , P_205_SACODENM , P_205_SSPUBSEL , P_205_SSREVSEL , P_205_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_206_SACODE , P_206_SACODENM , P_206_SSPUBSEL , P_206_SSREVSEL , P_206_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_207_SACODE , P_207_SACODENM , P_207_SSPUBSEL , P_207_SSREVSEL , P_207_SSFIXSEL , 
							P_SMHISAB ) ; 
							 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_208_SACODE , P_208_SACODENM , P_208_SSPUBSEL , P_208_SSREVSEL , P_208_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_209_SACODE , P_209_SACODENM , P_209_SSPUBSEL , P_209_SSREVSEL , P_209_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_210_SACODE , P_210_SACODENM , P_210_SSPUBSEL , P_210_SSREVSEL , P_210_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_211_SACODE , P_211_SACODENM , P_211_SSPUBSEL , P_211_SSREVSEL , P_211_SSFIXSEL , 
							P_SMHISAB ) ; 
  
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_212_SACODE , P_212_SACODENM , P_212_SSPUBSEL , P_212_SSREVSEL , P_212_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_213_SACODE , P_213_SACODENM , P_213_SSPUBSEL , P_213_SSREVSEL , P_213_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_214_SACODE , P_214_SACODENM , P_214_SSPUBSEL , P_214_SSREVSEL , P_214_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_215_SACODE , P_215_SACODENM , P_215_SSPUBSEL , P_215_SSREVSEL , P_215_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_216_SACODE , P_216_SACODENM , P_216_SSPUBSEL , P_216_SSREVSEL , P_216_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_217_SACODE , P_217_SACODENM , P_217_SSPUBSEL , P_217_SSREVSEL , P_217_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_218_SACODE , P_218_SACODENM , P_218_SSPUBSEL , P_218_SSREVSEL , P_218_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_301_SACODE , P_301_SACODENM , P_301_SSPUBSEL , P_301_SSREVSEL , P_301_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_302_SACODE , P_302_SACODENM , P_302_SSPUBSEL , P_302_SSREVSEL , P_302_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_303_SACODE , P_303_SACODENM , P_303_SSPUBSEL , P_303_SSREVSEL , P_303_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_304_SACODE , P_304_SACODENM , P_304_SSPUBSEL , P_304_SSREVSEL , P_304_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_305_SACODE , P_305_SACODENM , P_305_SSPUBSEL , P_305_SSREVSEL , P_305_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_306_SACODE , P_306_SACODENM , P_306_SSPUBSEL , P_306_SSREVSEL , P_306_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_307_SACODE , P_307_SACODENM , P_307_SSPUBSEL , P_307_SSREVSEL , P_307_SSFIXSEL , 
							P_SMHISAB ) ; 
							 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_308_SACODE , P_308_SACODENM , P_308_SSPUBSEL , P_308_SSREVSEL , P_308_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_309_SACODE , P_309_SACODENM , P_309_SSPUBSEL , P_309_SSREVSEL , P_309_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_310_SACODE , P_310_SACODENM , P_310_SSPUBSEL , P_310_SSREVSEL , P_310_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_311_SACODE , P_311_SACODENM , P_311_SSPUBSEL , P_311_SSREVSEL , P_311_SSFIXSEL , 
							P_SMHISAB ) ; 
  
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_312_SACODE , P_312_SACODENM , P_312_SSPUBSEL , P_312_SSREVSEL , P_312_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_313_SACODE , P_313_SACODENM , P_313_SSPUBSEL , P_313_SSREVSEL , P_313_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_314_SACODE , P_314_SACODENM , P_314_SSPUBSEL , P_314_SSREVSEL , P_314_SSFIXSEL , 
							P_SMHISAB ) ; 
	 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_401_SACODE , P_401_SACODENM , P_401_SSPUBSEL , P_401_SSREVSEL , P_401_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_402_SACODE , P_402_SACODENM , P_402_SSPUBSEL , P_402_SSREVSEL , P_402_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_403_SACODE , P_403_SACODENM , P_403_SSPUBSEL , P_403_SSREVSEL , P_403_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_404_SACODE , P_404_SACODENM , P_404_SSPUBSEL , P_404_SSREVSEL , P_404_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_405_SACODE , P_405_SACODENM , P_405_SSPUBSEL , P_405_SSREVSEL , P_405_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_406_SACODE , P_406_SACODENM , P_406_SSPUBSEL , P_406_SSREVSEL , P_406_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_407_SACODE , P_407_SACODENM , P_407_SSPUBSEL , P_407_SSREVSEL , P_407_SSFIXSEL , 
							P_SMHISAB ) ; 
							 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_408_SACODE , P_408_SACODENM , P_408_SSPUBSEL , P_408_SSREVSEL , P_408_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_409_SACODE , P_409_SACODENM , P_409_SSPUBSEL , P_409_SSREVSEL , P_409_SSFIXSEL , 
							P_SMHISAB ) ; 
	 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_501_SACODE , P_501_SACODENM , P_501_SSPUBSEL , P_501_SSREVSEL , P_501_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_502_SACODE , P_502_SACODENM , P_502_SSPUBSEL , P_502_SSREVSEL , P_502_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_503_SACODE , P_503_SACODENM , P_503_SSPUBSEL , P_503_SSREVSEL , P_503_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_504_SACODE , P_504_SACODENM , P_504_SSPUBSEL , P_504_SSREVSEL , P_504_SSFIXSEL , 
							P_SMHISAB ) ; 
	 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_601_SACODE , P_601_SACODENM , P_601_SSPUBSEL , P_601_SSREVSEL , P_601_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_602_SACODE , P_602_SACODENM , P_602_SSPUBSEL , P_602_SSREVSEL , P_602_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_603_SACODE , P_603_SACODENM , P_603_SSPUBSEL , P_603_SSREVSEL , P_603_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_701_SACODE , P_701_SACODENM , P_701_SSPUBSEL , P_701_SSREVSEL , P_701_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_702_SACODE , P_702_SACODENM , P_702_SSPUBSEL , P_702_SSREVSEL , P_702_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_703_SACODE , P_703_SACODENM , P_703_SSPUBSEL , P_703_SSREVSEL , P_703_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_704_SACODE , P_704_SACODENM , P_704_SSPUBSEL , P_704_SSREVSEL , P_704_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_705_SACODE , P_705_SACODENM , P_705_SSPUBSEL , P_705_SSREVSEL , P_705_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_706_SACODE , P_706_SACODENM , P_706_SSPUBSEL , P_706_SSREVSEL , P_706_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_707_SACODE , P_707_SACODENM , P_707_SSPUBSEL , P_707_SSREVSEL , P_707_SSFIXSEL , 
							P_SMHISAB ) ; 
							 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_708_SACODE , P_708_SACODENM , P_708_SSPUBSEL , P_708_SSREVSEL , P_708_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_901_SACODE , P_901_SACODENM , P_901_SSPUBSEL , P_901_SSREVSEL , P_901_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_902_SACODE , P_902_SACODENM , P_902_SSPUBSEL , P_902_SSREVSEL , P_902_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_903_SACODE , P_903_SACODENM , P_903_SSPUBSEL , P_903_SSREVSEL , P_903_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_904_SACODE , P_904_SACODENM , P_904_SSPUBSEL , P_904_SSREVSEL , P_904_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_905_SACODE , P_905_SACODENM , P_905_SSPUBSEL , P_905_SSREVSEL , P_905_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_906_SACODE , P_906_SACODENM , P_906_SSPUBSEL , P_906_SSREVSEL , P_906_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_907_SACODE , P_907_SACODENM , P_907_SSPUBSEL , P_907_SSREVSEL , P_907_SSFIXSEL , 
							P_SMHISAB ) ; 
							 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_908_SACODE , P_908_SACODENM , P_908_SSPUBSEL , P_908_SSREVSEL , P_908_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_909_SACODE , P_909_SACODENM , P_909_SSPUBSEL , P_909_SSREVSEL , P_909_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_910_SACODE , P_910_SACODENM , P_910_SSPUBSEL , P_910_SSREVSEL , P_910_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_911_SACODE , P_911_SACODENM , P_911_SSPUBSEL , P_911_SSREVSEL , P_911_SSFIXSEL , 
							P_SMHISAB ) ; 
  
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_912_SACODE , P_912_SACODENM , P_912_SSPUBSEL , P_912_SSREVSEL , P_912_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_913_SACODE , P_913_SACODENM , P_913_SSPUBSEL , P_913_SSREVSEL , P_913_SSFIXSEL , 
							P_SMHISAB ) ; 
		 
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_914_SACODE , P_914_SACODENM , P_914_SSPUBSEL , P_914_SSREVSEL , P_914_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_915_SACODE , P_915_SACODENM , P_915_SSPUBSEL , P_915_SSREVSEL , P_915_SSFIXSEL , 
							P_SMHISAB ) ; 
  
		 -- 안전작업허가서 조치요구사항 등록 
		CALL PSSCMLIB . PSM_PSM4041_SAFEORDER_SACODE_SAV ( P_SMWKTEAM , P_SMWKDATE , P_SMWKSEQ , P_SMWKORAPPDATE , P_SMWKORSEQ , 
		P_916_SACODE , P_916_SACODENM , P_916_SSPUBSEL , P_916_SSREVSEL , P_916_SSFIXSEL , 
							P_SMHISAB ) ; 
  
	END IF ; 
  
END P1;