--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_INSPECT_LASTLIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_INSPECT_LASTLIST ( 
	IN P_PECSABUN1 VARCHAR(6))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PEINUM,
		PEISABUN,
		KBHANGL,
		'' AS PEICHKDATE
		FROM
		(
		SELECT
		PECTEAM,
		PECDATE,
		PECSEQ,
		PECWOTEAM,
		PECWODATE,
		PECWOSEQ
		FROM PSSCMLIB.PSM_EXAM_CHECK
		WHERE PECSABUN1 = P_PECSABUN1
		ORDER BY PECDATE DESC, PECSEQ DESC
		fetch first 1 row only
		) AS TABLE1
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_INSPECT 
		ON   PEICTEAM = PECTEAM
		AND PEICDATE = PECDATE
		AND PEICSEQ = PECSEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
		ON   KBSABUN = PEISABUN
		ORDER BY PEINUM
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 