DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_RUN;
  
 
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_RUN ( 
	IN P_PECTEAM VARCHAR(6) , 
	IN P_PECDATE VARCHAR(8) , 
	IN P_PECSEQ NUMERIC(3, 0)  ) 
	DYNAMIC RESULT SETS 2 
	LANGUAGE SQL 

MAIN : BEGIN  -- 시작 
	P1 : BEGIN  -- 마스타 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		 
			SELECT 
			PECTEAM , 
			TYSCMLIB.SF_GB_ORGNAME(PECTEAM, CAST(PECDATE AS VARCHAR(8))) AS PECTEAMNM,
			PECDATE , 
			PECSEQ , 
			PECWOTEAM , 
			PECWODATE , 
			PECWOSEQ , 
			PECTITLE , 
			PECINSDATE , 
			PECSGUBUN , 
			PECSDATE , 
			PECSSEQ , 
			PECRDATE , 
			PECRSEQ , 
			PECTANKNO , 
			PECFAULTNM , 
			PECIMPROVE , 
			PECJKCD1 , 
			PECJKCDNM1 , 
			PECNAME1 , 
			PECSABUN1 , 
			PECDATE1 , 
			PECTIME1 , 
			PECCOMMENT1 , 
			PECJKCD2 , 
			PECJKCDNM2 , 
			PECNAME2 , 
			PECSABUN2 , 
			PECDATE2 , 
			PECTIME2 , 
			PECCOMMENT2 , 
			PECJKCD3 , 
			PECJKCDNM3 , 
			PECNAME3 , 
			PECSABUN3 , 
			PECDATE3 , 
			PECTIME3 , 
			PECCOMMENT3 , 
			PECJKCD4 , 
			PECJKCDNM4 , 
			PECNAME4 , 
			PECSABUN4 , 
			PECDATE4 , 
			PECTIME4 , 
			PECCOMMENT4 , 
			PECJKCD5 , 
			PECJKCDNM5 , 
			PECNAME5 , 
			PECSABUN5 , 
			PECDATE5 , 
			PECTIME5 , 
			PECCOMMENT5 , 
			PECJKCD6 , 
			PECJKCDNM6 , 
			PECNAME6 , 
			PECSABUN6 , 
			PECDATE6 , 
			PECTIME6 , 
			PECCOMMENT6 , 
			/* 사인 */ 
			IMG1 . IMGFILENAME AS IMGNAME1 , 
			IMG1 . IMGFILESIZE AS IMGSIZE1 , 
			IMG1 . IMGSIGN AS IMGSIGN1 , 
			IMG2 . IMGFILENAME AS IMGNAME2 , 
			IMG2 . IMGFILESIZE AS IMGSIZE2 , 
			IMG2 . IMGSIGN AS IMGSIGN2 , 
			IMG3 . IMGFILENAME AS IMGNAME3 , 
			IMG3 . IMGFILESIZE AS IMGSIZE3 , 
			IMG3 . IMGSIGN AS IMGSIGN3 , 
			IMG4 . IMGFILENAME AS IMGNAME4 , 
			IMG4 . IMGFILESIZE AS IMGSIZE4 , 
			IMG4 . IMGSIGN AS IMGSIGN4 , 
			IMG5 . IMGFILENAME AS IMGNAME5 , 
			IMG5 . IMGFILESIZE AS IMGSIZE5 , 
			IMG5 . IMGSIGN AS IMGSIGN5 , 
			IMG6 . IMGFILENAME AS IMGNAME6 , 
			IMG6 . IMGFILESIZE AS IMGSIZE6 , 
			IMG6 . IMGSIGN AS IMGSIGN6 ,
			CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_CHECK_DETAIL LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK_CONTENTS ON      PECCGUBUN = PECDGUBUN AND    PECCDATE = PECDDATE AND    PECCSEQ = PECDSEQ AND    
			PECCNUM = PECDNUM WHERE PECDTCTEAM = PECTEAM AND     PECDTCDATE = PECDATE AND     PECDTCSEQ = PECSEQ AND     PECCCHECK = 'Y'  AND     PECDCHECK = '') = 0 
			AND (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_INSPECT WHERE PEICTEAM = PECTEAM AND    PEICDATE = PECDATE AND    PEICSEQ = PECSEQ AND    PEICHKDATE = '') = 0  
			AND (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_REPORT WHERE PERTCTEAM = PECTEAM AND    PERTCDATE = PECDATE AND    PERTCSEQ = PECSEQ) > 0 THEN 'Y' ELSE '' END AS INSPECTGUBUN
			FROM PSSCMLIB . PSM_EXAM_CHECK 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS IMG1 
			ON IMG1 . IMGSABUN = PECSABUN1 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS IMG2 
			ON IMG2 . IMGSABUN = PECSABUN2 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS IMG3 
			ON IMG3 . IMGSABUN = PECSABUN3 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS IMG4 
			ON IMG4 . IMGSABUN = PECSABUN4 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS IMG5 
			ON IMG5 . IMGSABUN = PECSABUN5 
			LEFT JOIN PSSCMLIB . PSM_IMGSIGN AS IMG6 
			ON IMG6 . IMGSABUN = PECSABUN6 
			WHERE PECTEAM = P_PECTEAM 
			AND PECDATE = P_PECDATE 
			AND PECSEQ = P_PECSEQ  ; 
	 
		OPEN REFCURSOR ; 
	END P1 ; 

	P2 : BEGIN
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
			SELECT
				PEINUM,
				PEISABUN,
				CASE WHEN PEICHKDATE <> '' THEN SUBSTR(PEICHKDATE,1,4) || '-' || SUBSTR(PEICHKDATE,5,2) || '-' || SUBSTR(PEICHKDATE,7,2) ELSE '' END AS PEICHKDATE,
				KBMAILID,
				KBHANGL
				FROM PSSCMLIB.PSM_EXAM_INSPECT
				LEFT OUTER JOIN TYSCMLIB.INKIBNMF
				ON  KBSABUN = PEISABUN
				WHERE PEICTEAM = P_PECTEAM 
				AND    PEICDATE = P_PECDATE
				AND    PEICSEQ  = P_PECSEQ
				ORDER BY PEINUM ;

		OPEN REFCURSOR2 ; 
	END P2 ;
END  ; 
  