  
DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_PRT;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_PRT ( 
	IN P_PECTEAM VARCHAR(6) , 
	IN P_PECDATE VARCHAR(8) , 
	IN P_PECSEQ NUMERIC(3, 0)
	) 
	DYNAMIC RESULT SETS 3
	LANGUAGE SQL 
	
MAIN : BEGIN  -- 시작 
	P1 : BEGIN  -- 마스타 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT
			PECTITLE,
			CASE WHEN PECINSDATE <> '' THEN SUBSTR(PECINSDATE,1,4) || '-' || SUBSTR(PECINSDATE,5,2) || '-' || SUBSTR(PECINSDATE,7,2) ELSE '' END PECINSDATE,
			PECDDESC,
			PECLEVEL,
			PECCCHECK,
			CASE WHEN PECDCHECK = 'G' THEN 'Y' ELSE '' END AS  PECDCHECK_G,
			CASE WHEN PECDCHECK = 'F' THEN 'Y' ELSE '' END AS  PECDCHECK_F,
			CASE WHEN PECDCHECK = 'N' THEN 'Y' ELSE '' END AS  PECDCHECK_N
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK_DETAIL
			ON    PECDTCTEAM = PECTEAM
			AND  PECDTCDATE = PECDATE
			AND  PECDTCSEQ   = PECSEQ
			AND  PECDGUBUN  = PECSGUBUN
			AND  PECDDATE   = PECSDATE
			AND  PECDSEQ    = PECSSEQ
			LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
			ON    PECCGUBUN = PECDGUBUN
			AND  PECCDATE = PECDDATE
			AND  PECCSEQ = PECDSEQ
			AND  PECCNUM = PECDNUM
			WHERE PECTEAM = P_PECTEAM
			AND    PECDATE = P_PECDATE
			AND    PECSEQ = P_PECSEQ
			ORDER BY PECDNUM ; 
  
		OPEN REFCURSOR ; 
	END P1 ; 

	P2 : BEGIN  -- 결재정보 
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR 
			 
			WITH MAST AS
			(
			   SELECT
			   CAST(P_PECTEAM AS VARCHAR(6)) AS TEAM,
			   CAST(P_PECDATE AS VARCHAR(8)) AS DATE,
			   CAST(P_PECSEQ AS VARCHAR(3)) AS SEQ
			   FROM SYSIBM.SYSDUMMY1
			),
			TABLE1 AS
			(
			SELECT
			6 AS NUM,
			PECJKCD6 AS PECJKCD,
			PECJKCDNM6 AS PECJKCDNM,
			PECNAME6 AS PECNAME,
			PECSABUN6 AS PECSABUN,
			PECDATE6 AS PECDATE,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN6 
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN6 
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN6 
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN 
			*/
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN MAST
			ON  1 = 1
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PECSABUN6
			*/
			WHERE PECTEAM = TEAM
			AND    PECDATE = DATE
			AND    PECSEQ = SEQ

			UNION ALL

			SELECT
			5 AS NUM,
			PECJKCD5 AS PECJKCD,
			PECJKCDNM5 AS PECJKCDNM,
			PECNAME5 AS PECNAME,
			PECSABUN5 AS PECSABUN,
			PECDATE5 AS PECDATE,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN5 
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN5
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN5
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN 
			*/
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN MAST
			ON  1 = 1
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PECSABUN5
			*/
			WHERE PECTEAM = TEAM
			AND    PECDATE = DATE
			AND    PECSEQ = SEQ

			UNION ALL

			SELECT
			4 AS NUM,
			PECJKCD4 AS PECJKCD,
			PECJKCDNM4 AS PECJKCDNM,
			PECNAME4 AS PECNAME,
			PECSABUN4 AS PECSABUN,
			PECDATE4 AS PECDATE,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN4
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN4
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN4
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN 
			*/
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN MAST
			ON  1 = 1
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PECSABUN4
			*/
			WHERE PECTEAM = TEAM
			AND    PECDATE = DATE
			AND    PECSEQ = SEQ

			UNION ALL

			SELECT
			3 AS NUM,
			PECJKCD3 AS PECJKCD,
			PECJKCDNM3 AS PECJKCDNM,
			PECNAME3 AS PECNAME,
			PECSABUN3 AS PECSABUN,
			PECDATE3 AS PECDATE,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN3
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN3 
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN3 
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN 
			*/
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN MAST
			ON  1 = 1
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PECSABUN3
			*/
			WHERE PECTEAM = TEAM
			AND    PECDATE = DATE
			AND    PECSEQ = SEQ

			UNION ALL

			SELECT
			2 AS NUM,
			PECJKCD2 AS PECJKCD,
			PECJKCDNM2 AS PECJKCDNM,
			PECNAME2 AS PECNAME,
			PECSABUN2 AS PECSABUN,
			PECDATE2 AS PECDATE,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN2 
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN2 
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN2 
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN 
			*/
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN MAST
			ON  1 = 1
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PECSABUN2
			*/
			WHERE PECTEAM = TEAM
			AND    PECDATE = DATE
			AND    PECSEQ = SEQ

			UNION ALL

			SELECT
			1 AS NUM,
			PECJKCD1 AS PECJKCD,
			PECJKCDNM1 AS PECJKCDNM,
			PECNAME1 AS PECNAME,
			PECSABUN1 AS PECSABUN,
			PECDATE1 AS PECDATE,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN1 
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN1 
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PECSABUN1 
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN
			*/
			FROM PSSCMLIB.PSM_EXAM_CHECK
			LEFT OUTER JOIN MAST
			ON  1 = 1
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PECSABUN1
			*/
			WHERE PECTEAM = TEAM
			AND    PECDATE = DATE
			AND    PECSEQ = SEQ
			)
			SELECT
			*
			FROM TABLE1
			WHERE PECNAME <> ''
			ORDER BY NUM DESC; 
  
		OPEN REFCURSOR2 ; 
	END P2 ; 

	P3 : BEGIN  -- 점검자 정보
		DECLARE REFCURSOR3 CURSOR WITH RETURN FOR 
			 
			SELECT
			PEISABUN,
			KBHANGL,
			( SELECT 
					FILE_NAME 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PEISABUN 
				) AS IMGNAME , 
				( SELECT 
					FILE_SIZE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PEISABUN 
				) AS IMGSIZE , 
				( SELECT 
					ATTACH_BYTE 
				FROM PSSCMLIB . PSM_CMN_ATTACH 
				WHERE ATTACH_TYPE = 'SG' 
				AND ATTACH_NO = PEISABUN 
				) AS IMGSIGN  
			/*
			IMG . FILE_NAME AS IMGNAME , 
			IMG . FILE_SIZE AS IMGSIZE , 
			IMG . ATTACH_BYTE AS IMGSIGN 
			*/
			FROM PSSCMLIB.PSM_EXAM_INSPECT
			LEFT OUTER JOIN TYSCMLIB.INKIBNMF
			ON   KBSABUN = PEISABUN
			/*
			LEFT OUTER JOIN PSSCMLIB.PSM_CMN_ATTACH AS IMG
			ON    IMG.ATTACH_TYPE = 'SG'
			AND   IMG.ATTACH_NO   = PEISABUN
			*/
			WHERE PEICTEAM = P_PECTEAM
			AND    PEICDATE = P_PECDATE
			AND    PEICSEQ = P_PECSEQ
			ORDER BY PEINUM; 
  
		OPEN REFCURSOR3 ; 
	END P3 ; 

END;