--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_FIELDCHECK;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_FIELDCHECK ( 
	IN P_WOORSABUN VARCHAR(6),
	IN P_DATE      VARCHAR(8),
	IN P_WOSOTEAM  VARCHAR(6),
	IN P_WORETEAM  VARCHAR(6),
	IN P_WOPONUM1  VARCHAR(12),
	IN P_WOPONUM2  VARCHAR(12),
	IN P_WOPONUM3  VARCHAR(12),
	IN P_WOPONUM4  VARCHAR(12),
	IN P_WOPONUM5  VARCHAR(12),
	IN P_FXCCODE1  VARCHAR(10),
	IN P_FXCCODE2  VARCHAR(10),
	IN P_FXCCODE3  VARCHAR(10),
	IN P_FXCCODE4  VARCHAR(10),
	IN P_FXCCODE5  VARCHAR(10),
	IN P_L3CODE1   VARCHAR(9),
	IN P_L3CODE2   VARCHAR(9),
	IN P_L3CODE3   VARCHAR(9),
	IN P_L3CODE4   VARCHAR(9),
	IN P_L3CODE5   VARCHAR(9)) 

	DYNAMIC RESULT SETS 1 

P1 : BEGIN
	
	MAIN : BEGIN  -- 실행부
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			/* 요청자 */
			SELECT
			'1' AS GUBUN,
			KBHANGL AS DATA
			FROM TYSCMLIB.INKIBNMF
			WHERE KBSABUN = P_WOORSABUN
			AND   KBBALCD NOT IN ( '900', '560')

			UNION ALL

			/* 요청팀 */
			SELECT
			'2' AS GUBUN,
			ORG_NM AS DATA
			FROM   TYSCMLIB.INTORG101
			WHERE ENTER_CD = 'TY' 
			AND   P_DATE BETWEEN SDATE AND (CASE WHEN EDATE = '' THEN '99991231'  ELSE  COALESCE(EDATE, '99991231') END)
			AND   ORG_CD = P_WOSOTEAM

			UNION ALL

			/* 수신팀 */
			SELECT
			'3' AS GUBUN,
			ORG_NM AS DATA
			FROM   TYSCMLIB.INTORG101
			WHERE ENTER_CD = 'TY' 
			AND   P_DATE BETWEEN SDATE AND (CASE WHEN EDATE = '' THEN '99991231'  ELSE  COALESCE(EDATE, '99991231') END)
			AND   ORG_CD = P_WORETEAM

			UNION ALL

			/* 발주번호1 */
			SELECT
			'4' AS GUBUN,
			POM1000 AS DATA
			FROM TYSCMLIB.MRPPOMF
			WHERE POM1000||POM1010||POM1020||DIGITS(POM1030) = P_WOPONUM1

			UNION ALL

			/* 발주번호2 */
			SELECT
			'5' AS GUBUN,
			POM1000 AS DATA
			FROM TYSCMLIB.MRPPOMF
			WHERE POM1000||POM1010||POM1020||DIGITS(POM1030) = P_WOPONUM2

			UNION ALL

			/* 발주번호3 */
			SELECT
			'6' AS GUBUN,
			POM1000 AS DATA
			FROM TYSCMLIB.MRPPOMF
			WHERE POM1000||POM1010||POM1020||DIGITS(POM1030) = P_WOPONUM3

			UNION ALL

			/* 발주번호4 */
			SELECT
			'7' AS GUBUN,
			POM1000 AS DATA
			FROM TYSCMLIB.MRPPOMF
			WHERE POM1000||POM1010||POM1020||DIGITS(POM1030) = P_WOPONUM4

			UNION ALL

			/* 발주번호5 */
			SELECT
			'8' AS GUBUN,
			POM1000 AS DATA
			FROM TYSCMLIB.MRPPOMF
			WHERE POM1000||POM1010||POM1020||DIGITS(POM1030) = P_WOPONUM5

			UNION ALL

			/* 설비코드1 */
			SELECT
			'9' AS GUBUN,
			FXC3DESC AS DATA
			FROM TYSCMLIB.ACFIXCLASS3 C
			WHERE FXC3BCODE IN('20', '30', '40', '90')
			AND   FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) = P_FXCCODE1

			UNION ALL

			/* 설비코드2 */
			SELECT
			'10' AS GUBUN,
			FXC3DESC AS DATA
			FROM TYSCMLIB.ACFIXCLASS3 C
			WHERE FXC3BCODE IN('20', '30', '40', '90')
			AND   FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) = P_FXCCODE2

			UNION ALL

			/* 설비코드3 */
			SELECT
			'11' AS GUBUN,
			FXC3DESC AS DATA
			FROM TYSCMLIB.ACFIXCLASS3 C
			WHERE FXC3BCODE IN('20', '30', '40', '90')
			AND   FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) = P_FXCCODE3

			UNION ALL

			/* 설비코드4 */
			SELECT
			'12' AS GUBUN,
			FXC3DESC AS DATA
			FROM TYSCMLIB.ACFIXCLASS3 C
			WHERE FXC3BCODE IN('20', '30', '40', '90')
			AND   FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) = P_FXCCODE4

			UNION ALL

			/* 설비코드5 */
			SELECT
			'13' AS GUBUN,
			FXC3DESC AS DATA
			FROM TYSCMLIB.ACFIXCLASS3 C
			WHERE FXC3BCODE IN('20', '30', '40', '90')
			AND   FXC3SAUP||FXC3BCODE||DIGITS(FXC3MCODE)||DIGITS(FXC3SCODE) = P_FXCCODE5

			UNION ALL

			/* 구역코드1 */
			SELECT
			'14' AS GUBUN,
			L3NAME AS DATA
			FROM PSSCMLIB.PSM_LOCATION_CLASS3
			WHERE L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) = P_L3CODE1

			UNION ALL

			/* 구역코드2 */
			SELECT
			'15' AS GUBUN,
			L3NAME AS DATA
			FROM PSSCMLIB.PSM_LOCATION_CLASS3
			WHERE L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) = P_L3CODE2

			UNION ALL

			/* 구역코드3 */
			SELECT
			'16' AS GUBUN,
			L3NAME AS DATA
			FROM PSSCMLIB.PSM_LOCATION_CLASS3
			WHERE L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) = P_L3CODE3

			UNION ALL

			/* 구역코드4 */
			SELECT
			'17' AS GUBUN,
			L3NAME AS DATA
			FROM PSSCMLIB.PSM_LOCATION_CLASS3
			WHERE L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) = P_L3CODE4

			UNION ALL

			/* 구역코드5 */
			SELECT
			'18' AS GUBUN,
			L3NAME AS DATA
			FROM PSSCMLIB.PSM_LOCATION_CLASS3
			WHERE L3SAUP||L3BCODE||DIGITS(L3MCODE)||DIGITS(L3SCODE) = P_L3CODE5;

		OPEN REFCURSOR;

	END MAIN;

END P1;

CALL PSSCMLIB.PSM_PSM4011_FIELDCHECK('0311-M', '20230719', 'A20000', 'A20000', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');