DROP PROCEDURE PSSCMLIB.PSM_PSM4040_JSA_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_JSA_LIST ( 
	IN P_JSLWKGUBN VARCHAR(1),
	IN P_JSLWKTEAM VARCHAR(6),
	IN P_JSLWKDATE VARCHAR(8),
	IN P_JSLWKSEQ  NUMERIC(3,0))

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- Ω√¿€
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
			'<img src="/Resources/Images/icon_file.gif" style="cursor:pointer" onclick="GridJsaCopy(''' || JSLWKGUBN || '-' || JSLWKTEAM || '-' || JSLWKDATE ||'-'||DIGITS(JSLWKSEQ) ||'-'||JSLDATE ||'-'|| DIGITS(JSLSEQ) ||''');" />' AS JSACOPY,
			'<img src="/Resources/Images/btn_print.gif" style="cursor:pointer"
			  onclick="GridJsaPrt(''' || JSLWKGUBN || '-' || JSLWKTEAM || '-' || JSLWKDATE || '-' ||DIGITS(JSLWKSEQ) || '-' ||
			                             JSLDATE || '-' || DIGITS(JSLSEQ) || '-' || JSMBLASS|| '-' || JSMMLASS|| '-' || JSMSLASS|| '-' || DIGITS(JSMSEQ) ||''');" />' AS JSAPRT,
			JSLDATE,
			JSLSEQ,
			JSLWRSABUN,
			KBHANGL AS JSLWRSABUNNM,
			JSMBLASS,
			J1NAME AS JBCODE,
			JSMMLASS,
			J2NAME AS JMCODE,
			JSMSLASS,
			J3NAME AS JSCODE,
			JSMSEQ       ,
			JSMWKNAME    ,
			JSMSECTIONNUM,
			H1CODE.CDDESC1 AS H1CODE,
			DIGITS(JSMMSDSCODE)||'-'||DIGITS(JSMMSDSSEQ) AS JSMMSDS,
			JSLWKGUBN,
			JSLWKTEAM,
			JSLWKDATE,
			JSLWKSEQ
		FROM PSSCMLIB.PSM_JSALOG_MASTER
		INNER JOIN PSSCMLIB.PSM_JSACHANGE_MASTER
		ON   JSLWKGUBN = JSMWKGUBN
		AND  JSLWKTEAM = JSMPOTEAM
		AND  JSLWKDATE = JSMPODATE
		AND  JSLWKSEQ  = JSMPOSEQ
		AND  JSLDATE   = JSMDATE
		AND  JSLSEQ    = JSMMSEQ
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF
			ON  KBSABUN = JSLWRSABUN
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
		ON    JSMBLASS = J1CODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2
		ON    JSMBLASS = J2BCODE
		AND   JSMMLASS = J2MCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3
		ON    JSMBLASS = J3BCODE
		AND   JSMMLASS = J3MCODE
		AND   JSMSLASS = J3SCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF AS H1CODE
		ON            'H1' = H1CODE.CDINDEX
		AND  JSMSECTIONNUM = H1CODE.CDCODE
		WHERE JSLWKGUBN = P_JSLWKGUBN
		AND   JSLWKTEAM = P_JSLWKTEAM
		AND   JSLWKDATE = P_JSLWKDATE
		AND   JSLWKSEQ  = P_JSLWKSEQ
		ORDER BY JSLDATE DESC, JSLSEQ DESC;

	OPEN REFCURSOR;

END; 