--DROP PROCEDURE PSSCMLIB.PSM_PSM4040_JSALOG_COPY;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_JSALOG_COPY
(
	IN P_COPYDATE VARCHAR(8),
	IN P_COPYSEQ  NUMERIC(3,0),
	IN P_SABUN    VARCHAR(6),
	IN P_WKGUBN   VARCHAR(1),
	IN P_WKTEAM   VARCHAR(6),
	IN P_WKDATE   VARCHAR(8),
	IN P_WKSEQ    NUMERIC(3,0),
	IN P_DATE     VARCHAR(8),
	IN P_SEQ      NUMERIC(3,0)

)

LANGUAGE SQL

P1: BEGIN

	DELETE FROM PSSCMLIB.PSM_JSALOG_MASTER
	WHERE  JSLWKGUBN = P_WKGUBN
	  AND  JSLWKTEAM = P_WKTEAM
	  AND  JSLWKDATE = P_WKDATE
	  AND  JSLWKSEQ  = P_WKSEQ
	  AND  JSLDATE   = P_COPYDATE
	  AND  JSLSEQ    = P_COPYSEQ;

	INSERT INTO PSSCMLIB.PSM_JSALOG_MASTER
	SELECT
		JSLWKGUBN,
		JSLWKTEAM,
		JSLWKDATE,
		JSLWKSEQ,
		CAST(P_COPYDATE AS VARCHAR(8)) AS JSLDATE,
		CAST(P_COPYSEQ  AS NUMERIC(3,0)) AS JSLSEQ,
		CAST(P_SABUN   AS VARCHAR(6)) AS JSLWRSABUN,
		replace( CHAR(CURRENT_DATE),'-','') as  JSLENDDATE,
		replace( CHAR(CURRENT_TIME),'.','') as JSLENDTIME,
		'A',
		CURRENT_DATE,
		CURRENT_TIME,
		CAST(P_SABUN   AS VARCHAR(6)) AS JSLHISAB
	FROM PSSCMLIB.PSM_JSALOG_MASTER
	WHERE  JSLWKGUBN = P_WKGUBN
	  AND  JSLWKTEAM = P_WKTEAM
	  AND  JSLWKDATE = P_WKDATE
	  AND  JSLWKSEQ  = P_WKSEQ
	  AND  JSLDATE   = P_DATE;



	IF EXISTS( SELECT JSDWKGUBN FROM PSSCMLIB.PSM_JSACHANGE_DETAIL WHERE JSDWKGUBN  = P_WKGUBN
	                                                               AND   JSDPOTEAM  = P_WKTEAM
								       AND   JSDPODATE  = P_WKDATE
								       AND   JSDPOSEQ   = P_WKSEQ
								       AND   JSDDATE    = P_DATE) THEN

		DELETE FROM PSSCMLIB.PSM_JSACHANGE_DETAIL
		WHERE JSDWKGUBN  = P_WKGUBN
		  AND JSDPOTEAM  = P_WKTEAM
		  AND JSDPODATE  = P_WKDATE
		  AND JSDPOSEQ   = P_WKSEQ
		  AND JSDDATE    = P_COPYDATE
		  AND JSDMSEQ    = P_COPYSEQ;

		INSERT INTO  PSSCMLIB.PSM_JSACHANGE_DETAIL
		SELECT   JSDWKGUBN,
			 JSDPOTEAM,
			 JSDPODATE,
			 JSDPOSEQ,
			 CAST(P_COPYDATE AS VARCHAR(8)) AS JSDDATE,
			 CAST(P_COPYSEQ  AS NUMERIC(3,0)) AS JSDMSEQ,
			 JSDBLASS,
			 JSDMLASS,
			 JSDSLASS,
			 JSDSEQ,
			 JSDITEMSEQ,
			 JSDITEMTEXT,
			 JSDTOOLTEXT,
			 'A',
			 CURRENT_DATE,
			 CURRENT_TIME,
			 CAST(P_SABUN AS VARCHAR(6)) AS JSDHISAB
		FROM PSSCMLIB.PSM_JSACHANGE_DETAIL
		WHERE JSDWKGUBN  = P_WKGUBN
		  AND JSDPOTEAM  = P_WKTEAM
		  AND JSDPODATE  = P_WKDATE
		  AND JSDPOSEQ   = P_WKSEQ
		  AND JSDDATE    = P_DATE;

	END IF;
	
	IF EXISTS( SELECT JSMWKGUBN FROM PSSCMLIB.PSM_JSACHANGE_MASTER WHERE JSMWKGUBN = P_WKGUBN
	                                                               AND   JSMPOTEAM = P_WKTEAM
								       AND   JSMPODATE = P_WKDATE
								       AND   JSMPOSEQ  = P_WKSEQ
								       AND   JSMDATE   = P_DATE) THEN

		DELETE FROM PSSCMLIB.PSM_JSACHANGE_MASTER
		WHERE JSMWKGUBN = P_WKGUBN
		  AND JSMPOTEAM = P_WKTEAM
		  AND JSMPODATE = P_WKDATE
		  AND JSMPOSEQ  = P_WKSEQ
		  AND JSMDATE   = P_COPYDATE
		  AND JSMMSEQ   = P_COPYSEQ;
		
		INSERT INTO  PSSCMLIB.PSM_JSACHANGE_MASTER 
		SELECT 
			JSMWKGUBN,
			JSMPOTEAM,
			JSMPODATE,
			JSMPOSEQ,
			CAST(P_COPYDATE AS VARCHAR(8)) AS JSMDATE,
			CAST(P_COPYSEQ  AS NUMERIC(3,0)) AS JSMMSEQ,
			JSMBLASS,
			JSMMLASS,
			JSMSLASS,
			JSMSEQ,
			JSMWKNAME,
			JSMSYSTEM,
			JSMWKDATE,
			JSMADDATE,
			JSMADCHASU,
			JSMWKSABUN,
			JSMSANAME,
			JSMSECTIONNUM,
			JSMMSDSCODE,
			JSMMSDSSEQ,
			JSMWKSUMMARY,
			JSMNEEDDATA,
			JSMRISKCASE ,
			JSMSELFNAME1,
			JSMSELFTEXT1,
			JSMSELFNAME2,
			JSMSELFTEXT2,
			JSMSELFNAME3,
			JSMSELFTEXT3,
			JSMSELFNAME4,
			JSMSELFTEXT4,
			JSMSELFNAME5,
			JSMSELFTEXT5,
			JSMSCOMNAME1,
			JSMSCOMTEXT1,
			JSMSCOMNAME2,
			JSMSCOMTEXT2,
			'A',
			CURRENT_DATE,
			CURRENT_TIME,
			CAST(P_SABUN AS VARCHAR(6)) AS JSMHISAB
		FROM  PSSCMLIB.PSM_JSACHANGE_MASTER
		WHERE JSMWKGUBN = P_WKGUBN
		  AND JSMPOTEAM = P_WKTEAM
		  AND JSMPODATE = P_WKDATE
		  AND JSMPOSEQ  = P_WKSEQ
		  AND JSMDATE   = P_DATE;
	
	END IF;

	IF EXISTS( SELECT JSTWKGUBN FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL WHERE JSTWKGUBN = P_WKGUBN
	                                                                  AND   JSTPOTEAM = P_WKTEAM
									  AND   JSTPODATE = P_WKDATE
									  AND   JSTPOSEQ  = P_WKSEQ
									  AND   JSTDATE   = P_DATE) THEN


		DELETE FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
		WHERE JSTWKGUBN = P_WKGUBN
		AND   JSTPOTEAM = P_WKTEAM
		AND   JSTPODATE = P_WKDATE
		AND   JSTPOSEQ  = P_WKSEQ
		AND   JSTDATE   = P_COPYDATE
		AND   JSTMSEQ   = P_COPYSEQ;
		
		INSERT INTO  PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
		SELECT
			JSTWKGUBN  , 
			JSTPOTEAM  , 
			JSTPODATE  , 
			JSTPOSEQ   , 
			CAST(P_COPYDATE  AS VARCHAR(8)) AS JSTDATE,
			CAST(P_COPYSEQ   AS NUMERIC(3,0)) AS JSTMSEQ, 
			JSTBLASS   , 
			JSTMLASS   , 
			JSTSLASS   , 
			JSTSEQ     , 
			JSTINDX    , 
			JSTCODEGUBN, 
			JSTSAFECODE, 
			JSTSAFENAME, 
			'A'    ,  
			CURRENT_DATE,    
			CURRENT_TIME,
			CAST(P_SABUN   AS VARCHAR(6)) AS JSTHISAB
		FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
		WHERE JSTWKGUBN = P_WKGUBN
		AND   JSTPOTEAM = P_WKTEAM
		AND   JSTPODATE = P_WKDATE
		AND   JSTPOSEQ  = P_WKSEQ
		AND   JSTDATE   = P_DATE;

	END IF;

	IF EXISTS(SELECT JSRWKGUBN FROM PSSCMLIB.PSM_JSACHANGE_RISK WHERE JSRWKGUBN = P_WKGUBN
	                                                            AND   JSRPOTEAM = P_WKTEAM
								    AND   JSRPODATE = P_WKDATE
								    AND   JSRPOSEQ  = P_WKSEQ
	 						            AND   JSRDATE   = P_DATE) THEN

		DELETE FROM PSSCMLIB.PSM_JSACHANGE_RISK
		WHERE JSRWKGUBN = P_WKGUBN
		  AND JSRPOTEAM = P_WKTEAM
		  AND JSRPODATE = P_WKDATE
		  AND JSRPOSEQ  = P_WKSEQ
		  AND JSRDATE   = P_COPYDATE
		  AND JSRMSEQ   = P_COPYSEQ;
		
		INSERT INTO PSSCMLIB.PSM_JSACHANGE_RISK
		SELECT   
			JSRWKGUBN   , 
			JSRPOTEAM   , 
			JSRPODATE   , 
			JSRPOSEQ    ,
			CAST(P_COPYDATE  AS VARCHAR(8)) AS JSRDATE,
			CAST(P_COPYSEQ   AS NUMERIC(3,0)) AS JSRMSEQ, 
			JSRBLASS    , 
			JSRMLASS    , 
			JSRSLASS    , 
			JSRSEQ      , 
			JSRITEMSEQ  , 
			JSRSUBSEQ   , 
			JSRRISKTEXT , 
			JSRRISKCNT,
			JSRRISKSOLID,
			JSRRISKDEGREE,
			'A'    ,  
			CURRENT_DATE,    
			CURRENT_TIME,
			CAST(P_SABUN   AS VARCHAR(6)) AS JSRHISAB
		FROM  PSSCMLIB.PSM_JSACHANGE_RISK
		WHERE JSRWKGUBN = P_WKGUBN
		  AND JSRPOTEAM = P_WKTEAM
		  AND JSRPODATE = P_WKDATE
		  AND JSRPOSEQ  = P_WKSEQ
		  AND JSRDATE   = P_DATE;

	END IF;

	
	IF EXISTS(SELECT JSEWKGUBN FROM PSSCMLIB.PSM_JSACHANGE_REFORM WHERE JSEWKGUBN = P_WKGUBN
	                                                              AND   JSEPOTEAM = P_WKTEAM
								      AND   JSEPODATE = P_WKDATE
								      AND   JSEPOSEQ  = P_WKSEQ
								      AND   JSEDATE   = P_DATE) THEN

		DELETE FROM PSSCMLIB.PSM_JSACHANGE_REFORM
		WHERE JSEWKGUBN = P_WKGUBN
		  AND JSEPOTEAM = P_WKTEAM
		  AND JSEPODATE = P_WKDATE
		  AND JSEPOSEQ  = P_WKSEQ
		  AND JSEDATE   = P_COPYDATE
		  AND JSEMSEQ   = P_COPYSEQ;
		
		INSERT INTO  PSSCMLIB.PSM_JSACHANGE_REFORM
		SELECT   
			JSEWKGUBN   , 
			JSEPOTEAM   , 
			JSEPODATE   , 
			JSEPOSEQ    , 
			CAST(P_COPYDATE  AS VARCHAR(8)) AS JSEDATE,
			CAST(P_COPYSEQ   AS NUMERIC(3,0)) AS JSEMSEQ, 
			JSEBLASS    , 
			JSEMLASS    , 
			JSESLASS    , 
			JSESEQ      , 
			JSEITEMSEQ  , 
			JSESUBSEQ   , 
			JSEREFORMTEXT,
			JSEREFORMCNT,
			JSEREFORMSOLID,
			JSEREFORMDEGREE,
			'A'    ,  
			CURRENT_DATE,    
			CURRENT_TIME,
			CAST(P_SABUN   AS VARCHAR(6)) AS JSEHISAB
		FROM PSSCMLIB.PSM_JSACHANGE_REFORM
		WHERE JSEWKGUBN = P_WKGUBN
		  AND JSEPOTEAM = P_WKTEAM
		  AND JSEPODATE = P_WKDATE
		  AND JSEPOSEQ  = P_WKSEQ
		  AND JSEDATE   = P_DATE;

	END IF;

END P1;

CALL PSSCMLIB.PSM_PSM4040_JSALOG_COPY('20230811',33, '0311-M','D', 'A20000','20230327',1,'20230330', 1);