--DROP PROCEDURE PSSCMLIB.PSM_PSM4040_JSACHANGE_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_JSACHANGE_LIST
(
	  IN P_JSMWKGUBN VARCHAR(1),
  	  IN P_JSMPOTEAM VARCHAR(6),
	  IN P_JSMPODATE VARCHAR(8),
	  IN P_JSMPOSEQ  NUMERIC(3,0),
	  IN P_JSMDATE   VARCHAR(8)
)

RESULT SETS 1
LANGUAGE SQL

P1: BEGIN
	
	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
		*
		FROM PSSCMLIB.PSM_JSACHANGE_MASTER
		WHERE JSMWKGUBN = P_JSMWKGUBN
		AND   JSMPOTEAM = P_JSMPOTEAM
		AND   JSMPODATE = P_JSMPODATE
		AND   JSMPOSEQ  = P_JSMPOSEQ
		AND   JSMDATE   = P_JSMDATE;

	OPEN REFCURSOR;		

END P1;