DROP PROCEDURE PSSCMLIB.PSM_PSM4041_GRPID_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_GRPID_LIST (
	IN P_GRPID   VARCHAR(100)) 

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- 시작

	MAIN : BEGIN  -- 실행부
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
		
			SELECT
				ROW_NUMBER() OVER(ORDER BY USRID) AS ROWNO,
				USRID AS KBSABUN,
				KBHANGL,
				KBMAILID
			FROM TYJINFWLIB.ORG_GROUPUSR AS GROUP
			LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
			ON     GROUP.USRID = KIBN.KBSABUN
			WHERE GRPID  IN(SELECT * FROM TABLE(PSSCMLIB.SF_GB_RevColRow(P_GRPID, ',')) AS InTable );
			--WHERE GRPID     = P_GRPID
			AND   KBCOMPANY = '2'
			AND   KBBALCD NOT IN ( '900', '560');

		OPEN REFCURSOR;

	END MAIN;
	
END;


CALL PSSCMLIB.PSM_PSM4041_GRPID_LIST('SAFE_MAG');