--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 14:26:26 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MSAFETOOL_DEL ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MSAFETOOL_DEL ( 
	IN P_JSTWKGUBN   VARCHAR(1),
	IN P_JSTPOTEAM   VARCHAR(6),
	IN P_JSTPODATE   VARCHAR(8),
	IN P_JSTPOSEQ   NUMERIC(3,0),
	IN P_JSTDATE   VARCHAR(8),
	IN P_JSTMSEQ   NUMERIC(3,0),
	IN P_JSTBLASS VARCHAR(2) , 
	IN P_JSTMLASS VARCHAR(2) , 
	IN P_JSTSLASS VARCHAR(3) , 
	IN P_JSTSEQ NUMERIC(3,0) ) 
	LANGUAGE SQL 

	P1 : BEGIN 
	 
  
		DELETE FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
		WHERE JSTWKGUBN   = P_JSTWKGUBN
		AND   JSTPOTEAM   = P_JSTPOTEAM
		AND   JSTPODATE   = P_JSTPODATE
		AND   JSTPOSEQ    = P_JSTPOSEQ
		AND   JSTDATE     = P_JSTDATE
		AND   JSTMSEQ     = P_JSTMSEQ
		AND   JSTBLASS    = P_JSTBLASS
		AND   JSTMLASS    = P_JSTMLASS
		AND   JSTSLASS    = P_JSTSLASS
		AND   JSTSEQ      = P_JSTSEQ ;
  
END P1  ; 
  