--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_APPROVAL_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_APPROVAL_RUN ( 
	IN P_SMWKTEAM VARCHAR(6) , 
	IN P_SMWKDATE VARCHAR(8) , 
	IN P_SMWKSEQ NUMERIC(3, 0) , 
	IN P_SMWKORAPPDATE VARCHAR(8) , 
	IN P_SMWKORSEQ NUMERIC(3, 0) ) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작 
	DECLARE REFCURSOR CURSOR WITH RETURN FOR 
  
		 
		SELECT 
			SMORSABUN , 
			SMORNAME , 
			SMORJKCD , 
			SMORJKCDNM , 
			SMORAPPDATE , 
			SMORAPPTIME , 
			SMGRSABUN , 
			SMGRNAME , 
			SMGRJKCD , 
			SMGRJKCDNM , 
			SMGRAPPDATE , 
			SMGRAPPTIME , 
			SMCOSABUN , 
			SMCONAME , 
			SMCOJKCD , 
			SMCOJKCDNM , 
			SMCOAPPDATE , 
			SMCOAPPTIME , 
			SMSMSABUN , 
			SMSMNAME , 
			SMSMJKCD , 
			SMSMJKCDNM , 
			SMSMAPPDATE , 
			SMSMAPPTIME , 
			SMFSSABUN , 
			SMFSDATE , 
			SMFSTIME , 
			KIBN . KBHANGL , 
			/* 사인 */ 
			(SELECT
				FILE_NAME
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMORSABUN
			) AS ORIMGNAME, 
			(SELECT
				FILE_SIZE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMORSABUN
			) AS ORIMGSIZE, 
			(SELECT
				ATTACH_BYTE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMORSABUN
			) AS ORIMGSIGN,

			(SELECT
				FILE_NAME
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMGRSABUN
			) AS GRIMGNAME, 
			(SELECT
				FILE_SIZE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMGRSABUN
			) AS GRIMGSIZE, 
			(SELECT
				ATTACH_BYTE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMGRSABUN
			) AS GRIMGSIGN, 

			(SELECT
				FILE_NAME
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMCOSABUN
			) AS COIMGNAME, 
			(SELECT
				FILE_SIZE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMCOSABUN
			) AS COIMGSIZE, 
			(SELECT
				ATTACH_BYTE
			 FROM PSSCMLIB.PSM_CMN_ATTACH
			 WHERE ATTACH_TYPE = 'SG'
			 AND   ATTACH_NO = SMCOSABUN
			) AS COIMGSIGN
		FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
		LEFT OUTER JOIN TYSCMLIB . INKIBNMF AS KIBN 
		ON '2' = KIBN . KBCOMPANY 
		AND SMSMSABUN = KIBN . KBSABUN 
		WHERE SMWKTEAM = P_SMWKTEAM 
		AND SMWKDATE = P_SMWKDATE 
		AND SMWKSEQ = P_SMWKSEQ 
		AND SMWKORAPPDATE = P_SMWKORAPPDATE 
		AND SMWKORSEQ = P_SMWKORSEQ ; 
	 
	OPEN REFCURSOR;
  
END;