DROP PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MASTER_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4045_JSACHANGE_MASTER_RUN
( 
	IN P_JSMWKGUBN   VARCHAR(1),
	IN P_JSMPOTEAM   VARCHAR(6),
	IN P_JSMPODATE   VARCHAR(8),
	IN P_JSMPOSEQ   NUMERIC(3,0),
	IN P_JSMDATE   VARCHAR(8),
	IN P_JSMMSEQ   NUMERIC(3,0),
	IN P_JSMBLASS   VARCHAR(2),
	IN P_JSMMLASS   VARCHAR(2),
	IN P_JSMSLASS   VARCHAR(3),
	IN P_JSMSEQ   NUMERIC(3,0)
)
    RESULT SETS 3
    LANGUAGE SQL
    
MAIN : BEGIN -- Ω√¿€

	P1 : BEGIN
    
		DECLARE REFCURSOR CURSOR WITH RETURN FOR

			SELECT
			JSMBLASS     ,
			J1NAME AS JBCODE,
			JSMMLASS     ,
			J2NAME AS JMCODE,
			JSMSLASS     ,
			J3NAME AS JSCODE,
			JSMSEQ       ,
			JSMWKNAME    ,
			JSMSYSTEM    ,
			JSMWKDATE    ,
			JSMADDATE    ,
			JSMADCHASU   ,
			JSMWKSABUN   ,
			KBHANGL AS JSMWKSABUNNM,
			JSMSECTIONNUM,
			H1CODE.CDDESC1 AS H1CODE,
			JSMMSDSCODE  ,
			JSMMSDSSEQ   ,
			JSMWKSUMMARY ,
			JSMNEEDDATA  ,
			JSMRISKCASE  ,
			JSMSELFNAME1 ,
			JSMSELFTEXT1 ,
			JSMSELFNAME2 ,
			JSMSELFTEXT2 ,
			JSMSELFNAME3 ,
			JSMSELFTEXT3 ,
			JSMSELFNAME4 ,
			JSMSELFTEXT4 ,
			JSMSELFNAME5 ,
			JSMSELFTEXT5 ,
			JSMSCOMNAME1 ,
			JSMSCOMTEXT1 ,
			JSMSCOMNAME2 ,
			JSMSCOMTEXT2 ,
			JSMSANAME,
			JSMPODATE,
			JSMWKGUBN,
			JSMPOTEAM,
			JSMPODATE,
			JSMPOSEQ,
			JSMDATE,
			JSMMSEQ
			FROM PSSCMLIB.PSM_JSACHANGE_MASTER
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
			ON    JSMBLASS = J1CODE
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2
			ON    JSMBLASS = J2BCODE
			AND   JSMMLASS = J2MCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3
			ON    JSMBLASS = J3BCODE
			AND   JSMMLASS = J3MCODE
			AND   JSMSLASS = J3SCODE
			LEFT OUTER JOIN PSSCMLIB.PSM_CODEMF AS H1CODE
			ON             'H1' = H1CODE.CDINDEX
			AND   JSMSECTIONNUM = H1CODE.CDCODE
			LEFT OUTER JOIN TYSCMLIB.INKIBNMF KB
			ON  KB.KBSABUN = JSMWKSABUN
			WHERE JSMWKGUBN = P_JSMWKGUBN
			AND   JSMPOTEAM = P_JSMPOTEAM
			AND   JSMPODATE = P_JSMPODATE
			AND   JSMPOSEQ  = P_JSMPOSEQ
			AND   JSMDATE   = P_JSMDATE
			AND   JSMMSEQ   = P_JSMMSEQ
			AND   JSMBLASS  = P_JSMBLASS
			AND   JSMMLASS  = P_JSMMLASS
			AND   JSMSLASS  = P_JSMSLASS
			AND   JSMSEQ    = P_JSMSEQ;

		OPEN REFCURSOR;

	END P1;

	P2 : BEGIN
    
		DECLARE REFCURSOR2 CURSOR WITH RETURN FOR

			SELECT
			JSTSAFECODE AS CODE,
			JSTSAFENAME AS NAME
			FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
			WHERE JSTWKGUBN   = P_JSMWKGUBN
			AND   JSTPOTEAM   = P_JSMPOTEAM
			AND   JSTPODATE   = P_JSMPODATE
			AND   JSTPOSEQ    = P_JSMPOSEQ
			AND   JSTDATE     = P_JSMDATE
			AND   JSTMSEQ     = P_JSMMSEQ
			AND   JSTBLASS    = P_JSMBLASS
			AND   JSTMLASS    = P_JSMMLASS
			AND   JSTSLASS    = P_JSMSLASS
			AND   JSTSEQ      = P_JSMSEQ
			AND   JSTCODEGUBN = '1' ;

		OPEN REFCURSOR2;

	END P2;

	P3 : BEGIN
    
		DECLARE REFCURSOR3 CURSOR WITH RETURN FOR

			SELECT
			JSTSAFECODE AS CODE,
			JSTSAFENAME AS NAME
			FROM PSSCMLIB.PSM_JSACHANGE_MSAFETOOL
			WHERE JSTWKGUBN   = P_JSMWKGUBN
			AND   JSTPOTEAM   = P_JSMPOTEAM
			AND   JSTPODATE   = P_JSMPODATE
			AND   JSTPOSEQ    = P_JSMPOSEQ
			AND   JSTDATE     = P_JSMDATE
			AND   JSTMSEQ     = P_JSMMSEQ
			AND   JSTBLASS    = P_JSMBLASS
			AND   JSTMLASS    = P_JSMMLASS
			AND   JSTSLASS    = P_JSMSLASS
			AND   JSTSEQ      = P_JSMSEQ
			AND   JSTCODEGUBN = '2' ;

		OPEN REFCURSOR3;

	END P3;

END MAIN;

