--DROP PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_CANCEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_CHANGEASK_CANCEL
(
	IN P_CAASKTEAM VARCHAR(6),
	IN P_CAASKDATE VARCHAR(8),
	IN P_CAASKSEQ  NUMERIC(3,0)
)
LANGUAGE SQL

P1: BEGIN

	UPDATE PSSCMLIB.PSM_CHANGEASK_DOC SET
		CAASKDATE1    = '',
		CAASKTIME1    = '',
		CAASKDATE2    = '',
		CAASKTIME2    = '',
		CAASKDATE3    = '',
		CAASKTIME3    = '',
		CAASKDATE4    = '',
		CAASKTIME4    = '',
		CAASKDATE5    = '',
		CAASKTIME5    = '',
		CAASKREDATE1  = '',
		CAASKRETIME1  = '',
		CAASKREDATE2  = '',
		CAASKRETIME2  = '',
		CAASKREDATE3  = '',
		CAASKRETIME3  = '',
		CAASKREDATE4  = '',
		CAASKRETIME4  = '',
		CAASKREDATE5  = '',
		CAASKRETIME5  = ''
	WHERE CAASKTEAM = P_CAASKTEAM
	AND   CAASKDATE = P_CAASKDATE
	AND   CAASKSEQ  = P_CAASKSEQ;

END P1;