--DROP PROCEDURE PSSCMLIB.PSM_PSM4011_BIN_STATUSMF_UPDATE;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4011_BIN_STATUSMF_UPDATE ( 
	IN P_WOLOCATIONCODE1 VARCHAR(10),
	IN P_WOLOCATIONCODE2 VARCHAR(10),
	IN P_WOLOCATIONCODE3 VARCHAR(10),
	IN P_WOLOCATIONCODE4 VARCHAR(10),
	IN P_WOLOCATIONCODE5 VARCHAR(10)
	) 

LANGUAGE SQL 

P1 : BEGIN

	DECLARE V_SYULBI  VARCHAR(10);
	DECLARE V_SILOBIN VARCHAR(10);

	SET V_SYULBI  = '';
	SET V_SILOBIN = '';

	IF ( P_WOLOCATIONCODE1 <> '' ) THEN 

		SET V_SYULBI = P_WOLOCATIONCODE1;

		IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN

			SELECT
			FXC2DESC INTO V_SILOBIN 
			FROM TYSCMLIB . ACFIXCLASS2 
			WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
			AND FXC2SAUP  = SUBSTR ( V_SYULBI , 1 , 1 ) 
			AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
			AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
			AND CHAR ( FXC2MCODE ) = FXC2DESC;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_WOLOCATIONCODE2 <> '' ) THEN 

			SET V_SYULBI = P_WOLOCATIONCODE2;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_WOLOCATIONCODE3 <> '' ) THEN 

			SET V_SYULBI = P_WOLOCATIONCODE3;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_WOLOCATIONCODE4 <> '' ) THEN 

			SET V_SYULBI = P_WOLOCATIONCODE4;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_WOLOCATIONCODE5 <> '' ) THEN 

			SET V_SYULBI = P_WOLOCATIONCODE5;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF (V_SILOBIN <> '') THEN

		UPDATE TYSCMLIB.BIN_STATUSMF SET
			SBINSTATUS = '0'
		WHERE SDATE = ( SELECT MAX(SDATE) FROM TYSCMLIB.BIN_STATUSMF )
			AND TRIM(SBINNO) = TRIM(V_SILOBIN);		

	END IF;  
  
END P1;