--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_DETAIL_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_DETAIL_LIST ( 
	IN P_PECDTCTEAM VARCHAR(6),
	IN P_PECDTCDATE VARCHAR(8),
	IN P_PECDTCSEQ NUMERIC(3,0),
	IN P_PECDGUBUN VARCHAR(1),
	IN P_PECDDATE VARCHAR(8),
	IN P_PECDSEQ NUMERIC(1,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PECDTCTEAM ,
		PECDTCDATE ,
		PECDTCSEQ ,
		PECDGUBUN ,
		PECDDATE ,
		PECDSEQ ,
		PECDNUM , 
		CONT.PECLEVEL,
		CONT.PECCCHECK,
		PECDDESC ,
		CASE WHEN PECDCHECK = 'G' THEN 'Y' ELSE '' END AS PECDCHECK_G,
		CASE WHEN PECDCHECK = 'F' THEN 'Y' ELSE '' END AS PECDCHECK_F,
		CASE WHEN PECDCHECK = 'N' THEN 'Y' ELSE '' END AS PECDCHECK_N
		FROM PSSCMLIB.PSM_EXAM_CHECK_DETAIL 
		LEFT OUTER JOIN PSSCMLIB.PSM_EXAM_CHECK_CONTENTS AS CONT
		ON    CONT.PECCGUBUN = PECDGUBUN
		AND  CONT.PECCDATE = PECDDATE
		AND  CONT.PECCSEQ = PECDSEQ
		AND  CONT.PECCNUM = PECDNUM
		WHERE PECDTCTEAM = P_PECDTCTEAM
		AND   PECDTCDATE = P_PECDTCDATE
		AND   PECDTCSEQ = P_PECDTCSEQ
		AND   PECDGUBUN = P_PECDGUBUN
		AND   PECDDATE = P_PECDDATE
		AND   PECDSEQ = P_PECDSEQ
		ORDER BY PECDNUM
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 