-- DROP PROCEDURE PSSCMLIB.PSM_PSM4020_WORKORDER_CHECK;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4020_WORKORDER_CHECK ( 
	IN P_WOORTEAM  VARCHAR(6),
	IN P_WOORDATE  VARCHAR(8),
	IN P_WOSEQ     NUMERIC(3, 0)) 
DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- Ω√¿€ 

	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT
		*
		FROM PSSCMLIB.PSM_WORKORDER
		WHERE WOORTEAM = P_WOORTEAM
		AND   WOORDATE = P_WOORDATE
		AND   WOSEQ    = P_WOSEQ
		AND   WOCHANGEWKDIV = '2'
		AND   WOAPPSTATUS = 'F'; 
		 
	OPEN REFCURSOR;
  
END;

CALL PSSCMLIB.PSM_PSM4020_WORKORDER_CHECK('A20000','20230925',1);