DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SYSTEM_HISTORY_GET_MAX;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SYSTEM_HISTORY_GET_MAX ( 
	IN P_HISAUP   VARCHAR(1),
	IN P_HIBCODE  VARCHAR(2),
	IN P_HIMCODE  NUMERIC(4,0),
	IN P_HISCODE  NUMERIC(3,0)) 

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- Ω√¿€ 

	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		
		SELECT VALUE(MAX(HISEQ),0) + 1 AS SEQ
		FROM PSSCMLIB.PSM_SYSTEM_HISTORY
		WHERE HISAUP  = P_HISAUP
		AND   HIBCODE = P_HIBCODE
		AND   HIMCODE = P_HIMCODE
		AND   HISCODE = P_HISCODE; 
		 
	OPEN REFCURSOR;
  
END;