DROP PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_DOC_PRT;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_DOC_PRT ( 
	IN P_CRREVTEAM VARCHAR(6) , 
	IN P_CRREVDATE VARCHAR(8) , 
	IN P_CRREVSEQ NUMERIC(3, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- ¸¶½ºÅ¸ 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
			SELECT
			CAASKACYEAR || '-' || DIGITS(CAASKACSEQ) AS CAASKACSEQ,
			CASE WHEN CARECEIPTDATE <> '' THEN SUBSTR(CARECEIPTDATE,1,4) || '.' || SUBSTR(CARECEIPTDATE,5,2) || '.' || SUBSTR(CARECEIPTDATE,7,2) ELSE '' END AS CARECEIPTDATE,
			CRREVCONTENT,
			CRREVDATA,
			REPLACE(CRREVSUMMARY,'<br />', chr(10)) AS CRREVSUMMARY,
			CRREVAPPROVAL,
			CRREVREASION,
			CASE WHEN CRREVAPPDATE <> '' THEN SUBSTR(CRREVAPPDATE,1,4) || '.' || SUBSTR(CRREVAPPDATE,5,2) || '.' || SUBSTR(CRREVAPPDATE,7,2) ELSE '' END AS CRREVAPPDATE,
			CRREVAPPSABUN,
			KBHANGL AS CRREVAPPNAME,
			ATT.FILE_NAME,
			TYSCMLIB.SF_GB_NEWORGID(CRREVSABUN1, 'NAME', CRREVDATE) AS CRREVBUSEO1,
			CRREVJKCDNM1,
			CRREVNAME1,
			TYSCMLIB.SF_GB_NEWORGID(CRREVSABUN2, 'NAME', CRREVDATE) AS CRREVBUSEO2,
			CRREVJKCDNM2,
			CRREVNAME2,
			TYSCMLIB.SF_GB_NEWORGID(CRREVSABUN3, 'NAME', CRREVDATE) AS CRREVBUSEO3,
			CRREVJKCDNM3,
			CRREVNAME3,
			TYSCMLIB.SF_GB_NEWORGID(CRREVSABUN4, 'NAME', CRREVDATE) AS CRREVBUSEO4,
			CRREVJKCDNM4,
			CRREVNAME4,
			TYSCMLIB.SF_GB_NEWORGID(CRREVSABUN5, 'NAME', CRREVDATE) AS CRREVBUSEO5,
			CRREVJKCDNM5,
			CRREVNAME5,
			TYSCMLIB.SF_GB_NEWORGID(CRREVSABUN6, 'NAME', CRREVDATE) AS CRREVBUSEO6,
			CRREVJKCDNM6,
			CRREVNAME6,
			CRREVTIME1,
			CRREVTIME2,
			CRREVTIME3,
			CRREVTIME4,
			CRREVTIME5,
			CRREVTIME6,
			CRREVAPPTIME,
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN1 
			) AS IMGNAME1 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN1 
			) AS IMGSIZE1 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN1 
			) AS IMGSIGN1 , 
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN2 
			) AS IMGNAME2 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN2 
			) AS IMGSIZE2 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN2 
			) AS IMGSIGN2 , 
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN3 
			) AS IMGNAME3 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN3 
			) AS IMGSIZE3 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN3 
			) AS IMGSIGN3 , 
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN4 
			) AS IMGNAME4 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN4 
			) AS IMGSIZE4 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN4 
			) AS IMGSIGN4 , 
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN5 
			) AS IMGNAME5 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN5 
			) AS IMGSIZE5 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN5 
			) AS IMGSIGN5 , 
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN6 
			) AS IMGNAME6 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN6 
			) AS IMGSIZE6 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVSABUN6 
			) AS IMGSIGN6 , 
			( SELECT 
				FILE_NAME 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVAPPSABUN 
			) AS IMGNAME7 , 
			( SELECT 
				FILE_SIZE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVAPPSABUN 
			) AS IMGSIZE7 , 
			( SELECT 
				ATTACH_BYTE 
			FROM PSSCMLIB . PSM_CMN_ATTACH 
			WHERE ATTACH_TYPE = 'SG' 
			AND ATTACH_NO = CRREVAPPSABUN 
			) AS IMGSIGN7 
			/*
			IMG1 . FILE_NAME AS IMGNAME1 , 
			IMG1 . FILE_SIZE AS IMGSIZE1 , 
			IMG1 . ATTACH_BYTE AS IMGSIGN1, 
			IMG2 . FILE_NAME AS IMGNAME2 , 
			IMG2 . FILE_SIZE AS IMGSIZE2 , 
			IMG2 . ATTACH_BYTE AS IMGSIGN2, 
			IMG3 . FILE_NAME AS IMGNAME3 , 
			IMG3 . FILE_SIZE AS IMGSIZE3 , 
			IMG3 . ATTACH_BYTE AS IMGSIGN3, 
			IMG4 . FILE_NAME AS IMGNAME4 , 
			IMG4 . FILE_SIZE AS IMGSIZE4 , 
			IMG4 . ATTACH_BYTE AS IMGSIGN4, 
			IMG5 . FILE_NAME AS IMGNAME5 , 
			IMG5 . FILE_SIZE AS IMGSIZE5 , 
			IMG5 . ATTACH_BYTE AS IMGSIGN5, 
			IMG6 . FILE_NAME AS IMGNAME6 , 
			IMG6 . FILE_SIZE AS IMGSIZE6 , 
			IMG6 . ATTACH_BYTE AS IMGSIGN6, 
			IMG7 . FILE_NAME AS IMGNAME7 , 
			IMG7 . FILE_SIZE AS IMGSIZE7 , 
			IMG7 . ATTACH_BYTE AS IMGSIGN7
			*/
			FROM PSSCMLIB.PSM_CHANGEREV_DOC AS REV
			LEFT OUTER JOIN PSSCMLIB.PSM_CHANGEASK_DOC AS ASK
			ON    ASK.CAASKTEAM = REV.CRASKTEAM
			AND  ASK.CAASKDATE = REV.CRASKDATE
			AND  ASK.CAASKSEQ = REV.CRASKSEQ
			LEFT OUTER JOIN TYSCMLIB.INKIBNMF 
			ON   KBSABUN = CRREVAPPSABUN
			/*
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG1
			ON   IMG1 . ATTACH_TYPE = 'SG' 
			AND IMG1 . ATTACH_NO = CRREVSABUN1 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG2
			ON   IMG2 . ATTACH_TYPE = 'SG' 
			AND IMG2 . ATTACH_NO = CRREVSABUN2 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG3
			ON   IMG3 . ATTACH_TYPE = 'SG' 
			AND IMG3 . ATTACH_NO = CRREVSABUN3 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG4
			ON   IMG4 . ATTACH_TYPE = 'SG' 
			AND IMG4 . ATTACH_NO = CRREVSABUN4 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG5
			ON   IMG5 . ATTACH_TYPE = 'SG' 
			AND IMG5 . ATTACH_NO = CRREVSABUN5 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG6
			ON   IMG6 . ATTACH_TYPE = 'SG' 
			AND IMG6 . ATTACH_NO = CRREVSABUN6 
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH AS IMG7
			ON   IMG7 . ATTACH_TYPE = 'SG' 
			AND IMG7 . ATTACH_NO = CRREVAPPSABUN 
			*/
			LEFT OUTER JOIN PSSCMLIB . PSM_CMN_ATTACH ATT
			ON    ATT. ATTACH_TYPE = 'RE'
			AND  ATT. ATTACH_NO = CRREVTEAM || CRREVDATE || DIGITS(CRREVSEQ)
			WHERE CRREVTEAM = P_CRREVTEAM
			AND    CRREVDATE  = P_CRREVDATE
			AND    CRREVSEQ = P_CRREVSEQ ;
  
		OPEN REFCURSOR ; 
	END P1 ; 
  