--DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_WKCODE_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SAFEORDER_WKCODE_DEL
(
	IN P_SWWKTEAM      VARCHAR(6) , 
	IN P_SWWKDATE      VARCHAR(8) , 
	IN P_SWWKSEQ       NUMERIC(3, 0),
	IN P_SWORAPPDATE   VARCHAR(8) , 
	IN P_SWORSEQ       NUMERIC(3, 0)
)
LANGUAGE SQL

P1: BEGIN

	DELETE FROM PSSCMLIB.PSM_SAFEORDER_WKCODE
	WHERE SWWKTEAM    = P_SWWKTEAM
	AND   SWWKDATE    = P_SWWKDATE
	AND   SWWKSEQ     = P_SWWKSEQ
	AND   SWORAPPDATE = P_SWORAPPDATE
	AND   SWORSEQ     = P_SWORSEQ;

END P1;