DROP PROCEDURE PSSCMLIB.PSM_PSM4021_WORKORDER_RESABUN_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4021_WORKORDER_RESABUN_RUN(
	IN P_WOORTEAM VARCHAR(6),
	IN P_WOORDATE VARCHAR(8),
	IN P_WOSEQ    NUMERIC(3,0)
)
DYNAMIC RESULT SETS 1

P1 : BEGIN  -- Ω√¿€

	DECLARE REFCURSOR CURSOR WITH RETURN FOR

		SELECT
			KBSABUN,
			KBMAILID
		FROM PSSCMLIB.PSM_WorkOrder
		LEFT OUTER JOIN TYSCMLIB.INKIBNMF AS KIBN
		ON      WOAPPRESABUN1 = KIBN.KBSABUN
		WHERE WOORTEAM = P_WOORTEAM
		AND   WOORDATE = P_WOORDATE
		AND   WOSEQ    = P_WOSEQ;

	OPEN REFCURSOR;

END;