DROP PROCEDURE PSSCMLIB.PSM_PSM4040_SAFEORDER_LIST;

CREATE PROCEDURE PSSCMLIB.PSM_PSM4040_SAFEORDER_LIST ( 
	IN P_SMWKTEAM VARCHAR(6),
	IN P_SMWKDATE VARCHAR(8),
	IN P_SMWKSEQ NUMERIC(3,0),
	IN P_SMWKORAPPDATE VARCHAR(8))

DYNAMIC RESULT SETS 1 

P1 : BEGIN  -- 시작
	DECLARE REFCURSOR CURSOR WITH RETURN FOR
		 
		SELECT 
		(CASE WHEN SMFSWKCLOSE = 'Y' THEN '' ELSE '<img src="/Resources/Images/icon_file.gif" style="cursor:pointer" onclick="GridSafeCopy(''' || SMWKTEAM || '-' || SMWKDATE || '-' || DIGITS ( SMWKSEQ ) || '-' || SMWKORAPPDATE || '-' || DIGITS ( SMWKORSEQ ) || ''');" />' END) AS SAFECOPY,
		(CASE WHEN SMCOSABUN <> '' AND SMCOAPPDATE <> '' AND SMCOAPPTIME <> '' THEN '<img src="/Resources/Images/btn_print.gif" style="cursor:pointer" onclick="GridSafeDocClick(''' || SMWKTEAM || '-' || SMWKDATE || '-' || DIGITS ( SMWKSEQ ) || ''');" />'
		      ELSE '' END) AS SAFEDOCPRT,
		(CASE WHEN SMCOSABUN <> '' AND SMCOAPPDATE <> '' AND SMCOAPPTIME <> '' THEN '<img src="/Resources/Images/btn_print.gif" style="cursor:pointer" onclick="GridJSADocClick(''' || SMWKTEAM || '-' || SMWKDATE || '-' || DIGITS ( SMWKSEQ ) || ''');" />'
		      ELSE '' END) AS JSADOCPRT,
		SMWKTEAM || '-' || SMWKDATE || '-' || DIGITS ( SMWKSEQ ) AS APP_NUM,
		SMWKORAPPDATE || '-' || DIGITS ( SMWKORSEQ ) AS OR_NUM,
		( SELECT
		SWWKNAME
		FROM PSSCMLIB . PSM_SAFEORDER_WKCODE
		WHERE SWWKTEAM = SMWKTEAM
		AND SWWKDATE = SMWKDATE
		AND SWWKSEQ = SMWKSEQ
		AND SWORAPPDATE = SMWKORAPPDATE
		AND SWORSEQ = SMWKORSEQ
		FETCH FIRST 1 ROWS ONLY
		) AS SWWKNAME,
		( CASE WHEN SMWKMETHOD = '1' THEN '자체'
		WHEN SMWKMETHOD = '2' THEN '일용'
		ELSE '공사' END ) AS SMWKMETHOD,
		LCT1 . FXC3DESC AS C3NAME1,
		CASE WHEN SMWORKTITLE = '' THEN WOWORKTITLE ELSE SMWORKTITLE END AS SMWORKTITLE ,
		TYSCMLIB . SF_GB_ORGNAME ( SMREVTEAM,SMWKORAPPDATE ) AS SMREVTEAMNM,
		SUBSTR ( SMTADATE1,1,4 ) || '-' || SUBSTR ( SMTADATE1,5,2 ) || '-' || SUBSTR ( SMTADATE1,7,2 ) || '~' || SUBSTR ( SMTADATE2,1,4 ) || '-' || SUBSTR ( SMTADATE2,5,2 ) || '-' || SUBSTR ( SMTADATE2,7,2 ) AS SMTADATE,
		( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMORSABUN ) AS SMORSABUNNM,
		( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMGRSABUN ) AS SMGRSABUNNM,
		( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMCOSABUN ) AS SMCOSABUNNM,
		( SELECT KBHANGL FROM TYSCMLIB . INKIBNMF WHERE KBSABUN = SMSMSABUN ) AS SMSMSABUNNM,
		( CASE WHEN SMORSABUN <> '' AND SMORAPPDATE = '' THEN '작성중' 
		WHEN ( SMCNSABUN <> '' AND SMCNDATE <> '' AND SMCNTIME <> '' ) THEN '작업취소' 
		WHEN ( SMORSABUN <> '' AND SMORAPPDATE <> '' ) AND ( SMCOSABUN <> '' AND SMCOAPPDATE = '' ) THEN '결재진행' 
		WHEN ( SMCOSABUN <> '' AND SMCOAPPDATE <> '' ) AND ( SMFSSABUN = '' AND SMFSDATE = '' ) THEN '허가완료' 
		WHEN ( SMFSSABUN <> '' AND SMFSDATE <> '' AND SMFSWKCLOSE <> 'Y' ) THEN '작업완료' 
		WHEN ( SMFSWKCLOSE = 'Y' ) THEN '공사완료' END ) AS SFSTATUS,
		SMFSWKCLOSE		
		FROM PSSCMLIB . PSM_SAFEORDER_MASTER 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT1 
		ON SMSYSTEMCODE1 = LCT1 . FXC3SAUP || LCT1 . FXC3BCODE || DIGITS ( LCT1 . FXC3MCODE ) || DIGITS ( LCT1 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT2 
		ON SMSYSTEMCODE2 = LCT2 . FXC3SAUP || LCT2 . FXC3BCODE || DIGITS ( LCT2 . FXC3MCODE ) || DIGITS ( LCT2 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT3 
		ON SMSYSTEMCODE3 = LCT3 . FXC3SAUP || LCT3 . FXC3BCODE || DIGITS ( LCT3 . FXC3MCODE ) || DIGITS ( LCT3 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT4 
		ON SMSYSTEMCODE4 = LCT4 . FXC3SAUP || LCT4 . FXC3BCODE || DIGITS ( LCT4 . FXC3MCODE ) || DIGITS ( LCT4 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT5 
		ON SMSYSTEMCODE5 = LCT5 . FXC3SAUP || LCT5 . FXC3BCODE || DIGITS ( LCT5 . FXC3MCODE ) || DIGITS ( LCT5 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT11 
		ON SMCONNCODE11 = LCT11 . FXC3SAUP || LCT11 . FXC3BCODE || DIGITS ( LCT11 . FXC3MCODE ) || DIGITS ( LCT11 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT12 
		ON SMCONNCODE12 = LCT12 . FXC3SAUP || LCT12 . FXC3BCODE || DIGITS ( LCT12 . FXC3MCODE ) || DIGITS ( LCT12 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT21 
		ON SMCONNCODE21 = LCT21 . FXC3SAUP || LCT21 . FXC3BCODE || DIGITS ( LCT21 . FXC3MCODE ) || DIGITS ( LCT21 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT22 
		ON SMCONNCODE22 = LCT22 . FXC3SAUP || LCT22 . FXC3BCODE || DIGITS ( LCT22 . FXC3MCODE ) || DIGITS ( LCT22 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT31 
		ON SMCONNCODE31 = LCT31 . FXC3SAUP || LCT31 . FXC3BCODE || DIGITS ( LCT31 . FXC3MCODE ) || DIGITS ( LCT31 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT32 
		ON SMCONNCODE32 = LCT32 . FXC3SAUP || LCT32 . FXC3BCODE || DIGITS ( LCT32 . FXC3MCODE ) || DIGITS ( LCT32 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT41 
		ON SMCONNCODE41 = LCT41 . FXC3SAUP || LCT41 . FXC3BCODE || DIGITS ( LCT41 . FXC3MCODE ) || DIGITS ( LCT41 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT42 
		ON SMCONNCODE42 = LCT42 . FXC3SAUP || LCT42 . FXC3BCODE || DIGITS ( LCT42 . FXC3MCODE ) || DIGITS ( LCT42 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT51 
		ON SMCONNCODE51 = LCT51 . FXC3SAUP || LCT51 . FXC3BCODE || DIGITS ( LCT51 . FXC3MCODE ) || DIGITS ( LCT51 . FXC3SCODE ) 
		LEFT OUTER JOIN TYSCMLIB . ACFIXCLASS3 AS LCT52 
		ON SMCONNCODE52 = LCT52 . FXC3SAUP || LCT52 . FXC3BCODE || DIGITS ( LCT52 . FXC3MCODE ) || DIGITS ( LCT52 . FXC3SCODE ) 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L1 
		ON L1 . L3SAUP || L1 . L3BCODE || DIGITS ( L1 . L3MCODE ) || DIGITS ( L1 . L3SCODE ) = SMAREACODE1 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L2 
		ON L2 . L3SAUP || L2 . L3BCODE || DIGITS ( L2 . L3MCODE ) || DIGITS ( L2 . L3SCODE ) = SMAREACODE2 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L3 
		ON L3 . L3SAUP || L3 . L3BCODE || DIGITS ( L3 . L3MCODE ) || DIGITS ( L3 . L3SCODE ) = SMAREACODE3 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L4 
		ON L4 . L3SAUP || L4 . L3BCODE || DIGITS ( L4 . L3MCODE ) || DIGITS ( L4 . L3SCODE ) = SMAREACODE4 
		LEFT OUTER JOIN PSSCMLIB . PSM_LOCATION_CLASS3 L5 
		ON L5 . L3SAUP || L5 . L3BCODE || DIGITS ( L5 . L3MCODE ) || DIGITS ( L5 . L3SCODE ) = SMAREACODE5 
		LEFT OUTER JOIN PSSCMLIB . PSM_WORKORDER 
		ON WOORTEAM = SMWKTEAM 
		AND WOORDATE = SMWKDATE 
		AND WOSEQ = SMWKSEQ 
		WHERE SMWKTEAM = P_SMWKTEAM 
		AND SMWKDATE = P_SMWKDATE 
		AND SMWKSEQ = P_SMWKSEQ 
		AND SMWKORAPPDATE LIKE P_SMWKORAPPDATE || '%' 
		ORDER BY SMWKORAPPDATE DESC,SMWKORSEQ DESC;

	OPEN REFCURSOR;

END;