--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4047_JSACHANGE_RISK_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4047_JSACHANGE_RISK_RUN ( 
	IN P_JSRWKGUBN VARCHAR(1),
	IN P_JSRPOTEAM VARCHAR(6),
	IN P_JSRPODATE VARCHAR(8),
	IN P_JSRPOSEQ NUMERIC(3,0),
	IN P_JSRDATE VARCHAR(8),
	IN P_JSRMSEQ NUMERIC(3,0),
	IN P_JSRBLASS VARCHAR(2),
	IN P_JSRMLASS VARCHAR(2),
	IN P_JSRSLASS VARCHAR(3),
	IN P_JSRSEQ NUMERIC(3,0),
	IN P_JSRITEMSEQ NUMERIC(3,0),
	IN P_JSRSUBSEQ NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		JSRSUBSEQ,
		JSRRISKTEXT,
		JSRRISKCNT,
		JSRRISKSOLID,
		JSRRISKDEGREE
		FROM PSSCMLIB.PSM_JSACHANGE_RISK
		WHERE JSRWKGUBN  = P_JSRWKGUBN
		AND   JSRPOTEAM  = P_JSRPOTEAM
		AND   JSRPODATE  = P_JSRPODATE
		AND   JSRPOSEQ   = P_JSRPOSEQ
		AND   JSRDATE    = P_JSRDATE
		AND   JSRMSEQ    = P_JSRMSEQ  
		AND   JSRBLASS   = P_JSRBLASS
		AND   JSRMLASS   = P_JSRMLASS
		AND   JSRSLASS   = P_JSRSLASS
		AND   JSRSEQ     = P_JSRSEQ
		AND   JSRITEMSEQ = P_JSRITEMSEQ
		AND   JSRSUBSEQ  = P_JSRSUBSEQ
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 