DROP PROCEDURE PSSCMLIB.PSM_OutSideConstruct_WKCODE_RUN;

CREATE PROCEDURE PSSCMLIB.PSM_OutSideConstruct_WKCODE_RUN
( 
	P_OSWKDATE    VARCHAR(8),
    P_OSWKSEQ     NUMERIC(3, 0)
)
    RESULT SETS 1
    LANGUAGE SQL
    
P1 : BEGIN -- Ω√¿€
    
	DECLARE REFCURSOR CURSOR WITH RETURN FOR						
		
              SELECT OSWKDATE    ,
					 OSWKSEQ     ,
					 OSWKCODE    ,
					 OSWKNAME    ,
					 OSRISKRATE  ,
					 OSCHECKGN   
				FROM PSSCMLIB.PSM_OutSideConstruct_WKCODE
		        WHERE OSWKDATE = P_OSWKDATE
                  AND OSWKSEQ  = P_OSWKSEQ;

	OPEN REFCURSOR;

END