DROP PROCEDURE PSSCMLIB.PSM_PSM4041_SYULBI_LIST;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4041_SYULBI_LIST (
	IN P_SMSYSTEMCODE1   VARCHAR(10),
	IN P_SMSYSTEMCODE2   VARCHAR(10),
	IN P_SMSYSTEMCODE3   VARCHAR(10),
	IN P_SMSYSTEMCODE4   VARCHAR(10),
	IN P_SMSYSTEMCODE5   VARCHAR(10),
	IN P_SWWKCODE5       VARCHAR(1))

DYNAMIC RESULT SETS 1

P1 : BEGIN  -- 시작

	DECLARE V_SYULBI  VARCHAR(10);
	DECLARE V_SILOBIN VARCHAR(10);

	DECLARE V_SBINSTATUS VARCHAR(1);

	SET V_SYULBI  = '';
	SET V_SILOBIN = '';

	SET V_SBINSTATUS  = '';

	IF ( P_SMSYSTEMCODE1 <> '' ) THEN 

		SET V_SYULBI = P_SMSYSTEMCODE1;

		IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN

			SELECT
			FXC2DESC INTO V_SILOBIN 
			FROM TYSCMLIB . ACFIXCLASS2 
			WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
			AND FXC2SAUP  = SUBSTR ( V_SYULBI , 1 , 1 ) 
			AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
			AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
			AND CHAR ( FXC2MCODE ) = FXC2DESC;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE2 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE2;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE3 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE3;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE4 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE4;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF ( V_SILOBIN = '' ) THEN 

		IF ( P_SMSYSTEMCODE5 <> '' ) THEN 

			SET V_SYULBI = P_SMSYSTEMCODE5;

			IF ( SUBSTR ( V_SYULBI , 1 , 1 ) = 'S' ) THEN 

				SELECT 
				FXC2DESC INTO V_SILOBIN 
				FROM TYSCMLIB . ACFIXCLASS2 
				WHERE FXC2BCODE IN ( '20' , '30' , '40' , '90' ) 
				AND FXC2SAUP = SUBSTR ( V_SYULBI , 1 , 1 ) 
				AND FXC2BCODE = SUBSTR ( V_SYULBI , 2 , 2 ) 
				AND FXC2MCODE = SUBSTR ( V_SYULBI , 4 , 4 ) 
				AND CHAR ( FXC2MCODE ) = FXC2DESC;

			END IF;

		END IF;

	END IF;

	IF (V_SILOBIN <> '') THEN

		SELECT
			SBINSTATUS INTO V_SBINSTATUS
		FROM TYSCMLIB.BIN_STATUSMF 
		WHERE SBINNO = V_SILOBIN
		AND   SDATE = (SELECT MAX(SDATE) FROM TYSCMLIB.BIN_STATUSMF);

		IF (P_SWWKCODE5 = 'Y') THEN

			UPDATE TYSCMLIB.BIN_STATUSMF SET
				SBINSTATUS = '1'
			WHERE SDATE = ( SELECT MAX(SDATE) FROM TYSCMLIB.BIN_STATUSMF )
				AND TRIM(SBINNO) = TRIM(V_SILOBIN);

		ELSE

			IF(V_SBINSTATUS <> '') THEN

				IF (V_SBINSTATUS <> '1' AND V_SBINSTATUS <> '2') THEN

					UPDATE TYSCMLIB.BIN_STATUSMF SET
						SBINSTATUS = '0'
					WHERE SDATE = ( SELECT MAX(SDATE) FROM TYSCMLIB.BIN_STATUSMF )
						AND TRIM(SBINNO) = TRIM(V_SILOBIN);

				END IF;

			END IF;

		END IF;

	END IF;

	LIST3 : BEGIN  -- 실행부

		DECLARE REFCURSOR CURSOR WITH RETURN FOR

			SELECT V_SILOBIN AS SILOBIN
			FROM SYSIBM.SYSDUMMY1;

		OPEN REFCURSOR;
	END LIST3;

END;


CALL PSSCMLIB.PSM_PSM4041_SYULBI_LIST('S300311008','','','','');