DROP PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_DETAIL_DEL;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4073_EXAM_CHECK_DETAIL_DEL ( 
	IN P_PECDTCTEAM  VARCHAR(6),
	IN P_PECDTCDATE  VARCHAR(8),
	IN P_PECDTCSEQ   NUMERIC(3,0),
	IN P_PECDGUBUN   VARCHAR(1),
	IN P_PECDDATE    VARCHAR(8),
	IN P_PECDSEQ     NUMERIC(3,0)) 
	LANGUAGE SQL 
	
	P1 : BEGIN 

	DELETE FROM PSSCMLIB.PSM_EXAM_CHECK_DETAIL
	WHERE PECDTCTEAM = P_PECDTCTEAM
	AND   PECDTCDATE = P_PECDTCDATE
	AND   PECDTCSEQ  = P_PECDTCSEQ
	AND   PECDGUBUN  = P_PECDGUBUN
	AND   PECDDATE   = P_PECDDATE
	AND   PECDSEQ    = P_PECDSEQ ;

  
END P1  ; 
  