--DROP PROCEDURE PSSCMLIB.PSM_OUTSIDECONSTRUCT_DEL;

CREATE PROCEDURE PSSCMLIB.PSM_OUTSIDECONSTRUCT_DEL
(
	P_OSDATE	VARCHAR(8)    ,
	P_OSSEQ		NUMERIC(3, 0) 	
)
	LANGUAGE SQL
P1: BEGIN
	

	DELETE FROM PSSCMLIB.PSM_OUTSIDECONSTRUCT		
		WHERE OSDATE = P_OSDATE 
		  AND OSSEQ  = P_OSSEQ;

END P1