--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_LIST ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4071_EXAM_CHECK_CONTENTS_LIST ( 
	IN P_PECCGUBUN VARCHAR(1),
	IN P_PECCDATE VARCHAR(8),
	IN P_PECCSEQ NUMERIC(1,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	
	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		PECCGUBUN,
		PECCDATE,
		PECCSEQ,
		PECCNUM,
		PECCDESC,
		PECLEVEL,
		PECCCHECK,
		'추가' AS ROWADD,
		'삭제' AS ROWDEL,
		CASE WHEN (SELECT COUNT(*) FROM PSSCMLIB.PSM_EXAM_CHECK WHERE PECSGUBUN = PECCGUBUN AND    PECSDATE = PECCDATE AND    PECSSEQ = PECCSEQ ) > 0 THEN 'Y' ELSE 'N' END AS BTNGUBUN
		FROM PSSCMLIB.PSM_EXAM_CHECK_CONTENTS
		WHERE PECCGUBUN = P_PECCGUBUN
		AND    PECCDATE = P_PECCDATE
		AND    PECCSEQ = P_PECCSEQ
		ORDER BY PECCNUM
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 