DROP PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_DOC_APPROVAL;
CREATE PROCEDURE PSSCMLIB.PSM_PSM4031_CHANGEREV_DOC_APPROVAL ( 
	IN P_CRREVTEAM VARCHAR(6) , 
	IN P_CRREVDATE VARCHAR(8) , 
	IN P_CRREVSEQ NUMERIC(3, 0) , 
	IN P_CRASKTEAM VARCHAR(6) , 
	IN P_CRASKDATE VARCHAR(8) , 
	IN P_CRASKSEQ NUMERIC(3, 0) , 
	IN P_CRWOTEAM VARCHAR(6) , 
	IN P_CRWODATE VARCHAR(8) , 
	IN P_CRWOSEQ NUMERIC(3, 0) , 
	IN P_CRREVCONTENT VARCHAR(1000) , 
	IN P_CRREVDATA VARCHAR(100) , 
	IN P_CRREVSUMMARY VARCHAR(5000) , 
	IN P_CRREVAPPROVAL VARCHAR(1) , 
	IN P_CRREVREASION VARCHAR(200) , 
	IN P_CRREVSABUN1 VARCHAR(6) , 
	IN P_CRREVNAME1 VARCHAR(20) , 
	IN P_CRREVJKCD1 VARCHAR(3) , 
	IN P_CRREVJKCDNM1 VARCHAR(20) , 
	IN P_CRREVCOMMENT1 VARCHAR(200) , 
	IN P_CRREVSABUN2 VARCHAR(6) , 
	IN P_CRREVNAME2 VARCHAR(20) , 
	IN P_CRREVJKCD2 VARCHAR(3) , 
	IN P_CRREVJKCDNM2 VARCHAR(20) , 
	IN P_CRREVCOMMENT2 VARCHAR(200) , 
	IN P_CRREVSABUN3 VARCHAR(6) , 
	IN P_CRREVNAME3 VARCHAR(20) , 
	IN P_CRREVJKCD3 VARCHAR(3) , 
	IN P_CRREVJKCDNM3 VARCHAR(20) , 
	IN P_CRREVCOMMENT3 VARCHAR(200) , 
	IN P_CRREVSABUN4 VARCHAR(6) , 
	IN P_CRREVNAME4 VARCHAR(20) , 
	IN P_CRREVJKCD4 VARCHAR(3) , 
	IN P_CRREVJKCDNM4 VARCHAR(20) , 
	IN P_CRREVCOMMENT4 VARCHAR(200) , 
	IN P_CRREVSABUN5 VARCHAR(6) , 
	IN P_CRREVNAME5 VARCHAR(20) , 
	IN P_CRREVJKCD5 VARCHAR(3) , 
	IN P_CRREVJKCDNM5 VARCHAR(20) , 
	IN P_CRREVCOMMENT5 VARCHAR(200) , 
	IN P_CRREVSABUN6 VARCHAR(6) , 
	IN P_CRREVNAME6 VARCHAR(20) , 
	IN P_CRREVJKCD6 VARCHAR(3) , 
	IN P_CRREVJKCDNM6 VARCHAR(20) , 
	IN P_CRREVCOMMENT6 VARCHAR(200) , 
	IN P_CRREVHISAB VARCHAR(6) , 
	IN P_RESABUN VARCHAR(1000) , 
	IN P_RENAME VARCHAR(2000) , 
	IN P_COUNT NUMERIC(1, 0) , 
	IN P_APPROVAL VARCHAR(1) , 
	IN P_GUBUN VARCHAR(20) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_PSM4031_CHANGEREV_DOC_APPROVAL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
	DECLARE V_CNT NUMERIC ( 3 , 0 ) ; 
  
	DECLARE V_SYULBI VARCHAR ( 10 ) ; 
	DECLARE V_SILOBIN VARCHAR ( 10 ) ; 
  
	DECLARE V_CRREVAPPSABUN VARCHAR ( 6 ) ;  -- 승인사번 
	SET V_CRREVAPPSABUN = '' ;  -- 승인사번 
	SET V_CNT = 0 ; 
  
	SELECT 
		COUNT ( * ) INTO V_CNT 
	FROM PSSCMLIB . PSM_CHANGEREV_DOC 
	WHERE CRREVTEAM = P_CRREVTEAM 
	AND CRREVDATE = P_CRREVDATE 
	AND CRREVSEQ = P_CRREVSEQ ; 
  
	IF ( V_CNT = 0 ) THEN 
  
		INSERT INTO PSSCMLIB . PSM_CHANGEREV_DOC 
		( 
			CRREVTEAM , 
			CRREVDATE , 
			CRREVSEQ , 
			CRASKTEAM , 
			CRASKDATE , 
			CRASKSEQ , 
			CRWOTEAM , 
			CRWODATE , 
			CRWOSEQ , 
			CRREVCONTENT , 
			CRREVDATA , 
			CRREVSUMMARY , 
			CRREVAPPROVAL , 
			CRREVREASION , 
			CRREVSABUN1 , 
			CRREVNAME1 , 
			CRREVJKCD1 , 
			CRREVJKCDNM1 , 
			CRREVCOMMENT1 , 
			CRREVSABUN2 , 
			CRREVNAME2 , 
			CRREVJKCD2 , 
			CRREVJKCDNM2 , 
			CRREVCOMMENT2 , 
			CRREVSABUN3 , 
			CRREVNAME3 , 
			CRREVJKCD3 , 
			CRREVJKCDNM3 , 
			CRREVCOMMENT3 , 
			CRREVSABUN4 , 
			CRREVNAME4 , 
			CRREVJKCD4 , 
			CRREVJKCDNM4 , 
			CRREVCOMMENT4 , 
			CRREVSABUN5 , 
			CRREVNAME5 , 
			CRREVJKCD5 , 
			CRREVJKCDNM5 , 
			CRREVCOMMENT5 , 
			CRREVSABUN6 , 
			CRREVNAME6 , 
			CRREVJKCD6 , 
			CRREVJKCDNM6 , 
			CRREVCOMMENT6 , 
			CRREVHIGB , 
			CRREVHIDAT , 
			CRREVHITIM , 
			CRREVHISAB			 
		) 
		VALUES 
		( 
			P_CRREVTEAM , 
			P_CRREVDATE , 
			P_CRREVSEQ , 
			P_CRASKTEAM , 
			P_CRASKDATE , 
			P_CRASKSEQ , 
			P_CRWOTEAM , 
			P_CRWODATE , 
			P_CRWOSEQ , 
			P_CRREVCONTENT , 
			P_CRREVDATA , 
			P_CRREVSUMMARY , 
			P_CRREVAPPROVAL , 
			P_CRREVREASION , 
			P_CRREVSABUN1 , 
			P_CRREVNAME1 , 
			P_CRREVJKCD1 , 
			P_CRREVJKCDNM1 , 
			P_CRREVCOMMENT1 , 
			P_CRREVSABUN2 , 
			P_CRREVNAME2 , 
			P_CRREVJKCD2 , 
			P_CRREVJKCDNM2 , 
			P_CRREVCOMMENT2 , 
			P_CRREVSABUN3 , 
			P_CRREVNAME3 , 
			P_CRREVJKCD3 , 
			P_CRREVJKCDNM3 , 
			P_CRREVCOMMENT3 , 
			P_CRREVSABUN4 , 
			P_CRREVNAME4 , 
			P_CRREVJKCD4 , 
			P_CRREVJKCDNM4 , 
			P_CRREVCOMMENT4 , 
			P_CRREVSABUN5 , 
			P_CRREVNAME5 , 
			P_CRREVJKCD5 , 
			P_CRREVJKCDNM5 , 
			P_CRREVCOMMENT5 , 
			P_CRREVSABUN6 , 
			P_CRREVNAME6 , 
			P_CRREVJKCD6 , 
			P_CRREVJKCDNM6 , 
			P_CRREVCOMMENT6 , 
			'A' , 
			CURRENT_DATE , 
			CURRENT_TIME , 
			P_CRREVHISAB 
		) ; 
	ELSE 
  
		UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
			CRASKTEAM = P_CRASKTEAM , 
			CRASKDATE = P_CRASKDATE , 
			CRASKSEQ = P_CRASKSEQ , 
			CRWOTEAM = P_CRWOTEAM , 
			CRWODATE = P_CRWODATE , 
			CRWOSEQ = P_CRWOSEQ , 
			CRREVCONTENT = P_CRREVCONTENT , 
			CRREVDATA = P_CRREVDATA , 
			CRREVSUMMARY = P_CRREVSUMMARY , 
			CRREVAPPROVAL = P_CRREVAPPROVAL , 
			CRREVREASION = P_CRREVREASION , 
			CRREVJKCD1 = P_CRREVJKCD1 , 
			CRREVJKCDNM1 = P_CRREVJKCDNM1 , 
			CRREVNAME1 = P_CRREVNAME1 , 
			CRREVSABUN1 = P_CRREVSABUN1 , 
			CRREVCOMMENT1 = P_CRREVCOMMENT1 , 
			CRREVJKCD2 = P_CRREVJKCD2 , 
			CRREVJKCDNM2 = P_CRREVJKCDNM2 , 
			CRREVNAME2 = P_CRREVNAME2 , 
			CRREVSABUN2 = P_CRREVSABUN2 , 
			CRREVCOMMENT2 = P_CRREVCOMMENT2 , 
			CRREVJKCD3 = P_CRREVJKCD3 , 
			CRREVJKCDNM3 = P_CRREVJKCDNM3 , 
			CRREVNAME3 = P_CRREVNAME3 , 
			CRREVSABUN3 = P_CRREVSABUN3 , 
			CRREVCOMMENT3 = P_CRREVCOMMENT3 , 
			CRREVJKCD4 = P_CRREVJKCD4 , 
			CRREVJKCDNM4 = P_CRREVJKCDNM4 , 
			CRREVNAME4 = P_CRREVNAME4 , 
			CRREVSABUN4 = P_CRREVSABUN4 , 
			CRREVCOMMENT4 = P_CRREVCOMMENT4 , 
			CRREVJKCD5 = P_CRREVJKCD5 , 
			CRREVJKCDNM5 = P_CRREVJKCDNM5 , 
			CRREVNAME5 = P_CRREVNAME5 , 
			CRREVSABUN5 = P_CRREVSABUN5 , 
			CRREVCOMMENT5 = P_CRREVCOMMENT5 , 
			CRREVJKCD6 = P_CRREVJKCD6 , 
			CRREVJKCDNM6 = P_CRREVJKCDNM6 , 
			CRREVNAME6 = P_CRREVNAME6 , 
			CRREVSABUN6 = P_CRREVSABUN6 , 
			CRREVCOMMENT6 = P_CRREVCOMMENT6 , 
			CRREVHIGB = 'C' , 
			CRREVHIDAT = CURRENT_DATE , 
			CRREVHITIM = CURRENT_TIME , 
			CRREVHISAB	= P_CRREVHISAB 
		WHERE CRREVTEAM = P_CRREVTEAM 
		AND CRREVDATE = P_CRREVDATE 
		AND CRREVSEQ = P_CRREVSEQ ; 
  
	END IF ; 
  
	IF P_GUBUN = 'APPROVAL' THEN 
  
		UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
			CRASKTEAM = P_CRASKTEAM , 
			CRASKDATE = P_CRASKDATE , 
			CRASKSEQ = P_CRASKSEQ , 
			CRWOTEAM = P_CRWOTEAM , 
			CRWODATE = P_CRWODATE , 
			CRWOSEQ = P_CRWOSEQ , 
			CRREVCONTENT = P_CRREVCONTENT , 
			CRREVDATA = P_CRREVDATA , 
			CRREVSUMMARY = P_CRREVSUMMARY , 
			CRREVAPPROVAL = P_CRREVAPPROVAL , 
			CRREVREASION = P_CRREVREASION , 
			CRREVJKCD1 = P_CRREVJKCD1 , 
			CRREVJKCDNM1 = P_CRREVJKCDNM1 , 
			CRREVNAME1 = P_CRREVNAME1 , 
			CRREVSABUN1 = P_CRREVSABUN1 , 
			CRREVCOMMENT1 = P_CRREVCOMMENT1 , 
			CRREVJKCD2 = P_CRREVJKCD2 , 
			CRREVJKCDNM2 = P_CRREVJKCDNM2 , 
			CRREVNAME2 = P_CRREVNAME2 , 
			CRREVSABUN2 = P_CRREVSABUN2 , 
			CRREVCOMMENT2 = P_CRREVCOMMENT2 , 
			CRREVJKCD3 = P_CRREVJKCD3 , 
			CRREVJKCDNM3 = P_CRREVJKCDNM3 , 
			CRREVNAME3 = P_CRREVNAME3 , 
			CRREVSABUN3 = P_CRREVSABUN3 , 
			CRREVCOMMENT3 = P_CRREVCOMMENT3 , 
			CRREVJKCD4 = P_CRREVJKCD4 , 
			CRREVJKCDNM4 = P_CRREVJKCDNM4 , 
			CRREVNAME4 = P_CRREVNAME4 , 
			CRREVSABUN4 = P_CRREVSABUN4 , 
			CRREVCOMMENT4 = P_CRREVCOMMENT4 , 
			CRREVJKCD5 = P_CRREVJKCD5 , 
			CRREVJKCDNM5 = P_CRREVJKCDNM5 , 
			CRREVNAME5 = P_CRREVNAME5 , 
			CRREVSABUN5 = P_CRREVSABUN5 , 
			CRREVCOMMENT5 = P_CRREVCOMMENT5 , 
			CRREVJKCD6 = P_CRREVJKCD6 , 
			CRREVJKCDNM6 = P_CRREVJKCDNM6 , 
			CRREVNAME6 = P_CRREVNAME6 , 
			CRREVSABUN6 = P_CRREVSABUN6 , 
			CRREVCOMMENT6 = P_CRREVCOMMENT6 
		WHERE CRREVTEAM = P_CRREVTEAM 
		AND CRREVDATE = P_CRREVDATE 
		AND CRREVSEQ = P_CRREVSEQ ; 
  
		IF P_APPROVAL = '' THEN 
  
			SET P_APPROVAL = '0' ; 
  
		END IF ; 
  
		 -- 결재일자와 시간 업데이트 
		 -- 요청자 결재일자 및 시간 업데이트 
		IF P_COUNT = ( INT ( P_APPROVAL ) + 1 ) THEN 
  
			SET V_CRREVAPPSABUN = '' ;  -- 승인사번 
			IF P_COUNT = 1 THEN 
  
				SET V_CRREVAPPSABUN = P_CRREVSABUN1 ;  -- 승인사번 
				UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
					CRREVDATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					CRREVTIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			ELSEIF P_COUNT = 2 THEN 
  
				SET V_CRREVAPPSABUN = P_CRREVSABUN2 ;  -- 승인사번 
				UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
					CRREVDATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					CRREVTIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			ELSEIF P_COUNT = 3 THEN 
  
				SET V_CRREVAPPSABUN = P_CRREVSABUN3 ;  -- 승인사번 
				UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
					CRREVDATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					CRREVTIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			ELSEIF P_COUNT = 4 THEN 
  
				SET V_CRREVAPPSABUN = P_CRREVSABUN4 ;  -- 승인사번 
				UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
					CRREVDATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					CRREVTIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			ELSEIF P_COUNT = 5 THEN 
  
				SET V_CRREVAPPSABUN = P_CRREVSABUN5 ;  -- 승인사번 
				UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
					CRREVDATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					CRREVTIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			ELSEIF P_COUNT = 6 THEN 
  
				SET V_CRREVAPPSABUN = P_CRREVSABUN6 ;  -- 승인사번 
				UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
					CRREVDATE6 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
					CRREVTIME6 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			END IF ; 
  
  
  
			 -- 최종 전결자가 결재 했을 경우 
			 -- 검토자와 검토완요일자를 업데이트 함 
			UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
				CRREVAPPDATE = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
				CRREVAPPTIME = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) , 
				CRREVAPPSABUN = V_CRREVAPPSABUN 
			WHERE CRREVTEAM = P_CRREVTEAM 
			AND CRREVDATE = P_CRREVDATE 
			AND CRREVSEQ = P_CRREVSEQ ; 
  
  
  
		ELSE 
  
			IF P_COUNT <> INT ( P_APPROVAL ) THEN 
  
				IF P_APPROVAL = '0' THEN 
  
					UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
						CRREVDATE1 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						CRREVTIME1 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
					AND CRREVSEQ = P_CRREVSEQ ; 
  
				ELSEIF P_APPROVAL = '1' THEN 
  
					UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
						CRREVDATE2 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						CRREVTIME2 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
					AND CRREVSEQ = P_CRREVSEQ ; 
  
				ELSEIF P_APPROVAL = '2' THEN 
  
					UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
						CRREVDATE3 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						CRREVTIME3 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
					AND CRREVSEQ = P_CRREVSEQ ; 
  
				ELSEIF P_APPROVAL = '3' THEN 
  
					UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
						CRREVDATE4 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						CRREVTIME4 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
					AND CRREVSEQ = P_CRREVSEQ ; 
  
				ELSEIF P_APPROVAL = '4' THEN 
  
					UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
						CRREVDATE5 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						CRREVTIME5 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
					AND CRREVSEQ = P_CRREVSEQ ; 
  
				ELSEIF P_APPROVAL = '5' THEN 
  
					UPDATE PSSCMLIB . PSM_CHANGEREV_DOC SET 
						CRREVDATE6 = REPLACE ( CHAR ( CURRENT_DATE ) , '-' , '' ) , 
						CRREVTIME6 = REPLACE ( CHAR ( CURRENT_TIME ) , '.' , '' ) 
					WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
					AND CRREVSEQ = P_CRREVSEQ ; 
  
				END IF ; 
  
			END IF ; 
  
		END IF ; 
  
		 
  
  
		MAIN : BEGIN  -- 실행부 
			DECLARE REFCURSOR CURSOR WITH RETURN FOR 
				 
				SELECT 
					P_GUBUN AS GUBUN , 
					CRREVCONTENT , 
					CRREVDATA , 
					CRREVSUMMARY , 
					CRREVAPPROVAL , 
					CRREVREASION , 
					CRREVDATE1 , 
					CRREVTIME1 , 
					CRREVDATE2 , 
					CRREVTIME2 , 
					CRREVDATE3 , 
					CRREVTIME3 , 
					CRREVDATE4 , 
					CRREVTIME4 , 
					CRREVDATE5 , 
					CRREVTIME5 , 
					CRREVDATE6 , 
					CRREVTIME6 , 
					CRREVSABUN1 , 
					CRREVSABUN2 , 
					CRREVSABUN3 , 
					CRREVSABUN4 , 
					CRREVSABUN5 , 
					CRREVSABUN6 , 
					/* 사인 */ 
					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN1
					) AS SOIMGNAME1, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN1
					) AS SOIMGSIZE1, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN1
					) AS SOIMGSIGN1,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN2
					) AS SOIMGNAME2, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN2
					) AS SOIMGSIZE2, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN2
					) AS SOIMGSIGN2, 

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN3
					) AS SOIMGNAME3, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN3
					) AS SOIMGSIZE3, 
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN3
					) AS SOIMGSIGN3,

					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN4
					) AS SOIMGNAME4, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN4
					) AS SOIMGSIZE4,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN4
					) AS SOIMGSIGN4,


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN5
					) AS SOIMGNAME5, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN5
					) AS SOIMGSIZE5,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN5
					) AS SOIMGSIGN5,


					(SELECT
						FILE_NAME
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN6
					) AS SOIMGNAME6, 
					(SELECT
						FILE_SIZE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN6
					) AS SOIMGSIZE6,
					(SELECT
						ATTACH_BYTE
					 FROM PSSCMLIB.PSM_CMN_ATTACH
					 WHERE ATTACH_TYPE = 'SG'
					 AND   ATTACH_NO = CRREVSABUN6
					) AS SOIMGSIGN6

				FROM PSSCMLIB . PSM_CHANGEREV_DOC 
				WHERE CRREVTEAM = P_CRREVTEAM 
				AND CRREVDATE = P_CRREVDATE 
				AND CRREVSEQ = P_CRREVSEQ ; 
  
			OPEN REFCURSOR ; 
  
		END MAIN ; 
  
	ELSE 
		 -- 저장이면 없음 
		MAIN1 : BEGIN  -- 실행부 
			DECLARE REFCURSOR1 CURSOR WITH RETURN FOR 
  
				SELECT 
					P_GUBUN AS GUBUN 
				FROM SYSIBM . SYSDUMMY1 ; 
  
			OPEN REFCURSOR1 ; 
  
		END MAIN1 ; 
  
	END IF ; 
  
	 -- 참조자 저장 
	CALL PSSCMLIB . PSM_REFERENCE_UPDATE ( 'A' , 'RE' , P_CRREVTEAM || P_CRREVDATE || DIGITS ( P_CRREVSEQ ) , P_RESABUN , P_RENAME , P_CRREVHISAB ) ; 
  
	 --CALL PSSCMLIB.PSM_REFERENCE_UPDATE ('A', 'RE', P_CRREVTEAM||P_CRREVDATE||DIGITS(P_CRREVSEQ)||P_CRASKTEAM||P_CRASKDATE||DIGITS(P_CRASKSEQ)||P_CRWOTEAM||P_CRWODATE||DIGITS(P_CRWOSEQ), P_RESABUN, P_RENAME, P_CRREVHISAB); 
END P1;

call PSSCMLIB.PSM_PSM4031_CHANGEREV_DOC_APPROVAL('A20000','20231107',001,'A20000','20231016',001,'A20000','20230925',001,'704 화물 변경','MSDS 등.....','내용 테스트','Y','사유 테스트','0311-M','김상권','130','과장','','','','','','','','','','','','','','','','','','','','','','','','','','','0311-M','','',1,'0','SAVE')