--DROP PROCEDURE PSSCMLIB.PSM_WORKORDER_IMMED_UPT;
  
CREATE PROCEDURE PSSCMLIB.PSM_WORKORDER_IMMED_UPT ( 
	IN P_WOIMMEDDATE   VARCHAR(8),
	IN P_WOIMMEDSABUN  VARCHAR(6),
	IN P_WOIMMEDTEXT   VARCHAR(200),
	IN P_WOORTEAM      VARCHAR(6),
	IN P_WOORDATE      VARCHAR(8),
	IN P_WOSEQ         NUMERIC(3,0))
	LANGUAGE SQL 
	SPECIFIC PSSCMLIB.PSM_WORKORDER_IMMED_UPT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 

	UPDATE PSSCMLIB.PSM_WorkOrder SET
		WOIMMEDDATE     = P_WOIMMEDDATE,
		WOIMMEDSABUN    = P_WOIMMEDSABUN,
		WOIMMEDTEXT     = P_WOIMMEDTEXT
	WHERE WOORTEAM = P_WOORTEAM
	AND   WOORDATE = P_WOORDATE
	AND   WOSEQ    = P_WOSEQ;

END P1;