--DROP PROCEDURE PSSCMLIB.PSM_PSM4031_GET_MAX_SEQ;
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4031_GET_MAX_SEQ ( 
	IN P_CRREVTEAM VARCHAR(6),
	IN P_CRREVDATE VARCHAR(8)) 

	DYNAMIC RESULT SETS 1 

P1 : BEGIN
	
	MAIN : BEGIN  -- ½ÇÇàºÎ
		
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 

			SELECT
				VALUE(MAX(CRREVSEQ) + 1, 1) AS CRREVSEQ
			FROM PSSCMLIB.PSM_CHANGEREV_DOC
			WHERE CRREVTEAM = P_CRREVTEAM
			AND   CRREVDATE = P_CRREVDATE;

		OPEN REFCURSOR;

	END MAIN;

END P1;

CALL PSSCMLIB.PSM_PSM4031_GET_MAX_SEQ('A20000', '20231004');