--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	23-06-26 15:18:05 
--  Relational Database:       	S78E0180 
--  Standards Option:          	Db2 for i 
DROP PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_RUN ; 
  
CREATE PROCEDURE PSSCMLIB.PSM_PSM4046_JSACHANGE_DETAIL_RUN ( 
	IN P_JSDWKGUBN VARCHAR(1),
	IN P_JSDPOTEAM VARCHAR(6),
	IN P_JSDPODATE VARCHAR(8),
	IN P_JSDPOSEQ NUMERIC(3,0),
	IN P_JSDDATE VARCHAR(8),
	IN P_JSDMSEQ NUMERIC(3,0),
	IN P_JSDBLASS VARCHAR(2),
	IN P_JSDMLASS VARCHAR(2),
	IN P_JSDSLASS VARCHAR(3),
	IN P_JSDSEQ NUMERIC(3,0),
	IN P_JSDITEMSEQ NUMERIC(3,0))
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 

	P1 : BEGIN  -- 시작 
MAIN : BEGIN  -- 실행부 
LIST : BEGIN  -- 리스트 
		DECLARE REFCURSOR CURSOR WITH RETURN FOR 
			 
		SELECT
		JSDBLASS,
		J1NAME AS JBCODE,
		JSDMLASS,
		J2NAME AS JMCODE,
		JSDSLASS,
		J3NAME AS JSCODE,
		JSDSEQ,
		JSMWKNAME,
		JSDITEMSEQ,
		JSDITEMTEXT,
		JSDTOOLTEXT,
		JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ) || '-JSA' AS FILE_ID_JSA,
		JSDWKGUBN || JSDPOTEAM || JSDPODATE ||  DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ) || '-TOOL' AS FILE_ID_TOOL,
		( SELECT 
			FILE_NAME 
		FROM PSSCMLIB . PSM_CMN_ATTACH 
		WHERE ATTACH_TYPE = 'JJ' 
		AND ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		) AS FILE_NAME_JSA , 
		( SELECT 
			FILE_SIZE 
		FROM PSSCMLIB . PSM_CMN_ATTACH 
		WHERE ATTACH_TYPE = 'JJ' 
		AND ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		) AS FILE_SIZE_JSA , 
		( SELECT 
			ATTACH_BYTE 
		FROM PSSCMLIB . PSM_CMN_ATTACH 
		WHERE ATTACH_TYPE = 'JJ' 
		AND ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		) AS ATTACH_BYTE_JSA , 
		( SELECT 
			FILE_NAME 
		FROM PSSCMLIB . PSM_CMN_ATTACH 
		WHERE ATTACH_TYPE = 'JT' 
		AND ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		) AS FILE_NAME_TOOL , 
		( SELECT 
			FILE_SIZE 
		FROM PSSCMLIB . PSM_CMN_ATTACH 
		WHERE ATTACH_TYPE = 'JT' 
		AND ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		) AS FILE_SIZE_TOOL , 
		( SELECT 
			ATTACH_BYTE 
		FROM PSSCMLIB . PSM_CMN_ATTACH 
		WHERE ATTACH_TYPE = 'JT' 
		AND ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		) AS ATTACH_BYTE_TOOL 
		/* 
		ATT1.FILE_NAME AS FILE_NAME_JSA , 
		ATT1.FILE_SIZE AS FILE_SIZE_JSA, 
		ATT1.ATTACH_BYTE AS ATTACH_BYTE_JSA,
		ATT2.FILE_NAME AS FILE_NAME_TOOL , 
		ATT2.FILE_SIZE AS FILE_SIZE_TOOL, 
		ATT2.ATTACH_BYTE AS ATTACH_BYTE_TOOL
		*/
		FROM PSSCMLIB.PSM_JSACHANGE_DETAIL
		 
		/* 
		LEFT JOIN PSSCMLIB . PSM_CMN_ATTACH AS ATT1
		ON ATT1.ATTACH_TYPE = 'JJ'
		AND ATT1.ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE || DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		LEFT JOIN PSSCMLIB . PSM_CMN_ATTACH AS ATT2
		ON ATT2.ATTACH_TYPE = 'JT'
		AND ATT2.ATTACH_NO = JSDWKGUBN || JSDPOTEAM || JSDPODATE ||  DIGITS(JSDPOSEQ) || JSDDATE || DIGITS(JSDMSEQ) || JSDBLASS || JSDMLASS || JSDSLASS || DIGITS(JSDSEQ) || DIGITS(JSDITEMSEQ)
		*/ 
		LEFT OUTER JOIN PSSCMLIB.PSM_JSACHANGE_MASTER
		ON JSMWKGUBN     = JSDWKGUBN
		AND JSMPOTEAM     = JSDPOTEAM
		AND JSMPODATE     = JSDPODATE
		AND JSMPOSEQ      = JSDPOSEQ
		AND		JSMDATE       = JSDDATE
		AND JSMMSEQ       = JSDMSEQ
		AND JSMBLASS     = JSDBLASS
		AND JSMMLASS     = JSDMLASS
		AND JSMSLASS     = JSDSLASS
		AND JSMSEQ       = JSDSEQ 
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS1
		ON    JSMBLASS = J1CODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS2
		ON    JSMBLASS = J2BCODE
		AND   JSMMLASS = J2MCODE
		LEFT OUTER JOIN PSSCMLIB.PSM_JSA_CLASS3
		ON    JSMBLASS = J3BCODE
		AND   JSMMLASS = J3MCODE
		AND   JSMSLASS = J3SCODE
		WHERE JSDWKGUBN = P_JSDWKGUBN
		AND   JSDPOTEAM = P_JSDPOTEAM
		AND   JSDPODATE = P_JSDPODATE
		AND   JSDPOSEQ  = P_JSDPOSEQ
		AND   JSDDATE   = P_JSDDATE
		AND   JSDMSEQ   = P_JSDMSEQ
		AND   JSDBLASS  = P_JSDBLASS
		AND   JSDMLASS  = P_JSDMLASS
		AND   JSDSLASS  = P_JSDSLASS
		AND   JSDSEQ    = P_JSDSEQ
		AND   JSDITEMSEQ = P_JSDITEMSEQ
					 ; 
  
		OPEN REFCURSOR ; 
  
	END LIST ; 
  
END MAIN ; 
END  ; 